### ISSUE TITLE
Display legend entry items while they are loading on identify results

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1000]
Currently, any loading legend entries are omitted in the identify results (as of PR #999). This was done to prevent errors during code execution on loading legend entries. There may be a better way to handle this so that even loading entries are shown.

**Comment by james-rae** [comment]
Issue 1000 :cake: :fireworks: :dancers: :dash:

**Comment by milesap** [comment]
Done and done
