### ISSUE TITLE
Mercator Projections - Unable to display Point Info when clicking on highlighted map features after zooming

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1008]
Tested on build: http://fgpv.cloudapp.net/demo/v1.0.1-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
for all three major browsers

- Click Zoom to Feature button for any map features in Data Table
- After zooming to it, click on highlighted map point

It displayed "Nothing found" under Point Information panel. It seems "Zoom to Feature" button zoomed to scale of 1m, even the map feature is highlighted and visible, clicking on it didn't bring Point Info to user.

![image](https://cloud.githubusercontent.com/assets/18723160/17222525/d765e480-54c6-11e6-9269-703cd7438a25.png)

**Comment by cynngah** [comment]
Seems to break at certain zoom levels as demonstrated in gif below
Zooming out allows click identify to work as normal.

![](http://i.imgur.com/v20jRsM.gif)

**Comment by cynngah** [comment]
Seems to be an issue with click buffer not being large enough on lower zoom levels.

**Comment by mweech** [comment]
Adjusting the buffer based on zoom level makes sense to me.
