### ISSUE TITLE
Overview map not changed when switching to Blank Map

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1009]
Tested on build: http://fgpv.cloudapp.net/demo/v1.0.1-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Overview map will still display the previous base map after it switched to Blank Map.

![image](https://cloud.githubusercontent.com/assets/18723160/17223626/71f3d0e4-54cb-11e6-8f75-300d965d47c7.png)

**Comment by mweech** [comment]
An overview map is not worthwhile without a basemap.  This should not be made blank.
