### ISSUE TITLE
chore(build): deploy to dev task

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#101]
I think we need a task to deploy the current build to dev somewhere. Might be useful to quickly show the build to people.

**Comment by mweech** [comment]
We need to be able to deploy the Viewer to a dev server on an internal GC network to better test catalogue integration re: metadata and catalogue URL registration with RCS.

**Comment by alyec** [comment]
Proposal:
We don't actually need to deploy the viewer internally, but we do need an internal proxy (EC can probably use Dan's, but if NRCan needs a similar setup they will have to setup a separate instance).  We also need a way to point the viewer to a proxy at runtime and maybe save the setting in localStorage so it persists and doesn't need to be reset on every load of the viewer.

**Comment by mweech** [comment]
Original issue text: "I think we need a task to deploy the current build to dev somewhere. Might be useful to quickly show the build to people."

**Comment by mweech** [comment]
will create a different issue to implement something along the lines of aly's comment above.
