### ISSUE TITLE
No query results returned when clicking map points for certain user added WMS layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1010]
Tested on build: http://fgpv.cloudapp.net/demo/v1.0.1-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Test Data URL: http://geoportal.gc.ca/arcgis/services/Arctic_Voyage_Planning_Guide_ENG/MapServer/WmsServer

User added multiple layers through the test data URL. There are some visible map points on the map, but click on them didn't display any Point Information, even this layer allows query.

![image](https://cloud.githubusercontent.com/assets/18723160/17226762/f39dbfb2-54d8-11e6-97b9-b8e5b47c1664.png)

**Comment by jolevesq** [comment]
It is not just the identify, there is no datagrid as well. Nothing happen when ww click on the layer.

**Comment by ChrisLatRNCan** [comment]
Here's what cause the problem: the legendEntry.featureInfoMimeType is not defined.
It is explicitly defined when the ogcWms layer is load through a config file but it is not in the case of a user imported service.

**Comment by ChrisLatRNCan** [comment]
If in GetFeatureInfo section of Capabilities XML we get format (featureInfoMimeType) we don't cope with, the identifyOgcWmsLayer won't work. So I have to search for the first supported format through the ones mentionned in the XML.
Here's an example from http://geo.weather.gc.ca/geomet/:
`<Format>application/vnd.ogc.se_xml</Format>` :hankey:
`<Format>application/vnd.ogc.gml</Format>` :hankey: 
`<Format>text/plain</Format>` :+1:

**Comment by IsabellaPan** [comment]
Nov 29
Verified with build: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=Airports,ZoomScale,CESI_Other,NPRI_CO,mb_colour
