### ISSUE TITLE
Invisible layers are not set to be invisible at load

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1012]
When a layer object is generated, it's initial visibility is not being passed to the object constructor.  It appears the visibility is set on the layer later on, likely during some type of binding to the Legend control.

This makes for an inefficient load, as a visible layer will trigger an `update-start` event, causing data to be downloaded from the server.  Ideally, if the user never turns on an invisible layer, the map should never request any geometry for it.
It also causes the layer to appear briefly until the bindings can take place.

E.g. load `index-one.html` with only the following object in the `layers` array of `config.en-CA.json`

```
{
    "id":"powerplant100mw",
    "name": "Power Plants, 100 MW or more",
    "layerType":"esriFeature",
    "url":"http://geoappext.nrcan.gc.ca/arcgis/rest/services/NorthAmerica/energy_infrastructure_of_north_america_en/MapServer/7",
    "options": { "visibility": { "value": false } }
}
```

You will see the layer for a few seconds before it is set to invisible.  You can also see the features downloading if you monitor the web traffic.

At a brief glance, the `makeLayerConfig` function ([source](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.0.1-rc1/src/app/geo/layer-record.class.js#L113)) or it's overloads should be setting the `visible` property on the return object.

**Comment by AleksueiR** [comment]
Yeap, adding `opacity` and `visible` to the config works, although then invisible layers never load because of #980.
```js
return {
    id: this.config.id,
    opacity: this.config.options.opacity.value,
    visible: this.config.options.visibility.value
};
```

Would there also be a problem with all children of a dynamic layer showing up at the initial load until their visibility is set and some are hidden by the config values?

**Comment by james-rae** [comment]
The never load issue should be fixed soon (I may push it today as Aly is still away).

The dynamic layer case could do with some extra research, but the performance hit is much less as it only generates an image -- it doesn't download a data set.
