### ISSUE TITLE
Tab issue in IE11

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#1031]
In chrome and firefox a tab press will send you from button to button.

In IE11 a tab press will send you from a button to the icon within the button. This means that double the key-presses are needed to navigate the controls and half the time the focus isn't on a usable element.

Notice that SVGs are targets in focus/blur events:
![ie_focus_svg](https://cloud.githubusercontent.com/assets/2285779/17407855/dcd389f2-5a36-11e6-806d-46192435a3ef.gif)

**Comment by milesap** [comment]
It seems the only workaround for IE 11 is to set `focusable` to false, as in `<svg focusable="false"></svg>` as posted on [stackoverflow](http://stackoverflow.com/questions/18646111/disable-onfocus-event-for-svg-element). If this is the case, should we manually add this property to all svg elements, or dynamically add this at run time with jQuery? I'm thinking the latter unless it is not performant. Thoughts?

**Comment by AleksueiR** [comment]
Make a button decorator, similar to our [menuItem decorator](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/ui/common/menuItem.decorator.js), to add the `focusable="false"` attribute to the SVG element when it's rendered.
