### ISSUE TITLE
Cannot remove failed layer placeholder after basemap switching

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1032]
![no_remove_placeholder_after_basemap_switching](https://cloud.githubusercontent.com/assets/2285779/17412419/a9d9c1d8-5a4a-11e6-8336-b26b398b0b60.gif)

When trying to remove a failed placeholder, the following error is displayed in the console:

> core.js:12798 TypeError: Cannot read property 'remove' of undefined
>     at controller.removeLayer [as action](core.js:86348)
>     at fn (eval at compile (core.js:13643), <anonymous>:4:406)
>     at expensiveCheckFn (core.js:14625)
>     at callback (core.js:24093)
>     at Scope.$eval (core.js:16374)
>     at Scope.$apply (core.js:16474)
>     at HTMLButtonElement.<anonymous> (core.js:24098)
>     at HTMLButtonElement.dispatch (jquery-2.2.1.min.js:3)
>     at HTMLButtonElement.r.handle (jquery-2.2.1.min.js:3)

**Comment by cynngah** [comment]
error only appears after the second time you click the trash bin because the layer has already been "removed"

**Comment by cynngah** [comment]
Stuff hashed out from code review:

- Has to do with how bookmark goes through legendentry instead of layerrecords
- Going through legendentry instead of layerrecords might screw with the bindings so iterate through layerRegistry instead of the legend on map reload.
- Also make something in layerregistry to keep track of entry order in the toc


- Also need to move bookmark from core into geo

**Comment by ChrisLatRNCan** [comment]
Some tests:

Lambert ->Mercator->DELETE = :hankey:
Lambert A ->Mercator->Lambert A->DELETE= :hankey:
Lambert A ->Mercator->Lambert B->DELETE= :hankey:
Lambert A ->Lambert B->DELETE=:+1:

So switching to Mercator is problematic.

**Comment by AleksueiR** [comment]
@ChrisLatRNCan are you still working on this?

**Comment by ChrisLatRNCan** [comment]
I'm just coming back. So yes, if the problem is still there

**Comment by ChrisLatRNCan** [comment]
Not a lot of progress on that one.

**Comment by mweech** [comment]
to be addressed following implementation of #1275

**Comment by AleksueiR** [comment]
No longer valid in 2.x.
