### ISSUE TITLE
IE11 - Missing Chevrons & Search icon on top of FGP Visualiser

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1039]
Tested build: http://fgpv.cloudapp.net/demo/v1.0.2-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

![image](https://cloud.githubusercontent.com/assets/18723160/17485765/9a0a0e88-5d5c-11e6-8967-78d3951088cf.png)

**Comment by AleksueiR** [comment]
Host page problem ([IE11 problem really](http://stackoverflow.com/questions/29379602/in-ie11-using-pseudo-element-before-and-displaytable-cell-and-glyphicons-cont)). The chevron icons don't show up on WET's sample pages [here](http://wet-boew.github.io/wet-boew/index-en.html) and [here](http://wet-boew.github.io/themes-dist/GCWeb/docs/ref/GCWeb/GCWeb-en.html) when viewed in IE11 as well.
