### ISSUE TITLE
Zoom To Feature not working under Point Info panel for use added file based layers

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1041]
Tested build: http://fgpv.cloudapp.net/demo/v1.0.2-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
User added shape file: ne_10m_ports.zip, or CSV file: rc_cdr.csv

No responding when clicking magnifying glass icon highlighted in below screenshots.

![image](https://cloud.githubusercontent.com/assets/18723160/17490014/e76d8e4a-5d6e-11e6-9595-1bfd577f6970.png)

![image](https://cloud.githubusercontent.com/assets/18723160/17490190/a34d8688-5d6f-11e6-8975-433c5ec7c80f.png)

**Comment by james-rae** [comment]
The identify module was passing the object id in string form to the details panel. This would cause the local search by object id to fail; the code would then attempt a server lookup, which would also fail as it is a file based layer.

Should see a minor improvement in efficiency in general, as all feature layers were hitting the server on every lookup prior to this patch.
