### ISSUE TITLE
IE11 - Need Refresh (F5) to load FGP Visualiser

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1043]
Tested build: http://fgpv.cloudapp.net/demo/v1.0.2-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

When loaded directly from above URL, it just displayed blank box as below screenshot. Only after Refresh button was clicked, then the map could be loaded.

![image](https://cloud.githubusercontent.com/assets/18723160/17495375/d917b7cc-5d86-11e6-996a-588364e16179.png)

**Comment by IsabellaPan** [comment]
To reproduce, please clear IE cache first.

**Comment by alyec** [comment]
This will likely be fixed along with #1042
