### ISSUE TITLE
User added ESRI Ozone layer - Zoom To Feature not working in Datagrid for all zoom levels

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1046]
Tested build: http://fgpv.cloudapp.net/demo/v1.0.2-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
ESRI Ozone layer URL: http://sncr01wbingsdv1.ncr.int.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This issue was found in all three major browsers: Firefox, Chrome and IE11.
1. After adding ESRI Ozone layer, it seems all zoom levels have eye icon displayed. Cannot identify which layers are out of scale.
2. Open Datagrid for any zoom levels, Zoom To Feature button is not responding for any map points. Screenshot see below.

![image](https://cloud.githubusercontent.com/assets/18723160/17528743/95d1ae06-5e3e-11e6-9fe5-ee2c4935ca85.png)

**Comment by IsabellaPan** [comment]
Browser version:
Firefox: 46.0
Chrome: Version 52.0.2743.116
IE11: Version 11.0.9600.18376, Update Version: 11.0.33 (KB3170106)

**Comment by james-rae** [comment]
Very similar to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/953 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1019 .  Could not reproduce on my PC.

**Comment by james-rae** [comment]
Update - can reproduce, but only if I select the "Ozone" entry from the import wizard, and not the four "zoom level" leaf layers.

**Comment by james-rae** [comment]
Zoom controls were fixed but visible-eye-controls are still not working
