### ISSUE TITLE
Import File Wizard - Continue button disabled by default in step 3 (Configure layer)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1067]
Tested build: http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Test Data
GeoJSON: happy.json 
CSV: rc_cdr.csv 
Shapefile: 
[ne_10m_ports.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/430822/ne_10m_ports.zip)

When the Import File Wizard went to step 3 (Configure layer), by default there are some values populated in related fields, but Continue button is disabled for all three kinds of files.

For CSV file, by changing the value under Latitude Field and Longitude Field could enable the Continue button. And for Shapefile, Continue button could be enabled by changing Primary Field value, but the layer was still not added successfully, instead it displayed "Loading layer..." and never ending.

![image](https://cloud.githubusercontent.com/assets/18723160/17865152/18a6d8d0-686f-11e6-8916-62ec6ab6645c.png)

![image](https://cloud.githubusercontent.com/assets/18723160/17865192/4b1dd4da-686f-11e6-83b4-415de24564ec.png)

![image](https://cloud.githubusercontent.com/assets/18723160/17865328/1a98c864-6870-11e6-944a-19bda6734900.png)

**Comment by mweech** [comment]
this needs to be split into two different bug reports.  one for the continue button issue and another for the layer loading issue.

**Comment by IsabellaPan** [comment]
OK Mike, I am writing another bug report for layer loading issue now

**Comment by IsabellaPan** [comment]
[https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1103](url)

**Comment by AleksueiR** [comment]
Angular Material issue: https://github.com/angular/material/issues/9124

**Comment by AleksueiR** [comment]
This issue seems to be solved in Angular Material 1.1.0. I think should either roll back to 1.0.4 or update again.
