### ISSUE TITLE
Blank Map selector not responding when switching from another gallery

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1071]
Tested build: http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

This issue refers to two scenarios:
1. From any base map in Lambert gallery, select Blank Map in Mercator Maps gallery.
2. From any base map in Mercator gallery, select Blank Map in Lambert Maps gallery.

![image](https://cloud.githubusercontent.com/assets/18723160/17869505/95410002-6881-11e6-9ac2-797f9c02760a.png)

**Comment by spencerwahl** [comment]
Fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1070

**Comment by milesap** [comment]
Tested and working - #1070 has merged

**Comment by IsabellaPan** [comment]
This is broken again in build: http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

In this case, Get Link and backtoCart buttons also not reponding.

**Comment by james-rae** [comment]
Will ensure this is corrected when https://github.com/fgpv-vpgf/fgpv-vpgf/issues/926 is commited (and will re-close when verified)

**Comment by IsabellaPan** [comment]
Nov 16 verified with build 
http://fgpv.cloudapp.net/demo/users/milesap/build-1.4.0-6/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Barley
