### ISSUE TITLE
Point Info Panel -Incorrect display of Railway Network results 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1072]
Tested on :http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,FeatureServer,ZoomScale,Polygons

Linked to :[https://github.com/fgpv-vpgf/fgpv-vpgf/issues/643](url)

For some reason, Railway Network results are always displayed even when there are no railway points in the map. Clicking on the point returns empty results.Please investigate

![screenhunter_2399 aug 22 16 07](https://cloud.githubusercontent.com/assets/18539315/17869805/e7c946c6-6882-11e6-882d-bc97853cd063.jpg)

**Comment by mweech** [comment]
This is not a bug.  The challenge here is that the WMS layer is returning a single result at all times, in this case to indicate that nothing is found.  The viewer should not be responsible for parsing the results of the WMS layer and trying to determine if there is a legitimate result to be displayed or if the service is returning a result that is essentially null.
