### ISSUE TITLE
feat(ui): add support for radio-button style visibility toggles in toc

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#108]
As implemented in GcViz. Restricts view of only one layer per group at a time (the group itself still can be turned off by the group toggle though).
Apart from switch logic, need visual clues to indicate linked layers.

**Comment by jolevesq** [comment]
In GCViz, we have a border around the group.

**Comment by mweech** [comment]
@AleksueiR is this issue a duplicate of a task elsewhere in your thematic map work?

**Comment by AleksueiR** [comment]
I think this is original one.
