### ISSUE TITLE
Missing Labels for Data grid options  in Firefox

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1104]
Tested on build :http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Please fix the missing labels. Issue only in Firefox

![screenhunter_2402 aug 23 14 28](https://cloud.githubusercontent.com/assets/18539315/17904935/4c9a8224-693f-11e6-9947-d481731541ad.jpg)

**Comment by AleksueiR** [comment]
This was mostly solved by updating Angular Material to 1.1.0.
