### ISSUE TITLE
Unable to Import a Raster Layer as the existing Service Types does not identify the layer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1109]
Tested on build: http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.htm

Unable to Import a Raster layer. Should this be under supported Service Type?

Tested using the below service url:
http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/0

![screenhunter_2404 aug 24 11 42](https://cloud.githubusercontent.com/assets/18539315/17937423/08a490b2-69f0-11e6-8168-2c6aa1667529.jpg)

**Comment by mweech** [comment]
Viewer will only accept the layer if pasted without the layer ID, at which point the viewer identifies it as a Dynamic Layer.  The User Added layer dialog should look at the service property and be able to handle this scenario.
