### ISSUE TITLE
Unhandled Type error when resizing datatable

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1115]
Steps:
- Open datapanel
- Maximize panel
- Return to split view
- Observe error in the console

Error is triggered here: [src/app/ui/filters/filters-default.directive.js#L504](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/filters/filters-default.directive.js#L504).

> core.js:12798 TypeError: u.table.containers is not a function
>     at t.l [as draw](core.js:95783)
>     at core.js:95644
>     at p.$broadcast (core.js:16697)
>     at core.js:98484
>     at l (core.js:15112)
>     at core.js:15128
>     at p.$eval (core.js:16374)
>     at p.$digest (core.js:16190)
>     at core.js:16413
>     at i (core.js:5764)

**Comment by bkutty** [comment]
No error messages in console. tested build- v1.4.0-7
