### ISSUE TITLE
feat(ui): create add/import layer ui component

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#112]
- [x] Build stepper
- [x] Build layer import from a local file part
- [x] Build layer import from a network file / service part
- [x] Add trigger to the app bar

**Comment by dan-bowerman** [comment]
Mostly done, last part is blocked by interrogation functions from GeoAPI (#182)

**Comment by AleksueiR** [comment]
No update.

**Comment by AleksueiR** [comment]
No update.

**Comment by AleksueiR** [comment]
- [ ] unify ways layers are added to the map (layers can be added from the config, RCS or by user (services and files), and in each case information supplied differs PR # [to be added]

**Comment by mweech** [comment]
Will be PR'd as part of #611 and #612
