### ISSUE TITLE
bug(data): not able to get metadata content

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1126]
When I try to get the metadata for any of the Eco Geo layers I have this result:

<img width="753" alt="screen shot 2016-08-31 at 9 53 44 am" src="https://cloud.githubusercontent.com/assets/3472990/18131515/3351defc-6f61-11e6-9f2d-fb3b66453d52.png">

<img width="1276" alt="screen shot 2016-08-31 at 9 54 20 am" src="https://cloud.githubusercontent.com/assets/3472990/18131533/4625d7e0-6f61-11e6-88b4-0e359d12ab48.png">

I saw in your demo that it works but from NRCan network and from home it didn't.

**Comment by mweech** [comment]
The metadata record is using an internal catalogue dev instance.  Unfortunately there doesn't exist one that is accessible to everyone.
