### ISSUE TITLE
 IE 11 Full Screen mode - Scroll bar overlapped with Side Tool bar and overview map

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1132]
Tested build URL: http://fgpv.cloudapp.net/demo/users/AleksueiR/github-fix/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

See below screenshot.

![w](https://cloud.githubusercontent.com/assets/2285779/18140462/9e868976-6f83-11e6-8fb2-000df3730132.png)

**Comment by ChrisLatRNCan** [comment]
As mentionned here [https://github.com/twbs/bootstrap/issues/18543](url) 
putting -ms-overflow-style: scrollbar in the body fix the problem.

**Comment by ChrisLatRNCan** [comment]
I put the modif in _special.scss so the class won't be included as fgpv.body in which case the -ms-overflow-style has no effect.
