### ISSUE TITLE
Get Link not loading any map points

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1138]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.2.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
for all three major browsers

Get Link URL only loaded base map, all layers in original map appeared blank under Legend. 
![image](https://cloud.githubusercontent.com/assets/18723160/18179645/7502891e-7051-11e6-8486-45d98301b18f.png)

**Comment by james-rae** [comment]
Can reproduce the issue on `v1.2.0-rc1` but not on `v1.2.0` .  Possible that https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1068 solved whatever was causing this.
