### ISSUE TITLE
Handle Race Condition on Opening Data Grid with Screen Reader

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1145]
Datatable "no data" error message is read right away after the panel opens and before the data is loaded.

**Comment by AleksueiR** [comment]
What exactly was the problem here?

**Comment by milesap** [comment]
Tested various layers using `index-one.html` and `index-fgp-en.html` with NVDA screen reader - could not replicate this bug. Reviewed code for datatable creation and drawing, seems datatable is getting data when it is created, no delays/promises which would indicate this problem.

Also noticed the screen reader does not automatically start reading the data grid when it opens, I need to mouse over it.
