### ISSUE TITLE
Allow Help Section to be Read by Screen Reader

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1146]

**Comment by AleksueiR** [comment]
__Update:__
Help content can be read by the screen reader in the Full-Screen mode. This is likely connected to Angular Material randomly adding `aria` tags to elements when any dialog is opened.

**Comment by AleksueiR** [comment]
NVDA works in two modes: browse and focus. The browse mode is for documents (all content is flattened) and is used on html pages. The focus mode turns on when the user needs to interact with some controls (on a web page for example). NVDA switches between these modes automatically as you tab through the page (tabbing to a control turns on the focus mode; tabbing to a text block turns on the browse mode). Sometimes it doesn’t switch correctly for me though, as with the Help section. When you tab to the help dialog, NVDA seems to stuck in the focus mode and reads only the top heading and the close button. Switching it to the browse mode at this points works – “NVDA key + Space” (toggles browse mode). Pressing “NVDA key + Num 6” moves to the next line. This way you can access the help content.
