### ISSUE TITLE
Add Notes to Documentation Section Regarding Host Page Responsibilities for WCAG Compliance

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1149]

**Comment by milesap** [comment]
Items pulled from #1074:
- "skip to content" link
- page title
- sitemap
- switching languages in RAMP

**Comment by milesap** [comment]
[Host Page Responsibilities for WCAG Compliance](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Host-Page-Responsibilities-for-WCAG-Compliance)
