### ISSUE TITLE
Add Language Switching when in Fullscreen Application mode

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1150]

**Comment by jolevesq** [comment]
@AleksueiR do you already have an idea where you want this button to be? it can be just beside the appbar? If you already have a mockup for this let me know.

**Comment by AleksueiR** [comment]
### Option 1

A drop down menu is added to the side navigation panel where the user can switch the language of the application. The currently selected language is highlighted.

#### Pro:

Clean layout (you see languages only if you need them and you don't see stuff that is irrelevant for majority of users)

#### Con:

The word “Language”, which is used for the drop down button, might not mean anything to users when shown in a different from their own language. 

![](https://i.imgur.com/nVuYrHG.png)

[__Demo here__](http://fgpv.cloudapp.net/demo/users/jolevesq/1150-langswitch/samples/index-one.html)



### Option 2

A section with available languages is added to the side menu when the user can change the language of the application. The currently selected language is highlighted.

#### Pro:

Everyone should be able to recognize the name of the their own language when spelled in that language. 

#### Cons:

Takes up more space (might turn into a somewhat long section if many languages are added).

All other languages shown in the menu except user's preferred language mean nothing to them and add visual clutter to the menu.

| ![1](https://cloud.githubusercontent.com/assets/2285779/18548676/046121f8-7b18-11e6-83a8-cc19ff1e0806.png) | ![2](https://cloud.githubusercontent.com/assets/2285779/18548675/0460d950-7b18-11e6-8181-aca9e2b5c8df.png) |
| ---------------------------------------- | ---------------------------------------- |

**Comment by mweech** [comment]
^ Option 2

**Comment by AleksueiR** [comment]
The icon Google is using in their language menu
![](https://i.imgur.com/2LRnLXW.png)
is the [international language icon](http://www.languageicon.org/)
![](http://www.languageicon.org/icon.png)
and it was designed to indicate language switching:
> We wanted to create a universal icon which webmasters could use without hassle to use in their projects, which the audience could identify easily regardless of their origin or language.

We can add this to the Option 1 drop down label.

**Comment by jolevesq** [comment]
👍 and my preference goes to option 1

**Comment by AleksueiR** [comment]
Option 1
