### ISSUE TITLE
Provide Basic Text Output when Viewing with an old Browser

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1152]
Browsers that don't support the visualization, like text based browsers such as Links or Lynx.

**Comment by milesap** [comment]
Blocked with #1144

**Comment by milesap** [comment]
Detect if javascript is enabled - if not display a warning. See [common issues](http://stackoverflow.com/questions/2170484/shouldnt-we-use-noscript-tag) with the `noscript` tag. Look into having the warning as a static element (not inside a `noscript` tag) then try to hide it with javascript as a workaround.
