### ISSUE TITLE
Design UI for Image Export Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1156]

**Comment by AleksueiR** [comment]
|              Export (map view)                            |                 Export (legend view)                         |         Export (medium/small layout)                                 |
| ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| ![a04 - export - p0](https://cloud.githubusercontent.com/assets/2285779/18364073/f00c896e-75da-11e6-8743-6ee4a86150dc.png) | ![a04 - export - p1](https://cloud.githubusercontent.com/assets/2285779/18364075/f018e7f4-75da-11e6-8734-77f274074723.png) | ![a04 - export - p2](https://cloud.githubusercontent.com/assets/2285779/18364074/f01876d4-75da-11e6-85e3-a098997eadf7.png) |
