### ISSUE TITLE
Merge Map Image with Client Side Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1160]
- [ ] User Added layers
- [ ] Future usage of annotation layers

**Comment by mweech** [comment]
Johann to determine if this is still necessary following review of how it was previously implemented in NRCAN.

**Comment by jolevesq** [comment]
From my first test, there is a cors problem with user added layer and the export map. I will have to dig deeper because it works in GCViz when I add CSV. Maybe JSON is different.

**Comment by jolevesq** [comment]
If I use the proxy we use in GCViz, I am able to have JSON user added layer on the print export. Do we want to use a proxy or we prefer the approach you had with RAMP?

<img width="1468" alt="screen shot 2016-09-22 at 8 42 37 am" src="https://cloud.githubusercontent.com/assets/3472990/18748514/9ff445ea-80a0-11e6-8486-2d5e4a12fc87.png">

**Comment by AleksueiR** [comment]
Does this approach works with rather large files like [this one](https://fgpdoc.zz9.ca/index.php/s/gpR36PsHCZMJSrF)? Are there limits on how much user-added data you can send to the print service to generate an image?

**Comment by jolevesq** [comment]
I am not able to load from the url. I hate cors!

```XMLHttpRequest cannot load http://geoappext.nrcan.gc.ca/php/proxy.ashx?https://fgpdoc.zz9.ca/index.php/s/gpR36PsHCZMJSrF/521.csv. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access```

**Comment by AleksueiR** [comment]
Can you download it on your computer and add locally then?
[52I.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/487375/52I.zip)

**Comment by jolevesq** [comment]
Yes, but I have this error ```gapi.js:22210 Uncaught (in promise) TypeError: Cannot read property 'geometry' of undefined(…)```

**Comment by AleksueiR** [comment]
Ah, it's this issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1206.

**Comment by jolevesq** [comment]
Is this solved?

**Comment by AleksueiR** [comment]
Almost. Will PR the fix in five minutes if it builds on Travis.

**Comment by AleksueiR** [comment]
PRed together with another fix: https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1218

**Comment by jolevesq** [comment]
I have the latest version of geoApi and still have the error. I have checked your branch and from the viewer it works. Don't know what is going on.

**Comment by jolevesq** [comment]
@AleksueiR It didn't work with large csv file like this one. There is a cors problem. If we want to handle those files, we will have to do the same approach as what you have in RAMP.

**Comment by jolevesq** [comment]
Sample with large user added csv file and user added JSON file.

<img width="1029" alt="screen shot 2016-09-29 at 10 09 16 am" src="https://cloud.githubusercontent.com/assets/3472990/18957429/07329d2e-862d-11e6-9efd-ebc61398ef6a.png">

**Comment by jolevesq** [comment]
Everything works well when layout is MAP_ONLY. Both canvases have the same dimension when we merge them there is no problem.

If we use a layout like https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1159 there is a problem. The output image contain arrow and scalebar so it is bigger then just the map.  If we don't have the exact map size and location on the layout it is impossible to calculate the scale and offset to apply to the user added layer canvas

<img width="996" alt="screen shot 2016-09-30 at 1 19 06 pm" src="https://cloud.githubusercontent.com/assets/3472990/19000427/8142cf6a-8710-11e6-8e0b-7026207f53c5.png">

As a workaround we can have the map dimension and location from the mxd layout store somewhere so we can calculate the scale and offset. We can have naked template mxd and copy the scalebar and arrow from map (in this case the image will have the size of the map... need to test).

Any other ideas?

**Comment by AleksueiR** [comment]
Are the margins with the scalebar and north arrow always the same? If so, you can clip the image and be left with just the map, then the dimensions should match.

Did RAMP use the MAP_ONLY template?

**Comment by jolevesq** [comment]
No, the person who create the template decide the format. It will be hard to track all the possible layout. If we use MAP_ONLY we have to transfer the information from the map to the print output. In GCViz, at first, I did this when the print I used didn't use the print task.

Yes, RAMP uses MAP_ONLY layout.

**Comment by AleksueiR** [comment]
Understood. 

We can draw the north arrow and scalebar ourselves on top of the merged images. At this point, I think it will be faster than trying to figure out how much to crop the image. What do you think?

**Comment by jolevesq** [comment]
I agree! it will be faster this way if we only use MAP_ONLY layout and specified the output dimension for the image for our use (e.g. portrait, landscape, ...)

In this case, I will be able to push something for the print early next week.

**Comment by AleksueiR** [comment]
Sounds good. You can use http://svgjs.com/ library to draw the elements. I'm using it to create an svg version of the legend for the export image and the library is already included in the `core.js`.

**Comment by AleksueiR** [comment]
Do you want to create a canvas for the exported image and svg legend graphic as separate object and then smash them together, or draw the legend on the map export canvas? Not sure which way is better.
