### ISSUE TITLE
Consume GeoGratis Service Endpoints

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1162]
- [ ] Consume the Geolocation endpoint to perform searches based on a National Topographic System (NTS) number, postal code FSA or Lat/Long coordinates (https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/geogratis-web-services/17216#g2)
- [ ] Consume the GeoNames endpoint to perform searches for geographical features (http://www.nrcan.gc.ca/earth-sciences/geography/place-names/tools-applications/9249)

**Comment by milesap** [comment]
I'm thinking of putting this functionality into a new service which takes a search string (partial or full) and provides a list of possible location objects including:

- Location name
- Bounding box coordinates
- Center point coordinates

This could be consumed by some future directive which asks for a list of possible location matches as a user is typing, and could display the results in real time. 

Is there anything else I should add/consider here?

**Comment by milesap** [comment]
Per conversation with Alex:

- Service would accept full or partial strings of either NTS number, city, postal code, FSA or Lat/Long coordinates.
- Would provide a list of possible location matches for display to the user.
- Have functionality to pan to the center point of a location result.

## Filter Types
- __Visibility__: if `on` only display results whos center point is in the current extent.
- __Distance__: limit results by numeric value in kilometers representing the distance from the current center point.

**Comment by mweech** [comment]
Good reference for how search using NITS, etc is currently working in GcCanViz.
http://atlas.nrcan.gc.ca/toporama/en/index.html

**Comment by jolevesq** [comment]
We should be able to go a specific scale as well. It will be good to show the extent of the location.

![screen shot 2016-09-14 at 10 28 46 am](https://cloud.githubusercontent.com/assets/3472990/18516250/379bfc44-7a66-11e6-967f-4546345c9608.png)

![screen shot 2016-09-14 at 10 29 35 am](https://cloud.githubusercontent.com/assets/3472990/18516255/3bf2ed48-7a66-11e6-8da3-a2062fa47876.png)

**Comment by mweech** [comment]
PR #1180 is now pulled into Iteration 7.  Closing originating issue.
