### ISSUE TITLE
Design UI for GeoSearch Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1163]
Consume the GeoGratis Geolocation service (https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/geogratis-web-services/17216#g2) to perform searches based on a National Topographic System (NTS) number, postal code FSA or Lat/Long coordinates.

**Comment by AleksueiR** [comment]
We are copying Google Maps' design a bit here by putting the search prompt on the main toolbar, so it's immediately available when the viewer loads. When the search field gains focus, the main toolbar is expanded to accommodate search filters (province, type, etc.)

The search functionality will be similar to that of RAMP's: [RAMP Geo Search v0.2 - 1.pdf](https://github.com/fgpv-vpgf/fgpv-vpgf/files/473186/RAMP.Geo.Search.v0.2.-.1.pdf).


![a04 - geo search - option 1](https://cloud.githubusercontent.com/assets/2285779/18523264/79265e8c-7a81-11e6-8a36-8f1f5edda019.png)

Here Search and Legend are mutually exclusive components - to search, the user needs to first close the legend and vice versa.

![a04 - geo search - option 2](https://cloud.githubusercontent.com/assets/2285779/18523263/79261756-7a81-11e6-8c17-f79faa7434d2.png)

Here Search is a pop-up component that is positioned on top of the legend partially obscuring it. To search, the user doesn't need to close the legend; to open the legend, the user still needs to close the search results.

![a04 - geo search - option 3](https://cloud.githubusercontent.com/assets/2285779/18523262/79259ca4-7a81-11e6-936c-b930a3f43581.png)

Here, opening Search will collapse Legend section into a header and position it underneath search results. The user can return to the legend by either closing the search or clicking the Legend header (which will expand the legend and close the search results).

**Comment by mweech** [comment]
option 3.. even if its a broken link... nice try alex! ;)

**Comment by milesap** [comment]
Option 3 looks good
