### ISSUE TITLE
GeoAPI does not assign geometry type to file-based layers

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1166]
Layer's geometry type specifies which icon to use in the layer-type flag. Right now, since file-based layers do not have geometry type correctly assigned, the layer-type flag icons are empty:
![](https://i.imgur.com/GHVfy2r.png)

**Comment by bkutty** [comment]
Accepted as tested on http://fgpv.cloudapp.net/demo/users/milesap/build-1.4.0-6/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
