### ISSUE TITLE
Removed layers re-appeared after clicking BackToCart

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1169]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.2.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

- Remove multiple layers, for example JOSM, Airports, CESI and Barley layers
![image](https://cloud.githubusercontent.com/assets/18723160/18396622/abe6a464-7692-11e6-9fa9-6b1baf9f1c7f.png)
- Click BackToCart, 
- At least one removed layer re-appeared, in below screenshot, Airports layer came back.
![image](https://cloud.githubusercontent.com/assets/18723160/18396698/00353472-7693-11e6-97ef-6a5a45cc735a.png)

It seems every time there is different layer coming back after clicking BackToCart. Could try removing different combination of multiple layers, at least one layer will re-appear, and sometimes there might have two layers coming back.

**Comment by mweech** [comment]
This is related to the delayed layer removal to accommodate the "Undo" feature.

**Comment by AleksueiR** [comment]
When a layer is removed, it's temporary hidden and removed from the legend, but not from the map to allow the user to undo the removal. During that time, a `removed` flag is set on the legend entry. BookmarkService now uses that flag to filter out "removed" but still in the undo time frame layers from the bookmark.

**Comment by IsabellaPan** [comment]
Nov 21 Verified with build: http://fgpv.cloudapp.net/demo/users/milesap/build-1.4.0-6/prod/samples/index-fgp-en.html?keys=EcoAction,NPRI_CO,Railways,mb_colour,ZoomScale
