### ISSUE TITLE
Zoom to Feature not disabled completely when Dynamic layers are hidden 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1171]
Test build :http://fgpv.cloudapp.net/demo/v1.2.0/samples/index-fgp-en.html?keys=JOSM,Airports,ZoomScale,CESI_Other,NPRI_CO,Railways,mb_colour,Barley

Based on tests done for Bug fix  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/712

When a layer is hidden, zoom to feature icon is disabled in the datagrid, however it is available to click in the details pane. Please note that when the main layer is hidden, this is not an issue. It seems to not work when only the sub layer is hidden.
Please investigate

**Steps to reproduce**
- Load the FGP site
  -Import Service URL http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_census_of_agriculture_2011_ccs/MapServer
- -Hide one of the sub layers. Open the data grid. Zoom icon should be disabled for the hidden layer
- -Click on Details Panel and look for the zoom icon. 
## \- -Icon is still enabled in the details pane. 

![image](https://cloud.githubusercontent.com/assets/18539315/18398823/6aaf0efa-769c-11e6-992c-efce395784e0.png)

**Comment by mweech** [comment]
Can also be reproduced using the EcoGeo layer in http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley
