### ISSUE TITLE
Missing icon after clicking "back to cart"

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1172]
Tested build http://fgpv.cloudapp.net/demo/v1.2.0/samples/index-fgp-fr.html?keys=JOSM,Airports,ZoomScale,CESI_Other,NPRI_CO,Railways,mb_colour,Barley

Icon for excluding layer from click result option disappears after clicking on "back to cart" eventhough functionality works and the option is still disabled for the layer.

![image](https://cloud.githubusercontent.com/assets/18539315/18399472/28299976-769f-11e6-980f-93637e273ebe.png)

**Comment by james-rae** [comment]
Correction is included in bookmark update https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1266

**Comment by bkutty** [comment]
Tested this fix on http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Bookmark and "back to cart" function still does not seem to capture the icon which appears when you disable a query. Please investigate

![screenhunter_2588 nov 01 16 06](https://cloud.githubusercontent.com/assets/18539315/19905526/90aa224a-a04d-11e6-9206-b343f5754b13.jpg)

**Comment by james-rae** [comment]
The bookmark updates are in `v1.4.0-rc3`.  Probably a mis-communication on what should be tested on which version.
