### ISSUE TITLE
Add ESRI API method orderByFields from geoAPI to filter service query

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1174]
Currently we assume `oidField` values are sorted by esri map servers in `filterService`. Should this change or not be true in all cases, the filter service won't provide correct filtering.

If `oidField` values aren't sorted then the last item in the returned list may not have the highest `oidField` value for this particular result set. I.E. if the returned list was `[1, 5, 2, 0]` and a `exceededTransferLimit` was reached, then we would query again asking for results with an `oidField value > 0`. This would return `[1, 5, 2, 0]` again with a `exceededTransferLimit` so an infinite loop is possible. We can't sort client side either since the **first** result set could include the largest `oidField` value.

**Comment by james-rae** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2296

**Comment by mweech** [comment]
Edge case that has not been found elsewhere. Closing unless need re-emerges to support this.
