### ISSUE TITLE
Create UI for GeoSearch Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1175]
Create the UI component to implement GeoSearch based on mockup created by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1163.

**Comment by jolevesq** [comment]
@AleksueiR , @alyec There is a problem when we are pass over full extent. The extent projection for min and max coordinates gives bad result and the query does not work. We should add a test to see if we are over full extent and restrict the values inside those?

**Comment by jolevesq** [comment]
@AleksueiR , @alyec or would it be better to restrict the viewer to zoom or pan outside the full extent?

**Comment by AleksueiR** [comment]
What do you think about internally disabling the extent filter once the map zooms out far enough so the extent starts wrapping around? @james-rae suggested some code in the bookmark that can help with such detection: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.4.0-rc1/src/app/core/bookmark.service.js#L117

I don't think restricting the viewer to the full extent is a good solution, as we don't set the full extent in the first place.
