### ISSUE TITLE
Create UI for Image Export Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1176]
Implement design outlined in #1156.

**Comment by AleksueiR** [comment]
Here's pof for generating an svg legend and resizing it to fit the layout ([codepen](http://codepen.io/AleksueiR/pen/xEREVN?editors=0010)):

![](https://i.imgur.com/hEBBH9J.png)
![](https://i.imgur.com/YrIKSvS.png)
![](https://i.imgur.com/sejOy5Q.png)
![](https://i.imgur.com/wtMXyHw.png)
![](https://i.imgur.com/4aVwKdG.png)

**Comment by AleksueiR** [comment]
Ta-da :tada: 

Here's an example of a real legend with wms and everything:
![](http://i.imgur.com/EbSCS3B.png)

Now, I just need to fix some inefficiencies I found....

**Comment by AleksueiR** [comment]
Stuff to do:
- [ ] generation crashes if some layers don't have names
- [ ] generation crashes if some layers failed to load
- [ ] generation crashes if some layers don't have symbology defined (didn't load yet)
- [ ] long layer names without spaces cannot be wrapped right now
- [ ] low section count might crash the generation
- [ ] small legends looks weird spread out over many sections
- [ ] legend svg is sized strangely in IE (it's miracle it works at all)

**Comment by AleksueiR** [comment]
Aly is working on optimizing small legends. Otherwise this is complete.

**Comment by AleksueiR** [comment]
Moved two subtasks into separate images so this one can be closed.
