### ISSUE TITLE
fix(ui): see all information available inside basemap description

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1177]
We need to find a way to show all information for basemap description when it exceed the container length

<img width="297" alt="screen shot 2016-09-13 at 9 36 51 am" src="https://cloud.githubusercontent.com/assets/3472990/18475787/ceb1838c-7995-11e6-8054-524a2c6d1e40.png">

**Comment by mweech** [comment]
Changed to a CR.  Right now it is working "by design" with the stipulation that the text should be sized to available space.  R3 requirements involve making some changes to how we deal with basemaps and what is available information wise for them so we should bundle this accordingly.

**Comment by AleksueiR** [comment]
Current behaviour:
https://fgpdoc.zz9.ca/index.php/s/sssMmmqZnGBon9j
