### ISSUE TITLE
bug(ui): settings and metada toggles in toc are not accessible via keyboard or touch

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#118]
These toggles are hidden and shown only on hover; when tabbing, they are skipped and only the visibility toggle gets focus.

- [ ] Let settings and metadata to properly receive focus from the keyboard.
- [ ]  Always display toggles in mobile layout (and/or when a mobile browser detected.)

![](https://i.imgur.com/gBNiOMr.png)

**Comment by mweech** [comment]
solved as part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/52
