### ISSUE TITLE
Allow for Generation and Display of Bookmark within Viewer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1181]
Currently the viewer only supports creation of bookmarks when implemented through an external API by a host page.  The viewer needs to be able to generate a bookmark for a user from within the viewer.  

- [ ] Share button is added back to Left-sided menu
- [ ] Dialog is shown with option for a long or a short link
- [ ] Can disable presence of this feature from config

**Comment by AleksueiR** [comment]
Dialog with the share link:
![](https://i.imgur.com/K11jh6O.png)

**Comment by milesap** [comment]
Discussed with @AleksueiR - the short link option will use the [Google URL shortener API](https://developers.google.com/url-shortener/v1/getting_started). We can use the same Google API Key from the config that Geolocate uses for Googles Geolocation API. If there is no Google API key present in the config then there will be no short link option.
