### ISSUE TITLE
Visibility of user-added ESRI Tile Layer cannot be changed

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1186]
I added [this layer](http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer/) and the visibility control is disabled in its legend entry (visibility is initially off as well).

![](https://i.imgur.com/S7l44NG.png)

**Comment by AleksueiR** [comment]
**Cause**: 
When a tile layer is loaded in a projection different from its own, the layer is hidden and its visibility control is disabled. 

**Suggestion**:
When adding layers though the import wizard, detect tile layer's proper projection and inform the user that this layer will not be visible if it differs from the current projection. (Do we block the user from adding such layers completely? If not, these layers need to persist through projection switch, which they don't currently.)
Also implement this: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/626

**Comment by mweech** [comment]
Should allow users to add the layer, but mark it as being not in the current projection.

**Comment by milesap** [comment]
User added layers are not currently kept on projection change (changing on refactor). Will add icon to indicate it is in wrong projection (same for config loaded tile layers).
