### ISSUE TITLE
Help Files Missing from Deployments of Viewer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1187]
In deployments of the viewer based on our release packages, the Help file is missing for all languages.  This is not an issue on the Azure cloud instance where the viewer is auto-deployed.

Missing help file:
- http://section917.cloudapp.net/NACEI/nacei_map_en.html
- http://dev.gcgeo.gc.ca/viz/index-en.html

Help file is available:

- http://fgpv.cloudapp.net/demo/v1.2.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley

**Comment by AleksueiR** [comment]
Help services loads a translation file to get keys for help sections. In our test cloud deployments, translation files are located (erroneous) in the samples folder, so this process works. In the NACEI deployment, there are no translation files, and the help service fails.

Help service should not rely on translation files and translation files themselves should be removed from the samples.
