### ISSUE TITLE
Focus manager erroneously triggered 

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1192]
Steps:
- click on the map with a mouse 
- press "Tab" or "Shift + Tab"

"Keyboard focus" dialog gets triggered.

See PR fgpv-vpgf/fgpv-vpgf#1167.

Expected behaviour:
After clicking on the map, the focus should stay/be placed inside the viewer; pressing "Tab" should not trigger the dialog.

**Comment by bkutty** [comment]
Does not seem to be an issue. Tested on v1.4.0-7
