### ISSUE TITLE
Add filter icon to the "Filter by Extent" datatable option

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1195]
Place the filter icon on the data grid top menu same way you have for Print and Export.

![](https://i.imgur.com/bB1eujV.png)

Thank you @bkutty for the suggestion!

**Comment by AleksueiR** [comment]
On the other though, the “filter by extent” menu item is a checkbox-item (a checkmark indicates if it’s selected) and if we add a filter icon, we cannot indicate if the filter is enabled or not. 

![](https://i.imgur.com/nxMAPnD.png)


We can optionally move icon to the right of the labels, and then display both the checkmark and the icon:

![](https://i.imgur.com/Yft9Lmb.png)

**Comment by mweech** [comment]
Move icons to the right.
