### ISSUE TITLE
Opening Help with a keyboard moves focus to the legend button

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1202]
Page: http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html

Steps:
- tab to the viewer
- press "Enter" to activate
- open Help dialog
- instead of moving the close button, focus moves to either the main Menu or Legend button

**Comment by bkutty** [comment]
Verified based on tests performed on v1.4.0-7
