### ISSUE TITLE
Filter by Extent only Filters Datagrid on Initial Selection

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1203]
When using the "Filter by Extent" functionality, the datagrid will be filtered initially.  However on subsequent changes to the current extent, the datagrid does not update.

**Comment by AleksueiR** [comment]
Cannot reproduce. WOMM on develop.

**Comment by james-rae** [comment]
WOMM

**Comment by james-rae** [comment]
Possibly related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1264

**Comment by mweech** [comment]
reproducible in the mercator projection.

**Comment by james-rae** [comment]
Duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1264

**Comment by mweech** [comment]
Verified.
