### ISSUE TITLE
Zoom to Feature Freezes Browser Tab on Some Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1204]
When trying to Zoom to Feature for the following map on either of the Hurricane or NOAA Metar layers, the browser tab freezes with what appears to be an infinite loop.

http://section917.cloudapp.net/NACEI/nacei_map_en.html

This is found in v1.2.0.

**Comment by james-rae** [comment]
Cannot reproduce browser freeze as of v1.4.0

Did notice poor behavior on the Hurricane layer, all zooms were heading to map origin (Atlantic east of Africa in Mercator), inidicating a lat/long mis-conversion.

Checking the service, the data is encoded in lat/long but published as Web Mercator.  Not much we can do about services giving false info.

[Feature Sample](http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Hurricane_Active/MapServer/1/5?f=pjson) - note geometry in lat/long
[Service](http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Hurricane_Active/MapServer/?f=pjson) - note spatial reference is `102100` Web Mercator

**Comment by dan-bowerman** [comment]
Just to chime in based on an OCS conversation with James -- that Hurricane service is actually hosted by Esri, They also note that the service will be retired in 3 months, so hopefully whatever service replaces this won't have this issue when we're ready to implement a real solution (if we're doing anything beyond providing RAMP).

**Comment by bkutty** [comment]
No longer an issues. Accepted.  tested build v1.4.0-7
