### ISSUE TITLE
Layer loading issue for imported CSV & Shapefile

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1206]
Tested build: http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Test Data
CSV file: rc_cdr.csv
Shapefile: ne_10m_ports.zip

When importing CSV or Shapefile to FGP, it displayed "Loading layer..." status and never finished, even the layer map points have already added to the map.

![image](https://cloud.githubusercontent.com/assets/18723160/18718065/21bad4ba-7ff0-11e6-9f99-43abdf8ec242.png)

**Comment by james-rae** [comment]
Recent refactor of symbology generation dropped code to handle symbols that do not have an outline defined. Code is trying to generate outlines from an undefined object.  See `function esriSMS()`

**Comment by AleksueiR** [comment]
Fix is in PR to geoApi.

**Comment by milesap** [comment]
Create and link new geoApi build with `v1.3.0` release

**Comment by AleksueiR** [comment]
geoApi version updated in https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1218.
