### ISSUE TITLE
No Visible focus for selecting "Import File/Service" after tabbing on "Import Layer" feature in Firefox

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1207]
Tested on :http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

![screenhunter_2465 sep 21 11 58](https://cloud.githubusercontent.com/assets/18539315/18718863/eb6b7d1c-7ff2-11e6-8a77-0530e0644c4e.jpg)

Unable to select the option of Importing File/Service as the tab does not select either of these options after selecting "Import Layer". Issue found only in Firefox. Please investigate

**Comment by ChrisLatRNCan** [comment]
Problem vanished with latest version

**Comment by bkutty** [comment]
Accepted per tests on http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
