### ISSUE TITLE
Import File Wizard - Keyboard window pop-up in Step 3 when changing Primary Field

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1208]
Tested build: http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
 Test Data
 CSV file: rc_cdr.csv
 Shapefile: ne_10m_ports.zip

When using mouse to change  Primary Field default value to other options, Keyboard window pop-up as below screenshot.
![image](https://cloud.githubusercontent.com/assets/18723160/18721517/e363320c-7ffe-11e6-93f8-0ec486d5a06a.png)

**Comment by bkutty** [comment]
Please note that this issue is also found when a Service URL is imported.

**Comment by IsabellaPan** [comment]
Nov 29
Verified with build: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
