### ISSUE TITLE
Keyboard Navigation issue at multiple places in the Viewer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1210]
Tested:http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Keyboard navigation pop up seems to be an issue at multiple places. An issue is already logged #1208 for "Import Layer".
Similar issue is seen when a data grid is changed from Split View to Maximise.

![screenhunter_2466 sep 21 14 13](https://cloud.githubusercontent.com/assets/18539315/18723481/b768018e-8006-11e6-9831-d86d737ff4ae.jpg)

**Comment by mweech** [comment]
Implement focus management improvements outlined here: https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Focus-Management

**Comment by bkutty** [comment]
This issue seems to be resolved now as tested on v1.4.0-7.
