### ISSUE TITLE
Feature icons are missing under Point Details pane when clicking map points

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1211]
Tested build: http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

This happened with JOSM and Airports layers.
![image](https://cloud.githubusercontent.com/assets/18723160/18725464/5c355c28-800e-11e6-928a-6612badcadb3.png)

**Comment by AleksueiR** [comment]
All feature layer are missing symbology icon in identify results because the variable name for symbol has changed and _someone_ forgot to update it.
