### ISSUE TITLE
Angular material pop-up boxes ($mdDialog) closes unexpectedly on mouse click

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1215]
Tested on http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-one.html

- Navigate and open the help dialog box
- Click anywhere inside the dialog, or try to scroll using the scrollbar arrows or dragging the scrollbar itself

The dialog closes unexpectedly. This issue will block #1181 as it prevents clicking on a `switch` element inside an $mdDialog.

**Comment by AleksueiR** [comment]
duplicate: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1202

**Comment by milesap** [comment]
It may have a common solution but they are separate issues. If I set `clickOutsideToClose` to false it still happens so focus may not be causing this.

Checked `v1.2.0` working as intended

**Comment by AleksueiR** [comment]
Correct, my mistake. I noticed that yesterday and was asking in the main room :point_up: [September 20, 2016 2:55 PM](https://gitter.im/fgpv-vpgf?at=57e1861cc3e7045a306617cd), but didn't get to make an issue out of that.
