### ISSUE TITLE
IE11 - Missing Metadata links

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1217]
Tested build: http://fgpv.cloudapp.net/demo/v1.3.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Both Data Catalogue and Raw Metadata links are not showed up.
![image](https://cloud.githubusercontent.com/assets/18723160/18752734/4daf6a1a-80b1-11e6-9a38-3381f3c587cc.png)

**Comment by AleksueiR** [comment]
The function parsing a metadata xml document for IE11 was returning a string instead of a document fragment. `catalogue_url` and `metadata_url` were tucked onto the returned object (string in IE11 case, which silently fails, of course).
