### ISSUE TITLE
WMS Server Error while querying Railway Network Layer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1228]
Tested on:http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,ZoomScale

Projection: Mercator/World Imagery

Multiple Instances of failed query for Canada Railway Network layer. Seems issue only in IE11. Could not reproduce in Firefox. For some reason, I also see 2 horizontal lines going across the map as below. Please investigate

![screenhunter_2480 sep 26 16 16](https://cloud.githubusercontent.com/assets/18539315/18850395/53e404c0-8405-11e6-917b-5331f4023ea9.jpg)

![screenhunter_2481 sep 26 16 20](https://cloud.githubusercontent.com/assets/18539315/18850415/712a4648-8405-11e6-990a-eb8370782212.jpg)

**Comment by bkutty** [comment]
Please note that I got a similar error in Firefox today while querying Railway Network Points. Bookmark used for the test is as below:

http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?rv=A,YmFzZU5yQ2Fu,MTY2MTc5MS43OTQwOTAyNTU,LTExNjQ3Ny44OTQyMDg3ODkwOQ,NTAwMDA,MDByY3MuSk9TTS5lbjEwMDAwMDE,MDByY3MuQWlycG9ydHMuZW4xMDAwMDAx,MDByY3MuWm9vbVNjYWxlLmVuMTAwMDAwMQ,MDNyY3MuRWNvQWN0aW9uLmVuMTAwMDAx,MDNyY3MuQ0VTSV9PdGhlci5lbjEwMDAwMQ,MDNyY3MuTlBSSV9DTy5lbjEwMDAwMQ,MDFyY3MuUmFpbHdheXMuZW4xMDAxMDE,MDRyY3MubWJfY29sb3VyLmVuMTAwMDA,MDNyY3MuQmFybGV5LmVuMTAwMDAx

**Comment by alyec** [comment]
I spoke to Bindu about this and it seems this happened while IE was at a lower zoom level.  I believe IE is doing some image resampling (getting a larger image and resampling it to the screen).  This can trigger the size limits on WMSes (typically 2048 by default) and this causes the getFeatureInfo request to fail.

**Comment by alyec** [comment]
Looking into this a bit more: both WMS 1.1.1 and 1.3 send XML exceptions in this case.  This is something we can parse; however, no headers indicate the error and the status code is 200 so we will have to parse the incoming messages and looking for the `ServiceException` element.

**Comment by ChrisLatRNCan** [comment]
#1613

**Comment by milesap** [comment]
Duplicate to #1613, closing
