### ISSUE TITLE
Mercator maps - Map scale value changed reversely when zooming out after certain scale

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1230]
Tested build: http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

After zooming out to a scale of 3000km, the map scale changed reversely to 1000km, and then 60km if continuing to zoom out the map.
![image](https://cloud.githubusercontent.com/assets/18723160/18880262/4ad4081c-84a5-11e6-8ee1-dc187a596acc.png)

**Comment by mweech** [comment]
do we need a max zoom out level??

**Comment by ChrisLatRNCan** [comment]
I would put a 2000 Km limit to englobe tri-lat countries at max zoom out level

**Comment by ChrisLatRNCan** [comment]
Note:
isOffScale()
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L196

**Comment by ChrisLatRNCan** [comment]
Removing some Mercator level nodes in the config file does the job. We don't want to have several instances of the same basemap shown simultaneously.

**Comment by ChrisLatRNCan** [comment]
Will remove the first three lods levels for Mercator basemap. Need also to adjust the extent.

**Comment by IsabellaPan** [comment]
Feb 22 2017
No longer an issue as currently Mercator maps can only zoom out to scale of 2000km.
