### ISSUE TITLE
Point Information is populated in Expanded panel and not in Point Info Panel for most of the Railway map Points

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1236]
Tested using bookmark:http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?rv=A,YmFzZU5yQ2Fu,MTY1OTg3NS41NDU0NjYwOTQz,LTExMjcxOC4xNTc1MjI2NTYyOQ,MTc1MDA,MDByY3MuSk9TTS5lbjEwMDAwMDE,MDByY3MuQWlycG9ydHMuZW4xMDAwMDAx,MDByY3MuWm9vbVNjYWxlLmVuMTAwMDAwMQ,MDNyY3MuRWNvQWN0aW9uLmVuMTAwMDAx,MDNyY3MuQ0VTSV9PdGhlci5lbjEwMDAwMQ,MDNyY3MuTlBSSV9DTy5lbjEwMDAwMQ,MDFyY3MuUmFpbHdheXMuZW4xMDAxMDE,MDRyY3MubWJfY29sb3VyLmVuMTAwMDA,MDNyY3MuQmFybGV5LmVuMTAwMDAx

Layer used - Canadian Railway Network

Point information Panel is not populated at all times when querying this layer. However, all info is present in the expanded panel. Issue was found in "Railway Crossings" , Railway Stations and Tracks

![screenhunter_2483 sep 27 11 40](https://cloud.githubusercontent.com/assets/18539315/18881011/d40640f8-84a7-11e6-8add-f72a25c09c4f.jpg)

**Comment by ChrisLatRNCan** [comment]
Seems related to how OgcWms is handle.

**Comment by ChrisLatRNCan** [comment]
Tried to cut down the problem :scissors: .
Tests with tracks and stations only on fresh local build with  index-one.html and index-fgp-en.html.
From here http://maps.geogratis.gc.ca/wms/railway_en?service=wms&version=1.3.0&request=GetCapabilities
In the GetCapabilities xml file three formats are offered:
`    <GetFeatureInfo>
      <Format>text/html</Format>
      <Format>application/vnd.ogc.gml</Format>
      <Format>text/plain</Format>`

1- index-one.html
Setting the **featureInfoMimeType** to **text/html**
On Firefox:
-Tracks => info will appear only in expanded panel
-Stations => info will appear only in expanded panel
However it is ugly
![image](https://cloud.githubusercontent.com/assets/16193004/20402746/fdcfa612-accb-11e6-9708-b57ae5175a77.png)

On IE11 and Chrome I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/16193004/20401982/e39b2260-acc8-11e6-97b2-f5a5786e1936.png)

Setting the **featureInfoMimeType** to **text/plain**:
On Firefox:
-Tracks => info will appear in both panel and expanded panel
-Stations => **minimal** info will appear in both panel and expanded panel
On IE11 and Chrome I'm getting this error (same as previously but a bit more explicit):
![image](https://cloud.githubusercontent.com/assets/16193004/20402111/74121b00-acc9-11e6-903a-0072a66d8072.png)
Error in text format:
`<?xml version='1.0' encoding="ISO-8859-1" standalone="no" ?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException>
msWMSLoadGetMapParams(): WMS server error. Image size out of range, WIDTH and HEIGHT must be between 1 and 2048 pixels.
</ServiceException>
</ServiceExceptionReport>
`

2- index-fgp-en.html
Same behaviour for the three navigators
-Tracks => info will appear only in expanded panel
-Stations => info will appear only in expanded panel
Much nicer
![image](https://cloud.githubusercontent.com/assets/16193004/20402856/6f230e80-accc-11e6-9beb-2ecc39720716.png)

**Comment by ChrisLatRNCan** [comment]
Some observations:
**On local build**
With index-one.html **WIDTH** in the GetMap request is 2048 which is the max of the mapservice and **WIDTH** is 1137 for index-fgp-en.html
http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&STYLES=&VERSION=1.3.0&LAYERS=railway.track,railway.station&WIDTH=2048&HEIGHT=723...
http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&STYLES=&VERSION=1.3.0&LAYERS=railway.track,railway.station&WIDTH=1137&HEIGHT=700...

However on the cloud http://fgpv.cloudapp.net/demo/weekly-1.4.0-5/prod/samples/index-one.html
the WIDTH is 1920
http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&STYLES=&VERSION=1.3.0&LAYERS=railway.track,railway.station&WIDTH=1920&HEIGHT=542...

**Comment by ChrisLatRNCan** [comment]
Just saw that one:
WMS Server Error while querying Railway Network Layer #1228

**Comment by ChrisLatRNCan** [comment]
It's working :fireworks: :sparkles: 
It was too simple...
Need more tests...
![image](https://cloud.githubusercontent.com/assets/16193004/20568018/fcbd88d8-b168-11e6-9fa4-b05dd7a75b97.png)

**Comment by ChrisLatRNCan** [comment]
Is testable only with:
index-wet.html and index-fgp-{en|fr}.html
For other templates the error related to 2048 size limit stand still (see #1228 for more info)

**Comment by bkutty** [comment]
No longer an issue as tested in v1.5.0-2
