### ISSUE TITLE
Change Basemap Selector to a Right Sided Navigation Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1244]
Basemap Selector is currently implemented as a panel.  It should be implemented to operate the same as the Left sided menu.

**Comment by AleksueiR** [comment]
This how it works now - opened panels are partially hidden when the basemap selector is open to allow for better view of the map:
![new_basemap](https://cloud.githubusercontent.com/assets/2285779/19200356/991d77da-8c96-11e6-9c7d-7df42009a162.gif)

**Comment by AleksueiR** [comment]
![new_basemap2](https://cloud.githubusercontent.com/assets/2285779/19200972/bb7961ba-8c99-11e6-870e-b6800d51cd55.gif)
