### ISSUE TITLE
Switching language twice drops layers

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1255]
Steps:
- open `index-one.html`
- notice loaded layers from the English config
- switch to French
- notice loaded layer from the French config
- switch back to English
- notice layers have English names now, but the set of layers hasn't changed

![m_language_switching](https://cloud.githubusercontent.com/assets/2285779/19083924/4645afb6-8a32-11e6-8ff6-74eb79d1322e.gif)

**Comment by james-rae** [comment]
Should be solved by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275 

Verify that problem no longer exists after implementation

**Comment by milesap** [comment]
Duplicate of #1501, confirmed no longer an issue
