### ISSUE TITLE
feat(geo): add layer order array to geo

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#126]
Add an array structure to the [geo service](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/geo.service.js) to manage the order of layers in the map.

* See the [wiki](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Geo-Tier-Architecture) for details on the architecture
* Name array layerOrder (not set in stone; alternates can be suggested)
* Array will contain strings (layer ids)
* Array is exposed in return object for Geo
* Is there stuff that needs to be done for angular binding compatibility?

**Comment by AleksueiR** [comment]
The default legend should correspond to the `layerOrder` exactly. What about custom legend, how is `layerOrder` constructed from the supplied legend?

Say this is the legend provided:

```json
-- Legend --

[group 1]
	feature 1
	feature 2
	wms 1
	feature 3

[group 2]
	feature 4
	
	[group 3]
		feature 5
		wms 2
		feature 6
	
	wms 3
	feature 7

wms 4
feature 8
```

You would just flatten it and move wms layers underneath feature layers, like this:
```json
-- layerOrder --

feature 1
feature 2
feature 3
feature 4
feature 5
feature 6
feature 7
feature 8
wms 1
wms 2
wms 3
wms 4
```

Is that right?

I don't think anything specific needed for Angular bindings. Right now TOC is bound to a piece of [hardcoded legend structure/config](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.service.js#L24) and builds the layers selector out of that.

**Comment by jolevesq** [comment]
The layer order on the maps does not come from the layers order in the legend section but the layers order in the layers section. In the layers section, there is 2 group, one for feature layers and one for images layers. The legend section is only for display purpose in the legend tab.

**Comment by AleksueiR** [comment]
Right, forgot about that part. Thanks for explaining.

**Comment by AleksueiR** [comment]
@james-rae @mweech this seems to be obsolete now.
