### ISSUE TITLE
FGP Visualiser not loading any layers

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1260]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.4.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

![image](https://cloud.githubusercontent.com/assets/18723160/19156479/010693d2-8bb0-11e6-898b-f35ea3f1177b.png)

**Comment by james-rae** [comment]
Appears to be the RCS service is down.

**Comment by james-rae** [comment]
Resolved by restarting RCS service.  Service went down, possibly due to cloud server updates?

**Comment by dan-bowerman** [comment]
Yes, the VM was completely shut down and I wasn't aware. Given a few Windows machines have received automatic updates over the past couple days, I am going to blame that. Everything is back online now.
