### ISSUE TITLE
The viewer waits for RCS to respond before rendering the map

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1261]
RCS was down the other day and `index-one` page took an unusual amount of time to load. It seemed the viewer was waiting for RCS to reply with config snippets to add them to the file-based config. When the call timeouted, the viewer finally loaded.

This should not be happening as it makes the viewer feel unresponsive. Instead of waiting for RCS to reply, the viewer should launch with just layers specified in a config file (or no layers at all), and add layer RCS layers later, after receiving a response. 

Might be related to #380

**Comment by james-rae** [comment]
Will likely want https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275 to happen first. 

The current load process is tricky. We have config inputs coming from a number of places
* Config files
* RCS config snippets
* Bookmark config snippets
* Weird syncing of bookmark and RCS in the back-to-cart scenario

The app tends to wait for all this to be sorted out prior to consuming the final config product.

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275 will add the concept of an application state, and possibly the ability to modify that state after the app has loaded.

For this issue to be successful, we need some way of consuming and loading a config based layer (from the RCS as the main example, but also useful for restoring file based layers after a schema change) after the app has loaded. If this functionality is completed as part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275, it will likely go a long way to solving this issue.

**Comment by alyec** [comment]
@AleksueiR and I have some notes in #1275 https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275#issuecomment-259176030 .  It's probably a bit bigger than just #1275 and probably goes into some of #650 as well (changing the layer registry to allow Promise based updates on layers that are incomplete).

**Comment by AleksueiR** [comment]
Irrelevant in 2.0.

**Comment by mweech** [comment]
no longer valid under 2.0
