### ISSUE TITLE
Layer names duplicated in the Layer results pane

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1262]
Tested on : http://fgpv.cloudapp.net/demo/v1.4.0-rc1/

Layer names are duplicated under Point Information Panel when a map point is selected. For eg, in the below screenshot, Nature, Climate Change, Clean water and clean Air belongs to a single group EcoAction Community Funder Projects and the group name should have been displayed below each layer name. Instead the Layer name is repeated

![group layer naming](https://cloud.githubusercontent.com/assets/18539315/19192951/125a634a-8c76-11e6-8222-e66980f29a68.png)

**Comment by AleksueiR** [comment]
Currently rendered as:
![](https://i.imgur.com/UOpeHbT.png)

**Comment by mweech** [comment]
Verified.
