### ISSUE TITLE
Architecture of Bookmark Versioning

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1265]
Discussion thread about how to structure the bookmark logic; in particular, the parsing of multiple versions of bookmarks.

Discussion facts!
- Code to parse bookmarks exists in both the bookmark module (main function) and in the Layer Classes (contains layer-specific parsing routines).
- Differences between sibling versions are usually few.  E.g. version `n` and version `n+1` will likely have most of their format be the same, and thus use most of the same code to parse the bookmark.

Design difficulties
- Separating parsing routines into silos (one per version) is made difficult by some of the logic lurking in the Layer Classes
- Separating parsing routines into silos results in a lot of duplicated code.
- Adaptive parsing (i.e. one function handles multiple versions) results in lots of special `if` statements. The situation gets worse as more versions are supported.

Brief Discussion Notes from Refactor Meeting
- Remove logic from Layer Classes
- Have a base class of "useful utility functions" for parsing bookmarks.
- Have a class for each version that utilizes the functions in the base class.
  - Base class does the work. Version class orchestrates the work.

See [Bookmark Versions](http://fgpv-vpgf.github.io/fgpv-vpgf/v2.1.0/tutorial-bookmark_formats.html) for what they look like.

See this PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1266 for examples of both bad approaches.  The main application peppers `if` statements to add version specific logic.  The bookmark decoder page uses silo'd functions with lots of duplicated code

**Comment by mweech** [comment]
Is it possible to consider layer order when generating/using a bookmark.  

Use case: policy analyst compiles a map using both polygons and point features with a particular layer order that highlights useful information that is then shared with a colleague via a bookmark link.  Colleague opens the link and the polygon layer renders underneath the point feature layer so as not to obscure the data.

Refer to this issue:  http://redmine.gcgeo.gc.ca/redmine/issues/5975
