### ISSUE TITLE
Please modify "Help" section to replace "Share" with "Get Link" 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1270]
Tested v 1.4-rc1

Please modify "Share" description and terminology to "Get Link" just to be consistent with the feature available in  FGP.

![screenhunter_2519 oct 13 10 08](https://cloud.githubusercontent.com/assets/18539315/19352294/57d7cf82-912d-11e6-8deb-46dd39dbecb2.jpg)

**Comment by ChrisLatRNCan** [comment]
Same thing in French: Obtenir le lien in place of Partager

**Comment by bkutty** [comment]
Please complete the text for Get Link under French as highlighted. Get Link has different French name under "usage".

![help text](https://cloud.githubusercontent.com/assets/18539315/20681979/f19034d8-b573-11e6-9fb8-421dda9b676e.PNG)

**Comment by ChrisLatRNCan** [comment]
I'll process it in a new issue with others translations to be done/fix.

**Comment by mweech** [comment]
@ChrisLatRNCan we are going to change the naming of that functionality back to "Share" based on Usability report feedback.

**Comment by bkutty** [comment]
No longer an issue. Marking this item as fixed
