### ISSUE TITLE
No records displaying in datatable for canada.json layer

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1273]
- add `canada.json` file
- open datatable
- see there is no records (although at the bottom of the table is says, 0 entries filtered out of 1 total)

![](https://i.imgur.com/h90Lxni.png)

Identify on the canada polygon also doesn't return anything.

Would it be because canada.json doesn't have any useful data apart from lat/long? We don't show these in the datatable, so, technically, there is nothing to show.

**Comment by ChrisLatRNCan** [comment]
In the canada.json file there's a optional parameter named **id** (identifier) that is part of [GeoJson specs](http://geojson.org/geojson-spec.html#feature-objects). So with the **id** parameter we get no record in the table but without it we get one record. However, if we put a numeric value for **id** (say 25) the viewer will take the value as an OBJECTID. You can even put a letter in the id at the only condition that it is not at first position so 25, "25", "25b", "2b5" will work but not "b25", 2b5 . 
```
{"type":"FeatureCollection","features":[
{"type":"Feature","id":"CAN","properties":{"name":"Canada"},"geometry":
```
![canadajson3](https://cloud.githubusercontent.com/assets/16193004/21058621/d35468b2-be0c-11e6-8089-b1e3188c5937.gif)

Moreover, we can see a toast appearing and desappearing at the speed of light (there is no error in the console). Point info will show nothing even though there's one record in the table.

**Comment by james-rae** [comment]
This [function](https://github.com/fgpv-vpgf/geoApi/blob/v1.1.0/src/layer.js#L714) is likely part of the problem. We may need to enhance things to handle funny cases.

One example, without thinking too hard:
Pre-examine the entire geoJson feature attributes.  If field `id` exists and contains non-unique or non-interger values, port them to a different named field, like `origID`, then wipe and set `id` with autonumbers.

**Comment by ChrisLatRNCan** [comment]
There's two function calls of [makeGeoJsonLayerBuilder](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/layer.js#L764) .

**Comment by ChrisLatRNCan** [comment]
I implemented a mix of what James proposed. 
By default an id autonumber is generated. If an id originally exist in at least one of the feature, the original id value is put in a new attribute origID in the properties object of the feature so it can appears on the table. Any other features of the same dataset without a defined id will get an origID = ''

**Comment by ChrisLatRNCan** [comment]
For the moment the viewer doesn't support mixed-types geometry in the same file.

**Comment by ChrisLatRNCan** [comment]
In PR:
fix(geoapi): add geoJson id backup and id autonumbering  fgpv-vpgf/geoApi#176

**Comment by IsabellaPan** [comment]
Jan 11 2017
Verified with build http://fgpv.cloudapp.net/demo/v1.5.0-9/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
