### ISSUE TITLE
Full State Stored for Language, Projection Switch & Back to Cart

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1275]
Currently the viewer utilizes a the limited state of the bookmark link when switching language, projection or to store state in session storage as it allows for Back to Cart functionality (user added layers do not persist).  However, this paradigm should be switched such that language, projection and back to cart functionality uses session storage for full storage of state including the JSON of user added file based layers.  

By doing so, no user added layers would be lost upon switching projection or language and would allow for the following use case to be satisified: _As a policy analyst, I want to prepare my map in the language of my choice.  Once I have finished, I want to share my map (print, get link, etc.) with my Anglophone and Francophone colleagues in the language of their choice._

Furthermore, bookmarks should be subsequently generated based off of the full state that is captured, rather than assembled directly itself to prevent duplication of code.

**Comment by alyec** [comment]
Notes from the half meeting

Refactoring
- split load cycles up
  - have a clear separate load for map vs. config vs. UI
- have restore prompts for viewer when returning to the page
  - should use JS based detection for when the user navigates away (or is directed away for back to cart)
  - may want to use a time based prompt (you have a session from 30 minutes ago, restore?)
- bookmark will only save config state

UI
  - panels and datagrid should save some state
  - don't need to save all the details (i.e. where the user scrolled to in the datagrid)
  - can re-execute requests as needed so we only need to remember smaller details:
    - identify location; which layer had metadata open vs. caching the responses
  - legend tree should be stored (groups were expanded / collapsed)

Config
  - requires reloading the config and any RCS keys
  - the only config specific state we have is language

Map
  - state to save: extent, filters, datagrid (per layer), layer settings, basemap

Sample transitions
- UI
  - back to cart
  - navigate away from page and hit back button
- config
  - language switch
  - bookmark load
- map
  - projection switch

Tasks
- define a UI state
- define a map state
- write serialization logic for UI
- write serialization logic for map
- refactor map loading to apply deserialized states
- add support to save serialized states to some offline storage in browser
- refactor bookmark to work off the new map state

**Comment by james-rae** [comment]
The above implies (to me) that when we load a bookmark, we are still adjusting the application config file with bookmark settings prior to the config file being eaten by the application.  Is this correct?

Agree with putting a time-limit on the restore prompting.

**Comment by alyec** [comment]
I tend to distinguish state from config, but other than terminology I think that's correct.  I would see a bookmark load being:
- load all config sources (local vars, config files, RCS keys, ...)
- create initial state (this would be the same as if the app was loaded with no bookmark)
- parse the bookmark and deserialize the state snapshot (this will be incomplete since bookmark doesn't capture everything)
- apply state snapshot to initial state
- continue with application loading

**Comment by alyec** [comment]
@AleksueiR and I were discussing how to handle missing RCS layers without blocking the whole application load.  RCS layers can be loaded into the layer registry as promises and can be added as they are resolved.  State snapshot can chain on that promise to modify the final result without creating a bunch of blocking calls.

**Comment by mweech** [comment]
Estimate update to 21 following a discussion with Aly.  Viewer configuration schema refactoring scope will be pulled into this epic in order to facilitate this change.  This has added additional work and been re-estimated as a 21 overall as a result.

**Comment by yblain** [comment]
Related to #1962
