### ISSUE TITLE
Capture Language in Bookmark

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1277]
This issue should not proceed until https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275 is finished.

When the bookmark was first developed, the language of the map was dictated by the page it was hosted in.  Later on, the map tool was enhanced so that the language of the map could be changed without affecting the host page.  

The bookmark needs to capture this so the map ends up in the correct language.

This may require a bit of change in the order of how things are processed.

Currently (pre-1275) we do
- Load config file based on page language
- Modify config file based on bookmark contents
- Initialize map application with modified config file

Adding language means the bookmark will likely need to be parsed prior to the config file load step.  The changes introduced by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275 may also change the workflow completely.

**Comment by mweech** [comment]
@james-rae is this still an issue?

**Comment by milesap** [comment]
Rolling this into state storage work
