### ISSUE TITLE
Side menu ignores config changes

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1278]
Items are added to the side menu during the viewer initialization. When changing the language, a new config file is loaded but the side menu items are not updated.

Say `English` config enabled `shareable` and `French` config does not.
- Open the map (`English` is default)
- Check `Share` option is available in the side menu
- Switch language to French
- Check that `Share` option is still available

**Comment by jolevesq** [comment]
The problem is not just with the side panel. If I set overview enable false, the overview is still there after the language switch. When we switch language it should load the new config file because services can be different (English and French version).
