### ISSUE TITLE
WMS layer symbology taint map export canvas

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1279]
Since WMS legend is composed of actual images, they taint the export map canvas preventing it from being saved. (This will probably apply to any layer providing actual images (datauris are okay) as its symbology.)

A solution would be to load these images with `crossorigin="Anonymous"` but WMS services need to be CORS-enabled for that. Another solution would be to load images through out proxy.

In addition, since IE11 has mixed reports on crossorigin images we should test this out.
See https://reviewable.io/reviews/fgpv-vpgf/geoApi/161#-KUHp05QRhY10HlVHsHr for details.

**Comment by AleksueiR** [comment]
SVG doesn't support crossorigin attribute - need to load normally, convert to dataURL and then add to the SVG image. If image cannot be loaded with crossorigin, have to resolve to tainting the export canvas and let the user know how to save the image manually (#1281).

**Comment by AleksueiR** [comment]
GeoApi changes are PRed. This will be done when the viewer uses version of geoApi >= v1.0.7-2.

Out of three WMS layers in index-one page, only "Groundwater Information Network" layer is not CORS-enabled and its legend images will taint the export canvas preventing it from saving directly. Legends for "Railways" and "Grounwater" WMS layers can be saved directly as part of the map export image.

**Comment by bkutty** [comment]
Exporting with a WMS layer doesn't seem to be an issue anymore. Accepted
