### ISSUE TITLE
Let users save export image manually when something taints the canvas

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1281]
In cases when the export image canvas is tainted (wms legend images from a CORS-disabled service, see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1279), we cannot save the image directly. However, the user can save them image themselves by right-clicking on it and selecting `Save Image as...`.
- [x] output the final canvas to the export dialog if tainted canvas detected
- [x] display an updated error message explaining how to manually save the image

**Comment by jolevesq** [comment]
@AleksueiR Roght now there is already a message to tell the user the image cannot be saved. Can you just put the instruction on how to save manually with this message?

**Comment by AleksueiR** [comment]
Yes, but it's not that simple. The notification toast should only be used for short messages (per design guidelines), and we need to add the final image to the dialog so it can be saved (right now, if you check the dom, there are three separate images in the export dialog node - local, server, and legend; if you try to save them, only the top one will be saved).

**Comment by AleksueiR** [comment]
Because the solution does not apply to IE, I think it will be enough to add a short instruction to the tainted error toast, as @jolevesq suggested. Here:

![](https://i.imgur.com/IMzjc0B.png)

**Comment by mweech** [comment]
@AleksueiR @jolevesq Can we make an adjustment to this message so that it mentions "Due to browser security policies, " instead of "Oops" :)

**Comment by AleksueiR** [comment]
Error message's updated.
