### ISSUE TITLE
Share Link not working in IE11 for both Short Link and Long Link

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1284]
Tested build URL: http://fgpv.cloudapp.net/demo/release-v1.4.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

In IE11, although the dialog is shown up and "Click to copy" will display "Link copied to clipboard", but actually the URL is not copied. When pasting to a new tab in IE11, it is not the Link generated by Share Link in IE11, instead it just picks up whatever the previous copied item on clipboard.

![image](https://cloud.githubusercontent.com/assets/18723160/19574113/d800d16e-96d6-11e6-8a2c-d190bbe311c4.png)

**Comment by ChrisLatRNCan** [comment]
I have no share link displayed for: http://fgpv.cloudapp.net/demo/release-v1.4.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
![image](https://cloud.githubusercontent.com/assets/16193004/19899329/16eb08dc-a036-11e6-9420-6ca0b5d4a846.png)
However for http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
It works fine for me. In first place, IE11(version: 11.0.9600.18499) ask me if I allow the webpage to acces the clipboard. When I push "Allow access" it works as expected.
![image](https://cloud.githubusercontent.com/assets/16193004/19899413/6d9e2b00-a036-11e6-8f64-afbd59627e86.png)

**Comment by ChrisLatRNCan** [comment]
Found part of the problem here (bookmark.service.js):
`        function encodeInteger(value, bitSize) {
            const binary = value.toString(2);
            return '0'.repeat(bitSize - binary.length) + binary;
        }`
The repeat function is not supported by IE11 (support begins with Edge).
Reference: [http://www.w3schools.com/jsref/jsref_repeat.asp](url)
Possible Polyfill solution here:
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat](url)

**Comment by ChrisLatRNCan** [comment]
Will probabluy fix: Get Link and backtoCart not responding in IE11 #1323
Both Get Link and backToCart use encodeInteger

**Comment by IsabellaPan** [comment]
Nov 28
Short Link and Long Link still not working, tested with build: 
http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

**Comment by milesap** [comment]
WOMM; there is a pop-up that asks for permission to access the clipboard, so perhaps this defaults to deny for some users. Links appear, and can also be copied manually.

**Comment by alyec** [comment]
We may want to disable the clipboard copy altogether since it seems like a lot of GC users have the clipboard API disabled by group policy.  At that point it looks like the application is breaking because the user isn't presented with a prompt to allow the application to use the clipboard.

**Comment by ChrisLatRNCan** [comment]
Reminder: replace the copy to clipboard with a text box like it used to be
with text to copy/paste the url

**Comment by ChrisLatRNCan** [comment]
Like it or not. Need improvement ? It works in the three browsers.
![image](https://cloud.githubusercontent.com/assets/16193004/21273726/dbbb1952-c392-11e6-8f80-a70fabf35c1d.png)

**Comment by alyec** [comment]
Depending on how temperamental the focus manager is about such things we may want to automatically focus and select the text (so it's basically one action to copy on the part of the user).

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

**Comment by ChrisLatRNCan** [comment]
I'm trying to find the proper directive that will trigger URL selection automatically (to replace ng-click).
I've tried several ones blindly. Do you know a proper one ? 
`                <input ng-click="self.URLChanged($event)" ng-model="self.url" readonly>`

I've tried also a $scope.$watch using an ID but the DOM is edited, with the new URL, after the selection so the selection disappears with the old URL.
```
$scope.$watch('self.url' , function (val) {
    if (val) {
       $(document.getElementById("ID").select();
    }
});
```

I've tried also this and it works but it generates an error in the console.
```
$scope.$watch($(document.getElementById("ID") , function (val) {
    if (val) {
       $(document.getElementById("ID").select();
    }
});
```

**Comment by AleksueiR** [comment]
Tricky - you need access to the dom, but there is no `link` function for dialogs, so you can't get at the dialog container that way. 

Instead of opening the share panel, waiting for the link to be generated, and then focusing on it (this will unexpectedly move focus which is a no-no in WCAG), we can generate the link, then open the dialog, and focus on the field (get it using `element.find('some-css-class-of-the-input-field')`) as soon as the dialog is opened (I think the value should be already bound to the field by this point). You can add a `onShowing` callback (similar to one in the [export-service](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/export/export.service.js#L57)) to the [share dialog call here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/layout/shell.directive.js#L164).

Does this help?

**Comment by ChrisLatRNCan** [comment]
Absolutely it helps 👍 . However, I thought at first it would be much easier to get this done. So new experience for me 😄 Thanks

**Comment by ChrisLatRNCan** [comment]
Create a new service that generates links before the share-link panel is shown. The permanent text selection still not working.

**Comment by ChrisLatRNCan** [comment]
Notes:
-I'm losing the context of the element so the select cannot work properly.

**Comment by ChrisLatRNCan** [comment]
Waiting for IE11 to work again following last build

**Comment by ChrisLatRNCan** [comment]
Made progress. I'm able to have permanent link selection each time short link switch is triggered.
Now I need the link to be selected when dialog is first shown.

**Comment by ChrisLatRNCan** [comment]
Got it. Still have a selection delay on first dialog openning. Work with browsers trio. I'll PR those modifications.
![sharelink](https://cloud.githubusercontent.com/assets/16193004/22113502/79a39ae8-de34-11e6-9a5e-766ed3b49530.gif)
