### ISSUE TITLE
Make all layer 0.2 transparent when basemap selector is open

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1296]
When the basemap selector is opened, panels have their opacity reduced to make the changes of the basemap more visible. I think it would make sense to reduce the opacity of the visible layers for the same purpose.

**Comment by alyec** [comment]
Instead of messing with the layers directly can we simply place a translucent element covering the map and ordered between the map and the basemap selector?

**Comment by AleksueiR** [comment]
Oh, yeah, I was thinking of actually setting opacity on the dom objects. Forgot to mention.

**Comment by AleksueiR** [comment]
Everyone agreed this is a good idea :D

**Comment by IsabellaPan** [comment]
@milesap 
It seems the layers are much more dimmer than 0.86 transparent, see below screenshot.
![image](https://cloud.githubusercontent.com/assets/18723160/24013358/818666e2-0a57-11e7-87e0-4d7578836315.png)

**Comment by AleksueiR** [comment]
Yeap, this is correct. We changed the opacity value to 0.2, same as for the other chrome elements.
