### ISSUE TITLE
Unable to save or export map in IE due to connection Time Out issues 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1297]
Tested Build :http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html

While attempting to export, IE always gave the time out error. The map loads after a few minutes. However, the error persists and clicking on "Retry" just reloads the error. Please investigate

![screenhunter_2565 oct 26 14 14](https://cloud.githubusercontent.com/assets/18539315/19738888/fffad3a4-9b86-11e6-9b9c-7fca5ce38f56.jpg)

**Comment by AleksueiR** [comment]
Can you paste the full url, with all the layers added?

**Comment by bkutty** [comment]
Complete url : http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

**Comment by ChrisLatRNCan** [comment]
1. The presence of either JOSM or Airports causes the problem
2. Without thos two layers the image can be saved without error
3. Saving an image with the legend causes an error
More investigation to come...

**Comment by ChrisLatRNCan** [comment]
See also:
Map Export - JOSM & Airports layers not shown up on Exported Map (IE11 & Firefox)
#1306

**Comment by ChrisLatRNCan** [comment]
I begin to see the light. 
Adding this piece of string **xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"**
inside a SVG tag generated in the function generateLocalCanvas of the geoapi seems to solve a lot of problems.

Reference: 
[https://github.com/dnozay/innersvg-polyfill/pull/1](url)

**Comment by AleksueiR** [comment]
Maybe related to fgpv-vpgf/fgpv-vpgf#1324, fgpv-vpgf/fgpv-vpgf#1307, fgpv-vpgf/fgpv-vpgf#1306.

**Comment by ChrisLatRNCan** [comment]
It is related. As soon as the PR fgpv-vpgf/geoApi#167 is merged to the geoapi I'll double check.

**Comment by bkutty** [comment]
Issue Resolved based on tests on v1.4-07
