### ISSUE TITLE
Cannot view "ZoomScale" layer points on the exported map in Firefox v49.0.1

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1301]
Tested Build :http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

"ZoomScale" layer points are displayed on the map, however are not displayed in the Exported map. Legend seems to be incomplete too.This issue seems to be only in Firefox. Was a non issue in Chrome. Could not test in IE though due to the IE bug https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1297
Please investigate
Please note that points for service  http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer (also a zoom scale dependent layer) are displayed properly on the map as well as export.

![screenhunter_2567 oct 26 15 44](https://cloud.githubusercontent.com/assets/18539315/19742519/6543dbdc-9b93-11e6-817a-03a220e6ddc8.jpg)

**Comment by mweech** [comment]
Layer no longer available.  Cannot reproduce
