### ISSUE TITLE
Accessibility Issue- Empty links displayed for Layers

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1305]
Tested on :http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Please fix the empty links for the layers displayed below

![screenhunter_2574 oct 27 13 57](https://cloud.githubusercontent.com/assets/18539315/19779127/b28d566a-9c4d-11e6-867b-779350a3da28.jpg)

**Comment by ChrisLatRNCan** [comment]
Cannot replicate

**Comment by milesap** [comment]
Cannot replicate either, @bkutty please re-test and if still present provide additional details.

**Comment by bkutty** [comment]
Accepted. Sent another report using SortSite. Please review to see if we need to do any accessibility related fixes
