### ISSUE TITLE
Map Export - JOSM & Airports layers not shown up on Exported Map (IE11 & Firefox)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1306]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Although JOSM & Airports legends could be seen in exported map, all the map points for these two default layers went missing.

![image](https://cloud.githubusercontent.com/assets/18723160/19782719/0f3c4236-9c5d-11e6-81f4-63edbfb8d50a.png)

**Comment by AleksueiR** [comment]
This is likely a race condition between grabbing svg for Feature layers and hiding them before submitting a print task.

**Comment by AleksueiR** [comment]
Fix PRed in geoApi: https://github.com/fgpv-vpgf/geoApi/pull/167

**Comment by IsabellaPan** [comment]
Nov 25
Verified with build URL: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
