### ISSUE TITLE
Some User added Service Based Layers missing on Exported map (Firefox & IE11)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1307]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.4.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Added Polygons: 
http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

Check for layer "ProtectedAreaNationalView".
![image](https://cloud.githubusercontent.com/assets/18723160/19783635/aa384e9e-9c60-11e6-9df9-b620ada6752e.png)

**Comment by IsabellaPan** [comment]
Polylines as well, missing on exported map.
http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer/661

**Comment by AleksueiR** [comment]
Fix PRed in geoApi: https://github.com/fgpv-vpgf/geoApi/pull/167
