### ISSUE TITLE
chore(r&d): look into different options for creating help section

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#131]
One option is to do something similar to Reviewable help.

**Comment by AleksueiR** [comment]
Is this one still relevant?

**Comment by spencerwahl** [comment]
Not really, and we can always open it again if the current solution falls through

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/james-rae/milesdocfix/prod/samples/index-fgp-fr.html) |

Is it working as expected?
