### ISSUE TITLE
Dialogs have no opening animation

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1312]
When opening a dialog such as metadata, the dialog just appears immediately. There is a closing animation however. Tested as far back as version 0.17.0 and it seems to have never worked.

[Demo page](https://material.angularjs.org/1.1.0/demo/dialog) for angular material v1.1.0 as a reference for how it should look

[Demo page](https://material.angularjs.org/1.0.4/demo/dialog) for angular material v1.0.4 also has working examples (the version we used prior to 1.1.0)

**Comment by milesap** [comment]
This is a [known issue](https://github.com/angular/material/issues/8560) with the angular material team, where the fix [has yet to be merged](https://github.com/angular/material/pull/8856). Tested with version 1.1.1 (we are on 1.1.0) with same results. I can confirm the issue is associated with `$mdDialog` where `templateUrl` is used, opening animations work fine with `template`.

**Comment by bkutty** [comment]
Accepted as tested on v1.6.0-1
