### ISSUE TITLE
Get Link and backtoCart not responding in IE11

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1323]
Tested build :http://fgpv.cloudapp.net/demo/v1.4.0-4/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Get Link and backtoCart features are not working/responding in IE11. These functions still work in Chrome and Firefox. Please fix the issue

![screenhunter_2594 nov 02 14 49](https://cloud.githubusercontent.com/assets/18539315/19943000/ff78a28c-a10b-11e6-8f32-ea0cab6bfda8.jpg)

**Comment by ChrisLatRNCan** [comment]
Has been fixed by: fix(core): add string.repeat polyfill for IE #1352
It works on version 1.4.0-5

**Comment by IsabellaPan** [comment]
Nov 25
Verified with build URL: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
