### ISSUE TITLE
User added file-based layers not displayed on exported map

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1324]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.4.0-4/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Test Data
 JSON: jappy.json
 CSV file: rc_cdr.csv
 Shapefile: ne_10m_ports.zip

![image](https://cloud.githubusercontent.com/assets/18723160/19944201/2a5d9520-a111-11e6-8547-cf932eedbad6.png)

**Comment by AleksueiR** [comment]
Related #1306 and #1307.

**Comment by AleksueiR** [comment]
Fix PRed in geoApi: https://github.com/fgpv-vpgf/geoApi/pull/167

**Comment by IsabellaPan** [comment]
Nov 25
Verified with build URL: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
