### ISSUE TITLE
Include time in ESRI date field formatting

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1330]
Our formatting code for ESRI date fields is currently dropping the time portion.  Add some logic to include the time if the time is present (i.e. if time is `0:00:00`, keep formatting as-is).

Decision:  How to format the time?

* Time zones? UTC time? Convert to user local time?
* Formatting?  ISO looks bad: `2016-11-04T14:36:45.466Z`

Code location to change:
`layer-record.class.js`
```
// convert each date cell to ISO format
fieldNameArray.forEach(fieldName => {
	rows.forEach(row => {
		const date = new Date(row[fieldName]);
		row[fieldName] = date.toISOString().substring(0, 10);
	});
});
```

**Comment by milesap** [comment]
As far as formatting, I prefer something like `9:15 PM GMT` personally. On the subject of user timezone conversions, [Google Maps](https://developers.google.com/maps/documentation/timezone/intro) can provide useful things such as `timeZoneName`, `dstOffset`, and `rawOffset` for a given location.

**Comment by AleksueiR** [comment]
Using Angular `$filter` to format time:
```js
$filter('date')(new Date(), 'yyyy-MM-dd hh:mm:ss');
```

Used in legend export: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/export/export.service.js#L198

**Comment by james-rae** [comment]
If we use angular, I believe we will have to add a timezone parameter

`$filter('date')(new Date(esriDataValue), 'yyyy-MM-dd hh:mm:ss', 'UTC');`

**Comment by milesap** [comment]
Two options so far for getting the timezone:
- A script like [this one](http://pellepim.bitbucket.org/jstz/) for local browser timezone detection. 
    - It's an extra ~12kb in size. 
    - Fairly accurate (most likely good enough)

- Using the Google API
    - This requires a geolocate call first for their lat/lng position. 
    - So a google api key is required for this to work, otherwise default to GMT?
    - Very accurate

**Comment by AleksueiR** [comment]
[Moment/timezone](http://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/) is also a good one.

**Comment by james-rae** [comment]
For what it's worth, the angular filter does convert to user's local timezone (I just tested it).  But it won't show the timezone in the output string.

**Comment by milesap** [comment]
You could make a custom date filter in angular which only makes a Google Geolocation request if one has not already been determined, This avoids asking the user for permission to get location data for displaying data. If there is no Google api key just use GMT as default. [This function](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/locate.service.js#L79) can be used in that filter.

**Comment by mweech** [comment]
My vote is to stick with UTC initially.  Timezone could be set either by user choice (i.e. left side menu/viewer settings?), or via a library/api call as Miles has mentioned.  Either way, lets just get the time showing initially.

**Comment by james-rae** [comment]
proxy-friendly [sample service](http://section917.cloudapp.net/arcgis/rest/services/TestData/TimeParty/MapServer/0) with date/time field  
`http://section917.cloudapp.net/arcgis/rest/services/TestData/TimeParty/MapServer/0`

**Comment by IsabellaPan** [comment]
Feb 22 2017
Verified with build http://fgpv.cloudapp.net/demo/v1.5.1-1/prod/samples/index-fgp-en.html?keys=Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
