### ISSUE TITLE
IE11 - Unable to load any basemaps in Mercator projection 

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1339]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-4/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

As Visualiser defaulted basemap to Transportation (with label) under Lambert, when selecting any basemap in Mercator gallery, the check mark appeared to indicate the selection, but the map was not changed at all.

![image](https://cloud.githubusercontent.com/assets/18723160/20107345/34bb953c-a5a6-11e6-907f-16fa9a6041d1.png)

**Comment by alyec** [comment]
Probably needs https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#Polyfill

**Comment by alyec** [comment]
Same fix as #1284

**Comment by IsabellaPan** [comment]
Nov 25
Verified with build URL: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
