### ISSUE TITLE
Legend Panel and map points disappear in Firefox on changing basemaps after performing an Export

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1340]
Tested Build :http://fgpv.cloudapp.net/demo/v1.4.0-4/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Legend Panel is empty in Firefox when basemaps are changed. This is seen after performing/initializing export map feature. Please investigate

This issue could not be reproduced in Chrome. Could not test in IE due to bug https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1339

**Steps to Reproduce**

Load the Viewer in Firefox
Go To Full Screen
Add a File based or Service based layer to the Viewer
Export/Initiate Export map
Close the export window
Change Basemap (different projection)
Legend Panel blanks out . Map points are also not visible

![firefox blank legend](https://cloud.githubusercontent.com/assets/18539315/20116537/9a2fcb58-a5ca-11e6-9baf-4470f8ce16a1.PNG)

**Comment by bkutty** [comment]
Issue can also be reproduced without adding a File based layer

**Comment by milesap** [comment]
Tested on http://fgpv.cloudapp.net/demo/v1.4.0-6/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley w/ FF and IE - issue can no longer be reproduced
