### ISSUE TITLE
Automate weekly builds and release notes

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1342]
This script needs to:
- run every tuesday
- create builds from all release branches (`develop` and all `vX.X` branches)
- compile release notes using conventional changelog or something similar for all release branches from the previous weekly build
- increment version numbers and commit them
- tag version increments
- bonus points for not using coffeescript

**Comment by alyec** [comment]
## Versioning proposal

- auto builds will not tag with the conventional `v#.#.#-#` style tags.  They will continue following semantic versioning but will use a different prefix (e.g. `weekly-#.#.#-#`)
- all auto builds will be pre-release marked (i.e. `-#` suffixed)
- the version will always be based on the the version from `package.json`
  - if the package version is a pre-release already it will be incremented (`A.B.C-D` -> `weekly-A.B.C-(D+1)`)
  - if the package version is a full release it will have its minor version incremented (`A.B.C` -> `weekly-A.(B+1).0-1`)
