### ISSUE TITLE
Fix legend scrolling issue caused by dragula reordering

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1343]
### Issue

Using a touch device, you cannot scroll the legend by swiping up/down as you'd normally expect. Instead, you end up reordering legend items (via [dragula](https://bevacqua.github.io/dragula/)). 

### Expected behaviour

If `touch mode` is active, only reorder items on a long press. A long press is defined as a continuous press of >= 1 second and the press location does not change (or only very slight changes of a few pixels).

### Additional information 

There has been a [proposed feature](https://github.com/bevacqua/dragula/issues/289) for dragula to better support touch/mobile applications. Unfortunately, there is no straight forward way to achieve this in the dragula API directly.

**Comment by bkutty** [comment]
Accepted. Tested v1.5.0 in Browserstack.
