### ISSUE TITLE
Zoom to feature small/medium layout improvement

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1344]
### Issue

Currently, when you open the datatable in small or medium layouts it takes up the entire viewport. As a result, when you press the zoom to feature it appears to do nothing. While the map does zoom to the feature, this is visibly blocked by the datatable.

### Expected Behaviour

For small or medium layouts, when clicking on zoom to feature, set the datapanel (and any underlying panels) to transparent so that the map is visible to the user and they can see the change. When the user clicks/touches anywhere, restore the transparent panels to original opacity so they are back to the datatable. If they would like to interact with the map they would need to close the datapanel (and any underlying panels).

**Comment by AleksueiR** [comment]
Make it almost transparent, but not fully (0.14 opacity should work, it's the same level of transparency of the panels when the basemap selector is opened).
