### ISSUE TITLE
It's not possible to save a tainted canvas in IE, even manually

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1348]
Chrome and Firefox support saving canvas objects (event tainted ones) via the right-click menu ("Save image as..." option). IE does not support this functionality.

It is not possible to save the export map image if any of its parts (layer symbology or print service image) are tainted. This is the IE limitation there seem to be no way around, unless we can use a server-side functionality to generate the map export image.

See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1281 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1279 for more information.

**Comment by mweech** [comment]
@AleksueiR : is there some way we can test if a WMS/legend is not CORS enabled, and in that situation indicate that the "This service is not CORS enabled, causing the Legend graphic to be omitted.  Please contact the service provider to request their service be CORS enabled."
