### ISSUE TITLE
Design map state format and implement serialize and deserialize functions

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1358]
- [ ] document state format
- [ ] implement state capture and serialization
- [ ] implement deserialization
  - [ ] handle language switch events
  - [ ] handle reprojection events

**Comment by alyec** [comment]
Map state is now a subset of the v2 schema.  Most of the work is dependent on legendService refactoring which is currently in progress #1291

**Comment by mweech** [comment]
replaced by #1962
