### ISSUE TITLE
French - Canada View going to scale of 1000km and including South America

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1361]
Tested build URL: http://fgpv.cloudapp.net/demo/weekly-1.4.0-5/prod/samples/index-fgp-fr.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

It seems the Canada View map intended to include not only Canada scope but also South America. The scale goes to 1000km which is not consistent with English version Visualiser (400km scale for Canada View)
![image](https://cloud.githubusercontent.com/assets/18723160/20192168/b6a2dce8-a756-11e6-8feb-73e795109549.png)

**Comment by ChrisLatRNCan** [comment]
I suspect this addtional config text in the extentSets part of the config.fr-CA.json:

        "full": {
          "xmin": -4282638.06150141,
          "ymin": 3153821.09213678,
          "xmax": 4852210.1755664,
          "ymax": 4376714.4420974,
          "spatialReference": {
            "wkid": 3978
          }
        }

**Comment by ChrisLatRNCan** [comment]
Cannot replicate. Test done with the three browsers and keys on/off.

**Comment by bkutty** [comment]
This is no longer an issue. Tested on v1.4.0-7

**Comment by bkutty** [comment]
Please note that this issue still remains as tested on http://fgpv.cloudapp.net/demo/v1.4.1-1/prod/samples/index-fgp-fr.html?

**Comment by mweech** [comment]
reproduced during QA review.

**Comment by ChrisLatRNCan** [comment]
Ok I previously had a different understanding of the problem. 
So to rephrase the issue: By pushing the Canada view button we get a all North-America view when we should just get Canada.

**Comment by ChrisLatRNCan** [comment]
My first guess was right: I removed
`    "full": {
      "xmin": -4282638.06150141,
      "ymin": 3153821.09213678,
      "xmax": 4852210.1755664,
      "ymax": 4376714.4420974,
      "spatialReference": {
        "wkid": 3978
      }
    }`
in config.rcs.fr-CA.json and config.fr-CA.json to standardize with english config file. Reorder some lods node also.
