### ISSUE TITLE
Missing check mark on blank map selector when switching from other projection

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1362]
Tested build: http://fgpv.cloudapp.net/demo/weekly-1.4.0-5/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

This issue refers to two scenarios:
1.From any base map in Lambert gallery, select Blank Map in Mercator Maps gallery.
2.From any base map in Mercator gallery, select Blank Map in Lambert Maps gallery.

![image](https://cloud.githubusercontent.com/assets/18723160/20193310/7320dce0-a75b-11e6-862e-6a331bd7e2c2.png)

**Comment by ChrisLatRNCan** [comment]
With my local build I experimented just the second scenario. The check mark appears and then vanishes.

**Comment by ChrisLatRNCan** [comment]
Almost there. I had to add a test when we reload blank basemap so I can set the selected blank basemap to true (basemap.service). It just happens when we change the projection because we then reload all the basemap.

**Comment by ChrisLatRNCan** [comment]
The result:
![checkblank](https://cloud.githubusercontent.com/assets/16193004/21019153/7da0593c-bd3d-11e6-9340-363fb1c91ebd.gif)

**Comment by IsabellaPan** [comment]
Jan 24 2017
Fixes could be verified in build http://fgpv.cloudapp.net/demo/v1.5.0-15/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
