### ISSUE TITLE
AppInfo service is shared among viewer instances

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1363]
This happens because plain object Angular services (value and constant services) and not initialized with something like `Object.create` and remain shared between app instances. A fix involves adding some simple initialization to the service.

**Comment by mweech** [comment]
Can be tested on index-many.html pages.

**Comment by bkutty** [comment]
Leaving this open for now due to the bug https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1531
