### ISSUE TITLE
Missing "Filter by Extent" icon in the Legend Panel when projections are switched

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1365]
Tested build :http://fgpv.cloudapp.net/demo/weekly-1.4.0-5/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

**Steps to Reproduce**

-  Load the url. 
- Once all the layers are loaded, open the datapanel for JOSM layer
-  Enable "Filter by Extent" icon
- Icon also appears on the legend panel as expected
- Change the basemap to Mercator
- Datapanel remains on the map with the "Filter by Extent" option enabled
- The icon does not appear in the Legend Panel however.

![filterbyextent](https://cloud.githubusercontent.com/assets/18539315/20271595/4cb7a7c2-aa59-11e6-97b5-a31790b291d6.PNG)

**Comment by james-rae** [comment]
Depends on https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275 . As app works right now, filter settings are not captured in the bookmark, and the bookmark is what drives a projection switch.  The refactor should allow all state to be preserved during the switch.

**Comment by JahidAhmed** [comment]
Waiting until #2017 is resolved
