### ISSUE TITLE
Modify text "transparence" for "opacité" for more coherence with slider widget

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1366]
As it is right now 
![image](https://cloud.githubusercontent.com/assets/16193004/20274976/b09a21d8-aa64-11e6-8c63-1fcb9c53080d.png)
As it is right now 100% is more opacity and not more transparency.
It is self correction since I was the one who translated that.

**Comment by bkutty** [comment]
Accepted. Tested build - v1.4.0-7
