### ISSUE TITLE
Save export open in a new tab in Safari

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1368]
When we save the export image (canvas), instead of saving the file, it open in a new tab.

https://www.npmjs.com/package/file-saver#safari-61

**Comment by milesap** [comment]
On an iPhone/iPad when you export an image a new tab is opened as well. This makes it easy to see the image and/or save it to the device. With desktop, safari has less than 2% market share. Considering this is not a major issue I'd suggest this as a no fix.

**Comment by bkutty** [comment]
Working as designed.
