### ISSUE TITLE
The viewer container is violently displaced after switching projections

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1376]
On latest dev fgp-en page.

- open basemap selector
- switch basemap 
- wait for it to fully load
- click on the map to close the basemap selector
- observe the viewer being shoved to the left

![jumping_basemap](https://cloud.githubusercontent.com/assets/2285779/20349492/b7208bf8-abd8-11e6-8e9d-9f4506937e5e.gif)

**Comment by mweech** [comment]
bonus points for a great issue name! :star:

**Comment by bkutty** [comment]
Tested on v1.4.0-7

Still getting this issue in Chrome. Please investigate. Got Displaced map usually when a blank map is selected from the basemap selector. Reopening the issue


![image](https://cloud.githubusercontent.com/assets/18539315/20716042/17fda4b0-b61f-11e6-8ae6-918ae6ce3a3c.png)

**Comment by milesap** [comment]
@bkutty Could not reproduce this issue, could you post a detailed list of steps or a gif of this?

**Comment by AleksueiR** [comment]
I could reproduce it once, but not consistently.

**Comment by milesap** [comment]
Sounds like the `$timeout` delay needs to be increased :expressionless:

**Comment by AleksueiR** [comment]
Why does it only happen to the basemap selector and not to the side menu? There must be a difference somewhere.

**Comment by bkutty** [comment]
@milesap I cannot reproduce this issue consistently. Issue occurs when changing projections and then clicking the map.But I do notice that the left hand side panel also moves to the left in v1.4.0-8.

![screenhunter_2654 nov 30 15 15](https://cloud.githubusercontent.com/assets/18539315/20769882/ba9384f4-b711-11e6-8016-a385731e881a.jpg)
