### ISSUE TITLE
Focus dialog something skipped

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1377]
I noticed that skipping the focus dialog and then pressing Shift + Tab sometimes sets focus on the viewer directly without triggering the dialog. I think it might be related to that 200 ms delay - if `Shift + Tab` is pressed in that time window.

- tab to the viewer
- see the focus dialog popup
- press `Shift + Tab`
- press `Tab` again quickly
- the viewer gets focus without the focus dialog

**Comment by IsabellaPan** [comment]
Mar 9 2017
Verified with build http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
