### ISSUE TITLE
Set up Protractor test engine on geoApi

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1380]
Will allow us to write additional tests that use the real ESRI API.
* More real-world tests
* Less mocking fake APIs
* Extra checks when we bump a minor version of ESRI API

Ideally, setup files can be stolen from the viewer, and Angular parts removed

**Comment by milesap** [comment]
Issue moved to [fgpv-vpgf/geoApi #221](https://github.com/fgpv-vpgf/geoApi/issues/221) via [**ZenHub**](https://www.zenhub.com/)
