### ISSUE TITLE
Create a reset CSS for the viewer to prevent bleeding of host page styles

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1382]
CSS bleeds all over the place:
http://section917.cloudapp.net/NEB/
![](https://i.imgur.com/9lyQao7.png)

http://fgpv.cloudapp.net/demo/users/milesap/1241-touch/prod/samples/index-fgp-en.html?keys=Airports
![](https://i.imgur.com/YF5qlKZ.png)

**Comment by mweech** [comment]
Good example of this: http://section917.cloudapp.net/NEB/

**Comment by AleksueiR** [comment]
No progress yet. Was working on issues from usability report.

**Comment by AleksueiR** [comment]
This turns out harder than I thought - any resets we implement can be easily overwritten by the host page styles with `!important` or just selector with higher specificity. 
One potential option to explore is [Scoped CSS](http://caniuse.com/#feat=style-scoped), but it's not widely supported and involves injecting styles directly into the page (something we might not want to do).

For now, we can just reactively patch any found style leaks...

**Comment by AleksueiR** [comment]
Webpack transition might provide a way to solving this issue. Needs some R/D.

**Comment by AleksueiR** [comment]
With Webpack, our styles can be isolated from the host page, but the host page styles can still affect the viewer if they target all html elements like `h1..5`, `a` `div`, or `span` on the page. I don't think it's possible to prevent this except by using an iframe or using custom html elements.

**Comment by milesap** [comment]
No viable solution at this time, closing
