### ISSUE TITLE
Make a nicer identify icon

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1386]
the current one is ugly.

**Comment by james-rae** [comment]
![identifyv2](https://cloud.githubusercontent.com/assets/7585245/20405279/6157136e-acd6-11e6-8a59-e7b8318fc315.jpg)

**Comment by AleksueiR** [comment]
#### New Icon:
![](https://i.imgur.com/yaXYBZC.png)

#### New Behaviour:
- initial click on the map will place the icon at the click point
- as identify results are received and the selected layer has non-null results, the identify icon is removed and the features in the result set are highlighted
- if another layer in the details layer list is selected which has no results, the identify icon is placed at the click point
- if the map is panned or zoomed, the identify icon and feature highlights are removed
- if a layer in the details layer list is selected after the map is panned or zoomed, the identify icon or feature highlights are restored
