### ISSUE TITLE
First column in CSV data export is always blank

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1394]
Tested:http://fgpv.cloudapp.net/demo/users/milesap/build-1.4.0-6/prod/samples/index-fgp-en.html?keys=JOSM,Airports,ZoomScale,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Barley#/wb-cont

When data is exported to csv format, the first column in the exported file is always empty. Data is populated only from the 2nd column. Please investigate

![csv export](https://cloud.githubusercontent.com/assets/18539315/20434486/f7034848-ad75-11e6-9a4c-2c7ff3e79ddb.PNG)

**Comment by bkutty** [comment]
Could not see the fix in v1.4.0-7

**Comment by AleksueiR** [comment]
This is a fix for 1.5 version. It won't be available in 1.4.x. 
You can tell because this issue is labeled with `v1.5.0`.

**Comment by bkutty** [comment]
This issue is now fixed
