### ISSUE TITLE
Clicking "Point Information" button closes the details panel 

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1399]
Clicking "Point Information" button should collapse the details panel, instead of closing it.

![](https://i.imgur.com/e7J15Vr.png)

**Comment by ChrisLatRNCan** [comment]
The problem here is that the wrong toggleDetails is called. We want the one found in directive rvDetailsRecordEsrifeature. We need one also for rvSVG when we have OGC WMS html records.
Still need to be tested and validated.

**Comment by ChrisLatRNCan** [comment]
@AleksueiR I think it will make more sense to still use the "Point information" button to close the details panel and use the X in the details panel to collapse the panel (selected records only and not the icons with count and layers name). Moreover we could replace the X by double arrows like the one used to collapse the menu. What do you think ?

**Comment by AleksueiR** [comment]
Closing the details panel with the "Point Information" button will break consistency as you can't close the legend panel for good with the "Legend" button. 

Think of the icons in the appbar as a tabbed interface - usually you can only switch between tabs, not close them (if cases where you can close them, there is a separate close button for that).

The "X" button is also used in the import layer wizard. If we change "X" to "<<" in the details panel, it will create an additional way to close/collapse panels, again breaking consistency.

**Comment by AleksueiR** [comment]
@ChrisLatRNCan I'm sorry I stole your issue, but I really want this to be included in 1.4.

**Comment by IsabellaPan** [comment]
Dec 14 verified with build:
http://fgpv.cloudapp.net/demo/v1.5.0-2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
