### ISSUE TITLE
Datagrid does not go properly from maximize view to split view in Safari

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1404]
When we switch from maximized view to split view the datagrid is not draw properly

![screen shot 2016-11-23 at 2 16 40 pm](https://cloud.githubusercontent.com/assets/3472990/20575513/991d3dae-b187-11e6-9a91-134a50b1cfee.png)

**Comment by bkutty** [comment]
Accepted as tested on build http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=EcoAction. (using browser stack Safari 10.0)
