### ISSUE TITLE
Change state and settings declarations in the schema

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1409]
Make a new major version of the schema to simplify the structure and better separate state from controls.

- [x] update layer settings and state in the new schema (design listed below)
- [x] add conversion script for `1.x` to `2.0` schemas built into the viewer
- update relevant docs (moved to #1648)

**Comment by alyec** [comment]
Notes from @AleksueiR 

### Legend Entry Controls

Legend entry controls indicate which layer action are available to the user through the legend UI. The following list includes all possible layer actions:

```js
availableLegendEntryControls: [ 
    opacity, 
    visibility, 
    boundingBox, 
    query, 
    snapshot, 
    metadata, 
    boundaryZoom, 
    refresh, 
    reload, 
    remove,
    metadata,
    setting,
    data
]
```

Schema's definitions for basic layer types (Feature, Dynamic, WMS, etc.) will contain subsets of controls available for that layer type (for example, Dynamic layers do not have a `snapshot` controls).

In config's layer definition, the map author can specify which controls should be available for each layer (supplied as an array of strings):

```js
layer: {
  ...,
  controls: ['visibility', 'opacity', 'remove']
}
```

In the above example only `visibility`, `opacity` and `remove` controls are available to the user. Omitting this property enables all default controls for that layer type. Providing an empty controls array, hides all controls from the user.

### Initial Layer Settings

Initial layer settings set up the layer's state when it's added to the map. These are layer settings that can be specified in the config and their defaults: 


```js
initialLayerSettings: {
    opacity: 1,
    visibility: true,
    boundingBox: false,
    query: true,
    snapshot: false
}
```
In config's layer definition, the map author can override these defaults:

```js
layer: {
  ...,
  state:{
    opacity: 0.5,
    snapshot: true
  }
}
```

To simplify the schema, checking validity of supplied state settings is checked at the build time (in authoring tool?). If a setting is supplied that does not applied to its layer, it's ignored (a warning console statement is logged).

**Comment by AleksueiR** [comment]
Could you please also add `googleAPIkey` to the schema as it's missing:
```json
"googleAPIKey": { "type": "string", "description": "Google API key to enable geo location and share link shortening." },

```

**Comment by alyec** [comment]
Schema work is on https://github.com/alyec/fgpv-vpgf/tree/schema2 ; splitting docs into a separate issue as that will probably happen after geo module refactoring
