### ISSUE TITLE
UI datagrid filters for large layout

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1417]
When #1416 is done.

- [x] Large Layout (Desktop)
     - [x] Add Filters Row (set filters from Datagrid for string, number, date)
     - [ ] Add filters for thematic map  (from filters setting, selection list)

**Comment by jolevesq** [comment]
I will not implement selection filter because it will be use for thematic map. It will be done later.

**Comment by jolevesq** [comment]
This issues will be merge with #1416

**Comment by mweech** [comment]
@jolevesq Lets split out the thematic map based functionality into its own issue.
