### ISSUE TITLE
Improve management of OGC WMS GetFeatureInfo request return when there's no data

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1420]
From OGC WMS specifications:
**7.4.4 GetFeatureInfo response
The server shall return a response according to the requested INFO_FORMAT if the request is valid, or issue a service exception otherwise. The nature of the response is at the discretion of the service provider, but it shall pertain to the feature(s) nearest to (I,J)**

Actually, when there's no data returned by the service we can manage empty string or the error message string 'Search returned no results'. We want to be able the cope with different kinds of return or a least a definite set of returns.

- [ ] Inventory of WMS GetFeatureInfo returns when there is no data for the requested position (use GeoServer, MapServer, Esri as the basis for initial look)

- [ ] Identification of possible solutions (code enhancement, plugins, etc) 

- [ ] Implemention of the chosen solution (could be hybrid of possible solutions)

**Comment by mweech** [comment]
@ChrisLatRNCan thanks for documenting this.  this is the challenge with open-ended standards, essentially it says that there is no standard response.  given that scenario, our interim approach is to handle the service exception case and return the results otherwise.  the service standards group should be alerted re: "nothing found" responses and standardize an acceptable response when no results can be found.

**Comment by mweech** [comment]
related to #1411

**Comment by ChrisLatRNCan** [comment]
Getting this error when trying to do an Identify on http://maps.geogratis.gc.ca/wms/railway_en:
`msWMSLoadGetMapParams(): WMS server error. Invalid layer(s) given in the LAYERS parameter. A layer might be disabled for this request. Check wms/ows_enable_request settings.`
Happens when there's at least one layer loaded (I loaded every layers avalaible) that doesn't support the GetFeatureInfo.
Will start another issue for that bug.
Also, using the identify tool on a feature and then using the identify where there's no data won't remove the previous record in the panel (will start another issue for that one) . Need to check for othe kind of layers.

**Comment by mweech** [comment]
Closing this issue as we won't employ a WMS specific handling of errors, but would look at the issue at this point as an overall service error handling approach (i.e. service error console output).
