### ISSUE TITLE
Zoom scale dependent layers are displayed in the Legend even when it is out of scale in the Viewer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1422]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Zoom scale dependent layer information is captured in the legend  of the exported map even when it is out of scale in the Viewer. Please advise the correct behaviour

![zoom scale layer](https://cloud.githubusercontent.com/assets/18539315/20671064/c56ff5b6-b549-11e6-8190-fdd59531c964.jpg)

**Comment by mweech** [comment]
i would suggest that this layer should be omitted from the legend as it is out of scale.

**Comment by AleksueiR** [comment]
Do not display - if it cannot be possible visible on the map image, it shouldn't be in the legend.

**Comment by alyec** [comment]
This is going to get even more fun with WMSes where out of scale is a suggestion and not a hard requirement.  I agree for ESRI layers.

**Comment by AleksueiR** [comment]
Since we can't determine if the wms layer is visible on the map, its legend should always be included.

**Comment by JahidAhmed** [comment]
Fixed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2370
