### ISSUE TITLE
Change "Show Legend" tooltip

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1426]
- [x] Change "Legend" heading to "Layers" ("Couches" in French)
- [x] Change "Show Legend" tooltip to "Show Layers"

The panel was initially called "Layers" and it was renamed to "Legend" because of feedback that some users were confused by what "Layers" mean.

**Usability Issue:**
V3. Legend confusion (Type: Labelling)

Testers were confused by the “Legend” tooltip and “Legend” title and felt that a more descriptive word might be“Layers” or in French “Couches”.

**Comment by IsabellaPan** [comment]
As the tooltip still says "Show Layers" after all layers are displayed. Click on this button again actually will hide all layers. It is suggested to change the tooltip to something like "Layers".
Discussed with James & Alex.
