### ISSUE TITLE
Greater Feedback provided when clicking Continue in Add Layer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1428]
Progress indicator is being blocked by JS crunching numbers when importing a layer. UI thread is being blocked and all animations (expect for CSS transform animation are stalled).
##### Options:
- Add a notification explaining the app might feel unresponsive while data is processed (quick!)
- Custom css animation which is not blocked
- Offload processing to a web-worker (IE might support web-workers in a special way)

**Usability Issues:**
V8. Import final “Continue” buttonc onfusion (Type: Functionality)

After pressing the final “Continue” to import a layer, there is no indicator that the application is working, so the testers pressed the “Continue” button several times and wondered if it was working.

**Comment by AleksueiR** [comment]
:+1: to adding a notification

**Comment by milesap** [comment]
Would we want a notification just below the continue button like so:

![untitled](https://cloud.githubusercontent.com/assets/10187181/21185939/a7cc8fe4-c1e0-11e6-8cd3-d05e30288009.png)

**Comment by AleksueiR** [comment]
I would put it above the continue button. Also add 'md-caption' class on it.
