### ISSUE TITLE
feat(ui): add an empty state to the layer selector

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#143]
f no layers/services are configured for RAMP to display, display an empty states in place of the layer selector.

Possible empty states:
- user added layers component (if component is enabled)
- if no layers and none of above components are available.. sad robot.

[Empty states.](http://emptystat.es/)

Acceptance criteria:

- When an empty state is applied, the layer selector should be explicitly opened.

**Comment by mweech** [comment]
Removed from Usability results epic.  Will remain in backlog and handled as a feature request.
