### ISSUE TITLE
Intermittent Bug with Layers being indicated as Failed to Load

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1433]
Intermittent bug that indicates a layer has failed to load if it fails an initial load attempt.  Successful attempt is not indicated in the legend.  

May be wise to wait until Thematic Map related refactoring is complete.

**Usability Issue:**
V16. Thin red vertical bar in legend (Type: Labelling)

At some points in the usability tests, a thin red vertical bar appears beside someof the layers in the legend section and the testers would ask why (maybe it hasto do with the point information functions?). Testers tried to scroll it, and tried to click on it and still did notknow what it was for.

Comments:

**Comment by AleksueiR** [comment]
Agree, it will be redone during the thematic legend refactor - no sense in spending time on it now as it's not blocking or breaking any of the viewer functionality.

**Comment by mweech** [comment]
Removed from Usability results epic.  Will remain in backlog as an issue likely to be obsolete after refactoring.

**Comment by mweech** [comment]
Moved from Blocked to "To Do" as refactoring will not be completed for inclusion in an R2 release and this occurs too frequently to ignore.
