### ISSUE TITLE
Change Labeling to Address Navigation Issues

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1434]
- [x] change Point Information panel to "Feature Details"
- [x] change Get Link to "Share" with the Android icon for share (< with 3 dots)
- [x] Change symbology stack tooltip to “Legend details” or “Expand legend"
- [x] Update Import Layer tooltip to "Add Layer"

**Usability Issues:**

### V5. Symbology confusion (Type: Labelling)

Once testers clicked open the symbology(most required assistance to get there) they felt a more intuitive term forthat function’s tooltip would be “Show legend” or in French “Afficher lalégende”

### V7. Plus icon confusion (Type: Labelling)

Once the testers opened the legend they needed to interpret the plus icon to mean import; some testers asked that the icon be replaced by the text “Import”.

### V17. Point information confusion (Type: Labelling)

Testers were confused why it was called “Point Information” when it can also contain information about polygon and line features

### V23.  Get link confusion (Type: Labelling)

Testers were looking for text such as “Share link” with a recognizable icon such as (box with arrow icon) or (less than symbol with dots icon) instead of the “Get Link” button.

**Comment by AleksueiR** [comment]
Need French translations.
