### ISSUE TITLE
Please change "Help summary" to French in the French version

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1437]
Tested: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Please change the title "Help Summary" in French under Help.

![help](https://cloud.githubusercontent.com/assets/18539315/20681914/b0baee94-b573-11e6-9a48-b622d3513e40.PNG)

**Comment by ChrisLatRNCan** [comment]
The header of the panel has been modified. Change is no more necessary.

**Comment by bkutty** [comment]
Accepted
