### ISSUE TITLE
Back to Cart available within the Viewer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1438]
Due to viewer not being in full control of host page state, need to allow for the viewer to call back to the host page.

**Usability Issue:**
V21.  Disappearing get link and map cart (Type:Functionality)

After pressing the full screen button, testers found that the get link and map cart buttons are no longer visible or usable.

##### Idea 1:
We add a rv-cart-callback attribute on the viewer. If present we add Back to Cart on the menu, the contents of the tag is the name of a JS function which we call when Back to Cart is clicked. We mark this as deprecated from the moment we add it, but we agree to maintain this code through the v1.x line. When a plugin API gets developed we add a wrapper which calls the relevant plugin to keep backwards compatibility.
##### Idea 2:
Create RV.registerPlugin with basic support. registerPlugin( initFunction(), RV.PluginTypes.MENU ) where RV.PluginTypes would only have MENU for now.
Also create RV.MenuPlugin which every menu plugin must subclass. It would be a relatively simple interface of the form:
Plugin { getText( langShortCode ), onClick() }

**Comment by AleksueiR** [comment]
:+1:  to __Idea 2__.

It seems relatively simple, gets us closer to adding plugin support, and potentially means less work on maintaining backward compatibility.

**Comment by alyec** [comment]
Add a translation loading call.  Translations should only be added (throw error on any attempt to modify existing strings).

**Comment by alyec** [comment]
Related API functionality refactoring #1565
