### ISSUE TITLE
Legend wrapping optimization corner cases

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1439]
There seem to be some corner cases where legend wrapping optimization gets confused:

- [ ] special wrapping functions (`packLayersIntoExactSections` and `packLayersIntoOptimalSections`) are not used in cases of 1 layer per section allocation. https://files.gitter.im/AleksueiR/ZzT3/rv-app-0---2016-11-28-11-34-50.png
- [x] when only one section is available, the splitting logic does not (correctly) produce any splits and fails trying to assign the splits; probably just needs a check to not run optimization if only one section is available

**Comment by mweech** [comment]
obsolete
