### ISSUE TITLE
Allow all layers to have visibility toggled on/off

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1440]
- [x] add a toggle button next to "Add Layer" when the Legend is open that will toggle visibility of all layers
- [x] Create mockups to consider a seperate line of "tools" available between the Layer list and the header(?) control

### V26. Toggle layer visibility all on / all off (Type: Functionality)

Testers wanted to be able to turn the visibility on and off of all layers in the legend with a single toggle button.

**Comment by AleksueiR** [comment]
![a04 - layers tools row and basemap switcher v0 1](https://cloud.githubusercontent.com/assets/2285779/20928722/2234daae-bb95-11e6-865a-4bc4ae8d11f9.png)

**Comment by alyec** [comment]
Since `Import` and `Basemap` are both specific to the Layers mode of the panel why not move both buttons into the tools row?

**Comment by AleksueiR** [comment]
All functions in the tools row modify layers somehow; basemap switcher doesn't and is somewhat separate. I think it makes more sense to keep it out of it.
