### ISSUE TITLE
"Plant Hardiness Zones of Canada 2000"Layer takes too long to Load

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1447]
Tested :http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-one.htm

While testing issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1184, we noticed the unreasonable load times for this layer in the Index-one site. Can we improve the response time or inform/warn the user in this case. The layer would not finish loading in most of the cases.

![image](https://cloud.githubusercontent.com/assets/18539315/20725766/ebab3018-b640-11e6-86cb-3529a2017822.png)

**Comment by mweech** [comment]
This layer has by far the most features compared to the other layers we have used for testing (>100k features).  Not only is download of data from the service slow, but also processing to add the data to the datatable.  Need to investigate ways of handling smaller chunks of data at a time.

**Comment by james-rae** [comment]
We now have progress indicator on the grid while it loads, and the ability to abort a slow process.
