### ISSUE TITLE
Get Link and Back to Cart feature not working in the French site

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1448]
Tested :http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour

**Get Link** feature (from the side menu as well as the top header) is not working as expected in the French side
-Set the visibility of some layers to hidden
-Get Link through short/long link or the top header does not retain the visibility status of the hidden layers in the new URL

**Back to Cart**

Selecting Back to Cart feature in the French site reloads the English site. Please investigate

**Comment by AleksueiR** [comment]
Is this still an issue? It's almost a year old.

**Comment by james-rae** [comment]
WOMM
