### ISSUE TITLE
Data table duplicated OBJECTID column for user added CSV layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1449]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
Test data: rc_cdr.csv

Screenshot below:
![image](https://cloud.githubusercontent.com/assets/18723160/20729111/b2d1468e-b64e-11e6-9cd6-bf1cabfc62da.png)

**Comment by ChrisLatRNCan** [comment]
May have found th problem while working on #1273 . There's a double call on file load (geojson in #1273 case)

**Comment by ChrisLatRNCan** [comment]
One of the OBJECTID is autogenerate by the geoapi and the other one is coming from the file. 
I'll probably do a bit like we do for geojson id:
1- rename OBJECTID to OBJECTIDcsv
2- autogenerate a new OBJECTID

**Comment by ChrisLatRNCan** [comment]
Modifications are done here: [assignIds](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/layer.js#L718)
Cause CSV is converted to geojson object

**Comment by IsabellaPan** [comment]
Jan 11 2017
Verified with build http://fgpv.cloudapp.net/demo/v1.5.0-9/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
