### ISSUE TITLE
Please update basemap selector title/description in the French site

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1452]
Tested v1.4.0-7

Related to #1151 

Please update basemap selector description and title in the French site. It is in English in the current build.

![image](https://cloud.githubusercontent.com/assets/18539315/20766119/20a362b4-b703-11e6-9f90-ba868f862f59.png)

**Comment by mweech** [comment]
obsolete.  fixed in newest build.
