### ISSUE TITLE
User added Scale Dependency layer - All zoom levels were out of scale after zooming from Detail panel

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1454]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-8/prod/samples/index-fgp-en.html?keys=JOSM,Airports,NPRI_CO,Railways,mb_colour
User added scale dependency layer:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This issue happened with Mercator basemaps only.
-  Add scale dependency layer by selecting zoom level 1 to zoom level 4
-  Click any map point for the added layer to display Point Info panel
-  Click Zoom To Feature button highlighted in below screenshot
![image](https://cloud.githubusercontent.com/assets/18723160/20769597/afed2e02-b710-11e6-959d-df5381106085.png)
-  Click Legend to open up layers - all zoom levels are out of scale, see below
![image](https://cloud.githubusercontent.com/assets/18723160/20769858/a1ee650e-b711-11e6-95dd-18b5bee0a01a.png)

**Comment by james-rae** [comment]
Zoom is going in too far; its so close that all layers are out of scale.

Notice that using the Zoom button in the grid selects a more appropriate zoom level.  First thing to check is difference between code being run in Grid Zoom and Feature Detail Pane zoom.

**Comment by IsabellaPan** [comment]
However, IE11 has an opposite behaviour - no matter how far user zooming in or zooming out, all zoom levels displayed as visible with eye icons, even there isn't any point shown on the map. 
![image](https://cloud.githubusercontent.com/assets/18723160/20800157/88632376-b7b2-11e6-9036-319d1107706f.png)

Does anyone suggest to raise a separate issue for IE11?

**Comment by jolevesq** [comment]
Should the zoom in function goes to the maximum zoom available for a layer if a scale dependency is detected?

**Comment by IsabellaPan** [comment]
Feb 8 2017
Verified with build v1.5.0-rc3.
