### ISSUE TITLE
Layer reorder doesn't work on Android devices

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1457]
Cannot reorder in Chrome and Opera for Android (the list always scrolls and the item is never picked up).

See #1343 issue and #1410 PR for details.

**Comment by alyec** [comment]
Notes from pod discussion:
- drag reordering may be annoying on mobile in general
- may want to introduce a reorder mode:
  - arrows on each layer to move one up or one down
  - fan out the layers and put targets in between layers to allow for a click on layer then pick a target flow

**Comment by milesap** [comment]
On hold for UX review - Android does not ship with Chrome, need to discuss what browsers to support on Android.

**Comment by AleksueiR** [comment]
### What we have:
- Mouse/Finger-only reorder with Dragula is used for reordering on desktop and mobile
- Keyboard-only reordering implementation using Dragula

Dragula reordering doesn't work properly on Chrome for Android, and is generally slow on mobile devices (very computationally intensive, it's assumed).


### What is suggested:

- Keep the mouse-only Dragula reorder on desktops (need to explicitly block it on mobile devices)
- Replace the keyboard-only reorder with keyboard-friendly reorder that would work smoothly on mobile


### How to do it:
A keyboard-friendly reorder mode will be explicitly triggered by clicking on the "Reorder" button in the layers "Tools" row. When the reorder mode is activated, each top-level legend entry displays "Up/Down" reorder buttons instead of the regular "Visibility" and "Settings" buttons. See mockup below for more implementation details:

![a04 - layers tools row and new re -order v0 1](https://cloud.githubusercontent.com/assets/2285779/21143450/cd0a4c50-c114-11e6-88cb-925eb190cb31.png)


### Downside:
This new reorder mode will be available to the mouse users as well: they might be confused why there are two ways of reordering layers and some might mistakenly use the keyboard-friendly reorder instead of mouse-only reorder (which is more time consuming and awkward).

### Comments:
Please, type your comments in the text box below and press the green button :)

**Comment by ChrisLatRNCan** [comment]
Could we have something with less arrows ?

Make a legend entry active with finger then move it with buttons
Here's an example form Inkscape (desktop only)
![image](https://cloud.githubusercontent.com/assets/16193004/21144412/81abd798-c118-11e6-8689-e5babe802f45.png)

**Comment by alyec** [comment]
I like the select, then move option.  As long as the focus moves around cleanly for keyboard users (I'm guessing jump to the arrow bar on layer select and jump back to the top of the list when tabbing past the last arrow).

**Comment by AleksueiR** [comment]
Sounds interesting. Might be harder to implement though (focus management and all).

**Comment by ChrisLatRNCan** [comment]
In Inkscape you change focus with tab to move from layers zone to button zone. In the layers zone you change selection with keyboard arrows.

**Comment by jolevesq** [comment]
To follow Christian idea, when you select the layer to move, it can be the only one to have arrows . It will look like your mockup but with arrows only on he selected element

**Comment by ChrisLatRNCan** [comment]
@jolevesq not sure about it. It means you finger has to move with the selection if you want to move more then one position.

**Comment by milesap** [comment]
I suggest we don't support reordering on mobile devices. It doesn't seem like a feature that is awfully useful for the amount of work needed to make work.

**Comment by AleksueiR** [comment]
Selecting the layer to move redefines what the click on the layer does and the user needs to be instructed about the difference which leads to more possibilities of confusion.

**Comment by ChrisLatRNCan** [comment]
If we don't implement that feature on mobile devices, user will have to rely on setting opacity (eg feature of one layer hiding another one on a different layer).

**Comment by mweech** [comment]
Introduce a reorder button as suggested.  Once selected, there are "grab" buttons on layers.  Once a layer is grabbed, arrows are provided to move it up and down. 

This will require keyboard users to grab a layer, then tab to the controls to move the layer up/down.  Not ideal, but considering the cases this is the best outcome.  Priority of user experience IMO should be in this order:
- Mouse
- Mobile (will become much more prevelant and very common usage for the public, not to mention gaining in usage within departments)
- Keyboard

**Comment by AleksueiR** [comment]
Adding an explicit "grab" button adds another step in reordering layers for touch and keyboard users:
- click "reorder" button to toggle the mode on
- click "grab" on a layer
- click "up arrow"
- click "grab" to release the layer
- click "grab" on another layer
- click "down arrow"
- click "reorder" to toggle the mode off 

When displaying all the arrows upfront:
- click "reorder" button to toggle the mode on
- click "up arrow" on one layer
- click "down arrow" on another layer
- click "reorder" to toggle the mode off 

Yes, this will display lots of arrows, but they are not visible all the time, only when reordering. I think this is a fair trade-off for not implementing additional logic for grabbing layers and having to explain users how this works. And, as I said 
> Selecting the layer to move redefines what the click on the layer does and the user needs to be instructed about the difference which leads to more possibilities of confusion.

**Comment by ChrisLatRNCan** [comment]
We need a VRRS Voice Recognition Reordering System :grin:

**Comment by dan-bowerman** [comment]
I am torn on @milesap and @mweech's suggestions: Forget it, or make it a priority because it will become a bigger deal later on. I used to support the idea of not bothering with it.

In the UI meeting we had recently, we talked about how primarily, our main users at present are FGP (an internal Catalogue), ECCC (an even more internal Catalogue), and Open Maps (wide open to the world). We also talked about external facing (custom) apps for the future (e.g. Oil Sands) -- ideally in those cases, layer ordering is defined in the configuration and users won't want/need to reorder anything. From an internal use perspective, I'm not very concerned about internal mobile users. They barely exist, and I see little direction in the GoC to expand this in the future. 

But I think of Open Maps, which is probably our highest visibility externally (RAMP1 is working well there currently), and assuming RAMP2 will move there eventually, I do see the need for external mobile users to reorder layers.. at least not now, then in the future. I think this is a matter of "we could do this now, or we could do this never". That all said, I think I like Aleksuei's 2nd idea best... subtle arrows to allow anyone, regardless of platform to move things up and down. Fairly intuitive to use, and accessible as heck... the "A" in "RAMP". Just my 5 cents.

**Comment by AleksueiR** [comment]
Okay, here's another mad idea:
we keep the dragula drag-n-drop on mobile (it does work, but we had troubles making it work and allowing the users to scroll the layer list), but only allow reordering layers by their drag handles (this should allow for the layer list to be scrollable. The drag handles are shown only in the reorder mode.

![a04 - layers tools row and new re -order v0 2](https://cloud.githubusercontent.com/assets/2285779/21391872/72e4d388-c75b-11e6-9ea5-41d289e5d29e.png)

This should be even less work as other suggestions as we get to keep our current keyboard-only implementation.

**Comment by AleksueiR** [comment]
Updated mockups to reflect the current implementation:
![a04 - layers tools row and new re -order v0 3](https://cloud.githubusercontent.com/assets/2285779/21457182/2a979ce0-c8fb-11e6-81c6-4c2117f0d14e.png)

**Comment by bkutty** [comment]
Accepted as tested on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,ZoomScale
