### ISSUE TITLE
Map point Details Info remained for any user added layers after switching projection

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1459]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-8/prod/samples/index-fgp-en.html?keys=JOSM,Airports,NPRI_CO,Railways,mb_colour
User added layer: ne_10m_ports.zip or any others, incl. scale dependency layers.

-  Click on map point for a user added layer to open up Point Info panel
-  Click Legend to open all available layers
-  Switch projection, all user added layers will be removed, see below
![image](https://cloud.githubusercontent.com/assets/18723160/20801331/7ec0487c-b7b6-11e6-978f-c1e50a14e70d.png)
However, map point Details Info icon still remained, clicking on the icon will open the Details panel for user added layer's map point.
![image](https://cloud.githubusercontent.com/assets/18723160/20801483/1cb1a3fa-b7b7-11e6-9227-5868ac289df0.png)

**Comment by mweech** [comment]
this will be related to the refactoring of state storage and bookmarking.  won't fix with view to this being handled there.

**Comment by mweech** [comment]
on map reload feature details now closes by default.
