### ISSUE TITLE
Unable to view "Short Link" feature in Firefox and Chrome

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1460]
Tested build : http://fgpv.cloudapp.net/demo/v1.4.0-8/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

For some reason, "Short Link" option on "Get Link" cannot be seen in Chrome or Firefox. Seems to be visible in IE. Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/20803524/833efe3c-b7bd-11e6-913e-b71f09ec81b9.png)

**Comment by ChrisLatRNCan** [comment]
How come it appears in prod but not in dev. It<s the same for the following versions.
http://fgpv.cloudapp.net/demo/v1.4.0-8/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

**Comment by AleksueiR** [comment]
The short link is generated using Google url shortening service. It only works if a Google API key is included in the config and we strip out the key from the production builds, so no one can mistakenly deploy that build with our key in it. This is not a bug.

See related issue here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1458#issuecomment-264511467

**Comment by ChrisLatRNCan** [comment]
Yeah !!!

**Comment by bkutty** [comment]
Accepted
