### ISSUE TITLE
All feature layers map points went missing after map exported

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1463]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-8/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

See screenshot below, the top three feature layers are enabled but no feature points shown up on the map.
![image](https://cloud.githubusercontent.com/assets/18723160/20836219/5ba83dd4-b86c-11e6-9ff4-cebcabf4f511.png)

**Comment by AleksueiR** [comment]
This happens because I manually set 'viewBox' of the Feature layers SVG container. Firefox was returning `undefined` is the viewbox was not set while Chrome returned `0 0 0 0`.

**Comment by AleksueiR** [comment]
GeoApi fix is in PR fgpv-vpgf/geoApi#174.

**Comment by IsabellaPan** [comment]
Dec 14 verified with build:
http://fgpv.cloudapp.net/demo/v1.5.0-2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
