### ISSUE TITLE
Focus is lost when opening layer dropdown menu

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1469]
It seems that under some circumstances, the focus manager steal the focus from the layer dropdown menu and returns it to the viewer. See here:
![focus_m1](https://cloud.githubusercontent.com/assets/2285779/20897030/5c22db14-baee-11e6-8d0a-7a0e6da343df.gif)

After opening the menu, the focus (after a delay) moves from the first menu element to the "Add layer" button.

Also, you the menu is closed while the first element has focus, the focus manager welcome dialog is displayed:

![focus_m2](https://cloud.githubusercontent.com/assets/2285779/20897046/7397eb40-baee-11e6-8a52-5e1369dffad6.gif)

Both these things are wrong: focus should not move from the menu and the welcome dialog should not be shown to the mouse-only users.

**Comment by bkutty** [comment]
No longer an issue
