### ISSUE TITLE
User added Air Quality layer - All zoom levels were visible no matter how far the map zooming in or out

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1470]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-8/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
User added scale dependency layer:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

As discussed in QA Review meeting for issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1454 today, it is suggested to log a separate issue for Scale Dependency layer in IE11.
- Add scale dependency layer by selecting zoom level 1 to zoom level 4
- No matter how far user zooming in or zooming out, all zoom levels displayed as visible with eye icons (in below screenshot, the scale is 1m/4ft)

![image](https://cloud.githubusercontent.com/assets/18723160/20901990/16466d94-bb03-11e6-8cbf-a762b5acd461.png)

**Comment by ChrisLatRNCan** [comment]
Cannot reproduce using the same links and IE11. Zoom In is limited by the basemap so the level 4 still remains at max zoom in. Also, still works with version 1.5.0-0 [fac7492]:
![eiscale](https://cloud.githubusercontent.com/assets/16193004/21398457/58b320d6-c775-11e6-9a50-35dd1cc3ddab.gif)

**Comment by IsabellaPan** [comment]
Jan 12 2017
This is still an issue, tested with build http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

![image](https://cloud.githubusercontent.com/assets/18723160/21896106/2a0c1e00-d8b3-11e6-9f8e-a4873331870c.png)

**Comment by ChrisLatRNCan** [comment]
It is still working for me with http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley . I'll ask for someone else to test it.

**Comment by alyec** [comment]
I can reproduce this intermittently.  When it occurs I have an error in the console:
`SCRIPT7002: XMLHttpRequest: Network Error 0x2ee2, Could not complete the operation due to error 00002ee2.`  which translates to `12002       ERROR_INTERNET_TIMEOUT`

However, it doesn't look like that from the network tab:
![2017-01-13 10_41_39-fgp viewer - internet explorer](https://cloud.githubusercontent.com/assets/7646414/21935827/f9aa5158-d97c-11e6-89e7-5f8141d6c2ec.png)

**Comment by mweech** [comment]
occurs periodically depending on the user.   cannot reliably reproduce.

**Comment by AleksueiR** [comment]
Haven't seen this recently. @IsabellaPan can you retest please?
