### ISSUE TITLE
Map Navigation Buttons appear off-screen (Android 5.1)

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1472]
![1](https://cloud.githubusercontent.com/assets/10187181/20927330/1c036c64-bb8f-11e6-8b50-4bd020c58a68.png)

**Comment by alyec** [comment]
Testing on Chrome

![2016-12-06 16_07_51-android emulator - galaxy_nexus_api_22_5554](https://cloud.githubusercontent.com/assets/7646414/20944075/1ba339e8-bbd0-11e6-8f3b-aa0831bec192.png)

**Comment by mweech** [comment]
Android 5.1 built in browser is out of scope for support.
