### ISSUE TITLE
Menu Links/Buttons not rendered correctly (Android 5.1)

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1473]
![2](https://cloud.githubusercontent.com/assets/10187181/20927520/0366817c-bb90-11e6-990a-288074cc08ce.png)

**Comment by alyec** [comment]
Chrome version

![2016-12-06 16_08_13-android emulator - galaxy_nexus_api_22_5554](https://cloud.githubusercontent.com/assets/7646414/20944118/3828a36e-bbd0-11e6-8595-e84530bf7f62.png)

**Comment by mweech** [comment]
Android 5.1 built in browser is out of scope for support.
