### ISSUE TITLE
Export dialog controls outside viewport on Mobile

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1474]
![2](https://cloud.githubusercontent.com/assets/10187181/20927780/11c432ea-bb91-11e6-80c5-1b86f05a6ea5.png)

**Comment by AleksueiR** [comment]
What resolution is this?

**Comment by milesap** [comment]
1024x768

**Comment by AleksueiR** [comment]
On the screenshot, the download button takes at least a third of screen width - I don't think this is normal either.

**Comment by alyec** [comment]
This one improves a bit on Chrome but I think it's still valid and the UI needs some tweaking.  I believe my res was `720` x `1280`

![2016-12-06 16_08_59-android emulator - galaxy_nexus_api_22_5554](https://cloud.githubusercontent.com/assets/7646414/20944193/7be7f528-bbd0-11e6-86fc-1d2933df1320.png)

**Comment by AleksueiR** [comment]
Fair enough.

**Comment by alyec** [comment]
Maybe use some icons with hidden labels in mobile mode?  Download and close are both pretty recognizable IMO.

**Comment by bkutty** [comment]
I checked this fix in v1.6.0-1 using Samsung Galaxy 6 & 7 in chrome. In both cases "Close" seems to  cut off in the export header

![image](https://cloud.githubusercontent.com/assets/18539315/23755609/f15bd406-04ae-11e7-939b-925e837575ec.png)

![image](https://cloud.githubusercontent.com/assets/18539315/23755632/072fa488-04af-11e7-87e0-631e0822255c.png)
