### ISSUE TITLE
Datatable controls and right margin rendering incorrectly (Android 5.1)

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1475]
![2](https://cloud.githubusercontent.com/assets/10187181/20928434/d03388a0-bb93-11e6-81e3-cc3e8b1ff1bf.png)

Note: All dialog controls seem to be having this issue

**Comment by alyec** [comment]
Chrome version

![2016-12-06 16_11_20-android emulator - galaxy_nexus_api_22_5554](https://cloud.githubusercontent.com/assets/7646414/20944233/9e4caeb0-bbd0-11e6-9095-6628ca836ebb.png)

**Comment by mweech** [comment]
Android 5.1 built in browser is out of scope for support.
