### ISSUE TITLE
Identify results view renders incorrectly at bottom of page (Android 5.1)

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1476]
![2](https://cloud.githubusercontent.com/assets/10187181/20928597/9f03dfea-bb94-11e6-80ef-60f6dc2f2e10.png)

**Comment by alyec** [comment]
Chrome version

![2016-12-06 16_12_07-android emulator - galaxy_nexus_api_22_5554](https://cloud.githubusercontent.com/assets/7646414/20944252/ae221dac-bbd0-11e6-950b-ead2e88a2964.png)

**Comment by mweech** [comment]
Android 5.1 built in browser is out of scope for support.
