### ISSUE TITLE
"Share" doesn't work in develop and 1.4

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1478]
Share dialog doesn't open.

**Comment by IsabellaPan** [comment]
share  dialog all the way opened for me in all three browsers @AleksueiR 
In which build is it not opened??

**Comment by AleksueiR** [comment]
It is broken in __1.4.0__ release, that's why we needed a quick fix for that. Thanks for checking.

**Comment by bkutty** [comment]
No longer an issue.
