### ISSUE TITLE
Legend no longer loads for barley layer

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1487]
http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/

Identify doesn't seem to work as well.

**Comment by james-rae** [comment]
This [TODO](https://github.com/fgpv-vpgf/geoApi/blob/master/src/symbology.js#L33) might be the cause?  As you can see, the [legend](http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/legend) has a number of blank entries.

If this is the case, we may need to switch to some type of system-generated IDs for legend / renderer identification (would need some thinking)

**Comment by AleksueiR** [comment]
Did it ever work before?

**Comment by AleksueiR** [comment]
Legend for this one also stopped loading: http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_agri_environmental_indicators/MapServer

**Comment by james-rae** [comment]
Can't reproduce issue for [aafc_agri_environmental_indicators](http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_agri_environmental_indicators/MapServer)

**Comment by james-rae** [comment]
[Barley](http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/) is a Dynamic Layer, but the [endpoint](http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/0) is a `Raster Layer`. This means it has no features or a renderer, and the app currently will not generate a full legend.

[Here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.4.0-8/src/app/geo/legend.service.js#L105) you can see where the code realizes there are no features and skips the renderer enhancement & legend generation steps.

[Here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.4.0-8/src/app/geo/legend.service.js#L298) is some code we used earlier on to use the ArcGIS Server legend endpoint as a source for the legend. We may need to resurrect this code to grab legend info upfront for `Raster Layers`

**Comment by james-rae** [comment]
> Identify doesn't seem to work as well.

No features, no identify

**Comment by AleksueiR** [comment]
No legend for aafc_agri_environmental_indicators, just placeholders:
![](https://i.imgur.com/SOAUr42.png)

And no data or identify:
![](https://i.imgur.com/LP4zA7k.png)

Loaded on latest develop.

**Comment by james-rae** [comment]
Extra note: Data Table icon is showing on the `Barley` layer when it has no tabular data

**Comment by bkutty** [comment]
Confirmed Legend Loads for Barley Layer and Image Layer. Tested on build  http://fgpv.cloudapp.net/demo/v1.5.0-13/prod/samples/
