### ISSUE TITLE
Allow Feature Layers to be Imported as Dynamic Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1493]
When a user attempts to add a Map Service Feature Layer via the add layer component, the user cannot select to add it as a layer with Dynamic Map Service, as the viewer forces them to add the layer as a Feature Layer.

- [x] Allow users to Add a Feature Layer as a Map Service
- [x] Update the legend to display the map service as it would a Feature Layer
- [x] Update schema to allow for single layer Dyanmic services

**Comment by mweech** [comment]
Verify if Legend renders the single layer Dynamic as having no parent node for auto-legend.

**Comment by AleksueiR** [comment]
Added singleEntryCollapse option to layer import wizard. It's named "Display as a group", which is a reverse of the config option that collapses the top group.

- the option is automatically set to `true` if more than one layer is selected; to `false`, only one layer is selected.
- the option is locked to user interaction if more than on layer is selected;
- the `Group Name` input field is shown only when the `Display as a group` option is selected;
![](https://i.imgur.com/v0qlg1k.png)
