### ISSUE TITLE
"Get Link" option in the French site generates URL for English site

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1497]
Tested build :http://fgpv.cloudapp.net/demo/v1.4.1-1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley

Steps to Reproduce

-  Load the English URL
-  Navigate to the Left menu and select "French"
- French site should load
- Click on "Get Link" and copy the long/short url
- Paste it a different tab
- English site will load

Please note that this is not an issue when the French Link is used (http://fgpv.cloudapp.net/demo/v1.4.1-1/prod/samples/index-fgp-fr.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley)

![image](https://cloud.githubusercontent.com/assets/18539315/21108163/33259d40-c062-11e6-8aba-7a2f02911182.png)

**Comment by mweech** [comment]
Cannot control state of host page under current technical implementation.
