### ISSUE TITLE
Error message not disappearing when closing import file window

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1505]
1- Get an error message on import file (e.g. bad file): "Can't access file";
2- Close import file window;
3- Reopen import file window and the message is still there
version: 1.5.0-0 [0b897b1]

![importfileerror](https://cloud.githubusercontent.com/assets/16193004/21153067/eb2e0f42-c136-11e6-886e-0e5de7a2bd29.gif)

**Comment by ChrisLatRNCan** [comment]
Notes:
-There's no reference to the ng-model="self.upload.fileSelect" in loader-file.directive.js
-FileReset and FileUrlReset are called twice. The controller doesn't seem to be referenced twice

**Comment by ChrisLatRNCan** [comment]
The ng-if is harmful overhere. I don't fully understand the concept but ng-messages="self.upload.form.fileSelect.$error" is taking care of synchronizing the $setValidity effect with the DOM. So, removing ng-if is the solution here.

````
<div ng-messages="self.upload.form.fileSelect.$error" ng-if="self.upload.form.fileSelect.$invalid">
             <div ng-message="upload-error" translate>import.file.upload.noaccess</div>
</div>

**Comment by bkutty** [comment]
No longer an issue. Accepted per tests on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html
