### ISSUE TITLE
Rename "Shapefile" to "zipped Shapefile" in layer import wizard

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1506]
Importing a shapefile directly (not zipped) will trigger the error "Can't access file"
If it is still a behaviour that we want to keep, we need to specify it in the interface

Upload data
GeoJSON, CSV, or ~~Shapefile~~ zipped Shapefile

![image](https://cloud.githubusercontent.com/assets/16193004/21153791/02832896-c13a-11e6-8048-74a4282a0db6.png)

**Comment by AleksueiR** [comment]
I thought it's a zip, because this format requires several files.

**Comment by ChrisLatRNCan** [comment]
Usually, shapefile could be selected by selecting the *.shp file even though it is part of a set of files (a function will grab the other ones). So, we should just add a way to handle unzip shapefile. Also, it is really handy to be able to select a zip so we need to keep that possibility.

**Comment by AleksueiR** [comment]
Do you still need the other files, apart from *.shp? If so, selecting just one file will not work for us.
In a desktop app, you can load files from the same directory as the only selected (user selects a *.shp; the app loads the rest). Browsers do not have access to the file system and we can't load files this way. To load an unzipped shapefile, the user would need to select all the relevant files in one go. This would add complexity as we would need to handle cases where user doesn't select all the necessary files. Horrible stuff.

**Comment by james-rae** [comment]
Generally yes. The `.shp` usually holds geometries. The `.dbf` holds attributes. Any projection information will be in `.prj`

**Comment by ChrisLatRNCan** [comment]
Humm, I agree with you @AleksueiR, it is horrible 👹 stuff. As a first step we should at least mention on the interface **zipped** file. For the next option it needs 🤔 .

**Comment by AleksueiR** [comment]
Sure, `zipped Shapefile` sounds fine. @ChrisLatRNCan do you want to make a new issue for that? We can keep this one in the backlog in case we want (for lack of other work, I guess) to implemented importing unzipped shapefiles in the future.

**Comment by ChrisLatRNCan** [comment]
Sure, I'll do
