### ISSUE TITLE
Should "Expand/Collapse All" options apply to legend stacks?

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1509]
The "Expand/Collapse" option in the layers "Tools" row expands/collapses layer groups. Does it make sense for it to expand the legend stacks as well? Would it be useful to the user at all?

![image](https://cloud.githubusercontent.com/assets/2285779/21182952/a0ba1896-c1d3-11e6-8c67-35c1c0157ee3.png)

**Comment by james-rae** [comment]
I feel this is a `50/50`.  The data that happens to be in the legend pane affects how useful/awful expanding the legends would be.

A lazy solution: change the label from "Expand All" to something that makes it clear you are only expanding layer groups.

**Comment by AleksueiR** [comment]
"Expand/Collapse Groups" :+1: to lazy solution.

**Comment by mweech** [comment]
Agree with this for now.  We will probably get feedbacks on the specifics of this with more usage.  No reason to do more than change the label at this point in time.
