### ISSUE TITLE
Missing checkmarks for Full Screen & Show Layers on Left Sided Menu

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1512]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

This happened with Firefox browser only, for both English and French Visualiser.
![image](https://cloud.githubusercontent.com/assets/18723160/21187621/a097b2de-c1e6-11e6-8692-7f3896524fc4.png)

**Comment by mweech** [comment]
Related to #1548

**Comment by AleksueiR** [comment]
Fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1553 PR.
