### ISSUE TITLE
FGP Visualiser incl. basemap still in English after toggling to French

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1513]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Though the Left Sided Menu and Legend changed to French. (but English toggle button still in English?)
![image](https://cloud.githubusercontent.com/assets/18723160/21188464/83d29efe-c1e9-11e6-8b79-a369bad42a3d.png)

**Comment by ChrisLatRNCan** [comment]
For this issue I'll target the basemap behaviour not the page that host the viewer.

**Comment by mweech** [comment]
Language is spelled in native language to assist the users.

**Comment by IsabellaPan** [comment]
Feb 23 2017
The basemap is now displayed in French, as verified in build http://fgpv.cloudapp.net/demo/v1.5.1-1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
