### ISSUE TITLE
ReferenceError: 'Symbol' is undefined in IE11

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1516]
It errors on the line 135388 of the compiled `core.js` which looks like this:
```js

for (var _iterator = Object.entries(service.mapObject.attribution.itemNodes)[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var _step$value = _slicedToArray(_step.value, 1);

    var key = _step$value[0];

    service.mapObject.attribution.itemNodes[key].innerText = cfgAtt.text.value;
}
```

I guess Babel converts [this line here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/map.service.js#L369) into the above and IE [doesn't support](https://camo.githubusercontent.com/9a8ea930b1d871cc949a92a098d0b95e7e1ee958/68747470733a2f2f692e696d6775722e636f6d2f4c704c79556e532e706e67) Symbols.

**Comment by mweech** [comment]
can this be polyfilled?

**Comment by AleksueiR** [comment]
Theoretically: https://github.com/medikoo/es6-symbol

**Comment by AleksueiR** [comment]
This doesn't seem to be happening anymore. Should we close?

**Comment by james-rae** [comment]
Sounds good, though you will be depriving students of essential IE11 debugging skills 👯 💨

**Comment by JahidAhmed** [comment]
![](https://files.gitter.im/fgpv-vpgf/2Cq8/Capture.JPG)
