### ISSUE TITLE
Menu items in IE not rendering correctly

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1519]
![sidemenu](https://cloud.githubusercontent.com/assets/10187181/21196690/98b335f0-c206-11e6-8a52-08d2f536c60f.png)

**Comment by AleksueiR** [comment]
Yes, also noticed that just now. Do you know when it broke?

**Comment by milesap** [comment]
Breaks on daily `v1.5.0-2`

**Comment by AleksueiR** [comment]
Duplicate: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1510

**Comment by milesap** [comment]
too slow :disappointed:

**Comment by IsabellaPan** [comment]
This is already logged previously as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1510
