### ISSUE TITLE
IE draws their own clear buttons for input fields

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1520]
Noticed by @milesap in https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1514#- PR.

![](https://camo.githubusercontent.com/952295eb4f3c73b3aa7015ec19ce4dc4956d0c15/68747470733a2f2f66696c65732e72657669657761626c6575736572636f6e74656e742e696f2f696d616765732f72657669657761626c652f31303138373138312f39457a327a6246647458424d647854736f4b6f4931474c722f636c6f7365253230627574746f6e2e706e67)

Suggestion: do not draw our own clear buttons if the user agent is IE.

**Comment by IsabellaPan** [comment]
Feb 8 2017
Verified the fixes with build v1.5.0-rc3.
