### ISSUE TITLE
Allow toggling of WMS Layer Visibility

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1526]
WMS layers like the Railways layer may use a single metadata file to display multiple WMS layers (http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html?keys=Railways). 

Allow for each individual WMS layer to have their visibility toggled similar to how Group Layers are handled.

**Comment by alyec** [comment]
We could treat the WMS as a flat list in group layer format.  We can set visibility and identify on each of the children.

**Comment by AleksueiR** [comment]
Just a note: If we treat them as group layers, users won't be able to view all the wms legend graphics at once in one click. They would need to expand each graphic separately.

**Comment by james-rae** [comment]
Did brief R&D to prove we can manipulate the visibility of sublayers in the WMS.

By using [setVisibleLayers](https://developers.arcgis.com/javascript/3/jsapi/wmslayer-amd.html#setvisiblelayers) function we can adjust the them.  Would need to always bundle the visible ids into an array (many ways to manage that)

**Comment by AleksueiR** [comment]
Treating the symbology stack as the visibility filter for WMS sublayers posses a smallish problem - if a custom symbology stack is specified in the config, it might have more or fewer items that the actual layer. In this case, visibility toggles won't line up to the actual sublayers.

We can make it a requirement to supply the same number of symbols as the number of WMS sublayers, but this is overly restrictive. Or we can add an extra parameter to bind certain symbols to certain sublayers which lets you specify as many or as few as you want. Both options are cumbersome and require prior knowledge of the WMS layer you are adding (either the number of sublayers it has or sublayer ids).

If we go back to the suggestion about displaying WMS as groups (similar to Dynamic layers), there is a problem with WMS container nodes possibly containing data. As a work-around, we can still represent WMS as nested groups with a single, non-disabable by user element representing any data contained in the container node itself. It will display a legend graphic of the group itself and will be turned off when the group is turned off.

**Comment by AleksueiR** [comment]
Say you have a WMS layer with the following structure:
```
Groundwater
    Canadian water wells
        SaskWaterWell
        YukonWaterWell
        OntarioWaterWells
```

`Canadian water wells` is a "container" node which can also display data, and it's not possible to turn it off without turning all its children off. This data displayed by the container node will be represented by a dummy legend block (third from the top in the picture below with its visibility toggle disabled to the user). It will be toggled on/off only when the group (`Canadian water wells`) is turned off. 

![](https://i.imgur.com/kfZnb96.png)

Even if all the children of `Canadian water wells` are turned off, the data displayed by the "container" node should still be visible. This will be indicated by that dummy legend block. If we don't show something like that, it will be quite odd and inconsistent with how Dynamic groups are displayed.

![](https://i.imgur.com/YXjWbi2.png)

P.S.: please, correct me here if I'm not making any sense.

**Comment by mweech** [comment]
Here are some general comments... using this simple WMS as an example: http://proxyinternet.nrcan.gc.ca/arcgis/services/CLSS-SATC/CLSS_Administrative_Boundaries/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0


RE: auto-legend:
- GetMap and GetLegendGraphic is only usable when a "Layers" parameter is specified. This is why from an RCS perspective we force them to specify a Layers=<layername> parameter even though it is not a valid argument to a GetCapabilities call
- Since we know a WMS will be added to viewer with a specific layer or set of layers specified, we should format WMS in the legend such that each individual layer, by layer name has a toggle able entry. (National_Parks_and_National_Park_Reserves_of_Canada_Legislative_Boundaries & National_Parks_and_National_Park_Reserves_of_Canada_Legislative_Boundaries above) 
- If a layer has a unique Layer name, than it will also have a layer title. the toggle for visibility should be provided beside this. (2 in the example above)
-  each layer will typically have a default legend available as well under a particular style.  we will just be using the "Default" legend rather than providing the option to choose a legend from a different style (for now).
- if i read the viewer schema right, it appears that we treat a WMS as a URL to a service link similar to Esri, but i believe this is a mistake.  Esri uses a structured/REST like URL, however WMS is parameter based.  we need to manage the "layers" argument to WMS a bit more directly to enable this

for structured legend:
- if i read the schema right, we need to add a "layers" value to our WMS config schema
- a user should be able to structure the legend such that they can populate custom symbology per WMS entry... which means they may have to make 2 separate entries for each sublayer of a particular WMS. i.e. one for National_Parks_and_National_Park_Reserves_of_Canada_Legislative_Boundaries & another for National_Parks_and_National_Park_Reserves_of_Canada_Legislative_Boundaries
- if they choose to make 1 custom symbology group to cover a single WMS service entry with both layers (as in the example above).. well that's their decision.
