### ISSUE TITLE
Add unzipped Shapefile reading feature to import file facilities

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1533]
Shapefile is a set of files, all with the same name but with different extensions. 
Actually the import file service can deal only with zipped Shapefile. 
It would be nice to be able to let the user select the *.shp file only while all the other related ones are automatically selected. 

**Mandatory files** 
**.shp** — shape format; the feature geometry itself
**.shx**  — shape index format; a positional index of the feature geometry to allow seeking forwards and backwards quickly
**.dbf** — attribute format; columnar attributes for each shape, in dBase IV format
**Other files** 
**.prj** — projection format; the coordinate system and projection information, a plain text file describing the projection using well-known text format
**.sbn** and **.sbx** — a spatial index of the features
**.fbn** and **.fbx** — a spatial index of the features that are read-only
**.ain** and **.aih** — an attribute index of the active fields in a table
**.ixs** — a geocoding index for read-write datasets
**.mxs** — a geocoding index for read-write datasets (ODB format)
**.atx** — an attribute index for the .dbf file in the form of shapefile.columnname.atx (ArcGIS 8 and later)
**.shp.xml** — geospatial metadata in XML format, such as ISO 19115 or other XML schema
**.cpg** — used to specify the code page (only for .dbf) for identifying the character encoding to be used
**.qix** — an alternative quadtree spatial index used by MapServer and GDAL/OGR software

Source: [Shapefile](https://en.wikipedia.org/wiki/Shapefile)

**Comment by ChrisLatRNCan** [comment]
fgpv-vpgf/fgpv-vpgf#1506

**Comment by mweech** [comment]
is this possible from a browser security perspective? (i.e. can you get access to files you did not explicitly select?)

**Comment by ChrisLatRNCan** [comment]
I don't know. But we have to explore if it's possible. A lot gis users are used to select just the shapefile on desktop gis (arcmap, qgis) or ETL (fme). But, if it's not possible, we'll  just close the door to this option.
