### ISSUE TITLE
Left Sided Menu defaulted to English when loaded FGP Visualiser from index-fgp-fr.html

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1539]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.5.0-5/prod/samples/index-fgp-fr.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

When loading Visualiser from French URL, the left sided menu should default to French.

![image](https://cloud.githubusercontent.com/assets/18723160/21396926/dc14f3e2-c76f-11e6-8f97-f00de813179a.png)

**Comment by ChrisLatRNCan** [comment]
It's a known issue coming after fgpv-vpgf/fgpv-vpgf#1468 fix.

**Comment by ChrisLatRNCan** [comment]
**index-fgp-en.html** has no **rv-langs** parameter so it will get the default value **["en-CA","fr-CA"]** and get both languages in the menu with English has primary language
**index-fgp-fr.html** has no **rv-langs** parameter and previously had just fr-CA ( see #1468 with missing English option) so now it gets default value ["en-CA","fr-CA"] and still have English as primary language.
So the solution is to put explicitely **rv-langs** with French as primary language **["fr-CA","en-CA"]** for  **index-fgp-fr.html**

**Comment by IsabellaPan** [comment]
Feb 8 2017
No longer an issue, verified with build v1.5.0-rc3
