### ISSUE TITLE
feat(core): add geolocation guts

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#154]
- [x] Use [geolocator](https://github.com/onury/geolocator) to get the location.

**Comment by james-rae** [comment]
Optional alternative: use our [ramp geolocator code ](https://github.com/RAMP-PCAR/RAMP-PCAR/blob/develop/src/js/RAMP/Modules/navigation.js).  Less forking and stripping out.

**Comment by AleksueiR** [comment]
RAMP gelocation code works only if the user allows it; aforementioned geolocator falls back on determening your location from the IP address. I think it's a cool feature worthy of being included.

**Comment by james-rae** [comment]
Neat-o.  Proceed!  :dancers: :dash:
