### ISSUE TITLE
Error message persists on the "Import File" panel after attempting to upload individual shapefiles

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1540]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-6/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Relates to #1506 

Steps to reproduce

- Navigate to "Add Layer"
- Select " Import File"
- Upload individual shapefiles. Error message "Can't Access file"
- Upload another zipped shapefile and continue with all the subsequent steps to add the layer
- Access Import File Panel again
- Previous error message still remains on the panel

![image](https://cloud.githubusercontent.com/assets/18539315/21430333/c8f0d4d6-c830-11e6-9f10-b54287f4cc52.png)

**Comment by ChrisLatRNCan** [comment]
Already an issue for that here #1505

**Comment by bkutty** [comment]
Accepted as tested on http://fgpv.cloudapp.net/demo/v1.5.0-rc3/prod/samples/index-fgp-fr.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley
