### ISSUE TITLE
Styles on the side menu are broken again

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1548]
Language icon should be on the right, not left. Also need to add `rv-button-square` class to the buttons.
![](https://i.imgur.com/DcfUbSw.png)

**Comment by AleksueiR** [comment]
Related #1510 ?

**Comment by AleksueiR** [comment]
wip branch: https://github.com/AleksueiR/fgpv-vpgf/tree/1549-broken-styles-fixe

| old looks  | new looks  |
|---|---|
| ![](https://i.imgur.com/xTP70Zo.png)  | ![](https://i.imgur.com/JtRe9MX.png)  |

**Comment by AleksueiR** [comment]
The side menu will remain open as the Full screen mode is toggled. I removed the closing call since the user might want to click on something else in the menu after changing the mode.

**Comment by bkutty** [comment]
Accepted as per tests on build v1.5.0-10. Please note that issue#1510 still persists which related to left side menu alignment in IE
