### ISSUE TITLE
feat(ui): add datatable to the data panel with the following enhancements

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#155]
Features we might want to add to the datatable:
- [ ] index column
- [ ] show/hide columns
- [ ] individual row searching (text/select) X
- [ ] global table search (with regex) X
- [ ] info button in the table (generated content?)
- [ ] state saving
- [x] horizontal scroll for wide tables
- [ ] toggle to show items not in the current extent (with highlighting of row corresponding to visible elements) X
- [ ] column reordering
- [ ] Responsive extension to hide extra columns on mobile devices
- [ ] KeyTable extension (if it helps with accessibility)
- [ ] Buttons extension
- [x] Scroller extension - virtual renderer/repeater instead of pagination

**Comment by AleksueiR** [comment]
Should this also be an Epic?

**Comment by mweech** [comment]
duplicates the epic.  will be left open for additional information until epic is scheduled for development.

**Comment by AleksueiR** [comment]
Everything from here seems to be implemented. Closing.
