### ISSUE TITLE
Importing WMS through wizard fails if url parameters are present

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1550]
When importing a WMS layer with the following url
> http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer

the actual request sent is 
> http://cp.zz9.ca/index?http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer?service=WMS&version=1.3&request=GetCapabilities

but when using a url with parameters
> http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer?request=GetCapabilities&service=WMS

the actual request sent is 
> http://cp.zz9.ca/index?http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer?request=GetCapabilities&service=WMS?service=WMS&version=1.3&request=GetCapabilities

Notice `request=GetCapabilities&service=WMS` is doubled.
This request fails and another is sent:
> http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer?request=GetCapabilities&service=WMS&f=json&callback=dojo.io.script.jsonp_dojoIoScript5._jsonpCallback

which succeeds but the wizards still gets an error from the geoapi.

Relates:
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1543#issuecomment-269641358

**Comment by james-rae** [comment]
Eyeballing it, appears that `?service=WMS&version=1.3&request=GetCapabilities` is being appended to the url. 

Need to consider how this would affect WMS urls that have a `?` in their root path (if that is possible at all???).  E.g. `http://lurk.com/findWms?target=pigPens`

If that is not a concern, a lazy™ solution could be to drop the parameter string from a WMS (though the trick is knowing its a WMS prior to dropping it)

**Comment by mweech** [comment]
Parameter strings for WMS layers are very specific and dropping any part of the parameter could result in the WMS producing a very different response.  I don't think we should be appending "?service=WMS&version=1.3&request=GetCapabilities" if we can detect an exist URL parameter exists (i.e. ?). 

IMO: 
- if "?" exists on URL, do not append (may fail if not a well defined URL, but can't fix PEBKAC)
- if "?" does not exist attempt to append (may still fail if not a 1.3 wms)

-

**Comment by milesap** [comment]
This sounds like the `getCapabilities` method of  `geoApi.js` to me

**Comment by bkutty** [comment]
This issue seems to be fixed now. Accepted as tested on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley
