### ISSUE TITLE
Allow for inclusion of images in Help section

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1555]
At the moment, in-app help can only contain text. Need a way to include images with the text and to allow for more formatting options (headings, bold, lists, etc.).

Any ideas on how to do that?

Use markdown in translation file and run markdown processor during the build step, so we don't have to store any html in the translations?

**Comment by AleksueiR** [comment]
Help can be initially written in markdown with images and formatting, and stored in `src\locales\help\{{language-country}}.md` files (one file per language).

At the build step, each markdown file is compiled into html (https://github.com/chjj/marked), broken down by the top level headings and added to the translation file (either csv or directly to their json counterparts).

We cannot include all the help images with the `core.js` as it will get quite big, so we need to host them somewhere

This initial markdown file can looks something like this:

```md
 # Navigation Controls

 Navigation controls are used for changing the viewing extent of the map.
 ![](https://i.imgur.com/6BV3gGu.png)

 ### Usage:
 Click and drag to move the map in a particular direction.

 - Zoom In/Out: Click 'Zoom In/Out' to change the map extent
 - Canada: Click 'Canada' to view map at its full extent


 # Basemaps

 The Basemap selector is used to modify the underlying basemap to provide a variety of geographical contexts.
 ![](https://i.imgur.com/svwEjRH.png)

 ### Usage: 
 - Basemap: Click 'Basemap'. From the slideout menu, select the basemap of your choice and the map display will update. Click 'Basemap' again to close the slideout menu.
```

which renders as

># Navigation Controls
>
> Navigation controls are used for changing the viewing extent of the map.
> ![](https://i.imgur.com/6BV3gGu.png)
>
> ### Usage:
> Click and drag to move the map in a particular direction.
>
> - Zoom In/Out: Click 'Zoom In/Out' to change the map extent
> - Canada: Click 'Canada' to view map at its full extent
>
>
> # Basemaps
>
> The Basemap selector is used to modify the underlying basemap to provide a variety of geographical contexts.
> ![](https://i.imgur.com/svwEjRH.png)
>
> ### Usage: 
> - Basemap: Click 'Basemap'. From the slideout menu, select the basemap of your choice and the map display will update. Click 'Basemap' again to close the slideout menu.

**Comment by alyec** [comment]
If markdown parsing is performant do we want to do it at runtime instead?  This would allow some flexibility in configuration where we might have a key like `ui.help.contentRoot` (and under there we could have one directory per locale containing markdown text and various images).

**Comment by milesap** [comment]
Seems like runtime markdown is also good for allowing plugins to add their own help section documentation.
