### ISSUE TITLE
Focus manager resets lost focus at inopportune moments

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1557]
The following comments are from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1546 PR.

Our current implementation of the focus manager tries to keep the focus on the element, preventing the table from scrolling (in the gif I'm trying to scroll down, but it keeps resetting as soon as the focused row scrolls away):
![stubborn-table.gif](https://files.reviewableusercontent.io/images/reviewable/2285779/uXLNoQ_1KBsV-LA99Yx2qDsO/stubborn-table.gif)
We probably need to tweak the focus manager to avoid this behaviour, but until then, we need another solution for this jumping focus.

If you scroll a little bit faster, the focus is removed, and since the cell which had focus is already removed from the dom, the focus manager __will__ put the focus somewhere else (previously focused item, as far as I understand).
Here's what was happening for me - after scrolling faster, the focus was set to the header cell, but since that header cell was outside of the view, it was scrolled into the view, which messed up column alignment (scrolling some more fixed it though).
![focus\_table.gif](https://files.reviewableusercontent.io/images/reviewable/2285779/8VP0M7FLii3Pqhf7nj4axr5s/focus_table.gif)

**Comment by milesap** [comment]
The likely cause is the dataTable scroll extension deleting the row Element with focus when it scrolls out of view. Normally focus would go to the body element, it in this case the focus manager correctly catches this and puts focus on the last known focusable element (the headers in this case). 

An easy fix would be to implement an element attribute `rv-focusout-ignore` where all child focusout events are ignored by the focus manager.

**Comment by AleksueiR** [comment]
That would move focus outside the viewer, creating another bug :(

**Comment by milesap** [comment]
That's true, perhaps an `rv-focusout-to=someElement` attribute could work where focus moves to the specified element when any child element looses focus. In this case focus could be placed on something outside the dataTable so it doesn't autoscroll.

**Comment by AleksueiR** [comment]
What do you think about storing the element that had focus when the focus is lost, but not forcing it back onto the page right away. When the users presses `Tab` , set the focus to the cached element, or, if it's missing, to the previous one from the focus history (this of course should happen only inside the viewer).

**Comment by bkutty** [comment]
Accepted as tested on v1.5.0-rc3
