### ISSUE TITLE
Map Export download feature not working as expected in mobile emulator

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1559]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-8/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Selecting "download" option on a Map export gives the following message when tested in a Mobile emulator. I used the mobile browser emulator available as an Add on in  Chrome.

When "save image" option is selected, map image is saved with no title, legend, foot note, scale, north arrow or time stamp. Please investigate 

![image](https://cloud.githubusercontent.com/assets/18539315/21724461/7469343e-d402-11e6-9013-01ad85f8edbf.png)

![image](https://cloud.githubusercontent.com/assets/18539315/21724522/b20ef882-d402-11e6-9d56-598e2095ee7c.png)

**Comment by AleksueiR** [comment]
The error messages says "cannot save in __Safari__" when we know it's Chrome. Maybe the extension used to resize the browser pretends to be Safari for some reason. If so, Safari is unable to save the exported image directive (see this bug https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1368) and there is a fix around that. Looks like this fix is being mistakenly applied here.

**Comment by bkutty** [comment]
This is not an issue when the browser is resized to a smaller layout. Wrong results probably due to emulator. Closing this issue
