### ISSUE TITLE
Map Export for user added service layer - Map points not shown up on exported map when Export Image Size not big enough

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1560]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-8/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

- Add above test data service layer
- Select Nature, Water, and Air Emissions sub-layers as below screeenshot
![image](https://cloud.githubusercontent.com/assets/18723160/21728603/1628f2ca-d415-11e6-90b2-85f9d9324ccb.png)

After exported map, the added CESI three sub-layers points not shown up at default image size. Even increasing size to 2500 (width) X 1538 (height), map points still not displaying, see below screenshot. 
But when the image size reached to 3000 X 1845, the points could be displayed.

![image](https://cloud.githubusercontent.com/assets/18723160/21728844/48c97b40-d416-11e6-8561-4a3b9e23a755.png)

**Comment by AleksueiR** [comment]
@IsabellaPan Can you please look at this bug: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1461? Is this somehow related?

**Comment by IsabellaPan** [comment]
@AleksueiR Not quite sure if it is opposite? in my case, when the selected export image size big enough, like 3000 X 1845, then all map points will display correctly.

**Comment by AleksueiR** [comment]
If it's the opposite, it might be related as well. Thanks for checking.

**Comment by IsabellaPan** [comment]
Feb 13 2017
It seems still an issue, tested with build http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

**Comment by AleksueiR** [comment]
@IsabellaPan I'm not sure why Mike moved it to **Fixed** as no work was done to address this.

**Comment by JahidAhmed** [comment]
This does not seem to be an issue anymore. Can someone else test and confirm this

**Comment by dane-thomas** [comment]
Working for me as well.

**Comment by ShrutiVellanki** [comment]
yep works for me even at the smallest export size 
![capture](https://user-images.githubusercontent.com/25359812/43961752-d4d24900-9c83-11e8-9162-1d164d5cd7db.PNG)

**Comment by barryytm** [comment]
It does not seem to be an issue on my machine. However when the width is set to `3000`, it was automatically set back to `2999`.
