### ISSUE TITLE
Autolink URL's in Data Grid & Point Information Panels

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1564]
URL's present in the metadata panel, datagrid and the Point Information Panels (expanded view as well) should be turned into hyperlinks automatically.  This partially overlaps with work on the Enhanced Datagrid, however this should be done ahead of the FGP R2 release which as of yet, would not include that functionality.

![wt](https://cloud.githubusercontent.com/assets/7583387/21783313/c7d50cae-d684-11e6-99e3-55606d235255.png)

**Comment by AleksueiR** [comment]
We can't easily autolink urls in the datatable because truncated cells rendered as input fields, and it's not possible to add a link inside an input field: https://www.w3.org/TR/html51/single-page.html#the-input-element

**Comment by jolevesq** [comment]
There is a way to add url in datatable if we are able to know there is a url. For thematic map in GCViz from the authoring tool we can set url field and generate url a little bit like what we do when text is too long. If we are able to detect url we can do something.

**Comment by mweech** [comment]
Will split out Datagrid autolinking into it's own issue and assigned to @jolevesq

**Comment by james-rae** [comment]
For reference, this commit uses a filter to apply date formatting to both datagrid and details panel.  Possibly the same approach can be utilized here, assuming it works with Johann's solution
https://github.com/fgpv-vpgf/fgpv-vpgf/commit/83755011d2f47a300d403ed7418e92ac8ed9c75c
