### ISSUE TITLE
Viewer Crashes in IE & Firefox 

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1566]
Reported on FGP Redmine and echo'ed by @dan-bowerman re: JOSM templates.

"When trying to view the map in either IE or Firefox, the application crashes. Here is a sample URL

[[http://dev.gcgeo.gc.ca/viz/index-en.html?keys=3a1eb6ef-6054-4f9d-b1f6-c30322cd7abf]]

I have attached messages from bot Firefox and IE

IE 11.0.9600.18537
Firefox 50.1.0

Works fine in Chrome."

![ie](https://cloud.githubusercontent.com/assets/7583387/21816089/d7b9f19a-d72c-11e6-9b71-1538d4afb336.jpg)

![firefox](https://cloud.githubusercontent.com/assets/7583387/21816099/ddad9200-d72c-11e6-9db9-283ea0f2d8d6.jpg)

**Comment by dan-bowerman** [comment]
Testable within ECCC's network at http://maps-cartes.dev.ec.gc.ca/JOSM/index-fgp-en.html, and http://maps-cartes.dev.ec.gc.ca/JOSM/index-fgp-en.html and http://maps-cartes.dev.ec.gc.ca/JOSM/josm_map_en.html

**Comment by dan-bowerman** [comment]
As @alyec wisely suggested, moving the WET JavaScript statements above the RAMP bootstrap line seems to clear things up.

**Comment by alyec** [comment]
FYI I did find different errors for IE and FF, here's a summary of the issues:

Testing GCGeo on Firefox: no errors observed, but the map was inside the sign in div and rendered as 2px high.
Testing GCGeo on IE: `/lib/ie-polyfills.js` gave a 404 error and a message about Object.assign being undefined showed up in the console (`ie-polyfills.js` should provide Object.assign)
Testing JOSM on Firefox: loaded correctly
Testing JOSM on IE: `/lib/ie-polyfills.js` gave a 404 error and a message about Object.assign being undefined showed up in the console (`ie-polyfills.js` should provide Object.assign)
