### ISSUE TITLE
Update Help to include descriptions of new functionality

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1568]
such as the new `reorder` mode, `expand/collapse layer groups`, and `hide/show all layers`.

**Comment by milesap** [comment]
I'll block this on #1555 until design is confirmed. Will also go through existing sections and add/improve content. Need to do same for french. Bumping estimate as well.

**Comment by milesap** [comment]
French to follow on #1800
