### ISSUE TITLE
Export Datatable columns have extra format descriptions instead of pure values

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1570]
Tested build http://fgpv.cloudapp.net/demo/v1.5.0-9/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

- Open Datatable for any feature layers, for example JOSM
- Export Datatable
The format displayed as below example:
![image](https://cloud.githubusercontent.com/assets/18723160/21864319/3b14f054-d80f-11e6-994d-83ee0ca4ef29.png)

![image](https://cloud.githubusercontent.com/assets/18723160/21864162/84c0ae38-d80e-11e6-8d0a-04b4480f9c9b.png)

Link to issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/759

**Comment by jolevesq** [comment]
This happen because input tag are not strip off from the table when it is exported to CSV. The issue #1577 replace the input by a span tag and span tag are strip off when exported so it solve the problem.

**Comment by IsabellaPan** [comment]
Feb 9 2017
Not an issue in build v1.5.0/prod
