### ISSUE TITLE
Left side menu Panel of the Viewer remains open in Full screen mode

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1573]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-9/prod/samples/

This behaviour is different in v1.5.0-8 where the panel is not open when the viewer is in Full screen mode

Steps to Reproduce

- Load the Viewer
- Select "Full Screen" from the left side panel 
- Viewer loads in Full Screen
- Left side Panel does not slide back/remains open in Full screen mode

![image](https://cloud.githubusercontent.com/assets/18539315/21892484/19d7a8aa-d8a5-11e6-88e2-a566db262fac.png)

**Comment by AleksueiR** [comment]
This is updated behaviour. The side menu will remain open as the Full screen mode is toggled. Not a bug.

**Comment by bkutty** [comment]
Is this updated behaviour mentioned in any item#? This is just so that I can trace it back to Reqs.

**Comment by AleksueiR** [comment]
I just added a comment to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1548.

**Comment by bkutty** [comment]
Expected behaviour. Closing the issue
