### ISSUE TITLE
Plant Hardiness Zones of Canada Layer still does not load in IE

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1574]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-one.html

Plant Hardiness layer still does not load in IE. Please see below the error in Console.

![image](https://cloud.githubusercontent.com/assets/18539315/21893081/92774476-d8a7-11e6-9af4-07b82e18e01d.png)

**Comment by ChrisLatRNCan** [comment]
CORS problem.

SEC7118: XMLHttpRequest for http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_plant_hardiness_zones/MapServer/0/query?where=OBJECTID%3E99000&outFields=*&returnGeometry=false&f=json required Cross Origin Resource Sharing (CORS).
File: index-one.html

**Comment by milesap** [comment]
Confirmed data is loading in IE (and chrome) using link http://fgpv.cloudapp.net/demo/develop/prod/samples/index-one.html

Since there are 107,498 entries and IE being IE, the data will appear in 3-7 minutes. Chrome takes 3-7 seconds, though there is still a noticeable delay.
