### ISSUE TITLE
Plant Hardiness zones of Canada Layer-  Symbology "undefined" in Data grid

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1575]
Tested Build :http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-one.html

Please investigate why symbology for "Zone" is displayed as undefined in the data grid for this layer. I can get to load this Layer only in Chrome so far.

![image](https://cloud.githubusercontent.com/assets/18539315/21893444/0868a034-d8a9-11e6-8bc2-9034f477e392.png)

**Comment by mweech** [comment]
Likely related to #1600

**Comment by IsabellaPan** [comment]
Mar 8 2017
Tested with build http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-one.html
Undefined is removed from symbol, but the height of those data row is not correct. See below:
![image](https://cloud.githubusercontent.com/assets/18723160/23713416/d34709ba-03f3-11e7-9b2a-77e69836d2c8.png)
