### ISSUE TITLE
Scrollbars and Zoom To/Details Buttons missing on DataTable

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1576]
JOSM layer is not having scroll bars (horizontal or vertical) applied to the data table.

Link: http://fgpv.cloudapp.net/demo/v1.5.0-9/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

![capture](https://cloud.githubusercontent.com/assets/7583387/21894693/247fbbfe-d8ae-11e6-9b8d-1c84cf5a3ed4.PNG)

**Comment by IsabellaPan** [comment]
Jan 24 2017
Not an issue in build http://fgpv.cloudapp.net/demo/v1.5.0-15/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
