### ISSUE TITLE
Side menu content is crushed in IE on initial opening

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1578]
![](https://i.imgur.com/9PLJrNc.png)

It fixes itself if you cycle the Fullscreen mode.

**Comment by AleksueiR** [comment]
Duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1510.

**Comment by AleksueiR** [comment]
Now it's broken on the `index-one` page (![](https://img.zohostatic.com.cn/writer3/Aug_16_2016/images/ie-icon.png):gun:) :


![](https://i.imgur.com/a3aByjB.png)

**Comment by bkutty** [comment]
Issue is fixed now as per tests on v1.5.0-15
