### ISSUE TITLE
Language for Basemap labels and descriptions not toggled when using Side Menu toggle button

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1586]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

-  Go to Side menu
-  Click French under Language 
-  Open BASEMAP
The Projection names, Lambert and Mercator switched to French, but Basemap labels and descriptions under them still displayed in English.
![image](https://cloud.githubusercontent.com/assets/18723160/21933180/5dcd66e4-d972-11e6-8be4-3d4d64a365c8.png)

**Comment by mweech** [comment]
related to #1539.  fixed in new build.

**Comment by jolevesq** [comment]
Description is in the configuration file. French file needed translation.

**Comment by IsabellaPan** [comment]
Jan 24 2017
Fixed in build http://fgpv.cloudapp.net/demo/v1.5.0-15/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
