### ISSUE TITLE
FGP Visualiser not loading in IE11

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1587]
Tested build http://fgpv.cloudapp.net/demo/v1.5.0-11/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

The performance in IE11 is getting even worse with above build. Not able to load map at all.

![image](https://cloud.githubusercontent.com/assets/18723160/21936215/5d949b50-d97e-11e6-992b-e49215d0f8d8.png)

**Comment by bkutty** [comment]
Not an issue as tested on v1.5.0-15
