### ISSUE TITLE
Content of certain long text fields in the datagrid seems to overflow when you mouse over

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1589]
tested build :http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Related : #1482

tested with : http://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer/ 

While testing item#1482, we notice that longer texts in data grid are overflowing and not readable to the user when you mouse over

![image](https://cloud.githubusercontent.com/assets/18539315/21937449/88c13c82-d985-11e6-9fb8-a4b44e94a899.png)

**Comment by jolevesq** [comment]
@bkutty Can you tell me on wich browser? I tested it with Chrome and FF and I can't reproduce.

**Comment by bkutty** [comment]
@jolevesq I got this in Chrome Version 55.0.2883.87 m

**Comment by jolevesq** [comment]
Ok, find the error when we have url. It is because of the wrapping. I can solve this as part of #1577.
