### ISSUE TITLE
feat(core): add mobile browser detection script

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#159]
Find and include a script for detecting mobile browsers.
Can be used for things like making menu buttons larger for ease of finger tapping, etc.

Something like this: http://detectmobilebrowsers.com/ or https://github.com/hgoebl/mobile-detect.js

**Comment by mweech** [comment]
decision was to avoid problematic detection of mobile browsers and instead preference is to adjust interface depending on screen size.
