### ISSUE TITLE
Object ID placement  in the datagrid for CESI :Other Air Indicators is different

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1590]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Object ID appears twice in the datagrid for the sub layer " Mercury Emissions to Air"
Object ID appears as the last field in "Greenhouse Gas Emissions" grid

Please fix the issue

![image](https://cloud.githubusercontent.com/assets/18539315/21938588/faccebec-d989-11e6-91d3-7654e416aa57.png)

**Comment by mweech** [comment]
This is the order of the fields according to the relevant service layers defined by the Map Service (we did not create this one).

http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/36
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/34

**Comment by bkutty** [comment]
Not an issue. Working by design
