### ISSUE TITLE
Datagrid not loading for all sub-layers under EcoAction Community Funded Projects

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1593]
Tested build http://fgpv.cloudapp.net/demo/v1.5.0-11/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

![image](https://cloud.githubusercontent.com/assets/18723160/21941679/ed6db54a-d997-11e6-9da8-6c65063714d8.png)

Console error:
> core.js:12798 RangeError: Invalid string length
    at Array.join (native)
    at getColumnWidth (http://fgpv.cloudapp.net/demo/develop/dev/lib/core.js:132393:73)

**Comment by bkutty** [comment]
No longer an issue as per tests on v1.5.0-15.
