### ISSUE TITLE
Datatable fails to populate for Eco Geo dynamic layer

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1594]
On current dev `index-one.html` or [v.1.5.0-10 `index-fgp.en`](http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=EcoAction):
 - open layers panel, 
 - click on one of the Eco Geo sublayers
 - observe datatable perpetually loading
 - observe the the following console error:

> core.js:12798 RangeError: Invalid string length
    at Array.join (native)
    at getColumnWidth (http://fgpv.cloudapp.net/demo/develop/dev/lib/core.js:132393:73)

**Comment by IsabellaPan** [comment]
Is this the same issue as logged in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1593?

**Comment by AleksueiR** [comment]
Indeed :) you were faster by 30 minutes. 

Closed as duplicate.
