### ISSUE TITLE
Keyboard Issues in Add Layer

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1595]
Two small annoyances:
- pressing enter on the URL in `Add Service` does not trigger the continue action, it must be tabbed to directly
- there seems to be a hidden select box between the styled drop down and the cancel button on the second step
  - to find this add a service, go to the second step, when tabbing from the service type drop down to the buttons there is a point where the focus goes invisible, hitting space / enter will show a select box

**Comment by jolevesq** [comment]
Another problem... when we press enter on continue at step 1 the focus goes back to close button. Would not be more appropriate for the focus to go at the service type selection? Less confusing then focus going back to close button. This append when we switch from step 2 to step 3 as well.

**Comment by jolevesq** [comment]
Because md-select has name, it creates a select element inside md-input-container and tab goes to this element even if it is tabindex="-1"

```<md-select name="dataType" ng-model="self.layerBlueprint.fileType" md-on-open="self.select.selectResetValidation()" required>...
```

```
<select class="md-visually-hidden" name="dataType" aria-hidden="true" tabindex="-1"><option value="" class="ng-binding">import.file.type.</option><option ng-value="self.layerBlueprint.fileType" selected="" value="csv"></option></select>
```

**Comment by AleksueiR** [comment]
Do we set its name or is it autogenerated? If we are setting it, is it necessary?

**Comment by jolevesq** [comment]
We set the name and if I remove it I have this error ```TypeError: Cannot read property '$setValidity' of undefined```

```
function toggleErrorMessage(form, fieldName, errorName) {
            var state = arguments.length <= 3 || arguments[3] === undefined ? false : arguments[3];

            // when showing errors, dirty and touch the fields
            // this is needed when a preselected field causes validation to fail; since user hasn't interacted with the field, it's untouched and pristine and error messages are not shown for untouched fields;
            if (!state) {
                form[fieldName].$setDirty();
                form[fieldName].$setTouched();
            }

            form[fieldName].$setValidity(errorName, state); ERROR HERE!!!
        }
```

**Comment by AleksueiR** [comment]
Yeap, that is important. This seems like a side effect of setting the `name` property on `md-select` and this generated `select` field doesn't' seem to affect the `md-select` control and how it works. Either removing or `display: none` hiding (I just tried and both approaches work) this field should be enough to fix this. (hiding is simple since it's only a CSS change)

**Comment by jolevesq** [comment]
I will do that, thanks. I saw other implementation on the web and they do not have our side effect of the name attribute. I will not dig deeper if css solve the solution.
