### ISSUE TITLE
Small and medium layouts are not applied in all cases

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1599]
They work correctly when the browser window is resized; however, optimized layout are not applied if the size of the map container itself is small. See screenshot (this is still `large` layout):

![](https://i.imgur.com/6jrrkCs.png)

These layouts are applied using media queries and they won't fire if the browser window is itself remains unchanged. Need a way to force layout reflows based on the container size.

**Comment by ChrisLatRNCan** [comment]
Does pushing the Canada view button will zoom-out ?

**Comment by milesap** [comment]
One idea would be to append the class `rv-small`, `rv-medium`, or `rv-large` to the `$rootElement` depending on the width of the map. There would be a `resize` listener on this element which would update the class accordingly. 

As a result, this would make media queries obsolete and they would be completely removed.

**Comment by AleksueiR** [comment]
Good idea. There is `rvResize` directive which was never used. Maybe that can help.

**Comment by bkutty** [comment]
No longer seems to be an issue. Accepted
