### ISSUE TITLE
feat(core): write language detection routine

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#16]
with tests

**Comment by AleksueiR** [comment]
Not sure if this is still relevant. The app (if app's language is not specified explicitly) was to run some check to determine the language of the host page and switch to that language.

**Comment by spencerwahl** [comment]
Right now we default to the first language in `rv-langs`, English if nothing is specified

**Comment by ChrisLatRNCan** [comment]
I'm pretty sure it is related to the issue #620 on which I'm already working on. Please comment #620 so we get on the same page. I'm actually trying to cope with rv-langs specified/not specified.
Thanks

**Comment by AleksueiR** [comment]
We had some notes on language detection from the last year. Not sure how accurate they still are though.

#### Language Detection
Language can be specified inside the config file or inferred from lang attribute of the parent's container (in case of several, the most direct parent is used). Language determines which translation files to load and, optionally, which config file to load.

#### Sequence
1. Check if map-cfg is an object. 
	- a. Check if the lang attribute is set, use default language otherwise.
	- b. Load translation files. Stop.
2. Check if map-cfg refers to a global object. 
	- a. Check if the lang attribute is set, use default language otherwise.
	- b. Load translation files. Stop.
3. Check if map-cfg is a URI containing __lang__ substring.
	- a. Search DOM upwards from the root element looking for lang attribute on a parent node, use default otherwise if not found any.
	- b. Substitute __lang__ with the found language value.
	- c. Load the config file using resulting URI.
	- d. Load translation files. Stop.
4. Check if map-cfg is a URI and can be loaded successfully.
	- a. Check if the lang attribute is set in the config.
      - i. If not set, search DOM upwards from the root element looking for lang attribute on a parent node, use default otherwise if not found any.
	- b. Load translation files. Stop.

**Comment by ChrisLatRNCan** [comment]
Nice to know. I should have ask sooner.

**Comment by ChrisLatRNCan** [comment]
Since I'm already in language "management" stuff

**Comment by ChrisLatRNCan** [comment]
Maybe the issue would need to be renamed "Language management" but for the time being I'll list some tasks to be done regarding everything concerning a multilingual viewer
Please feel free to add/comment tasks
- [ ] Check if we still need a detection routine

- [ ] Document more the language initialization/transition flow (wiki)

- [ ] Chase english only stuff (eg. error message, info coming from services, etc)

- [ ] Have some kind of thesaurus for specific terms for a seamless UX  (wiki)

**Comment by AleksueiR** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2835.
Solved by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2861.
