### ISSUE TITLE
chore(r&d): multiple versions of Datatables

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#160]
Check if multiple versions of Datatables (from the wrapper page) can cause any problems and if there is any solutions for it.

**Comment by spencerwahl** [comment]
Slightly more complicated than expected to check for datatables existing. I have it loading through CDN right now; might need to be changed as that seems to have caused problems with the jQuery fix and our network. This should be in PR Monday morning.

**Comment by spencerwahl** [comment]
PR: #478
