### ISSUE TITLE
Symbol showing undefined with bad renderer

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1600]
Test layer `http://section917.cloudapp.net/arcgis/rest/services/TestData/ClassBreaks/MapServer/0`

There is one feature in this layer that is too big to fall under the range of the renderer, and the renderer has no default defined.  So you don't see the feature on the map, which is correct, we are doing what the renderer instructs.

However, when we see that feature in the grid, we see `undefined` in the symbol column.  Would suggest we add some catch-all logic to the symbology engine, so that if it fails to find a valid symbol, it defaults to an empty svg (i.e. the column is empty, but does not show `undefined`).

Feature in question is `Queen Maud Gulf Migratory Bird Sanctuary`, OID 12 so it is 12th in the grid with default order.

**Comment by bkutty** [comment]
While testing this issue on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html, an issue was found with the datagrid layout as below. Re-opening the issue for further investigation

![image](https://cloud.githubusercontent.com/assets/18539315/23083656/c772c780-f52c-11e6-906e-2e6ee3c44185.png)

**Comment by jolevesq** [comment]
My PR review modification added the size problem. I resubmit a new PR to solve this.

**Comment by IsabellaPan** [comment]
Mar 7 2017
It seems to be an issue for the height of problemed data rows, though undefined in the symbol column fixed to have an empty svg.
See below example for ObjectID 12, checked with build v1.6.0-0
![image](https://cloud.githubusercontent.com/assets/18723160/23710322/52ba2f4c-03ea-11e7-9c7f-ee1c5152fad3.png)
