### ISSUE TITLE
User added Scale Dependency layer -  Unable to load Feature Details when clicking on map points

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1601]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-13/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
User added scale dependency layer:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This issue happened with all three major browsers.

• Add scale dependency layer by selecting zoom level 1 to zoom level 4
• Click any map point for the added layer to display Feature Details panel

![image](https://cloud.githubusercontent.com/assets/18723160/22036089/48d27788-dcc0-11e6-8f25-4d9a0da5f260.png)

**Comment by bkutty** [comment]
No longer an issue. Accepted
