### ISSUE TITLE
Hovertips fight with Highlighter

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1604]
Our feature highlighter masks the map.  Currently, two things happen when a highlight appears and the map has hovertip layers

* If a hovertip was active when the highlight is applied, the `mouse-out` event on the hovertip graphic does not trigger.  This results in the hovertip never disappearing until the user changes the scale level.
* When highlight is active, no features can trigger a hovertip. This is because the haze polygon is on top of everything and blocks any mouse events to the stuff under it.

## Short Term Solutions

* Change default config setting for hovertips to `false`. This means tips are available to custom implementers, but the catalog site / RCS sources will have them off (and this might be a good thing; else we will have catalog maps where only some layers have hover tips, or we need to modify RCS to explicitly set the tips to OFF for all registrations)
* Add code to clear any hovertips whenever a highlight is requested. This will solve the hovertip that never leaves.

## Long Term Solutions

* Implement the Alex highlighting approach.  It gets rid of the haze polygon. See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/820
* Implement hover events on highlight layer as well to enable hover on highlights (RAMP1 did a similar approach...need to link graphics in highlight layer to their source graphic)

**Comment by mweech** [comment]
I vote short term option 2 for now.  Long term we should do #820.

**Comment by AleksueiR** [comment]
Can someone update #820 with the long term solution for this?

**Comment by IsabellaPan** [comment]
Mar 7 2017
No longer an issue, verified with build http://fgpv.cloudapp.net/demo/v1.6.0-0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
