### ISSUE TITLE
Identify broken for Dynamic Layers

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1608]
A recent change to support date-time formatting is depending on an optional fields parameter to be present.  The Dynamic identify code doesn't use fields, as it comes back already aliased.  So the optional parameter isn't there, and the date code attempts to do array operations on nothing.

Will change logic around so it works

**Comment by bkutty** [comment]
Verified per tests on v1.5.0-16
