### ISSUE TITLE
Loading order is incorrect

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1609]
bootstrap.js / core.js is async loading or loading in the wrong order. This is preventing Plugins from loading correctly. 

Blocking #1565

**Comment by bkutty** [comment]
Back to Cart functionality is working as expected now. Tested on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley
