### ISSUE TITLE
Identify error on OGC/WMS added layer

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1614]
Load **Railway network** layer from http://maps.geogratis.gc.ca/wms/railway_en

Two types of error

**Type 1** No result won't make the previous record disapear
![erroridentify](https://cloud.githubusercontent.com/assets/16193004/22159567/8e6607c8-df0f-11e6-8cf3-e2fd731ae38d.gif)

**Type 2** Clicking multiple times with the identify tool will always return the same record (the first selected) in the panel but the good one in the expanded view  
![erroridentify4](https://cloud.githubusercontent.com/assets/16193004/22159860/e8659774-df10-11e6-8d9f-68f9767a7cfd.gif)

**Comment by ChrisLatRNCan** [comment]
feeling stupid
Found the problem in svg.directive.js
```
                   // do not watch for updates to src anymore
                   if (attr.once) {
                         stopWatch();
                     }
```
Removing those lines solve the problem. Doesn't know yet if there's an unwanted side effect.

**Comment by AleksueiR** [comment]
This will definitely cause problems. Try adding `once="false"` attribute to this line: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/details/details-content.html#L19

**Comment by ChrisLatRNCan** [comment]
Saw your comment too late. Ok, I'll try that. Thx

**Comment by ChrisLatRNCan** [comment]
Ok, it works perfectly. I would have never found that solution by myself. I'll push modif.

**Comment by AleksueiR** [comment]
You were more than half-way there though.

**Comment by bkutty** [comment]
Tested build :http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-fgp-en.html

I still see the identify error when adding the railway layer. Also there is a known issue pertaining to this bug #1613
