### ISSUE TITLE
Add "drop down selection" filters type for datagrid

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1617]
Be able to filter by selection or multi selection items from a drop down menu. This filter can be use by thematic map when author specify the type in the configuration file. This issue will need an update to the config file schema and the creation of a selection type filter.

**Comment by mweech** [comment]
is this issue blocked until we are further down the refactoring path?

**Comment by mweech** [comment]
@jolevesq which PR did this get bundled into?

**Comment by jolevesq** [comment]
Resolve by #1944
