### ISSUE TITLE
Reorder fields  for datagrid from settings panel

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1618]
Need to check for side effect with display and sort because on the settings panel because reordering the fields will modify the index. Because table is deleted each time those reordered fields index will have to be kept somewhere.

It should follow the same approach for reordering as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1457

**Comment by AleksueiR** [comment]
Can we store them with the formatted attribute data? Filters are stored there already.
