### ISSUE TITLE
Use Global Search to Type Complex Queries for Datagrid

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1619]
Currently, global search, search for the value inside the whole table and display rows who contains that value. We can use the global search input to search complex queries.

- [x] set query language type
- [x] show field internal name not only title (query will be easier)
- [x] update help

**Comment by AleksueiR** [comment]
Any thoughts on what the query language should look like?

**Comment by jolevesq** [comment]
@AleksueiR do we go with something like subset of SQL or the way GitHub does the filtering. Datatable is not made to be queried by SQL. We will have to keep the query functions basic because we will have to implement all the functionnalities.

For field name, we can use the real name but it can be hard to type long name (you can always cut and paste) and the query will be pretty long. We can use the field position. It will be simple but not easy to read and confusing when there is a lot of fields. We can use the real field name but we will have to show them some way and do we really want to expose internal stuff?

SQL

=	Equal to	Author = 'Alcott'
<>	Not equal to (many DBMSs accept != in addition to <>)	Dept <> 'Sales'
>	Greater than	Hire_Date > '2012-01-31'
<	Less than	Bonus < 50000.00
>=	Greater than or equal	Dependents >= 2
<=	Less than or equal	Rate <= 0.05
for range, it is a combinaison of greater then and less then
we can use * for wildcard in string comparison
we separate all query by AND


GitHub
https://help.github.com/articles/search-syntax/
=	Equal to	Author:'Alcott'
<>	Not equal to (many DBMSs accept != in addition to <>)	Dept <> 'Sales'
>	Greater than	Hire_Date:>'2012-01-31'
<	Less than	Bonus:<50000.00
>=	Greater than or equal    Dependents:>= 2
<=	Less than or equal	Rate:<= 0.05
for range Rate:[0.05..0.30]
we can use * for wildcard in string comparison
we can use space between field for separator (if we only use AND).

Do we want to let user only use AND and avoid OR. I don't think there is an easy way to query with OR in datatable. In datatable you can use regex search to do OR but regex is not easy to build. Or we can create custom filter like the one we use for number and date filter.
http://stackoverflow.com/questions/25382569/jquery-datatables-or-search-filter

**Comment by AleksueiR** [comment]
I think we should go with Github search-syntax: it's already defined, so we don't have to come up with our own or even pick a subset of SQL to implement (also avoids further questions why we didn't implement something specific from SQL). Maybe we can leverage some existing parsers to at least break the query string, like this one: https://github.com/nepsilon/search-query-parser

For field names, what do you think about using first three (or more, up to the full name) letters for identification? If there are several fields which have the same three letters, the user must use four or more, but the minimum of three is required for everything else. Additionally, as long as the table search field has some content typed it, display these column identifiers to help the user:
![](https://i.imgur.com/NwjYPNi.png)

Would using just `AND` be sufficient for querying the table? It would be nice to have `OR`, but if it requires lots of time and effort to implement, maybe this can be done later.

**Comment by alyec** [comment]
If we can get it free with a good library I say we go with that option.  I'm definitely in the camp of avoiding complexity until we need it so if we want to keep a very limited syntax initially I'm fine with that.

**Comment by jolevesq** [comment]
Github use Lucene syntax to perform query (http://stackoverflow.com/questions/10618509/advanced-search-on-github). I found this parser https://www.npmjs.com/package/lucene-query-parser to break it down. There some difference between Lucene and Github syntax like the range (git:[1..2] and Lucene:[1 to 2] difference. We can use the same as github and just replace difference by Lucene syntax and use the parser.

**Comment by jolevesq** [comment]
Datatable use regex to search (filter) the rows. Use regex make it very simple to use datatable. I will try to find if there is an easy way to parse from Lucene syntax to regex. For string, range there is no problem. For number > another number or date it seems a little bit more complicated

**Comment by AleksueiR** [comment]
What do you think about using shortened field aliases for field names?
I was also thinking about adding auto-complete for filed names to the search, but auto-complete controls are notoriously troublesome especially when you want builds something complex.

**Comment by jolevesq** [comment]
I was thinking using drag and drop from colReorder extension to add the field name to the search box. For keyboard user it doesn't help but it can be good for the other. For the field alias it can be a good idea but how do you show them to user? In the tooltip?

If we go with regex for the search, we will be able to replace our global search filter by regex filter for date and number. It should help for query performance.

**Comment by AleksueiR** [comment]
Drag-n-drop of column might get horribly tricky I'm afraid, when dropping a column in the middle of a string. We can display field aliases in the column headers (see my screenshot above), either along the full name or replacing it. Aliases will only be displayed when there is a query string in the search box.

**Comment by jolevesq** [comment]
Ok for the alias display when user focus/enter text in search box.

For regex, do you know a parser from text to regexp for :>number or :>date? For the rest it is not too complex.

**Comment by AleksueiR** [comment]
Nope, unfortunately. You are thinking of using the `OR` operator after all?

**Comment by jolevesq** [comment]
Doing OR inside one field is not hard (city:London|Tokyo). Doing it between fields will be a little bit harder but I think it can be achieve. I just don't know if i go with the speed of regex search (need to parse the text query to regex or I go with a global filter like what we have for number and date and have more flexibility.

**Comment by jolevesq** [comment]
I can't just add the field name because the width is set and it will overflow. I can replace the whole title by the data value. Technically title should be longer then data. I can put the data then the title and render the overflow with ... what do you prefer?
