### ISSUE TITLE
Create a github.io site for viewer documentation

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1625]
Example: http://ramp-pcar.github.io/docs/index-en.html

Also look into a suitable layout (either copy the above or find a better one).

**Comment by milesap** [comment]
Documentation url: http://fgpv-vpgf.github.io/fgpv-vpgf/
Generated on the `gh-pages` branch

**Comment by alyec** [comment]
We already have https://github.com/fgpv-vpgf/fgpv-vpgf.github.io and we can probably reuse that.  Just don't overwrite the autobuild folder.

**Comment by milesap** [comment]
My initial thoughts on this are to keep documentation within the repo. I created a `documentation` branch for this which gets published to the `gh-pages` branch. Right now its a manual process but travis could eventually publish the gh-pages build on documentation push.

**Comment by milesap** [comment]
Writing docs in wiki first, then we can tackle where to put them. Couscous does not work for organization pages on travis out of the box. JSDoc works but is not very customizable.
