### ISSUE TITLE
Config data option is not being applied

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1628]
Turning off the `options.data` setting in the config file still results in the data table being accessible in the app.

Oil Sands would use this to prevent the Oil Sands Regions layer from exposing a table.

**Comment by dan-bowerman** [comment]
Sample config snippet:
```
    {
      "id":"regions",
      "name": "Régions",
      "layerType":"esriDynamic",
      "layerEntries": [{"index": 1}],	  
      "options": {
        "opacity": { "value": 1.0 },
		"query": { "enabled": false, "value": false },
		"data": { "enabled": false, "value": false }
      },
      "url":"http://section917.cloudapp.net/arcgis/rest/services/JOSM/Oilsands/MapServer"
    }
```

**Comment by jolevesq** [comment]
In this case we may have a problem. The data options is not at the right level. It should be at the layerEntries level to apply only on one child layer.

**Comment by dan-bowerman** [comment]
Do you mean like this?:

```
    {
    	"id": "regions",
    	"name": "Regions",
    	"layerType": "esriDynamic",
    	"layerEntries": [{
    			"index": 1,
    			"data": {
    				"enabled": false,
    				"value": false
    			},
    		"query": {
    			"enabled": false,
    			"value": false
    		}
				
    	}],
    	"options": {
    		"opacity": {
    			"value": 1.0
    		}
    	},
    	"url": "http://section917.cloudapp.net/arcgis/rest/services/JOSM/Oilsands/MapServer"
    }
```

In this case, excellent, I can no longer identify on the layer.. however I still am able to open the data grid for it.

**Comment by jolevesq** [comment]
Yes, data will have to be inside layerEntries like that:

 "layerEntries": [{"index": 6, "data": { "enabled": false }}, ...  {"index": 7}, {"index": 8}, {"index": 9}]

Some modification will have to be made to the code to make it work. I saw the problem with identify, I will solve this at the same time.

**Comment by dan-bowerman** [comment]
@jolevesq Disabling identify and the grid is what I hope to accomplish.

It appears I am still able to identify, though I do see the flag that says I shouldn't be able to query:

![image](https://cloud.githubusercontent.com/assets/5294596/22472808/b52db9c6-e7a4-11e6-9ae8-acc9a81f8586.png)

**Comment by jolevesq** [comment]
I saw the flag problem and it will be solve at the same time. You will be able to disable both and flag we be visible accordingly
