### ISSUE TITLE
Zoom to feature extent is offset

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1629]
When zooming to a feature, it's placed about 3/4 down the height of the viewer instead of putting it in the middle.

![](https://i.imgur.com/oURuj9k.png)

**Comment by AleksueiR** [comment]
I think the zoom logic assumes the datatable is open taking the upper half of the screen, and compensates by offseting the extent.

**Comment by IsabellaPan** [comment]
Mar 9 2017
Fixed in build http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
