### ISSUE TITLE
Move "Details" and "Zoom to Feature" Links to Symbology Column of Datagrid

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1630]
Currently the linkage for details and zoom to feature are located in the first data column of the datagrid.  However these columns are often ID fields (random integers) and could potentially require wide columns now that column width is set based on service field length.  Moving the links to the symbology column would better group the graphical elements of the datagrid and allow them to remain a static distance from the left side of the datagrid.

**Comment by AleksueiR** [comment]
See here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1631#issuecomment-275457474
