### ISSUE TITLE
Data grid functionality dependent on ObjectID column being first

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#1631]
See http://section917.cloudapp.net/JOSM/josm_map_en.html (warning, this link may get blown away if any major developments occur in the next couple days since creating this issue).

As a test, I modified JOSM's MXD to move the mandatory ObjectID field to the bottom of the fields list:
![image](https://cloud.githubusercontent.com/assets/5294596/22340472/934e7f9e-e3bb-11e6-9354-00a05211f409.png)

And while this does achieve the effect of having the ObjectID listed at the bottom/end of the details pane/data grid, the data grid loses the zoom to functionality and the icon shortcut that would open the details pane for that row.

![image](https://cloud.githubusercontent.com/assets/5294596/22340586/f1007ef8-e3bb-11e6-85b9-346ffec4d9fc.png)
vs.
![image](https://cloud.githubusercontent.com/assets/5294596/22340625/1299bd22-e3bc-11e6-9363-7c8971cb1e12.png)

**Comment by james-rae** [comment]
It looks like we are hotwiring the OID field for the zoom/details button.  We should probably refactor so those two buttons are column independent (possibly putting them in the symbol column?).  
I believe there is a hidden field with object ID at the end of the grid that we can use, allowing us to not show OID in the grid.

**Comment by james-rae** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1630

**Comment by AleksueiR** [comment]
In 1.6, zoom/details buttons are moved to a separate column right after the symbology:
![](https://i.imgur.com/mLWqxcJ.png)

**Comment by mweech** [comment]
great! lets bring forward those changes to 1.5.1... 1.6 release date is undefined.

**Comment by bkutty** [comment]
Accepted as tested on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley
