### ISSUE TITLE
"Plugin Links/Back to Cart" on the left side panel is missing once "back to cart" on top of the home page is clicked

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1632]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley

Steps to Reproduce

- Load FGP Viewer
- Click on "Back to cart" on top of the Viewer
- Map will reload with all the layers
- Select Left side menu panel
- The whole section of Plugin Links is missing
- 

![image](https://cloud.githubusercontent.com/assets/18539315/22345974/4fc5a67a-e3d0-11e6-86b6-74b7e2094777.png)

**Comment by milesap** [comment]
A quick fix has been created, however there is a blocking api issue which is being patched by @alyec.

**Comment by bkutty** [comment]
Accepted. As tested on http://fgpv.cloudapp.net/demo/v1.5.0-rc3/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley
