### ISSUE TITLE
All layers disappear after selecting "Back to Cart" from Full screen 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1634]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley

**Steps to Reproduce**

- Load FGP Viewer
- Select "Full Screen" from the left side panel
- Full screen viewer loads
- Select "Back to Cart" from the left side panel
- Viewer exits full screen, however all layers are not retained

![image](https://cloud.githubusercontent.com/assets/18539315/22346262/7256734e-e3d1-11e6-99f1-c3bbb87c9c75.png)

**Comment by mweech** [comment]
no longer an issue under develop.

**Comment by bkutty** [comment]
Accepted as tested on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,ZoomScale
