### ISSUE TITLE
"SiteOnline Resource" url for some JOSM points cuts off in the feature details Pane

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1635]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html

This issue applies to only JOSM layers so far where if a map point has longer url for siteOnlineresourceText_en/siteOnlineResource_fr, the content seems to cut off as below. Mainly seen when there is xls link. Please fix the issue

![image](https://cloud.githubusercontent.com/assets/18539315/22347821/5d7b9048-e3d7-11e6-92ec-2730a0fd1136.png)

**Comment by AleksueiR** [comment]
Links are notoriously bad at wrapping. We can truncate the overflow so it looks like this:

![](https://i.imgur.com/UGVS8I7.png)

**Comment by AleksueiR** [comment]
All links are forced into a single line and truncated with an ellipsis (even in IE):
![](https://i.imgur.com/3kAzLF7.png)

**Comment by bkutty** [comment]
No longer an issue as per tests on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-fr.html?keys=JOSM
