### ISSUE TITLE
Unable to tab to the blue cell while navigating datagrid

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1638]
Tested build:http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley

Related to #1577 

Using a tab key, users can only navigate to Details and zoom to feature action buttons in the grid which is expected. However, if a cell is highlighted blue using arrow key, user cannot tab to this highlighted cell. Please investigate/advise the expected behaviour.

![image](https://cloud.githubusercontent.com/assets/18539315/22348888/534e2834-e3db-11e6-91fd-3daf24c68a80.png)

**Comment by AleksueiR** [comment]
Related issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1577
@jolevesq Can you add a bit of an explanation how the KeyTable extension works?

**Comment by mweech** [comment]
You CAN tab into the grid.  Aly and I were able to reproduce it, however it will always reset you to the top left cell.

**Comment by bkutty** [comment]
Okay. Was unclear how the datagrid should behave when you mix arrow key and tab to navigate. I was able to tab to the grid itself.

**Comment by bkutty** [comment]
Accepted. Working as designed
