### ISSUE TITLE
"SiteOnline Resource" url for some JOSM points are autolinked incorrectly

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1639]
JOSM's `siteOnlineResource_en` seem to ofter contains at least two urls separated by a pipe:
```html
http://www.ec.gc.ca/data_donnees/SSB-OSM_BioCont/Hunter-Trapper-Harvested-Wildlife-Toxicology-and-Contaminants/Metals-Terrestrial-Mammals-Pooled-Liver_2013.xlsx|http://www.ec.gc.ca/data_donnees/SSB-OSM_BioCont/Hunter-Trapper-Harvested-Wildlife-Toxicology-and-Contaminants/PAHs-Terrestrial-Mammals-Pooled-Liver-2013.xlsx
```

The autolinking library considers this as a single link, and autolinks it as one:
![](https://i.imgur.com/pSB5lMh.png)

I quickly tested several other autolinking libraries and none of them picked up the second link in the above sample. I would say this is really a problem with the data - there is no way to know a pipe is used as a delimiter.

Even Github autolinks this as a single URL. Observe:
http://www.ec.gc.ca/data_donnees/SSB-OSM_BioCont/Hunter-Trapper-Harvested-Wildlife-Toxicology-and-Contaminants/Metals-Terrestrial-Mammals-Pooled-Liver_2013.xlsx|http://www.ec.gc.ca/data_donnees/SSB-OSM_BioCont/Hunter-Trapper-Harvested-Wildlife-Toxicology-and-Contaminants/PAHs-Terrestrial-Mammals-Pooled-Liver-2013.xlsx

Thoughts?

**Comment by mweech** [comment]
Data issue
