### ISSUE TITLE
Legend generation not considering bookmark deletions

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1640]
In the case where we have dynamic layers that have more at least two levels of nested sub-layers, if a user deletes a nested sublayer, then makes a bookmark, the sublayer will re-appear when the bookmark is used.

Revist this after the legend refactor

See https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1627#issuecomment-275515469 for discussion

**Comment by mweech** [comment]
Closing this as this should be considered behavior as intended.  We are capturing inclusion of a layer or SET of layers as defined by a RCS ID.  If a user removes a subset and then reloads the map, RAMP should reload as the bookmark indicates.  The user can simply elect to remove the subset again.
