### ISSUE TITLE
User added Ozone layer - Zoom To Feature not working on Feature Details panel

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1643]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

-  Add above test data, select only Ozone layer in step 3
-  Click any map point for Ozone to open Feature Details panel
-  Click Zoom To Feature button on the panel
The map is not zooming to the selected map point.

![image](https://cloud.githubusercontent.com/assets/18723160/22377508/3e75c796-e480-11e6-8056-9267cf23c343.png)

**Comment by jolevesq** [comment]
When we add the sublayer directly it works. If I only add the top group, when I click indentify then zoom I have this error:

```
Uncaught (in promise) TypeError: Cannot read property 'options' of undefined
    at core.js:115188
    at zoomWithOffset (core.js:115196)
    at core.js:115080
```
zoomLayer is not define

```
 function zoomToGraphic(layer, zoomLayer, featureIdx, objId) {
                fetchGraphic(layer, featureIdx, objId).then(function (gBundle) {
                    zoomWithOffset(gBundle.graphic.geometry, layer, zoomLayer).then(function () {
                        applyHilight(gBundle);
                    });
                });
            }
```

**Comment by milesap** [comment]
Confirmed fix in PR #1721

**Comment by IsabellaPan** [comment]
Mar 6 2017
Still not working, tested with build http://fgpv.cloudapp.net/demo/v1.6.0-0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

**Comment by milesap** [comment]
Tested and working on v1.6.0 release http://fgpv.cloudapp.net/demo/v1.6.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

**Comment by milesap** [comment]
Fixed - closing
