### ISSUE TITLE
HTML code displayed in datagrid for this zoom scale dependent layer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1644]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley

Tested Layer: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_AirEmissions_CO/MapServer

![image](https://cloud.githubusercontent.com/assets/18539315/22377868/74c48b42-e481-11e6-91b0-f823ad508e79.png)

**Comment by AleksueiR** [comment]
I like how there is a `rampMap` call.

**Comment by mweech** [comment]
this service is not a good one for sharing in other viewers as its closely tied to the implementation of the CESI maps.  the RAMP2 viewer is appropriately passing through the contents of this data element which is a javascript fragment that is only useful on the CESI site.
