### ISSUE TITLE
feat(core): delivery method

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#165]
- [ ] Come up with a solution for delivering the viewer to the end user. CDN, local hosting, etc. (#152 is related)
- [ ] #153

**Comment by dan-bowerman** [comment]
Can we host the viewer library ourselves, and update existing deployments automatically?
Assess options for hosting vs. deploying built code. Connect with Technical Integration team. 

For now, follow the "build and ship" strategy.

**Comment by AleksueiR** [comment]
On script loading:
https://stackoverflow.com/questions/8996852/load-and-execute-order-of-scripts
https://www.w3.org/TR/html5/scripting-1.html#script
http://www.html5rocks.com/en/tutorials/speed/script-loading/

**Comment by mweech** [comment]
obsolete issue.  handled as part of #768
