### ISSUE TITLE
Enlarged Map points at times

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1655]
Tested:http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Map points appear too big at times. I don't get this error consistently though.

![map points](https://cloud.githubusercontent.com/assets/18539315/22514003/ec272fda-e86b-11e6-99b5-75e299b550c8.jpg)

**Comment by james-rae** [comment]
Haven't seen this in a year.  Will re-open if it resurfaces
