### ISSUE TITLE
SiteOnline resource links for some JOSM points loads  404 error page

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1656]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Related #1635 

![image](https://cloud.githubusercontent.com/assets/18539315/22516372/9b559760-e873-11e6-941c-24dbdc786819.png)

**Comment by AleksueiR** [comment]
All bad links are coming from the Catalogue.

**Comment by dan-bowerman** [comment]
This is a data provider issue, nothing wrong in RAMP. The JOSM data stewards are currently fixing these to update the links to a more standard format using IMD's "Data Mart 2" for the impending follow-up release for JOSM.
