### ISSUE TITLE
Back To Cart not loading any layers after removed Feature layers and Raster layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1658]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

-  Load above URL
-  Remove JOSM, Airports, and Barley layer one by one
-  Click Back To Cart from left side menu

It is found all the dynamic layers and WMS layer are not loading, however, URL bar still showed those layers (also the removed Airports layer showed there)
![image](https://cloud.githubusercontent.com/assets/18723160/22525510/70c35e20-e895-11e6-8cf7-91f56685327c.png)

**Comment by alyec** [comment]
Probably related to #1657

**Comment by james-rae** [comment]
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1657 appears to have resolved the major issues (layers not appearing), but we are still noticing some layers that were removed are re-appearing when we do Back to Cart.

Be sure to consider what the appropriate behavior of Back to Cart should be....normally the user would go back to the catalog, select new smallkeys, and reload the map. Unsure how we treat in-map deletions in this use case.

**Comment by james-rae** [comment]
Was a race condition. Back to Cart was clicked before the delayed removal from the layer registry, so back to cart thought it was still part of the map.  Added delete tracking to layer record

**Comment by IsabellaPan** [comment]
Feb 9 2017
Verified fixes with build v1.5.0
