### ISSUE TITLE
Scrollbars in details panel

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1659]
If the key name is an unbreakable string (no spaces), it will overflow its container and scrollbars will appear:

![](https://i.imgur.com/Ewq3Vpz.png)

If the key value is an unbreakable sting (no spaces), it will overflow its container and will be truncated on the left (no additional scrollbars) (this happens because both items float):
![](https://i.imgur.com/0osc64e.png)

**Comment by AleksueiR** [comment]
Solution:

- breakable key names are wrapped normally (breaking at spaces)
- breakable key values are wrapped normally (breaking at spaces)
- unbreakable key names are break-wrapped to prevent overflowing (at any character)
- unbreakable key values are break-wrapped to prevent overflowing (at any character)
- links are forced into a single line and truncated with an ellipsis

Here's an example:
![](https://i.imgur.com/oQbHZpd.png)

**Comment by bkutty** [comment]
Accepted per tests on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-fr.html?keys=JOSM
