### ISSUE TITLE
rvInteractive field is shown in the feature details view

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1661]
http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-fr.html?keys=JOSM

- click on any feature
- scroll the details panel down 
- observe `rvInteractive` displayed at the bottom

![](https://i.imgur.com/K5nQWHZ.png)

**Comment by IsabellaPan** [comment]
Feb 13 2017
Fixed. Verified with build http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-fr.html?keys=JOSM
