### ISSUE TITLE
Add 'data-' translations for custom attributes

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1665]
- [x] add translation in bootstrap to convert `data-rv-*` to `rv-*` custom attributes
- [x] add support for `is="rv-map"` in addition to `class="fgpv"`
- [x] add warning for `class="fgpv"` to be deprecated

This is needed because custom attributes don't validate in any of the current validators (including w3's) so we should do what angular does and allow for data attributes to be used in their place.  These will be only used for static declaration (i.e. anything reading/writing using the DOM API should be reading from the actual `rv-*` attributes).

**Comment by AleksueiR** [comment]
Supported attributes (without prefixes): `config`, `langs`, `service-endpoint`, `restore-bookmark`, `wait`, `keys`, `fullpage-app`.
