### ISSUE TITLE
geosearch result panel doesn't overflow flow in FireFox

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1668]
The geosearch panel doen't overflow when numbers of item excced the height of the container. The flex height is not set properly.

<img width="461" alt="screen shot 2017-02-07 at 10 47 28 am" src="https://cloud.githubusercontent.com/assets/3472990/22698644/19789b70-ed23-11e6-8fe4-9092476d2199.png">

**Comment by AleksueiR** [comment]
I solved this for Firefox, but it turned out this issue happens in IE as well and the fix I found doesn't work :(

**Comment by AleksueiR** [comment]
IE would not respect max-height specified as a percent on a flex child :+1: http://stackoverflow.com/a/35537510

**Comment by bkutty** [comment]
No longer an issue. Accepted as per tests on v1.6
