### ISSUE TITLE
Bookmark after language switch mismatches RCS keys

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1674]
As documented in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1277 , we currently do not capture language in a bookmark.

The recent change in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1657 resulted in a missed edge case.

- Load a page with url RCS keys
- Change the map language only (not the page)
- Generate a bookmark and load the bookmark
- Bookmark contains French RCS layer ids (e.g. `rcs.MyLayer.fr`)
- Since bookmark targets English page, it will activate the English variants of the RCS keys (e.g. with id `rcs.MyLayer.en`)
- Bookmark restore code is using French ids as keys on objects with English ids as keys, results in null dereferences.

Fix is to make bookmark only use RCS keys, not layer ids, when matching config items to bookmark items.

**Comment by bkutty** [comment]
Fixed. as tested on v1.5.1
