### ISSUE TITLE
Back To Cart not loading any layers after language toggle

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1677]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-rc3/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

- Toggle to French from left side menu
-  Click "RETOUR AU PANIER" from left side menu or "backToCart" on top of Visualiser
All layers are gone.
![image](https://cloud.githubusercontent.com/assets/18723160/22741041/d6dcd8c2-eddf-11e6-8c28-54f7eb43b1dc.png)

**Comment by james-rae** [comment]
Majority of problems solved by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1674

Additional problem found:  Barley layer fails when switching to French. Bookmark then attempts to read child information on the failed layer, causing issues.

**Comment by IsabellaPan** [comment]
Feb 22 2017
Verified with build v1.5.1-1
