### ISSUE TITLE
Deleting child layers attempts layer removal

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1679]
When deleting a child layer / sub layer of a Dynamic layer, if user does not press the Undo toast, the code will still go through the logic to attempt to delete the actual layer.

Since it is not a real layer, it the thread exits early on an error in `geoService.removeLayer`.  Nothing is broken, but you do get the error in the console.

Minor cleanup to handle the child case better.

**Comment by AleksueiR** [comment]
Need to check if this still an issue in 2.0.

**Comment by AleksueiR** [comment]
No longer valid under 2.x.
