### ISSUE TITLE
<a href> tag displayed in Details pane for some JOSM points

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1681]
Tested build : http://fgpv.cloudapp.net/demo/v1.5.0-rc3/prod/samples/index-fgp-fr.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley

Related #1661 
For eg, Object ID 2111 Wildlife Contaminants

![image](https://cloud.githubusercontent.com/assets/18539315/22744422/56e72ca6-edeb-11e6-9590-cdcf17af711f.png)

**Comment by AleksueiR** [comment]
Solved by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1680.

**Comment by bkutty** [comment]
Accepted. As tested on http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,ZoomScale,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Barley
