### ISSUE TITLE
Short link control is visible when API key is removed

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1686]
http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html
http://fgpv.cloudapp.net/demo/v1.5.0/dev/samples/index-fgp-en.html

The `prod` build has the google API key removed, which means the URL shortener doesn't work.  The `dev` build should have the key included.

Looking at the two links above, it appears the logic has been swapped.  The `prod` site has the URL shortener control, but it does nothing.  The `dev` site does not show the control.

**Comment by james-rae** [comment]
Appears the Your Location tool is also affected

**Comment by milesap** [comment]
Our API key seems to be blocked by Google "Project blocked; abuse detected."

Prod builds are keeping their google api key while dev build are not so this should be swapped.
