### ISSUE TITLE
Strategy for handling library dependencies during a longer support cycle

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1689]
RAMP2 can have library dependency collisions (jQuery and Angular mostly) and we basically have to declare a "tested" version and differ to the page host to deal with it. As a general rule, newer versions of dependencies should not break the app, but it happens anyway.

Sandboxing comes to mind (it might also solve https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1382). There seem to be four-ish options: iframes, Google Caja, web workers, and web components.

- Google Caja seems no longer under active development;
- web workers lack DOM; 
- web components are [not completely there yet](http://jonrimmer.github.io/are-we-componentized-yet/) and [Web Component polyfill](https://github.com/WebComponents/webcomponentsjs) is required for IE 11 and missing features in other browsers; 
- iframes

What's your poison?

**Comment by alyec** [comment]
I think the general feeling we had after some pod discussions earlier is that web components would be perfect.  I think it's worth testing out the polyfill and seeing what we can do with it.

I also wonder if some of the newer JS build tools can help with this, especially if they provide proper isolation of dependencies with ES6 modules.

**Comment by AleksueiR** [comment]
There is an interesting article from the Edge team one web components: https://blogs.windows.com/msedgedev/2015/07/14/bringing-componentization-to-the-web-an-overview-of-web-components/

It seems a fully isolated import with a separate global object is slated for the next generation of web components (scroll to the bottom of the page). We need the global object isolation to load specific versions of dependencies. There are proposals to implement it, but I can't find what the current state of development is.

The article authors also state `iframe` is the `most successful (and only widely-deployed) form of componentization on the web today`.

**Comment by jolevesq** [comment]
with iframe, will it be possible to link multiple viewer together e.g. if one viewer zoom/pan the other viewers will do the same thing?

**Comment by AleksueiR** [comment]
It's possible for code in iframe to communicate with the host page with [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). It might be a bit more cumbersome, but it should be possible to link viewer instances.

**Comment by AleksueiR** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/960.

Switching to [webpack](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1873) build tool, allowed for sandboxing of all runtime dependencies effectively solving the library collision issue.
