### ISSUE TITLE
Clean up logging messages in prod

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1692]
At least for the prod version we need to clean up noisy logging.  Ideally with a `rv-logging-level` type of attribute, but at the very least removing noisy console activity on the prod build.

**Comment by AleksueiR** [comment]
Console logs made by geoApi code are still present.

**Comment by milesap** [comment]
A potential roadblock here is that geoAPI is bundled with all other required dependencies (I believe this is `lib.js` in `gulp.config.js`). We would need to separate the geoAPI import from the others to let gulp do its thing. We can't strip console logs from everything as we may want to see them, and the current gulp plugin breaks some libraries that use console differently like `console && console.log("foo");`

**Comment by alyec** [comment]
I think this should be a fix on geoApi rather than trying to split out dependencies.

**Comment by milesap** [comment]
Issue moved to [fgpv-vpgf/geoApi #183](https://github.com/fgpv-vpgf/geoApi/issues/183) via [**ZenHub**](https://www.zenhub.com/)
