### ISSUE TITLE
Basemap checkmark pointed to Transportation after applying Back To Cart for blank map

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1697]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

- Select blank map
- Click Back To Cart

![image](https://cloud.githubusercontent.com/assets/18723160/22995859/8459dbca-f39a-11e6-91e9-8044e9186656.png)

**Comment by AleksueiR** [comment]
This needs to be re-examined against 2.0.

**Comment by james-rae** [comment]
WOMM
