### ISSUE TITLE
Datatable column headers overllap in IE

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1698]
Column headers overllap in IE:
![](https://camo.githubusercontent.com/10e886c5feb7dfa02cd71e272e77f5f679b7bcac/68747470733a2f2f692e696d6775722e636f6d2f475369746b6a4d2e706e67)

This might be related to IE special way of calculating width of things when determining column sizes.

Found in v1.7 build.

**Comment by milesap** [comment]
No longer an issue on my machine in IE :+1: Please re-test to see if we can close

**Comment by milesap** [comment]
Also fixed with PR #2151
