### ISSUE TITLE
Basic Support for Esri Dynamic service display (grouped layers)

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#170]
Display grouped layers on the map. 
- [x] Provide basic display support of grouped layers
- [x] Wire grouped layers to the UI TOC in a fashion that shows the hierarchy of the layers

AAFC example: http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_plant_hardiness_zones/MapServer 

Traceability Matrix ID#079

**Comment by dan-bowerman** [comment]
Linked to Dynamic layers PBI.

**Comment by mweech** [comment]
Can load and display grouped layers, however there are no details available yet on the TOC.

**Comment by mweech** [comment]
Reopening issue and capturing that wiring to the TOC is still incomplete.

**Comment by AleksueiR** [comment]
See #303
