### ISSUE TITLE
Identify Error on user added WMS layer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1715]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.1-1/prod/samples/index-fgp-en.html

While testing the fix for #1614 , Identify error as below was noticed in the Details Pane. This error was more consistent after zooming in to the map. Please investigate.

Layer Added: http://maps.geogratis.gc.ca/wms/railway_en

![image](https://cloud.githubusercontent.com/assets/18539315/23220905/69dfe99a-f8f1-11e6-80fb-c062e61efcfc.png)

**Comment by ChrisLatRNCan** [comment]
OGC WMS hell
#1613 and #1284

**Comment by mweech** [comment]
Identify will fail if the railway layer is added and the Subdivisions sub layer is not excluded from the list.  Closing  as a duplicate.
