### ISSUE TITLE
Implement Basemap Switcher

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#173]
- [x] Wire UI to the configuration schema
- [x] Port notification code from RAMP
- [x] Define a UI for warning for refresh (#111)

Traceability Matrix ID#010

**Comment by AleksueiR** [comment]
Relates
#106 
#107 
#111

**Comment by ec-dev** [comment]
back end code completed and in develop, needs UI hookup. 1 point remaining.
