### ISSUE TITLE
Railway Network layer not shown up on exported map for Mercator projections

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1730]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.2-0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

Though this layer is included in the Legend of map export, see below screenshot.
![image](https://cloud.githubusercontent.com/assets/18723160/23475884/efe2b848-fe86-11e6-835e-fceee8cb38c1.png)

**Comment by james-rae** [comment]
WOMM
