### ISSUE TITLE
Populate Datagrid for Group Layers

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#174]
- [x] Add radio buttons to improve accessibility (#195)
- [x] Enable datagrid for Group Layer children

Traceability Matrix ID#016

**Comment by AleksueiR** [comment]
Duplicate #161

**Comment by dan-bowerman** [comment]
Fix this already, @dan-bowerman!

**Comment by mweech** [comment]
Only partial completion of requirement to date.  Reopening.

**Comment by mweech** [comment]
Removed from R2 scope with enhancements to follow in Y3: 
- [ ] Enhance datagrid with the following features (from #155):
        -  individual row searching (text/select)
        -  global table search (with regex)
        -  toggle to show items not in the current extent (with highlighting of row corresponding to visible elements)

**Comment by mweech** [comment]
User added layers related scope split to #449.

**Comment by AleksueiR** [comment]
No update.

**Comment by AleksueiR** [comment]
No update.

**Comment by AleksueiR** [comment]
Partially completed; blocked by #522.

**Comment by AleksueiR** [comment]
@mweech Should this be marked as completed? It is, technically.

**Comment by mweech** [comment]
@AleksueiR: Please remove the symbology from the group layer datagrid for now to allow for the grid to be available, until #522 is resolved.  I will open a seperate issue to re-implement once #522 is accomplished.
