### ISSUE TITLE
"Visible" option in GeoLocation Search is Confusing

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1745]
Tested build:http://fgpv.cloudapp.net/demo/v1.6.0-0/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

This functionality is confusing and I am not sure if this is working as intended. 

![image](https://cloud.githubusercontent.com/assets/18539315/23672484/e1881666-033c-11e7-90c9-c6f4fb996ea7.png)

**Comment by jolevesq** [comment]
It is use to only show results that are inside the extent of the map. Everything outside the extent is filter out. It is working as expected but we can the word visible to something more meaningful like 'Inside extent' or 'Visible on map'

@AleksueiR do you have a preference?

**Comment by AleksueiR** [comment]
"Visible on map" sounds better as some might not be familiar with what "extent" is.
