### ISSUE TITLE
Export dialog window closed unexpectedly upon selecting Custom size from the drop down menu

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1771]
Tested build: http://fgpv.cloudapp.net/demo/v1.6.0-4/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

- Load above URL and export the map
- Select Custom size from the drop down menu in the export dialog window

Export dialog window was closed and instead Focus Manager window pop-up as below screenshot.
![image](https://cloud.githubusercontent.com/assets/18723160/23964660/967bd25c-098b-11e7-817f-28e29e852406.png)

**Comment by milesap** [comment]
Confirmed - seems I forgot mouse users :1st_place_medal:

**Comment by IsabellaPan** [comment]
Selecting other options (Small, or Medium) will also close the export dialog window.
