### ISSUE TITLE
Focus Manager pop up when Province/Type fields of GeoLocation search is selected

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1772]
Tested build :http://fgpv.cloudapp.net/demo/v1.6.0-4/prod/samples/index-fgp-en.htm

Please investigate the below error when Province and Type fields are used in GeoLocation search. Error goes by pressing "Enter"

![image](https://cloud.githubusercontent.com/assets/18539315/23968031/a5f296ec-0997-11e7-8a28-3b0208e11058.png)

**Comment by milesap** [comment]
Errors appear to be caused by md-select not having proper focus wrappers applied (they are rendered outside the viewer)

**Comment by milesap** [comment]
Tested on http://fgpv.cloudapp.net/demo/v1.6.0/prod/samples/index-fgp-en.html with chrome, cannot reproduce this error. Please update this issue with additional details on bug reproduction.

**Comment by bkutty** [comment]
No longer an issue. Accepted
