### ISSUE TITLE
Tile Layer not loading in Firefox and IE

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1775]
Tested Build : http://fgpv.cloudapp.net/demo/v1.6.0-rc1/prod/samples/index-fgp-en.html

Tile layer used : http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer/

While Testing the fix for #1744 , it was found that the above mentioned tile layer added through "Add Layer" appears always with visibility "off" in Firefox and IE11.  Issue could not be seen in Chrome.
Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/24008705/c215fc04-0a48-11e7-9703-5346491bbec1.png)

**Comment by james-rae** [comment]
Also of note, errors spitting out from [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.6.0-rc1/src/app/ui/toc/entry-symbology.directive.js#L149) , perhaps something in FF & IE is not creating the `svg` elements; perhaps there are too many due to the large size of this layer?

**Comment by milesap** [comment]
![ff-tile](https://cloud.githubusercontent.com/assets/10187181/24009259/cfb4e8d2-0a4a-11e7-9fb0-e06459c26cdc.png)

womm in FF. I see the tile layer has an incorrect projection icon, so it should have visibility off. Haven't checked in IE yet. Works when I add tile layer on a correct projection.

**Comment by milesap** [comment]
Tested in IE, seems to be working. @bkutty please provide additional information as to the expected outcome and actual result. Also please confirm if this issue occurs when adding the tile layer to a mercator projection.

**Comment by bkutty** [comment]
Realised this layer works only with Mercator projection. My tests were on Lambert. No longer an issue

**Comment by milesap** [comment]
@bkutty ok thanks for confirming, closing as not an issue
