### ISSUE TITLE
No indication on the layer panel if a data table fails to load

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1778]
Tested build : http://fgpv.cloudapp.net/demo/v1.6.0-rc1/prod/samples/index-fgp-en.html?

It seems due to  fix #1433, at present there is no way to indicate if a data table fails to load.  Could this be looked into.

![image](https://cloud.githubusercontent.com/assets/18539315/24055094/2981fdb2-0b15-11e7-8862-a349a10c30e8.png)

**Comment by milesap** [comment]
@bkutty I don't believe this was ever a feature. Please update issue with a working example (using an older viewer version). Also let me know how #1433 is related to this. 

If this was never implemented you can open a feature request.

**Comment by milesap** [comment]
Possible future feature request, not an issue - closing
