### ISSUE TITLE
North arrow should not rotate when projection is web mercator

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1779]
For web mercator projection north arrow should never rotate because in this projection, north is always straight up.

**Comment by milesap** [comment]
Not sure what the status of this issue is, please close if abandoned or update release draft if completed

**Comment by milesap** [comment]
Confirmed north arrow on export still rotates for mercator projections, issue still active

**Comment by milesap** [comment]
@jolevesq advised fix is on geoApi v1.1.4-1. Will release v1.1.5 tomorrow and merge to develop
