### ISSUE TITLE
Multiple projection support for basemaps

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#178]
- [x] Port RAMP's current projection handling (EPSG 3857, 3978, 3979 & Lat/long)

Dynamic support of any EPSG coordinate system captured in a seperate PBI (#281)

Traceability Matrix ID#053

**Comment by dan-bowerman** [comment]
Link to basemap switching.

**Comment by dan-bowerman** [comment]
Relates to #268

**Comment by mweech** [comment]
Refactoring being completed following comments from PR.

**Comment by mweech** [comment]
@ec-dev to fix failing unit test.

**Comment by ec-dev** [comment]
Task completed, code merged PR #393
