### ISSUE TITLE
User added CESI layer - Datagrid not loading for all sub-layers

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1781]
Tested build: http://fgpv.cloudapp.net/demo/v1.6.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

User added CESI layer from above test data by selecting Nature, Water or Air Emissions sub-layers, data tables were not loaded for all sub-layers.
![image](https://cloud.githubusercontent.com/assets/18723160/24107567/7bd7762a-0d61-11e7-9a82-ce0b888ceaea.png)

**Comment by milesap** [comment]
Removing from 1.6.1 target, please update when target release is known

**Comment by mweech** [comment]
services are responding slowly causing longer load times.
