### ISSUE TITLE
Create Structured Legend Samples

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1786]
- [x] Sample with visibility sets
- [x] Sample with controlled layers
- [x] Sample with direct linking of dynamic child
- [x] Sample with one group linking to multiple layers in child entries
- [x] Nested visibility sets (see config-mobile-3.json, may be able to steal from there)
- [x] Dynamic layer with children split across multiple top level groups
  - [x] Variant where another layer controls several of the children in the dynamic group
- [x] Layer with single entry collapsed set (include the layer multiple times where some cases the collapse triggers and others where it fails)
- [ ] ~Hovertips disabled~
- [x] Multiple layers with opacity, visibility disabled and locked (use multiple combinations)

**Requested samples from QA**
- [x] Layer with only Information section
- [x] Tile layer which is only valid in one of the basemap projections
- [x] Layer with symbology overridden by config file specified image file
- [x] Hidden layer sample
- [x] Visibility Set with children
- [x] Layers with only symbology
- [x] Viewer with Map re-order disabled for auto legends
- [x] Viewer with “About map” text changed
- [x] Layer with Bounding Box disabled
- [x] Layer with Query disabled
- [x] Layer with Snapshot disabled
- [x] Layer with Metadata disabled
- [x] Layer with boundary zoom disabled
- [x] Layer with reload disabled
- [x] Layer with remove disabled
- [x] Layer with settings disabled
- [x] Layer with data table disabled
- [x] Layer with customized title of a data table
- [x] Super group with tile layer, dynamic layer- Controls visibility/settings and disable visibility
- [x] Zoom scale dependent layer as a part of visibility group and standalone
- [x] Set table open by default
- [x] Set table name
- [x] Hide/Display field
- [x] Set sorting field by default
- [x] Enabled/disabled global search for a table
- [x] Set width for a column
- [x] Order Fields 
- [x] Layer with layer import disabled
- [x] Map showing when exporting
- [x] `ABOUT MAP` with custom content
- [x] Sample with hidden layer
- [x] Map with custom title
- [x] Viewer with custom name and logo

**Comment by milesap** [comment]
@barryytm has this under control :+1:

**Comment by bkutty** [comment]
Please modify Sample#26 as "Remove" is not an option for Structured Legends.
Please modify Sample#33 to create a layer with visibility group. Current sample has a layer with group

**Comment by bkutty** [comment]
Please modify the config file to display the map while Export

**Comment by barryytm** [comment]
- Sample#26: It is by design that `remove` is not an option when it is disabled
- Samples#33: It was modified in #2115
- Maps should be displayed on export after #2115

**Comment by barryytm** [comment]
`remove` in the "more options icon" is currently not working.  However it is going to be fixed soon.  Please refer to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2126 for the newest updates regarding to the issue.

**Comment by bkutty** [comment]
Request for 2 more samples
-Sample with  hidden layer (hidden in the legend panel, map points appear in the map)
-Map with custom title

**Comment by bkutty** [comment]
Please create a sample with a custom logo and name for the viewer (per #2109)

**Comment by barryytm** [comment]
Finished the requests mentioned above in #2142

**Comment by bkutty** [comment]
Please create a test sample to test this reqt

![image](https://user-images.githubusercontent.com/18539315/28464579-dd4a34e0-6df3-11e7-8129-c0d515ec540e.png)
