### ISSUE TITLE
Add a section to mapnav for user to navigate between previous and next extent

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1791]
Add to map nav section a tool for use to navigate between previous and next extent

**Comment by mweech** [comment]
This one was left out of the original UI design on purpose if I understand correctly.  Need to assess how necessary this is from a business perspective.  Although we are replacing existing viewers we need to be careful not to just try to replace functionality 1:1.

**Comment by jolevesq** [comment]
I know this function is use by internal people in NRCan who work with GCViz viewer. They found this useful when they need to move back and forth on the same extents for their work. For external user I don't know how much this tool is used.

**Comment by mweech** [comment]
Transfered to plugins repo.
