### ISSUE TITLE
Add coordinates info button to sidenav

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1792]
Add a button in sidenav that wait for user click then show information about the coordinates to give a result like this

<img width="404" alt="screen shot 2017-03-20 at 3 23 21 pm" src="https://cloud.githubusercontent.com/assets/3472990/24117637/62294b48-0d81-11e7-9c5d-fa574a6c7fcc.png">

Check if it need to be in the core or as external plugin

**Comment by milesap** [comment]
Sounds like a plugin is the way to go here, but I'll review it in more detail first.
