### ISSUE TITLE
Add annotation tools

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1794]
Add tools to:
- draw line, polygon, free line
- draw text
- export and import annotations and measure
- select color

**Comment by yblain** [comment]
Now that we have a map being used by a good group of people, some of the feedback is indicating that a measure tool would be very useful. 

I pasted the email I received:

> I agree!  Most of the discussion at DEOC this morning were about “how far is it from A to B?” between fires and critical infrastructure.  Let’s get this use case in!
> 
> Thanks,
> Patricia
> 
> From: Morton, Peter (NRCan/RNCan) 
> Sent: July 20, 2017 15:27
> To: Blain, Yannick (NRCan/RNCan) <yannick.blain@canada.ca>
> Cc: Pollock, Patricia (NRCan/RNCan) <patricia.pollock@canada.ca>
> Subject: RAMP V2 Suggestion
> 
> Hi Yannick,
> 
> What would be very useful for the map is a tool to measure distance?
> 
> The dynamic scale now used on the viewer, doesn’t provide the capability to at least estimate distance.
> 
> Just a suggestion.
> 
> Peter
>

**Comment by yblain** [comment]
Johann to add more analysis to this issue

**Comment by yblain** [comment]
Johann to add info on how it's been done in GCViz

**Comment by dan-bowerman** [comment]
This is now handled through plugins.
