### ISSUE TITLE
Details panel assumes key-value pairs are plain text

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1798]
Identify results and datatagrid details assume key-value content is plain text when rendering. In some cases there might be embedded links in that text, so we run the autolinker on that.

@jolevesq brings up a question from one of the users:
> They use to be able to see formated text, in detail panel, when it contain html tag. This was ok in previous version of RAMP2 but not anymore. Do we change something about this?
> 
> ![](https://files.gitter.im/fgpv-vpgf/n3QK/Screen-Shot-2017-03-21-at-9.27.21-AM.png)

There seem to be HTML snippets in feature details which is displayed as raw html. Do we want to display arbitrary HTML received from the service as part of the details view?

**Comment by mweech** [comment]
I think we should make it optional. Allow someone to suppress HTML (render as text) or allow it. In FGP's case they have a controlled set of services so its ok to trust them.  User Added Layers are a user responsibility and FGP has to be OK with that possibility.

Potential requirements to come out of this..
1. Add viewer wide true/false setting to allow HTML text to be rendered (may want to consider some basic sanitation of the HTML text)
2. Add setting to service settings to override global setting and enable/disable on a per server basis (perhaps add a control to the Feature details window?)
3. Thematic maps allow per service enable/disable of HTML rendering

**Comment by milesap** [comment]
The HTML not rendering is `$sce`, so that should be trivial to tell it to allow HTML on select layers. Perhaps HTML permission should be set in the config?

**Comment by milesap** [comment]
@jolevesq Please provide the layer url that was used in the above screenshot

**Comment by mweech** [comment]
I am pretty sure that layer is only available from within NRCAN.

**Comment by AleksueiR** [comment]
You can use `rvSvg` to include anything on the page, without passing it though HTML sanitization.

**Comment by milesap** [comment]
Testing layer is http://s-she-gisdev1.nrn.nrcan.gc.ca:6080/arcgis/rest/services/Test_Math/elevation_fr/MapServer/0

**Comment by milesap** [comment]
Test layer is not accessible from my location, assigning to @jolevesq for further investigation

**Comment by jolevesq** [comment]
@AleksueiR we can use this https://docs.angularjs.org/api/ng/directive/ngBindHtml?

**Comment by jolevesq** [comment]
ng-bind-html is already used. Will check why it doesn't work.

**Comment by AleksueiR** [comment]
Didn't we say the config will specify what to expect from the service - html or plain text?

**Comment by AleksueiR** [comment]
Ah, yes, it won't work for RCS layers.

**Comment by mweech** [comment]
closed by #1815
