### ISSUE TITLE
Multiple instance support

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#180]
Allow the viewer to be present multiple times on a single WET page.  Handle potential conflicts in library loading and toggling of interaction with webpage container to allow for a mix of static windows and interactive (i.e. query string based).

**Comment by AleksueiR** [comment]
@mweech I think this one should be closed as well.

**Comment by mweech** [comment]
Multiple instance support could be expanded to include linking multiple maps together so that they keep their extents in synch, etc.

**Comment by AleksueiR** [comment]
I would say this is done.

**Comment by milesap** [comment]
Moving to done pile

**Comment by AleksueiR** [comment]
Ask Mike first, he wanted to keep it open for some reason.

**Comment by mweech** [comment]
I do not recall exactly why I wanted to keep it open, but I believe it was linked to capabilities that is more appropriate for External API work (i.e. linked extents, etc.)
