### ISSUE TITLE
More geosearch enhancements

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1805]
Some geosearch suggestions from previous PRs; some of them might not be relevant anymore.

- If I set a filter with the drop down there is no way to remove it. You can click the clear filter button but it will remove all the filters. May be we should have the first item in the list an item to reset the filter.

- When I close geosearch and get back to it later, my previous search is cleared. Would it be good to keep it as long as the user doesn't clear it himself? The filters works that way. For small screen when you select an element, you can't see it is the right thing until you close the panel and you lose your search.

- Would be great to see the overflow when hovering or tabbing to the element (like in our filter panel). Or when selected, there is a popup like the hovering to show the complete text selection.

- Focus is not trap inside geosearch when tabbing. At the end it goes to zoom control but it should go the search text.

- In FF and Safari, when I select a filter value with the keyboard FF completely lost focus and Safari bring it url bar then goes back to the filter.

**Comment by jolevesq** [comment]
Focus is now trap inside but visible checkbox can't be tab. At the end of items it goes to filter. To go back to text we need to close the panel with esc and open geosearch again.

Safari and FF, if you close panel (esc key or select item) focus is lost.
