### ISSUE TITLE
North arrow overlap item when panning up north

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1814]
This is 2 sample of wierd behaviour when we oan up north. The arrow overlap the toc and the datatable

![screen shot 2017-03-29 at 3 28 35 pm](https://cloud.githubusercontent.com/assets/3472990/24472662/85b1a6cc-1494-11e7-97ab-d40cdfbdc8cc.png)
![screen shot 2017-03-29 at 3 29 52 pm](https://cloud.githubusercontent.com/assets/3472990/24472685/99993358-1494-11e7-9c36-deebfeb2ec1b.png)

**Comment by milesap** [comment]
Maybe just remove arrow z-index for now. It will be hidden by navbar if it moves there but I'm ok with that

**Comment by milesap** [comment]
I might as well take this, a one liner :+1:
