### ISSUE TITLE
Load dependencies over host page URL's scheme

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1824]
Request from user:
> ... It would also be awesome if you guys could update the jquery cdn you are using in your source code to use https instead of http. The live site will use https so if this is not changed the map will break. We also found the same issue in the core.js with this link https://js.arcgis.com/3.14/

**Comment by milesap** [comment]
Unless IE throws a fit, all urls (script, css) should lead with `//` as in `//ajax.googleapis.com/ajax/libs/angularjs/${this.ourVersion}/angular.min.js` so that the current page URL's scheme is followed, either http or https

**Comment by alyec** [comment]
`//` does work in IE (I've used it in other projects, pretty sure it's good from IE9 unless there are regressions)
