### ISSUE TITLE
Correct datatable arrow key navigation so focus is set on cell item

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1825]
Currently, when a cell item is clicked or moved to via arrow key a `td` element is given the class `rv-cell-focus` so it appears focused. Actual focus is on the document body. Focus should actually be set on the cell, and `rv-cell-focus` class can be changed in the css file to `td:focus` (or similar). 

Currently this is causing issues with FM (issue #1816) and can cause issues with screen readers.

@jolevesq I'm assigning you as you know the most about how this works and did the original implementation of arrow movement. This will solve #1816 as well :+1:

**Comment by jolevesq** [comment]
In v1.7 and v1.6.1 every there is hidden tab everywhere. You need to tab twice to make tab go forward or backward. It was not the case in v1.5.3.
