### ISSUE TITLE
Overview map is not rendered when several viewer instances are present

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1829]
Occurs on `index-two.html`, currently in `geo2` refactor branch. The left map doesn't have its overview map shown; the right one does. Both viewer instances use the same config.

![2017-03-31 14_07_27-title](https://cloud.githubusercontent.com/assets/2285779/24563181/875da9f2-161b-11e7-920a-d680884da1da.png)

**Comment by milesap** [comment]
Overview maps are working on `index-two.html` when an individual viewer has a computed width > 840px (large viewport). Please update issue with additional details if the problem persists (browsers affected, sample page used, expected behaviour).

**Comment by AleksueiR** [comment]
This bug seems to have fixed itself. Can't reproduce.

Closing.
