### ISSUE TITLE
Interface for viewing per-layer datagrid

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#183]

**Comment by dan-bowerman** [comment]
Fake data for now, full functionality later when schema is ready.

**Comment by dan-bowerman** [comment]
Done, except for disabling grid when there is no data to show.

**Comment by spencerwahl** [comment]
@AleksueiR is taking over as he's already midway through wiring up the layers.

**Comment by dan-bowerman** [comment]
Blocked by #303

**Comment by AleksueiR** [comment]
Layer item with no associated data cannot be clicked anymore.
