### ISSUE TITLE
Scale bar is present even when we set false in config file

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1830]
Even when scale bar is false inside configuration file the scale bar is present.

<img width="385" alt="screen shot 2017-03-31 at 3 21 00 pm" src="https://cloud.githubusercontent.com/assets/3472990/24566006/b09b97d4-1625-11e7-838f-beb0eddb15d1.png">

In geoApi ```mapManager.js``` line 71 setting.scaleBar is use to check if scale bar need to be there. it should be setting.scaleBar.enabled

**Comment by milesap** [comment]
Issue moved to [fgpv-vpgf/geoApi #189](https://github.com/fgpv-vpgf/geoApi/issues/189) via [**ZenHub**](https://www.zenhub.com/)
