### ISSUE TITLE
Investigate replacing babel with typescript

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1832]
Since typescript has EC6 support it should be possible with minimal changes. Webpack is also optional but will greatly simplify the build process.

**Comment by milesap** [comment]
`webpack` has been integrated. Considered adding typescript support to webpack but will hold off for now to avoid fragmenting the code base. Easy to add as a loader in webpack down the road.

Added documentation task to issue #1900 for webpack

**Comment by mweech** [comment]
@milesap @alyec @AleksueiR is this obsolete? still relevant?

**Comment by AleksueiR** [comment]
Kinda, @milesap is using Typescript for the external API.

**Comment by milesap** [comment]
My understanding at this time is that both are needed. Doing a quick search online indicates TS can replace babel, but for our TS webpack loader babel is needed for IE to function.

I'll check when I have some free time to see if its simply a TS config issue while building out the api, if it is I'll rip out babel and run everything through the ts loader.

**Comment by milesap** [comment]
I'll also have to consider the impacts to `babel-polyfill` which handles IE atm and if it's sympatico with TS

**Comment by milesap** [comment]
Converting to strict TS compiling (incl. js) without Babel causes compile time errors, and is also known to impact IE. Closing for now, I don't see this changing anytime soon (and this is a minor improvement to the build process speed, no impact on viewer)
