### ISSUE TITLE
Performance issue in IE and Firefox

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1834]
Tested build :https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/v1.6.1-rc2

This build was very slow to respond in IE and Firefox.  Performance issue was noticed for features like "back to Cart", "Export" and "data grid". Please investigate the cause

**Comment by milesap** [comment]
Did some basic :eyes: testing (no profiling) and it seems the same as v1.6.0. Looking at the v1.6.1 commits, nothing stands out as a resource hog for these two browsers. 

We have a few performance issues already open, #959 should cover this in more detail.
