### ISSUE TITLE
fix(bug): missing menu icon

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1839]
Some menu icons (visibility all and add layers) are missing since last rebase

<img width="659" alt="screen shot 2017-04-06 at 8 24 05 am" src="https://cloud.githubusercontent.com/assets/3472990/24757030/f0b931fc-1aab-11e7-9f09-06029580e99e.png">

**Comment by AleksueiR** [comment]
Took a quick look and it seems something is stripping the icons after their templates have been compiled. Very random.

**Comment by milesap** [comment]
Ok'd by @mweech to cancel v1.6.2 and move straight to v1.7.0
