### ISSUE TITLE
fix(filter): keytable extension is too slow for huge table

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1842]
If we try to navigate with the arrow in huge table like Plant Hardiness Zones of Canada 2000 (over 100 000 features). The key-focus event takes fews seconds to fire. It slows down everything. Wiil need to see if we can fix keytable or disable keytable for huge table.

Even with this layer http://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer/ (25 000 features) it is too slow.

**Comment by AleksueiR** [comment]
Have you checked Datatables forums? People must have encountered something like this before and maybe a solution is posted there somewhere.

**Comment by jolevesq** [comment]
I checked and there is not so much about this in the forum. Haven't found a sample where they use a lot of data.

**Comment by jolevesq** [comment]
Problem came from this function

```
	/**
	 * Find the unique elements in a source array.
	 *
	 * @param  {array} src Source array
	 * @return {array} Array of unique items
	 * @ignore
	 */
	var _unique = function ( src )
	{
		// A faster unique method is to use object keys to identify used values,
		// but this doesn't work with arrays or objects, which we must also
		// consider. See jsperf.com/compare-array-unique-versions/4 for more
		// information.
		var
			out = [],
			val,
			i, ien=src.length,
			j, k=0;
	
		again: for ( i=0 ; i<ien ; i++ ) {
			val = src[i];
	
			for ( j=0 ; j<k ; j++ ) {
				if ( out[j] === val ) {
					continue again;
				}
			}
	
			out.push( val );
			k++;
		}
	
		return out;
	};
```

It took's 6 seconds to select the proper row/cell in a table with 100 000 rows

**Comment by jolevesq** [comment]
Posted something on the forum about that and got an answer from the Datatable developer. We have to move to version 1.10.15. We are using 1.10.11 right now.

**Comment by milesap** [comment]
Using version 1.10.15 :+1:
