### ISSUE TITLE
Help - Provide Generic help in English and French

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#185]
- [x] Implement UI container for help text (#134)
- [x] Define English help text
- [x] Obtain translations of text to French
- [x] Integrate help text into UI container

Traceability Matrix ID#038

**Comment by AleksueiR** [comment]
Relates
#134 
~~#131~~

**Comment by AleksueiR** [comment]
I feel we should postpone creating help content for after the panic deadline. 

Between now and then there will probably be many changes (perhaps small) to the interface and (potentially) to how things work. Writing help section right now means rewriting it in the coming weeks (maybe several times).

Unless it's critical to have the help ready for the beta app, it might be beneficial to use that time for development instead. (Maybe we could include some rudimentary help - copy-pasted from RAMP/GcViz).

**Comment by jolevesq** [comment]
I think we should include some rudimentary help for March. Like you say, copy-pasted with minor modifications can be good. For the contextual help it can wait.

**Comment by dan-bowerman** [comment]
Need rudimentary Help text in time for March 31st.

**Comment by dan-bowerman** [comment]
Assigned to me in order to cull what we've got in RAMP for the basic March 31st help support.

**Comment by dan-bowerman** [comment]
Also leaving a note here: Usability testing from R1 suggested that a Searchable help would be immensely beneficial (use-case, how to find the Legend for a dataset, when no help subheader existed for this)

**Comment by dan-bowerman** [comment]
Text from RAMP, modified a bit but will require some further review and updates based on new/modified functionality in the R2 Viewer.

**Navigation Controls** 
Navigation controls are used for changing the viewing extent of the map; the datagrid updates accordingly to what's viewable in the current extent.
Usage:
- Click Pan North/South/East/West to move the map in that particular direction.
- Click Canada View to view map at its full extent.
- Click Zoom In/Out to change the map extent.
- Click and drag the Zoom Slider to zoom in/out.


**Basemaps**
The Basemap selector is used to modify the underlying basemap to provide a variety of geographical contexts.
Usage: From the dropdown, select the basemap of your choice and the map display will update.


**Get Link**
Get Link is used to generate a shareable URL of the current map state with selected datasets.
Usage: 
- Short link - Select this link to use Google's URL shortening service to generate a concise and easily shareable link to the current state of the map viewer.
- Email - Select this link to open a new email in your default mail client, with the URL contained in the body for convenient sharing.


**Full Screen**
Full Screen is used to collapse the departmental headers and footers to provide larger screen space for mapping.
Usage: Click the Full Screen button in the toolbar to hide departmental header and footer information. Select the Full Screen button again to restore to default view.


**Datasets**
The Datasets tab lists the layers available to display in the map. Feature layers also display in the data grid. The Datasets tab also serves as a map legend.
There are three types of layers that can reside in the Dataset tab.
Feature layers represent data that can be interacted with on the map, and viewed in the data grid.
Static layers provide additional geographical context against the basemap. They are not interactive and do not show in the data grid.
WMS layers provide an overlay of data from a Web Map Service. They can support a click interaction on the map, and do not show in the data grid.


**Layer Visibility**
Select the "eye" icon next to a dataset name to toggle the layer on or off.


**WMS Queries Toggle**
When a user clicks on the map (and not on a feature), the results for any queryable WMS layer will be displayed for the location clicked. This behaviour may not be desired for certain layers. Clicking the WMS Query Enable/Disable icons on the right side of the layer selector will toggle this functionality for an individual layer. The global toggle at the top of the layer selector will enable or disable the function for all WMS layers. WMS layers that are not queryable will not have a toggle icon.


**Layer Legends**
Each layer has some symbology associated with it. For simple feature layers a single icon will be present next to the layer name. For complex feature layers (i.e. those with multiple symbols used per layer) the icon will show as a stack and maybe toggled on and off. When toggled on a section will expand beneath the layer name and show the full symbology for the layer. WMS layers may optionally have a graphical legend defined, if one is present it will be displayed in the same drop down manner.


**Handling Layer Errors**
If a layer fails to load correctly it will be identified by an error notice. Instead of the standard layer actions you can select to either reload the layer (this is particularly helpful if there is a temporary network connectivity issue) or remove the layer. If a layer is removed it will be taken out of the layer selector completely and if it is added back via "Add Dataset" it will lose any previous customizations.


**Layer Reordering**
Click and drag the 6 dots to the left of the dataset up or down to re-order the layers on the map interface.


**Layer Group Boundaries**
While all layers can be re-ordered, WMS layers and Feature / Static layers may not be mixed together. When reordering layers, layers which cannot be mixed will be greyed out. Although layers can be reordered within their groups the grouping is static with feature and static layers always displaying over the WMS layer group.


**Layer Metadata**
Select the "Metadata" link to display relevant metadata for that source in a collapsible Info Panel.


**Layer Settings**
Select the "Settings" link to access additional options for the layer.
The layer's opacity can be adjusted using the slider control.
If the layer has a bounding box, its visibility can be toggled using the checkbox.
If the layer is a feature layer, and is in on-demand mode, the option to Load All Features is available. On-demand mode means the layer will be downloaded in parts as needed. Clicking Load All Features will cause all layer data to be loaded in the browser at once, providing snappier response times once the download completes. This is called snapshot mode. Attempting this with very large datasets may cause the site to stall or the layer to crash. A layer in snapshot mode will have the Load All Features link disabled and a checkmark beside the link.


**Zoom Scale Dependent Layers**
Some layers may only be visible at certain zoom levels. If a layer is not visible at a given zoom level the layer selector will display a notice and have an action available to zoom to the closest zoom level at which the layer will be visible (this may involve either zooming in or zooming out).


**User Added Datasets**
Additional datasets can be added to the map viewer. Supported formats are: ESRI Feature Layer, WMS, GeoJSON, Shapefile, and CSV File. The '+' button at the top-left of the Layer Selector will launch the Add Dataset wizard.
Usage: 
Select the type of data source you would like to add: 'Service' to add a web-based map service; 'File' to upload a GeoJSON, CSV, or Shapefile.
Specifying the Dataset Location - Enter the location of the service URL or dataset file in the location box. If the dataset is a file on your file system, you must click the 'File' button and browse to the location.
- A web based URL can be typed or pasted into the box.
- The Viewer will predict the dataset type, if it is incorrect, click the button that specifies the correct type.
- Click the 'Connect' or 'Load' button to initiate the loading of the dataset.
Specifying the Specifics of the Dataset - Depending on the type of dataset being loaded, various parameters can be set in this phase.
- A Feature Service allows the choice of a Primary Attribute, which determines the attribute used to identify a feature in the data grid and map tips. All other information is derived from the service's metadata.
- A WMS Service allows the choice of the Layer Name, which determines the layer in the WMS to be used as the source for the dataset. All other information is derived from the service's metadata.
- File based datasets allow the choice of the following: a Dataset Name, which will be displayed in the Layer Selector; a Primary Attribute, which acts the same as in the Feature Service; a Symbol Colour, which determines the colour of the points / lines / polygons on the map. CSV files also allow the specification of the columns that contain the Latitude and Longitude values, used to derive the point location on the map.
Clicking the 'Add Dataset' button will insert the layer into the map.


**Summary Grid**
The Summary Grid lists basic information for all the features that is visible in the current map extent.
Usage: 
- Sorting - Select the Sort link at the top of the data grid to sort by field name, descending. Select the Sort link again to switch the sort to ascending mode.
- Details - Select the Details link next to each data row to display its information in an Info Panel. This function replicates clicking directly on a map feature.
- Zoom To - Every row on the data grid has an option to quickly zoom the map view to that data point. If the "Zoom To" link is clicked, the map and the data grid will dynamically zoom to that specific point.
- Zoom Back - After the "Zoom To" link is clicked, the link will be replaced by a "Zoom Back" link. Clicking on the "Zoom Back" link will bring the user back to the extent of the map before the "Zoom To" link was clicked.
- Pagination - Use the far left and right arrows to jump to the first or last page, respectively, of the information in the data grid. Use the inner left and right buttons to move back or forward one page at a time. Selecting the Page link will permit you to quickly jump to any page in the data grid listing. There is also a record count next to the pagination buttons, which indicates the number of features currently in the map extent versus the total number of features in the map.


**Extended Grid**
The Extended Grid lists detailed information about all the features that in the current map extent.
Usage: 
- Select the "Full Data" button at the top right corner of the Summary Grid to show the Extended Grid.
- Select the "Data Summary" button at the top right corner of the Extended Grid to go back to the Summary Grid view.
- Sorting - For any column, selecting the upward arrow will sort the extended grid in ascending order by that column, selecting the downward arrow will sort the grid in descending order by that column.
- Details - Select the Details link next to each data row to display its information in an Info Panel.
- Pagination - Use the far left and right arrows to jump to the first or last page, respectively, of the information in the data grid. Use the inner left and right buttons to move back or forward one page at a time. Selecting the Page link will permit you to quickly jump to any page in the data grid listing. There is also a record count next to the pagination buttons, which indicates the number of features currently in the map extent versus the total number of features in the map.


**Info Panel**
The Info Panel displays data associated with a selected feature.
Usage:
Select a feature on the map interface, or select the Details link in the Data Grid. The Info Panel will display information related to the selected feature. Clicking away from the feature or clicking the arrow in the top left corner of the panel will hide the display.


**Map Export**
Map Export is used to convert the contents of the map into an image that can be downloaded by the user.
Usage:
Click the Map Export button in the toolbar to initiate the image generation. The Map Export window will open. A "Loading" message will display, and the image preview will appear once it is generated. Click the Download Image button to save the image. Click the X to close the Map Export window.
Limitations - Currently Map Export will only capture layers that are hosted on a public internet service. Layers hosted privately (e.g. on an intranet) or added from file-based sources will not appear in the resultant image file. Images are currently only available in PNG format.


**Accessibility**
This page is WCAG 2.0 AA compliant.
Keyboard Accessibility - Keyboard functionality is provided as an alternative for users who are unable to use a mouse. Use the Tab key to navigate forward to links and controls on the page. Press Shift+Tab to go back one step. Use the Enter or Spacebar keys to activate links and controls.
Navigation Controls - Zoom Slider: With the Zoom Slider highlighted, use the Up arrow key to zoom in and the Down arrow key to zoom out.
Datasets/Data Tabs - With either the Datasets or Data tab highlighted, use the Left and Right arrow keys to switch between them.
Datasets Tab - Within the Datasets tab, use the Up and Down arrow keys to navigate to different layers. With the layer handle (6 dots icon) highlighted, use Enter or Spacebar to grab the layer. Grabbed layers are indicated with a dark blue background. With the layer grabbed, use the Up or Down arrow keys to re-order the layers on the map interface. Press Enter or Spacebar again to release the layer.


**Advanced Toolbar**
The advanced toolbar provides utilities that can break accessibility, usually due to their dependence on a mouse-driven input.
Usage:
- Opening the Toolbar - Select the Tools button on the main toolbar to open the advanced toolbar. Selecting the button a second time will close the advanced toolbar and de-activate any active tools.
- Tool Activation - Any tool can be activated by clicking the appropriate button on the advanced toolbar. Clicking a second time will de-activate the tool, as will closing the advanced toolbar, or selecting a new tool.
- Population Tool - Select the Population button to activate the population tool. Draw a polygon on the map and release the mouse. The population of people inside the polygon will be displayed in the results window. The Clear button will erase an existing result from the map.
- Buffer Tool - Select the Buffer button to activate the buffer tool. Enter a desired buffer size in kilometers in the tool input. Draw a polygon on the map and release the mouse. A buffer of the desired size will be applied to the polygon and displayed.
- Area Tool - Select the Area button to activate the tool. Draw a polygon on the map and release the mouse. The area and the circumference of the polygon will be displayed in the results window.
- Distance Tool - Select the Distance button to activate the tool. Draw a line on the map and release the mouse. The distance of the line will be displayed in the results window.


**Load Times / Unanticipated Behaviour**
Load times may vary based on network location and bandwidth availability, and unanticipated behaviour may occur if any map interactions occur before data is fully loaded. Please allow the webpage to load completely before triggering any map functions.
Note: If the "Loading..." text appears in the lower right corner of map or the data grid displays a loading message, please allow the loading indicator to disappear before triggering any function on the map.

**Comment by dan-bowerman** [comment]
**Contrôles de navigation**
Les contrôles de navigation servent à modifier la taille de l’affichage de la carte; la grille de données sera actualisée et ajustée selon le contenu visible dans l’affichage en cours.
Utilisation:
[fr] Click and drag to move the map in a particular direction.
Cliquez sur Voir Canada pour afficher la carte en entier.
Cliquez sur « Zoom avant » ou sur « Zoom arrière » pour modifier la taille de l’affichage de la carte.


**Fonds de carte**
Utilisez le sélecteur de fond de carte pour remplacer le fond de carte et afficher divers contextes géographiques.
Utilisation: Dans le menu déroulant, sélectionnez le fond de carte désiré et la carte sera actualisée en conséquence.


**Obtenir le lien**
L’option « Obtenir le lien » est utilisée pour générer une URL partageable de l’état actuel de la carte avec les ensembles de données sélectionnés.
Utilisation:
- Lien raccourci - Cliquez ce lien pour utiliser le service de raccourci URL de Google pour générer un lien concis et aisément partageable vers l’état actuel du visualiseur de cartes PCAR.
- Courriel - Cliquez ce lien pour ouvrir un nouveau message dans votre service de courriel par défaut; l’URL sera insérée dans le corps du message, permettant de la partager aisément.


**Plein écran**
Le plein écran est utilisé pour masquer le haut et le bas de page du Ministère afin d’allouer plus d’espace à l’écran pour l’affichage cartographique.
Utilisation: Cliquer sur le bouton Plein écran (Full Screen) de la barre d’outils pour cacher l’en-tête et le pied de page du Ministère. Choisir de nouveau le bouton Plein écran (Full Screen) pour rétablir la vue par défaut.


**Ensembles de données**
Les ensembles de données présentent la liste des couches disponibles pour l’affichage sur la carte. La grille de données présente aussi les couches d’éléments interactifs. Les ensembles de données agissent également à titre de légende de la carte.
Trois types de couche peuvent être présentés sous l’onglet « Ensemble de données ».
Les couches d’éléments interactifs affichent des données avec lesquelles on peut interagir sur la carte, et qui peuvent être affichées dans la grille de données.
Les couches statiques ajoutent un contexte géographique au fond de carte. Elles ne sont pas interactives et ne sont pas affichées dans la grille de données.
Les couches SCW sont des couches superposées de données fournies par un service de cartes Web. Ces données sont interactives sur la carte, mais ne sont pas affichées dans la grille de données.


**Visibilité de la couche**
Sélectionnez l’icône en forme d’œil près du nom de l’ensemble de données pour masquer ou afficher la couche.


**Activer ou désactiver les requêtes du Service de cartes Web (SCW)**
Lorsqu’un utilisateur clique sur la carte (et pas un composant), les résultats pour toute couche SCW pouvant être interrogée s’afficheront pour le lieu cliqué. Ce comportement n’est peut-être pas voulu pour certaines couches. Cliquer sur les icônes d’activation et de désactivation des requêtes du SCW à la droite du sélecteur de couches activera ou désactivera cette fonctionnalité pour toute couche individuelle. L’option globale d’activation et de désactivation en haut du sélecteur de couches activera ou désactivera la fonction pour toutes les couches SCW. Les couches SCW ne pouvant pas être interrogées n’auront aucune icône d’activation et de désactivation.


**Légende des couches**
Une certaine symbologie est associée à chaque couche. Pour des couches de fonctionnalité (feature layer) simples, une seule icône sera présente à côté du nom de la couche. Pour les couches de fonctionnalité complexes (c.-à-d. celles où de multiples symboles sont utilisés par couche), l’icône apparaîtra comme une pile qui peut être activée ou désactivée.


**Traitement des erreurs de couche**
Si la couche ne se charge pas correctement, elle sera identifiée par un avis d’erreur. Au lieu des mesures standards liées à la couche, on peut choisir de recharger la couche (ce qui est particulièrement utile en cas de problème temporaire de connexion au réseau) ou de retirer la couche. Si une couche est […]


**Changement de l’ordre des couches**
Cliquez et faites glisser les six points à gauche de l’ensemble de données vers le haut ou vers le bas pour changer l’ordre d’affichage des couches sur la carte.


**[fr]Layer Group Boundaries**
While all layers can be re-ordered, WMS layers and Feature / Static layers may not be mixed together. When reordering layers, layers which cannot be mixed will be greyed out. Although layers can be reordered within their groups the grouping is static with feature and static layers always displaying over the WMS layer group.


**Métadonnées sur la couche**
Sélectionnez le lien « Métadonnées » pour afficher les métadonnées associées à cette source dans un panneau d’information repliable.


**Paramètres de la couche**
Cliquez sur le lien « Settings » (Paramètres) pour avoir accès aux options supplémentaires pour la couche.
La transparence de la couche peut être ajustée au moyen de la commande de réglage
Si la couche a un cadre englobant, sa visibilité peut être activée et désactivée au moyen de la case à cocher.
Si la couche est une couche de composants et qu’elle est en mode sur demande, l’option « Load All Features » (Charger tous les composants) est disponible. Le mode sur demande signifie que la couche sera téléchargée en partie en fonction des besoins. Cliquer sur « Load All Features » fera charger toutes les données de couches dans le navigateur en même temps, offrant de meilleurs temps de réponse une fois le téléchargement terminé. Cela s’appelle le mode instantané. Tenter cela avec de très grands ensembles de données peut geler le site ou faire planter la couche. Une couche en mode instantané aura le lien « Load All Features » désactivé et un crochet à côté du lien.


**Couches dépendantes de l’échelle de zoom**
Certaines couches peuvent être visibles uniquement à certains niveaux de zoom. Si une couche n’est pas visible à un niveau de zoom donné, le sélecteur de couche (Layer Selector) affichera un avis et offrira une action afin d’établir un zoom au niveau de zoom le plus prêt auquel la couche sera visible (cela peut consister à faire un zoom in)

**Ensembles de données ajoutées par l’utilisateur**
Des ensembles de données supplémentaires peuvent être ajoutés au visualisateur de cartes (map viewer). Les formats pris en charge sont : couche de fonctionnalité (Feature Layer) ESRI, WMS, GeoJSON, Shapefile (fichier de forme) et fichier CSV. Le bouton « + » au coin supérieur gauche du sélecteur de couche (Layer Selector) lancera l’assistant « Ajouter ensemble de données » (Add Dataset).
Utilisation: 
Sélectionner le type de données sources à ajouter : « Service » (Service) pour ajouter un service de carte Web; « Fichier » (File) pour télécharger un fichier GeoJSON, CSV ou Shapefile.
Préciser l’emplacement de l’ensemble de données - Saisir l’emplacement du service URL ou du fichier de l’ensemble de données. Si l’ensemble de données est un fichier du système de dossiers, sélectionner le bouton « Fichier » (File) et naviguer jusqu’à l’emplacement.
Une adresse URL peut être tapée ou collée dans la case.
RAMP prédira le type d’ensemble de données; si elles sont incorrectes, cliquer sur le bouton qui précise le type exact.
Cliquer sur le bouton « Connecter » (Connect) ou « Charger » (Load) pour amorcer le chargement de l’ensemble de données.
Préciser les caractéristiques de l’ensemble de données. - Selon le type d’ensemble de données chargé, divers paramètres peuvent être établis à cette étape-ci.
Un service de fonctionnalité (Feature Service) permet de choisir un attribut primaire, qui détermine l’attribut servant à déterminer une caractéristique dans la grille de données et des conseils sur la cartographie. Tous les autres renseignements proviennent des métadonnées du service.
Un service WMS permet de choisir le nom de la couche, ce qui détermine la couche du WMS qui servira de source de l’ensemble de données. Tous les autres renseignements proviennent des métadonnées du service.
Les ensembles de données axés sur les fichiers permettent de choisir ce qui suit : le nom de l’ensemble de données, qui sera affiché dans le sélecteur de couche (Layer Selector); un attribut primaire (Primary Attribute), qui agit de la même manière que le service de fonctionnalité (Feature Service); une couleur de symbole (Symbol colour), qui détermine la couleur des points, des lignes, des polygones sur la carte.
En cliquant sur le bouton « Ajouter ensemble de données » (Add Dataset), on peut insérer la couche dans la carte.


**Data Grid**
[fr][This section requires a complete rewrite]


**Panneau d’information**
Le panneau d’information affiche les données associées à l’élément interactif sélectionné.
Utilisation: Sélectionnez un élément interactif directement sur la carte ou cliquez sur le lien « Détails » dans la grille de données. Le panneau d’information affichera les renseignements relatifs à l’élément sélectionné. Un clic à côté de l’élément interactif ou sur la flèche située dans le coin supérieur gauche du panneau masquera l’affichage du panneau.


**Exporter la carte**
« Map Export » est utilisé pour convertir le contenu de la carte en une image qui peut être téléchargée par l’utilisateur.
Utilisation: Cliquez sur le bouton « Map Export » (Exporter la carte) dans la barre d’outils pour amorcer la génération de l’image. La fenêtre « Map Export » s’ouvrira. Un message de chargement s’affichera et l’aperçu de l’image s’affichera une fois qu’il sera généré. Cliquez sur le bouton « Download Image » (Télécharger l’image) pour enregistrer l’image. Cliquez sur le X pour fermer la fenêtre « Map Export ».


**Accessibilité**
Cette page respecte les règles pour l’accessibilité des contenus Web WCAG 2.0 AA.
Accessibilité au clavier - La fonctionnalité du clavier est offerte en tant qu’alternative pour les utilisateurs qui sont incapables d’utiliser une souris. Utilisez la touche de tabulation pour naviguer vers les liens et les contrôles sur la page. Appuyez simultanément sur les touches Majuscule+Tabulation pour revenir un pas en arrière. Utilisez la touche Entrée ou la barre d’espace pour activer les liens et les contrôles.
Contrôles de navigation - Curseur de zoom : Avec le curseur de zoom sélectionné, utilisez la touche flèche orientée vers le haut pour effectuer un zoom avant; utilisez la touche flèche orientée vers le bas pour effectuer un zoom arrière.
Onglets « Ensembles de données » et « Données » - Avec l’onglet « Ensembles de données » ou l’onglet « Données » sélectionné, utilisez les touches flèches orientées vers la gauche ou vers la droite pour passer d’un onglet à l’autre.
Onglet « Ensembles de données » - Dans l’onglet « Ensembles de données », utilisez les flèches orientées vers le haut et vers le bas pour naviguer entre les différentes couches. Avec la poignée de couche (l’icône à six points) sélectionnée, utilisez la touche Entrée ou la barre d’espace pour saisir la couche. Les couches saisies sont identifiées par un fond bleu foncé. Avec la couche saisie, utilisez les flèches orientées vers le haut ou vers le bas pour réorganiser les couches sur l’interface cartographique. Appuyez sur la touche Entrée ou la barre d’espace pour libérer la couche.


**Durée du chargement / Comportement imprévu**
La durée des chargements peut varier selon l’emplacement réseau et la disponibilité de la largeur de bande. Un comportement imprévu peut survenir lorsque des interactions avec la carte ont lieu avant la conclusion du chargement des données. Veuillez permettre le chargement complet de la page Web avant d’activer d’autres fonctions sur la carte.
Remarque: Lorsque la mention « Chargement » apparaît dans le coin inférieur droit de la carte ou lorsque la grille de données affiche un message de chargement en cours, attendez que l’indicateur de chargement disparaisse avant d’activer d’autres fonctions sur la carte.

**Comment by dan-bowerman** [comment]
[help_en.txt](https://github.com/fgpv-vpgf/fgpv-vpgf/files/134979/help_en.txt)
[help_fr.txt](https://github.com/fgpv-vpgf/fgpv-vpgf/files/134980/help_fr.txt)

**Comment by mweech** [comment]
Awaiting translation of French text.

**Comment by bchagnon** [comment]
Status:
- reviewing the English
- roughly (and unofficially) translating the French

**Comment by AleksueiR** [comment]
No update.

**Comment by bchagnon** [comment]
Here is what I have as of today. Much needs to be added as the viewer progresses.

[help_en_0.txt](https://github.com/fgpv-vpgf/fgpv-vpgf/files/241215/help_en_0.txt)
[help_fr_0.txt](https://github.com/fgpv-vpgf/fgpv-vpgf/files/241216/help_fr_0.txt)

**Comment by spencerwahl** [comment]
PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/549
