### ISSUE TITLE
HTML 5 fullscreen

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1853]
Should we switch our fullscreen functionality to us HTML 5 full screen mode? This can allow implementations running inside an iframe to use fullscreen function as well.

**Comment by milesap** [comment]
I'll have a look into this - if it works I'll implement it

**Comment by AleksueiR** [comment]
This one hasn't been decided on yet. Proceed with caution.

**Comment by milesap** [comment]
Ok, I'll post any info I find - I won't implement anything at this time

**Comment by milesap** [comment]
HTML5 fullscreen should be avoided for now:
- It is currently experimental, all browsers custom prefix the API
- Using [this demo](http://labs.qnimate.com/full-screen-api/) across IE, FF, and chrome, fullscreen renders the content differently for all three browsers
- Copying the demo page to localhost caused chrome to no longer enter fullscreen mode (without errors). FF and IE work.

I'll proceed to fix fullscreen on geo4 without changing the implementation.

**Comment by alyec** [comment]
How about a wrapper library like https://github.com/sindresorhus/screenfull.js/ to easy some of the prefixing pain?  That demo also works consistently across browsers for me.

**Comment by AleksueiR** [comment]
All major browsers seem to be supported: http://caniuse.com/#feat=fullscreen

**Comment by milesap** [comment]
Mobile browsers are not supported. The prefixing is not a big issue, screenfull.js demos render differently between all the browsers as well.

**Comment by milesap** [comment]
Spoke with @AleksueiR and @alyec - we are ok with no iOS support.

**Comment by milesap** [comment]
Note: If the viewer is in an iframe, the iframe must have the property `AllowFullScreen` for fullscreen to work.

**Comment by mweech** [comment]
@milesap Please make note of the AllowFullScreen requirements in our documentation.
