### ISSUE TITLE
Viewer fails to load if geosearch is enabled by search services are not provided

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1855]
Geosearch can be enabled in the config under `map.components.geoSearch`, but if no search services are provided under `search.serviceUrls`, the geosearch module crashes the app trying to retrieve the province list.

Version affected: 1.6.1

Options:
1. Including of `serviceUrls` should be enforced in schema if geosearch is enabled. (hard to implement, easy to break by manually editing the config file since schema validation happens only on build in 1.x versions).
2. Check for presence of `serviceUrl` and disable geosearch if absent. (easy to implement)
3. Implement proper schema validation at run time (I think it's coming up in 2.x)

**Comment by milesap** [comment]
It seems option 3 is best; malformed configs is a map authors problem, they should always follow the correct schema. At least option 3 can catch these mistakes without hardcoding checks.

**Comment by james-rae** [comment]
If geosearch services were down, would that also crash the app (there would still be no provinces)?  If true, should also gracefully handle that situation.

**Comment by james-rae** [comment]
Getting Barry to do option 2 for time being
