### ISSUE TITLE
Malformed CSV?

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1856]
One of the sample CSV files (2015-12-15 FGP dataset INTERNAL ONLY 2015 data_ori.csv) has lots of duplicate column names. Angular Material select component doesn't like duplication values and there are lots of errors being dumped into the console. The loader works and the layer will be added to the map though. I'm not sure if anything else is breaking because of that.

Is this a common occurrence for CSV files to have duplicate columns? Is this considered a malformed file for importing into the viewer? Should we bar such files at the validation stage?

What about other formats, can Shapefile or GeoJSON have duplication fields?

**Comment by james-rae** [comment]
Our internal attribute structures use the field name as the object key.  So on assignment/generation, if the conversion libraries don't error, they will certainly overwrite the first instance of a duplicated field with the value of the second instance

**Comment by mweech** [comment]
something like a CSV we can't assume field names would be unique (i.e. might have multiple "totals" columns).  would suggest it can be used directly as a display name, but would have to have a prefix if used as an object key rather than being used directly.

**Comment by milesap** [comment]
Fixed on geoApi PR https://github.com/fgpv-vpgf/geoApi/pull/253
