### ISSUE TITLE
Spanish build support

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1859]
Update Spanish branch to ~~1.6.1~~ a new branch for NACEI. Still at version 1.6.0.

**Comment by ChrisLatRNCan** [comment]
Will wait for 2.0 for a biggest update. Meanwhile, help section (.md file) will need to be translated properly.

**Comment by mweech** [comment]
@ChrisLatRNCan FGP management elected to not support Spanish directly.  I would suggest you create a seperate NACEI project repo to maintain code related to Spanish translations instead of in the main viewer repo here.

**Comment by ChrisLatRNCan** [comment]
@mweech OK
But I'm confused...

Thanks

**Comment by ChrisLatRNCan** [comment]
Will probably start another project
