### ISSUE TITLE
GeoSearch Component

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#186]
A user should be able to enter a place name, a postal codes FSA (forward search area), a lat/long coordinate, or an NTS number and the map will zoom to the entered location.

The component should use the GeoNames service for place names, and can use the GeoGratis service for FSA, Lat/Long and NTS lookup.

For FSA, only the first 3 characters are allowed (A1A = ok; A1A1 = no)
For NTS, need 3 numbers, letter between a-p then number between 01 to 16
For scale, need to start with 1: followed by number or spaces (1:100000 = ok, 1:100 000 = ok)
For coord in decimal degree (lat, long): [+-](nothing = +) 0 to 90 [space , or ;] [+-](nothing = +) 0 to 180
For coord in degree, minute, second (lat, long): [+-](nothing = +) 0 to 90 [space] 0 to 60 [space] 0 to 60 [, or ;] [+-](nothing = +) 0 to 180 [space] 0 to 60 [space] 0 to 60

**Comment by mweech** [comment]
Removed from Usability results epic.
