### ISSUE TITLE
Multiple issues when adding ESRI Air Quality Scale Dependency layer 

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1867]
Tested build: http://fgpv.cloudapp.net/demo/v1.7.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
User added scale dependency layer:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

- In step 3 Configure layer, there is only one option "Ozone" displayed, missing four other options (below 1st screenshot)
- After this layer added to Lambert projection, all four zoom lever layers are visible (below 2nd screenshot)
- Datagrid cannot be opened as "There was an error retrieving this resource..." (below 3rd screenshot)
- Add the layer to Mercator basemap, for example World Topographic Map, this layer is disabled and cannot be toggled to "Show layer"; There were no sub-layers displayed under Ozone even Ozone layer is in expanding condition (below 4th screenshot)

![image](https://cloud.githubusercontent.com/assets/18723160/25624116/7611bab6-2f26-11e7-8a10-b325fceed8d7.png)

![image](https://cloud.githubusercontent.com/assets/18723160/25624408/4384c88a-2f27-11e7-91fe-fd7fdc395d3d.png)

![image](https://cloud.githubusercontent.com/assets/18723160/25624460/71b7cbda-2f27-11e7-8859-04cfb325c311.png)

![image](https://cloud.githubusercontent.com/assets/18723160/25624969/1879bd38-2f29-11e7-8d7b-76ed15edd81b.png)

**Comment by AleksueiR** [comment]
Something is wrong with the service: 

![ozone](https://cloud.githubusercontent.com/assets/2285779/25632154/963adaec-2f40-11e7-8b58-5a884ba912e1.gif)

**Comment by AleksueiR** [comment]
The services was fixed by WIG. Should be working correctly now. Please, check.

**Comment by IsabellaPan** [comment]
CESI service was fixed, this issue could be closed
