### ISSUE TITLE
Tooltip for map points display HTML tags

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1868]
Tested build: http://fgpv.cloudapp.net/demo/v1.7.0-rc1/prod/samples/index-fgp-en.html

Linked to #1798 

This bug fix was tested with a file which has html lists in the name field. Map points for this layer displayed html tags along with the name. Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/25661303/0dadd28a-2fde-11e7-8a18-78df0d603037.png)

**Comment by mweech** [comment]
my initial thought is this is not a bug, the viewer is not responsible for poorly formatted/chosen fields.  

(assuming we don't want HTML formatting allowed as it may break stuff)

**Comment by milesap** [comment]
Tooltips are generally unformatted since they contain a very small amount of data. Can't see a reason for allowing HTML here (unless someone wants to make big tooltips).

**Comment by AleksueiR** [comment]
Johann has added an ability to parse and display image urls in tooltips, but that's a very specific case.
