### ISSUE TITLE
Unit Test Fixes

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1869]
- [ ] delete low value / useless tests (listed below)
- [ ] fix broken tests (listed below)
- [ ] investigate the `stepper` code to see if unit testing is feasible
- [ ] investigate testing of blank basemaps
- [ ] combine `state` directive tests into `content-pane`
- [ ] name / describe tests correctly in `content-pane`

## delete
basemap-item
basemap
stepper-item
entry-symbology
details
mapnav
entry-controls
help-overlay
entry-flag
entry
help.directive
shell
morph

## fix
layer-registry
help (once help rewrite is complete)
toc
geo
state.directive

## keep
content-pane
statemanager

**Comment by mweech** [comment]
Issue is well out of date and best to be handled in a new and targeted testing initiative.
