### ISSUE TITLE
Back To Cart not capturing basemap in certain scenario

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1871]
Tested build; http://fgpv.cloudapp.net/demo/v1.7.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

- Switch to blank map from default loaded Transportation (CBMT)
- Select any basemap in another Projection, for example World Imagery
- Apply BackToCart
In this scenario, World Imagery basemap is not captured after BackToCart, intead it loaded blank map. Only the overview map displayed the World Imagery map.

![image](https://cloud.githubusercontent.com/assets/18723160/25674121/c07f041e-3007-11e7-8065-79a30841ad83.png)

**Comment by james-rae** [comment]
Appears to have fixed itself after grand refactor
