### ISSUE TITLE
Change build tool to webpack

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1873]
This is to replace both gulp (as the current build tool) and bower (to npm modules). This is an epic which, when implemented, will resolve or will be trivial to resolve the sub-issues below.

#### Update:
Webpack build scopes all our dependencies solving the library collision problem (#960 and other potential collisions we hand't experienced yet).

Read some details on how the new build tool works here: [wiki page](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Rebasing-PR's-for-new-webpack-build-system).

**Comment by AleksueiR** [comment]
We need some guide/description of how the build process changed, where things are located now, and how the format of source files differs from the old style.
