### ISSUE TITLE
Be able to specify about and help file name from config file

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1874]
Because many html page can share the same build it would be great to be able to specify the name for the about and help markdown in the configuration file. This ways it is easy to set different files for different application. 

For the help, if users develop plugin function they will be able to add them to the help. Or we do not let user modify real help but give them a way to add to the existing help.

**Comment by mweech** [comment]
About page: This is a very good idea.  It allows you to maintain a collection of about pages that may be relevant to different sections of an organization or allows for a single about entry for a collection of maps (i.e. multiple CESI maps).  

Help page: The need to provide help content for users re: plugins makes this a useful feature.  I would suggest 3 modes for help content:
1. "core" help, no plugin content shown
2. "core" help + a plugins section with help content (if provided)
3. custom help, totally overrides existing help

**Comment by AleksueiR** [comment]
I think this is already possible with `help` and `about` config options.

**Comment by barryytm** [comment]
Under the current [schema](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.2.0-daily07/schema.json#L773), you can only specify the names of folder of `about` and `help`.  It would be problematic when specified folders don't contain the files required.  As for plugin of `help`, I don't think it is currently implemented unless I am mistaken.
