### ISSUE TITLE
North arrow should turn into a marker icon when over the pole

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1875]
Now, the north arrow simply sticks to a point on a basemap:
![](https://i.imgur.com/FhXpl28.png)

The icon should change to something else in such cases:
![](https://i.imgur.com/MUa4EeO.png)

@jolevesq Do you know what would be an appropriate icon/image to show there?

**Comment by milesap** [comment]
I vote for:

![](http://vignette4.wikia.nocookie.net/frontierville/images/b/b4/The_North_Pole-icon.png/revision/latest?cb=20101209023946)

**Comment by AleksueiR** [comment]
![](https://i.imgur.com/nLCP3lR.png)
![](https://i.imgur.com/jcTSPZo.png)
![](https://i.imgur.com/SEqGM5L.png)
![](https://i.imgur.com/IMwcbea.png)

**Comment by milesap** [comment]
The snowman is nice. We also have ![](http://www.creativehunt.co/wp-content/uploads/2016/02/Santas-Sleigh-300x300.png)
