### ISSUE TITLE
"Zoom to Feature" goes to the scale that all zoom levels for Ozone layer were out of scale

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1878]
Tested build: http://fgpv.cloudapp.net/demo/v1.7.0-rc2/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
User added scale dependency layer:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This issue happened with Mercator basemaps only. It is similar to previous logged https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1454 which was closed in Feb.
- Add scale dependency layer by selecting Ozone layer
- Click any map point for the added layer to display Point Info panel
- Click "Zoom To Feature" button highlighted in below screenshot
![image](https://cloud.githubusercontent.com/assets/18723160/25869356/001d85f8-34ce-11e7-93ca-fe504a6abe4f.png)
- Click Legend to open up layers - all zoom levels are out of scale, see below
![image](https://cloud.githubusercontent.com/assets/18723160/25869453/57bff796-34ce-11e7-9169-e6d8a6fd7aa2.png)

**Comment by AleksueiR** [comment]
This will be fixed by #1959.

**Comment by milesap** [comment]
Re-test needed on [latest daily](http://fgpv.cloudapp.net/demo/v2.0.0-daily11/) to see if this can be closed.

**Comment by james-rae** [comment]
Believed fixed; layer no longer exists to re-verify.
