### ISSUE TITLE
Map export never finish loading - "Syntax Error" in console

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1882]
Tested build: http://fgpv.cloudapp.net/demo/v1.7.0-rc2/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

Therefore, Download button could not be enabled, and Legend not displayed.
![image](https://cloud.githubusercontent.com/assets/18723160/26005334/bba1a54a-3706-11e7-8ce9-c47c5866c5d6.png)

![image](https://cloud.githubusercontent.com/assets/18723160/26005411/ea18793a-3706-11e7-9e18-74e753cb928b.png)

**Comment by AleksueiR** [comment]
Please, re-test. This doesn't seem to be an issue in 2.0.
