### ISSUE TITLE
Data Details Panel

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#189]
- [x] Port existing Dynamic/Feature layer support
- [x] Support for new data types
- [x] Complete accessibility improvements with aria (#195)
- [x] ~~#145~~
- [x] ~~#156~~
- [x] ~~#162~~

Traceability Matrix ID#???

**Comment by dan-bowerman** [comment]
Includes
#155 
#156
#160 
#162
#195
#174

**Comment by dan-bowerman** [comment]
2-16-2016 - Dynamic/Feature layers are only ones being interrogated. More work needs to be done to populate panel with data.

**Comment by AleksueiR** [comment]
No update.

**Comment by mweech** [comment]
removed #147 from rollup of tasks.  Closing
