### ISSUE TITLE
Closing Import File menu does not reset to previous page

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1924]
Clicking the 'X' on the file import closes panel but does not go back to Layers page. "TypeError" in console.

![importfile](https://cloud.githubusercontent.com/assets/9637542/26687955/4a39888c-46bf-11e7-85b3-fccd7e584afd.JPG)
![resetundefined](https://cloud.githubusercontent.com/assets/9637542/26687963/4df3fbec-46bf-11e7-980c-ad93d8d5c5bd.JPG)

**Comment by JahidAhmed** [comment]
If a file is uploaded first, then the reset works as expected.

**Comment by AleksueiR** [comment]
It tries to reset all the user-editable values to defaults when you click the close button, and since the file hasn't been uploaded yet, there is nothing to reset.
