### ISSUE TITLE
Zoom text shown in top left

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1925]
After zooming out one level, on the top left of the screen there is text for Zooming In and Out.

**Comment by AleksueiR** [comment]
Screenshot please.

**Comment by JahidAhmed** [comment]
![zoom](https://cloud.githubusercontent.com/assets/9637542/26690783/9940950c-46c8-11e7-8eb9-64fb237602c9.JPG)

**Comment by AleksueiR** [comment]
Seems to be default esri zoom in/out controls got unhidden :)
