### ISSUE TITLE
The north arrow does not show up

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#1942]
The North arrow was not rendered properly.  Probably had to do with the directive.

![capture](https://user-images.githubusercontent.com/19259169/26932016-495d6e8a-4c30-11e7-9374-4111fc9c0f2c.PNG)
![capture2](https://user-images.githubusercontent.com/19259169/26932020-4accb35c-4c30-11e7-9239-9820b9dca1ad.PNG)

**Comment by mweech** [comment]
please make sure to estimate
