### ISSUE TITLE
Review issue where pressing escape closes main panels

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1947]
Part of #1928:
> While focusing on any input field while importing a file layer, pressing 'esc' will hide the entire legend. 

While not a bug, may not be optimal behavior.

A little background info:

A panel can have multiple child panels defined, however, only one child can be open at a time. So when the file import panel is opened, the legend panel is closed. A history of ordered active panels is maintained so pressing escape closes panels in the order they were opened.

Clicking on the close button itself is different, as we explicitly open the legend panel (which in turn closes the file import panel).
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/loader/loader-file.directive.js#L367

I can't see an easy way to change this. One way is to upgrade the panel history such that when a sibling panel closes another, the close panel is added to the history. We would then toggle instead of close panels in the history.

**Comment by mweech** [comment]
Panel API now makes this irrelevant.
