### ISSUE TITLE
Help documentation clarification

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1951]
As per our help documentation, we state: `Note that the map must be focused for key binding to work. The map has focus when there is a blue border around it.`

In cases where the overview map is pressed but the cursor is hovering over the overview map and not the main map, key binding does not work even though there is a blue border around the map.

Should we potentially reword / clarify the documentation?

**Comment by milesap** [comment]
Opened #2022 - this wording is correct but there is an issue with our key bindings.
