### ISSUE TITLE
Air Ozone Layer clarification with feature details

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1954]
If the only visible layer is the `Air Ozone Scale Dependency x2 More Ozone Than Other Planets`, zooming out one (or multiple) levels and clicking on the map has no effect: the feature details panel does not appear due to the layer being dependent on scale level.

May want to indicate somehow the scale level for toggling query for such layers.

**Comment by mweech** [comment]
Due to zoom scale dependency not yet being fully implemented?

**Comment by AleksueiR** [comment]
Fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1994.

![](https://i.imgur.com/b9V4HwM.png)
