### ISSUE TITLE
Unable to reload layers imported from file

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1955]
Attempting to reload a layer imported from a file shows the layer still active in the TOC however we are not able to reproduce the layer on the map.

May need to cache data to allow for file layers to be reloaded.
We can also make the button unclickable or hide / remove it completely until further changes.

**Comment by AleksueiR** [comment]
Duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2056 - all user-added layer can be reloaded now.
