### ISSUE TITLE
Grey lines appear after closing legends on chrome

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#1970]
The following appears after closing a legend on Chrome when zoom is 125%, 150%, or 250%.  There could be more.

![capture](https://user-images.githubusercontent.com/19259169/27101388-90a437f6-504f-11e7-9617-a3c87c884848.PNG)

**Comment by AleksueiR** [comment]
No lines with zoom set to 100%?

**Comment by JahidAhmed** [comment]
Nope, none at 100%

**Comment by JahidAhmed** [comment]
So I noticed that switching to a different tab and back to the Viewer tab gets rid of the lines and also highlighting the entire page (Ctrl + A) and clearing the highlight also removes the lines

**Comment by AleksueiR** [comment]
Sounds like a browser artifact; I can see the lines made by the bottom border of the collapsing panel, but they do not linger in my Chrome:
![lines](https://user-images.githubusercontent.com/2285779/27129119-36fe1ec6-50cf-11e7-843b-4836ef37eb4d.gif)
I wonder if the line will disappear when if you resize the browser window. In any case, I don't think we can do much about it.

**Comment by AleksueiR** [comment]
Closing since it's browser-related.
