### ISSUE TITLE
Datatable header does not update properly

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1974]
The header of the data panel seems to get stuck after switching the data source several times and will not update properly.

![datatable_name_stuck](https://user-images.githubusercontent.com/2285779/27130721-799401dc-50d5-11e7-83f3-34103f3d770a.gif)

Notice how after changing to `my custom title` the header doesn't change even after closing the panel and opening it again. Closing the panel should have cleared all data from the display manager.

Affects latest develop: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html

**Comment by jolevesq** [comment]
It should be because of the custom tile set by the config file. If you play with the other table it should work.
