### ISSUE TITLE
geoSearch should handle external service errors gracefully

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1976]
When the following GeoGratis files become unavailable, GeoSearch fails to provide results, but did not provide an appropriate error message.  Should indicate there is a service availability issue.

Links affected:
http://geogratis.gc.ca/services/geoname/en/codes/province.json
http://geogratis.gc.ca/services/geoname/en/codes/concise.json

Error:

```json
{
    "error": "javax.persistence.PersistenceException"
}
```

**Comment by milesap** [comment]
Services operational :+1:

**Comment by mweech** [comment]
@milesap  did the viewer gracefully handle the 500 service errors?

**Comment by milesap** [comment]
@mweech It didn't crash, but it didn't indicate anything was wrong either. Typing in the search bar didn't return any results.

**Comment by mweech** [comment]
OK, lets flip back to TODO to have a good error message provided i.e. "Service Unavailable: GeoSearch web services are not currently available."

**Comment by milesap** [comment]
We fetch `concise.json` and `province.json` on page load. So we have a few options:
- Disable search icon and show tooltip indicating outside service failed to load
- Don't pre-fetch `concise.json` and `province.json` (if possible) and show a ~~alert box~~ nice message (where?) to the user.

**Comment by AleksueiR** [comment]
Cast my vote for __disabling search button and changing the wording of its tooltip to indicate that the service has failed__. 

![](https://i.imgur.com/Kz01QBA.png)
