### ISSUE TITLE
webpack prod uglify broken on PR #1966

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1979]
http://fgpv.cloudapp.net/demo/users/AleksueiR/wrong-projection/prod/ shows rv-main.js at ~8mb, should be around 2.5mb. Webpack throws a soft error on prod builds. Please investigate

**Comment by AleksueiR** [comment]
I don't see any changed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1966/files that might affect the build, except maybe geoApi being bumped from 59 to 62. Everything else is just regular code.

**Comment by milesap** [comment]
Only thing I see at a quick glance is https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1966/files#r122194027, but no idea if that would cause the uglify issue

**Comment by AleksueiR** [comment]
The production build is correctly minified when geoApi version is set to 59.
Running `npm run build -- --env.prod` with geoApi#65 fails:
```text
ERROR in rv-main.js from UglifyJs
Unexpected token: operator (>) [rv-main.js:14836,32]
```

**Comment by AleksueiR** [comment]
This seems to have fixed itself:
![](https://i.imgur.com/s1787iG.png)

**Comment by milesap** [comment]
Excellent, I double checked the file size to make sure it somehow didn't jump to 27mb.

**Comment by AleksueiR** [comment]
:D Yeah, I did that too. It about matches my local build with 2,725,687 bytes. Will close this.
