### ISSUE TITLE
Basic Layer Loader

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#198]
(From James Rae:)

load config file at startup

iterate over layer section of config file, triggering loader

define layer load event handler
* update visuals to indicate loaded state (tricky: data is not loaded yet, but is "done" if not at scale level, or visibility off)

define layer update-end event handler
* re-application of active highlighting (feature layer only)
* update visuals to indicate loaded state

define layer update-start event handler
* update visuals to indicate layer is loading data

define layer error event handler
* remove from map stack (may want to re-examine in new architecture)
* update visuals to indicate error state

define feature layer click event handler
* trigger show data & anchor tip process (or hide if already showing) for event feature 

define feature layer mouse-over event handler
* trigger show hovertip process for event feature 

define feature layer mouse-out event handler
* trigger hide hovertip process for event feature 

package event handlers in event object (stateful) stored in geo module

determine shared/common sub-functions in the load routines below

load a feature layer from service
* config snippet input
* new object (prototype comes from geoApi)
* call geoApi.layer.wrapEvents on object
* add to layers collection in geo
* add to map object
* generate bounding box (save for later)
* trigger attribute loader in geoApi, store result in layer collection

load a wms layer from service
* config snippet input
* new object (prototype comes from geoApi)
* call geoApi.layer.wrapEvents on object
* add to layers collection in geo
* add to map object
* register with map click if appropriate
* generate bounding box (save for later, or skip due to terrible wms support)

load a dynamic layer from service
* config snippet input
* new object (prototype comes from geoApi)
* call geoApi.layer.wrapEvents on object
* add to layers collection in geo
* add to map object
* register with map click if appropriate
* trigger attribute loader in geoApi, store result in layer collection
* generate bounding box (save for later, would rely on extent defined with service)

trigger datagrid load when attribute loader finishes for a layer

**Comment by jolevesq** [comment]
Even if it is a dynamic layer, if we keep the geometry, we can do the active highlighting. This way, from a user perspective the only difference from a dynamic or feature layer is the hover.

**Comment by james-rae** [comment]
if we pull the geometry for a dynamic, are we not then loading the same amount of data as we would with a feature layer?  Or would geometry be loaded "on demand" for an individual polygon as it is clicked?  Would we need to consider checks or timeouts for massive lines/polygons?

**Comment by jolevesq** [comment]
The problem with the speed came from the drawing engine. For GCViz, I keep the geometry inside the array of attributes for each feature. I use this geometry only to draw highlight when user select a row. For my 25 000 points there is no problem. We can test for massive line/polygons layers. Do you have a sample I can quickly test in GCViz?. As you say load the geometry on demand when they are clicked is a good idea as well.

**Comment by james-rae** [comment]
This map service, layer index 4 (Protected Areas Polygons), has always been our bad-boy.  It can load with feature layer on-demand but is very slow and will kill IE
http://ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/

**Comment by jolevesq** [comment]
I tried to load it for the datatable and it timed out. How many polygons are inside?

**Comment by james-rae** [comment]
~34,000

**Comment by jolevesq** [comment]
Even when I try to query directly from the service there is an error if we query more then 3000 polygons and it is pretty slow. It will be a problem just to get attributes to populates the datatable. I think your idea of getting the geometry when needed can be good to be able to display highlight on selection.
