### ISSUE TITLE
Automate testing of User Added Layers panel with Protractor

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1980]
#### Test Cases
- [ ] Panel opens for both file and service types
- [ ] Panel closes on escape and close button
- [ ] Import succeeds for every valid layer type
- [ ] Handles bad inputs gracefully with proper error messages
- [ ] . . .

**Comment by mweech** [comment]
Need to assess overlap with UI automation testing.
