### ISSUE TITLE
"Spatial Density Of Barley ..." layer is missing a layer type flag

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1981]
![](https://i.imgur.com/qZUHEVF.png)

http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/

**Comment by james-rae** [comment]
The child layer in this service is of a Raster type, not a Feature.

First suspicion is [this enum](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.0.0-daily02/src/app/geo/geo.constant.service.js#L3) doesn’t have an entry for `esriRaster`

More suspicious is [this function](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.0.0-daily02/src/app/ui/toc/legend-element-factory.class.js#L324) doesn’t have an image for `esriRaster`

**Comment by AleksueiR** [comment]
This must be it. The import logic parses `esriRaster` as dynamic [here](https://github.com/AleksueiR/fgpv-vpgf/blob/develop/src\app\ui\loader\layer-source.service.js#L54), according to the layer type matrix conversion.
But the internal layerType property is still raster, and, as you found, we don't have it in our layer type list.

Need to add appropriate icon and label for that layer type then.

**Comment by barryytm** [comment]
Was fixed by #2074.
