### ISSUE TITLE
Be able to easily enable/disable identify

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1985]
For example, with the plugin coord info we would like to disable the identify task when user click on map to get coordinate info the setting identify back when user close the information panel.

**Comment by mweech** [comment]
Thoughts:
- have a config based toggle for default behavior..
- also provide a run-time internal toggle a plug-in could use to suppress built-in viewer Identify
- how do we deal with poor plug-ins?  could suppress and then screw up and never re-enable.. perhaps some kind of notice to the user while it's disabled..? "plug-in has temporarily disabled Map Identify.  Click here to re-enable"

**Comment by AleksueiR** [comment]
A runtime `identify` toggle will be implemented as part of the following issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2595.

**Comment by AleksueiR** [comment]
@james-rae Can we close this one?
