### ISSUE TITLE
'Date layer field' not reloading all points on map

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1988]
The `Date layer field` initially has a filter applied for the datatable, so opening the datatable results in many points being removed from the map.

However, `Clear filters` seems to only result in a few of the original points being displayed on the map and many of them still are not visible.

This can be verified by reloading this layer.

**Comment by JahidAhmed** [comment]
This was a misunderstanding on my part as I did not notice the permanent filter applied in the `Incident Report Number` column. So clearing filters has no effect on that column, which is why not all points are displayed.

I think this can be closed.

**Comment by AleksueiR** [comment]
So, "clear filters" does not remove permanent filters? Can you remove permanent filter manually?

**Comment by JahidAhmed** [comment]
I don't see a way to remove permanent filters other than modifying the config.

**Comment by AleksueiR** [comment]
Ah, yes, there is a `static` property on the filter that you can set in the config. Thanks.

This can be closed now.
