### ISSUE TITLE
When switching table with a custom title, wrong title is shown

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1992]
If you open Date layer field from index-mobile.html, Custom tile is shown as title. If you open another layer table then reopen Date layer field table, the title is set as the last table title

**Comment by AleksueiR** [comment]
Possible duplicate: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1974

**Comment by JahidAhmed** [comment]
Is this the same as #1974

**Comment by jolevesq** [comment]
Yes, I will close this one and update #1974
