### ISSUE TITLE
Records are not loaded into the datatable for Protected Area polygon layer

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1998]
Service: http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

Datatable is empty:
![](https://i.imgur.com/XDzsiKu.png)

**Comment by james-rae** [comment]
Verified that attribute data is loading from the server.
