### ISSUE TITLE
Import Wizard Defaults to Dynamic When Given a Feature Layer

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1999]
When adding a service via the wizard, if supplying an indexed url to a feature layer (e.g. `www.myserver.com/mapserver/3`), the next step in the wizard will default to Dynamic Layer (with Feature Layer being an option in the list).  

Pre-refactor, a feature layer url would default to Feature Layer type.

**Comment by AleksueiR** [comment]
I think it might be sorting option by alphabet. Need to check. In pre-refactor it wasn't possible to add Feature as Dynamic anyway, so we defaulted to the only option that would work :D
I'm perfectly good with changing order. What do you think the most common case is? Adding features as features or as dynamics?

**Comment by james-rae** [comment]
> Adding features as features

Seems most intuitive.  Both layer types have advantages / disadvantages.  Feature layers are more rich in interactivity, so a clueless user might appreciate having that as default
