### ISSUE TITLE
The config option for disabling hover tips needs to be added to the schema

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2001]
The config option for disabling hover tips need to be added to the schema.

Add a sample to index-samples.html that will exercise this option re: #1786

**Comment by AleksueiR** [comment]
I think it's already implemented: https://github.com/AleksueiR/fgpv-vpgf/blob/1969-zoom-scale/src/app/core/config.class.js#L429

**Comment by james-rae** [comment]
Is it just a matter of adding something to the schema?  I don't see anything herer that would suggest hovertips.
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.0.0-daily05/src/content/samples/schema.json#L204

Also, from a geoApi perspective, the hover events are always wired up. Is there something in the client that is suppressing the tip?  It might be more efficient to pass this along to geoApi so it doesn't bother lookup up data that is not displayed

**Comment by AleksueiR** [comment]
Yes, you are correct, it needs to be added to the schema.
Hover tips are suppressed internally for controlled layers and hidden legend blocks. Not sure about moving that to geoapi though.

**Comment by james-rae** [comment]
Keep the tip suppression where it is, but also tell the FeatureRecord that there are no tips.  Right now, if tips are off, grid has not been loaded, and you hover over something, the Record is fetching tip info from the server.

If we don't do it now, we should make a new issue for that (for later).
