### ISSUE TITLE
Issue with RCS layer registration

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2002]
A bug has been identified with regards to the registration of a service in RCS.

Here is the description of the problem from Jose's point of view:

Hi 

I have been reported a problem with registering the following layer in RCS:

http://services1.arcgis.com/HsjBaDykC1mjhXz9/ArcGIS/rest/services/FloodExtentPolygon_SouthManitoba_MODIS_20170405_1530_1705/FeatureServer/0 

The Data Catalogue is sending the following request:

{
  "en": {
    "service_url": "http://services1.arcgis.com/HsjBaDykC1mjhXz9/ArcGIS/rest/services/FloodExtentPolygon_SouthManitoba_MODIS_20170405_1530_1705/FeatureServer/0",
    "service_type": "esriFeature",
    "service_name": "FloodExtentPolygon_SouthManitoba_MODIS_20170405_1530_1705" 
  },
  "fr": {
    "service_url": "http://services1.arcgis.com/HsjBaDykC1mjhXz9/ArcGIS/rest/services/FloodExtentPolygon_SouthManitoba_MODIS_20170405_1530_1705/FeatureServer/0",
    "service_type": "esriFeature",
    "service_name": "FloodExtentPolygon_SouthManitoba_MODIS_20170405_1530_1705" 
  },
  "version": "2.0" 
}

But getting the following error:

 { "msg": "Problem communicating with service endpoint http://services1.arcgis.com/HsjBaDykC1mjhXz9/ArcGIS/rest/services/FloodExtentPolygon_SouthManitoba_MODIS_20170405_1530_1705/FeatureServer/0 content-type" }

Tested also with the RCS test page and same issue.

The request looks fine, but maybe not sure if maybe the service_type value is not what is expecting RCS?

If you can provide me some feedback on how to manage this is really appreciated, thanks.

The related issue in Redmine is this one: http://redmine.gcgeo.gc.ca/redmine/issues/9156

Regards,
Jose García

**Comment by mweech** [comment]
Issue moved to [fgpv-vpgf/rcs #73](https://github.com/fgpv-vpgf/rcs/issues/73) via [**ZenHub**](https://www.zenhub.com/)
