### ISSUE TITLE
Config loaded twice

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2004]
Confirmed on: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html

Dev tools -> Network shows `config-mobile-2.json` loaded twice, back-to-back. This is likely unintentional.

Adds to overall bandwidth and likely reduces page load by ~300ms

**Comment by AleksueiR** [comment]
@milesap is this still a problem? I think you fixed it recently, right?

**Comment by milesap** [comment]
This is done :+1:
