### ISSUE TITLE
Datatable sort property doesn't seem to be applied when specified in the config

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2010]
When adding filters sections to the layer definition in the config, the `sort` property seems to be ignored.

__Affects:__ 2.0

**Comment by JahidAhmed** [comment]
The problem seems to be occurring [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/filters/filters-default.directive.js#L313).

The value returned on line 322 is not consistent with the value on line 313.
