### ISSUE TITLE
Legend incorrect width in IE full screen mode

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2014]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Enabling full screen mode causes the legend to become the entire width of the screen in IE.
Also effects the placement of the `Toggle Groups` and `Toggle Visibility` menus on click.

**Comment by AleksueiR** [comment]
Screenshots please.

**Comment by JahidAhmed** [comment]
This is while full screen.

![untitled](https://user-images.githubusercontent.com/9637542/27434263-25c4b176-5726-11e7-80a9-50cc5a4b91eb.jpg)

![untitled2](https://user-images.githubusercontent.com/9637542/27434315-55c86d9a-5726-11e7-9268-c131e6fb64e0.jpg)

**Comment by AleksueiR** [comment]
Can IE think it's in mobile layout?
P.S.: Why is everything _italic_?

**Comment by JahidAhmed** [comment]
That is weird, all the text is italicised, including Main Menu and Help Menu.

**Comment by AleksueiR** [comment]
@JahidAhmed I think you inherited italics from James :)
