### ISSUE TITLE
Removing filter from datatable error

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2015]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Opening up any layers datatable and removing filters (if no filter initially, will need to add a filter) results in: `TypeError: Cannot read property 'filter' of undefined` and displayed 'Processing...' at the bottom of the datatable indefinitely and sometimes does not update the table accordingly.

Closing and then re-opening the datatable will then update it correctly.

**Comment by jolevesq** [comment]
Not able to replicate since I solved #2036
