### ISSUE TITLE
Error parsing French accents

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2019]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Opening a datatable for any layer which has columns with French accents in them throws an error: 
`Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 8-8 [é] in expression [self.Catégorie.value].`

**Comment by AleksueiR** [comment]
More errors of the same type when adding http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/G%C3%A9ochronologie.csv.

> rv-main.js:95762 Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 11-29 ['échantillon.value] in expression [self.Num. d'échantillon.value].
http://errors.angularjs.org/1.6.4/$parse/lexerr?p0=Unterminated%20quote&p1=…29%20%5B'%C3%A9chantillon.value%5D&p2=self.Num.%20d'%C3%A9chantillon.value
    at rv-main.js:81303

**Comment by AleksueiR** [comment]
After looking at this some more with @JahidAhmed, we think it's better to use simplified column names for template data binding (some of the column names contain brackets and spaces which can't be valid identifiers at all).
