### ISSUE TITLE
Custom map key bindings broken/missing

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2022]
Some time ago we disabled ESRI map bindings with our own implementation since ESRI requires a mouse to hover over the map in order to pan. It seems ESRI key bindings are being used again.

Also, when using arrows to pan, error is thrown:
> Uncaught TypeError: Cannot read property 'extent' of undefined

**Comment by AleksueiR** [comment]
Likely it got turned off during the refactor.
