### ISSUE TITLE
Unable to test Metadata for structured Legends

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2024]
Tested build: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html

Metadata option for structured legends are non responsive. Please investigate as this feature cannot be tested in the current build.

![image](https://user-images.githubusercontent.com/18539315/27448842-491008b4-5754-11e7-97dc-304eb11c90fd.png)

**Comment by mweech** [comment]
please include metadata in at least one of the sample configs.

**Comment by barryytm** [comment]
I will include a sample config with metadata in my next PR.

**Comment by barryytm** [comment]
The XSL files for metadata were not included in the build, currently waiting for the files to be added in order to be included in samples configs.  Please see #2075 for more details.
