### ISSUE TITLE
North arrow color visibility

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2028]
This issue as been entered by Paul. H in Redmine ([Issue9954](http://redmine.gcgeo.gc.ca/redmine/issues/9957))

Description: The right side of the north arrow is barely visible. Try using the same colour as the left side (#6D6D6D) for the contour of the right side

**Comment by AleksueiR** [comment]
Something like this?
![](https://i.imgur.com/h0Uii0f.png)

I made the border black and the right side a little darker.

**Comment by phuppe** [comment]
The attached image does not render too well, but it seems to be what we would want.
