### ISSUE TITLE
Datagrid "Filter by Extent" function not working as expected

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2036]
Tested build: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html

Related to #884 

Filter by Extent option available in a datagrid is not filtering the data by the current extent.  Tried this on thematic maps with structured legends and also by importing a service layer. Please investigate

![image](https://user-images.githubusercontent.com/18539315/27546465-df9ae97a-5a60-11e7-9d76-e22f14477bf1.png)

**Comment by jolevesq** [comment]
All layers are esriFeature layerType even if they are esriDynamic. This cause problems with the filter by extent
