### ISSUE TITLE
Correct package issues in v1.7.0

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2042]
Release `v1.7.1` to resolve the following issues found in `v1.7.0`.

Missing help: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2041

Wrong version of geoApi included in build (should be using `v1.1.5`).

From gitter:

So I've found the cause of the issue. When the packaged builds of `v1.7.0` were made, it appears it used an incorrect version of geoApi.  How this happened I'm not sure.

The source code for `v1.7.0` points to this version.
`https://github.com/fgpv-vpgf/geoApi/raw/v1.1.5/dist/geoapi-1.1.5.tgz`

Looking at various files.

```
// geoapi v1.1.5 source
// also present in https://github.com/fgpv-vpgf/geoApi/raw/v1.1.5/dist/geoapi-1.1.5.tgz
api.mapManager = mapManager(esriBundle, api);


// refactor source.
// also is in the `core.js` for viewer v1.7.0 downloadable bundle
api.Map = esriMap(esriBundle, api);
```

The change from `mapManager` to `Map` was done by Aly as part of the refactor (the object now acts as a wrapper to the ESRI map, similar to what we did for the layers).
The error we see is when the source code tries to use the `mapManager` object on geoApi and fails because it does not exist in the version lurking inside `core.js`.

So unresolved is what version of geoApi was used when `v1.7.0` was generated...the code included only exists in `refactor` branch and the `v0.0.0-protoLR` tags of geoApi.  A new build will need to be made to fix it.

**Comment by AleksueiR** [comment]
Seems that only `fgpv-1.7.0-dev-samples` contain the wrong geoApi; the distribution package itself must be correct according to this Travis job: https://travis-ci.org/fgpv-vpgf/fgpv-vpgf/jobs/231170489

**Comment by milesap** [comment]
Please see: http://fgpv.cloudapp.net/demo/v1.7.0/prod/samples/index-mobile.html

This shows production loading. I uploaded the v1.7.0 files again from our cloud.
