### ISSUE TITLE
Align proj4 with Webpack, Jasmine, and Terraformer

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2044]
This issue refers to geoApi.

In `proj.js`, using `bower`, we would get at the `proj4` library using `const proj4 = require('proj4')`.

Upon switching to `webpack`, we need to do `const proj4 = require('proj4').default`.  This works fine when geoApi is consumed by the viewer.

When running `jasmine` tests on geoApi, the module load appears to do something different and you get a pile of errors indicating the `proj4` library doesn't have properties it should have.  If you revert back to using `const proj4 = require('proj4')`, `jasmine` is a happy camper but the viewer will error on startup.

Jahid found this thread https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15663 that seems to describe similar things. If you read through it it appears the problem lies with `webpack` behavior.

Furthermore, we have our [terraformer-proj4js library](https://github.com/RAMP-PCAR/terraformer-proj4js) that is using an older version of `proj4` than geoApi is.

1. Immediate step: disable all the problematic `jasmine` tests in geoApi, and tag them with an identical comment (so we can find them all later).
2. Figure out why `jasmine` behaves differently and determine if we can make it work
3. Consider updating `terraformer-proj4js` so it is using the same version of `proj4`.

**Comment by JahidAhmed** [comment]
All problematic tests have been declared pending and marked with a comment above the respective test:
`// post webpack: proj4 inconsistency`

**Comment by JahidAhmed** [comment]
Changes made in this PR for reference: https://github.com/fgpv-vpgf/geoApi/pull/233

**Comment by milesap** [comment]
proj4 merged ES6 modules in ~v2.4.0
https://github.com/proj4js/proj4js/pull/224#commitcomment-21236433

Node.js only supports AMD loading, so going forward
- tests are converted from ES6 to AMD through babel cli
- webpack will use ES6 as usual, while continuing support for AMD

Going forward, geoApi can start using ES6 module loading. AMD will continue to be supported. Will push geoApi PR shortly.
