### ISSUE TITLE
User added Air Ozone layer not visible on the viewer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2045]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily08/prod/samples/index-samples.html
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

Even the visibility check mark is checked, no zoom level map points are showed up on the viewer. This happened for every zoom levels.
![image](https://user-images.githubusercontent.com/18723160/27556062-19fe9564-5a82-11e7-824c-1a1818564639.png)

**Comment by AleksueiR** [comment]
WOMM:
![](https://i.imgur.com/eVEPaQw.png)

**Comment by milesap** [comment]
Works for me as well

**Comment by JahidAhmed** [comment]
Working on my machine also

**Comment by AleksueiR** [comment]
@IsabellaPan Can you retest please?

**Comment by IsabellaPan** [comment]
@AleksueiR It works this morning. 
But it seems only happening in the afternoon on certain week day - at the time every step of importing service was responding very slower.

**Comment by AleksueiR** [comment]
This service is know to fails in weird ways - properly loading only once in three tries. It's likely this is the cause.

**Comment by mweech** [comment]
service issue.
