### ISSUE TITLE
Rename filter to be a grid-specific term

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2051]
Up until now we have been using the word `filter` to describe the grid in code. Now that we have actual filters in the grid, the terminology is becoming awkward. We should do a rename across the whole app (config schema, file names, object names, documentation) to something like `grid`, `table`, `datagrid`

- [x] Determine what the new name / term should be.
- [x] Update the config schema
- [x] Update code references to schema / object names
- [x] Update file names in the application
- [x] Update technical documentation / help
- [x] Update any tests

This should be done after https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2050 , and ideally at a time where there is no other major development happening on the impacted areas of the code.

**Comment by milesap** [comment]
I like **grid** or **table**, two fine choices. Any other suggestions?
