### ISSUE TITLE
Full screen IE menu placement

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2052]
When in full screen mode and one of the menu options is clicked from the legend panel, the placement of the menu appears to the left and not beside the button itself.

![](https://user-images.githubusercontent.com/9637542/27588618-cc2b9a54-5b16-11e7-90da-c6ce20de28bf.JPG)

**Comment by milesap** [comment]
ie dev tools is "non-functional" (to put it nicely),  especially on my machine. There is no way for me to address this issue without it.

**Comment by milesap** [comment]
Looks like this fixed itself :+1: please re-test (womm)

**Comment by JahidAhmed** [comment]
Seems to still be broken on my machine. 
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

**Comment by AleksueiR** [comment]
Yeap, same happens on my machine as well.

**Comment by milesap** [comment]
try on `index-sample.html`, I've learned my lesson from opening `index-mobile.html` in IE

**Comment by AleksueiR** [comment]
:+1:  that's what I'm doing :)

**Comment by milesap** [comment]
Strange, not sure why it works for me but not you two. Assigning to @JahidAhmed for further investigation. 

I've looked at Angular Material menu demos in ie fullscreen and they work well. Check if they are broken on your machine first. https://material.angularjs.org/latest/demo/menu then F11 to fullscreen.

**Comment by AleksueiR** [comment]
Does the datatable menu works for you as well?

**Comment by milesap** [comment]
Yeah

**Comment by AleksueiR** [comment]
Are you sure it's IE? :smile:

**Comment by JahidAhmed** [comment]
The menus work fine in `index-samples.html` but not `index-mobile.html` for me also

**Comment by AleksueiR** [comment]
I don't know what is going on. I thought it might be related to how we implement full screen, but I can't find what is broken.

If you press `F11` to enter the regular full-screen mode, all menus work correctly, but they are broken when you switch to full-screen from inside the viewer. Something about expanding `rv-shell` node breaks menu positioning, but I can't understand what.
