### ISSUE TITLE
Step 2 Continue button not responding while importing CSV and GeoJSON files

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2053]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html
Test data: 
1. happy.json 
2. rc_cdr.csv

Clicking below Continue button has no responses.
![image](https://user-images.githubusercontent.com/18723160/27594290-62458db4-5b27-11e7-8f53-b3716402c605.png)

**Comment by AleksueiR** [comment]
I get the following error:
![](https://i.imgur.com/sSpvJS5.png)

I suspect some polyfill is missing. Maybe Babel polyfills do not cover something that we used before which was removed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2033.

@milesap can you check please?
