### ISSUE TITLE
User-added layer cannot be reloaded

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2056]
Tested build :http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html

Test data: Any feature or dynamic layer including WMS layer
Related issue #1969 

Map points are hidden in the viewer whenever a layer is reloaded. A similar issue was reported for layers in a visibility set.  Visibility set layers work fine. However other layers added through the wizard seem to have similar issue. Please investigate

**Comment by AleksueiR** [comment]
This applies only to user-added layers, correct?

**Comment by AleksueiR** [comment]
Ok, seems you cannot reload a user-added layer at all.

**Comment by AleksueiR** [comment]
- all used-added layers are now added at the top of their respective sort group, as opposed to at the bottom as was done previously; this is useful when adding layers to a structured legend since you can't reorder layers afterwards.
