### ISSUE TITLE
Missing images in Help

### ISSUE THREAD

**Issue by phuppe** [fgpv-vpgf/fgpv-vpgf#2057]
Here is the list of the missing images for the Help:

- Failed to load resource: the server responded with a status of 404 (Not Found) fullscreen.png
- Failed to load resource: the server responded with a status of 404 (Not Found) zoomout.png
- Failed to load resource: the server responded with a status of 404 (Not Found) geolocation.png
- Failed to load resource: the server responded with a status of 404 (Not Found) canada.png
- Failed to load resource: the server responded with a status of 404 (Not Found) help.png
- Failed to load resource: the server responded with a status of 404 (Not Found) toggle.png
- Failed to load resource: the server responded with a status of 404 (Not Found) menu.png
- Failed to load resource: the server responded with a status of 404 (Not Found) layers.png
- Failed to load resource: the server responded with a status of 404 (Not Found) basemap.png
- Failed to load resource: the server responded with a status of 404 (Not Found) fullscreen.png
- Failed to load resource: the server responded with a status of 404 (Not Found) export.png
- Failed to load resource: the server responded with a status of 404 (Not Found) share.png
- Failed to load resource: the server responded with a status of 404 (Not Found) touch.png
- Failed to load resource: the server responded with a status of 404 (Not Found) help.png
- Failed to load resource: the server responded with a status of 404 (Not Found) language.png
- Failed to load resource: the server responded with a status of 404 (Not Found) scale.png
- Failed to load resource: the server responded with a status of 404 (Not Found) zoom.png
- Failed to load resource: the server responded with a status of 404 (Not Found) ellipses.png
- Failed to load resource: the server responded with a status of 404 (Not Found) metadata.png
- Failed to load resource: the server responded with a status of 404 (Not Found) settings.png
- Failed to load resource: the server responded with a status of 404 (Not Found) datatable.png
- Failed to load resource: the server responded with a status of 404 (Not Found) layer.png
- Failed to load resource: the server responded with a status of 404 (Not Found) zoomto.png
- Failed to load resource: the server responded with a status of 404 (Not Found) reload.png
- Failed to load resource: the server responded with a status of 404 (Not Found) remove.png
- Failed to load resource: the server responded with a status of 404 (Not Found) menu.png
- Failed to load resource: the server responded with a status of 404 (Not Found) add.png
- Failed to load resource: the server responded with a status of 404 (Not Found) reorder.png
- Failed to load resource: the server responded with a status of 404 (Not Found) expand.png
- Failed to load resource: the server responded with a status of 404 (Not Found) view.png

**Comment by AleksueiR** [comment]
Help markdown files and images are added to [1.7.0 release](https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/v1.7.0).

**Comment by phuppe** [comment]
All good now. thanks.
