### ISSUE TITLE
Can't Load File on a Server

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2061]
http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html

Attempting to use the URL option when adding a File, and using this server-based file
http://maps-cartes.dev.ec.gc.ca/sandbox/EcoGeo2/happyEnhance.json

Gives the error (split over two lines for reading)
`loaderFileDirective problem retrieving file link with error`
`TypeError: _loadFileData(...).then is not a function`

Likely [code location of issue](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.0.0-daily09/src/app/ui/loader/layer-source.service.js#L346)

**Comment by AleksueiR** [comment]
Found one issue: `_loadFileData` was not returning a promise if the file loaded does not have an HTML5 file object. But then it fails while parsing JSON:
> SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (<anonymous>)
    at Object.geojson (rv-main.js:171099)
    at Object.validateFile (rv-main.js:171108)

Looking at the network tab, it looks like geoApi tries to load the file over wmsproxy:
> http://167.40.64.74/wmsproxy/ws/wmsproxy/executeFromProxy?http://maps-cartes.dev.ec.gc.ca/sandbox/EcoGeo2/happyEnhance.json

with the following result:
```xml
<ServiceExceptionReport version="1.1.1">
<ServiceException>
The URL http://maps-cartes.dev.ec.gc.ca/sandbox/EcoGeo2/happyEnhance.json? cannot be read
</ServiceException>
</ServiceExceptionReport>
```

**Comment by james-rae** [comment]
[getServerFile](https://github.com/fgpv-vpgf/geoApi/blob/v0.0.0-protoLR-75/src/layer.js#L67) is in geoApi, and all webcalls in geoApi go through the esri web request library. And that has the proxy initialized on it.

I'm not sure if this is the thing we control that has whitelistings of stuff on it?

Possible solutions

* If we can, add file types to our whitelist `(.json, .zip, .csv)`
* Attempt to do some nonsense like temporarily removing the proxy setting from ESRI API prior to making this call, then restore it after (synchronously, not on on asynch result)

**Comment by AleksueiR** [comment]
We can also load these files in the client, like the local files are loaded.

**Comment by AleksueiR** [comment]
Trying to load files from a place without proper CORS settings will fail.

**Comment by AleksueiR** [comment]
Sample data for testing is here: http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/
