### ISSUE TITLE
Download export map - missing Footnote

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2062]
Tested build:  http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html

Footnote check mark is checked under map export settings.
![image](https://user-images.githubusercontent.com/18723160/27605413-9faa5ae0-5b4a-11e7-8a56-f9d67a298a32.png)

**Comment by AleksueiR** [comment]
What config number was that?

**Comment by IsabellaPan** [comment]
@AleksueiR Not sure if it is related to sample file?
I could see this happened with couple of sample files, for example: 01.Layer with visibility sets and 05. Nested visibility sets

**Comment by AleksueiR** [comment]
I was wonder if the config file specified the footnote in the first place. `config 1` does, so it's likely a bug.

**Comment by AleksueiR** [comment]
Turned out there was a bug that disregarded all config export options and use defaults only. :confounded:

**Comment by IsabellaPan** [comment]
Config file has footnote included, see below:
![image](https://user-images.githubusercontent.com/18723160/27650396-d8d825d2-5c02-11e7-80f6-e1d3705e17b0.png)

**Comment by AleksueiR** [comment]
Yes, that's the point - the default footnote is blank, and the app just used the defaults, which will give you everything except for the bookmark. 

Actually, the export image using this config should be only the footnote, since it's the only thing specified in the config.
![](https://i.imgur.com/yj9bIzJ.png)
I'll fix the bug, and then we need to update config files to include more export elements.

**Comment by IsabellaPan** [comment]
Do you mean all the rest under setting, like north arrow, time stamp, scale, title, basemap, etc. shouldn't be included at all? :)

**Comment by AleksueiR** [comment]
It depends on the config file you are using. If you are talking about `config-1`, then yes, north arrow, time stamp, scale, title, basemap, etc. won't be included at all.
And again, the config is very flexible and we provide a lot of options to to whoever designs a map and makes a config for it. Some cases might seem ridiculous, like having only footnote as your export image, and it's up to the config author to make sensible configs.
