### ISSUE TITLE
Coordinates missing in Full Screen mode

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2063]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html

![image](https://user-images.githubusercontent.com/18723160/27607597-5f89579c-5b52-11e7-800f-d74d05fdcd73.png)

**Comment by JahidAhmed** [comment]
Cannot reproduce, WOMM
