### ISSUE TITLE
Parent values under settings not fully propagated to children for dynamic layers

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2071]
Tested build:http://fgpv.cloudapp.net/demo/v2.0.0-daily10/prod/samples/index-samples.html

Test data:http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer

"Query" value defined in the Parent layer does not seem to propagate to the children. Visibility and Opacity features are working as expected. However when you toggle query to the "off" position, sub layers still seem to have that in the "on" position. Please investigate

Please note that this was tested for user added layers and structured legends

**Comment by AleksueiR** [comment]
When reporting bugs on `index-samples` page, please, indicate which config file was used.
