### ISSUE TITLE
Geo Search Text box does not take numbers entering from number keypad, instead move map to different directions

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2072]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily10/prod/samples/index-samples.html

When user tried to do a Geo Search For scale (need to start with 1: followed by number or spaces, like 1:100000), it turned out the number entered on number keypad from 1 to 9 (except 5) were not taken in the Search box, instead entering different numbers just moved the map to different directions.
It only takes number "5".

![image](https://user-images.githubusercontent.com/18723160/27652200-e87911a8-5c08-11e7-83c7-af5847ad7a1f.png)

**Comment by AleksueiR** [comment]
Can you check if you have NumLock enabled? It makes numpad keys work as arrow keys.

**Comment by milesap** [comment]
I'm assuming this isn't a NumLock issue, might be related to the key binding issue I'm working on #2022
