### ISSUE TITLE
Map click still displaying Feature Details results when query is disabled

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2073]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily10/prod/samples/index-samples.html

- Go to Settings for Electric Transmission Line child layer to disable data query
- Click on any map point for this layer

It still brings Feature Details result for the map point, even there is an icon with tooltip to say "Layer will be excluded from map click results" appearing for the layer.
![image](https://user-images.githubusercontent.com/18723160/27658790-2e0a4456-5c1f-11e7-9e61-5cf6dde53cdd.png)
![image](https://user-images.githubusercontent.com/18723160/27658569-7c322a32-5c1e-11e7-80e9-11b54bef09ca.png)

**Comment by barryytm** [comment]
It was disabled when I tried it.

![capture2](https://user-images.githubusercontent.com/19259169/27659225-aca8ecd0-5c20-11e7-985c-6a48242fae2c.PNG)


![capture](https://user-images.githubusercontent.com/19259169/27659172-8ab16602-5c20-11e7-88c4-d41a6e44b740.PNG)

**Comment by IsabellaPan** [comment]
It seems this issue cannot be reproduced this morning. Closed.
