### ISSUE TITLE
"Remove" option not available for user added layers in a thematic map

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2078]
Tested build: http://fgpv.cloudapp.net/demo/users/barryytm/1786-legend-samples/prod/samples/index-samples.html

"Remove" option is not available for user added layers when it is added to a thematic map. Please investigate

![image](https://user-images.githubusercontent.com/18539315/27701615-6d9bd458-5ccf-11e7-9afe-889e13c78d96.png)

**Comment by AleksueiR** [comment]
User-added layers can now be removed even from the structured legend.
