### ISSUE TITLE
Integrated Data Catalogue Search

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#208]
Modify existing User Added Layers component to allow for addition of layers via a catalogue search without navigating away from the viewer.
- [ ] Consume Data catalogue search service
- [ ] Wire up catalogue search to UI

Traceability Matrix ID#042

Jose from GeoCat offers the following:
The search service is described in http://geonetwork-idx.geocat.net/geonetwork/doc/api/index.html#metadata-search, see parameters and examples. There's a fast parameter (boolean) that indicates to return a simplified version or a full version of the xml.

Also this service http://geonetwork-idx.geocat.net/geonetwork/doc/api/index.html#metadata-retrieve allows to retrieve the xml from the uuid.

[This URL is behind a username and password, so here is the Search Service documentation]:
## Metadata search

The **q** service can be used to retrieve metadata records from GeoNetwork.

Requires authentication: Optional

Request

Search configuration parameters (all values are optional):
- **from**: Initial record to return.
- **to**: Final record to return (if not specified, a maximum of 1000 records are returned)
- **hitsPerPage**: Results per page (default: 10)
- **similarity**: Lucene accuracy for searches (default 0.8)
- **sortBy**: Sorting criteria. Values: relevance (default), rating, popularity, changeDate, title
- **fast**: Indicates to use fast mode (index only) that returns a subset of the metadata information or no fast mode, to return the full xml (default true).

Search parameters (all values are optional):
- **eastBL, southBL, northBL, westBL**:
  Bounding box to restrict the search
- **relation**: Bounding box criteria.
  Values: equal, overlaps (default), encloses, fullyOutsideOf,
  intersection, crosses, touches, within
- **any**: Text to search in a free text search
- **title**: Metadata title
- **abstract**: Metadata abstract
- **themeKey**: Metadata keywords. To search for several use a value like "Global" or "watersheds"
- **template**: Indicates if search for templates or not. Values: n (default), y
- **dynamic**: Map type. Values: off (default), on
- **download**: Map type. Values: off (default), on
- **digital**: Map type. Values: off (default), on
- **paper**: Map type. Values: off (default), on
- **group**: Filter metadata by group, if missing search in all groups
- **dateFrom**: Filter metadata created after specified date
- **dateTo**: Filter metadata created before specified date

Request to search for all metadata example::

  Url:
  http://localhost:8080/geonetwork/srv/eng/q

  Mime-type:
  application/xml

  Post request:
  <?xml version="1.0" encoding="UTF-8"?>
  <request />

Request to search for all metadata example, returning full metadata xml::

  Url:
  http://localhost:8080/geonetwork/srv/eng/q?fast=false

  Mime-type:
  application/xml

  Post request:
  <?xml version="1.0" encoding="UTF-8"?>
  <request />

Request with free text search example::

  Url:
  http://localhost:8080/geonetwork/srv/eng/q

  Mime-type:
  application/xml

  Post request:s
  <?xml version="1.0" encoding="UTF-8"?>
  <request>
    <any>africa</any>
  </request>

Request with a geographic search example::

  Url:
  http://localhost:8080/geonetwork/srv/eng/q

  Mime-type:
  application/xml

  Post request:
  <?xml version="1.0" encoding="UTF-8"?>
  <request>
    <any>africa</any>
    <eastBL>74.91574</eastBL>
    <southBL>29.40611</southBL>
    <northBL>38.47198</northBL>
    <westBL>60.50417</westBL>
    <relation>overlaps</relation>
    <sortBy>relevance</sortBy>
  </request>

Request to search using dates and keywords example::

  Url:
  http://localhost:8080/geonetwork/srv/eng/q

  Mime-type:
  application/xml

  Post request:
  <?xml version="1.0" encoding="UTF-8"?>
  <request>
    <title>africa</title>
    <themekey>"Global" or "World"</themekey>
    <dateFrom>2000-02-03T12:47:00</dateFrom>
    <dateTo>2010-02-03T12:49:00</dateTo>
  </request>

Response

```

The response is the metadata record with additional
**geonet:info** section. The main fields are:

- **response**: Response container.

  - **summary**: Attribute
    **count** indicates the number of metadata records retrieved

    - **keywords**: List of keywords
      that are part of the metadata resultset. Each keyword
      contains the value and the number of occurences in the
      retrieved metadata records.

  - **metadata**: Container for
    each metadata record found.  Each container has a
    **geonet:info** element with the
    following information:

      - **id**: Metadata internal
        identifier
      - **uuid** : Metadata
        Universally Unique Identifier (UUID)
      - **schema**: Metadata
        schema
      - **createDate**: Metadata
        creation date
      - **changeDate**: Metadata last
        modification date
      - **source**: Source catalogue
        the metadata

Metadata search response example (fast mode)::

  <?xml version="1.0" encoding="UTF-8"?>
  <response from="1" to="7">
    <summary count="7" type="local">
      <keywords>
        <keyword count="2" name="Global"/>
        <keyword count="2" name="World"/>
        <keyword count="2" name="watersheds"/>
        <keyword count="1" name="Biology"/>
        <keyword count="1" name="water resources"/>
        <keyword count="1" name="endangered plant species"/>
        <keyword count="1" name="Africa"/>
        <keyword count="1" name="Eurasia"/>
        <keyword count="1" name="endangered animal species"/>
        <keyword count="1" name="Antarctic ecosystem"/>
      </keywords>
    </summary>
    <metadata xmlns:gmx="http://www.isotc211.org/2005/gmx">
      <geonet:info xmlns:geonet="http://www.fao.org/geonetwork">
        <id>12</id>
        <uuid>bc179f91-11c1-4878-b9b4-2270abde98eb</uuid>
        <schema>iso19139</schema>
        <createDate>2007-07-25T12:05:45</createDate>
        <changeDate>2007-11-06T12:10:47</changeDate>
        <source>881a1630-d4e7-4c9c-aa01-7a9bbbbc47b2</source>
      </geonet:info>
    </metadata>
    <metadata xmlns:gmx="http://www.isotc211.org/2005/gmx">
      <geonet:info xmlns:geonet="http://www.fao.org/geonetwork">
        <id>11</id>
        <uuid>5df54bf0-3a7d-44bf-9abf-84d772da8df1</uuid>
        <schema>iso19139</schema>
        <createDate>2007-07-19T14:45:07</createDate>
        <changeDate>2007-11-06T12:13:00</changeDate>
        <source>881a1630-d4e7-4c9c-aa01-7a9bbbbc47b2</source>
      </geonet:info>
    </metadata>
    ...
  </response>

Metadata search response example (no fast mode)::

 <?xml version="1.0" encoding="UTF-8"?>
  <response from="1" to="7">
    <summary count="7" type="local">
      <keywords>
        <keyword count="2" name="Global"/>
        <keyword count="2" name="World"/>
        <keyword count="2" name="watersheds"/>
        <keyword count="1" name="Biology"/>
        <keyword count="1" name="water resources"/>
        <keyword count="1" name="endangered plant species"/>
        <keyword count="1" name="Africa"/>
        <keyword count="1" name="Eurasia"/>
        <keyword count="1" name="endangered animal species"/>
        <keyword count="1" name="Antarctic ecosystem"/>
      </keywords>
    </summary>
    <gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:srv="http://www.isotc211.org/2005/srv"
      xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:xlink="http://www.w3.org/1999/xlink"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gfc="http://www.isotc211.org/2005/gfc"
      xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gmi="http://www.isotc211.org/2005/gmi"
      xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmx="http://www.isotc211.org/2005/gmx"
      xmlns:napm="http://www.geoconnections.org/nap/napMetadataTools/napXsd/napm"
      xmlns:napec="http://www.ec.gc.ca/data_donnees/standards/schemas/napec" xmlns:geonet="http://www.fao.org/geonetwork">
      <gmd:fileIdentifier>
        <gco:CharacterString>bc179f91-11c1-4878-b9b4-2270abde98eb</gco:CharacterString>
      </gmd:fileIdentifier>
      ...
    </gmd:MD_Metadata>
    <gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:srv="http://www.isotc211.org/2005/srv"
    xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gfc="http://www.isotc211.org/2005/gfc"
    xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gmi="http://www.isotc211.org/2005/gmi"
    xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmx="http://www.isotc211.org/2005/gmx"
    xmlns:napm="http://www.geoconnections.org/nap/napMetadataTools/napXsd/napm"
    xmlns:napec="http://www.ec.gc.ca/data_donnees/standards/schemas/napec" xmlns:geonet="http://www.fao.org/geonetwork">
      <gmd:fileIdentifier>
        <gco:CharacterString>5df54bf0-3a7d-44bf-9abf-84d772da8df1</gco:CharacterString>
      </gmd:fileIdentifier>
    </gmd:MD_Metadata>
    ...
  </response>


Metadata retrieve
-----------------

The `xml.metadata.get` service can be used to retrieve a metadata record stored in GeoNetwork.

Request
```

_One_ of the following parameters is required:
- **uuid** : Metadata Universal Unique Identifier (UUID)
- **id**: Metadata internal identifier

Get metadata request example::

  Url:
  http://localhost:8080/geonetwork/srv/en/xml.metadata.get

  Mime-type:
  application/xml

  Post request:
  <?xml version="1.0" encoding="UTF-8"?>
  <request>
    <uuid>aa9bc613-8eef-4859-a9eb-4df35d8b21e4</uuid>
  </request>

Response

```

Successful response (HTTP status code 200) is the XML metadata record with additional **geonet:info** section. The principal fields for **geonet:info** are:

- **schema**: Metadata schema

- **createDate**: Metadata creation date

- **changeDate**: Metadata last modification date

- **isTemplate**: Indicates if the metadata returned is a template

- **title**: Metadata title

- **source**: Source catalogue the metadata

- **uuid** : Metadata Universally Unique Identifier (UUID)

- **isHarvested**: Indicates if the metadata is harvested

- **popularity**: Indicates how often the record is retrieved

- **rating**: Average rating provided by users

- State of operation on metadata for the user: view, notify, download, dynamic, featured, edit

- **owner**: Indicates if the user that executed the service is the owner of metadata

- **ownername**: Metadata owner name

Get metadata response example::

  <?xml version="1.0" encoding="UTF-8"?>
  <gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco">
    <gmd:fileIdentifier>
      <gco:CharacterString>aa9bc613-8eef-4859-a9eb-4df35d8b21e4</gco:CharacterString>
    </gmd:fileIdentifier>
    ...
    <geonet:info>
      <id>10</id>
      <schema>iso19115</schema>
      <createDate>2005-08-23T17:58:18</createDate>
      <changeDate>2007-03-12T17:49:50</changeDate>
      <isTemplate>n</isTemplate>
      <title />
      <source>881a1630-d4e7-4c9c-aa01-7a9bbbbc47b2</source>
      <uuid>aa9bc613-8eef-4859-a9eb-4df35d8b21e4</uuid>
      <isHarvested>n</isHarvested>
      <popularity>0</popularity>
      <rating>0</rating>
      <view>true</view>
      <notify>true</notify>
      <download>true</download>
      <dynamic>true</dynamic>
      <featured>true</featured>
      <edit>true</edit>
      <owner>true</owner>
      <ownername>admin</ownername>
      <subtemplates />
    </geonet:info>
  </gmd:MD_Metadata>

Error response (HTTP 500 status code) is an XML document with the details of what
went wrong. An example of such a response is as follows::

 <error id="operation-not-allowed">
   <message>Operation not allowed</message>
   <class>OperationNotAllowedEx</class>
   .....
 </error>

See :ref:`exception_handling` for more details.

Errors
```
- **Request must contain a UUID or an ID**, if a uuid or id parameter was not provided. Returns 500 HTTP code
- **Operation not allowed (error id:
  operation-not-allowed)**, when the user is not allowed
  to view the metadata record. Returns 500 HTTP code

**Comment by mweech** [comment]
This issue may be pushed into the R3 scope in favor of a more direct & temporary "back to cart" button.

**Comment by mweech** [comment]
This would be implemented outside of the Viewer itself in the containing WET page.  May not be in scope for the viewer specifically.

**Comment by mweech** [comment]
Has been years since this was last discussed as a priority.  A plugin will accomplish this in the future if it becomes a requirement for a particular project.
