### ISSUE TITLE
Datatable filter elements duplicate and follow the mouse

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2082]
Tested build:http://fgpv.cloudapp.net/demo/users/barryytm/1786-legend-samples/prod/samples/index-samples.html

Related #884 

When highlighting text in the grid filter field using the mouse, the browser begins an element drag-and-drop animation and the filter elements duplicate and follow the mouse.

**Comment by JahidAhmed** [comment]
Similar issue: https://datatables.net/forums/discussion/41156/problems-using-column-filter-input-field-with-ordering-true-and-colreorder-true

Since the filters are in the table header, when trying to reorder columns, the entire header is selected and thus resulting in this behaviour.

**Comment by JahidAhmed** [comment]
After attempting a few different methods and some discussion with @AleksueiR and @jolevesq, the most feasible fix was to disable reordering by method of drag-and-drop.
