### ISSUE TITLE
Data Table (user added CSV file) - Double OBJECTID columns, one has double rows min & max filter text box

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2083]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily10/prod/samples/index-samples.html
Test data: rc_cdr.csv (already sent to James)

After added the above test data, the Data Table contained two columns of ObjectID, the 1st has double rows "min & max" filter text box, the 2nd one doesn’t have. And if I enter number to the 1st row of filter, the 2nd row filter automated repeated the number entered.
By checking the filter settings, it also has two ObjectID columns as the 2nd screenshot below.

Discussion with James:
"It looks like two bugs to me.
First is the duplicate column names.  I believe there is a reason for the duplication, but the title of the second one is supposed to be changed to something like ORIG_OBJECTID.
The second is the formatting / positioning of the min & max.  My guess is this will be fixed when the column names are corrected – it’s searching for the column to add the filter by name, and since they have same name, it finds the first column both times."

![image](https://user-images.githubusercontent.com/18723160/27705580-5af39c16-5cdc-11e7-9e70-cae9e4ec622e.png)
![image](https://user-images.githubusercontent.com/18723160/27705598-6d6ee990-5cdc-11e7-8c6e-45e9d63ae857.png)

**Comment by james-rae** [comment]
[Relevant code](https://github.com/fgpv-vpgf/geoApi/blob/v0.0.0-protoLR-73/src/layer.js#L803) for duplicating `OBJECTID` in file-based layers

**Comment by james-rae** [comment]
Wizard was passing in all fields on the customize field option.  Rather than hack the wizard, just removed the custom option (as we are not using it for custom fields).

Considered ready for testing once geoApi `v0.0.0-protoLR-79` is consumed by the viewer
