### ISSUE TITLE
bug(core): check lat/long are actual numbers;

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#209]
Relevant to RAMP code we plan to steal.

Converter may fail if fields contain other symbols. Try to get rid of them; display a meaningful error otherwise.

TODO: make a sample file

**Comment by AleksueiR** [comment]
Duplicate #210

**Comment by cynngah** [comment]
Implemented function to check whether or not lat/long are actual numbers in layer.js, but still need to implement front end where user selects which columns specify lat/long to be able to use said function.
