### ISSUE TITLE
Bookmarks are not working after a user added layer is imported

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2095]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily11/prod/samples/index-samples.html

**Steps to Reproduce**

Load the samples site. Make sure sample site  is loaded properly with map points(sample15)
Add a user added layer
Use the "Share" function for bookmarking
Paste the url is the bookmark field
Blank map with no points loads

Expected result: Points in the sample file should load

Unable to test in IE

![image](https://user-images.githubusercontent.com/18539315/27837219-02ef755c-60b1-11e7-860c-b712c315fa84.png)

**Comment by AleksueiR** [comment]
Turned out, this was broken by implementation of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2056. Should be working as expected now.
