### ISSUE TITLE
Layer with symbology overridden by config file (config sample 18) not working in Mercator projection

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2099]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

Overridden is not working switching to Mercator map. There is a yellow exclamation mark saying "cannot display layer in the current projection".

![image](https://user-images.githubusercontent.com/18723160/27840188-0ac32846-60c5-11e7-8c2c-75664cb495db.png)

**Comment by barryytm** [comment]
It should not work on Mercator projection since the layer is only works on `ESPG:3978` (Lambert Conformal Conic projection).  

For more info: http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBME_CBCE_HS_RO_3978/MapServer

**Comment by james-rae** [comment]
According to Alex, the missing symbology is by design. The user gets the frowny face to indicate the problem.
