### ISSUE TITLE
User Added Layers: Improve error handling and provide meaningful error messages

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#210]
Currently, when a service fails to import, the User Added Layers function will provide a generic message indicating "Incorrect file format".  This message is relatively vague, and it may help for a more specific error message to be provided if available.  The error message should also direct the user to the help file for guidance, which should be updated with some basic guidance on the expected file formats (i.e. CSV files and lat/long column expectations, shapefiles must be zipped, etc).

Acceptance criteria: 
- Error message is expanded and more meaningful.
- Help file is updated with better instructions for file formats.

Original post by @dan-bowerman :

Gitter.im conversation regarding CSV import failing in R1 Viewer:

AleksueiR 11:36
In R2, should we expect properly formatted csvs and other files? If this is something that can happen often, we might try preparsing lat/long fields to get rid of strange characters.

alyec 11:36
Can we leave a note somewhere: either bug report against RAMP or some task in R2 to have a look at FileReader and csv2geojson to check where the parser is messing up?

dan-bowerman 11:36
No, I would always put the emphasis on clean data on the data providers.

james-rae 11:37
filth in, filth out  

AleksueiR 11:37
Then a more meaningful error would be helpful.

alyec 11:38
@dan-bowerman generally agree, but we can probably do something better than crash. And it might even be as simple as updated the csv2geojson library.

dan-bowerman 11:38
I'll file it as an issue, but it should be low low priority right now. At least till we're ready to implement the file based layers.

alyec 11:40
Agreed, I just want to put the issue somewhere so we check. And at least make sure all the FileReader type calls are wrapped in proper error checking.

**Comment by AleksueiR** [comment]
Ideally, error messages for malformed csv/json files should provide enough details for the user to fix the error.
