### ISSUE TITLE
Raster layers are added as dynamic layers with datatable flag in the Legend Panel

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2104]
Tested build : http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

test data:
http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/0
![image](https://user-images.githubusercontent.com/18539315/27870029-b5112384-616f-11e7-97de-8a1925d55a8f.png)

![image](https://user-images.githubusercontent.com/18539315/27870138-1743f91e-6170-11e7-83f4-364a308fc4b3.png)

This layer was added through the Layer wizard as a dynamic layer. The layer is a raster layer with no data. However, the legend panel displays data table flag which may confuse the users. Please remove this flag for layers without data.

**Comment by AleksueiR** [comment]
Please be aware that #2076 is still happening. This is an issue caused by #1965 and will be solved later.
