### ISSUE TITLE
IE 11 - All buttons within viewer frozen after zooming out to scale 1000km/1000mi

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2105]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

This issue is for Lambert projection only. All buttons in tool bar are not responding after zooming out to 1000km/1000mi, including all buttons on top of the viewer (menu, Geo Search, legend, bookmark, etc.)

![image](https://user-images.githubusercontent.com/18723160/27873040-bcac9a48-6178-11e7-895d-3952c32bd871.png)

**Comment by AleksueiR** [comment]
@JahidAhmed had found that IE was chocking on drawing the snowman svg icon (zoom out too far, and the north poll comes into view). The icon is fixed; snowman, defanged.
