### ISSUE TITLE
"Apply to Map" feature in  datatables not working as expected for certain layers

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2106]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

Test data: http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0     
                 http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_SO2/MapServer

Related #884 

"Apply to Map" feature does not filter the points to display the filtered data for layers from config file or user added layers consistently. This feature cannot be seen in the datatable with some dynamic layers. Please investigate

![image](https://user-images.githubusercontent.com/18539315/27876553-87366530-6185-11e7-8ba6-8c977c0658be.png)

**Comment by mweech** [comment]
@jolevesq plz estimate
