### ISSUE TITLE
Ability to turn on/off geosearch from the config file

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2108]
FGPV is being used for a map that is a collaboration between Canada, the US and Mexico. Since our geosearch only has canadien data, the group would like to turn off geosearch.

Would it be possible to make it configurable in the config file?

Thanks,

**Comment by milesap** [comment]
Version 2.0 will have this available under config `map -> components -> geoSearch -> enabled = false`.

**Comment by AleksueiR** [comment]
It seems 1.7 schema also supports turning geosearch off: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/schema.json#L778

**Comment by milesap** [comment]
Schema supports it but the viewer doesn't :smile: support was merged into v2.0
