### ISSUE TITLE
Ability to change Viewer name and logo

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2109]
As we get more departments using the viewer, we are now getting requests to change the logo and viewer name title (currently: FGP R2 Viewer).

Would it be possible to make this configurable through the config file?

**Comment by milesap** [comment]
The logo can be changed in the config via `ui -> logoUrl`

The viewer name can be changed inside `translations.csv` under `sidenav.title`. Maybe this should be moved into the config instead (since you'd need to re-build the viewer for translations to be bundled)

**Comment by AleksueiR** [comment]
I thought we implemented title change long time ago... This should definitely be added to the config.
