### ISSUE TITLE
Bounding box is not visible in Bookmarks even when it is enabled in settings

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2111]
Tested build :http://fgpv.cloudapp.net/demo/v2.0.0-daily13/prod/samples/index-samples.html

**Steps to reproduce**

Enable bounding box for a layer
Use "Share" to create a bookmark
Paste the bookmark link in the bookmark field
Viewer loads without bounding box even though this feature is enabled under "settings"

![image](https://user-images.githubusercontent.com/18539315/27912798-15d5a44e-622c-11e7-8900-eb5a9f6e4cac.png)

**Comment by AleksueiR** [comment]
I think this might be related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2102.

**Comment by milesap** [comment]
Can't fix until post 2.0 as this would invalidate all v1.x bookmarks

**Comment by mweech** [comment]
This bug will be eliminated once an overhaul of state storage/bookmarks occurs.
