### ISSUE TITLE
User may not know how to exit toggle filter settings menu in a data grid 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2123]
A user could find it confusing to exit out of these settings. Can we make this more intuitive

![image](https://user-images.githubusercontent.com/18539315/27926368-33d044e8-6256-11e7-9e76-99dce92fc707.png)

**Comment by milesap** [comment]
I agree this is confusing. Both the close button and pressing escape close the grid, and re-opening the grid brings you back to the filters.

**Comment by JahidAhmed** [comment]
I've made that mistake more than a few times

**Comment by AleksueiR** [comment]
I agree with you guys - the close button should close the filters overlay, not the datatable itself. The datatable menu and global search can also be hidden when the filters overlay is open. Here's original mockup:

![a04 - sets - layer data - filters](https://user-images.githubusercontent.com/2285779/28066851-b0970cd2-660c-11e7-9229-8e14393146f1.png)

**Comment by mweech** [comment]
we should tackle these changes.  especially making the filters dialog completely overlay the datagrid dialog.  it looks odd the way it is now.  will have to be v2.1 from a timeline pov though.

**Comment by milesap** [comment]
Changed with #2235
