### ISSUE TITLE
Datagrid filtering not working for ObjectID Range numbers (min/max)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2125]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily13/prod/samples/index-samples.html
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

This happened with Datagrids containing French accents.
Enter min/max numbers for ObjectID column, either from Column Heading filter row or from toggle Filters Setting.

![image](https://user-images.githubusercontent.com/18723160/27929075-84a21a14-625f-11e7-802a-0d98efaee04d.png)

**Comment by JahidAhmed** [comment]
Looks like it is fixed by #2127.
