### ISSUE TITLE
Daily14 build not loading in Firefox

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2128]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily14/prod/samples/index-samples.html

It loads in Chrome and IE11 though.

![image](https://user-images.githubusercontent.com/18723160/27961811-050b249a-62fe-11e7-9e84-f206b153ec08.png)

**Comment by JahidAhmed** [comment]
WOMM. Can someone else please test.

**Comment by milesap** [comment]
WOMM

**Comment by IsabellaPan** [comment]
It seems the issue is intermittent. At the time it was logged, it was also verified on Bindu's Firefox browser.
Now it could be loaded :)

**Comment by milesap** [comment]
No longer an issue, closing for now
