### ISSUE TITLE
User Added Layers: When adding a FeatureServer service allow the user to pick a sublayer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2129]
User Added Layers should allow for a user to pick the sublayers when adding a FeatureServer but not specifying the layer ID on the URL.  This would align with MapServer functionality.

Original item by @bkutty :

Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily14/prod/samples/index-samples.html

Test Data: http://www.agr.gc.ca/atlas/rest/services/app_cdm_ssc/canadian_drought_monitor_editing/FeatureServer

This Service gives an error while importing. However, it is possible to import the layer by appending the index no. to the url.  Expected result would be to import the layer successfully and give the user options to choose the sub layers. Please investigate

![image](https://user-images.githubusercontent.com/18539315/27963571-7ec09e28-6303-11e7-9025-4d03239b5a8b.png)

![image](https://user-images.githubusercontent.com/18539315/27963532-61219dcc-6303-11e7-8675-a0868f19b0be.png)

**Comment by mweech** [comment]
we do not currently support adding a FeatureServer in the same fashion as MapServer types (i.e. as a group).  would agree the dialog should provide similar flexibility given AGOL is all FeatureServer
