### ISSUE TITLE
Opacity control confusing on Non-Dynamic Dynamics

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2131]
^ Issue title is also confusing 🏆 

Add http://section917.cloudapp.net/arcgis/rest/services/TestData/Nest/MapServer as a dynamic layer, selecting the `0` index (`Group1`) as the only item.  
Then open the Settings for one of the child layers. You will see the opacity slider, but cannot interact with it.  Changing opacity at the root will update the child slider accordingly.  Since service is not Dynamic (esri term, different from Dynamic Layer on client), this is expected.

Suggest there be a more clear indication that the slider is disabled (more faded? an icon? the text ` (NO!)` beside the word Opacity?).  When I opened the panel I tried to adjust it fully expecting it to work.

**Comment by AleksueiR** [comment]
There might be another inconsistency: the opacity can be changed on "Group1" and "Group2" and this change will affect the entire layer. 
![](https://i.imgur.com/CGeLhqv.png)
In this case, opacity should only be changeable at the root level ('GroupTest`).

I suggest adding a small description that opacity should be changed at the root of the layer and a link that opens the settings panel for that root element, something like this:
![](https://i.imgur.com/7UmOAVr.png)
![](https://i.imgur.com/kdqmI61.png)

**Comment by AleksueiR** [comment]
If a not-true-dynamic dynamic not-group-sublayer is added as a single entry, not a group, it shouldn't have it's opacity slider disabled, since there is no other way to change it's opacity since it has no group. This is a confusing issue. :)

**Comment by AleksueiR** [comment]
New behaviour:
![confusing_opacity](https://user-images.githubusercontent.com/2285779/29775450-2d34edc2-8bd3-11e7-8085-a4b5b86103e4.gif)

I also restored lost `selected` indicator for legend blocks - now it's easy to see which legend block the opened panel belong to.

**Comment by AleksueiR** [comment]
See config `47` on `index-samples`.
