### ISSUE TITLE
Map points for one child Dynamic Polygon layer in a group not displaying on the viewer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2133]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily14/prod/samples/index-samples.html
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

Add above test data as ESRI Dynamic Layer by selecting BorealCaribouRange and CriticalHabitatNationalView children.  One child layer BorealCaribouRange has no map points showing on the view even the tooltip for this Dynamic Layer indicated it contains 51 polygons.

![image](https://user-images.githubusercontent.com/18723160/27974485-2811083c-632c-11e7-8860-e57ee5afb1e4.png)

**Comment by AleksueiR** [comment]
Loads correctly on latest develop this morning: https://i.imgur.com/551nfP0.png

**Comment by mweech** [comment]
could have been a server issue that day.
