### ISSUE TITLE
French Accent column titles not displayed properly in datagrid export

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2135]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

Column titles with French Accents are not displayed as expected. Please see the below screenshot

![image](https://user-images.githubusercontent.com/18539315/28023289-799257d4-655b-11e7-9f09-dcbdd3c1274b.png)

**Comment by AleksueiR** [comment]
More errors of the same type when adding http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/G%C3%A9ochronologie.csv.

> rv-main.js:95762 Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 11-29 ['échantillon.value] in expression [self.Num. d'échantillon.value].
http://errors.angularjs.org/1.6.4/$parse/lexerr?p0=Unterminated%20quote&p1=…29%20%5B'%C3%A9chantillon.value%5D&p2=self.Num.%20d'%C3%A9chantillon.value
    at rv-main.js:81303
