### ISSUE TITLE
Unable to view "remove" option for Auto Legends

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2140]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html

This sample (Sample#30) is populated with auto legends in the config file. However, I am not able to view "Remove" as an option for each of those layers.

Per Reqt, Auto Legends added through config file should have "remove" option.

Please note that this option can be viewed in Isabella's machine.

![image](https://user-images.githubusercontent.com/18539315/28031090-36171e18-6574-11e7-8f8a-97f719325be1.png)

**Comment by AleksueiR** [comment]
Yeap, there is a bug in checking the legend type - it becomes fixed to the legend type of the first config loaded. If you load `config 30` first, all other config with structured legends will have the "remove" control visible as well.
