### ISSUE TITLE
More service layers (both Feature and Dynamic) - Datagrid Column Headings not scrolling with body

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2141]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html
Test data: http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0

This is a similar issue as previous logged in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2081, just realize this behavior is not only happened with scale dependency layers.

![image](https://user-images.githubusercontent.com/18723160/28036206-7a64d978-6585-11e7-9c46-94f070451c3d.png)

**Comment by JahidAhmed** [comment]
I can only replicate in Chrome when the zoom is at a certain value. 
At 100% all layers work as expected.
At 110% no layers with scrollbars work.

And when zooming in more, certain layers work and others don't.
Specifically, the powerplants layers don't work at 125% and 175% but they do work at 150% zoom.

(Note: datatable must be closed and reopened when attempting to zoom and scroll)

**Comment by milesap** [comment]
Can't reproduce this issue

**Comment by jolevesq** [comment]
Not able to replicate

**Comment by AleksueiR** [comment]
Seems to be a known issues with Datatables: https://github.com/DataTables/DataTablesSrc/commit/7cfdcdd4198494

**Comment by IsabellaPan** [comment]
July 12
Tested with today's daily build: http://fgpv.cloudapp.net/demo/v2.0.0-daily16/prod/samples/index-samples.html
Still not working in Chrome and Firefox, my browsers are always set to Zoom 100%
