### ISSUE TITLE
Pointer remains on the map even after closing the coordinate info box

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2144]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html

1.Selecting the "coords info" displays the  coordinate info of a map location with pointer. This pointer remains on the map even after closing the info box. 

2. Clicking on the map to view the coords info also seems to trigger feature details pane. Is this expected?

![image](https://user-images.githubusercontent.com/18539315/28069924-35c0dd0a-6619-11e7-832e-f8bd5f9b7a78.png)

![image](https://user-images.githubusercontent.com/18539315/28070100-cde2d598-6619-11e7-8a52-9114058cc8d2.png)

**Comment by jolevesq** [comment]
@bkutty  you are right, clicking on the map should not trigger details panel. The cursor comes from the details panel as well. Removing the event will remove the cursor.
