### ISSUE TITLE
User added WMS layer not displaying on the viewer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2150]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html
Test data: http://maps.geogratis.gc.ca/wms/railway_en

Though this Railway WMS layer could be added under the legend.
To reproduce the issue, "Select All" in step 3 (Configure layer)

![image](https://user-images.githubusercontent.com/18723160/28085959-52c0d144-664b-11e7-9abe-937f843083ee.png)

**Comment by milesap** [comment]
This seems isolated to this service which has a bad layer `railway.subdivision`. Testing with the service http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en?VERSION=1.1.1&request=GetCapabilities&service=wms is ok. Its probably a good idea to stop testing with the railway service and use this one instead.

@IsabellaPan let me know if any other WMS services cause this issue.

**Comment by mweech** [comment]
Railway layer is allowable for testing ONLY if you do not use select all and avoid use of subdivision layer.

**Comment by milesap** [comment]
Seems isolated to the faulty railway layer, works for other WMS layers
