### ISSUE TITLE
Back To Cart Doesn't Detect Pending Removals

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2153]
If a user removes a layer, and quickly clicks Back To Cart before the "Undo" timer expires, the request sent to the data catalog will include the deleted layer.

Need a way to detect the pending deletion.  Tricky because the UI handles the Undo process; it doesn't inform Geo Module of anything until the timer expires.  The Layer Registry is what determines the cart contents and is unaware of the UI

**Comment by AleksueiR** [comment]
The Layer Registry now derives the order of layer records from the legend to synchronize layer stacks. It will omit any pending layers since such legend blocks are actually removed from the legend structure (and re-inserted on timeout expiry). We can use that for bookmarking and back-to-cart.

**Comment by mweech** [comment]
This is a timing issue and the user can just remove from their cart afterwards.  Work around available.
