### ISSUE TITLE
Print does not work

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2163]
The print in the new daily build doesn't return a print image.

I believe there is a bug in the code.

You can try it out in this demo: http://fgpv.cloudapp.net/demo/v2.0.0-daily16/dev/samples/index-fgp-en.html

**Comment by james-rae** [comment]
Fails in `index-fgp-en` but works in `index-samples`.  Possibly just a configuration issue in `index-fgp-en`, which was recently migrated and really only used to test RCS

**Comment by james-rae** [comment]
Yep, the config file for `index-fgp-<lang>` only has `footnote` defined in the printing node.
Can do a quick PR to add the other things

**Comment by AleksueiR** [comment]
You forgot about timestamp, but that's okay. :)
