### ISSUE TITLE
Set basemap to use in overview map

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2168]
We need to be able to set the overview map to use. It can be the used basemap as default but we need to be able to specify a layer even if this layer is not in our list of basemap.

**Comment by james-rae** [comment]
Believe this has been completed for v2.1.0

See
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2206
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2238
https://github.com/fgpv-vpgf/geoApi/pull/249
