### ISSUE TITLE
Sample 1 - Missing top bracket (exclusiveVisibility) when radio button was removed

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2169]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily17/prod/samples/index-samples.html

![image](https://user-images.githubusercontent.com/18723160/28174100-7d2844fc-67be-11e7-838e-2cd4d25c46da.png)

**Comment by AleksueiR** [comment]
This is "correct" since the bracket is added to the visibility control. Since it's removed, there is no bracket. That said, this is a meaningless use case - there is no point in added a layer to a visibility group and removing its visibility control.

**Comment by mweech** [comment]
Agree with Alex
