### ISSUE TITLE
Wrong label in print export setting

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2176]
we miss the ,export.component.mapelements, North arrow and scalebar,1, Flèche du nord et échelle graphique,1. It use mapElement instead and it is not define

![screen shot 2017-07-13 at 2 43 02 pm](https://user-images.githubusercontent.com/3472990/28182287-a3f44804-67d9-11e7-8e9e-a77ada02165a.png)

**Comment by jolevesq** [comment]
It was a problem in the config file. mapElements was used instead of mapelements.

**Comment by AleksueiR** [comment]
Safe to close then?

**Comment by jolevesq** [comment]
I think so. In the other hand do we want to check if the item is in the list of items and if not throw an error. In the futur we should something to create and validate config file so it is maybe not needed.

**Comment by AleksueiR** [comment]
Good point - config validation should take care of that.

**Comment by jolevesq** [comment]
I think I will have to change ```componentOrder = ['title', 'map', 'mapElements', 'legend', 'footnote', 'timestamp'];``` to mapelements because it is mapelements inside translation.csv so it can make the link. Will maybe have to change the schema to put mapelements as well.

**Comment by jolevesq** [comment]
I change translation.csv. It was the easiest way.

**Comment by AleksueiR** [comment]
Yeah, all the samples configs use `mapElements`.
