### ISSUE TITLE
Double clear buttons in Datagrid search bar 

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2181]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily17/prod/samples/index-samples.html

This issue is similar to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1520

![image](https://user-images.githubusercontent.com/18723160/28217907-d7fae472-6884-11e7-8a33-63b2ff2b3a5c.png)

**Comment by AleksueiR** [comment]
Probably need to use
```css
input::-ms-clear {
            display: none;
        }
```

similar to how it's used here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b6686db2bb4bd78239bd2093df055c3c41b2e1f8/src/content/styles/modules/_help.scss#L77
