### ISSUE TITLE
Highlighted Feature Blocks Hovertips

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2189]
The highlight graphic will not have mouse events, and appears to be blocking the events of the real graphic underneath.

To test - Do a zoom to feature.  Mouse over it. No tip.  Slightly pan the map to remove the highlight. Mouse over it. Tip.

I believe there is already code/css to force a graphic to allow mouse events to pass through it

**Comment by AleksueiR** [comment]
Fixes, thanks.
