### ISSUE TITLE
Adding filters and closing and reopening datatable not consistent

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2203]
Adding filters for `Date Layer field` and then closing and reopening the datatable automatically applies the filters to the map.

However, the filters are not automatically applied for other layers after closing and reopening the datatable.

Possibly due to `Date Layer field` having `filter` pre-defined in the config.

**Comment by jolevesq** [comment]
Filters are apply automatically because of the setting inside the config file. It should only do this the first time table is open. This is a bug.
