### ISSUE TITLE
"Show Filters" in datagrid unable to turn on or off the filter row for column heading

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2209]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc2/prod/samples/index-samples.html

![image](https://user-images.githubusercontent.com/18723160/28382401-f680f8ea-6c8b-11e7-853c-8a743c2f22bb.png)

**Comment by JahidAhmed** [comment]
Changing `Show Filters` for one layer affects all other layers so turning it off in one table will turn it off for the other tables and vice versa. Do we want to leave it as is or have it separate. I believe it was the latter before

**Comment by AleksueiR** [comment]
Should be per-table I think, as with the `split view/maximize` option.

**Comment by AleksueiR** [comment]
@IsabellaPan has this been checked?
