### ISSUE TITLE
Datagrid does not display properly once Filters are applied

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2217]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc2/prod/samples/index-samples.html

Test data:
[ne_10m_airports.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/1162404/ne_10m_airports.zip)

http://maps.ottawa.ca/arcgis/rest/services/CyclingMap/MapServer

Once filters are applied to datagrid, filtered table is not readable. It appears as below in Firefox and Chrome. I tested this on a File based layer and using a service url. Please investigate

Firefox

![image](https://user-images.githubusercontent.com/18539315/28419457-f4f44558-6d2c-11e7-9b81-1bfc24619cd3.png)

Chrome

![image](https://user-images.githubusercontent.com/18539315/28419485-0a3148c6-6d2d-11e7-9328-fe543e8f93a9.png)

**Comment by JahidAhmed** [comment]
Related issues in #2201.

**Comment by milesap** [comment]
Could not replicate, I can see for a brief moment the data flash when filters is closed, but then normalizes within 100-200 milliseconds.

**Comment by JahidAhmed** [comment]
I can replicate but need to rearrange the columns from the settings menu.
`autoWidth: false` seems to fix this problem though

**Comment by AleksueiR** [comment]
Yeap, can replicate only after reordering columns.

**Comment by milesap** [comment]
Ok, I still can't on reordering columns - I can briefly see the data is unreadable but it corrects quickly.

This is certainly related to `autoWidth: false` where they claim:
> This can be disabled as an optimisation (it takes a finite amount of time to calculate the widths)

Though it should eventually correct depending on the row count I imagine. In either case I'll assign it to @JahidAhmed who can replicate this issue.
