### ISSUE TITLE
Keep track of selected radio button when visibility is set to false

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#2224]
![radiobutton](https://user-images.githubusercontent.com/16193004/28431059-d7b49dde-6d50-11e7-84f7-b2f91d746369.gif)

**Comment by AleksueiR** [comment]
How about this? :)
![smart_vis_gropu](https://user-images.githubusercontent.com/2285779/28463246-833795ca-6ded-11e7-803b-e7a1dd5a1554.gif)

Visibility groups now remember previous selection when toggled by their parents.
