### ISSUE TITLE
All other children map points are gone after removing only one child layer for EcoAction Community

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2233]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc3/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction 
(Main site provided by James)

![image](https://user-images.githubusercontent.com/18723160/28467519-34902250-6dfe-11e7-857d-af744a18d7dd.png)

**Comment by IsabellaPan** [comment]
Following the above issue, BackToCart button is not responding

**Comment by james-rae** [comment]
Without looking at the code, am expecting the `Remove` function is removing the entire layer instead of dealing with the virtual child layer.  Legend becomes out of synch , and bookmark / BackToCart is attempting to parse a non-existing layer

**Comment by AleksueiR** [comment]
Yeap, that's what's happening. I think have a fix.
