### ISSUE TITLE
Enhanced Projection Support

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2234]
Attempting to load [this layer](http://gis.lethbridge.ca/lethwebgisarcgis/rest/services/OpenData/odl_picnictables/MapServer/0) fails due to the reprojection.

The layer's spatial reference is
```
"wkid": 102187,
"latestWkid": 3776
```

We attempt to get the `epsg` code for `102187`, which does not exist.  However, the code for `3776` does.

A few ideas to go forward:

1. If initial request fails, and the spatial reference has a `latestWkid` property, attempt to do a second lookup on that key (or possibly, and more efficiently, try `latestWkid` first).
2. Debate about soft error handling if we cannot find a reprojection code.  We would treat it same as basemap and accept possible issues (ESRI servers should auto-reproject the map component ; things like bounding boxes and zoom to extent / zoom to feature would be impacted).  Could be significant refactors.
3. Consider making a separate issue to move the reprojection logic to a plug-in.  Right now we are hardcoded to use `epsg` lookups.  Some implementors might want to use an ESRI projection service, or a hybrid that tries one then falls back to another.

**Comment by james-rae** [comment]
Also, for short term support (forest fires) we will add some hardcoded mappings to the geoApi

**Comment by mweech** [comment]
Does this create our first "GeoAPI plugin" ?  i.e. projection lookups, etc. sounds like an entirely back-end functionality and very different from other plugins that add/change behavior of the front-end.

**Comment by mweech** [comment]
Marking as a higher priority for v2.1 scope.  The potential implementation as a plug-in will greatly increase the sustainability of the viewer if resources are not available to provide support to core functions.

**Comment by AleksueiR** [comment]
It's still a client plugin, I think. Right now, `epsg lookup` function is hardcoded on the client and is passed to geoApi when layer records are made. This new plugin would just replace that function.

**Comment by james-rae** [comment]
May also want to toy with the idea of changing the projection library (e.g. `proj4` vs ESRI Projection Server).  A bigger refactor as it involves more geoApi stuff & library references (instead of just a webcall function)

**Comment by mweech** [comment]
implement Option #1.  assign as you see fit
