### ISSUE TITLE
Table Settings Revamp

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2235]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc3/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction

![image](https://user-images.githubusercontent.com/18723160/28469746-46d3efb2-6e05-11e7-9e53-f423de71b9ce.png)

**Comment by AleksueiR** [comment]
Likely host-page styles are being applied to these elements.

**Comment by mweech** [comment]
this might be a good issue to use as a catalyst for updating styling of the data grid settings.  it needs to be more consistent with the look and feel of the rest of the viewer.  i think we can refer back to the mock ups from Alex.

**Comment by milesap** [comment]
@AleksueiR Please post all the mockups you have here for reference

**Comment by AleksueiR** [comment]
Check here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2123#issuecomment-314418929

**Comment by milesap** [comment]
![28066851-b0970cd2-660c-11e7-9229-8e14393146f1](https://user-images.githubusercontent.com/10187181/28569962-fb1dc54a-7109-11e7-8bea-752136a5df06.png)

**Comment by JahidAhmed** [comment]
Regarding the mockups, can we add a button for `Display` to toggle all the columns on / off

**Comment by AleksueiR** [comment]
Should probably rename `Display` to `Show` to make it less confusing.

**Comment by AleksueiR** [comment]
The filter values are still hardly visible (as in the first screenshot). The host page overrides the placeholder colour with 
```css
[placeholder], input[placeholder] {
    color: #5c5c5c!important;
}
```

We need to counter that and override it back with the default color :D
