### ISSUE TITLE
Legend display in Export image should be modified to reflect the top level elements

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2236]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc3/dev/samples/index-samples.html

Legend in export image reflects only immediate elements which might not be meaningful to the user. Please see below screenshot of the legend panel and the legend display in export image

![image](https://user-images.githubusercontent.com/18539315/28469705-206eb5b4-6e05-11e7-983a-566c0c9091f6.png)

![image](https://user-images.githubusercontent.com/18539315/28469682-0c87ed04-6e05-11e7-97cc-a9a9d1ce44c7.png)

**Comment by mweech** [comment]
This is working as expected.  

The real issue here is that the structured legend is not very well labelled for a polished deployment.  There is no value to providing a layer named "Nuclear", which also has a legend of one symbol named "Nuclear".  It would be more appropriate to have one layer named "Power Plants", with a legend that had three symbols labelled "Nuclear, Wind, Solar".  The legend would look alot better.

**Comment by AleksueiR** [comment]
@JahidAhmed looked into this a bit more, and this is an actual bug, not a by-design behaviour.

If you check pre-2.0 generated legends, they do reflect hierarchy of the dynamic layers ([here](
https://files.gitter.im/AleksueiR/ZzT3/rv-app-0---2016-11-28-11-34-50.png) and [here](https://camo.githubusercontent.com/09d70e8b9a6fe27cce858916a5f835477f143b0b/687474703a2f2f692e696d6775722e636f6d2f456253435333422e706e67)). The above example should have been rendered as:
```
Power Plants, nuclear
- [icon] Nuclear

Power Plants, wind
- [icon] wind

Power Plants, solar
- [icon] Solar
```

The top-level grouping are lost and for some reason replaced with the label of the single child.

#### Old (proper pre-2.0) rendering of the Eco Geo layer:
![](https://i.imgur.com/6NEII2q.png)

#### New (2.0) rendering of the Eco Geo layer:
![](https://i.imgur.com/YHRwzWy.png)

I believe some of the structure got lost with 2.0 update and the export logic that generates a legend operates on fewer items - it looks like each Eco Geo sublayer is considered to be a separate layer.

This should be relatively easy to fix by updating how the legend tree is extracted from the collection of the legend blocks.
