### ISSUE TITLE
Error hovering over symbols for Air Ozone layer

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2239]
Possibly related to #2225.

After clicking on one of the symbols (the ones identified in the legend, not the `Nature` symbols) on the map for the `Air Ozone` layer, the `Feature Details` panel opens.

While the panel is open, hovering onto or out of any of these symbols described above or any clickable item (for example any of the buttons) results in the following error:

![capture](https://user-images.githubusercontent.com/9637542/28477584-bb2b67f6-6e22-11e7-952f-0d376ba11088.JPG)

Note: Only happens for this layer, none of the others result in this error.

**Comment by AleksueiR** [comment]
No relation to #2225 :)

[Here](https://github.com/AleksueiR/fgpv-vpgf/blob/2233-don-t-remove-layers-prematurely/src/app/ui/details/details-record-esrifeature-item.html#L54), the result value is passed through two filters. (This was supposed to be a one-time binding, but filters don't let the value stabilize). 

`old_symbol` doesn't have a value, and the [`picture` filter](https://github.com/AleksueiR/fgpv-vpgf/blob/2233-don-t-remove-layers-prematurely/src/app/core/formatters.filter.js#L97) is expecting a string, which fails when it tries to cast a `null`.

**Comment by james-rae** [comment]
Can you post the URL to the Air Ozone layer (or at least the test page being used)?  I've encountered bad services before (if it's not the production one)

**Comment by AleksueiR** [comment]
`index-mobile` page is used.
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer/2

**Comment by AleksueiR** [comment]
This needs a further tweak.
