### ISSUE TITLE
Unable to save the exported map in IE

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2243]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/dev/samples/index-samples.html
http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction

For some reason, export image cannot be saved in IE.  I cannot save this in Firefox too.Please investigate

![image](https://user-images.githubusercontent.com/18539315/28524805-00af1a1e-7050-11e7-9c86-4ff331fd50b8.png)

![image](https://user-images.githubusercontent.com/18539315/28524989-b64bd7ea-7050-11e7-8bb3-cd90d22cd4f5.png)

**Comment by AleksueiR** [comment]
Works for me in Firefox.
I see the error on the second screenshot says it's Safari. Have you tested in Safari as well? What browser was that?

**Comment by bkutty** [comment]
No, didn't use Safari. This error was in Firefox (54.0 ).  Can't test export now as there seems to be some network error. Export does not finish loading.

![image](https://user-images.githubusercontent.com/18539315/28526755-7811367c-7056-11e7-9311-995e8f4dab81.png)

**Comment by AleksueiR** [comment]
Yes, the printing service went down in the last ten minutes or so. 
Also, it's a bug for Firefox being identified as Safari.

**Comment by milesap** [comment]
Will check back later today, print service is down atm

**Comment by milesap** [comment]
http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/Utilities

**Comment by milesap** [comment]
No luck yet using the URL http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task

> exportGeneratorsService print task failed on try 1 with error Error: Error performing submit job operation

**Comment by milesap** [comment]
Confirmed service is still down - I wonder if _they_ know its down?

**Comment by milesap** [comment]
Having errors this morning:

> exportGeneratorsService print task failed on try 1 with error Error: 9017$SITE_NOT_INITIALIZED
