### ISSUE TITLE
Removed child layers coming back under the legend after applied Bookmark or BackToCart

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2245]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction

- Remove some children from EcoAction Comminity group layer, for example, Nature and Clean Water
- Apply backToCart, or Get Link, or Share the map
The above two child layers come back under the legend, though visibility is setting to off. User could still enable the map points.
![image](https://user-images.githubusercontent.com/18723160/28529187-e7520064-705d-11e7-954e-2cc2e6ca3900.png)
![image](https://user-images.githubusercontent.com/18723160/28529221-ff1ad1da-705d-11e7-8fac-45afe6a0a233.png)

**Comment by AleksueiR** [comment]
The current version of the bookmark (V2) doesn't not preserve removed dynamic children. They will come back as toggled off after loading from a bookmark.

**Comment by AleksueiR** [comment]
This is loosely related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2233.

**Comment by JahidAhmed** [comment]
This seems to also be happening when we simply reload a dynamic child after removing one of its 'siblings'.

Removing one child and reloading the other restores the previously removed child
