### ISSUE TITLE
Geolocation Search - The selected option half hided

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2247]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction

![image](https://user-images.githubusercontent.com/18723160/28530127-b86cc2ae-7060-11e7-93a4-e39b659ded3e.png)

**Comment by barryytm** [comment]
Please refer to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1877

**Comment by IsabellaPan** [comment]
This could be closed if duplicated with  #1877
