### ISSUE TITLE
Strengthen validation of the latitude and longitude fields of a  CSV when importing

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2254]
Need to check all the cell values of a CSV file before going to step 3 letting users to pick the costumed latitude and longitude fields.  Otherwise it would cause errors when using the values the user selected.

![capture](https://user-images.githubusercontent.com/19259169/28540217-7a19c070-7082-11e7-89d0-7f481d90dbd8.PNG)

**Comment by AleksueiR** [comment]
This will require changes to geoApi and the client.
