### ISSUE TITLE
Layer tooltip when opacity is 0

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2263]
Opacity of layer is 0 but tooltip is shown instead of the layer beneath it. Potentially this is the correct approach. However, can also disable tooltip in this case.

![](https://files.gitter.im/JahidAhmed/hm3z/Capture.JPG)

**Comment by AleksueiR** [comment]
In RAMP 1, when layer opacity is set to zero, the layer layer went invisible (no tooltips, no identify). We can implement that again. Another crazy idea: do not allow 0 opacity with the minimum opacity is at 1%.

**Comment by AleksueiR** [comment]
Relevant comment (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2456#issuecomment-340520610) and some discussion points around it:

> @mweech if a user has chosen specifically to "hide" it, we should really truly hide it. that includes interactions. they have made a choice to do so... opacity i think could be viewed as less binary... its a scale, not an on/off choice


Visibility and opacity are viewed as two different settings and should be treated differently. Setting opacity to 0 still renders the points on the map even though they are fully transparent. As such, they should spawn tooltips and appear in identify results.

The suggestion to turn the layer off when opacity is set to 0 has a counter argument pointing out that there is little difference between opacity 0 and 0.01. In both cases the features are effectively invisible to the user and should behave in a similar fashion.

@JahidAhmed I think this can be closed now
