### ISSUE TITLE
Map Export (for Lambert) not working after imported service as Dynamic layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2265]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc5/dev/samples/index-samples.html
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

- Add above test data as Dynamic layer with Lambert projection (map export is working with this projection in current build)
- Export map

Map export will not load map points and basemap. However, it works if adding the same service as Feature layer.
![image](https://user-images.githubusercontent.com/18723160/28586489-0d95fdae-7142-11e7-977d-ae4a2085f351.png)

**Comment by AleksueiR** [comment]
Might be related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2261

**Comment by mweech** [comment]
@barryytm plz verify if this is still an issue

**Comment by barryytm** [comment]
The layer is a feature layer but imported as a dynamic layer and it is by design that we don't support such import.

**Comment by barryytm** [comment]
There are some layers work and some don't 
Working example:

- http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/0 

Not working example:

- http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

**Comment by barryytm** [comment]
The following message appears in the Network tab when an error occurs

`{"jobId":"j75791425acc1405887a2c079d9418c67","jobStatus":"esriJobFailed","messages":[{"type":"esriJobMessageTypeInformative","description":"Submitted."},{"type":"esriJobMessageTypeInformative","description":"Executing..."},{"type":"esriJobMessageTypeError","description":"Layer \"esriDynamic#2\": Unable to connect to map server at http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer."},
{"type":"esriJobMessageTypeError","description":"Could not determine encoding"},{"type":"esriJobMessageTypeError","description":"Failed to execute (Export Web Map)."},{"type":"esriJobMessageTypeError","description":"Failed to execute (Export Web Map Task)."},{"type":"esriJobMessageTypeError","description":"Failed."}]}`

**Comment by JahidAhmed** [comment]
For the protected areas, was it imported as dynamic or feature because the error you pasted says `esriDynamic`; if I try to import as Feature Layer the export works

**Comment by james-rae** [comment]
Works in `v2.3.0`. Likely solved by issue #2448
