### ISSUE TITLE
Datatable column positioned incorrectly

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2271]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Since we have `autoWidth: false` for the table, zooming out in your browser while the datatable is open displaces the positioning of the columns.

![capture](https://user-images.githubusercontent.com/9637542/28632809-ba12ae3e-71ff-11e7-9039-f6c2957cc966.JPG)

**Comment by AleksueiR** [comment]
Scrolling the table seems to fix it, after a couple of seconds. If browser zoom level changes can be detected, maybe we can call something like `.scroller.measure()` to correct column positions.

**Comment by JahidAhmed** [comment]
Also need to ensure the dotted line representing static fields does not disappear. It does not come back when the columns are readjusted in this case.

**Comment by milesap** [comment]
dotted line representing static fields will disappear if the zoom level makes the text too small for it to render on the display.
