### ISSUE TITLE
Datagrid changed to Maximize view & Filters were gone in Full Screen mode

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2272]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc5/dev/samples/index-samples.html

- Set datagrid to Split View and Show Filters (1st screenshot)
- Switch to Full Screen mode (2nd screenshot)
In this case, the options for Split View and Maximize are both cut off in setting menu.

Full Screen mode has a series of issues for IE browser. This issue might related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2266

![image](https://user-images.githubusercontent.com/18723160/28639628-e31e067c-7216-11e7-8497-4a77e10b6a8c.png)
![image](https://user-images.githubusercontent.com/18723160/28640030-59a9ee22-7218-11e7-9755-c946c7de9564.png)

**Comment by AleksueiR** [comment]
Likely related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2266
