### ISSUE TITLE
Zoom To Layer Boundary Behavior

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2273]
Need to determine best logic for where map ends up when user clicks `Zoom To Layer Boundary`

## Layer with Well-Defined Extent

Want to zoom to it.  In particular, useful if area is small, or outside the normal map view (e.g. user adds dataset in China. Zooming to it lets them know why they don't see it in Canada).

## Layer with Massive Extent

Often the case of poor server defaulting (e.g. WMS really likes to do the entire world in Lat/Long).  Sometimes data covers entire world, sometimes not; this makes zooming to the extent randomly useful.

Is a bigger problem with Lambert basemap; it's focused on Canada and distorts the rest of the world severly. Zooming to the world means Canada is panned northward off the screen.

Mercator is not bad because our tile set covers the world and what you see on the screen makes sense.

User can always click the "Canada Extent" button to return from a nonsense view.

## Options

This is most problematic with RCS layers and user-added layers. A config-file based layer can override the layer extent to be something intelligent.

Each basemap category (i.e. projection schema) can have various extents set for them, such as `full` and `maximum` extents; however these are not required. `default` is required and will be used if the other extents are not provided.  We could add logic that limits the `Zoom To Layer Boundary` to reside inside one of those extents. But we lose some utility in doing so (e.g. if data is in Europe, where do you zoom to? Canada view? Not helpful).

Since user can always recover from a silly/confusing view, we could just accept that some zooms will be bad (e.g. full world in Lambert) and blame the service creators.

Related issues:
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1650
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2259

**Comment by AleksueiR** [comment]
As James suggested yesterday, we will track zoomto actions and display a snackbar notification when it moves out of `full` basemap extent. The notification will let the user to undo the zoomto action and return to the previous extent. If not action upon, the snackbar self-dismisses in a couple of seconds.

**Comment by AleksueiR** [comment]
Enhance!
![bad_zoom](https://user-images.githubusercontent.com/2285779/29136117-3b695b62-7d0a-11e7-889d-f82997d5026c.gif)

**Comment by AleksueiR** [comment]
@james-rae do we consider this done or do we want to implement anything else?
