### ISSUE TITLE
DataTable scrollbars in Desktop Safari

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2274]
Safari seem to render scrollbars only when you hover over them or the content is scrolling. This doesn't work as intended with the datatable and layer list:

![safari-table](https://user-images.githubusercontent.com/2285779/28668578-7ad8d370-729e-11e7-8c4f-3dbe4e2ddf4d.gif)

If you scroll the table with a scrollwheel or keyboard, and then hover of the scrollbar, you can drag it with a mouse.

> Safari 10.1.1

**Comment by AleksueiR** [comment]
@jolevesq can you check if this is happening for you as well?

**Comment by jolevesq** [comment]
@AleksueiR I have Safari 10.1.2 and it works as expected. Should we close this issue?

![screen shot 2017-10-25 at 7 41 16 am](https://user-images.githubusercontent.com/3472990/31996847-f7c9d6e0-b957-11e7-98c0-4cc5efe30f03.png)

**Comment by AleksueiR** [comment]
@jolevesq If this works correctly in the real Safari, I'm happy to close this. Thanks for checking :+1:
