### ISSUE TITLE
Datatable clearing / applying filters in IE

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2276]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

In IE, for the datatable settings panel, the containers have an 'X' to clear the value inside them (no 'X' in Chrome) and hitting that button clears the value inside the filter but still has `Apply to Map` enabled and thus sets the filter to it's previous value.

![capture](https://user-images.githubusercontent.com/9637542/28675765-c7a0dc9e-72b6-11e7-9d73-b07185cb6212.JPG)

**Comment by AleksueiR** [comment]
These are IE-specific controls. They can be removed by
```css
input::-ms-clear {
            display: none;
        }
```
