### ISSUE TITLE
Datatable not loading for field names resembling function notation

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2282]
Adding [this](http://mycity.houstontx.gov/arcgisv91/rest/services/PWE/PUDUtilities_Public_wm/MapServer/79) service and opening the datatable throws an error: `TypeError: data[a[i]] is not a function`.  (NOTE: avoid testing with that service as it is massive. Ask James for a sample file)

The error is coming from a datatables function, `_fnGetObjectDataFn` which is attempting to check if they are dealing with special notation (in this case, function notation) and handling it appropriately.

The service has a field named `SHAPE.STLength()` which is causing the error.

**Comment by JahidAhmed** [comment]
Opening any other table after this error also causes them to display incorrectly, though that should be fixed after handling this problem.

![image](https://user-images.githubusercontent.com/9637542/28724057-d123e600-7386-11e7-91a0-a6d527ec77cc.png)

**Comment by james-rae** [comment]
Attempting to do a full field rename is problematic, as it involves identifying and changing fields at a number of spots in the code, including

- initial fields load
- attribute load
- identify results from server
- quick feature load for hovertips
- field names in renderers

Decided instead to trick the datagrid by adding a function that it was looking for.  The function returns the property value of the offending field.

A small adjustment to the details pane was made to prevent any functions on the attribute object from appearing.

**Comment by james-rae** [comment]
For testing, I suggest not using the original URL provided above.  It is a massive dataset (~150 MB), takes minutes for the grid to load, and will likely anger the service owner.

Easiest approach is to create a geoJSON file with a naughty field name.  I can provide a sample.

**Comment by james-rae** [comment]
One limitation to the solution, if dataset has two similarly named fields, one will get overwritten.

E.g. 
```
{
  "OBJECTID": 1,
  "Barry": "I am Barry",
  "Barry()": "I am also Barry"
}
```

Will have field `Barry` erased by the secret function.

**Comment by james-rae** [comment]
Considered done when viewer is using geoApi `v2.0.1-2` or higher
