### ISSUE TITLE
Warning for Large Attribute Sets

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2284]
Idea for showing some type of warning if user attempts to open datagrid on layer with lots of records, and allow them to cancel the request.

E.g. `alert('Hello you are about to open a table with [feature count] rows. It might take a while to load.');`

We would decide what our limit is for triggering the message ( e.g. > 1000  )

Somewhat related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/613

**Comment by AleksueiR** [comment]
A snackbar notification can be used. Instead of asking users if they want to continue load a large dataset, start loading as usual and display a notification about a large datataset after ten seconds or so with an option to cancel.

**Comment by AleksueiR** [comment]
This can be used for testing: http://mycity.houstontx.gov/arcgisv91/rest/services/PWE/PUDUtilities_Public_wm/MapServer/79

**Comment by AleksueiR** [comment]
Ok, change of plans: instead of notifications, a number of currently loaded record will be displayed.
Closing table before everything is loaded, stop the loading process.

![large_data_2](https://user-images.githubusercontent.com/2285779/28828385-96847bf2-769e-11e7-8146-195a93484d50.gif)

**Comment by AleksueiR** [comment]
Client modifications are complete; geoApi needs to expose `loadedFeatureCount` on the layer proxy.
