### ISSUE TITLE
Details panel chokes when trying to expand results

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2293]
Steps:
 - add the layer below to the map
 - click somewhere to get identify results
 - try to expand one of the results
 - observe app becoming unresonsive

```json
     {
          "id":"aafc_plant_hardiness_zones",
          "name": "AAFC Plant Hardiness Zones",
          "layerType":"esriDynamic",
          "layerEntries": [{"index": 0}],
          "url":"http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_plant_hardiness_zones/MapServer",
          "state": {
            "visibility": false
          }
        },
```

I think the problem in reprojection geometry of result symbols for highlighting purposes. These symbols have massive amounts of rings:
![](https://i.imgur.com/TiZTHfV.png)

Can the highlight symbol be simplified somehow? Or maybe we drop highlights for such heavy object and display a graphic marker instead?

**Comment by james-rae** [comment]
Semi-related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2190

**Comment by james-rae** [comment]
Alternate thought for fast lazy solution.... make request for highlighting asynchronous to main detail display.

**Comment by AleksueiR** [comment]
... and display a graphic marker until the request resolves.

**Comment by james-rae** [comment]
Removing hilight from same thread that opens details.
Can't test on that layer due to cross domain anger issues, but was able to open another large polygon detail.

No graphic marker because we need the geometry to know where to put it, and the geometry is what is slow.

Adding more detail to #2190 for more efficiency on the server to client graphic side of things.

**Comment by AleksueiR** [comment]
We should use web-workers to run calculations in a single thread to make it asynchronous. Either that, or server-side component.

**Comment by AleksueiR** [comment]
> No graphic marker because we need the geometry to know where to put it, and the geometry is what is slow.

We can put the graphic marker at the click point.

**Comment by james-rae** [comment]
Setting back to To Do
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2190 solution will help improve the situation from an efficiency aspect (large geometries are simplified on server).
This issue will remain to look into implementing web-workers and graphic marker enhancements.

**Comment by AleksueiR** [comment]
Pushing to 2.1 for web-worker implementation.

**Comment by AleksueiR** [comment]
Reopening, so it is not lost. This is still an issue.

**Comment by james-rae** [comment]
Related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/964

**Comment by james-rae** [comment]
Appears to be solved.  Original service is down, but using [another large polygon dataset](http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/1) as dynamic layer shows fast performance.
It's possible the bug in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3379 was causing the geometry to not simplify.
