### ISSUE TITLE
Server Attributes Not Sorted By ObjectID

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2296]
## Story and Sad News

We fetch our feature attributes separate from the spatial element of the layers. Some benefits:

- can avoid downloading full attribs until they are needed (e.g. a grid opens)
- can work around the upper record limits of services (e.g. stripping attributes from a large client side feature layer would hit the server limit, usually 1000)
- can unify the code for getting attributes from feature and dynamic layers

To accomplish this, we run multiple queries against the service endpoint.  We grab as much data as possible; if there is more remaining, we note the largest `OBJECTID` returned in the last batch, and instruct the next query to ignore records below that id.

The underlying principle that makes this work is that records are returned from the server sorted by `OBJECTID` in ascending order.

Sadly we have discovered [a service](http://mycity.houstontx.gov/arcgisv91/rest/services/PWE/PUDUtilities_Public_wm/MapServer/79) that does not do this. 

## Server Pagination

ArcGIS Server 10.3 and up [supports pagination](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Query_Map_Service_Layer/02r3000000p1000000/), but apparently only [if the underlying data is in an ArcSDE enterprise GDB like SQL Server, Oracle, or Postgre](https://geonet.esri.com/thread/118631), and is configured to support pagination; our FileGDBs seem to be out of luck.
As nice as this seems, the limitations make this not very useful.

## Ordered Queries

10.1 server supports order by field in the result.  This means we can force the results to be sorted by `OBJECTID`, but will put an extra load on the servers.  In particular, large datasets will have to do a full sort on every batch.  For the naughty service above, that amounts to around 144 sorts on 140,000 records.

We are toast for 10.0 server.

## IDs First

The server query limit does not apply to a request for object ids only.  A solution would be to download the ids, sort them in client, calculate batch ranges, and specify precise chunks of ids rather than relying on the `>` sign.

Adding complication to this approach is that 10.0 servers do not expose a `maxRecordCount` property, which we need to calculate the size of the batches.  And even better, 10.1 servers have a bug that can return the wrong `maxRecordCount`, see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/485

For the naughty service, this adds an additional 13MB web call.  It also means adding a call that, in most cases, would serve no use other than a saftey check.

## Lazyness

As a more theoretical discussion, maybe someone loading 150000 / 150MB of records into a web-based viewer deserves exactly what they get.

It would also be good to know how often a service would not sort by `OBJECTID`. It is so prevalent that I wager it is the default configuration. We might be making our download process more inefficient to handle a miniscule number of cases.

Issue is somewhat related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1965

**Comment by milesap** [comment]
Just thought this could be a good time to implement web workers for fetching feature attributes (maybe one worker per layer?). Perhaps:

- Start all workers when the viewer loads
- Opening the table continues to show progress on the feature attribute download
- Each worker does a quick check on a group of feature attributes to determine if they are sorted, if so continue as we normally do
- If feature attributes are not sorted stop and start over doing:
    - Ordered Queries on 10.1+ servers
    - IDs First otherwise

This would increase bandwidth usage for some users. Also, if there are many layers it may take more time to finish a particular layer since there are multiple workers downloading over the same bandwidth.

**Comment by AleksueiR** [comment]
We probably should not download any data upfront without the user triggering the download - imagine how much data it will eat on your mobile data plan if you open a heavy map. I'm all for using web-workers though.

**Comment by james-rae** [comment]
`table.service.js`, function `queryMapserver` is also affected by this. The logic here handles the grid-filter-by-extent (and likely soon to also handle filter by symbology), and uses the same sorting dependency to handle more results than the map server allows.

An alternate solution for this case is, when dealing with a server based layer, to not use the ESRI QueryTask and instead generate a raw ArcServer `/query` REST request.  The advantage here is we can leverage the `returnIdsOnly` flag, which removes the limit on the number of results returned. And Ids are all we need for this situation.

**Comment by mweech** [comment]
Edge case that has not been found elsewhere.  Closing unless need re-emerges to support this.
