### ISSUE TITLE
Create LegendItem class and supporting service

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2314]
:warning: idea in progress :warning: 

The external API needs a basic way to work with the legend. I propose a `LegendItem` class with the following properties:

- id (unique)
- name (as displayed in legend)
- children (array of other `LegendItem` that are direct children in the legend if any)
- isVisible (boolean)
- setVisibility (boolean) Only defined if setting visibility is possible

Instances of this class would be created alongside the actual `LegendNode` or `LegendSet` creation and saved in a service named `LegendItemApi`. This service would have a `getById` method which returns an instance of `LegendItem` with that id.

Instances of `LegendItem` will be passed to plugins when certain actions occur such as opening a table, or changing visibility. Plugins will also be able to request a `LegendItem` by id.

#### Used for

- Visibility toggle slider plugin
    - Get visibility set by id, `children` property contains `LengendItem`'s in the set used for populating slider
    - set the visibility  with `setVisibility` 

- host page custom header plugin
    - plugin service passes a `LengendItem` instance whenever visibility is turned on

**Comment by milesap** [comment]
Closing this for now due to time constraints - will implement a quick  "demo" solution that works for the time being

**Comment by AleksueiR** [comment]
Good point.
