### ISSUE TITLE
Unable to tab past data filters

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2320]
Steps:
- tab to a layer with data
- open datatable
- wait for it to load and the focus to shift to the datatable close button
- start tabbing (focus goes to the datatable filters)
- when tabbed to the input field in the last filter, focus gets stuck there, and then disappears
- further tabbing of shift+tabbing doesn't have any effect

**Comment by JahidAhmed** [comment]
WOMM, though it takes like 10 tabs for it to reach the body of the table

**Comment by JahidAhmed** [comment]
I think it's because of the double header that we have. Inside `dataTables_scrollBody` there's `thead` which isn't displayed that could be what it's tabbing to and taking those multiple tabs to reach the body

**Comment by AleksueiR** [comment]
Yeap, you are right - if you tab long enough, it eventually gets to the table data. Should exclude the second header from tab index.

**Comment by JahidAhmed** [comment]
Yeah, that seems like the way to go.

Also, noticed another problem. Tabbing in the body scrolls the headers along too but tabbing the headers doesn't scroll the body.

**Comment by AleksueiR** [comment]
It behaves the same way (scrolling headers and not body) for a vanilla datatable as well: https://datatables.net/examples/basic_init/scroll_x.html
