### ISSUE TITLE
Removed child layers re-appeared after applying BackToCart

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2333]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.1-1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

- Remove some child layers, for example Greenhouse gas emissions under CESI: Other group layer
- Click BackToCart
The above removed child layer came back again with the visibility setting to off.
![image](https://user-images.githubusercontent.com/18723160/29420671-9ddbe206-8340-11e7-82de-c73de2ba6047.png)

**Comment by james-rae** [comment]
Looks like duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2245

**Comment by IsabellaPan** [comment]
@james-rae Didn't realize that is still an open issue :)
