### ISSUE TITLE
Map export not finished loading

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2334]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.1-1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways

It seems legend, north arrow and scalebar could display.
![image](https://user-images.githubusercontent.com/18723160/29425531-92c7d86e-8351-11e7-8fde-38176fbc8c97.png)
![image](https://user-images.githubusercontent.com/18723160/29425601-dde19a10-8351-11e7-8c8b-a83745416051.png)

**Comment by JahidAhmed** [comment]
Map export seems to fail if there is any imported dynamic layer. 
Also tested on: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

**Comment by james-rae** [comment]
Fixed by #2448
