### ISSUE TITLE
No focus on close button when opening help panel

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2344]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

**Comment by JahidAhmed** [comment]
Focus is also not being applied on the close button for a layers `Metadata` and `Settings` panels

**Comment by milesap** [comment]
Likely something going on here https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/ui/common/dialog.decorator.js#L47
