### ISSUE TITLE
Viewer Incompatible with Canada.ca CDTS .NET Template

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2349]
More details to follow from @barryytm 

From what I recall, ESRI api is requesting its own version of jQuery, which fails when it collides with the jQuery on the host page. Our bundle also leaks jQuery, we should try and stop that if possible.

ESRI uses a dojo module loader which naturally doesn't work with any build tools. So I suspect webpack cannot replace calls to `window.jQuery` in ESRI code to our bundled version, so ESRI panics and requests its own version. Since our jQuery leaks, it would explain why esri doesn't download jquery on our sample pages. Need to look at why this is different for CDTS.

**Comment by barryytm** [comment]
The part in `CDTS` that collides with our `jQuery` was from the footer of  `GoCWebTemplate.Application.Master` in the `GoC.WebTemplate` folder which is using `WET` for footer building.  If we could not find a way to contain the `jQuery` from the `ESRI` API, one of the possible solutions is to contact the developers from `CDTS` to see if they can contain the `jQuery` from `WET` in their side.  As for now, we are currently using `iframe` to wrap around `FGPV` as a temporary solution.

**Comment by dan-bowerman** [comment]
A couple of other issues, unclear if these are configurable or supposed to work out-of-the-box:

- Header language toggle not working as expected
- “Report a problem” button returns a 404 (where should it go?)
- Contact Us link goes nowhere

Example page: http://maps-cartes.qa.ncr.ec.gc.ca/LWBSF-map/app/ramp2-en

**Comment by milesap** [comment]
The "hack" to fix the esri jQuery issue is to delay our viewer from loading until WET jQuery is loaded on the window. Something like the following:

```js
setInterval(function() {
    // check if window has jQuery, if so cancel this interval and
    document.write('<script src="rv-main.js"><\/script>');
}, 500);
```

ESRI is then happy it has some version of jQuery and doesn't load its own, WET template is happy for avoiding the need to scope jQuery, and we continue using our bundled version.

**Comment by barryytm** [comment]
@dan-bowerman I fixed the 3 problems you mentioned above

Page: http://maps-cartes.dev.ec.gc.ca/EcoGeo-Ramp2.0/App/ecogeo

**Comment by barryytm** [comment]
The broken link can be fixed in the `master` file that is being used at the footer and pre-footer sections.  The language language toggling problem was fixed by using key `GoCTemplateCulture`.

**Comment by mweech** [comment]
I suspect, and perhaps @alyec can better judge this.. Since we are using the .NET template, CDTS is rendering the header/footer templates first before the content area so WET's jQuery is always loading first.

**Comment by alyec** [comment]
The following cshtml page works with CDTS 4.0.25

```html
@{
    ViewBag.Title = "View";
    ViewBag.WebTemplateCore.HTMLHeaderElements.Add("<link rel='stylesheet' href='http://fgpv.cloudapp.net/demo/develop/prod/rv-styles.css'/>");
    ViewBag.WebTemplateCore.HTMLBodyElements.Add("<script src='http://fgpv.cloudapp.net/demo/develop/dev/rv-main.js'></script>");
    Layout = "~/Views/GoC.WebTemplate/GoCWebTemplate.Application.cshtml";
}

<h2>View</h2>

<div id="cdtsMap" style="height: 500px" is="rv-map" rv-config="http://fgpv.cloudapp.net/demo/develop/dev/samples/config/config-sample-01-structured-visibility-sets.json" ></div>
```
