### ISSUE TITLE
Name the Viewer Platform

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#236]
Putting ALL of the previously submitted names and acronyms into one issue:

* R2 - Release 2 Viewer
* TOMAHAWK - Thematic Online Mapping And Hopefully Accessible Web Kit
* SALSA - Try to find something to fit in French and English (reutiliSable et Accessible, la Librarie pour viSualiser des cArtes / reuSable and Accessible Library to viSualize mAps)
* CAMELOT - Customizable Accessible Mapping Experience Leveraging Online Toolkits 
* R2D2 - Release 2 Dynamap 2oolkit
* SPAM - Simple Platform for Accessible Mapping 
* ALEX - Accessible Localized ESRIMap Xperience
* ROADMAP - Reusable, Open, Accessible, Dynamic Mapping Application Platform
* FLAMINGO - Framework Leveraging Accessible Mapping Inspiring Nice Geography Online
* TOMCAT - Thematic Online Map Customizable Accessible Toolkit
* MEDUSA - Mapping Experience Delivering Usability, Sizzle & Accessibility
* OMEGA - Online Mapping Enhancing GIS & Accessibility
* AMAP - Accessible Mapping on the Angular Platform
* GUVMAP - Government of Canada's Unified Visualisation Mapping Application Platform
* GeoRAMP - GRAMPS
* GCMAP (or GCMaps) - Government of Canada Mapping Application Platform
* MATLAS - Mapping Application Toolkit for Lightweight Accessible Solutions
* CARTES - Canada's Accessible, Reusable Template for Esri Solutions
* GCOMVIS - Government of Canada's Open Mapping VIsualization Solution
* GCGeoMap - Not an acronym...
* GCWEBMAP - Government of Canada's WCAG-compliant Extensible Mapping Application Platform

**Comment by dan-bowerman** [comment]
Some English words and acronyms to use (just trying to clean up my junk notepad file):

Accessible / Application / Agnostic / Adaptable
Bilingual (?)
Configurable / Customizable / Canada / Collaborative
Data / Dynamic
Esri 
Federal / Framework
Geospatial / Government
H - 
Interactive / Integrated
JavaScript
K - 
Lightweight
Mapping / Mobile
N -
Open
Platform / Platform independent
Q - Don't use Q
Reusable
Solution / Straightforward / Simple
Thematic / Toolkit
Unified / User-friendly
Visualization
WCAG compliant / Web
X - eXperience
Y - 
Z - Don't use Z

**Comment by dan-bowerman** [comment]
Another good reference:
http://support.esri.com/en/knowledgebase/Gisdictionary/browse

**Comment by AleksueiR** [comment]
MapWidget(s)

**Comment by mweech** [comment]
RAMP 2.0
