### ISSUE TITLE
Make EPSG Online Projection Lookup an Extension

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2360]
Related to step 3 of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2234

We currently have our EPSG projection lookup [hardcoded in layer-blueprint.class](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.0.0/src/app/geo/layer-blueprint.class.js#L200). 

Would probably be better as a plugin. Would make sense to delay this until the upcoming plugin discussions happen (early Sept 2017).  See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2346

**Comment by milesap** [comment]
Issue moved to [fgpv-vpgf/core-extensions #1](https://github.com/fgpv-vpgf/core-extensions/issues/1) via [**ZenHub**](https://www.zenhub.com/)
