### ISSUE TITLE
Dynamic layer root group name is not defined (unless it's overridden)

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2364]
### Problem

When adding a dynamic layer to the map without collapsing the root group, the name of the root group is not being set at all. 

```json
      {
        "id": "14",
        "layerType": "esriDynamic",
        "layerEntries": [{"index": 15}],
        "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/"
      }
```

![](https://i.imgur.com/2RoGt7E.png)

You can see here that the root group does not have a name.

___

If you override the name in the config, everything is hunky-dory:

```json
      {
        "id": "14",
        "name": "Random name",
        "layerType": "esriDynamic",
        "layerEntries": [{"index": 15}],
        "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/"
      }
```
![](https://i.imgur.com/zWXZloi.png)

### Expected Behaviour

In this example, If the name if not set by the config, I would expect it to be `Energy Infrastructure of North America` as specified in http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/.

![](https://i.imgur.com/d8y1tQO.png)

Thoughts?

**Comment by mweech** [comment]
i think this is working as expected.  if you leave out a name, no name appears.
