### ISSUE TITLE
App bar does not close properly after clicking on the layers button a few times in a certain frequency  

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2366]
![capture2](https://user-images.githubusercontent.com/19259169/30278569-b11e2cec-96d8-11e7-9abe-9584301570f1.PNG)

Tested page: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html
![capture3](https://user-images.githubusercontent.com/19259169/30278643-ee9e268a-96d8-11e7-87a0-3a9856744423.PNG)

Tested page: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html
![capture](https://user-images.githubusercontent.com/19259169/30278496-795b1d60-96d8-11e7-9fe5-ee968ea43e37.PNG)

**Comment by AleksueiR** [comment]
The panel opening functionality is debounced: it will close or open on the first click and ignore all subsequent clicks spaced less than 175ms apart. If this is what you are referring to, it's be design. :dancer:

**Comment by JahidAhmed** [comment]
I don't think that's exactly what he was referring to, the bar just goes completely white without any clickable components

**Comment by AleksueiR** [comment]
This would be a :bug: then. 
@barryytm can you make a gif of that? I can't seem to reproduce it.

**Comment by AleksueiR** [comment]
Thanks, @JahidAhmed 
![](https://files.gitter.im/JahidAhmed/yuPn/thumb/bar.gif)

The app bar doesn't go blank, it gets pulled up too far by having a `transform` applied to the whole panel for some reason , so you only see a sliver of it (if the legend is short, it looks white).
```css
    transform: translate(0%, -100%) matrix(1, 0, 0, 1, 0, 0);
```
![](https://i.imgur.com/fAC7QAl.png)
