### ISSUE TITLE
Export image - unbound layers and info section decision

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2367]
Need to decide whether unbound layers and info sections should be included in the export image

**Comment by AleksueiR** [comment]
Instead of unilaterally deciding to include them or not, what if we add a config option to the info blocks to include them in the export legend?

**Comment by JahidAhmed** [comment]
Oh yeah, I believe @james-rae had the same idea

**Comment by AleksueiR** [comment]
We also might not want to include hidden layers' symbology in the export image.
If the config author wants to include a layer on the map and not include its symbology in the legend, it makes sense not to include that symbology in the exported image as well.
