### ISSUE TITLE
Changing opacity of child of entryGroup invalidates opacity of parent

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2372]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html (Sample 5)

Steps to reproduce:
- Open settings panel for parent; `Renewable Energy Source`: opacity is 100
- Enable visibility for `Solar` (just for visual purposes later on)
- Change visibility for either of the children; `Solar` or `Wind`
- Open settings panel for parent; `Renewable Energy Source`: opacity is now 50
- The opacity is the children is still correct (whatever it was before) even though this now shows 50

**Comment by JahidAhmed** [comment]
Just noticed this is by design, the defaultVaule is 0.5 and that is being set since all of the entries opacity is not the same

**Comment by AleksueiR** [comment]
Yes, this is by design. I would prefer to change the state of the parent's slider to some "indeterminate" state, similar to such a checkbox:
![](https://i.imgur.com/0AeEVnE.png)

Unfortunately, the Angular slider doesn't support anything like that.
