### ISSUE TITLE
Render markdown of info sections in the export image

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2392]
#2389 adds export support to legend info sections, but markdown content can only be represented as plain text so far:
![](https://i.imgur.com/R8qHasR.png)

There are some options to implement that:
- find or build a markdown-to-svg/canvas converter :) maybe use something like [spongedown](https://ivanceras.github.io/spongedown/)
- [draw rendered markdown html to a canvas by wrapping it in an svg element](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas)
- ~~use [html2canvas](https://github.com/niklasvh/html2canvas) library or something similar to create canvas representations of rendered info sections~~
  - bad solution - if we turn info sections straight into images and then add them to the legend, the legend might further scale the images to fit in the export legend column. This will distort the text, potentially making it illegible. 

The last one seems the most promising - at least it should fast to check if this approach works or not.

Highcharts seems to use a server call to export their graphs as images. Moreover, their graphs are rendered as svg from the start, so all the labels and their styling are svg-based, and are relatively easy to draw on a canvas as is.

**Comment by milesap** [comment]
I have a working solution that uses a maximum width of 200 and an estimated variable height. Text can be different sizes, depending on how its scaled - but scaling appears to maintain proper aspect ratios. 

Let me know if this is ok. Ideally we would have text all the same size, but we don't know the scaled sizes until after rendering is complete. We could possibly wait for the rendering to complete and then substitute all markdown, but we would need to also compute the smallest text size across all info sections so text is uniform and none go out of bounds.

#### Current Layout 

![control](https://user-images.githubusercontent.com/10187181/30857916-95ac79d2-a28b-11e7-8f4c-9a395181ab9c.png)

#### Markdown Rendered Layout

(working on reducing top/bottom "padding")

![rendered](https://user-images.githubusercontent.com/10187181/30857933-a0719230-a28b-11e7-9493-90542f76e20c.png)

**Comment by mweech** [comment]
you forgot the lazy james option: strip markdown from export map output and format as plain text.

**Comment by AleksueiR** [comment]
We discussed that option extensively. It's a fallback if nothing above works satisfactory.

**Comment by mweech** [comment]
I like the idea that you guys extensively discussed doing nothing. :+1:
