### ISSUE TITLE
Info section images are not resizes correctly

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2393]
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2389 added support for info sections to be included in the export image, and some of the info section images are not resized correctly:
![](https://i.imgur.com/RaoD6Gt.png)

The large `6 Reasons to be thankful for your cat` should be scaled down to fit in the column.

**Comment by barryytm** [comment]
I think the problem has been solved.  Tested on http://fgpv.cloudapp.net/demo/v2.2.0-daily07/dev/samples/index-mobile.html.
