### ISSUE TITLE
Importing an incorrect file by means of URL, status bar appearing

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2394]
In the import file menu, if we type in some invalid input, the continue button is still disabled but hitting enter throws an error but still shows the progress bar (which now does not disappear).

The progress bar remains there even if we press cancel or close the menu and reopen it.

It should not appear at all for invalid input.

**Comment by AleksueiR** [comment]
Shouldn't we just disallow pressing `Enter` if the input value is invalid?

**Comment by JahidAhmed** [comment]
Yeah, that works too

**Comment by AleksueiR** [comment]
Do you have a sample URL handy?

**Comment by JahidAhmed** [comment]
http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/G%C3%A9ochronologie.csv

**Comment by AleksueiR** [comment]
It seems that pressing `Cancel` doesn't really cancel file loading at all. If you wait, the file will load and the wizard proceeds to the second step.

![load_file](https://user-images.githubusercontent.com/2285779/30710270-03fd7b6e-9ed3-11e7-92a5-60bcaf8ea792.gif)

**Comment by AleksueiR** [comment]
Actually, this happens when importing a service:
- open import service wizard
- set focus to the url input field
- press enter
- observe `Service does not respond` and some Chrome-specific tooltip
- check console and see more errors

![](https://i.imgur.com/sBujaQm.png)

**Comment by AleksueiR** [comment]
Everything's good now 💃
