### ISSUE TITLE
Bug/New Feature - Cant clear focus from "Zoom To Feature"

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2395]
Presently, when you click on "Zoom to Feature" in the table, you are zoomed to the feature and all the other features are faded out, which is a great functionality.

Unfortunately, there is no way of clearing the focus without clicking on the map, which executes a Get Feature info request.

It would be nice to have a button or something to clear the focus.

**Comment by AleksueiR** [comment]
You can pan the map a little to remove the higlight:
![zoom_and_pan](https://user-images.githubusercontent.com/2285779/30715921-08ec0560-9ee6-11e7-98ba-0ff937870247.gif)

This was implemented under https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1386.

**Comment by AleksueiR** [comment]
A possible solution - the click on the map while a feature is highlighted simply removes the highlight without triggering an identify query. 

![identify_highligh_and_the_mouse_click](https://user-images.githubusercontent.com/2285779/30742918-7309bb30-9f69-11e7-9bb0-7730b46f2377.gif)

Here is the demo: http://fgpv.cloudapp.net/demo/users/AleksueiR/2395-identify-click-identify/prod/samples/index-samples.html
Please, check it out.

**Comment by mweech** [comment]
Click to disable the highlight is a good compromise.  Fallback option would be a timeout... where it reverts back eventually.

**Comment by AleksueiR** [comment]
We are waiting for the feedback from the user requesting this change.

**Comment by yblain** [comment]
After verification with the group that brought the issue. It seems like a satisfactory solution.
