### ISSUE TITLE
attribution not working properly

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#2397]
There's two problems here:
1- If attribution is put on default basemap, it won't appear at load time. However, it can be displayed by clicking on the corresponding basemap in the sideMenu;
2- The custom attribution doesn't replace the one coming from the server, it is just added to it.
```
"attribution": {
          "text": {
            "enabled": true,
            "value": "Here's my attribution"
          },
          "logo": {
            "enabled": false
          }
        }
```
![attribution](https://user-images.githubusercontent.com/16193004/30746069-75bef072-9f76-11e7-9797-4177a7879cd6.gif)
Tested on version 2.1.0 [55fb54dc7]

**Comment by barryytm** [comment]
Should users have the option of replacing/turning off the logo and copyright?  From https://developers.arcgis.com/terms/attribution, it stated that Esri attribution should be included when using their services or technology.  If we do allow the option, should we also include a disclaimer or some sort to warn the users?

**Comment by mweech** [comment]
it is the responsibility of the individual deploying the application to make sure attribution is correct.  we should not be enforcing this through code.  i would agree with a warning in configuration so they know what they are doing though.

**Comment by AleksueiR** [comment]
An option to replace the existing copyright makes sense. As for the disclaimer, it should be noted in the config schema and in the authoring tool.

**Comment by AleksueiR** [comment]
I'm not sure what's wrong with setting attribution: `config-1` on `index-samples.html` doesn't have any attributions specified, but it still changes when the basemap is reloaded.

```json
"baseMaps": [
      {
        "id": "baseNrCan",
        "name": "Canada Base Map - Transportation (CBMT)",
        "description": "The Canada Base Map - Transportation (CBMT) web mapping services of the Earth Sciences Sector at Natural Resources Canada, are intended primarily for online mapping application users and developers.",
        "altText": "altText - The Canada Base Map - Transportation (CBMT)",
        "layers": [
          {
            "id": "CBMT",
            "layerType": "esriFeature",
            "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer"
          }
        ],
        "tileSchemaId": "EXT_NRCAN_Lambert_3978#LOD_NRCAN_Lambert_3978"
      }
]
```
![attrib](https://user-images.githubusercontent.com/2285779/31084965-db2b82b4-a763-11e7-98d0-dff5f0f8077b.gif)

**Comment by barryytm** [comment]
The attributions are the same but in a different order.  I have consulted with @james-rae and turned out that the attributions were appended in the ESRI api therefore we don't have control of it.  Therefore we are not able to control attributions that are not custom.

**Comment by barryytm** [comment]
Replacing the attributions would cause an error from ESRI, therefore we can only append it to what it had originally rather than replacing the default attributions.

**Comment by AleksueiR** [comment]
@ChrisLatRNCan can you check the [PR demo](http://fgpv.cloudapp.net/demo/users/barryytm/2.1.0-2397/prod/samples/index-samples.html) and see if this solutions satisfies you? Thanks.

**Comment by ChrisLatRNCan** [comment]
@AleksueiR no problem !

**Comment by phuppe** [comment]
On the PR Demo, it looks like the custom attribution is shown from the start withoiut having to select a basemap,  This is good.  I am seeing the ESRI logo there which should not be visible when we use the NRCan basemaps, but I assume that this is because it is not set to "false".  Is this correct?

**Comment by barryytm** [comment]
@phuppe Yes, that is correct.  It would look like the fellowing if logo->enable is set to false.

![capture](https://user-images.githubusercontent.com/19259169/31448021-630aa2f0-ae71-11e7-800c-251c1357f33d.PNG)
