### ISSUE TITLE
Pressing "Enter" doesn't disable "Continue" button when loading a service

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2405]
Found strange behaviour not present before.
Steps:
- enter incorrect service url
- press enter
- see the try failed with "Service does not respond" message
- remove url and paste it back again
- press enter
- observe the "Continue" button is still active (pressing more times doesn't help)
- the "Continue" button becomes disabled after some time passes

Note: 
> This only seem to work if the network is slow. You can replicate this by using the `throttling` option in Chrome dev tools.

![import-service-enter-presses.gif](https://files.reviewableusercontent.io/images/reviewable/2285779/9wNBqUHqGwAdlulNv2O4A2il/import-service-enter-presses.gif)

**Comment by mweech** [comment]
Cannot reproduce
