### ISSUE TITLE
'Show All' button functionality

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2409]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html (Sample 1)

Toggling the visibility to 'Show All' should then disable the button.

Seems to be happening due to visibility sets (only one child can be visible so the remaining are not shown, and thus 'Show All' is not disabled)

**Comment by mweech** [comment]
Not worth fixing.
