### ISSUE TITLE
2.1.0 Samples for testing

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2415]
http://fgpv.cloudapp.net/demo/v2.1.0-daily02/dev/samples/
- [x] [#TM9] A map layer entry can have a description defined which will appear beneath the layer title and above the layer symbology when expanded (#2260) Sample#50
- [x] Enable coordinates for `index-fgp-en.html`

**Comment by bkutty** [comment]
Please create a new sample for Sample#43-Customised map title should appear on the Left layer menu

**Comment by barryytm** [comment]
@bkutty Please see sample#44, it contains a customized logo and viewer title.

**Comment by IsabellaPan** [comment]
Please enable coordinates when building the viewer index-fgp-en.html

**Comment by bkutty** [comment]
Please create a sample to test #2384
