### ISSUE TITLE
Unable to import CSV file

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2422]
Tested build: http://fgpv.cloudapp.net/demo/v2.1.0-daily02/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,NPRI_CO,Railways
Test data: rc_cdr.csv

In step 2 of Import File wizard, it displayed "Incorrect file format" upon clicking Continue button.
![image](https://user-images.githubusercontent.com/18723160/31550974-1aa0118a-b001-11e7-8aa7-9996939b1bda.png)

**Comment by JahidAhmed** [comment]
WOMM. Can someone else test.

**Comment by bkutty** [comment]
I get this too. However, test and test2.csv works. Could it be due to #2254 ?
