### ISSUE TITLE
Navigation Controls Zooming no effect

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2423]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

Steps to reproduce: (might take a few tries to reproduce)
- Press the 'Zoom Out' button (or zoom in)
- Press 'Canada' (home button)
- Quickly press one of the zooming buttons; the buttons stop working due to an uncaught promise.

![navigation](https://user-images.githubusercontent.com/9637542/31609656-113de088-b243-11e7-8806-875aaf81aab1.gif)

**Comment by dane-thomas** [comment]
Couldn't reproduce this issue in http://fgpv.cloudapp.net/demo/v2.5.0-b1/dev/samples/index-samples.html. Zoom doesn't stop working but there does seem to still be an uncaught promise. It looks like the issue originates from the ESRI api.

**Comment by AleksueiR** [comment]
I think this one might have been solved by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2730.
