### ISSUE TITLE
Metadata for EcoGeo non responsive

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2426]
Tested site:  http://fgpv.cloudapp.net/demo/v2.1.0-daily02/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction

Metadata for EcoGeo child layers (nature/Climate Change/Clean Water and Clean Air) is not loading. Below is what  I see in the console window. Please investigate

![image](https://user-images.githubusercontent.com/18539315/31628918-0dfab3b4-b280-11e7-9c7b-44b27b47739d.png)

**Comment by dan-bowerman** [comment]
Appears to be an issue on the live RAMP2 app as well, though Comms has not yet switched from RAMP1 to RAMP2, so regular users won't be noticing this just yet.

Here are the metadata records. For the demo builds, I think we just need to update in RCS, the for the live application, we need to update CDTS anyways, so I'll sneak it in there too.

English:
http://open.canada.ca/data/en/dataset/2c51ad60-d6fa-4d61-a998-1968d3a4409b
http://ouvert.canada.ca/data/en/dataset/2c51ad60-d6fa-4d61-a998-1968d3a4409b.xml

French:
http://open.canada.ca/data/fr/dataset/2c51ad60-d6fa-4d61-a998-1968d3a4409b
http://ouvert.canada.ca/data/fr/dataset/2c51ad60-d6fa-4d61-a998-1968d3a4409b.xml

**Comment by mweech** [comment]
RCS issue, not a bug.
