### ISSUE TITLE
Filter by Extent icon missing in some layers

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2427]
Tested URL: http://fgpv.cloudapp.net/demo/v2.1.0-daily02/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction

Filter by Extent icon is missing for layers added through RCS keys. It seems to be working for some user added layers though. Please check.

- Open the data panel for JOSM layer
- Enable "Filter by Extent" option
- Data is filtered now
- No icon present in the legend panel to indicate the data is filtered

![image](https://user-images.githubusercontent.com/18539315/31632358-a9b24308-b28a-11e7-9e63-74e0d9fc29d7.png)

**Comment by JahidAhmed** [comment]
I believe the icon functionality was changed so it only shows for table filters and not when filtering by extent.

**Comment by mweech** [comment]
better to have 2 different icons, 1 to reflect extent filtering and 1 to reflect datagrid filtering.
