### ISSUE TITLE
Export not loading basemap and feature points in Mercator projections

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2430]
Tested build: http://fgpv.cloudapp.net/demo/v2.1.0-daily03/dev/samples/index-samples.html

See below screenshot. Export works with Lambert projections though.
![image](https://user-images.githubusercontent.com/18723160/31734983-69f274d8-b40e-11e7-84b0-04ae8804ba50.png)

**Comment by barryytm** [comment]
This issue has been resolved by changing the print service to asynchronous.

**Comment by barryytm** [comment]
Please see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2448 for more details.
