### ISSUE TITLE
Export doesn't work with ESRI World Street Map basemap

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2432]
The viewer export window never stop processing and I get this is the error message...

We have the same problem with all ESRI basemap from ArcGIS online

{"jobId":"j1effd7b57e3e4ebd8096f453b0ca3e19","jobStatus":"esriJobFailed","messages":[{"type":"esriJobMessageTypeInformative","description":"Submitted."},{"type":"esriJobMessageTypeInformative","description":"Executing..."},{"type":"esriJobMessageTypeError","description":"Layer \"layer6\": Unable to connect to map server at http://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer."},{"type":"esriJobMessageTypeError","description":"Could not determine encoding"},{"type":"esriJobMessageTypeError","description":"Failed to execute (Export Web Map)."},{"type":"esriJobMessageTypeError","description":"Failed to execute (Export Web Map Task)."},{"type":"esriJobMessageTypeError","description":"Failed."}]}

**Comment by james-rae** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2265

@barryytm found that while the Print Server would return the failed message, the ESRI API Print Task / Dojo Deferred would never trigger the success or failure handlers, resulting in the screen staying in the processing mode.  We tried restructuring the code a number of ways to get the event to trigger but were not successful.

**Comment by james-rae** [comment]
Possibly also related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2261 , https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2334

**Comment by barryytm** [comment]
This issue has been resolved with changing the print service to asynchronous.

**Comment by barryytm** [comment]
Please see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2448 for more details.
