### ISSUE TITLE
Sample files not working after 2424

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2434]
Some of the sample files are not working after https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2424.

**Comment by AleksueiR** [comment]
`index-samples` can no longer reload config files. When attempted, it fails with the following:
> geo.service.js:80 geoService failed to assemble the map with error Error: Attempted to access config synchronously before loading completed.  Either use the promise based API or wait for rvReady.
    at e.get (config.service.js:204)
    at Object.f [as makeMap] (map.service.js:106)
    at geo.service.js:60
    at <anonymous>

**Comment by AleksueiR** [comment]
Related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2442
