### ISSUE TITLE
Synchronize Grid and Symbol Filters on Map

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2438]
Related to the Symbol Filter implemented in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2368

When applying a filter to a map layer, the current logic will over-write any filter that was put there by a different module (in particular, the legend and the grid "apply" clobber each other).

Case 1: After adding a grid filter and clicking apply on the datagrid, then changing the legend filter, the applied filter is lost on the map. This might be an OK behaviour, as the Apply button is sort of a one-way street. But we could also look at preserving any existing grid filter when applying legend filters. Legend guts would need a way to ask the grid if it has an active filter, and get the query string from it (connect them with an OR i think?)

Case 2: Do some legend filters. Then do a grid filter and click apply. The map loses the legend filters. This one is probably bad because the map doesn’t match the checkboxes in the legend. So a bit of the same, when applying the grid filter, need to tack on any legend filters that are existing.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Issue resolved.
