### ISSUE TITLE
Create Sample Layer with Default Symbology

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2440]
Related to the Symbol Filter implemented in #2368 

Need to create a layer with a class breaks or unique value renderer (maybe a sample of both), and have the default symbol enabled. 

Test code to ensure it handles it correctly (legend symbol list, details pane icon, grid icon, hovertip icon, symbol filter)

**Comment by barryytm** [comment]
Layer with unique balue renderer and default symbol:
http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/Sandbox/defaultSymbol/MapServer/0
