### ISSUE TITLE
Unable to Export Map

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2448]
Tested build: http://fgpv.cloudapp.net/demo/v2.1.0-daily05/dev/samples/index-fgp-en.html?keys=EcoAction,CESI_Other

Export seems to be loading indefinitely. Only legends are visible in the export window. Please investigate

![image](https://user-images.githubusercontent.com/18539315/32060605-436167ea-ba3d-11e7-9852-ad06424e75ff.png)

**Comment by AleksueiR** [comment]
Export works for Lambert maps on the `index-samples.html` page but not on the `index-fgp-en.html`.
Export doesn't work for the Mercator maps on both pages.

**Comment by barryytm** [comment]
#2432, #2334, #2265, #2261 Probably the same issue

**Comment by barryytm** [comment]
Export on many of the older versions of the viewer are not currently working.  Prossibly cause by the failure of printing service.

![capture](https://user-images.githubusercontent.com/19259169/32519184-ea685184-c3d9-11e7-9fbf-0a78d3ca267d.PNG)

**Comment by barryytm** [comment]
http://maps-cartes.dev.ec.gc.ca/EcoGeo-Ramp2.0/App/ecogeo is the only version I found that is currently working.

**Comment by JahidAhmed** [comment]
I want to say ecogeo is working because they're all Feature Layers but I'm not sure if that theory was debunked previously; trying `index-samples` Sample 1 with only one of the feature layers visible correctly displays the export map but turning visibility on for `crops` and trying again breaks it

**Comment by AleksueiR** [comment]
Is it the same error of not being able to talk to the server in all non-working cases?

**Comment by JahidAhmed** [comment]
This could be completely off but by the looks of it, if the layers geometry type is not `esriGeometryPoint` (or maybe more specifically, if it is `esriGeometryPolygon`) and it's imported as a dynamic layer; it's failing. 

Sample 3 has dynamic layers where the export works but they are points. Importing protected areas as a feature layer the export works but as dynamic the export fails and its polygons.

**Comment by barryytm** [comment]
@AleksueiR No, not all.  Some of the non-working cases are related Dojo Deferred not working properly which caused errors to not even appear on the console.  However those errors were returned as a form of response.

**Comment by james-rae** [comment]
As a service to test as a baseline, try [Province Boundaries Polygon](http://maps-cartes.ec.gc.ca/arcgis/rest/services/Common/CommonGIS_AuxMerc/MapServer/0). It's very simple, will help determine if it's polygons in general, or massive amounts of huge polygons (which is what Protected Areas is).

**Comment by JahidAhmed** [comment]
Seems to be polygons in general

**Comment by barryytm** [comment]
There are currently 2 known cases what would cause export failure

- Layers containing polygons render as a dynamic layer in the viewer
- The print service being used is not working

**Comment by AleksueiR** [comment]
Polygon layers rendered as dynamics will be sent to the printing server, not rendered locally as actual Feature layers. Can we try running print services against such a polygon-as-dynamic layer outside RAMP to see if it works in principle?

**Comment by barryytm** [comment]
I've tested all the print services, here is the result.

- http://utility.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task `not working`

- http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task `not working`

- http://maps-cartes.ec.gc.ca/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task `not working`

- http://section917.cloudapp.net/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task `not working`

- http://webservices.maps.canada.ca/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task `working`

Seems like there is only one print service that is currently working.

**Comment by JahidAhmed** [comment]
Following up on my comment above, it isn't working for dynamic polylines or multipoints either so it looks like it only works for points

**Comment by james-rae** [comment]
Have made a simple testing page dedicated to printing.  Click the map to trigger a print.

Feel free to make copies for additional tests. On the devmap webroot share (ends with $), in folder Sandbox\printguts\

http://maps-cartes.dev.ec.gc.ca/sandbox/printguts/printguts.html   (poly)
http://maps-cartes.dev.ec.gc.ca/sandbox/printguts/printpointguts.html

I've actually yet to get a successful print. 
I've tried using the dotnet proxy (in the above folder), and the proxy we use in RAMP2.
It's possible there is something dumb in the code, but so far all the prints give the same experience we were having with RAMP: server failure message, dojo deferred ignores it and waits forever.

Still lots of things to persue. I'll probably google these error messages, can try these samples against different print servers, etc.

**Comment by barryytm** [comment]
Found http://support.esri.com/en/technical-article/000012706.  It suggested that the firewall is blocking the connection.  Not sure if this has to do anything with the issue.

**Comment by barryytm** [comment]
Try these layers on the print service http://webservices.maps.canada.ca/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task

- http://webservices.maps.canada.ca/arcgis/rest/services/NRCan/abandoned_mines_information_system_database_en/MapServer

- http://webservices.maps.canada.ca/arcgis/rest/services/CFIA/emerald_ash_borer_regulated_areas_en/MapServer

- http://webservices.maps.canada.ca/arcgis/rest/services/StatCan/national_agricultural_ecumene_of_canada_2001_en/MapServer

They all work.  My theory is that since they have be from the same version/domain of the service for them to work.

**Comment by james-rae** [comment]
http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/ also prints, and it is 10.5 . But it still may suggest that the problem is with servers (seems to be issues with our production, and ESRI's basemap server).  Need to find more test subjects to narrow things down.

**Comment by JahidAhmed** [comment]
It appears section917 services and the ones on the dev server are not working regardless of geometry type or service tried.

Tested (on the test page, not the viewer) some geoappext.nrcan services and noticed certain services were working and some were not ..

Worked: 
- http://geoappext.nrcan.gc.ca/arcgis/rest/services/NRCAN/coverage_HRDEM_en/MapServer/0
- http://geoappext.nrcan.gc.ca/arcgis/rest/services/EGS/Communication_Towers/MapServer/0

Didn't work:
- http://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCA/basin_e/MapServer/5 (However, this worked on develop branch for the viewer; but an error displayed in the console mentioning service has no OID defined)

Tried services from [here](http://gis.lethbridge.ca/lethwebgisarcgis/rest/services/OpenData) but none of them returned any type of response; could be because of the version as Barry mentioned.

**Comment by james-rae** [comment]
I'm able to get the GSCA/basin_e/Mapserver/5 to print on my test. You just need to not use a proxy.  The OID error is from RAMP because the service is lacking it; the grid / symbology / tooltips would be busted for that layer.   Far as I can tell, geoapext has no issues printing across that server.

**Comment by barryytm** [comment]
If the print job is done at the rest end point, it will work.

Example:
http://section917.cloudapp.net/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/execute

**Web Map as JSON**: `{"mapOptions":{"showAttribution":false,"extent":{"xmin":-6729590.577216155,"ymin":-3895727.6402082806,"xmax":7121374.624714251,"ymax":3128973.9091948187,"spatialReference":{"wkid":3978}},"spatialReference":{"wkid":3978}},"operationalLayers":[{"id":"layer0","title":"layer0","opacity":1,"minScale":145000000,"maxScale":17500,"url":"http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer"},{"id":"esriDynamic#1","title":"esriDynamic#1","opacity":1,"minScale":0,"maxScale":0,"url":"https://sampleserver6.arcgisonline.com/arcgis/rest/services/Military/MapServer","visibleLayers":[2]}],"exportOptions":{"outputSize":[1745,885],"dpi":96}}`

**Format**: `jpg`

**Layout Template**: `MAP_ONLY`

**Comment by barryytm** [comment]
Found a print service that is not from us that works when using it via RAMP:
http://gis.brevardcounty.us/gissrv/rest/services/Print/ExportWebMap_async/GPServer/Export%20Web%20Map

**Comment by james-rae** [comment]
@barryytm discovered why most print servers fail to work. They are configured to execute synchronously, while RAMP requests asynchronous processing. 

This is a good find, but still does not explain the `Could not determine encoding` errors we get on valid asynch print calls.

**Comment by dan-bowerman** [comment]
I enabled this on section917's print service, and it worked like a charm on CESI.
http://section917.cloudapp.net/arcgis/rest/services/Utilities/PrintingTools/GPServer

I have also set the message level from "Error" to "Info" which should provide more verbosity on the status of exports when using the service. 

![image](https://user-images.githubusercontent.com/5294596/32679763-9e35f0e2-c635-11e7-9394-8bf88eba6224.png)

**Comment by dan-bowerman** [comment]
I also wonder if the max number of services returned (default is at 1000) could be at play here? If we upped it to something high on a non-async service, would it work more often? We're usually playing with pretty heavy data, but I think James' simple layer tests were working fine?

**Comment by mweech** [comment]
leave open until print services are updated to asynchronous, RAMP sample pages are updated and documentation is added to capture the dependency.
