### ISSUE TITLE
Legend display in Export does not reflect the toggling of renderer visibility

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2449]
Tested build: http://fgpv.cloudapp.net/demo/v2.1.0-daily05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

For JOSM layer, if users only toggle visibility for couple of symbologies as below screenshot, Legend displayed in Map Export still included all symbologies, and not filtered via their individual symbology toggling (2nd screenshot)
It seems Acceptance Criteria in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2368 are not quite clear regarding Legend display in Export.

![image](https://user-images.githubusercontent.com/18723160/32068423-5070c888-ba54-11e7-949b-6894592c8bc5.png)
![image](https://user-images.githubusercontent.com/18723160/32068847-69816a98-ba55-11e7-9aee-1dec0c4dae62.png)

**Comment by AleksueiR** [comment]
This refers to the export functionality:
> 8. Print map legend output will not omit hidden layer renderers from the legend, however the map itself will reflect the current visibility state.

From the above I understand the legend display in the export image should include all renderers, even ones which are toggled off. the behaviour seems to be correct.

**Comment by IsabellaPan** [comment]
@AleksueiR 
My understanding for Acceptance Criteria Item 8 is about Print function for Datagrid as below screenshot.
Should we clarify with Mike?
![image](https://user-images.githubusercontent.com/18723160/32230442-8f8f7554-be29-11e7-98bd-c6b0de9dae51.png)

**Comment by AleksueiR** [comment]
Printing from the datatable will just print the data visible in the table at the moment. I don't think it has to do with the legend display.

@mweech can you clarify please?
