### ISSUE TITLE
Symbology description overlapped with renderer visibility checkbox in certain French scenario

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2452]
Tested build: http://fgpv.cloudapp.net/demo/v2.1.0-daily05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

Add sub-layer "Émissions de gaz à effet de serre..." under Other Air Indicators to the map.
![image](https://user-images.githubusercontent.com/18723160/32073050-bde0fa10-ba62-11e7-999d-4aacd12f7207.png)

**Comment by AleksueiR** [comment]
The description should be truncated.

**Comment by james-rae** [comment]
Appears to have been fixed sometime prior to release of `v2.3.0`.
