### ISSUE TITLE
Symbology toggles are missaligned

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2454]
Latest [develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html).

![](https://i.imgur.com/mBiW6qX.png)

**Comment by IsabellaPan** [comment]
It becomes more serious in build v2.2.0 daily00, see below:
![image](https://user-images.githubusercontent.com/18723160/32329535-c25b4202-bfb3-11e7-81fb-130aa3599dd9.png)
