### ISSUE TITLE
Improve symbology toggles behaviour

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2456]
The behaviour of the symbology toggles is inconsistent with the layer group/child behaviour found elsewhere in the layer selector. Suggested improvements below:

| current                                      | improved                                 |
| ---------------------------------------- | ---------------------------------------- |
| Turning the layer "off" has no effect on symbology toggles. | Turning the layer "off", turn all the symbology toggles off. |
| ![ehn_symbology_toggles_1](https://user-images.githubusercontent.com/2285779/32109775-ae43f818-bb03-11e7-85f2-6650297c9cfd.gif) | ![ehn_symbology_toggles_2](https://user-images.githubusercontent.com/2285779/32109776-ae5961bc-bb03-11e7-8d90-b1a48dba9f60.gif) |
| Turning all symbology toggles "off" has no effect on the parent layer. | Turning all symbology toggles "off", turns the parent layer "off" as well. |
| ![ehn_symbology_toggles_3](https://user-images.githubusercontent.com/2285779/32109779-ae68e92a-bb03-11e7-9a54-8fffd85720c4.gif) | ![ehn_symbology_toggles_4](https://user-images.githubusercontent.com/2285779/32109780-ae78eda2-bb03-11e7-9b31-8810705d8e67.gif) |
| Turning a single symbology toggle "on" when all other toggles and the parent layer itself are "off" has no effect on the parent layer. | Turning a single symbology toggle "on" when all other toggles and the parent layer itself are "off" turns the parent layer back "on". |
| ![ehn_symbology_toggles_5](https://user-images.githubusercontent.com/2285779/32109781-ae8ce776-bb03-11e7-9e13-0e8b2148fffa.gif) | ![ehn_symbology_toggles_6](https://user-images.githubusercontent.com/2285779/32109774-ae31e056-bb03-11e7-84f8-747eb4bba359.gif) |

**Comment by JahidAhmed** [comment]
Regarding the first one, based on current functionality, with the layer visibility off, we still see results in the table. However, if we modify it to toggle the symbology off when the layer is toggled off, the datatable will filter everything out and show no results whenever the layer is not visible. Is that behaviour fine?

**Comment by AleksueiR** [comment]
That's a very good question. Maybe we can discuss this during our next RAMP meeting.

**Comment by AleksueiR** [comment]
> Miles Petrov @milesap 13:19
I just had a pod discussion and think that toggling symbology off should mean:
its not displayed on the map
does not appear in identify
will not be shown in datatables
Which leads to the road that if a layers visibility is off, then its datatable is empty (or we just dont give the option of the table)
otherwise visibility means different things in different parts of the viewer
