### ISSUE TITLE
User added JSON layer - Name column missing data in Datagrid

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2460]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily00/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Test data: happyEnhance.json

![image](https://user-images.githubusercontent.com/18723160/32282957-696de4b6-bef9-11e7-994d-02a8aed79b7c.png)

**Comment by barryytm** [comment]
Couldn't replicate this this behavior

**Comment by barryytm** [comment]
Couldn't reproduce this behavior

**Comment by JahidAhmed** [comment]
Still happening on my machine, on develop. Text only appears when you click on it; seems to be an issue with how the HTML is rendered 

![image](https://user-images.githubusercontent.com/9637542/33610868-940a01f8-d99a-11e7-8791-157c3a070a8e.png)

**Comment by barryytm** [comment]
Tried the wrong file.   @JahidAhmed you are right, it is still an issue.  It's not just an issue on IE but on Chrome as well.  However it is partially working on Firefox.

![capture](https://user-images.githubusercontent.com/19259169/33612155-b4c40232-d99e-11e7-93a2-211a2aead7e7.PNG)
