### ISSUE TITLE
Legend visibility  icon  is not properly aligned  for JOSM layer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2464]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily00/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Related #2368 

Issue seen in Chrome & Firefox.  Legend visibility icon is not aligned/hidden partially for this layer.  This issue is not seen on initial load. But once you switch to full screen, alignment goes off.Please investigate

Test data: JOSM Layer

![image](https://user-images.githubusercontent.com/18539315/32374804-945fa81c-c075-11e7-9da9-936668f9babe.png)

**Comment by milesap** [comment]
Should be fixed on PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2462
