### ISSUE TITLE
Header title needs to be truncated in French

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2467]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily01/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,mb_colour

Is it possible to have the header title panel and feature detail panel to be of the same width. There is an inconsistency  now. This issue is only seen in French. 

![image](https://user-images.githubusercontent.com/18539315/32380332-38902514-c086-11e7-85d0-5d185a386315.png)

**Comment by AleksueiR** [comment]
Is it possible to pick a different translation that will fit?

**Comment by mweech** [comment]
@yblain thoughts on @AleksueiR comment?

**Comment by YaroRoodzit** [comment]
Issue resolved. Tested with the build: v2.5.0-b1. Title of details panel now will just say "Details" in both languages.
