### ISSUE TITLE
Preset zoom to Areas of Interest

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2469]
Our client would like to be able to create a list of predefined zoom extents within the viewer so the end-user can easily zoom to areas of interest.  For example, the top ten cities by population or a list of national parks.  Another example is to use items that exist in the GeoLocation API such as NTS areas.

**Comment by mweech** [comment]
I think this kind of functionality makes alot of sense mapped to a plugin built using the External API when completed.

**Comment by mweech** [comment]
Completed by NRCAN #2709
