### ISSUE TITLE
Image style items have unneeded extra space under the label in the legend

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2470]
Problem may be related to [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.1.0-daily07/src/app/ui/toc/symbology-stack.directive.js#L436) as it is providing false (larger) values when it executes vs. when you inspect the element in dev. tools. 

![68747470733a2f2f692e696d6775722e636f6d2f72585176394b392e706e67](https://user-images.githubusercontent.com/10187181/32493056-77ca2d9a-c38a-11e7-997a-69584a001822.png)

**Comment by YaroRoodzit** [comment]
Issue resolved. Tested with build : v2.5.0-b1
