### ISSUE TITLE
Fix language errors in help file

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2479]
Important language errors have been found in the help section of the tool.

This needs to be fixed as soon as possible.

I will check at NRCan to see if we can get access to a language expert to go over our help file to make sure all errors are identified.

**Comment by mweech** [comment]
@barryytm work with NRCAN to integrate changes to the French help file they will provide.

**Comment by barryytm** [comment]
@yblain Can you snap the error?

**Comment by mweech** [comment]
@barryytm they are going to provide an updated French file with all corrections made. You will just have to update using what they provide to us.

**Comment by barryytm** [comment]
In that case, @yblain can you create a PR and assign me to it when the French file has been updated?

**Comment by barryytm** [comment]
In that case, @yblain @ChrisLatRNCan can you create a PR and assign me to it when the French file has been updated?

**Comment by barryytm** [comment]
Sorry, accidentally deleted @mweech'c comment.  @yblain @ChrisLatRNCan Just let me know when you need my help.

**Comment by barryytm** [comment]
Sorry, accidentally deleted @mweech's comment. @yblain @ChrisLatRNCan Just let me know when you need my help.

**Comment by ChrisLatRNCan** [comment]
Salut @barryytm . I'll push in PR my changes for the French. You'll have to do the same for the English. I'll send you the file containing some errors identified by one of our colleague in the English help file.

**Comment by ChrisLatRNCan** [comment]
I'll ask @jolevesq to review the PR
