### ISSUE TITLE
Config Option to Show or Hide ObjectID and Shape Fields

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2485]
Consider having a config option to supress shape and objectid field in the data grid and detail pane.

Suggest at `featureLayerNode` and `dynamicLayerEntryNode` structures in the config.

Decision for default value to be made. Worth considering that the default value would be applied to any RCS layer.

Outstanding design considerations:

The name of the objectd id field can vary (e.g. `OBJECTID`, `OID`, `FID`, `ID`). In geoApi, we don't know the name of the field until the layer / sublayer has finished loading.  Currently the field name is contained in an **asynchronous** property because of that. As well, the value is not exposed via the LayerRecord proxy interface.  Additionally, the `fields` array that is contained in geoApi has the field type on each field (also asych, also not exposed via proxy interface).

Depending on which solution makes more sense for use on the client:

* If we expose `oidField` fieldname via the proxy, we will need to do so in a way that we convert other asynch properties to synchronous properties (see `geometryType` for example).
* If we expose `fields` via the proxy, we do the same asynch to synch conversion as above, but also need to add code to `attribute.js` to handle an odd case where the object id field is not tagged as such. Search for variable `noFieldDefOid`, and add logic to update the fields list if the field wasn't marked.

The fields approach might be better, as it would handle the unexpected case where `SHAPE` field is named differently. However it would also require a search iteration of the field list in multiple cases.

**Comment by dan-bowerman** [comment]
It would be helpful if this could be extended to hide any specified field as well, such as "Symbol" used in CESI to determine symbology, but offers no value to the end consumer. 

SHAPE seems to already get filtered in RAMP, as I haven't seen it show up in any Detail panes or grids.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2 . Works as expected.
