### ISSUE TITLE
Add Layer button not responding in Full Screen mode & unable to open layer setting menu

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2491]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily06/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,NPRI_CO,Railways

Thus unable to import layers as a result.
![image](https://user-images.githubusercontent.com/18723160/33183136-a5dbdd34-d044-11e7-8474-9a28de48f5f6.png)

**Comment by JahidAhmed** [comment]
Related to #2487

**Comment by IsabellaPan** [comment]
The three dots icon (to make the layer settings menu appear) is not responding as well in full screen mode.
