### ISSUE TITLE
Support Labelling In Viewer

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2493]
Look into various situations where the viewer can be improved when dealing with layers that have labels.

Known example: When a map highlight is applied to a feature, that feature's label is not included.

See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2492 for pictures of this happening.

Useful info:

[Labeling data structure](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r3000001m1000000) as exposed by ArcGIS Server.

There is client-side labelling in the Javascript API for [Feature Layers](https://developers.arcgis.com/javascript/3/jsapi/featurelayer-amd.html#setlabelinginfo). However with dynamic layers, there is no feature layer. We use a graphics layer to achieve the highlihgting, so would need to determine how to take the labelling information (server definition + current feature's attributes) and transform it into something drawn on the map.

**Comment by mweech** [comment]
@james-rae according to some esri documentation (http://server.arcgis.com/en/server/10.3/publish-services/linux/10038-data-frame-uses-the-maplex-label-engine.htm), they only recommend usage of maplex labeling engine if using a cached map service as there is dynamic label calculations occurring on the fly which will degrade performance.   not sure if this is something we should be supporting.

**Comment by ppollock** [comment]
Labels both **with and without** Maplex enabled are disappearing when a map highlight is appearing. 

BTW the performance of the service we have created using Maplex labelling is good; we have experienced no problems or delays.
