### ISSUE TITLE
Layer Refresh interval setting is lost when you change projections

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2500]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily09/dev/samples/index-fgp-en.html

Steps to Reproduce

- Set Refresh interval to 0.2 for JOSM layer in Lambert projection
- Change projection to Mercator
- Open Settings to confirm Refresh Interval
- Time reverts to 0

Expected behaviour: Refresh Interval setting should be maintained between projection changes

**Comment by mweech** [comment]
awaiting full state storage implementation.

**Comment by mweech** [comment]
Marking this as a "won't fix".  Changes to state storage may make this addressable in the future.
