### ISSUE TITLE
Missing Footnote even it is included in Export map settings

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2501]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily09/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

See below screenshots.
![image](https://user-images.githubusercontent.com/18723160/33491417-3a832778-d688-11e7-9bfa-3af2bc76e3ff.png)

![image](https://user-images.githubusercontent.com/18723160/33491573-ada97e78-d688-11e7-806b-9cc550f61ba5.png)

**Comment by JahidAhmed** [comment]
I believe the footnote value is an empty string by design

**Comment by AleksueiR** [comment]
Maybe we should hide the "Footnote" and other options if they have null values. It doesn't make sense to keep them if they don't do anything; this just confuses the user.
