### ISSUE TITLE
Almost half map points for JOSM not refreshing

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2504]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily09/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

- Set up Refresh Interval of 0.2 minute for JOSM layer (example in Mercator projection)
Some map points are not refreshing, see below screenshot for those stable points. 
![image](https://user-images.githubusercontent.com/18723160/33500855-649a9760-d6a8-11e7-84ca-44462a0c3bf0.png)

**Comment by mweech** [comment]
server issue
