### ISSUE TITLE
bug(ui): wet overrides fonts on layer group togles and other styles

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#251]
and maybe some other places

Also: Rounded corners on some panels; bigger gap at the bottom of some panels.

| wet | vanila |
|-----|--------|
|![](https://i.imgur.com/1omgG96.png)               | ![](https://i.imgur.com/Hw5B1iS.png)|

**Comment by mweech** [comment]
related: #482
