### ISSUE TITLE
Bounding box not retained in between projections in Firefox for JOSM and other layers

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2510]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily10/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction

Related issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2468

Bounding box is not retained when switching projections. This was reported for JOSM initially. However, this is an issue for other layers -EcoAction, CESI_Other. Bounding box icon is still displayed in the layer menu.

Also note that issue#2468 still persists in Firefox

**Comment by mweech** [comment]
bounding boxes do not currently persist based on omission from the current bookmark structure.
