### ISSUE TITLE
Unable to view the filter criteria under "Toggle Filter settings" panel for filtering datatable

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2515]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily10/dev/samples/index-fgp-en.html?keys=ZoomScale,JOSM,EcoAction

Related#https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2235

This issue seems to be back. User input is not visible

![image](https://user-images.githubusercontent.com/18539315/33679493-e88dcaa0-da8c-11e7-9af0-6492de39ea24.png)

**Comment by YaroRoodzit** [comment]
Tested and verified with Chrome and IE. Problem resolved.
