### ISSUE TITLE
bug(build): wet pages need jquery-less viewer builds

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#252]
Two jquery libraries don't play nice together.

**Comment by AleksueiR** [comment]
Another option is to conditionally load jQuery (and potentially other libraries like datatables) if they are not already present on the page. Thoughts?

**Comment by jolevesq** [comment]
To rely on the page it can create problems like jQuery 2.1.4 that have a bug and make dataTables crash. In GCViz, we have an internal version for jQuery that we use to override the jQuery present on the page (if there is one). This way we can control wich version we use.

**Comment by alyec** [comment]
Does gcViz replace the jQuery in the global namespace or does it keep a separate version around (e.g. using jQuery.noConflict)?  And is it possible to specify the jQuery reference to datatables?

**Comment by jolevesq** [comment]
I keep a separate version using noConflict. For datatables I was not able to load it trough AMD so it use the jQuery on the page. It is how I found the bug with jQuery 2.1.4 because WET4 template we use for a partener had this version.

I dont know if you can force a jQuery reference to datatables.

**Comment by alyec** [comment]
@AleksueiR and I talked about this a bit.  We are thinking of loading jQuery and datatables if they are not present on the page, if they are present we will use the global version.  We will also output a warning if there are libraries in the global scope that don't match the versions we are using (essentially warning anyone that this is an untested config).

**Comment by jolevesq** [comment]
Sounds good. At least the warning will help to know that it can be the source of the problem.

**Comment by spencerwahl** [comment]
Update time: JQuery conditional loading seems to be working, next on the to-do is datatables and possibly version checking

**Comment by mweech** [comment]
DataTable is related to #160.  
Is DataTables crucial?  If so let's pull in that one and close this off (assuming the version checking is a nice to have which could be a follow on task)

**Comment by AleksueiR** [comment]
I would say datatables is crucial since it's the second most common library between WET and R2 which can cause errors.

**Comment by mweech** [comment]
Ok, i will pull DataTables (#160) into the next milestone and will file the version checking (#448) seperately.  That moves this issue to a PR request state..

**Comment by mweech** [comment]
Closed by PR #462.
