### ISSUE TITLE
Check Box missing in legend for items with long titles

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2524]
![image](https://user-images.githubusercontent.com/5502696/34055913-35f5ba0a-e19f-11e7-8456-99cbefb47f32.png)

The check box in the legend is missing for this one, possibly because the label/title is too long...

Service can be found here:
http://geoappext.nrcan.gc.ca/arcgis/rest/services/MMS/IMA_F/MapServer/0

Same happens with this one:
http://geoappext.nrcan.gc.ca/arcgis/rest/services/MMS/IMA_F/MapServer/1

**Comment by ppollock** [comment]
Sometimes it looks like this:
![image](https://user-images.githubusercontent.com/5502696/34166808-ebf08e14-e4ad-11e7-9015-bc97d6e61bf3.png)

**Comment by AleksueiR** [comment]
@milesap Can you link this to an appropriate PR?
