### ISSUE TITLE
Refresh Interval setting is not working for dynamic layers-Only Chrome

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2529]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily13/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

Test Data : EcoAction Layer

Refresh Interval is not working as expected for Dynamic Layers in Chrome. This is not an issue in IE or Firefox.  Map points are not reloading per the interval set under Settings. 
Please see below the screenshot of Console error

![image](https://user-images.githubusercontent.com/18539315/34122935-fc29b9b6-e3fb-11e7-8974-b8991a262b8d.png)

**Comment by JahidAhmed** [comment]
Seems to be working on my machine; I don't come across any of these errors in the console either.

Can someone else please test this

**Comment by james-rae** [comment]
Can't reproduce in Chrome either. The error message posted above seems to indicate something went terribly wrong in setting up the `DynamicRecord` object.  Possibly some server hiccup / bad web result at the time, which cascaded into this problem?

Lets keep an eye open to see if this happens again.

**Comment by bkutty** [comment]
This still seems to be not working at our end.  Isabella could reproduce the issue.
