### ISSUE TITLE
Geolocation Search returned tens of {{::result.type.name}} in IE11

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2533]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-qa/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

See below two screenshots.
![image](https://user-images.githubusercontent.com/18723160/34218587-99a9a206-e57c-11e7-98b6-f28a58efb3f9.png)
![image](https://user-images.githubusercontent.com/18723160/34218824-40d46c78-e57d-11e7-8939-da18ec5fc2ef.png)

**Comment by barryytm** [comment]
I wasn't able to reproduce the issue

**Comment by JahidAhmed** [comment]
Working fine for me as well

**Comment by james-rae** [comment]
Also worked for me :(

Isabella's PC is much slower than ours. We should check again using her PC.  If it works, then it was probably a network failure. 
If she can reproduce, we might need to investigate if it's a race condition

**Comment by IsabellaPan** [comment]
One more instance when testing with index-sample:
http://fgpv.cloudapp.net/demo/v2.2.0-qa/prod/samples/index-samples.html
![image](https://user-images.githubusercontent.com/18723160/34227743-413e8148-e59c-11e7-95ab-b031fa1b7e92.png)

**Comment by james-rae** [comment]
Occurred again (one time, could not reproduce).
build `v2.6.0-b3`
on Bindu's machine
IE11
doing a lat-long search
