### ISSUE TITLE
Refresh interval reverted to 0 after RELOAD for user added Dynamic service layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2534]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-qa/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

- Add the test data as ESRI Dynamic Layer
- In step 3 select ProtectedAreaNationalView layer to add
- Set Refresh Interval to some value, like 1 minute or 0.5 minute and Reload
After reloading, it reverted to 0 and the added layer cannot refresh.
![image](https://user-images.githubusercontent.com/18723160/34225756-874044f8-e595-11e7-9b15-f02beaaa4fc9.png)

**Comment by JahidAhmed** [comment]
I think I know the cause of this;

Dynamic children get their refresh interval from their dynamic root, but I think in this case the dynamic root is collapsed and thus the refresh interval for that is 0 so this layers interval will always be reset to 0.

**Comment by YaroRoodzit** [comment]
Tested with Chrome.Problem with reverted refresh interval has been resolved, but refresh for Dynamic service layer doesn't work. Issue #6220 logged for refresh problem.
