### ISSUE TITLE
Please add a label/indicator to indicate default opacity value of 0.5 in parent entries when opacity value differ with child entries

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2535]
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-qa/prod/samples/index-samples.html

 Related :#2372

Default value of opacity is set to 0.5 in cases where opacity values are different for parent and child items.  Please add a label/indicator of some sort to indicate this setting

![image](https://user-images.githubusercontent.com/18539315/34273065-cd6fb564-e660-11e7-8c6d-20a3c6b4d031.png)

**Comment by mweech** [comment]
@AleksueiR thoughts?

**Comment by AleksueiR** [comment]
How about something like this:
![](https://i.imgur.com/rCT3ZKH.png)

- `Applies to nested items` is displayed on regular group elements only
- `Mixed values` label shows that opacity values of nested values are not the same
- The slider track is not coloured and the opacity value is hidden to indicate the indeterminate state


----
Current view:
![](https://i.imgur.com/TPFwiUO.png)

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-2b. Sample#4. Label "Mixed values" shown when child layers opacities differ.
**Comment:** No value is shown in this case.

**Comment by dane-thomas** [comment]
That is the intended result. There was a slight design change to remove the "%" in the discussion in #2752

**Comment by AleksueiR** [comment]
^ see this [comment](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2752#issuecomment-394331024)

**Comment by YaroRoodzit** [comment]
Thank you for the update.  Then completed.
