### ISSUE TITLE
Reordering layers has no effect on map

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2536]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html

Imported 2 layers (`happy.json` and then `convert.json`) and reordering them had no effect. 
`happy.json` always remained below the other layer even if it was above in the legend stack.

Expected behaviour would be to see `happy.json` layer above `convert.json`

**Comment by AleksueiR** [comment]
`configService.getSync.map.layers` returns an empty array here https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L290 instead of a layer list.

**Comment by YaroRoodzit** [comment]
Tested with  Chrome and IE . Problem resolved.
