### ISSUE TITLE
WMS raster data in export differs from what's being displayed on the viewer

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2539]
When exporting an WMS layer, the raster data differs from what is being displayed on the viewer.

- Tested page: http://fgpv.cloudapp.net/demo/v2.3.0-semi-weekly00/dev/samples/index-samples.html
- Tested Layer: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities
- JSON snippet: `{
        "id":"wms",
        "name": "WMS Layer",
        "layerType":"ogcWms",
        "disabledControls": [ "styles" ],
        "layerEntries": [
            {
              "id": "GDPS.ETA_UU",
              "allStyles": [ "WINDARROW", "WINDARROWKMH", "WINDSPEED", "WINDSPEEDKMH" ],
              "currentStyle": "WINDSPEEDKMH"
            }
        ],
        "url":"http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities"
      }`

Viewer:
![capture](https://user-images.githubusercontent.com/19259169/34498984-f6ba6c0a-efd1-11e7-8cac-22d33012ba2c.PNG)

Export:
![capture2](https://user-images.githubusercontent.com/19259169/34498983-f6b838c2-efd1-11e7-8a92-1d04792c0731.PNG)

**Comment by mweech** [comment]
right layer, wrong style it seems.
