### ISSUE TITLE
Ignore filtered out features in identify results for dynamic layers

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2544]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

Applying filters in the table to a dynamic layer and then clicking on the map where a hidden feature previously was still returns a result in the identify panel.

After discussing with @james-rae, he had the following to add:
> identify on feature layer happens on client, so thing is invisible and it doesnt identify
dynamic identify happens on server. it dont know about the filters. so it returns result.
to fix, would need to add more parameters to [this param object](https://github.com/fgpv-vpgf/geoApi/blob/v2.2.1-1/src/layer.js#L717) to add the filter definitions for sub-children. Would be [like this](https://developers.arcgis.com/javascript/3/jsapi/identifyparameters-amd.html#layerdefinitions)

**Comment by YaroRoodzit** [comment]
Tested on  Chrome with layers #06 and #07. Problem resolved.
