### ISSUE TITLE
Grid Titles Revert To Field Names When Search Has Focus

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2545]
When a datagrid is open for a layer that uses field aliases, the field aliases will be used as column titles.

If the `Search` box to the right of the grid title receives focus, the grid titles will switch back to the raw field names.  When the box loses focus, they switch back to proper aliased names.

Sample service:  https://cipgis.canadaeast.cloudapp.azure.com/arcgis/rest/services/AHCCD/AHCCD_fr/MapServer/0

**Comment by james-rae** [comment]
Appears this might have been done [on purpose](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/ui/table/table-search.directive.js#L39).  Will reach out to @jolevesq

**Comment by AleksueiR** [comment]
It is done on purpose - actual field names are used for filtering, so titles revert back to show a user to aid in typing.

**Comment by james-rae** [comment]
This brings up an interesting case then.  Raw field names is useful because you can do stuff like a SQL WHERE clause in the search (which wont work on an alias).

But as you can see, with certain services, the raw field name is anything but helpful to the user.  Need to ponder this.

![cesi_grid](https://user-images.githubusercontent.com/7585245/34778045-1fdad912-f5ea-11e7-9909-2774ade3fe90.jpg)

**Comment by dan-bowerman** [comment]
Speaking from a purely CESI perspective, I can understand the need to query based on actual field names and not aliases, but this could potentially be jarring for the user is now suddenly sees the "Details" field displayed as "E_Details_URL". I don't have any great insights for how/if we should handle this issue -- from my end, I think we should just pure more emphasis on naming GDB field names more cleanly, to avoid even the need for aliasing (which would still be useful for adding French accents).

**Comment by JahidAhmed** [comment]
This doesn't seem to be working anymore (not sure if intended).

Problem here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/table/table-search.directive.js#L37

The event may be broadcasting too early as it can't find the `input` (hasn't been created in time).

**Comment by mweech** [comment]
original issue is a false positive.
