### ISSUE TITLE
Reloading a layer that is adding multiple times removes all but one instance of it

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2546]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html (Sample 8)

After discussing with @AleksueiR, we weren't sure what the use case would be for adding several layer multiple times and how a situation like this should be handled.

(In the gif, I refresh off screen)
![](https://files.gitter.im/JahidAhmed/gt7t/fullscreen.gif)

**Comment by JahidAhmed** [comment]
Duplicate of #2657 - marking this as a duplicate as that issue has more detail on use case and expected behaviour

**Comment by AleksueiR** [comment]
Also a duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2901 - which has even more details and a better gif.
