### ISSUE TITLE
Viewer API Extent Behavior

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2547]
The API exposes the current map extent to an outside caller. Our current convention is that the API publishes anything geometric in LatLong co-ordinates.

Extents are funny things when it comes to projections. An extent is an extent because it is a box (four sided closed poly) with right angles. The right angles only exist in the projection it's being displayed in. As an example, if you treat an extent as just a raw polygon and project it from Mercator to Lambert, the result will be a fan-shaped four-sided polygon.  The right angles are lost.

The RAMP core has a function to re-establish the right-angles when projecting extents. It does this by using fancy math to construct a new extent that has right angles and covers the area of the old one.  But this is not a reversible process. Often the new extent is padded to make adjustments due to the shape differences in projections.

When the API provides the extent in LatLong, it is using this fancy function to preserve the extent.  In other words, the extent you get from the API will look like a square when viewed in a LatLong projection.  But if the LatLong extent gets passed back into RAMP, and re-adjusted to RAMP's projection, it has to go through the fancy function again -- this usually results in an extent that has been double-padded, and is not the same as the original extent.

An example:

* The ORANGE square represents the extent that the RAMP map was at.  It is in Lambert.
* The PURPLE filled square represents the Lambert extent in Lat Long if you just project the min/max values by hand and ignore warping. This illustrates why we need fancy functions to preserve extents.
* The GREEN square represents the original extent after it has been put through the fancy function and exposed via the API in LatLong. You can see it covers the initial extent, but also some more area due to the warping of projection change.
* The BLUE square represents the extent that is produced if the GREEN extent (API LatLong) is passed back into RAMP and goes through the fancy function to become an extent in Lambert again. It covers the LatLong extent, plus padding due to warping, but is much bigger than the original ORANGE extent.

![extentwarp](https://user-images.githubusercontent.com/7585245/34896026-33995096-f7b6-11e7-8402-bd9f40a676d5.jpg)

Possibly solutions going forward:

* Don't warp the API Extent.  This will allow the values to be seamlessly converted between LatLong and the map projection. We might have to use a four-point polygon instead of XYBounds class (not sure).
* Remove the LatLong extent and tell people to use `mapI.extents` instead. Don't know how safe this is; `mapI` might be the unsupported interface.
* Have an option in API to warp or not warp the API extent.
* Other ideas.

**Comment by milesap** [comment]
Once things settle down I'll take some time to think about this and discuss.

**Comment by milesap** [comment]
First, the "I should blame someone else":

> Is it possible the conversion math can be improved so switching/warping extents is precise?

The above may not be possible, so a dumb idea:

> What if on the `GAPI` side of things we cache warps (you gave me this, I gave you that) so if I see a previous extent I don't recompute, just pass cached extent. Not sure if the original distortion would remain with this.

At the end of the day I like and support the

> Don't warp the API Extent 

Any other thoughts?

**Comment by mweech** [comment]
Suggestion:
- return the extent in whatever the current projection system is
- user can read the projection and use it in combination to determine the lat/long if necessary

**Comment by james-rae** [comment]
## Direct Interface to the API Map

Exposes on the map object a way to get and set the Extent in the native projection.  Uses ESRI JSON format (which is fairly intuitive to use for non-esri people).

Setting the extent directly on the map changes the map, which will trigger the standard `bounds` listener on the API and thus the official warped values and observables also get updated.

We currently have the setter `extent` which appears to allow a raw json input and doesn't do any projection manipulation.  It has no documentation, and has no way of allowing a caller to access the `fit` parameter.

Propose:

* Changing the `extent` setter to a function. Include the optional `fit` parameter.  Add proper documentation.
* Create a matching getter or get function to allow API user to access the map extent in map projection format.  Add proper documentation.
* Consider renaming to imply the extent is in map projection.  Bad ideas: `rawExtent`, `mapPrjExtent`
* No new observables. API devs can still listen to the `boundsChanged` observable, and when it triggers they can access the new getter / get function if they want a raw extent.

PROS: Doesn't interfere with existing API geometry classes. Only two endpoints to maintain.
CONS: Without good naming & documentation, can be confusing to have concept of extents and bounds which are actually different things.  Uses an unwrapped/untyped object that is ESRI specific.

Current suggested approach.  Ideally added to `v3.0` before `extent` setter becomes part of the released API.

## Fancy Geometry

We update the API geometry to support extents in a native projection.  Would mean either enhancing the `XYBounds` class, or making a new class that wraps an extent.  

This would introduce changes in a number of spots, as we use `XYBounds` in a number of areas, and all the API code currently runs on the assumption of LatLong co-ords.

Not suggesting this approach. Effort is too high / changes too many things too close to release date.  Maybe something like this can be implemented in a future release, then we depreciate the extent endpoints in the suggested approach.
