### ISSUE TITLE
Full screen mode does not exit properly when exiting without using side nav nor map nav

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2555]
Tested page: http://fgpv.cloudapp.net/demo/v2.3.0-semi-weekly01/dev/samples/index-fgp-en.html

The issue occurs when using a template.  Try exiting full-screen with `Esc` or any other methods without clicking the full-screen buttons on the side/map navigation.

**Comment by barryytm** [comment]
This problem seemed to be caused by [toggle()](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-semi-weekly01/src/app/ui/common/full-screen.service.js) not being invoked when exiting in not built-in ways.  Perhaps we can do a check on [change()](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-semi-weekly01/src/app/ui/common/full-screen.service.js#L62) and run [toggle()](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-semi-weekly01/src/app/ui/common/full-screen.service.js) if needed?

**Comment by barryytm** [comment]
This behavior seemed to only occur when pressing `ESC` or `F11` to exit full screen.  My hypothesis is that default actions from the browser are not being overwritten properly.  If that is the case, `focus-manager` is either not handling the right keys or not handling at the right time.  @AleksueiR do you have any thoughts on this?

**Comment by AleksueiR** [comment]
I don't believe focus-manager is handling `Esc` or `F11` keys at all.

`onChange` handler does seem to trigger on these keys though, so I think your idea of running `toggle()` from there should work. :+1:

**Comment by YaroRoodzit** [comment]
Tested on Chrome and IE. Problem resolved.
