### ISSUE TITLE
Bootstrap code executes out of order when loading after window ready event

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2559]
If the `rv-main.js` is loaded after the page ready event, [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/app-seed.ts#L7) executes immediately and fails because the `RV._nodes` property is not defined. It's not defined because [the logic populating this property](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/bootstrap.js#L24) is located after the function accessing it in the js bundle. 

The files and their dependencies to be included in the bundle are listed [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/app-loader.js#L27). However, the order of import statements is not preserved and `app-seed` code ends up begin executed before `bootstrap`. This is okay under normal circumstances when the `rv-main` file is initially loaded together with the page.

Also, the ie-polyfill for the SVG library must wait until the SVGjs is loaded by RAMP before being applied. When `rv-main` is loaded after the initial ready event, this polyfill fails to apply as well.

**Comment by milesap** [comment]
The solution is to stop using the window global as a data store and instead export/import variables/const/functions etc. properly so that webpack can bundle thinks in the correct order. I'll PR this asap, but I have 2-3 other urgent issues as well. Fun times!

**Comment by milesap** [comment]
Fixed on commit https://github.com/fgpv-vpgf/fgpv-vpgf/commit/6edc0619e5571685b617c6d41fb76b8ce868aeba
