### ISSUE TITLE
Changes to strings

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#2560]
From the "settings" for a layer in French, the string "La légende" should simply be "Légende".

Also, per Canada.ca guidelines, labels should be written in sentence-case, i.e. "Feature Details" should read as "Feature details".

**Comment by dan-bowerman** [comment]
Also several untranslated strings in RAMP:

- [fr] Loading data...
- [fr] Geo Search
- [fr] Building Table...
- [fr]Change {{settingName}} at
- [fr] Zoomed too far?
- [fr] fix?

**Comment by YaroRoodzit** [comment]
Verified with Chrome and IE.
