### ISSUE TITLE
App freezes when a drop down menu opened in programmatic bootstrap

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2561]
When a RAMP instance is created programmatically, through the upcoming v3 API, the map freezes if a dropdown (datatable settigns, legend entry settings, etc.) menu is opened with the following error:
```js
TypeError: Cannot read property 'setStatus' of undefined
    at HTMLButtonElement.HTMLElement.rvFocus.e.fn.rvFocus (focus-manager.js:622)
    at HTMLButtonElement.HTMLElement.focus.e.fn.focus (focus-manager.js:668)
    at activateInteraction (rv-main.js:161960)
```

Sample: http://maps-cartes.dev.ec.gc.ca/sandbox/barry/index-programmatic.html

First noticed when trying to solve the `multipleDefine` problem here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2554#issuecomment-360132174

**Comment by milesap** [comment]
Focus manager needs to be updated for programmatic bootstraping
