### ISSUE TITLE
API Sample Folder

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2566]
See discussion in this PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2556

As we will likely have a number of API sample pages, create a subfolder in the `samples` folder to house them. Update the build process so the samples get processed and published.

Move any existing API samples to that folder

**Comment by barryytm** [comment]
The new structure of the api sample files location that I came up with.  Feel free to give suggestions.
  
- samples
    - api
        - `api-export.tpl`
        - `api.tpl`
        - extensions
            - `hello-world.js`
            - `self-loader.js`
