### ISSUE TITLE
Console error - layer record undefined

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2567]
When launching a details pane (e.g. identify results, or clicking detail icon from the data grid), the following error appears in console

`TypeError: Cannot read property 'layerType' of undefined`

Appears that `layerRecord` is undefined in [this line of code](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.2.0/src/app/ui/toc/symbology-stack.directive.js#L189)

The error does not appear to be causing any issues in the application proper; could just be an event firing on something that shouldn't have an event?  Regardless, would be good if the problem could be squashed to keep the console free of errors.

**Comment by YaroRoodzit** [comment]
Verified with Chrome. No console error for the data grid.
