### ISSUE TITLE
Investigate large text encoding arrays in IE Polyfills

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2569]
We use the library [text-encoding](https://github.com/inexorabletash/text-encoding) to help IE handle converting `utf-8` files into [string formats](https://github.com/fgpv-vpgf/geoApi/blob/v2.2.0/src/layer.js#L463).

The source code contains large arrays of integers that map all types of [encodings](https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding-indexes.js).  As these are raw data, they don't minify well. 

Look into the possibility that all the extra encodings are not required by RAMP (since we're always going from `utf-8`). If so, consider forking the library to the project github, removing all the non-essential encodings, and test thoroughly.

**Comment by barryytm** [comment]
I've come across to [text-encoding-utf-8](https://github.com/arv/text-encoding-utf-8) which is basically a subset of `text-encoding` that we are currently using.  It only encodes/decodes utf-8 which makes the source files much smaller.  Using this library would save us time and hassle to do it ourselves.  Any thoughts on this module?  Assuming we want to remove all the extra encodings of course.

NPM page: https://www.npmjs.com/package/text-encoding-utf-8

**Comment by barryytm** [comment]
Here are the production builds with both `text-encoding` and `text-encoding-utf-8`

**Current** 

- [ie-polyfills.js](http://fgpv.cloudapp.net/demo/users/barryytm/CESI-2560/prod/ie-polyfills.js)
- [index-samples](http://fgpv.cloudapp.net/demo/users/barryytm/CESI-2560/prod/samples/index-samples.html)

**UTF-8 only** 
- [ie-polyfills.js](http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2569/prod/ie-polyfills.js)
- [index-samples](http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2569/prod/samples/index-samples.html)

**Comment by AleksueiR** [comment]
What are the size differences?

**Comment by james-rae** [comment]
Was able to load all 3 filetypes in IE 🏆

**Comment by spencerwahl** [comment]
@AleksueiR 96.1 kb vs 628 kb according to chrome

**Comment by AleksueiR** [comment]
@spencerwahl Awesome! Are these minified sizes?

**Comment by dane-thomas** [comment]
Currently doesn't seem like the switch to `text-encoding-utf-8` will be simple. 

`geoApi` requires `text-encoding` but that should be something we can change. 
`text-encoding-polyfill` is required by `parsedbf` which might be more difficult to change. 

Something that may make it a little better would be to use `text-encoding-polyfill` for `geoApi` since it appears to be literally the same as `text-encoding`.

**Comment by mweech** [comment]
Impasse reached and parent issue has been closed.
