### ISSUE TITLE
chore(build): wet sample page missing resources on fgpcloud site

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#257]
I didn't want to include wet code in our source, so I linked resourced from a lib folder. Auto-deploy script doesn't copy them over and the wet sample page is currently broken: http://fgpv.cloudapp.net/demo/develop/index-wet.html

What should we do? Include wet in source or update auto-deploy script to copy over wet folder?

Relates to #10

**Comment by alyec** [comment]
How about having WET deployed on the demo system as a separate resource: http://fgpv.cloudapp.net/demo/wet4.0.20/ .  Linking with absolute refs should allow the site to work in dev or on the demo system.

**Comment by AleksueiR** [comment]
Perfect, thanks! And we can remove the wet dev dependency as well.
