### ISSUE TITLE
Legend toggling issue in layers with default symbol

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2580]
Tested Layer: http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/Sandbox/defaultSymbol/MapServer/0

Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2368, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2440

When toggling via legend in a layer with default symbol.   Turning off one of the none-default symbols will also turn off all the symbols.

![graphic](https://user-images.githubusercontent.com/19259169/36045177-daf2f2a0-0da2-11e8-8988-b487449489e9.gif)

**Comment by YaroRoodzit** [comment]
Tested with Chrome and IE. Problem resolved.
