### ISSUE TITLE
bug(ui): datatable body hides headers

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#259]
~~Sometimes~~  datatable body expands vertically and hides headers:

![](https://i.imgur.com/cAetNgm.png)

**Comment by spencerwahl** [comment]
The body of the table is re-sizing after creation, causing the headers to have less vertical room to occupy. The header container is still there but has a height of 0 or 1 pixels usually.

The body can also re-size back to normal for no apparent reason.

**Comment by spencerwahl** [comment]
This seems to have fixed itself at least temporarily

**Comment by AleksueiR** [comment]
Don't close yet; let's wait for a couple of weeks.
