### ISSUE TITLE
Removing layers "quickly" and then re-adding them leaves them invisible

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2592]
This was found using the API.

If you remove layers in quick succession (before the toast disappears) the state assigned to the layer id sticks. Then if you add a layer back with the same id it is added but in a non-visible state.

Removing a second layer before the first toast disappears also triggers an error about the toast.

Steps:
- Remove layer1 using the API
- Remove layer2 using the API within a couple seconds
- Try to add layer1 using the API

**Comment by james-rae** [comment]
Handwaving solutions for discussion:

## Solution One: One delete at a time

1. Disable all the "Remove" garbage can icons while the Toast is active. This solves the "i click really fast" scenario.
2. When deleting through the API, don't show the toast and immediately remove the layer (maybe we already do this?). This solves the webpage making API calls in automated fashion going too fast.

Not sure if disabling the garbage cans is unacceptable for usability.

## Solution Two: Roguelike delete

Remove the toast. donethanks. Favours the lazy programmer and brave user.

## Solution Three: Enhance some code

1. Find out why state is sticking, second delete is causing toast error
2. Look at refactoring our delayed delete and how it tracks ids when deletes are done in quick succession.
3. Propose solution and enhance.

**Comment by mweech** [comment]
I believe API based removal should shortcut some of the additional notifications you get when done directly through the RAMP interface (i.e. remove toast).  If one wishes to override built in viewer functionality and interact via the API directly, they are taking over some responsibility for user experience..

**Comment by jolevesq** [comment]
Adding to this, when the error about the toast is triggered, the remove layer event is no fired so we can't start our own event on layer removed.

**Comment by dan-bowerman** [comment]
May need more investigation for CESI in the future, otherwise this is probably not worth pursuing. Engage NRCan to see if this is still impacting them as well.

**Comment by jolevesq** [comment]
@dan-bowerman I remember there workaround was developed to bypass this condition. I think the best approach would be to do this at the source and avoid workaround. Comment from Mike Weech (June, 13 - 2018) is relevant.
