### ISSUE TITLE
Improve API identify for GroupLayer

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2601]
🚧 Final implementation of `IdentifyRequest` has passed consensus - using `promise` 🚧 

### IdentifyRequest
When an identify action occurs (i.e. clicking on the map) an `IdentifyRequest` object will be emitted immediately from either a `ConfigLayer` or `LayerGroup` instance - of the form:

```js
{
    requestId: number;
    layer: ConfigLayer;
    features: Promise<DataItem[]>;
}
```

A `DataItem` is defined [here](http://fgpv-vpgf.github.io/fgpv-vpgf/api/interfaces/_index_d_.rv.layer.dataitem.html) but may be expanded as needed. There was discussion about adding symbology - perhaps at another time if it's not currently needed.

### LayerGroup
The `layer` property in an `IdentifyRequest` is redundant on the layer level, but becomes useful when using `LayerGroup`'s. Like `ConfigLayer`, a `LayerGroup` will have a similar implementation with the exception of the emitted value changing from an `IdentifyRequest` to the following form for all layers who have identify enabled:

```js
{
    requestId: number;
    iReqs: IdentifyRequest[];
}
```

#### Example

```js
mapI.layers.identify.subscribe( (iReqs, reqId) => {
    iReqs.forEach(r => {
        console.log(`Identify action started on layer ${r.layer.name}`);
        r.features.then(results => {
            results.forEach(r => {
                console.log(`${r.name} : ${r.value}`));
            });
        });
    });
});
```

#### Example
`mapI.layers.setIdentify(false);`

Note that the above is an alias to the layers `setIdentify` methods. If for example, you only want the first layer in a `LayerGroup` to emit identify results this would work:

```js
mapI.layers.setIdentify(false);
mapI.layers.allLayers[0].setIdentify(true);
```

**Comment by AleksueiR** [comment]
This is done and merged now except for `setIdentify`.
