### ISSUE TITLE
API identify for LayerGroup and ConfigLayer

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2603]
See PR #2597 for map implementation. The idea is to expand this functionality to `LayerGroup`, `ConfigLayer`, and `SimpleLayer` for more granular control. 

Remove any identify logic from the panel directive and place into the api and/or geoApi where appropriate. 

Setting identify modes on a layer takes the highest priority, followed by LayerGroup, then the map.

Reference [idea 1 or 2](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2684) for the `identifyResults` return values (whichever is chosen).

`SimpleLayer` will likely be different - `identifyResults` could return a lat/lng bbox and any geometry instances intersecting that box.

**Comment by JahidAhmed** [comment]
`identifyMode` was moved to from `Map` to `LayerGroup` and a queryable option was added to `ConfigLayer` which is linked with the `UI` query option in the settings panel in [this PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2740).

A new issue will be created to handle `identifyRequests` for `SimpleLayers` (TODO after `SimpleLayer` implementation is completed)
