### ISSUE TITLE
JOSM Layer - Feature Point roaming along with mouse after click-holding on the map and dragging the map

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2614]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

Not sure if this is an IE performance issue. There was always a map point and its tooltip lingering with the mouse within the viewer whenever user tried to drag the map.
![image](https://user-images.githubusercontent.com/18723160/38107052-d7b2a8a6-335e-11e8-8098-e99a7b663f3a.png)

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-b1. Original Issue resolved.On-hover tooltips still flickering when map point close to a left or right side of the viewer.

**Comment by james-rae** [comment]
Flickering tip logged in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2754
