### ISSUE TITLE
User added single entry Dynamic service layer not refreshing after set up refresh interval

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2620]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/21

• Add the above test data as ESRI Dynamic Layer
• In step 3 select Average ambient ozone concentrations... (the default one) sub-layer to add
• Set Refresh Interval to some value, for example 0.2 minute and Reload
After reloading, this layer doesn't refresh.
![image](https://user-images.githubusercontent.com/18723160/38270089-672f6dda-3750-11e8-9583-53bb548f2d65.png)

**Comment by barryytm** [comment]
Might be the same issue as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2519
