### ISSUE TITLE
Snowman icon is not positioned correctly over the north pole

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2624]
The origin point of the icon seems to be set to `left top`; `center center` or `center bottom` should be used instead.

Note that this transformation should only be applied to the snowman/north pole icon, not the north arrow icon as it uses the origin point for rotation.

![](https://i.imgur.com/DbBw1V0.png)

**Comment by YaroRoodzit** [comment]
Tested with Chrome and IE11.
