### ISSUE TITLE
"About map " information shown in French when language set to English

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2627]
Tested build:http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-mobile.html
"About map " information shown in French when Viewer language set to English.

**Comment by JahidAhmed** [comment]
The content of the 'About map' section seems to be only [lorem ipsum](https://en.wikipedia.org/wiki/Lorem_ipsum) placeholder text

**Comment by mweech** [comment]
Title was translated, sample content was just Lorem Ipsum.
