### ISSUE TITLE
Debug statements in production code

### ISSUE THREAD

**Issue by jvanulde** [fgpv-vpgf/fgpv-vpgf#2629]
Please remove debug statements (e.g. console.log) from production builds. Consider using the webpack-strip module. The console output is verbose.

**Comment by james-rae** [comment]
From miles:

> look at https://github.com/mishoo/UglifyJS2#compressor-options . Specifically, examine `pure_funcs` so we keep the `error` and `warn` messages but not the other console output

**Comment by bkutty** [comment]
Tested build http://fgpv.cloudapp.net/demo/v2.4.0-b2/. Working as expected

**Comment by jvanulde** [comment]
:thumbsup:
