### ISSUE TITLE
Incorrect statement in "Help" content for Layers 

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2631]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Incorrect statement in "Help" content in  Layers part. The eye icon should be changed to the checkbox for layers visibility.
![help_layers](https://user-images.githubusercontent.com/38046459/38635765-5dee83d8-3d94-11e8-9260-166c95ddf49a.jpg)

See attached for clarity.

**Comment by james-rae** [comment]
French translations still required
