### ISSUE TITLE
Unexpected highlight oulitne on legend items

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2633]
An unexpected outline is shown around legend items and their symbology stack elements when clicked with a mouse. It doesn't seem to show up when tabbing to interactive elements inside the legend.

This highlight is not needed, and just gets in the way.

![](https://i.imgur.com/h1AZ0ru.gif)

**Comment by YaroRoodzit** [comment]
Tested with Chrome and IE11.Problem resolved.
