### ISSUE TITLE
Help text requires clarification regarding a footnote

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2634]
Help text requires clarification regarding a footnote in Export Image section. It should be indicated that footnote may not be available and depend on the map.
Tested  build : http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM

**Comment by james-rae** [comment]
French translations still required
