### ISSUE TITLE
Timestamp option not available for Export 

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2635]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM
Timestamp option not available for map Export.
Please add timestamp option or remove it from the Help > Export Image

**Comment by barryytm** [comment]
The key `timestamp` is missing under `services.export` in the [config file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-build-04/src/content/samples/config.rcs.en-CA.json#L31).  The time stamp option should be available with ` timestamp there.

E.g.
```
    "services":{  
        "export":{  
            "title":{},
            "timestamp":{}
        }
    }
```

**Comment by james-rae** [comment]
Since timestamp is optional / configurable, the Help doc should reflect that

**Comment by dane-thomas** [comment]
Needs official translations #2891
