### ISSUE TITLE
Only the layer of the first RCS key is loaded 

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2636]
Tested Build: http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways

When loading layers with RCS keys in the URL, the viewer only loads the layer of the first RCS key.  For example, only JOSM is loaded in the tested build above.

**Comment by IsabellaPan** [comment]
It seems an issue for Chrome only. All RCS keys could load in FF and IE

**Comment by YaroRoodzit** [comment]
Tested with Chrome.Problem Resolved.
