### ISSUE TITLE
The master "text search" does not  have wildcard search

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2637]
A statement in the  **Help** > **Filter data** about usage of wildcard character is not clear .

> 

 **Text:** Character input field. Use the wildcard character * to replace a sequence of zero or more characters (e.g. * levo will find Charlevoix) 

> 
It is not immediately obvious if wildcard character can be used with master "text search".
The master "text search" does not appear to have wildcard search implemented in the current build .
 As suggested by James Rae we need either add the wildcard to the master search, or clarify the wildcard help text to indicate it doesn't work in the master search.  
Tested build : http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM

**Comment by james-rae** [comment]
Needs revisiting (i.e. what is app doing, what is help saying), and then edit help file so it aligns to what the app is doing.

**Comment by mweech** [comment]
Help text no longer mentions wildcard search.
