### ISSUE TITLE
Console Error - can't set map cursor

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2644]
Console error worth investigating.

Steps that produced it:
load site with JSOM rcs key
open datagrid
close datagrid
put mouse over a point

![console error](https://user-images.githubusercontent.com/7585245/38742044-739d1430-3f09-11e8-8baa-86eb177e2523.jpg)

**Comment by JahidAhmed** [comment]
Related to #2596
