### ISSUE TITLE
COORDS INFO cannot open coordinates info window

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2645]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

-  From left-side menu click COORDS INFO
-  Place the + sign on any point on the map
It didn't pop a window like before to tell user the detail Coordinates info, instead it opened up Feature details panel as below screenshot.

![image](https://user-images.githubusercontent.com/18723160/38743597-80653c8e-3f0d-11e8-97a6-f457457366c8.png)

**Comment by YaroRoodzit** [comment]
Tested with Chrome and IE11. Problem resolved.

**Comment by jolevesq** [comment]
Value returned from one of the service have changed format so it throws an error.

**Comment by bchagnon** [comment]
Still does not work for me. Are you sure this has been resolved?
Note: "From left-side menu click COORDS INFO" to get Map location information (a.k.a. COORDS INFO) window, not to get layer query information.

Map location information that should appear:
![maplocationinfo](https://user-images.githubusercontent.com/2006029/39252775-6399505c-4874-11e8-9411-a63715ba42b2.png)

**Comment by bchagnon** [comment]
My apology @YaroRoodzit, was testing with previous build-05 **\*deuh\***
