### ISSUE TITLE
WMS Legend graphics should be requested differently based on WMS version

### ISSUE THREAD

**Issue by jfbourgon** [fgpv-vpgf/fgpv-vpgf#265]
The way to determine which URL to use in order to get the Legend graphics associated to a WMS layer has changed between WMS 1.1.1 (GetLegendGraphic) and WMS 1.3.0 (legendURL). Current version of the FGP viewer (RAMP) only requests Legend graphics through GetLegendGraphic queries no matter what is the WMS version supported by the service endpoint and then ignore server capabilities.

**Comment by mweech** [comment]
This issue has been rolled up into issue #224.
