### ISSUE TITLE
Import ESRI API from custom location

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2654]
Currently we load the ESRI API from ```dojoURL: '//js.arcgis.com/3.20/'```. It would be a good thing if we can customize the url from the schema so that we can host the api ourselves. It will solve some bugs we had with NRCan network and ESRI api site.

**Comment by james-rae** [comment]
A good idea. The config property should be optional and/or clearly marked as `BE CAREFUL`, as we don't guarantee support for any version except the one we're currently developing against and pointing to in our distribution.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b1. Sample #71. The sample can be loaded. Verified with Shruti V.
