### ISSUE TITLE
Custom symbology toggling sublayer visibility

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2656]
Here is the same layer added twice: with default symbology (top) and custom (bottom):
![](https://i.imgur.com/R1x4OvE.png)

The layer has only one sublayer, but the custom symbology stack displays four checkboxes which - it seems - try to modify layer's visibility. If more then one is toggled, the symbology stack leaves empty space underneath it when collapsed:
![](https://files.gitter.im/JahidAhmed/tc0J/thumb/image.png)

The following error is logged as well:
> Error: Unable to draw graphic (null): Unable to complete operation.

Toggling those symbology icons also seems to break the datatable, it remains on the Building table ... screen.

____

from @james-rae:
> I believe we had an idea to add an extra property in the custom symbols to allow a query string to link in to the symbol filters.
For now I think you can disable toggleSymbology in the config to remove the checkboxes

**Comment by dane-thomas** [comment]
`symbol.definitionClause` contains the query that is applied when a symbol is selected. So a possible fix for this issue would be to use the existence of a `definitionClause` to determine if a symbol can be toggled.

**Comment by AleksueiR** [comment]
@james-rae Do we want a separate issue for linking custom legend graphics with filters or just keep this one open?

**Comment by james-rae** [comment]
Added to Centralized Filtering Epic, will see what we can figure out in v3

**Comment by james-rae** [comment]
#3143
