### ISSUE TITLE
If a layer's opacity set to 0 initially, the opacity setting will fail

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2658]
Tested build:http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-samples.html
Sample map:11.Multiple layers with opacity disabled initially
- Map points cannot be seen, because opacity set to 0 
- Go to the layer setting and change the opacity to 100% 
Map points still cannot be seen

**Comment by james-rae** [comment]
Likely related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2594
