### ISSUE TITLE
Initial basemap broken causes an error with blank basemap

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2659]
Functionality wise, changes were made to ensure the app does not crash if the initial basemap fails to load. However, since the blank basemap is created using the first basemap in the list (with opacity 0), when the first basemap fails, switching to the blank basemap will also fail.

**Comment by james-rae** [comment]
Worth noting, the main use case here involves the entire basemap server being down, which means the simple "use the next basemap in the list" approach likely won't be of much use.
