### ISSUE TITLE
Remove hello-world from extensions in samples

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2663]
`api/hello-world` was created to show a very basic example of an extension.

It has been added to a number of the sample page `tpl` files.

This extension is intercepting double clicks (which should trigger a zoom) and presents a dialog which is difficult to clear.

`We detected a double click, but you may have just clicked twice slowly. Proceed anyways?`

It should be removed from the main samples. We can make a special sample that uses it if we want to preserve the glory of `hello-world`.

**Comment by YaroRoodzit** [comment]
Problem resolved. Tested with Chrome.
 Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-b1/dev/samples/index-samples.html
