### ISSUE TITLE
Samples Review

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2664]
A few samples have been asked to be examined.

Sample 26: Would appear this is disabling the "Trash Layer" function, but that normally isn't on in a structured legend.
Examine, and either rename the test or change the test to be an on-demand map.

Sample 28: Need confirmation if the "View Data Table" menu option should be visible and disabled.  It is currently not in the menu.  If display is correct, please rename the test to not use "Disabled". If display is incorrect, please fix the menu.

**Comment by YaroRoodzit** [comment]
Resolved. Tested with Chrome.
Tested build : /v2.3.0-b1
