### ISSUE TITLE
Snapping to embedded maps on mouse interactions

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2665]
Panning the map causes the browser to snap to it if any part of the map is off screen. 
In cases where a user is looking at half of a map, as well as other info, if the user pans (or otherwise interacts with the map) they will no longer have the same view they had.

This can be seen on CIP, as well as on non-fullscreen samples like http://fgpv.cloudapp.net/demo/v2.2.0/prod/samples/index-fgp-en.html

This is browser behaviour on an element getting focused, but other embedded maps such as Google Maps do not snap like this (https://www.chapters.indigo.ca/en-ca/home/storelocator/). It should also be noted that tabbing to the embedded map still gives it focus and snaps, which is expected.

**Comment by james-rae** [comment]
For what it's worth, Firefox seems to not be affected

**Comment by spencerwahl** [comment]
@AleksueiR Yes

**Comment by YaroRoodzit** [comment]
Tested with v2.4.0-b1. Issue resolved.
