### ISSUE TITLE
The version-github hyperlink fails when viewer called from remote page using iframe

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#2666]
The version-github hyperlink violates the Content Security Policy if CSP directive is not set in remote page using iframe.

`Refused to display 'https://github.com/fgpv-vpgf/fgpv-vpgf' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

![version-hithub-iframe](https://user-images.githubusercontent.com/2006029/39057198-a70c33e6-4486-11e8-8dd0-2a21af12edef.gif)

Suggestion: make elements in Menu's caption section configurable. 
e.g. remove hyperlink on Github stamp

**Comment by dane-thomas** [comment]
What's happening is that the app is trying to redirect the iframe to the github page and it's not liking that. 

I think the ideal solution would be for the parent page to redirect to the Github page rather than trying to load the page in the iframe.

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-b2. Issue resolved. Github hyperlink can be loaded, but with errors. 
![image](https://user-images.githubusercontent.com/38046459/41114451-7c1db758-6a52-11e8-9868-e49485ba56ab.png)

**Comment by AleksueiR** [comment]
Where are you getting these errors? On the Github page? They don't seem to be related to the viewer, just fonts being blocked by a policy.
