### ISSUE TITLE
"Zoom to Feature" icons not disabled in datagrid for a hidden layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2670]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-06/dev/samples/index-fgp-en.html?keys=JOSM

As discussed in #1134, 'Zoom To Feature' for any map points in a hidden layer should be disabled. Currently, the icons are still enabled in datagrid.

![image](https://user-images.githubusercontent.com/18723160/39209786-ce14957c-47d4-11e8-93a2-f7d3c79369d8.png)

**Comment by YaroRoodzit** [comment]
Problem resolved. Tested with Chrome.
Tested build: v2.3.0-b1
