### ISSUE TITLE
WET sample pages not loading in IE11

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2674]
Pages include:
- index-theme-wet.html
- index-theme-base.html
- index-theme-gc-intranet.html
- index-theme-gcweb.html

There is no visible map on these pages in IE11. Require at least one working WET sample to support CIP [task 38169](http://tfs.int.ec.gc.ca:8080/tfs/DC/CCPED/_workitems?_a=edit&id=38169&triage=true).

**Comment by james-rae** [comment]
looks working. donethanks
