### ISSUE TITLE
IE11 is working with errors and is broken after a certain update interval is specified

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2675]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-06/dev/samples/index-fgp-en.html?keys=JOSM
Browser used for test: IE11
Steps to reproduce:
- Open Viewer with provided URL 
- Open Layer > Setting > Set Refresh Interval( I used 1 min) and click Reload 
Now, try to change Zoom,Move Map,Hide all/Show all ect.
![ie_sample1](https://user-images.githubusercontent.com/38046459/39311101-0297367c-493a-11e8-9a68-364bf1fab2f1.jpg)
![ie_sample2](https://user-images.githubusercontent.com/38046459/39311108-08becff6-493a-11e8-9ad6-aa33d25a23c9.jpg)

See attached for more info.

**Comment by james-rae** [comment]
Whomever looks at this, see if having the `F11` console open or not makes a difference in the behavior

**Comment by dane-thomas** [comment]
Seems like this was an issue with a missing polyfill which has since been added. 

Can't reproduce this issue in the latest test build: http://fgpv.cloudapp.net/demo/v2.5.0-b1/dev/samples/index-fgp-en.html?keys=JOSM.
