### ISSUE TITLE
Add top offset to north pole icon and make flag use new api geometry point

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2678]
1. Ability to specify a top offset in screen pixels for the north arrow compass. This offset will need to be included in the compass trigonometry math.

![untitled](https://user-images.githubusercontent.com/10187181/39320721-053701fa-4953-11e8-9cb4-e78d4fa1ed99.png)

2. The north pole icon should now use the api geometry point object.

**Comment by AleksueiR** [comment]
There is a bit of hierarchy to the RAMP containers where stuff is put in.
- `rv-shell` - the outermost RAMP container which contains all RAMP elements
- `rv-inner-shell` - the container for RAMP controls and panels (appbar, legend panel, map navigation, pop-up dialogs, etc.) more info here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2622

The inner shell was added to accommodate a CIP requirements of having the map span the full length of the page with controls occupying only the center part of the map designated for content; it also served to offset the controls from the top to allow for a sliver of the map to be shown in the page header. The host page can easily control the placement of the RAMP controls without much fuss with some custom CSS.

Here's an example how to works:

__The inner shell with a blue border:__
![](https://i.imgur.com/2aTQ5Z6.png)

__CSS rules to offset the shell:__
![](https://i.imgur.com/7UEkA9g.png)

The north arrow should be moved to the `rv-inner-shell` container and it will be correctly offset by the host page. When calculating the arrow's angle, you need find actual pixel offset of the north arrow to include in the math.

**Comment by YaroRoodzit** [comment]
Tested with v2.4.0-b1. Issue resolved. Verified with James R.
