### ISSUE TITLE
Logic Error in New Layer Positioning

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2679]
See `FIXME` at this location
https://github.com/fgpv-vpgf/fgpv-vpgf/commit/ff8a3dbdc4620987102fa0998e8b6984150f347b#diff-dec82a4d46993f6dd36a141f9adeb738R194

The error does indeed exist. 
To reproduce, have a map with only non-feature based layers. Then add a feature layer (e.g. a geoJson file).  While the new layer will be in the correct order on the map, it will appear BELOW the other layers in the layer legend.

We'll need to enhance the logic at this spot to get the correct entry point for a first feature layer.

**Comment by james-rae** [comment]
Works good when first feature layer is added.
However, if you then add a second feature layer, it will appear under the first in the legend.  You will see the new layer correctly on top of the map, but then a few seconds later it dives below the first layer (likely the legend synchronization kicking in)

**Comment by YaroRoodzit** [comment]
Still problem. Discussed with Barry and Jahid.

**Comment by YaroRoodzit** [comment]
Test case 1:
1.1	Load sample #63
1.2	Change projection to Mercator .Select any basemap.
1.3	Load Canada.json  
1.4	Load HappyEnhance.json
1.5	Reorder layers and place Canada.json on top of HappyEnhance.json . Layers order did not change on screen.
1.6	Remove Canada.json  .Both feature layers removed from legend .
Test case 2:
2.1 Load /v2.4.0-b2/dev/samples/index-fgp-en.html Mercator projection. Select any basemap.
2.2 Load  ESRI Tile Layer:                                       
http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer
2.3 Load Canada.json  
2.4 Load HappyEnhance.json
2.5 Reorder layers and place Canada.json on top of HappyEnhance.json . Layers order did not change on screen.
2.6 Remove Canada.json  .Both feature layers removed from legend .

**Comment by barryytm** [comment]
After some testings done by @JahidAhmed and me. We've found that the issue @YaroRoodzit mentioned has to do with projection switching.  If the projection is changed different from the initial one, then the ordering of the newly added layers would be incorrect and the layer reordering would fail to work.

**Comment by barryytm** [comment]
An unrelated issue.  While we were testing.  We've also found that if the initial projection is set to Mercator, an error would show up in console.  I've created a new [issue](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2771) for it.

**Comment by barryytm** [comment]
I've opened https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2777 for @YaroRoodzit's new issue regarding to the layer positioning when projection is switched.
