### ISSUE TITLE
Attribution doesn't work as expected

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2695]
There is few problems with the attribution
 - The link value is not enable
 - The custom attribution is set once but when we switch basemap it is not reinitialize
 - The link was set in mapDefault but never change when we change basemap

**Comment by YaroRoodzit** [comment]
Tested with v2.4.0-b1. Sample #62. Working as designed. Attribution in the left bottom corner of the map changing when switching basemaps.
