### ISSUE TITLE
Panels API and Supporting Features

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2697]
Updates based on May 28th meeting

#### Changes
Changes have been made to both simplify panels, while allowing flexibility and organization in which they can be placed on the map. It is the responsibility of the panel creator to properly place a panel on the map.

- `Control` class has been removed, `Panel` class has a `controls` setter that is always on the top
- Panels can no longer have sub-panels, just content
- The map area is divided into 20x20 rectangles each being 5% width/height. A panel positions itself by providing a top left and bottom right square. You can no longer provide px or % for positioning. 
- There are observables for when the number of grid squares changes, like when going fullscreen or resizing the dom, the panel can adjust itself if it wants to
- in addition to a panel position, you can specify a minimum position that is contained within its position. This will shrink the panel if possible when another panel is open in its space.
- To create a panel, you call `mapInstance.createPanel(id);` and to delete you call `mapInstance.deletePanel(id);`.

```ts
class Panel {
  constructor(id: string): void;
  open(): void;
  close(): void;
  set controls(elems: PanelElem[]): void;
  get controls(): PanelElem[];
  get content(): PanelElem;
  set content(item: PanelElem): void;
  get id(): string;
  // returns the panel shell element
  get element(): jQuery<HTMLElement>;
  setPosition(topLeft: number,bottomRight: number): void;
  // The default for minPosition is just the position - meaning it won't resize. If set, the panel will be
  // adjusted up to its min position to accommodate other panels. 
  // minPosition must be subset of position. 
  setMinPosition(topLeft: number,bottomRight: number): void;
  widthChanged: Observable<number>; // the width in pixels of a grid square
  heightChanged: Observable<number>; // the height in pixels of a grid square
  positionChanged: Observable<number, number>; // topLeft, bottomRight
  opening: Observable;
  closing: Observable;
  /**
  * Returns an array of arrays representing each grid square. An array value can be the following:
  * -1 : Invalid panel position
  *  0 :  Valid panel position with no other panels capable to covering it (even partial cover)
  * 1+: Valid panel position with 1 or more other panels capable of covering it (even partial cover)
  *
  * If width and/or height are not provided the width/height can be computed from the panel position. 
  * If position is not set throw an error
  */
  static availableSpaces(width: number, height: number): number[][];
  // if no position is set, calculate based on a 1x1 panel.
  availableSpaces(): number[][];
  // returns the outer panel element, useful for changing width/height within a grid square (like being half a grid square for map buttons.
  get element(): jQuery<HTMLElement>;
}

/**
*  All elements will be scoped with their respective Control and PanelElem instance,
*  and therefore something like the following is valid:
*  <input onclick="this.visible = false; this.control.find('anotherBtn').visible = true;">
*/
class PanelElem {
  /**
  * Strings of either '|' or 'x' are shortcuts for a control divider and a close button respectively. All other text is considered to be a title. 
  */
  constructor(element: string | HTMLElement | jQuery<HTMLElement>): void;
  // strings are converted into HTML via jQuery - internally are types become jQuery<HTMLElement>
  // scope this element with the instance of the panel class such that `this.panel` is the panel instance it belongs to.
  get element(): jQuery<HTMLElement>;
}

class Btn extends PanelElem {
  set icon(svg: SVG): void;
  set text(txt: string): void;
}
```

**Comment by AleksueiR** [comment]
Things to add to Panel class:
- `z-index: number` - to overlap panels over each other
- `className` - to provide a custom CSS class names

I don't think need separate a `offset` property; `position` should be enough. All controls/panels should be rendered in the `innerShell` which can be offset by CSS rules (as in the CIP's case) and the panel's position would be relative to this `innerShell`. 

I also suggest adding `top` and `right` to the `position` property so you can size a panel relative to the container, without specifying explicit `height/width` values. (Or we can offload all that work onto the host page's CSS rules 😄).

Question: by `float`, do you mean CSS `float` or number `float`?
> position(top?: float, left?: float): void;

**Comment by milesap** [comment]
First part involves panel support on the API, existing panels to remain unchanged. Second part will involve converting existing panels to new API implementation and ripping out statemanager.

**Comment by ShrutiVellanki** [comment]
Just to make sure, in order to implement this, should I mainly be looking at refactoring code found in: 

- [ui.ts](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/api/src/ui.ts)
- [events.ts](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/api/src/events.ts) 
- [displaymanager.service.js](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/core/displaymanager.service.js)
- [statemanager.service.js](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/core/statemanager.service.js)

with (for example) [panel.directive.js](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/ui/panels/panel.directive.js) meant to be "using" this new implementation?

**Comment by milesap** [comment]
Based on pod discussion:

- No changes to the above files, when this PR merges you should be able to create new panels and control any panels created via the api.
- Existing panels remain unchanged (for now). The next step is moving them to the API.
- No changes to the look and feel. Feel free to copy/reuse HTML/CSS as needed. 
- No panel animations on open/close. 
- Code goes into `api` folder, written in TypeScript.

**Comment by milesap** [comment]
Major changes edited into original post. Some things will be easier (no more sub-panels or multiple control blocks!) Positioning is different 💩 I'll set a meeting for Monday to fully cover the changes and to determine if anything was missed that might be needed to migrate our existing panels.

**Comment by milesap** [comment]
### Meeting notes

The following items can be completed by Shruti for this panel release:

- Restrict the panel grid to the inner shell element (div element with class `rv-inner-shell`).
- Have the ability to set a panels width and height (based on its current position) as either: 
    - a percentage
    > Setting the width and height to 50% of a 4x5 panel would make it appear to be a 2x2.5 panel. For available spaces calculations this panel remains as a 4x5. 
    - or a pixel count
    > Pixels can be used as well but they cannot exceed the position on the grid. If they do the pixel count is ignored. This is to support things like map navigation controls that would exist in a panel with a fixed width of less than one grid square.
- Panel controls are optional. If none set do not display the controls header.

Once these are complete a PR can be opened and once merged we can work on two larger tasks:

#### Angular integration
We need the ability to add angular content to both the panel body and panel controls. I don't think this will be an issue, but I'll need to figure out where to place this logic so that the angular compiler and scope are available to the panel.

Here is how we create a new scope:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0/src/app/ui/table/table-default.directive.js#L279

This is where we compile the data table buttons:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0/src/app/ui/table/table-default.directive.js#L715

#### Break points
Currently, the legend panel remains the same size as the window is resized up - to a predefined break point.  Currently all panels scale to fit their position in the grid. Need to find a balance between usefulness and complexity as there does not seem to be an easy solution to implement perfect fixed width w/ break points in a grid environment.
