### ISSUE TITLE
Allow Web-Based File Layers in the Config Layer List

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2700]
Would be useful to allow a file-layer (GeoJSON, CSV, Zipped Shape) to be specified in the config's Layers list and loaded at application start.

Potential blocking problem: 
In https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1415 we ran into issues attempting to load files via web requests in the geoApi. Appeared to be due to our use of ESRI's `request` library and its use of the proxy.  See also https://github.com/fgpv-vpgf/fgpv-vpgf/issues/702

First verify if this is still a block or not. 

Once cleared, need to 

* propose a config schema for the file layer entries (type names, required info like name field, x/y field for csv, symbology colour)
* adjust layer load routines and config object file to handle new types
* add / adjust endpoints in geoApi to have a URL target for files instead of just being given the stream of data.

Alternate idea if `request` block is too much hassle:  Have angular make web request to the files (avoiding proxy mayhem), convert to data stream, and proceed creating the layer in the same manner as you would via the Add Layer wizard (but automated).

**Comment by james-rae** [comment]
@YaroRoodzit  found that the sample page fails in IE and Edge browsers for GeoJSON and CSV file samples.

**Comment by james-rae** [comment]
Also, appears the wizard cannot load those files either.  Console seems to indicate the migration to polyfills.io may be causing the problem 
See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3141

**Comment by ShrutiVellanki** [comment]
@james-rae note that this link: http://fgpv.cloudapp.net/demo/users/JahidAhmed/file-loading-through-config/dev/samples/index-samples.html?sample=85

which was part of #3133 merged in 18 days ago shows the same issues on IE. 

Migration to `pollyfills.io` done on #3141 was only merged in 10 days ago, so the problem might be deeper.

**Comment by james-rae** [comment]
Sadly he rebased on December 6th, which pulled in the polyfills.io . So that build has it.  I tried to re-create the "old polyfill" but need a Miles knowledge of the build tool

**Comment by dane-thomas** [comment]
The error message in Edge is:
```
SCRIPT438: Object doesn't support property or method 'forEach'
```
But I'm also getting
```
Layer proxy failed to resolve for "hydrometric-stations6k" [object Object]

Layer proxy failed to resolve for "happy" ReferenceError: 'TextDecoder' is undefined
```
which doesn't provide and additional insights

**Comment by james-rae** [comment]
Good finds everybody.
It looks like we have a `NodeList` support but perhaps that script is failing, since we're seeing `TextDecoder` undefined errors and those are defined here as well.

https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.6.0-b1/src/polyfills.js#L18

**Comment by YaroRoodzit** [comment]
Tested  with  Build v2.6.0-b2.
Sample 85. Layers are file-based and  loaded automatically.
Very slow with IE11. Good response with Chrome and Edge.
