### ISSUE TITLE
Inappropriate French translation for standby message "Building Table..."

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#2703]
Unless the standby message is to convey "**Table of the building...**",  "**Tableau de l'immeuble...**" is inappropriate.

In translations.csv:
`,table.splash.buildingtable,Building Table ...,1,Tableau de l’immeuble ...,0`

**Comment by james-rae** [comment]
Benoit, would `Édifice de la table...` be more appropriate?  If not could you provide a message that is? Thx

**Comment by YaroRoodzit** [comment]
Tested with v2.4.0-b1. Issue resolved.
