### ISSUE TITLE
Cloud based state storage options

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2704]
We currently preserve state in the URL, however the URL length is constrained by browsers which limits what we can save. User added services, layers, or possibly user drawn geometry (via API) are some things we cannot store in the URL. Intentions/extensions may also want the ability to add custom state values.

Moving state information into a json file stored in the ☁️ will allow users to share RAMP links which contain a link to their ☁️ json file. Some considerations:

🌩 We want to avoid providing our own cloud storage endpoint, users should have their own endpoint.
🌩 Which service(s) do we want to support? Google drive, dropbox, ... ? Should be firewall friendly.

### End user support
Users looking to share a link would be presented with compatible cloud drives such as Google and Dropbox. They would need an account to login to one of these services. Once logged in we would be granted permission to write our json file into their account and flag it as shareable. 

The good:
- Wide support across all cloud storage providers
- No central config hosting headaches
- No anonymous file uploading

The bad:
- Users need an account to share a link with one of the supported cloud providers.
- Additional login step to get share link

### Map author support
The map author would provide a well defined endpoint that we specify for uploading the json files. Likely a link to upload the json payload, with a return value of a url to the file. 

The good:
- Seamless to end users 
- Easier for us to implement

The bad:
- No api support for anonymous file uploads by all reputable/large cloud providers. Smaller file sharing sites are firewalled.
- Additional work for map author
- Open folders can be difficult to secure from bad people

**Comment by spencerwahl** [comment]
A different solution to possibly ponder;

With all the complexity that storing state in the cloud adds, maybe we should keep a simple "normal" URL based sharing, as well as offering endpoints in the API for snippets of the state (or the whole thing). This way a host page can implement cloud based storage, or any other means of using the state. I think most scenarios where sharing a RAMP map would be useful would also be fine with a simplified version of the state (like we have) shared through a URL.

**Comment by AleksueiR** [comment]
Since we need something very simple - like a key-value store - we can just use Github Gist. There are good JS libraries implementing their API and as a :heavy_plus_sign: you can read public gist without having to log in.

**Comment by james-rae** [comment]
> Additional login step to get share link

if this also means the person you send a bookmark too has to log in / know a password, would be great if we can avoid that (i.e. something along the lines of what Aleks is suggesting)

**Comment by AleksueiR** [comment]
Some json anonymous storage:
https://jsonbin.io/
http://myjson.com/

**Comment by milesap** [comment]
Alright, so I think the two prong approach works best here based on the feedback thus far. We can minify/compress the json state and test if it fits within the limits of a url. If its too large we revert to storing the json snippet in one of two (for now) cloud providers - https://jsonbin.io/ and http://myjson.com. If both providers fail we fall back to an extremely simple share link which contains your extent, zoom level, and basemap id. The user would be shown a warning that some state could not be preserved.

**Comment by james-rae** [comment]
Worth looking at and maybe doing at the same time?
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2709

For example, the basic lossy bookmark could be the intention, we provide a nice full state extension that's easy to set up, others can develop their own extension.

If it's too much to change at once, we can adopt 2709 later

**Comment by milesap** [comment]
Combining final thoughts into gist: https://gist.github.com/milesap/a089a0bfab4a97fd3adab358fe8bce35
