### ISSUE TITLE
Use two fingers to move the map on mobile devices

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#2705]
When viewing a map on smaller mobile devices, it can monopolize all window real estate which makes it a  frustrating experience for the user to scroll the web page instead of moving the map.

A solution might be to force the user to use two fingers to move the map, a la Google Maps:

![usetwofingers](https://user-images.githubusercontent.com/2006029/39767011-b4017ada-52b3-11e8-9d90-eca1501ec453.PNG)

**Comment by milesap** [comment]
Need to determine when this feature is activated, aka detect mobile platform, based on screen resolution, config setting etc.
