### ISSUE TITLE
Link is broken inside detail panel

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2707]
Download links for this layer doesn't work inside the detail panel. https://geoappext.nrcan.gc.ca/arcgis/rest/services/NRCAN/coverage_HRDEM_en/MapServer/1

They work fine from the table

**Comment by james-rae** [comment]
We are unable to reproduce. Can you check again? If it still happens for you, can you let us know the page you are hosting RAMP in, and which browser? Thx

**Comment by jolevesq** [comment]
Looks like it was resolve way back. I tested it with 2.2 and 2.3 and it works fine. Our 2.0 prod version was the problem
