### ISSUE TITLE
Basic Support for WMS layers (1.1.0, 1.3.0)

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#271]
- [x] WMS Services appear in TOC based on config
- [x] TOC includes a legend based on v1.1.1 standard
- [x] Layer settings are wired to UI settings panel

Related:
Differences in spec 1.1.0 vs 1.3.0 will be handled seperately: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/224

Traceability Matrix ID#084

**Comment by mweech** [comment]
Blocked on #197

**Comment by alexandreleroux** [comment]
Related to the support of WMS layers, in the current gcgeo.canada.ca version, after connecting to a WMS server, all layers are presented at the same level one after the other, ignoring the layer tree of the WMS GetCapabilities.

It would be very useful/essential to present WMS layers of a server with the structure provided in its GetCapabilities. This feature is crucial for browsing content of WMS servers which provide hundreds of WMS layers. Thanks! -- Alex :-)

**Comment by mweech** [comment]
Current scope of WMS support is confined to auto-legend/RCS based.  Structured legend and User Added Layers support for WMS layer hierarchy will be captured seperately.
