### ISSUE TITLE
GeoJSON & CSV Files fail to load in IE

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2722]
Function works in `v2.3.0`, but fails afterwards.

Prime suspect is the great polyfill overhaul that happened post `v2.3.0`

**Comment by AleksueiR** [comment]
Does it still work for shapefiles?

**Comment by james-rae** [comment]
WOMM.  Are you seeing it fail?

**Comment by AleksueiR** [comment]
No, just wanted to check because it's IE.
