### ISSUE TITLE
Trying to pan and zoom at the same time breaks all subsequent zoom attempts

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2730]
## Description
Trying to pan the map using a keyboard as it zooms in or out, prevents any subsequent keyboard-triggered (+/- keys of zoom in/out buttons on the map interface) zoom action from working.

**Version tested**: v2.4.0-4

### Steps to Reproduce
- tab to the map
- press + and -> keys simultaneously or in a very quick succession
- pres + or - key again

### Expected Results
The map zooms normally.

### Actual Results
The map doesn't want to zoom anymore. There is an uncaught error in the console.

### Logging Output / Screenshots
> index-fgp-en.html?keys=JOSM:1 Uncaught (in promise) undefined

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-b1. Issue resolved.

**Comment by AleksueiR** [comment]
Is this broken again?

**Comment by YaroRoodzit** [comment]
It works for me with Chrome.

**Comment by james-rae** [comment]
> Is this broken again?

if your asking due to this being re-opened, it was re-opened due to github acting weird on Barry's account and closing the issue prematurely.  It will be closed once `v2.4.0` is released
