### ISSUE TITLE
Propose implementation of an analytic platform

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2733]
Review if Google analytics is compliant with the treasury boards privacy/tracking requirements. Check if more suitable platforms exist. Determine metrics for use as benchmarking (page speed, average time spent, abandonment rate, etc.) and if heatmaps/feature use can be inferred.

**Comment by milesap** [comment]
We might need a lawyer:

https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=26761

Appendix A subclause 3 looks impossible to achieve. 

But then I viewed the page source and at the bottom I can see they're using Google analytics 🌻

I'll look into the platform to see how it can integrate with RAMP and post the results.

**Comment by mweech** [comment]
It really depends on if the code filters out the IP and provides a different identifier before transmittig back to Google AND if Google stores that IP if it is transmitted..

**Comment by milesap** [comment]
Luckily Google analytics has a few very good compliance tools:

1. User and event data retention (in months)
2. [IP Anonymization in Analytics](https://support.google.com/analytics/answer/2763052?hl=en)
3. [Individual user opt-out](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out) 

Looks like IP Anonymization should be used to avoid most compliance issues.

**Comment by bchagnon** [comment]
FYI we use the _ga("set", "anonymizeIp", true);_ setting where GA is implemented in our NRCan pages.  You might want to view the Web Analytics section in our  [NRCan - Terms and Conditions](https://www.nrcan.gc.ca/terms-conditions/10847) page for reference.

**Comment by milesap** [comment]
### Google Tag Manager
- Does not replace Google Analytics (GA), instead it is capable of watching for DOM changes and interactions and integrating these actions into reportable events for analytics (among other things).
- Not strictly needed, you can place GA code throughout your code base to send event information (like when a panel is opened, some feature is used, or a plugin is loaded. In some cases we may need to place GA code directly into RAMP
- The benefit is that most interactions do not need any modification to the RAMP code base. You can tell tag manager to watch for a certain element (CSS selector or ID) to be visible, clicks, javascript errors, scrolling etc). These changes are done in the tag management site, not in the code base.

### Google Analytics
Comprehensive tool which reports among others:
- Users country / region
- browser type and version
- time spent
- events triggered by tag manager
- event flow (order of actions they took on the page)
- abandonment analysis (why did they leave, what action did they take)
- performance benchmarks (page load, usability)
- compliance tools we can use (IP anonymization) so that no personal information is provided

### Next steps
1) Determine how we want to report events. We can set 4 event parameters (Category, Action, Label, and Value). This can be something along the lines of (UI, Panel, Grid-UI, Open) and (API, Plugin, Added, myPluginName) for example

2) Tag manager has versioning, so it can track variations of RAMP. Figure out how this will work with our versioning.

3) Determine things tag manager can't watch or would be difficult (perhaps plugins, API use) so that these events can be hard-coded into RAMP where needed.

4) If GA or tag manager is already present on the page, determine steps needed to add our tracking code, if not load appropriate google scripts.

**Comment by milesap** [comment]
#### Overview

Google Tag Manager (GTM) is a script we insert on bootstrap that together with its web interface is capable of watching the DOM for triggers such as elements becoming visible, clicks, JS errors, scrolling and more. You can also set timers that run custom JS code which would be able to inspect the current API state. Custom events from within RAMP can be pushed when the triggers are more complex and would be too difficult to implement within the GTM interface. 

We only need to include the GTM code snippet in ramp. Any events captured by GTM will be passed to our Google analytics (GA) account which provides advanced analysis on the events, times, order of events etc. 

#### Treasury board compliance

We will anonymize IP addresses where GTM performs this anonymization before writing it to disk. We will limit stored records to 18 months per treasury board guidlines. No personal information is uploaded and therefore we meet all guidelines.  

#### Loading script

Google supports multiple GTM script tags to be used where there is more than one tracking account. So if the WET template contains GTM code, it is recommended to also include another GTM script code using our tracking ID. Ramp can insert this script on bootstrap.

#### Manual events (coded in RAMP)

GTM can handle most tags and events. In some cases we might need to manually send an event from RAMP to GTM, but I believe this is unlikely given the available options. If needed however, this is done by pushing an object to a global `dataLayer` object which is watched by the GTM. An example:

```js
dataLayer.push({
	event: "RV-UI",
	eventCategory: "Panels",
	eventAction: "Open",
	eventLabel: "Grid-UI"
});
```

Since there can be multiple instances of GTM on a page (WET, RAMP) and they must both use the same global `dataLayer` array, the solution is to use custom `event` properties like we did above with `RV-UI`. In GTM we can set a trigger for the event `RV-UI` and push that to our analytics account. Other instances of GTM would ignore these events.

#### Event reporting

We will have a few custom event types (subject to change/add/remove based on feedback):
- RV-UI : For UI interaction with panels, settings, menu etc.
- RV-API: To track general API use at a high level (API class creation) and common uses
- RV-PLUGINS: Capture loaded intentions/extension
- RV-ERROR: Capture specific points of failure or try to catch most/all RAMP errors to see general app health

#### Versioning

As different versions of RAMP are released, the trigger type/selector may change due to changes in our html or user flow. GTM has the concept of versioning, and assigning versions to environments. For example, if we change a buttons name/id that was being used by GTM to track clicks in ramp v2.4.0 then we could save the new name/id under v2.4.0 in GTM and update the script type GTM uses to point to version v2.4.0. v2.3.0 (with the old name/id) would continue to be tracked correctly as well since it is using the v2.3.0 version as it always has.

**Comment by AleksueiR** [comment]
> if the WET template contains GTM code

We should assume all WET pages have the GTM code included. All the sample you get from their github do.

##### Several RAMP instances
When collecting data from a page with several RAMP instances, do we want to distinguish them apart by including an internal id or something like that?

**Comment by milesap** [comment]
That's true, and it's fine if there is/isn't an existing gtm script. gtm supports/needs a separate script for each tracking account on a page. They must share a global `dataLayer` object, however pushed data to the global `dataLayer` must be configured within the gtm site for it to be recorded on analytics. If, for example, two tracking accounts exist on a page with two corresponding apps which listen on the same event name then either app can trigger both accounts listeners. This is avoided by using non-generic event names.

I thought about tracking multiple maps on a page, and it is possible. Before implementing something like this it might be worth reporting how many pages use multiple maps and if the number is large enough to go ahead with implementing it. 

The current PR segments analytics by ramp version, multiple maps could be another possible segment.
