### ISSUE TITLE
Enhance keyboard-based identify

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2736]
Mockups:
- https://invis.io/WZJ7OWFEF6U#/298577715_10a-Ds-06-L_03
- https://invis.io/8YJ7OXQV73C#/298577717_10a-Ds-06-L_04

Behaviour:
- blue highlight around the map is displayed around the map when it's keyboard focused
- arrow keys pan the map; holding Shift pans the map faster
- `+/-` keys zoom the map in/out
- pressing "Enter" triggers an identify call
- crossharis are centered relative to the rv-shell; if the inner shell is not center aligned, crosshairs can appear off-center
- a hover tooltip is displayed above or beneath the crosshairs when the crosshairs pass over a feature
- the tooltip is fixed relative to the map container;

Related issues:
- [bug] #2730 - breaks keyboard-based zoom when trying to pan during zoom animation

**Comment by AleksueiR** [comment]
Crosshairs is visible against both light and dark basemaps:
![](https://i.imgur.com/YubuMmY.png)
![](https://i.imgur.com/87YPZPQ.png)

**Comment by AleksueiR** [comment]
#### Movement and identify
![keyboard-identify](https://user-images.githubusercontent.com/2285779/40558052-27be341c-6020-11e8-98bb-117284e80d25.gif)

#### On-hover tooltips
![](https://i.imgur.com/hUtwv0V.gif)

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-b1. Working as designed.

**Comment by james-rae** [comment]
Yaro found an interesting situation that could arise. If the mouse is over the map, you get hovertips triggering off both mouse cursor and gun cursor. Just mentioning if this is a problem or not. @AleksueiR  please advise.

(Star is where the mouse pointer is)

![gunmouse](https://user-images.githubusercontent.com/7585245/40858616-dc1488da-65ac-11e8-9208-5442a2cd5063.jpg)

**Comment by AleksueiR** [comment]
The keyboard-navigation mode is enabled when the map received focus and is disabled when the map loses focus. The mouse cursor will always trigger the tooltip.

We can disable the keyboard mode on mouse movements and it will solve this particular problem, but I don't think this is a good idea. People will end up accidentally canceling the keyboard mode by nudging their pointer devices, 

In a way, this is the expected behaviour - you get a tooltip when you are actively pointing to things.

I don't think this is a problem and suggest just have it logged until people complain.
