### ISSUE TITLE
Timestamp not formatted properly

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2738]
The export timestamp is not formatted properly it is for example YYYY-05-DD 13:45:23 instead of 2018-05-28 13:45:23.

![screen shot 2018-05-28 at 3 14 07 pm](https://user-images.githubusercontent.com/3472990/40626976-fe1d6ce2-6289-11e8-8a7b-1a1d86b96252.png)

**Comment by YaroRoodzit** [comment]
Tested with v2.4.0-b1/dev/samples/index-samples.html. Issue resolved.
