### ISSUE TITLE
Run RAMP through the Fortify security tool

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2745]
Run a basic page with a RAMP map through the Fortify security tool.

Investigate the results. Be aware the tool has a history of giving false positives.

Take action on any tangible threats.

**Comment by mweech** [comment]
Funding for a scan of fortify has been identified via the CCCS viewer project.  License for run of scan will be available soon.

**Comment by ShrutiVellanki** [comment]
@mweech alright, thank you!

**Comment by milesap** [comment]
RAMP has passed the fortify static analysis as part of the CCCS project on August 17.
