### ISSUE TITLE
WFS 3.0 Layer Support

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2748]
Create initial / basic support for WFS 3.0

Leverage the geoJson output of WFS 3.0 and our geoJson to Esri Feature adapter we use for files.

At this point, we will only support loading one individual collection in a WFS service as a layer. Multiple collections need to be loaded as separate layers.

We recognize the 3.0 spec is not finalized, and will adjust our adapters as needed once it is.

Related to #400 (supports a subset of this issue).
Related to #2726 (uses the plumbing that issue creates)

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b1. Sample #68. WFS layers loaded successfully.

**Comment by bkutty** [comment]
Will need to test with different sample file as and when they become available
