### ISSUE TITLE
Table dates filtering from config not working properly

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#2749]
Filtering a table using dates defined in a config file doesn't work. It just loads everything.

Test is done with a range:
```
...
{
    "data": "LAST_UPDATED",
    "title": "LAST_UPDATED",
    "filter": {
                   "type": "date",
                   "value": "2005-02-22,2005-04-30"
                }
}
...
```
The service is Geochronology:
[https://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer](https://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer)

Here some observations:

- The table is looking for 'rv-date' format and not 'date' as defined in the schema;
- Once we put 'rv-date' the problem is still there;
- Filtering with the datePicker is working properly;
- Searching for a particular date with the search tool is working properly (e.g. LAST_UPDATED:2005-02-22).
- Found problems with the way dates are loaded from the config

Solution:
 - Change the way dates are loaded from config file;
 - Explore the replacement of 'rv-date' by 'date' everywhere. Potential conflicts with reserved word Date.

**Comment by ChrisLatRNCan** [comment]
Reworked all the table date filtering. Have now similar filtering results from config, search and DatePicker.

**Comment by ChrisLatRNCan** [comment]
Wrong minutes and secondes displayed in viewer for type date.

Time should look similar to what is shown by AGOL for the same service:
[http://webservices.maps.canada.ca/arcgis/rest/services/NRCan/EGS_Flood_Product_CurrentYear_fr/MapServer/1](http://webservices.maps.canada.ca/arcgis/rest/services/NRCan/EGS_Flood_Product_CurrentYear_fr/MapServer/1)

**Comment by ChrisLatRNCan** [comment]
Error from IE11 as expected 😆  : 

>Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**Comment by ChrisLatRNCan** [comment]
These ways of range filtering will return 🤞 same amount of features:
From config
>"value":"AAAA-MM-DD,AAAA-MM-DD"

From seach box
>COLUMN_NAME:[AAAA-MM-DD..AAAA-MM-DD]

**Comment by ChrisLatRNCan** [comment]
Did more tests:
 ```
     "filter": {
           "type": "date",
            "value": "min,max"
     }
```
For lower bound only, those definitions will give the same result
"value": "min,"
"value": "min"

For upper bound only, there's just one way of doing things
"value": ",max"

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b1. Sample 61.  Filtering by dates works properly.
