### ISSUE TITLE
Flickering Hovertip on Right Side of Map

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2754]
To reproduce:

- Open fgp viewer with oil sands layer (e.g. `index-fgp-en.html?keys=JOSM` )
- Zoom in so that a JOSM point is near the right-side edge (east) of the map.
- Mouse over it to turn on the hover tip.
- Watch the hover tip flail.

Possibly an issue with the positioning logic?

**Comment by YaroRoodzit** [comment]
Just found out, on-hover tooltips flickering when map point is near the left-side edge as well as right-side.

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-b2. Issue resolved.
