### ISSUE TITLE
Setting GeoSearch to false in config breaks the map

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#2758]
From a config snippet:
```
   "map":{  
      "initialBasemapId":"baseEsriStreet",
      "components":{  
         "geoSearch":{  
            "enabled":true,
            "showGraphic":true,
            "showInfo":true
         }...
```

Setting "enabled" to false will return an error in the map. 

![image](https://user-images.githubusercontent.com/5294596/40984503-0f05778a-68b0-11e8-8216-7fa134a68376.png)

**Comment by james-rae** [comment]
Was fixed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2743 , we just didn't bother making an issue for it. So this should be live when `v2.4.0` is published (soon™)
