### ISSUE TITLE
Plugin loading and developer tooling

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2765]
We currently have an `intension.service.js` file. Review if this can be changed to `plugin.service.js` (that handles both intentions/extensions) or if a new service is needed for extensions.

Keep `rv-extensions` backwards compatible in https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/init-map.directive.js#L107 so that urls continue to load older style plugins and now optionally parses window objects for the new system. Something like:

```js
extensionList.forEach(ext => {
  if (ext.match(/http/)) {
    $.ajax({method: 'GET', dataType: 'text', ext})
       .then(data => eval(`(function(mapInstance) { ${data} })(apiMap);`));
  } else {
    window[ext].init(apiMap);
  }
});
```

Url support can be removed in future v3.

Mainly to start support for repo https://github.com/fgpv-vpgf/extensions

Also see if there is an easier way to integrate the extensions repo during the ramp build step such that extension distribution files are moved into RAMP samples automatically.

**Comment by james-rae** [comment]
PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2773
