### ISSUE TITLE
User added ESRI Dynamic layer not grouped together with existing Dynamic layers

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2766]
Tested build: http://fgpv.cloudapp.net/demo/v2.4.0-b2/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

- Add above test data as ESRI Dynamic layer, select ProtectedAreaNationalView
- Check the user added layer Positioning
This user added layer is placed on top of Railway WMS layer, and not grouped with existing Dynamic layers (NPRI, CESI, and EcoAction) which are underneath WMS layer.
![image](https://user-images.githubusercontent.com/18723160/41062999-5f7d3a54-69a5-11e8-90a9-dbba76b66f13.png)

**Comment by james-rae** [comment]
WMS and Dynamic share the same "area" of the legend, so this behavior is correct.  Adding a new layer adds it to the top of it's group.... so a WMS or Dynamic (or Tile) will go to the top of that group, and a feature / file will go to the top of the feature group (top of the legend).
