### ISSUE TITLE
Area of interest does not refresh after switching config

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2767]
Area of interest does not refresh after switching and reloading an another config in the sample page. 

Tested page: sample 64 in  http://fgpv.cloudapp.net/demo/v2.4.0-b2/dev/samples/index-samples.html.

![capture](https://user-images.githubusercontent.com/19259169/41106521-2c3b3788-6a3e-11e8-8ab4-f89edb06c910.JPG)

**Comment by YaroRoodzit** [comment]
Problem resolved. Tested with Chrome, IE, FireFox.
