### ISSUE TITLE
Sample #01 - WMS Layer in Visibility Set not shown up in the Viewer when toggled to visible

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2768]
Tested build: http://fgpv.cloudapp.net/demo/v2.4.0-b2/dev/samples/index-samples.html

![image](https://user-images.githubusercontent.com/18723160/41122298-11ac336a-6a69-11e8-9e54-9a14880a7ff3.png)

**Comment by YaroRoodzit** [comment]
Tested with build: v2.5.0-b1 .Sample 1. WMS layer is shown.
