### ISSUE TITLE
Console error when Mercator is set as default projection

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2771]
An error related to projection shows up in console when setting Mercator as the default projection.

![capture](https://user-images.githubusercontent.com/19259169/41173280-431eb33a-6b24-11e8-83c8-eada2acbea17.JPG)

**Comment by barryytm** [comment]
The same error happens when switching to Mercatorfrom another projection as well.

**Comment by mweech** [comment]
appears to be resolved in 2.4
