### ISSUE TITLE
Structured legend config cannot be updated

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2776]
When using `mapI.setLegendConfig` the north arrow layer is found and causes the update to fail.

The layer is missing the `config` object in its `_viewerLayer`. Which makes me believe there are a couple solutions:
1. Remove the layer from the API layer list
2. add a dummy config object to the layer (I have no idea if this would work properly)
3. make the structured legend pretend the layer doesn't exist

To verify removing the layer from the API list would work:
- open up a RAMP instance with a structured legend
- `RZ.mapInstances[0].mapI.setLegendConfig({"root": {"name": "root","children": []}})`
- An error will be thrown saying `source` does not exist
- `RZ.mapInstances[0].layers.allLayers.splice(0,1)`
- `RZ.mapInstances[0].mapI.setLegendConfig({"root": {"name": "root","children": []}})`
- No error should be thrown

**Comment by milesap** [comment]
Problem is likely with `simpleLayer` in general, so option 3 seems best since they are not shown in structured legends.

**Comment by spencerwahl** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2716
