### ISSUE TITLE
Layer positioning error when switching to a different projection

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2777]
@YaroRoodzit has discovered this issue and please see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2679 for more details.

When switching to a projection different than the initial one.  The layer positioning will be incorrect and the layer re-ordering will also be malfunction.  It seems the information of layer ranking is lost in the transition and it somehow disabled the re-ordering function.

**Comment by barryytm** [comment]
The issue also occurs when the language is changed.

**Comment by YaroRoodzit** [comment]
Problem resolved. Tested with index-fgp-en.html AND  index-samples.html
