### ISSUE TITLE
Update sample configs to have north pole enabled for Lambert projection

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2780]
To accommodate https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2772.

Put `"hasNorthPole": true` under `tileSchemas` for Lambert maps in all config files.

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.4.0`  
- checked out the `v2.4.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2781  were included in the code

Still no longer an issue as checked with current develop.

Closing issue.
