### ISSUE TITLE
Read web map and web app id

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2784]
Get information about a web app and a web map. Inside the geoApi there is only the call to get the item id information. When you a protected ArcGIS online portal, we need to add credential. This portion is taking care of inside the calling application. It is easier this way because the caller is the one who is able to overrides vendor css.

**Comment by james-rae** [comment]
https://github.com/fgpv-vpgf/geoApi/pull/306
