### ISSUE TITLE
Implement Scalebar

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#279]

**Comment by AleksueiR** [comment]
Angular Material doesn't have a vertical slider yet (a PR has been submitted last month). Can we defer this task until it's included? I don't want to use esri scalebar.

**Comment by dan-bowerman** [comment]
I believe Jack has already implemented this? We must have this feature for the March 31st release.

**Comment by AleksueiR** [comment]
Oh, sorry, I misread this as zoombar :( never mind
