### ISSUE TITLE
formatLayerAttributes function should place icon in attribute bundle

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2790]
While removing the current table implementation I came across this `todo`. 

See https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.service.js#L331 and https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.service.js#L404

**Comment by mweech** [comment]
Unknown issue.
