### ISSUE TITLE
Reduce build history size on fgpv.cloudapp.net

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2792]
Frequently having travis builds not get published to our cloudapp

TODO: update or implement our travis cleanup scripts to capture the following discussion from chat:

alyec
> Build sizes are getting out of hand. I may have to allocate more storage on that machine or increase the frequency of the cleanup.

AleksueiR
> Didn't Miles reduce the build sizes?

alyec
> Is ~30m per build what I should be seeing?

AleksueiR
> This seems excessive.
> Oh, that must be the source maps bloating the build.

alyec
> For now we should be good for a few weeks. When we figure out what the build size should be I'll see if I need a bit more storage.
> I've been trying to keep a history for every released version, I could also change that rule since they're going to be on github anyways (I figured it might help for checking regressions).

james-rae
> Suggestion from a person who knows nothing about this sort of thing: Order a student to write a script to clean up the source maps (assuming they are what's causing build gerth) on older builds. So we can keep some older history around, but they are slimmer.
> Feel free to shoot that down.

milesap
> I'll see what I can do to reduce build sizes going forward. i.e. leave out dist on non tagged builds, omit source maps on certain builds etc

alyec
> Good point. I'll definitely add that.
> milesap I think James' suggestion probably works best. Don't worry about it on the build side we can deal with it on the VM side (where it's way easier to fiddle with shell scripts).

**Comment by mweech** [comment]
Build server issues should not be handled via RAMP github page anymore.
