### ISSUE TITLE
Improve service loading feedback

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2794]
### Problem

The data architecture for this project is expected to use Geomet WFS and WMS services.  Earlier non-prod query times are on an order of 9-10 seconds.  Although a speed increase for production can be expected, it is still expected to have a greater load time than desired for smooth interaction with the user.  In order to provide more obvious feedback in cases where delays are expected, we need to determine options for increasing feedback to the user on loading delays. 

### Solution

A new service called `ShellService` is created to track various loading processes and their effects on the global loading status (the global loading status is displayed by a progress bar along the bottom edge of the map).

Any module can register a process that takes time to complete (not necessarily a layer load/update) by supplying a following signature:

```ts
{
    {id} [string] - id of the loading process; used to clear the loading process when it's completed
    {initDelay} [number] [optional=0] - initial delay before the loading process is marked as `active`; this is a convenience so the caller code can avoid using timeouts; useful to avoid setting indicator for a small amounts of time
    {messageDelay} [number] [optional=4000] - delay before the notification is displayed
    {messageDuration} [number=0] - specifies how long the notifcation will be shown
    {message} [string] [optional=''] - the text of the message to be displayed when the process is going on for longer than the `messageDelay` value
    {action} [string] [optional=''] - the text of the toast action button; clicking on the action button closes the notification and resolves the returned promise; the caller code can wait on that promise to perform some action
}
```

A process is marked as active only after the `initDelay` time has elapsed; the global loading status is `true` if at least one of the registered processes is active. 

When added, individual processes have an option to display a notification message after the specified period of time and also allow for a user action via the notification action button. Notifications are automatically removed when their corresponding processes clear.

Notification do not stack, but they queue. If the first one is dismissed, the next one is shown. 

At the moment, only three types of processes are being registered: `map-init`, `map-update` and `layer-load`.

- `map-init` - refers to the initial loading of the map; used only once and will not display any notifications;
- `map-update` - a catch-all process to track any map updates; will trigger on layer loads/updates, but will not show any notifications;
- `layer-load` - will be registered when a layer record is generated from a layer blueprint and cleared when a `rv-loaded` event is fired by that record; will display a "taking-longer-than-expected" notification after 4000 ms (or other time delay if overridden by the config) with an option to dismiss the notifications;

A new option is added to the layer schema definitions:

**expectedResponseTime** - The time span after which a 'slow-to-respond' notification is shown for any loading or refreshing layer. Defaults to 4000 ms.

### Demo

![](https://i.imgur.com/5HTsR8q.gif)

![](https://i.imgur.com/RuBjCJj.gif)

**Comment by YaroRoodzit** [comment]
Tested with build: v2.5.0-b1 .Sample 1. WMS layer is shown. A message appears for a slow loading layer.
