### ISSUE TITLE
Implement enhancedTable

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2798]
Using [ag-grid community edition](https://www.ag-grid.com). 

In no particular order, a rough outline of the work required:

- [x] remove all existing table code/functionality
- [x] add ag-grid table and populate with columns and rows
- [x] disable focusManager on the table to allow ag-grid to handle focus movements
- [x] activate ag-grid features like sort and filter
- [x] re-enable some features like print, export, and re-sizing
- [x] determine the table `intention` interface - how will it work within ramp and the api
- [x] implement `intention` interface
- [x] change table to new panel api, particularly with the removal of statemanager

MOVED to new issues:
- add filter by extent
- add zoom to feature row button
- add view details panel row button
- add documentation

Currently with 100,000+ rows the table is loading in under 1 second with filtering/sorting enabled.

**Comment by milesap** [comment]
### Current progress

Basic implementation into table panel with headers working, columns/data, and sorting/filtering. 

![enhancedtable](https://user-images.githubusercontent.com/10187181/41717647-63b9fe48-7528-11e8-8af8-37bda2801779.gif)

**Comment by AleksueiR** [comment]
Decided against `ui-grid`?

**Comment by mweech** [comment]
Issue complete.  Work continues on the following multiple part issues:
#3077 
#3079
#3080
#3105
#3132
