### ISSUE TITLE
Shareable URL / Get Link

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#280]
Basic requirements:
- allow for sharing of services and viewer state via a easily shareable and familiar URL format
- implementation should allow for backwards compatibility as changes to the state occur
- provide a similar dialog for providing either a short or long link as provided by RAMP (minus the email button)

Basic state that must be captured:
- list of RCS keys (if present)
- state of layers (order, opacity, visibility, bounding box visibility, loading mode)
- basemap selected
- current zoom level
- current extent
Traceability Matrix ID#070

Tasks:
- [x] Create layer bookmark items
- [x] assemble layers together for bookmark
- [x] Grab extent info for bookmark
- [x] Grab basemap for bookmark
- [x] Parse layers from bookmark
- [x] Parse data within layerRecord
- [x] Parse and use basemap
- [x] Parse and use extent
- [x] load RCS layers from bookmark (And wait for them before trying to apply bookmark data)
- [x] add api hook for bookmark creation/parsing

**Comment by spencerwahl** [comment]
A proposal for bookmarking:

## Structure
### Layers:

We will store layers and their data as one string, this reduces repitition and space requirements

Strings will follow the form (without pipes):

type | id | data, [next layer]

The format of "data" is determined by the layer type. e.g. default: index | opacity | vis | BB | snapshot

### Extent:

Extent will be stored in the form:

zoom level | x of center | y of center

We have the possibility of separating x and y with a delimiter or we could pad after the decimal to standardize accuracy (and allow easy regex parsing)

### Basemap:

The basemap will be stored in the same way as RAMP, using the index in the selector

### Complete:

basemap,extent,layers

This is easily added to a url as one parameter, e.g. blah.html?rv=123123123...&someotherkey=...&...

We also still have the option of compressing this string if space becomes a concern

## Creation

With the layer record refactor, layers will be stored as classes. We can add a "bookmark" function to these classes to output their data string. This makes it very easy to wrap everything up and report it only when the bookmark is needed.

At creation time:

- find basemap
- append ","
- find center of map
- find zoom level
- append ","
- for each *top-level* layer:
    - call bookmarking function
    - append ","



inside that bookmarking function:

- find layerType
- find id
- find index (map or legend? Maybe just insert layers based on legend position and assume the correct order on retrieval?)
- find needed data (settings panel items)


## Parsing

Basic steps:
- characters up to first `,` used as basemap index
- next chunk used as extent info
- the rest is passed through a layer regex which
    - finds the layer type
    - uses the layer type to find length of data string
    - finds delimiter and moves backwards to capture the data
    - takes everything from end of type to start of data and uses that as the ID
- then the data strings are passed to their respective layer records (using the IDs)

The layer records will then have functions that know how to unpack their data strings and assign those values to their respective fields.

Initial bookmark layer regex would look something like:

00(.\*?)(.{8})|01(.\*?)(.{6})| etc.

An example layer record regex would look like:

(.{2})(.{3})(.{1})(.{1})(.{1})

**Comment by mweech** [comment]
@spencerwahl can you provide a sample of how the following layers would resolve into a bookmark (at some random extent)? 

http://fgpv.cloudapp.net/demo/develop/index-fgp-en.html?keys=EcoAction,Railways,mb_colour,Airports

**Comment by spencerwahl** [comment]
Using the method of bookmarking based on legend position:

`?rv=0,[zoom and extent],00Airports100100,01EcoAction10010,02Railways10010,02mb_colour10010`

**Comment by james-rae** [comment]
**encoding of layers**: do we need a restriction on numerics in layer ids?  a leading or trailing digit could mess up the decode (note: i really dont understand regex so maybe you've handled this).

**basemap**: we may need the key for compatibility (link becomes kinda wrong if more basemaps get added).  If so, would want to shorten our keys.

**extent**:
standardizing co-ordinate accuracy gets tricky when switching between a projection in meters and a projection in degrees.

* difference between `6,124,424.32` and `6,124,424.3` meters is a few centimeters
* difference between `50.5` and `50.55` degrees is 5 kilometers
  * horizontal amounts differ with position...accuracy more important near equator

**Comment by spencerwahl** [comment]
**layers:** I figured 2 digits would be more than plenty for layer types (and therefore we'd know that the first two digits of a layer bookmark would always be the type). From that type we also always know the length of the data string. Using that length and the delimiter to mark the end we can always find where the id ends and the data starts.

in the layer regex: `00` is the layer type `(.\*?)` is the id (non-greedy selector takes whatever isn't taken by everything else) and `(.{x})` is the known length data string

**basemap:** agreed

**extent:** I was thinking more along the lines of padding with 0's (this would require knowing the maximum accuracy), I agree taking away accuracy would be a terrible idea. It's probably better to just throw a character in between the x, y and zoom that we know wont show up in any of them (not sure if commas are safe)

**Comment by mweech** [comment]
suggestion: if we ever have to add to the state we capture in the data portion, we would potentially have issues dealing with older bookmarks.  on that note, we should insert a simple bookmarking scheme version ID. that way if the content of the bookmark changes, we would be able to maintain backwards compatibility.

**Comment by james-rae** [comment]
**extent**: yeah.  padding 0's works, but will add a lot of redundant 0s for co-ords in meters, which is what we normally deal with.  special character sounds dandy. I've always been fond of `~`

**Comment by AleksueiR** [comment]
Some other options we discussed:
- size of a bookmark is not a concern if a third-party service is used (git gists, pastebin, etc.)
  - the link must be available indefinitely (which we cannot guarantee in this case)
- have the user download a config file with full state and then import it in another map instance
- have the user copy serialized state as text and then paste that in another map instance

Notes:
- use standard share icon in the menu:
![](https://materialdesignicons.com/api/download/icon/png/C25D5913-39C7-4215-B372-88F90EE2B6E5)

**Comment by spencerwahl** [comment]
Blocked for now until #606 progresses more

**Comment by spencerwahl** [comment]
Update: Estimate was waaaaaay off. Main contributor was the amount of PRs I was in charge of last week, in addition to the design making this look too easy to me. Ran into troubles and had to redo sections, this was further stretched out due to PRs limiting the amount of productive time I had.

**Comment by spencerwahl** [comment]
Everything but creation of bookmarks on demo pages is done. Will be PR'd on Monday.

**Comment by spencerwahl** [comment]
testable using index-fgp-en and index-fgp-fr
