### ISSUE TITLE
Structure legend symbology stack

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2800]
We should have the ability to have the symbology stack expand by default for structured legend. for now we have the ability to have group entry expand but not entry.

![image](https://user-images.githubusercontent.com/3472990/41723857-2c89dda0-753a-11e8-9c1d-f2131ddc64cb.png)

**Comment by YaroRoodzit** [comment]
Verified with build v2.5.0-b3. As expected.
