### ISSUE TITLE
Show/hide details column's from table setting

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2803]
We can remove fields and set visibility from table but this have no effect on the details panel.

![Screen Shot 2018-06-21 at 2.08.55 PM.png](https://images.zenhubusercontent.com/5695178c638e718c99600115/12bb6760-4a8a-47a6-b0f4-2d2d0a38feb3)

![Screen Shot 2018-06-21 at 2.09.09 PM.png](https://images.zenhubusercontent.com/5695178c638e718c99600115/96ff57dc-3208-485c-ad05-8d7b23a67c12)

**Comment by james-rae** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2485

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2 . Works as expected.
