### ISSUE TITLE
Design Options for JSON File Data Table

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2805]
Original request can be found in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1415

Things have changed a bit since that request, and we are now looking at supporting layers that traditionally had no attribute support at all (i.e. adding a table feature instead of just making existing table features faster).

Basically, the concept is for a layer we can target a json file to use as a source to populate the data table for that layer.  There are a number of considerations for how fancy we make this.

### Unlinked

In this case, the data table is essentially independent of the layer, with the exception that clicking the layer in the legend will open the table. Any additional functions (e.g. zoom to feature, details, icons) will need to be addressed for the unlinked case (details in sections below).

This case is a :bear: minimum to implement.

### Linked

In this case, the data table (and all other functions that run off attributes) remain connected to the map layer. The only difference is when the app goes to download the attribute set, it will source it from the json file instead of querying the map service. ObjectIds in the json file must align to the Ids on the map service.

Why use a json file when the service already exists? Some benefits include faster load time, and possibly supporting Dynamic Layers on servers that have the `/query` endpoint disabled.

The linked case will only work on layers that already support ESRI attributes (i.e. anything that inherits from `AttribRecord` -- mainly Feature Layers and Dynamic Layers).

Supporting the linked mode is more work, but lets us hit additional use cases. If we decide not to implement in the first cut of file based tables, we should at least attempt to design the new code to allow support in the future.

### ESRI-like Dictionary

This approach stores attributes in the JSON file using a similar/identical structure to how ArcGIS Server provides attributes. The pro of this approach is our current parsing routines can eat it raw. We can also create content from existing ESRI sources with relative ease. The con is the file size will be larger as attribute keys are repeated for every entry.

```text
{
 fields: [
  {
   name: "Field1",
   type: "esriFieldTypeString",
   alias: "Field One",
   length: 200
  },
  {
   name: "Field2",
   type: "esriFieldTypeDouble",
   alias: "Field Two"
  }
 ],
 features: [
  {
   attributes: {
    Field1: "Big Duck Pond",    
    Field2: 12.82
   }
  },
  {
   attributes: {
    Field1: "Germy Lake",    
    Field2: 4.98
   }
  }
 ]
}
```

### Array Based Structure

This approach stores data in an array form (making it look similar to a table). The pro of this approach is the file size is minimized. The con is we need to write parsing code, and possibly it is more effort to translate date into this structure when generating the files.

```text
{
 fields: [
  {
   name: "Field1",
   type: "esriFieldTypeString",
   alias: "Field One",
   length: 200
  },
  {
   name: "Field2",
   type: "esriFieldTypeDouble",
   alias: "Field Two"
  }
 ],
 features: [
  [ "Big Duck Pond", 12.82 ],
  [ "Germy Lake", 4.98 ]
 ]
}
```

As it stands, this is the recommended approach for speed gains.

### Split Structure

This approach separates the bulk data and the metadata into two files. This lets us quickly download table metadata (e.g. field names) up front if we need them. Whether this is necessary depends on how much support we give to non-attribute layer types (e.g. tabe on WMS, table on ESRI Tile). If we essentially disable everything but "table view" then it may be unnecessary.

### Core Elements

Need an optional property on a `layerNode` element to allow a url to a json file to be defined. The presence of a value in that property will trigger the appropriate setup for a file based grid (see sections below).

### Optional Elements

Potential for additional properties to define enhanced things.

* Marking a lat & long field in the data to enable a zoom to point function
* An indicator if the file is linked to the layer, or is independent (e.g. object ids in file align to object ids on service). Should default to unlinked for safety.
* Ability to provide an icon for each row.  This could be enhanced to fancier structures (essentially providing a class break or unique value renderer type thing); not recommended at this point.
* Ability to specify a name field? Would be needed if we want to support a details pane view with a reliable title value (See `Details Pane` section below for more analysis).

If we are considering adding options beyond the url, we may want to create a sub-object to contain all the json table properties.

E.g. (field names not final):

```text
{
  id: "myLayer",
  url: "http://myserver.com/fancymap/",
  jsonTable: {
    url: "http://myserver.com/fancytable.json",
    linked: false,
    icon: "http://myserver.com/happyDuck.png"
  }
}
```

### Considerations

* Files must be loaded in the Angular code (using `$http.get()`). The request library in geoApi fails with files due to the proxy being cooked into `esriRequest`. (See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2061#issuecomment-313451883 )
* The results can be provided from the same function within geoApi as normal attributes. See `attribute.js - newLayerPackage()`.
  * The loading from the server should not begin until `layerPackage.getAttribs()` is first called.
  * This approach allows for existing workflows regarding the table / attributes to be re-used with minimal impact
* The results can be provided via a separate mechanism
  * Would only support unlinked mode
  * The "load the table" step would recognize its the json file case and call the alternate method to get data
  * Allows us to ignore compatibility issues of trying to have traditional attributes and json file attributes existing harmoniously in the same workflows

### Implementations

If attempting to integrate with the standard `getAttribs()` approach:

* We want the actual web request in angular, so that function will exist in the viewer. However, we trigger our attribute load from the geoApi.
  * Suggest our new geoApi function to setup the file table mode should accept a loader function.  This way, when the geoApi is ready to load the table (usually first time opening the table), it can just execute the registered loader function. 
  * Makes geoApi blissfully unaware that it's using angular.
  * Allows the option to switch to a different load approach later, as long as the function interface remains the same.
* Likely need an alternate form of `newLayerPackage`, or need to overwrite it's `getAttribs` function. 
  * The new function needs to see if `_attribData` exists, and if not, it needs to make a new Promise
  * Inside new Promise: execute the registered function to trigger the $http.get(), then massage result from json file format into esri format
  * Resolve Promise with proper object (see `createAttribSet`)
* Likely need a third function similar to `loadFileAttribsBuilder` and `loadServerAttribsBuilder` (probably closer to `loadFileAttribsBuilder` in content).
  * It will set the various metadata properties correctly.
  * Need to be aware of sources, particularly if we are dealing with a layer that doesn't natively have attributes (e.g. fields would have to come from file, so they may not be set upfront)

If taking the separate mechanism route -- we can pretty much do whatever we please.

## Layer Objects

This new feature has the potential to complicate our layer hierarchy in geoApi. Attribute support is currently confined to the `AttribRecord` class and all inheritors. File based tables means classes not derived from `AttribRecord` now require some level of support.

### Minimal Approach - Integrated

This approach essentially fakes the attribute loader on layers not related to `AttribRecord`.  It would not use the class inheritance, and would instead inject appropriate functions onto Record/FC objects to make things look compatible.

We can also entertain doing this on `AttribRecord` based classes, where we overwrite existing attribute loader logic with file loader logic on a case-by-case basis.  This is a bit risky in that there are quite a few related functions that depend on attributes and may break / act weird.

### Minimal Approach - Separate Mechanism

This ties into the separate mechanism approach described in the `Loading Mechanism` section above.  Basically the json file to grid flow is separate from all existing structure.

This approach will only support the Unlinked mode. So it causes the least amount of chaos, but offers the least amount of value.

### Reeefactor

This involves significant changes to the Layer Record / FC object hierarchies.  While it would need further analysis if we decide to persue this, at a high level:

* Attribute support would need to exist at a low level in the hierarchy. The `LayerRecord` class would make sense.
* The `LayerRecord` implementation could have the file based load support. If no file has been defined in the config, it can return an empty array or an error (to be decided which is more appropriate).
* The `AttribRecord` class would retain it's code for supporting ArcGIS Server based attribute loading. However, it would need to allow for recognizing the file based case, and let the logic drop through to `LayerRecord`.  In other words, it can't just steamroll the attribute logic; it needs to allow both branches of code to execute depending on the configuration.

This approach offers good support for all layer types, and best supports the Linked mode (having file that aligns with server data).

## Details Pane

In unlinked mode, we have a few choices

* Disable the details pane.  The data is in the grid anyways so its just showing the same thing but in vertical layout.
  * Lazy!
  * Should remove the detail button from the grid.
* Push data to the standard zebra-stripe attribute view.
  * May need to disable things like zoom to feature and icon, depending on what configuration options we've added.
  * May also have to guess or suppress the "name field" if we have decided to not make that a config option (or it was not provided) 
* Could make the detail pane a configuration option.
  
In linked mode, everything should work as normal as the data will be aligned to the layer metadata.

## Zoom To Feature

In unlinked mode:
* Default behavior would be no zoom. Button should not be in the grid.
* Can have optional lat-long columns defined in config to zoom to point. Would involve a projection and then the zoom to point pipeline.
  * If geometry is a line/poly, only real option is to use the lat-long as centroid and accept that zoom level may be a poor choice for the shape.

In linked mode, everything should work as normal as the data will be aligned to the layer metadata.

## Hovertips

In the case of having a layer that natively supports attributes, and we are using a json sourced table, and the table is not aligned to the service, we would need to disable hovertips, or force them to always use the one-shot quickloader (essentially ignoring the attribute store even though it exists).

**Comment by mweech** [comment]
Closing incomplete R&D work until issue is revised.
