### ISSUE TITLE
Ability to define enhanced symbology for WFS Layer

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2807]
At the moment we are using the Wizard Engine to support the WFS Layer creation.  This means symbology customization is limited to picking a colour.

We can explore a few options for enhancement.

* Ability to set an image / base64 string for point symbols.  Likely the most useful one, as lines and polygons look good with simple symbology.
* Border colour for polygons
* Circle size for non-image point symbols
* We can also consider looking at the work being done in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2718 , and perhaps there is a way to leverage this (it's a bit of collision between API and Config)

**Comment by james-rae** [comment]
Essentially a duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2878

**Comment by mweech** [comment]
Done,thanks
