### ISSUE TITLE
Abstraction of Data Loading Code from Import Wizard

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2808]
When loading WFS layers via the config file, we still leverage a decent amount of code from with Add Layer Wizard.

Consider (i.e. needs more analysis) abstracting the loading parts to a new service, and have the Wizard and Config based loaders leverage that service.

**Comment by AleksueiR** [comment]
I think this can be closed now - that data loading process has been moved to the `layerBlueprint`.
