### ISSUE TITLE
Keyboard identify crosshairs tooltip is sometimes misaligned

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2809]
### Problem
The tooltips is not properly positioned. So far this was noticed only in the CCCS build.
This happens because the size of the crosshairs image is taken into account when positioning the tooltip and sometimes the image doesn't load fast enough return the default icon size of 24x24.

![](https://i.imgur.com/T07VXyt.png)

### Solution
Deffer getting the dimensions of the crossharis image until the first extent change cause by the keyboard navigation.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b1. Issue resolved.
