### ISSUE TITLE
Support for any projection

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#281]
Support for WKIDs specifically -- if it's not searchable through http://epsg.io/, we don't want it.

Traceability Matrix ID#077

**Comment by dan-bowerman** [comment]
Working, not where it needs to be for it's final state.

**Comment by dan-bowerman** [comment]
Some code needs Esri WKID which is not always there...

**Comment by dan-bowerman** [comment]
Code needs refactoring in the future.

**Comment by dan-bowerman** [comment]
If we can meet at least the projections used in R1/ RAMP 5.4.2, we're sitting pretty.

**Comment by mweech** [comment]
Priority reduced to medium as FGP projection support is already covered directly.

**Comment by james-rae** [comment]
Projection lookup intention should give us piles of flexibility.  Donethanks
