### ISSUE TITLE
WCAG 2.0 "AA" Compliance for R2

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#282]
# 1.1 Text Alternative
### 1.1.1 Non-text Content:
All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, except for the situations listed below. (Level A)
 - Controls, Input: If non-text content is a control or accepts user input, then it has a name that describes its purpose. (Refer toGuideline 4.1 for additional requirements for controls and content that accepts user input.)
 - Time-Based Media: If non-text content is time-based media, then text alternatives at least provide descriptive identification of the non-text content. (Refer to Guideline 1.2 for additional requirements for media.)
 - Test: If non-text content is a test or exercise that would be invalid if presented in text, then text alternatives at least provide descriptive identification of the non-text content.
 - Sensory: If non-text content is primarily intended to create a specific sensory experience, then text alternatives at least provide descriptive identification of the non-text content.
 - CAPTCHA: If the purpose of non-text content is to confirm that content is being accessed by a person rather than a computer, then text alternatives that identify and describe the purpose of the non-text content are provided, and alternative forms of CAPTCHA using output modes for different types of sensory perception are provided to accommodate different disabilities.
 - Decoration, Formatting, Invisible: If non-text content is pure decoration, is used only for visual formatting, or is not presented to users, then it is implemented in a way that it can be ignored by assistive technology.
[How to Meet 1.1.1](https://www.w3.org/WAI/WCAG20/quickref/###qr-text-equiv-all) | [Understanding 1.1.1](https://www.w3.org/TR/[Understanding-WCAG20/text-equiv-all.html)

# 1.2 Time-based Media	
### 1.2.1 Audio-only and Video-only (Prerecorded): 
For prerecorded audio-only and prerecorded video-only media, the following are true, except when the audio or video is a media alternative for text and is clearly labeled as such: (Level A)
 - Prerecorded Audio-only: An alternative for time-based media is provided that presents equivalent information for prerecorded audio-only content.
 - Prerecorded Video-only: Either an alternative for time-based media or an audio track is provided that presents equivalent information for prerecorded video-only content.
[How to Meet 1.2.1](https://www.w3.org/WAI/WCAG20/quickref/#qr-media-equiv-av-only-alt) | [Understanding 1.2.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-av-only-alt.html)

### 1.2.2 Captions (Prerecorded):
 Captions are provided for all prerecorded audio content in synchronized media, except when the media is a media alternative for text and is clearly labeled as such. (Level A)
[How to Meet 1.2.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-media-equiv-captions) | [Understanding 1.2.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-captions.html)

### 1.2.3 Audio Description or Media Alternative (Prerecorded): 
An alternative for time-based media or audio description of theprerecorded video content is provided for synchronized media, except when the media is a media alternative for text and is clearly labeled as such. (Level A)
[How to Meet 1.2.3](http://www.w3.org/WAI/WCAG20/quickref/#qr-media-equiv-audio-desc) | [Understanding 1.2.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-audio-desc.html)

### 1.2.4 Captions (Live):
 Captions are provided for all live audio content in synchronized media. (Level AA)
[How to Meet 1.2.4](http://www.w3.org/WAI/WCAG20/quickref/#qr-media-equiv-real-time-captions) | [Understanding 1.2.4](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-real-time-captions.html)

### 1.2.5 Audio Description (Prerecorded):
 Audio description is provided for all prerecorded video content in synchronized media. (Level AA)
[How to Meet 1.2.5](http://www.w3.org/WAI/WCAG20/quickref/#qr-media-equiv-audio-desc-only) | [Understanding 1.2.5](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-audio-desc-only.html)

# 1.3 Adaptable
### 1.3.1 Info and Relationships: 
Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text. (Level A)
[How to Meet 1.3.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-content-structure-separation-programmatic) | [Understanding 1.3.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

### 1.3.2 Meaningful Sequence: 
When the sequence in which content is presented affects its meaning, a correct reading sequence can beprogrammatically determined. (Level A)
[How to Meet 1.3.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-content-structure-separation-sequence) | [Understanding 1.3.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html)

### 1.3.3 Sensory Characteristics: 
Instructions provided for [Understanding and operating content do not rely solely on sensory characteristics of components such as shape, size, visual location, orientation, or sound. (Level A)
Note: For requirements related to color, refer to Guideline 1.4.
[How to Meet 1.3.3](http://www.w3.org/WAI/WCAG20/quickref/#qr-content-structure-separation-understanding) | [Understanding 1.3.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-understanding.html)

# 1.4 Distinguishable
### 1.4.1 Use of Color: 
Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element. (Level A)
Note: This success criterion addresses color perception specifically. Other forms of perception are covered in Guideline 1.3 including programmatic access to color and other visual presentation coding.
[How to Meet 1.4.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-without-color) | [Understanding 1.4.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html)

### 1.4.2 Audio Control: 
If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume independently from the overall system volume level. (Level A)
Note: Since any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether or not it is used to meet other success criteria) must meet this success criterion. See Conformance Requirement 5: Non-Interference.
[How to Meet 1.4.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-dis-audio) | [Understanding 1.4.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-dis-audio.html)

### 1.4.3 Contrast (Minimum): 
The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following: (Level AA)
 - Large Text: Large-scale text and images of large-scale text have a contrast ratio of at least 3:1;
 - Incidental: Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.
 - Logotypes: Text that is part of a logo or brand name has no minimum contrast requirement.
[How to Meet 1.4.3](http://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-contrast) | [Understanding 1.4.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)

### 1.4.4 Resize text: 
Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality. (Level AA)
[How to Meet 1.4.4](http://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-scale) | [Understanding 1.4.4](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html)

### 1.4.5 Images of Text: 
If the technologies being used can achieve the visual presentation, text is used to convey information rather thanimages of text except for the following: (Level AA)
 - Customizable: The image of text can be visually customized to the user's requirements;
 - Essential: A particular presentation of text is essential to the information being conveyed.
Note: Logotypes (text that is part of a logo or brand name) are considered essential.
[How to Meet 1.4.5](http://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-text-presentation) | [Understanding 1.4.5](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-text-presentation.html)

# 2.1 Keyboard Accessible
### 2.1.1 Keyboard
All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes, except where the underlying function requires input that depends on the path of the user's movement and not just the endpoints. (Level A)
Note 1: This exception relates to the underlying function, not the input technique. For example, if using handwriting to enter text, the input technique (handwriting) requires path-dependent input but the underlying function (text input) does not.
Note 2: This does not forbid and should not discourage providing mouse input or other input methods in addition to keyboard operation.
[How to Meet 2.1.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-keyboard-operation-keyboard-operable) | [Understanding 2.1.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)

### 2.1.2 No Keyboard Trap
If keyboard focus can be moved to a component of the page using a keyboard interface, then focus can be moved away from that component using only a keyboard interface, and, if it requires more than unmodified arrow or tab keys or other standard exit methods, the user is advised of the method for moving focus away. (Level A)
Note: Since any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether it is used to meet other success criteria or not) must meet this success criterion. See Conformance Requirement 5: Non-Interference.
[How to Meet 2.1.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-keyboard-operation-trapping) | [Understanding 2.1.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html)

# 2.2 Enough Time
### 2.2.1 Timing Adjustable: 
For each time limit that is set by the content, at least one of the following is true: (Level A)
 - Turn off: The user is allowed to turn off the time limit before encountering it; or
 - Adjust: The user is allowed to adjust the time limit before encountering it over a wide range that is at least ten times the length of the default setting; or
 - Extend: The user is warned before time expires and given at least 20 seconds to extend the time limit with a simple action (for example, "press the space bar"), and the user is allowed to extend the time limit at least ten times; or
 - Real-time Exception: The time limit is a required part of a real-time event (for example, an auction), and no alternative to the time limit is possible; or
 - Essential Exception: The time limit is essential and extending it would invalidate the activity; or
 - 20 Hour Exception: The time limit is longer than 20 hours.
Note: This success criterion helps ensure that users can complete tasks without unexpected changes in content or context that are a result of a time limit. This success criterion should be considered in conjunction with Success Criterion 3.2.1, which puts limits on changes of content or context as a result of user action.
[How to Meet 2.2.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-time-limits-required-behaviors) | [Understanding 2.2.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-required-behaviors.html)

### 2.2.2 Pause, Stop, Hide: 
For moving, blinking, scrolling, or auto-updating information, all of the following are true: (Level A)
 - Moving, blinking, scrolling: For any moving, blinking or scrolling information that (1) starts automatically, (2) lasts more than five seconds, and (3) is presented in parallel with other content, there is a mechanism for the user to pause, stop, or hide it unless the movement, blinking, or scrolling is part of an activity where it is essential; and
 - Auto-updating: For any auto-updating information that (1) starts automatically and (2) is presented in parallel with other content, there is a mechanism for the user to pause, stop, or hide it or to control the frequency of the update unless the auto-updating is part of an activity where it is essential.
Note 1: For requirements related to flickering or flashing content, refer to Guideline 2.3.
Note 2: Since any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether it is used to meet other success criteria or not) must meet this success criterion. See Conformance Requirement 5: Non-Interference.
Note 3: Content that is updated periodically by software or that is streamed to the user agent is not required to preserve or present information that is generated or received between the initiation of the pause and resuming presentation, as this may not be technically possible, and in many situations could be misleading to do so.
Note 4: An animation that occurs as part of a preload phase or similar situation can be considered essential if interaction cannot occur during that phase for all users and if not indicating progress could confuse users or cause them to think that content was frozen or broken.
[How to Meet 2.2.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-time-limits-pause) | [Understanding 2.2.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-pause.html)

# 2.3 Seizures
### 2.3.1 Three Flashes or Below Threshold: 
Web pages do not contain anything that flashes more than three times in any one second period, or the flash is below the general flash and red flash thresholds. (Level A)
Note: Since any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether it is used to meet other success criteria or not) must meet this success criterion. See Conformance Requirement 5: Non-Interference.
[How to Meet 2.3.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-seizure-does-not-violate) | [Understanding 2.3.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html)

# 2.4 Navigable
### 2.4.1 Bypass Blocks: 
A mechanism is available to bypass blocks of content that are repeated on multiple Web pages. (Level A)
[How to Meet 2.4.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-skip) | [Understanding 2.4.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html)

### 2.4.2 Page Titled: 
Web pages have titles that describe topic or purpose. (Level A)
[How to Meet 2.4.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-title) | [Understanding 2.4.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html)

### 2.4.3 Focus Order: 
If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability. (Level A)
[How to Meet 2.4.3](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-focus-order) | [Understanding 2.4.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html)

### 2.4.4 Link Purpose (In Context): 
The purpose of each link can be determined from the link text alone or from the link text together with itsprogrammatically determined link context, except where the purpose of the link would be ambiguous to users in general. (Level A)
[How to Meet 2.4.4](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-refs) | [Understanding 2.4.4](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html)

### 2.4.5 Multiple Ways: 
More than one way is available to locate a Web page within a set of Web pages except where the Web Page is the result of, or a step in, a process. (Level AA)
[How to Meet 2.4.5](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-mult-loc) | [Understanding 2.4.5](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-mult-loc.html)

### 2.4.6 Headings and Labels: 
Headings and labels describe topic or purpose. (Level AA)
[How to Meet 2.4.6](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-descriptive) | [Understanding 2.4.6](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html)

### 2.4.7 Focus Visible: 
Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible. (Level AA)
[How to Meet 2.4.7](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-focus-visible) | [Understanding 2.4.7](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html)

# 3.1 Readable
### 3.1.1 Language of Page:
 The default human language of each Web page can be programmatically determined. (Level A)
[How to Meet 3.1.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-meaning-doc-lang-id) | [Understanding 3.1.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-doc-lang-id.html)

### 3.1.2 Language of Parts:
 The human language of each passage or phrase in the content can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text. (Level AA)
[How to Meet 3.1.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-meaning-other-lang-id) | [Understanding 3.1.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-other-lang-id.html)

# 3.2 Predictable
### 3.2.1 On Focus: 
When any component receives focus, it does not initiate a change of context. (Level A)
[How to Meet 3.2.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-consistent-behavior-receive-focus) | [Understanding 3.2.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-receive-focus.html)

### 3.2.2 On Input: 
Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised of the behavior before using the component. (Level A)
[How to Meet 3.2.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-consistent-behavior-unpredictable-change) | [Understanding 3.2.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html)

### 3.2.3 Consistent Navigation:
 Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in thesame relative order each time they are repeated, unless a change is initiated by the user. (Level AA)
[How to Meet 3.2.3](http://www.w3.org/WAI/WCAG20/quickref/#qr-consistent-behavior-consistent-locations) | [Understanding 3.2.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-locations.html)

### 3.2.4 Consistent Identification: 
Components that have the same functionality within a set of Web pages are identified consistently. (Level AA)
[How to Meet 3.2.4](http://www.w3.org/WAI/WCAG20/quickref/#qr-consistent-behavior-consistent-functionality) | [Understanding 3.2.4](http://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-functionality.html)

# 3.3 Input Assistance
### 3.3.1 Error Identification: 
If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text. (Level A)
[How to Meet 3.3.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-minimize-error-identified) | [Understanding 3.3.1]()

### 3.3.2 Labels or Instructions: 
Labels or instructions are provided when content requires user input. (Level A)
[How to Meet 3.3.2]() | [Understanding 3.3.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-identified.html)

### 3.3.3 Error Suggestion: 
If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user, unless it would jeopardize the security or purpose of the content. (Level AA)
[How to Meet 3.3.3](http://www.w3.org/WAI/WCAG20/quickref/#qr-minimize-error-suggestions) | [Understanding 3.3.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-suggestions.html)

### 3.3.4 Error Prevention (Legal, Financial, Data): 
For Web pages that cause legal commitments or financial transactions for the user to occur, that modify or delete user-controllable data in data storage systems, or that submit user test responses, at least one of the following is true: (Level AA)
	1. Reversible: Submissions are reversible.
	2. Checked: Data entered by the user is checked for input errors and the user is provided an opportunity to correct them.
	3. Confirmed: A mechanism is available for reviewing, confirming, and correcting information before finalizing the submission.
[How to Meet 3.3.4](http://www.w3.org/WAI/WCAG20/quickref/#qr-minimize-error-reversible) | [Understanding 3.3.4](http://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-reversible.html)

# 4.1 Compatible
### 4.1.1 Parsing: 
In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features. (Level A)
Note: Start and end tags that are missing a critical character in their formation, such as a closing angle bracket or a mismatched attribute value quotation mark are not complete.
[How to Meet 4.1.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-ensure-compat-parses) | [Understanding 4.1.1](http://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

### 4.1.2 Name, Role, Value: 
For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can beprogrammatically set; and notification of changes to these items is available to user agents, including assistive technologies. (Level A)
Note: This success criterion is primarily for Web authors who develop or script their own user interface components. For example, standard HTML controls already meet this success criterion when used according to specification.
[How to Meet 4.1.2](http://www.w3.org/WAI/WCAG20/quickref/#qr-ensure-compat-rsv) | [Understanding 4.1.2](http://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

**Comment by mweech** [comment]
Issue is blocked until a functional release is available.

**Comment by dan-bowerman** [comment]
[RAMP GIS Viewer BeSD Assessment.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/408952/RAMP.GIS.Viewer.BeSD.Assessment.xlsx)

**Comment by dan-bowerman** [comment]
Updated to remove "AAA" requirements, we're only focused on WCAG "AA" for now.

**Comment by dan-bowerman** [comment]
Just noting here, I am only assessing the full-screen RAMP view, e.g. index-one.html. This is not an assessment for WET or any other templates that might contain the map.
