### ISSUE TITLE
Select basemap layer thumbnail

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2820]
Be able to select the basemap layer to use to generate thumbnail. When we have more then one layer it takes the first one added. In our sample the first one his the hillshade and the second one the real info. Check if we can use both layers for thumbnail or set one inside the configuration file.

**Comment by AleksueiR** [comment]
I think we can use all the layers specified on a basemap to generate the thumbnail; any opacity values set on these layers should be applied to corresponding thumbnail components.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. As expected.
