### ISSUE TITLE
WMS Layer has odd positioning

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2821]
http://fgpv.cloudapp.net/demo/v2.5.0-b1/prod/samples/index-samples.html
Sample 1.  Enable the visibility for the WMS layer.

You will notice the wind arrows seem to skew towards the west coast.  

Zoom in to around 300km scale level.   Do pans from Alberta to Newfoundland.  Enjoy the erratic drawing of the arrows.

I have verified that the bounding boxes that RAMP is providing to the WMS service are correct.

It's possible the issue is with the WMS service.

Sample WMS image request.
```text
http://geo.weather.gc.ca/geomet?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&LAYERS=GDPS.ETA_UU&WIDTH=727&HEIGHT=499&CRS=EPSG:3978&BBOX=-1280618.220938108,167420.59025484716,642906.4594445864,1487694.0641351284&styles=WINDARROWKMH
```

**Comment by mweech** [comment]
This is definitely a service issue.  It consistently stops generating the wind coverage at a max size.
