### ISSUE TITLE
Unlinked JSON File Datatable

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2823]
Parent issue: #2805 

The following needs to be implemented in the first round:

### Unlinked

In this case, the data table is essentially independent of the layer, with the exception that clicking the layer in the legend will open the table. Any additional functions (e.g. zoom to feature, details, icons) will need to be addressed for the unlinked case (details in sections below).

### ESRI-like Dictionary

This approach stores attributes in the JSON file using a similar/identical structure to how ArcGIS Server provides attributes. The pro of this approach is our current parsing routines can eat it raw. We can also create content from existing ESRI sources with relative ease. The con is the file size will be larger as attribute keys are repeated for every entry.

```text
{
 fields: [
  {
   name: "Field1",
   type: "esriFieldTypeString",
   alias: "Field One",
   length: 200
  },
  {
   name: "Field2",
   type: "esriFieldTypeDouble",
   alias: "Field Two"
  }
 ],
 features: [
  {
   attributes: {
    Field1: "Big Duck Pond",    
    Field2: 12.82
   }
  },
  {
   attributes: {
    Field1: "Germy Lake",    
    Field2: 4.98
   }
  }
 ]
}
```

### Core Elements

Need an optional property on a `layerNode` element to allow a url to a json file to be defined. The presence of a value in that property will trigger the appropriate setup for a file based grid (see sections below).

If we are considering adding options beyond the url, we may want to create a sub-object to contain all the json table properties.

E.g. (field names not final):

```text
{
  id: "myLayer",
  url: "http://myserver.com/fancymap/",
  jsonTable: {
    url: "http://myserver.com/fancytable.json"
  }
}
```

### Considerations

* Files must be loaded in the Angular code (using `$http.get()`). The request library in geoApi fails with files due to the proxy being cooked into `esriRequest`. (See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2061#issuecomment-313451883 )
* The results can be provided via a separate mechanism
  * Would only support unlinked mode
  * The "load the table" step would recognize its the json file case and call the alternate method to get data
  * Allows us to ignore compatibility issues of trying to have traditional attributes and json file attributes existing harmoniously in the same workflows

### Implementations

If attempting to integrate with the standard `getAttribs()` approach:

* We want the actual web request in angular, so that function will exist in the viewer. However, we trigger our attribute load from the geoApi.
  * Suggest our new geoApi function to setup the file table mode should accept a loader function.  This way, when the geoApi is ready to load the table (usually first time opening the table), it can just execute the registered loader function. 
  * Makes geoApi blissfully unaware that it's using angular.
  * Allows the option to switch to a different load approach later, as long as the function interface remains the same.
* Likely need an alternate form of `newLayerPackage`, or need to overwrite it's `getAttribs` function. 
  * The new function needs to see if `_attribData` exists, and if not, it needs to make a new Promise
  * Inside new Promise: execute the registered function to trigger the $http.get(), then massage result from json file format into esri format
  * Resolve Promise with proper object (see `createAttribSet`)
* Likely need a third function similar to `loadFileAttribsBuilder` and `loadServerAttribsBuilder` (probably closer to `loadFileAttribsBuilder` in content).

## Layer Objects

This new feature has the potential to complicate our layer hierarchy in geoApi. Attribute support is currently confined to the `AttribRecord` class and all inheritors. File based tables means classes not derived from `AttribRecord` now require some level of support.

### Minimal Approach - Separate Mechanism

This ties into the separate mechanism approach described in the `Loading Mechanism` section above.  Basically the json file to grid flow is separate from all existing structure.

This approach will only support the Unlinked mode. So it causes the least amount of chaos, but offers the least amount of value.

## Details Pane

In unlinked mode, we have a few choices

* Disable the details pane.  The data is in the grid anyways so its just showing the same thing but in vertical layout.
  * Lazy!
  * Should remove the detail button from the grid.
* Push data to the standard zebra-stripe attribute view.
  * May need to disable things like zoom to feature and icon, depending on what configuration options we've added.
  * May also have to guess or suppress the "name field" if we have decided to not make that a config option (or it was not provided) 

## Zoom To Feature

In unlinked mode:

* Default behavior would be no zoom. Button should not be in the grid.

## Hovertips

In the case of having a layer that natively supports attributes, and we are using a json sourced table, and the table is not aligned to the service, we would need to disable hovertips, or force them to always use the one-shot quickloader (essentially ignoring the attribute store even though it exists).

**Comment by mweech** [comment]
Closing incomplete R&D work until issue is revised.
