### ISSUE TITLE
Share link is empty when viewing complex exclusiveVisibility layer

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#2827]
When viewing the esriDynamic  https://geoappext.nrcan.gc.ca/arcgis/rest/services/EGS/CENSUS_2016/MapServer service with a structured legend set with exclusiveVisibility, the Link to Share output is empty and emits a console error.

error:
`bookmark.service.js:301 Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at bookmark.service.js:301
    at bookmark.service.js:279
    at Array.map (<anonymous>)
    at t (bookmark.service.js:275)
    at bookmark.service.js:277
    at Array.map (<anonymous>)
    at t (bookmark.service.js:275)
    at bookmark.service.js:241
    at bookmark.service.js:65
    at Array.map (<anonymous>)`

config:
`{
								"name" : "Population - Census 2016",
								"expanded" : false,
								"controls" : [ "visibility", "settings" ],
								"children" : [
									{
										"exclusiveVisibility" : [
											{
												"layerId" : "1d51c94e",
												"entryIndex" : 1
											},
											{
												"layerId" : "1d51c94e",
												"entryIndex" : 2
											},
											{
												"layerId" : "1d51c94e",
												"entryIndex" : 4
											},
											{
												"layerId" : "1d51c94e",
												"entryIndex" : 3
											},
											{
												"layerId" : "1d51c94e",
												"entryIndex" : 5
											}
										]
									}
								]
							}`

result:
![complexe_exclusivevisibility_sharelink](https://user-images.githubusercontent.com/2006029/42350224-87cecc7c-807d-11e8-8e8b-bd72e869cced.png)

**Comment by ShrutiVellanki** [comment]
@bchagnon  Hello! I'm having trouble replicating the steps for this issue with the link provided. I don't seem to get radio buttons on my map (just checkboxes) so i can't really test it

**Comment by ShrutiVellanki** [comment]
@bchagnon Hi, I've tried to replicate your issue with [this link](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/exclusive-dynamic/dev/samples/index-samples.html). (sample 74). The bookmark link seems to be working fine for me with no related console errors.

Here's the full related config, let me know if I'm missing anything:

```js
"legend": {
      "type": "structured",
      "root": {
        "name": "root",
        "children": [
          {
            "name": "People and communities",
            "expanded": false,
            "controls": [
              "visibility",
              "settings"
            ],
            "children": [
              {
                "name": "Population - Census 2016",
                "expanded": false,
                "controls": [
                  "visibility",
                  "settings"
                ],
                "children": [
                  {
                    "exclusiveVisibility": [
                      {
                        "layerId": "1d51c94e",
                        "entryIndex": 1
                      },
                      {
                        "layerId": "1d51c94e",
                        "entryIndex": 2
                      },
                      {
                        "layerId": "1d51c94e",
                        "entryIndex": 4
                      },
                      {
                        "layerId": "1d51c94e",
                        "entryIndex": 3
                      },
                      {
                        "layerId": "1d51c94e",
                        "entryIndex": 5
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    },
    "layers": [
      {
        "id": "1d51c94e",
        "name": "Population - Census 2016",
        "layerType": "esriDynamic",
        "layerEntries": [
          {
            "index": 1
          },
          {
            "index": 2
          },
          {
            "index": 3
          },
          {
            "index": 4
          },
          {
            "index": 5
          }
        ],
        "url": "https://geoappext.nrcan.gc.ca/arcgis/rest/services/EGS/CENSUS_2016/MapServer/"
      }
    ]
```

**Comment by ShrutiVellanki** [comment]
Tried to reproduce the issue after rebasing onto `develop`, seems that it is resolved. 

- [Config + Other code](https://github.com/fgpv-vpgf/fgpv-vpgf/compare/develop...ShrutiVellanki:exclusive-dynamic-2?expand=1)  (do a search for `exclusiveVisibility`)
- [index-sample #74](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/exclusive-dynamic-2/dev/samples/index-samples.html)
- [index-mobile](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/exclusive-dynamic-2/dev/samples/dynamic-sample.html)

Double checked that accurate bookmarks are being produced with [bookmark decoder](http://fgpv.cloudapp.net/demo/develop/prod/samples/bookmark-decode.html). Steps to reproduce: 

- Click on first layer: `Total Population by Disemmination`, set opacity to 40%
- Click on link to share, should show bookmark at the end of URL as: 
`B,YmFzZU5yQ2FuMA,NDM0MDE3LjU,MTI5OTM3Ni41,MTc1MDAwMDA,MzUxMjA1NTE0MDA0NTA0MDA4NTA0MDBjNTA0MDEwNTA0MDE0MWQ1MWM5NGU`
- Paste this in the bookmark decoder, should show that only the clicked layer (`index 1`) is visible with correct opacity set

![capture](https://user-images.githubusercontent.com/25359812/43415914-e14e634e-9404-11e8-8ed9-1fae464874cb.PNG)


***Note:*** `index 3` and `index 4` switch places in the bookmark decoder. 

Found a possibly related issue with reproducing layers from bookmarks which I have logged here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2893
