### ISSUE TITLE
Basic WMS GetFeatureInfo/Identify Support 

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#283]
- [x] Port from RAMP codebase.
- [x] Integrate with existing Identify functionality (#270)

Depends on Basic WMS Support: #271
Account for spec 1.3 issues seperately: #224 

Traceability Matrix ID#091

**Comment by alyec** [comment]
Will be working on UI integration in the viewer after all the geoApi work is done (i.e. LegendUrl and GetLegendGraphic)
