### ISSUE TITLE
CORS Mode

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2833]
We have a need to support CORS servers in RAMP (i.e. not rely on a proxy)

* Servers may exist inside firewall, making use of an external proxy no good.
* Servers may not support `JSONP`, so our web requests using that approach will not work.
* With ESRI API, domain names of CORS servers must be supplied before attempting to hit them without a proxy.
* Servers may be hit during app startup if they exist as layers in the config file

Here is a working sample of code that can live in the HTML, which is fine for layers added via the wizard (i.e. AFTER the app loads).

```js
setTimeout( function() {
	// set up cors for no-proxy
	var corsServers = [
		'geomet2-nightly.cmc.ec.gc.ca',
		'geo.weather.gc.ca',
		'geo.wxod-dev.cmc.ec.gc.ca'
	];
	RZ.GAPI.debug(true);
	var esriBundle = RZ.GAPI.esriBundle();
	var corsArr = esriBundle.esriConfig.defaults.io.corsEnabledServers;
	corsServers.forEach(function(server) {
	  corsArr.push(server);
	});
}, 4000);
```

Bad for many reasons; the timeout, hacking in via geoApi debug, server domains hardcoded in html page, etc.

I've attempted trickery using `RV.gapiPromise` instead of a timeout, but the promise handler still executes after the config based layers start loading.

Proposal for a CORS mode via the config:

Config part:

* Have a new config element that captures CORS mode for RAMP.  It might make sense to put it in the `services` section next to `proxyUrl`, as they are related.
* Element should have a boolean to indicate if mode is on. Default to false.
* Element should have an array of strings for the server domains.
* Alternate: empty array indicates CORS mode is off.  Might be a bad idea if we later decide to add API calls for calling page to add servers on the fly.

App load part:

* Process if we are in CORS mode sometime after geoApi has initialized, but before any layer loading starts.
* If CORS mode, feed the geoApi the servers (see snippet above).
* Will probably want a proper interface on geoApi to access the `corsEnabledServers` array (rather than going to debug mode and going via the bundle).
* Might want to have a console `warning` if config file provides both a proxy url and asks for cors mode.

Stretch goals:

* Make API call to allow page to pass in more servers (can be spawned into a new issue).
* Very fancy code to inspect URLs, determine if in the array, add them. Possible security issue? Possible bug hive (adding non-CORS servers)? Suggest not implementing without massive amounts of blessings from the team.

Sample layer config snippet that should work after this is implemented:

```text
{
  "id": "MEANTEMP",
  "name": "mean (unfriendly) temps",
  "layerType": "ogcWfs",
  "nameField": "station_id",
  "url": "http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/ahccd-trends/items?measurement_type=temp_mean"
}
```

**Comment by alyec** [comment]
Proposed implementation:

- add `cors-everything` option to the esriMap constructor
- instrument `addLayer` on the map and read off the layer URL adding it to the cors exception list

This is definitely a hack (and I doubt it will be elegant in any other implementation).  Since `proxyUrl` conflicts with CORS enabled WMSes there doesn't seem to be any value in the case where `proxyUrl` is not set and the layer is not on the CORS exception list.  If the layer is on the list and not CORS enabled the request will fail, but if it is not on the list the request won't even be attempted.
