### ISSUE TITLE
Dataset metadata available to the user

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#284]
- [x] Porting XSLT code from RAMP
- [x] Wire up UI to XSLT code

We can leverage the XSLTs from RAMP for this -- display key fields from Data Catalogue CSW consumption on a per dataset/layer basis.

Traceability Matrix ID#097

**Comment by mweech** [comment]
@ec-dev to resolve failing unit test encountered during PR.
