### ISSUE TITLE
Errors on Console when using URL RCS

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2841]
http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html?keys=JOSM

```
TypeError: Cannot read property 'map' of undefined
    at config.service.js:167

this.config.map.layers.push(...result);
```

I can't tell if this actually causes an issue in the app or not, but something needs to be tightened up.

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.5.0`  
- checked out the `v2.5.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2872 were included in the code

Still no longer an issue as checked with [current develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?keys=JOSM,CESI_Otherl) (add adding some RCS keys)

Closing issue.
