### ISSUE TITLE
Add option for a "blank" basemap in the Basemap selector

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#285]
From Usability Testing. The specific use case was that users were overlaying railways and roads WMS layers onto a Canada Transportation basemap, and we confused when disabling the WMS layers and still seeing roads and railways. 

This also helps users to find data that is otherwise difficult to see due to complex basemap imagery.

Traceability Matrix ID#104

**Comment by dan-bowerman** [comment]
When basemap is off, it's not making requests -- this is the easiest option to implement most likely.

**Comment by mweech** [comment]
Could possibly be implemented as a toggle of basemap visibility altogether instead of adding selections to the basemap selector.

**Comment by jolevesq** [comment]
We had this at first in GCViz but clients complaint and really wanted to have selection for that. I think it was more obvious to them that remove the basemap. But in fact it just change the visibility.

**Comment by ec-dev** [comment]
back end code completed (local not merged in), needs UI hookup 
2 story points remaining

**Comment by ec-dev** [comment]
In PR #472
