### ISSUE TITLE
WFS Layers Fail to Enter Legend in AutoLegend Mode

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2859]
Upon loading a WFS layer via the config file in autolegend mode, the layer will load and draw on the map.

It will not appear in the legend.
In `layer-registry.service`, `synchronizeLayerOrder()`, it will error as `map.legendBlocks` is null.

**Comment by AleksueiR** [comment]
### Obstacles
The legend generation is more tightly bound to layer record creation than I thought :/
We need proxy objects from the layer records to make legend entries, and they are available only after the layer record is made which essentially makes the whole thing a sync call. In cases of WFS layers, data loading will block the creation of the proxy object preventing the legend entry from being created as well.

I'm thinking of wrapping the proxy object in a promise, and making it look like it's returning the `rv-loading` state until it actually resolves (when the layer record is made). It might just work.

**Comment by AleksueiR** [comment]
Related #2726
