### ISSUE TITLE
Layer disappears after filter apply.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2864]
Tested build: http://fgpv.cloudapp.net/demo/v2.5.0-b1/dev/samples/index-samples.html
Sample #61.
Steps to reproduce : 
1.Load sample #61. Layer loaded with default values for the filter.
2.Click APPLY. Layer "Electric Transmission Line" disappeared.
3. Click on Clear filters. The layer appeared. 
4. Implement any filter and click APPLY.  
5. The layer is not shown.

**Comment by dane-thomas** [comment]
The layer appears to be breaking when filtering by `Country`. It seems to filter all the other fields correctly.

**Comment by YaroRoodzit** [comment]
I got the same result even with no Country filter. 
![image](https://user-images.githubusercontent.com/38046459/42780143-77f12ac0-8910-11e8-9346-13d823bebc55.png)

**Comment by dane-thomas** [comment]
Items with `OBJECTID` 1-4 are in Mexico so they should be visible if you pan south.

![image](https://user-images.githubusercontent.com/8885149/42814790-57eeb20a-8993-11e8-808b-142ac1e3e434.png)

But it also looks like the `OBJECTID`s have not filtered correctly in your screenshot.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Issue resolved.

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.5.0`  
- checked out the `v2.5.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2877 were included in the code

Still no longer an issue as checked with current develop and irrelevant as of `v.3.0` with `enhancedTable`

Closing issue.
