### ISSUE TITLE
Permit configuration change for default Dynamic layer display field

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#2866]
When registering an esriDynamic layer in RAMP's config, the nameField attribute is ignored and the primary field displayed when identifying a feature will default to whatever the service is configured for (see screencap). 
![image](https://user-images.githubusercontent.com/5294596/42840298-5fb98b86-89d4-11e8-9bc3-73d3e6bd30bf.png)

As a map builder who is not necessarily in control of the data services being displayed in RAMP, I would like  the ability to override the service's default display field to a field of my choosing from the service (e.g. switch "OBJECTID" for "Name".

**Comment by dan-bowerman** [comment]
![before](https://user-images.githubusercontent.com/5294596/42840397-bc48feea-89d4-11e8-8629-5271833bc928.png)


vs. 

![image](https://user-images.githubusercontent.com/5294596/42840405-c2a73482-89d4-11e8-95ce-50d1b452ac71.png)

**Comment by AleksueiR** [comment]
I think it would also be useful to have a separate field name for the default tooltip.

Here, both the tooltip and the identify details title display the amount of precipitation. I think it would be best to display that station's name/id as the title in the details panel.
![](https://i.imgur.com/BKQzpwT.png)

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Sample #73. As expected.
