### ISSUE TITLE
RAMP does not load in iOS Safari / official Facebook iOS app

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#2870]
When attempting to load RAMP from a shared link in Facebook, or directly via Safari on iOS, RAMP does not load, it perpetually displays the loading spinner animation instead.

Test case: Send a private message with a link to an external RAMP based application (e.g. CESI http://indicators-map.canada.ca/), and attempt to load it directly from Facebook or pasting the URL into iOS Safari browser.

**Comment by mweech** [comment]
Works on most recent 2 version of iOS using Safari.
