### ISSUE TITLE
Custom Symbology for Feature Layers

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2878]
## Overview

Applying custom symbology to a vector layer has two components: symbols and renderers. Symbols determine how an individual feature is drawn. Renderers determine what symbol is used for a given feature.

As it stands, RAMP usually gets the symbology from the service the layer resides on.  For file based layers and WFS layers, we use the most basic renderer possible and allow a colour to be chosen.

### Symbols

Line features are fairly limited: colour, thickness, and dash-dot patterns if we get fancy.
Polygons are similar (the border is a line), but also have a fill colour (ESRI also supports some basic hatching patterns).
Points use markers (i.e. things that stay the same size regardless of map scale). These can be images, or default ESRI markers (e.g. circles, squares, svg paths).

### Renderers

Ramp currently supports the three common renderers in the JS.API.
Simple renderer applies the same symbol to every feature.
Class Breaks renderer applies a symbol based on where given attributes numeric value falls on a number range.
Unique Value renderer applies a symbol based on the value(s) of up to three attributes.

## Avenues of Definition

There are a number of potential ways a symbology could be defined on an applicable layer.

### Layer Config Object

Defining symbology on the layer config would allow the layer to be initialized with the desired settings.  It would not provide the ability to modify symbology on the fly.

Would require a non-trivial object structure to be added to the config defintion.  Some ideas

* Specifically define all structures to support all combinations.  Should be done in an ESRI agnostic way (though it could mirror the structure).  Certain fancier options could be omitted.
  * Pro: proper interface.
  * Con: significant effort for what is essentially a wrapper.
* Define an "object" property with no constraints. Onus is on config author to provide proper structure. Structure would be ESRI object definition, as we are not translating the input.
  * Pro: easy as far as config plumbing goes.
  * Con: ESRI dependence in the config. Difficult to provide guidance to RAMP implementers on proper input beyond asking them to look at ESRI samples.
* Pick a small subset of symbology options to support, make simpler, abstracted config inputs for them.
  * Pro: balance between the Pros & Cons of first option.
  * Con: will encounter complexity & mess later on when people inevitably ask for more options to be supported.

There is also the Config Authoring Tool, being built by NrCan, to consider (they may want to skip this part if we go with the complex options).  
  
### RAMP API  

A function on the RAMP `ConfigLayer` API class could allow symbology to be updated via the controlling page. 

This allows more flexibility in that the symbology can be changed at any time.  It also adds a burden in that page hosted code needs to be present to do overrides (unless the Layer Config option above is also implemented).

We have a similar decision here on how complex or simple to make the interface classes.  See Existing Work section below.

There may also be some behind the scenes updating required if changing symbology post-load. See Layer Source Types section below.

### Wizard

Defining symbology via the Wizard adds more complexity, in that we need a UI for all the options.  Wizard support would require the Layer Config Object support above to be created.  We can consider minimizing which options are available via the Wizard.

## Layer Source Types

Generally the discussion has been around file based and WFS based layers, as those sources do not define their own symbology.  However it was also mentioned that the ability to override Feature Layer symbology would also be a useful ability.  As far as setting renderers go, this should work; but there may be some timing considerations to attend to, as the layer `load` event may re-write the layer with the server symbology definition.  Renderers are also used to derive icon lookups during the layer initialization phase.  These might need to be delayed to re-executed.

## Suggested Limitations

If going for config-based structure (i.e. not the open-ended ESRI object choice), would suggest the following limitations on what we allow. Counter-arguments welcome.

### Symbols

For Points, allow picture symbol only. If people want the custom ESRI symbols (e.g. EsriSquare ), they can make an image of it.

For Lines, allow solid line only. No fancy dashes. This also applies to polygon borders.

For Polygons, allow solid fill only. No hatches.

### Renderers

Disallow gaps in Class Breaks renderer.

Consider using a tuple-array format to define Unique Value sets instead of verbose object structures.
  
## Existing Work

https://github.com/fgpv-vpgf/geoApi/pull/309 and https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2824 , both still pending review, implement a symbology interface for the RAMP API `SimpleLayer` (equivalent of ESRI Graphics Layer).  It's possible this could be abstracted out of SimpleLayer so it's also used on Feature Layer implementations of RAMP API `ConfigLayer`.

There is no work done for Renderer support.

**Comment by mweech** [comment]
I think allowing a pass through of an Esri object is the way to go.  It avoids reinventing the wheel and having to maintain that abstraction.  There is also existing samples to reference, although we will have to document the subset of allowable features (none of that fancy label stuff).

I also like the idea of letting the base API handle this and letting maintenance of app side customizations sit with the app owner.  If we translate, we assume that responsibility as a broker between our config and the underlying API structures.

**Comment by milesap** [comment]
Abstracting the `SimpleLayer` implementation is my pick:
- It shares logic between `SimpleLayer` and `ConfigLayer` types
- `SimpleLayer` api implementation can map to the abstracted logic
- `ConfigLayer` would simply take the config object as-is. 

> "Define an "object" property with no constraints. 

In theory since the object has no constraints, it could contain non esri specific render/symbology configs. The map author would need to be aware of the underlying mapping SDK and write the objects appropriately.

The `SimpleLayer` mapping to the esri implementation would bind ramp to esri. While not ideal, we're pretty well bound to esri unless there is another great ~~refactor~~ enhancement.

**Comment by spencerwahl** [comment]
My vote is also for using Esri objects directly.
- We do very little coding
- No abstraction to maintain
- Full availability of what Esri allows
- No confusion for anyone that knows Esri definitions

This makes configs tied to Esri, but as was discussed yesterday the viewer is almost definitely not going to move away from Esri (and it would be a major major change anyways).

**Comment by JahidAhmed** [comment]
Both `SimpleLayer` and `Esri objects` seem justifiable, but I'm leaning towards the latter as well.

`SimpleLayer` would require abstracting the existing symbology code (linked above by James) to `BaseLayer` and ensuring it works on the fly, not just at initial creation (which is what's happening now for `SimpleLayer` geometry). But it would then give us the ability to move towards edits for SimpleLayer geometry which was briefly discussed a while back (probably low priority though).

Layer config esri type object on the other hand would also allow usage in two main components; initial definition and wizard loading, along with all the points mentioned above by Mike and Spencer.

**Comment by james-rae** [comment]
A bit of clarification in terminology.  Comments on this thread are using `API` interchangeably between two different approaches.  For adding stuff to the config schema (either open-ended-object or very strict object), we can specify custom symboloy via the API by doing something like.

```
RZ.addLayer({ config snippet with renderer property set });
```

For the pure API approach, we do things via API with something like 

```
var myLayer = RZ.getLayer(layerId);
myLayer.setRenderer(new RZ.Renderer(...));
```

Config approach allows us to set something custom at Layer Add time.  Pure API approach allows us to update things on the fly, but is not tied to the config schema.  Doing both would give us all options.

For time being, pure API is nice but doesn't give us anything we need at the moment. Jahid also made a good point in that it's only been used / tested for symbols (not renderers), and at graphic creation time, not updating layers post-creation.

The config approach lets us set things via config file, API `addLayer`, wizard (if UI is built), and RCS (if we allow direct registering of snippets).  While having an open-ended-object is technically bad, it also means we can do what we want as we never break the schema.

For hitting CCCS deadline, open-ended config approach is probably the only approach i'd be confident in it being stable.

Post CCCS we can look at investing in full API as new priorities present themselves.

**Comment by AleksueiR** [comment]
I agree with James: if we need it fast (pre-CCCS), go with an open-ended ESRI object; later on in the year, a properly implemented API.

If we have time to develop it, a proper symbology API will add consistency to the rest of the code and could be incorporated into the loading wizard. I don't see much value in picking a subset of symbology options to support as it would take much thinking to decide which ones are important and it's likely we will hit a use case that needs options do don't support in the future anyway.

In the case of just using an ESRI object, there is still a way to at least partially incorporate it into the wizard. We can add a text field as the last step and let users paste a layer symbology snippet as raw JSON.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Sample # 74. As expected.
