### ISSUE TITLE
Legend &  Map sometimes fails to reproduce Bookmark State 

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#2893]
***Steps to reproduce:*** 
- Make only first `layer`/`layerEntry` visible
- Get **"Link to Share"**
- Reload page with link
- Layer will reset to default visibility settings and fail to read from bookmark

***Tested on:***  
- [complex dynamic layer](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/exclusive-dynamic-2/dev/samples/dynamic-sample.html) : `Total Population by Dissemination` visible only
- [sample 7](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html) : `Biomass` visible only
- [sample 1](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html): `Natural Gas Pipeline` visible only

***Examples of Layers that work as expected:*** 
- [index-mobile](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html): `Power Plants, 2` visible
- [index-theme-gcweb](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-theme-gcweb.html): `Electric Transmission Line` visible only

***Notes:*** 
- Correct bookmarks seem to be generated in all cases as tested in [bookmark decoder](http://fgpv.cloudapp.net/demo/develop/prod/samples/bookmark-decode.html) 
- Correct config seems to be generated as well when `applyBookmark` is called in `config.class.js`
- Seems to fail when legend is being generated (maybe near `legend.service.js`)

**Comment by james-rae** [comment]
Solved by fix to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3114
