### ISSUE TITLE
Enhance `visibilitySet` legend entries

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2896]
### Problem
A maps has four layers with only one visible at a time and the layer visibility is controlled through the API. Only one `unbound` legend entry is displayed reflecting the currently selected layer. Using an `unboundLayer` legend entry means not being able to control opacity/visibility through the UI.

### Enhancement options:
- ability to add control to unbound legend, it executes a callback of our choice (which would then change viz/opac)
- keep bound legend, implement appropriate code to change which layer the bound legend is bound to
- add option to `collapse` an exclusive visibility set so only the most recently selected (all entries could be turned off in a set) option is visible

### Solution being implemented
Add the `collapse` option to the visibility stack and replaced the `unboundLayer` with it.

### Demo
![enhanced_visibility_set](https://user-images.githubusercontent.com/2285779/43461708-216366f8-94a2-11e8-9ce8-fba73393f3cf.gif)

### Info
Read here for more details: :point_up: [July 23, 2018 3:20 PM](https://gitter.im/RAMP-PCAR/CCP?at=5b562a8cee530e4aac91a52f)
Reported by @james-rae.

**Comment by YaroRoodzit** [comment]
Tested build v2.5.0-b2. Sample #72. As expected.
