### ISSUE TITLE
Improve UX when layer not available

### ISSUE THREAD

**Issue by jvanulde** [fgpv-vpgf/fgpv-vpgf#2898]
For example: https://open.canada.ca/data/en/fgpv_vpgf/d880ba18-8790-41a2-bf73-e9247380759b

Perhaps bring up a msg or something indicating that the resource(s) are not available. Right now users just get an empty map with no indication of a problem.

**Comment by AleksueiR** [comment]
Several similar things are already implemented and will be available in v2.5 when if comes out.
- toast notifications are displayed for resources taking very long to respond (see this issue for more details https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2794)
- toast notification are also displayed for resources which fail to load correctly
![](https://i.imgur.com/dwP0szX.gif)

We are also planning to add an option to reload a failed layer directly from the notification (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2801).

___

> For example: https://open.canada.ca/data/en/fgpv_vpgf/d880ba18-8790-41a2-bf73-e9247380759b

I don't see any errors on this page. A call to RCS does not fail and the returned config is valid. The config does not have any layer definitions though, so nothing loads, but there is not error to catch.

**Comment by jvanulde** [comment]
Thanks @AleksueiR. That was probably a bad example. The example you provided is more common. Some users don't intuitively know that they need to open the legend to see the status of the map. So the toast notifications will be helpful. If a configuration is loaded and it's empty a message along the lines of no layers available/configured - layers can be added by clicking the + button in the legend. If no key is passed is there configuration? If not, a message should be shown if an empty configuration is passed.
