### ISSUE TITLE
Move data filtering to geoApi and enhance

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2906]
Move the logic [filteredState](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d131444bf3af710367c7ab5659911e8080dcefb8/src/app/ui/table/table.service.js#L651) and [queryMapserver](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d131444bf3af710367c7ab5659911e8080dcefb8/src/app/ui/table/table.service.js#L671) into geoApi and expose it on the map layer api.

Make a `LayerQuery` interface to resemble something like:

```ts
interface LayerQuery {
  query: string | (string | LayerQuery);
  operator?: string; // operator for child layerQuery and strings, can be AND, OR etc. Defaults to AND
  inCurrentExtent?: boolean; // filters by extent
}
```

Example use case in map api

```ts
myLayer.attributesChanged.subscribe(x => {
  // update the fancy table
});

myLayer.filter({
  query: [
     'OID = 1 OR OID = 2 OR OID = 3', 
     { operator: 'OR', query: ['CITY = Toronto', 'CITY = Irondale'] }
  ]
});

// Query is 'OID = 1 OR OID = 2 OR OID = 3 AND (CITY = Toronto OR CITY = Irondale)'
```

**Comment by james-rae** [comment]
`queryMapserver` could move into the layerRecord class hierarchy. 
Not sure about `filteredState`, as it's processing grid data.

**Comment by mweech** [comment]
Outdated issue under the updated v3.
