### ISSUE TITLE
Move details panel to panel api and provide api accessor 

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2908]
The details panel should be changed so that it uses the new panel api. Add an api method to the layer class such as `viewDetails(oid: string | string[])` which opens the panel with the provided feature(s) id.

Old code can be found here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/table/table-default.directive.js#L899

**Comment by mweech** [comment]
Completed under a seperate issue during hte panels migration.
