### ISSUE TITLE
Geometry portion of identify info is lost for WFS

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2921]
Possibly affects other feature based layers.

Responses such as 
```text
"features": [ { 
  "geometry": { 
    "type": "Point", 
    "coordinates": [ -123.63, 48.65 ] 
  }, 
  "type": "Feature", 
  "properties": { 
    "province": "BC", 
    "elevation": "138", 
    "joined": "0", 
    "station_id": "1017230", 
    "station_name": "SHAWNIGAN LAKE", 
    "identifier": "1017230"
  }, 
  "ID": "1017230" 
}]
```

have the geometry portion removed in between receiving the data and the bundle being passed to the details panel in RAMP. This causes us to not be able to display the lat/long of the point in details templates, etc.

**Comment by james-rae** [comment]
This actually happens to all feature based layers, and always has. The attributes contain only attributes.  Some exceptions we have seen include a) data owners copying co-ordinate values into the attributes (essentially duplicating the data along with the geometry), or specifically setting their layer to include the shape field in the attribute set (rarer case).

Three proposals to move forward on this:

## More Inputs to Custom Parser & Template

Currently the custom parser & template accept the attributes of the results. This proposes that framework be expanded to accept more inputs.

We recently had a feature request to generate some restful urls based on application state inside the details pane, so this is not the first time we've had a situation where the parser would benefit from having access to more information.

PRO: Data is available to be used at whim inside parser & template. All other RAMP components are not affected by the change.
CON: Extra info is only available to custom templating. If someone wants co-ords to appear in default ESRI key-value result pane, it won't happen. Also will not appear in the data grid.
UNKNOWN: Amount of effort to add more parameters.
UNKNOWN: May need to update our Dynamic Layer Identify logic to include geometry. Would only want to do this for point layers.
UNKNOWN: Figuring out what things should be passed in. Feature geometry?  `RZ` reference? Moar???

## Config Option to Port Co-ords to Attributes

Have an optional config flag to force geoApi loader to copy co-oridinates to the attribute set.  This would only make sense for point layers.

PRO: Should be seamless once working. Table, standard identify, etc should pick up values as normal attributes.
CON: Extra R&D + coding to make this work on dynamic feature sources. Bulk geometry traditionally never comes to the client in this mode.
CON: Possible extra coding for Dynamic Identify results, as they come directly from a dedicated server identify task (so need to shunt in co-ords in that pipeline too).
CON: Need to worry about field name collisions. If we use `x` and `y` and layer already has those, need adaptive naming to avoid overwriting data.
CON: Would need to add a checkbox to the wizard to allow this feature to be applied on user added layers.
CON: Small risk of having attribute set out of synch with original service metadata. For the most part we use a modified copy of the metadata.

## Lazy

Not in attributes?  No co-ords for you.

**Comment by james-rae** [comment]
After discussion on chat channels, we are doing the following for now.

* Add a config option for WFS layers only. The option defaults to off.  If turned on, will copy the geometry to the attributes.
* Only applies to Point layers.
* Will use a system/internal naming structure to avoid collisions and not fool users into thinking they are part of original attributes.
* Will not be available as an attribute for quick-load hover tips (we can add this later if we need to).
* Will not be an option for WFS layers added via the wizard

**Comment by james-rae** [comment]
System attribute names are `rvInternalCoordX` and `rvInternalCoordY`

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2 . Sample 76. As expected.
