### ISSUE TITLE
Multiple details parser calls

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2929]
In the details (identify) response watchers are sometimes added on repeat clicks. This causes multiple identical parser calls and all the console cluttering and unneeded processing that comes with that.

Either delete the $watch after its used or use a different callback process.

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.5.0`  
- checked out the `v2.5.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2957 were included in the code

Also in current [develop](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/details/details-record-html.directive.js#L73)

Closing issue.
