### ISSUE TITLE
bug(build): source map generation is broken

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#293]
Sourcemaps map to wrong lines.

Turning sourcemaps off for now.

**Comment by AleksueiR** [comment]
On top of source maps being broken, now it's not possible to put a breakpoint anywhere in `core.js`. It seems all the lines are mapped to some dragula file. There are also some random npm modules showing up in the source: 
![](https://i.imgur.com/oTtsIYk.png)

All this makes debugging quite difficult.

**Comment by jolevesq** [comment]
@AleksueiR Found dragula can break sourcemapping https://github.com/bevacqua/angular-dragula/issues/42. Maybe it can help.

**Comment by alyec** [comment]
"Temporary Workaround" added: https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/723#-KJf_maDARSzzgCImNb0

**Comment by alyec** [comment]
sourcemaps has a compatibility list of plugins and we have a few that are not on the list: https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support

Finding alternatives / rewriting those that are incompatible is quite a bit of work.  Given the current state with a non-minified core.js breakpoints work in the debug tools and the code is readable.  Adding sourcemaps would get us direct links to the files, but once a dev has some general knowledge about the structure it shouldn't be too hard to find the appropriate line from our source.

**Comment by AleksueiR** [comment]
Do we want to add source maps to the production build? It will still be only `core.js` file, but it enables some sort of debugging on prod. This will increase time to create a production build, but not by much.

**Comment by AleksueiR** [comment]
Do we close this issue when #882 gets merged or are we going to try getting fully-functional source maps (with links to files) working?

**Comment by mweech** [comment]
we leave it in the backlog as an inactive issue for now.  aly brought the issue to me, and indicated that to get sourcemaps fully working we would have to replace alot of incompatible dependencies.  for the time being this will have to remain an outstanding known issue.

**Comment by AleksueiR** [comment]
Fixed by webpack! Kudos to @milesap .

**Comment by AleksueiR** [comment]
Ok, source maps works on dev builds, but not on prod builds.

@milesap can you look into enabling source maps on prod builds as well? They are more useful there than on dev.

**Comment by milesap** [comment]
Waiting on resolution of #1979
