### ISSUE TITLE
Collapsed symbology stack is rendered with a black halo

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2942]
### Problem
Symbology stacks with lots of items are rendered with a kind of a black halo when collapsed.

Demo url: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?keys=JOSM,CESI_Other,NPRI_CO

![](https://i.imgur.com/629PUXE.png)

### Expected result
![](https://i.imgur.com/73yH7aI.png)

**Comment by YaroRoodzit** [comment]
Issue resolved. Tested with build  v2.5.0-b4.
