### ISSUE TITLE
Using non Latin1 characters in id (and name?) key in config file breaks the bookmark function

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#2944]
In fgpv 2.4.0, when using a config file that has a id (and  name?) composed of text that includes non Latin1 characters e.g. n-dash in "Hydro energy resource potential – reservoir hydro", selecting a base map with a different projection or clicking on the Share widget does nothing.

The following console error appears:

`DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`

Smells like sanitization is having trouble with non Latin1 characters (?)

**Comment by james-rae** [comment]
`btoa()` does conversion from normal strings to base64 strings...helps us reduce size.  I'm interested why the layer name is getting encoded...bookmarks should generally be storing layer ids. 

Worth taking a peek into.

**Comment by bchagnon** [comment]
I have limited knowledge of bookmarks 🔖. You are most correct in saying 

> bookmarks should generally be storing layer ids

I wrongly assumed that both name and id were the culprits in the following key values that generate the error.

```
"name": "Hydro energy resource potential – reservoir hydro",
"id": "Hydro energy resource potential – reservoir hydro***99015304"
...
"layerId": "Hydro energy resource potential – reservoir hydro***99015304"
```

**Comment by bchagnon** [comment]
I 👀 now

"[calling btoa() on a Unicode string will cause an InvalidCharacterError exception](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa#Unicode_strings)"

"[use typed arrays to do the conversion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Base64_encoding_and_decoding#Solution_.232_.E2.80.93_rewriting_atob()_and_btoa()_using_TypedArrays_and_UTF-8)"

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Test page samples/index-fgp-en.html?keys=unicode–Layer. As expected.
