### ISSUE TITLE
Export image error

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2950]
Tested: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=67

Trying to export "Canada Elevation" throws an error `TypeError: get_URL(...).createObjectURL is not a function`

**Comment by spencerwahl** [comment]
should be solved in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2949

`window.URL` was being overwritten in index samples

**Comment by AleksueiR** [comment]
Is this still happening?

**Comment by james-rae** [comment]
WOMM
