### ISSUE TITLE
Single Entry Collapsed Dynamic gets table config from wrong location

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2954]
Doing something like this:

```text
{
  "id": "fancyLayer",
  "layerType": "esriDynamic",
  "url": "http://fancymaps.ca/arcgis/rest/services/VeryFancy/MapServer",         
  "singleEntryCollapse": true,
  "layerEntries": [{
	"index": 0, 
	"table": {
	  "columns": [
		{ "data": "OBJECTID", "visible": false },
		{ "data": "Fancy_Field" }
	  ]
	}				
  }]
}
```

will result in the `OBJECTID` field remaining visible in the datagrid

Issue appears to be in `table-default.directive.js`, function `initColumns`, line:
`const config = requester.legendEntry.proxyWrapper.layerConfig.table;`

Hypothesis is that the `singleEntryCollapse` option means the child layer is existing in what is normally the dynamic layer root entry of the legend. So when table is opened, it is looking for the config table definition at the main layer config level instead of the `layerEntries` level.  It finds no `table` entry there, and executes defaulting code to show all fields defined in the layer.

If correct, needs a fix to pipe the correct config element to the table.

**Comment by ShrutiVellanki** [comment]
@james-rae and I both tried to replicate this issue and neither of us could. 

only fails to work when the Dynamic Layer in question has multiple entries like this: 
![groupformat](https://user-images.githubusercontent.com/25359812/45240125-841b3380-b2b5-11e8-9588-ade7c7a8df77.PNG)

but is defined like this which is a nonsense use case.

```js
{
                "id": "ecogeosec",
                "name": "Eco Geo Single Entry Collapse True Horse Staple Battery",
                "layerType": "esriDynamic",
                "singleEntryCollapse": true,
                "layerEntries": [
                    {
                        "index": 0,
                        "table": {
                            "columns": [
                                {
                                    "data": "Nom",
                                    "visible": false
                                }
                            ]
                        }
                    }
                ],
                "url": "http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer",
                "metadataUrl": "http://intranet.ecdmp-stage.cmc.ec.gc.ca/geonetwork/srv/eng/csw?service=CSW&version=2.0.2&request=GetRecordById&outputSchema=csw:IsoRecord&id=1c0eb1b2-93ae-49ae-a3ce-e495d8fd767b&_=1417717957845"
            },
```

works fine when Dynamic layer in question has a single entry like this: 
![singleentryformat](https://user-images.githubusercontent.com/25359812/45240213-d0667380-b2b5-11e8-9633-f6a251ac4a76.PNG)

**Comment by james-rae** [comment]
Excellent findings.   It may be possible i was seeing this on a v2.4.0 build and just wasn't paying attention. (i.e. it has been fixed since)
