### ISSUE TITLE
Overview map when basemap have more then 1 layer

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2961]
When we have a basemap with more then 1 layer, the overview map only shows the first one. It needs to show all available layers.

I don't think we can use more then 1 layer inside the Esri didjit. We will have to see if we want to create our own overview map intention or when this happen user will need to use overviewUrl

**Comment by dan-bowerman** [comment]
Is this still relevant? @jolevesq 
It's a few years old, and the team thinks this shouldn't be a problem any longer.
