### ISSUE TITLE
Pan & zoom broken on chrome 68 for touch and zoom events

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2962]
`document.createTouch` has been dropped on chrome 68 which is being used on ESRI jsapi v3.x.
See: https://developers.google.com/web/updates/2018/06/chrome-68-deps-rems
init.js: https://gist.github.com/jigokuotaku/3796e85713eabfde8060

Polyfill `createTouch` with better `Touch` constructor.
https://developer.mozilla.org/en-US/docs/Web/API/Touch/Touch

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.5.0`  
- checked out the `v2.5.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2963 were included in the code

Also in current [develop](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/startup.ts#L11)

Closing issue.
