### ISSUE TITLE
"No content" image is briefly shown when opening the about dialog

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2964]
### Problem
When the About dialog is open, the "No content" (sad Canada) image is shown briefly and then replaced by the about text.

![sad_about](https://user-images.githubusercontent.com/2285779/44852946-93a1d900-ac32-11e8-8ff1-5eb7b443b7eb.gif)

### Expected
The "No content" image should only be shown where there is no content. It should not be displayed while the about text is loading.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Issue resolved.
