### ISSUE TITLE
Support annotation layer

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2965]
Annotation layer is loaded automatically when it is inside an ESRI dynamic layer (https://community.esri.com/thread/194478-add-annotation-layers-to-js-application). However, the viewer legend is not able to deal with the symbology

```
symbology.js:1075 Uncaught (in promise) TypeError: Cannot read property 'legend' of undefined
    at mapServerLegendToRenderer (symbology.js:1075)
    at eval (symbology.js:1150)
```

We need to find a way to load those type of layer because if one annotation layer is inside the dynamic service, we can't load the whole service. We also need it because client wants to be able to display them.

**Comment by bchagnon** [comment]
I have observed that setting `"stateOnly": true` on the specific annotation layer of the service makes the other layers in the service load properly.

Caveat: the annotation layer still does not display on the map as per schema notes "[stateOnly] A flag indicating this entry is only for state tracking (i.e. it should not be displayed on the UI and all of the controls will be ignored, **but the layer itself will be displayed on the map with the given state settings**)."

**Comment by james-rae** [comment]
https://github.com/fgpv-vpgf/geoApi/pull/324

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. As expected.  Tested with http://gis.pendercountync.gov/arcgis/rest/services/Base_Map/MapServer. Layer loaded successfully. The annotation layers appeared in legend with no symbols.
