### ISSUE TITLE
OverviewUrl in tileschema is broken

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2967]
Even if we define a overviewUrl inside tileSchema it is never applied because ```this.basemapGallery.on('selection-change'``` always call resetOverview without the url from custom overview if define

**Comment by james-rae** [comment]
https://github.com/fgpv-vpgf/geoApi/pull/323

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. Used sample #71. As expected.
