### ISSUE TITLE
Opening "Settings/Metadata/Legend" snaps the page to the top

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2969]
### Problem
When opening "Settings" or "Metadata" panels, or expanding the legend stack using a mouse, the viewport snaps to the top of the page. This happens because the clicked menu element is removed from the DOM and focus is lost. Everything works as expected when using a keyboard to interact with the viewer.

### Solution
The [scroll disabling logic](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/focus-manager.js#L411) added in #2665 is misfiring when the currently focus is lost and moved to the top of the page. This only needs to run only __once__ every time a viewer is activated.

Related to #2665

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. As expected.
