### ISSUE TITLE
A "layer failed" toast is shown when individual tiles of a Tile layer fail to load

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2971]
### Problem
Some tile layers don't have all the tiles, like this one: https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_TXT_3978/MapServer

When the map is trying to load missing tiles, ESRI throws an `rv-error` and a `rv-loaded` events in a quick succession, which triggers a "layer failed" toast making it look like a layer has momentarily failed and restored itself. Everyone finds this quite annoying. 

### Solution
When an error event comes in, delay the handler action by a jiffy. If a `rv-loaded` event is fired during that time, do not act on the previous `rv-error` event. This will filter out volleys of error events fired by the above tile layer which is perfectly functional and spare users from the assault of the failed toasts. If the layer does fail properly, the "layer failed" will be displayed after the timeout expires.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. As expected.
