### ISSUE TITLE
Icon symbology overlaps descriptions

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2975]
On initial legend load the description item height is not being accounted for. This causes layer symbology to overlap the text and make it unreadable.

Fix offsetting symbology past the description.

![](https://i.imgur.com/P5TmcAZ.png)

**Comment by AleksueiR** [comment]
Related?
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2857
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2935

**Comment by AleksueiR** [comment]
:racehorse: condition it is

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.5.0`  
- checked out the `v2.5.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3000 were included in the code

Still no longer an issue as checked with [current develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?keys=JOSM,CESI_Other) 

Closing issue.
