### ISSUE TITLE
Filtering map using layer symbology does not affect identify results

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2981]
### Actual behaviour
Layer symbology can be used to filter features displayed on the map; however, when trying to identify some of the remaining feature, the query returns all the hits at the click position, even features supposedly filtered out by the symbology filters.

![bad_filter](https://user-images.githubusercontent.com/2285779/45089202-6d1fea00-b0d9-11e8-8286-6fb363e5baa7.gif)

### Expected behaviour
Identify results include only features visible on the map.

**Comment by AleksueiR** [comment]
Related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2456

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. As expected.
