### ISSUE TITLE
`symbologyExpanded` does not work for Dynamic layer entries

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2987]
### Problem
`symbologyExpanded` is meant to expand the symbology stack of the legend block. This works fine for all non-group layers (non-Dynamic layers). With a dynamic layer, setting `symbologyExpanded` to `true` as below, has no effect since this configuration applies to the root legend block of the Dynamic layer which is rendered as a legend group. 

```json
          {
            "layerId": "0",
            "symbologyExpanded": true,
            "entryIndex": 0
          }
```

The setting is not passed down to its children and symbology stacks remain collapsed.

### Suggestion
We need options to expand symbology stacks for Dynamic layer entries individually. Just setting one property on the Dynamic root legend block implies you want to expand symbologies for all layer entries. There is no way right now to specify that you want just one of the layer entries to have the expanded symbology.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. The sample used #8. As expected.
