### ISSUE TITLE
Accented letters in datatable search show/don't show depending on accent

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#2988]
For example the accented "México" shows up fine:
![mexicosearch2](https://user-images.githubusercontent.com/25359812/45161527-150ce480-b1ba-11e8-8d1a-4dfb4c984554.PNG)

Whereas the accented "Compañía" doesn't: 

![compania](https://user-images.githubusercontent.com/25359812/45161591-3ff73880-b1ba-11e8-82df-d1c06f10d998.PNG)
![compania2](https://user-images.githubusercontent.com/25359812/45161602-44bbec80-b1ba-11e8-800b-714993266780.PNG)

Only tested on global search for now, but will also need to work for `lazyFilter` : https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2985 when merged.

We need to decide whether to universally include or exclude all accented letters from searches with normal letters.

**Comment by AleksueiR** [comment]
Might be related to these:
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2019
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2135

**Comment by JahidAhmed** [comment]
I think maybe none of the accents are showing up as expected. The 'Mexico' one looks like it is possibly because of the 'Mexico' (without the accent) in the country column

**Comment by james-rae** [comment]
Jahid has found a solution for the `datatables` library.  We discussed making a config option to allow an author to have the grid search in an accent friendly manner (i.e. matching accented letters to plain letters), or enforcing a strict match.

However, with v3 migrating to a "table plugin" architecture, it raises a few concerns, as it can mean any table library needs to implement this ability, or we have to document that the function "works if the table supports it".

Could also debate that making a config option is overkill, and that always attempting an accent friendly search is fine for our needs.

We will take a look and see what type of support the `ag-grid` library provides.

**Comment by milesap** [comment]
We could consider character/accent folding search support on the api. Something like `queryFeatures(query: string, options: {accentFolding: true}): FeatureItem[]`.

Found this: https://github.com/tylerjpeterson/accent-fold
We'd likely just want to pull in https://github.com/tylerjpeterson/accent-fold/blob/master/accent-map.json instead of requiring another dependency since this is a simple task.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2.
Issue resolved.
