### ISSUE TITLE
Gracefully Handle No-Feature WFS

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2995]
Our current workflow for WFS layers:

- Load geoJson data from WFS service
- Convert to ESRI Json / Disconnected ESRI Feature Layer
- Load layer in map

The conversion step needs to inspect the first feature in the geoJson features array to extract the attribute field names and the geometry type. 

If we encounter a service with no features, this part of the step fails, and the UI shows the layer as "loading".

Need a more graceful way to catch this scenario and have the UI go to the layer error state.
This is a bit trickey, as the error state happens before any ESRI Layer / Layer Record is created (note: it's possible this is no longer the case after the last refactor of layer-blueprint.  Person making this fix needs to inspect the code).

**Comment by AleksueiR** [comment]
WFS data loading is happening on the client. Maybe I can inspect the payload for the absence of records and kill the process at this step, even before passing it to the geoapi?

**Comment by james-rae** [comment]
Can be an option.  I think as long as we have a layer blueprint / layer record (or fake proxy to one) that can provide an error event / error state, and handle a reload request, then we should have a UI experience similar to a normal error failing.

I'm not sure how well the blueprint / record / proxy structures play if we abort the geoApi layer init.

**Comment by AleksueiR** [comment]
After looking some more, I think the best place to kill the loading process is the [`validateFile`](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/layer.js#L507) function in geoApi, and it's logical as well - a layer without records is not valid. I think it should be as simple as `if (!geoJson.features.length === 0) { return Promise.reject(); }`.

If this is dandy, I'll start making modification, so the UI part can handle the rejection correctly.
