### ISSUE TITLE
Clean up Index-Samples test case ids

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2996]
The test numbers have become un-aligned with the file names.

e.g. `60. Tile layer` uses file `config-sample-63.json`

There is also two variants of file 73.
Ideally the visible numbers should stay the same, as that is what the QA team is used to seeing.

**Comment by AleksueiR** [comment]
How hard can renaming a couple of files be? Well, git thought I was changing files' content, not just their names -> very messy PR changes.
