### ISSUE TITLE
Invalid image url in legend results in repeated image requests

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3003]
If an image url in a legend won't resolve, the code repeatedly attempts to load the image.

Appears to be caused by this block of code

```text
self.canEnlarge = () => {
    const img = new Image();
    img.onload = function() {
        width = Math.min(this.width + 50, shellNode.width() * 0.8);
        height = Math.min(this.height, shellNode.height() * 0.8);
    }
    img.src = imageUrl;
    return width > element.parents(".rv-toc").width();
};
```

Something like it's continually attempting to ask how big the image is, but can never get an image.  Also, a possible out-of-order thing happening here, with `width` being used prior to the promise resolving(?)

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. Used sample #67. As expected.
