### ISSUE TITLE
Make Google Tag Manager opt-in

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3018]
Add an `rz-gtm` attribute to the ramp html tag to opt-in.

**Comment by AleksueiR** [comment]
Why `rz-`? All other attributes use `rv-`. Shouldn't this one be `rv-` as well for consistency?

**Comment by milesap** [comment]
The `rz` started with `rz-extensions` I believe before the `v3` branch was made, I'll likely revert everything to `rv` once we get closer. 

Potatoe Potahta
