### ISSUE TITLE
Ensure Accurate Identify Results For Toggle Symbology Stacks (Edge Case)

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3019]
Related https://github.com/fgpv-vpgf/geoApi/pull/327

As @james-rae pointed out the solution linked has a problem:

> This has one limitation, in that if a layer has different categories with identical symbols, the svg comparisons won't be able to tell which category they came from. I don't see a quick solution to that (would involve enhancing symbology.searchRenderer() to also return the definitionClause on the result and use that on identify results).

We need a fix that ensures identify results are limited to the correct results even when multiple categories have the same symbol.

Note: this issue happens only when the layers in question are Dynamic layers.

**Comment by AleksueiR** [comment]
Related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2456

**Comment by james-rae** [comment]
As of `v3.0.0` we are no longer using SVG to match against filter results. Instead we pre-filter using definition queries on the identify task.
