### ISSUE TITLE
More SetExtent Calls Not Fitting To Map

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3023]
Some new setExtent calls have been introduced that are not using the fit to map flag
See round one of cleanup here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2214

Current areas needing the flag:

* geoService `setFullExtent`
* core.run `setExtent`
* geoApi map constructor

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. No problem found. As expected.
