### ISSUE TITLE
HTTPS and Service Wizard

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3031]
Appears that if ramp is running in https mode, if a user attempts to add a service based layer via the wizard, and the url is http, the wizard will error.

Some ideas:

* Add an additional check to wizard to detect if we are in https mode, and display a helpful message to user if they use an http url
* Add some code that detects if we are in https mode, and auto-adds an `s` if an http url is passed in
* Discover other trickery that allows an http url to be used

**Comment by AleksueiR** [comment]
- add a hint to the input field that `Requests will be made using HTTPS`

  ![](https://i.imgur.com/WTMzzwk.png)

- if the user enters an `http` url, __do not__ display any error messages right away

- allow the user to click the `Continue` button

- internally, replace `http` with `https` and the try to connect to the service using `https`, but do not update the user-entered url in the input field

  - if successful, proceed to the next step
  - else, display the usual error message (and block the continue button) that the service has failed to connect
