### ISSUE TITLE
chore(build): setup github backup

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#304]
https://github.com/joeyh/github-backup

:point_up: [February 9, 2016 8:47 AM](https://gitter.im/RAMP-PCAR/TeamRoom?at=56b9edde37ae7622436ba68c)

**Comment by james-rae** [comment]
Looks like Mr JoeyH removed the repo. 

Will need to search out a different option, or decide to do nothing

**Comment by mweech** [comment]
> or decide to do nothing
