### ISSUE TITLE
Toggling the visibility on or off of point features other than the first child toggles the visibility on and off of the first child in the legend

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3049]
To reproduce, add the following layer to a map and toggle the visibility on or off of point features other than the first child; the first child in the legend will also turn on or off.

https://webservices.maps.canada.ca/arcgis/rest/services/PHAC/fluwatchers_en/MapServer/0

![fluwatch](https://user-images.githubusercontent.com/2006029/46215998-adefd500-c30c-11e8-8aec-6fbc76e784a5.gif)

**Comment by AleksueiR** [comment]
Which version of RAMP are you using?

**Comment by bchagnon** [comment]
First observed in 2.5.0-0726 and tested with develop with the same result

**Comment by AleksueiR** [comment]
Could be related to 
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3045
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2438
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2456

**Comment by bchagnon** [comment]
Note that toggling the visibility on or off of children works as expected with this polygon feature layer.

https://webservices.maps.canada.ca/arcgis/rest/services/PHAC/influenza_influenza_like_illness_activity_en/MapServer/0

**Comment by YaroRoodzit** [comment]
Issue resolved. Tested with build v2.5.0-b4.
