### ISSUE TITLE
Permit global "excludedColumns" to be managed in the configuration file

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3053]
Many applications using RAMP do not wish to expose the ArcGIS generated OBJECTID field, system fields, or other fields used to determine symbology. There is an array called "excludedColumns" where these fields can be added, and this requires manual editing to add to this array in order to remove these fields from the RAMP viewer.

**Comment by bchagnon** [comment]
How does "excludedColumns' differ from the "visible" key in the table columns array in 2.4/2.5.0... ?
e.g.
```
{
	"data": "OBJECTID",
	"title": "OBJECTID",
	"visible": true,
	"searchable": true,
	"filter": {
		"type": "number"
	}
}
```

**Comment by dan-bowerman** [comment]
Duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2485

**Comment by james-rae** [comment]
@bchagnon the main difference was the internal `excludedColumns` array was a global "forbidden" list of fields. It would be applied even if a layer config had no `columns` array defined (i.e. the default show-everything state). 

Once you start adding items to the columns array, it dictates the table layout, so you need an entry for all columns. So fine when crafting a specific config for a site, but becomes a burden when dealing with random datasets from catalogs or things imported through the wizard.

We've had a few unofficial talks about making the `columns` array more flexible, but it's still on the back-burner.
