### ISSUE TITLE
RAMP v3.0 Documentation Update

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3059]
RAMP 3.0 involves a number of major changes to the library and how it is structured.  As a result, much of the legacy documentation needs to be updated as well as several new sections to properly capture the map authoring and new api/extension functionalities.

RAMP documentation needs to be maintained/updated in two places:

### RAMP Documentation site (https://ramp-docs.fgpv-vpgf.com/v3-0110/#/home)
1. Map Author Docs (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3250)
2. Developer Docs (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3257)
- Introduction (???)
  - Knowledge required
  - Basic RAMP concepts
  - Terminology & UI Component Diagram
- API Doc (???)
- Plugins Doc (???)
- Legacy API Notes (???)

3. Technical Docs (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3258)
4. Contributing Docs: https://ramp-docs.fgpv-vpgf.com/v3-0110/#/contribute/getting_started (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3251)

Please respond with any comments, complaints, missed content, etc.

**Comment by milesap** [comment]
Plugin documentation is mostly complete:
https://ramp-docs.fgpv-vpgf.com/v3-doc-1024/#/developer/plugins

**Comment by mweech** [comment]
Capturing initial outline proposal for posterity before editing issue body.
 
### Potential outline for Readme.MD Documentation
- Description:
   - Basic use case for RAMP
   - High level summary of features (Can link a list of features to doc site sections)
- Requirements to use RAMP
- Usage Example
   - How ramp library is placed in a web app folder structure
   - How it is included in a page
   - Link to more usage examples
- Docs
   - Link to main site and highlight major sections:
     - Map Author Docs
     - Developer Docs
     - Contributing Docs
- Building the Project??
   - Have windows specific build steps to solve node sass
- Support
   - How we provide support
   - Repos
   - Link to contribution docs 

### RAMP Documentation site (based on @milesap  work to date)
- Map Author Docs (https://ramp-docs.fgpv-vpgf.com/v3-0110/#/mapauthor/intro):
   - Writing a config file
   - Adding viewer to a page
   - Link to map authoring tool
   - Tips, Tricks, Issues & Known Limitations??
   - Advanced topics?
- Developer Docs (https://ramp-docs.fgpv-vpgf.com/v3-0110/#/developer/intro):
   - Introduction
     - High level architecture summary
     - RAMP v geoAPI v Esri JS v external libraries
     - Basic RAMP organization
     - Terminology
   - Interactive Schema Docs (https://fgpv-vpgf.github.io/schema-to-docs/)
   - API docs (including list of observables and angular events to subscribe to)
   - Plugins
   - Legacy API Summary
   - Technical Documentation (Auto generated)
- Contributing Docs (https://ramp-docs.fgpv-vpgf.com/v3-0110/#/contribute/getting_started):
   - Tools
    - Github and fork
    - Environment setup
    - Running a local copy
    - Useful commands
    - Https
    - Testing https on localhost
