### ISSUE TITLE
Design for Centralized Filtering

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3062]
# Terms

- Feature Layer refers to a server-based feature layer.
- File Layer denotes a feature layer that is client side (includes WFS-3 layers).
- OID is Object ID, unique to each feature.
- SQL in this document refers to a SQL WHERE clause. E.g. `ANIMAL = 'Dog' AND AGE > 3`. This is what ESRI uses for applying filters to features in layers.

# Fun Facts

- The local graphics array in a Feature Layer...
  - only has OID in the attribute set.
  - is only guaranteed to contain features you can currently see.
  - can be destroyed and recreated when zooming.
- There is no geometry on the client when using a Dynamic Layer. This means spatial query results will be arrays of OIDs from the server.
- Since the grid is now a plugin...
  - we cannot assume what its filtering capabilities are
  - we want to avoid making a plugin author implement something complex like a SQL interpreter

# Filter Manager

A service that presents a simplified interface to filtering, and orchestrates the details of the requests

- Takes requests, finds related layers / filter objects, updates data
- Issues events to notify interested parties that filters have changed
- Allows parties to register / unregister to filter events
- Does appropriate invalidation of previous filter data/results when new changes occur
  
# Data Structure

A set of filters for a feature class (i.e. a Feature Layer, File Layer, or Dynamic Layer's child sub-layer)

This can be managed inside the Filter Manager, or can be placed as a child object of the geoApi `FC` class.

## External things

- a property to indicate who these filters belong to
  - is there a proxy id?
  - filter manager could have logic to create (e.g. layerID + childID + magic)
  - if object is a child of `FC` class then we don't need an id property
- a property describing the flavour of the feature class it belongs to. E.g. `feature`, `file`, `dynamic`. Needed as how we filter varies based on these types
- filter registration functions
  - setSymbolFilter, setApiSqlFilter, setSpatialFilter, setGridFilter
  - would store things internally, invalidate any cached results that are no longer up-to-date
  - might trigger a filter-changed event. but likely makes more sense for this to happen in a filter manager module.
- filter clear functions
  - can target a specific thing (e.g. user turns off extent filter, so turn it off)
  - could have a clear-all variant
  - should also do invalidation of internals
- properties exposing current filter settings (if needed; could be these are fine being internal)
  - symbol SQL, API SQL, spatial extent (or simply a boolean), grid OID array
- a function to return collated SQL
  - combines symbol and API SQL with ` AND `
  - used when a layer wants to update it's definition query with active filters
- a function to return collated OID array
  - want a parameter for who is asking. both to avoid circular filters, and also to avoid triggering server hits when they are not needed. 
  - e.g. table wants to ignore any list of OIDs it has outputted from its last filter
  - e.g. a dynamic layer would not want to get OIDs if its only using a symbology filter, as it can use the SQL instead
  - collation would be a "this number exists in both arrays" type operation
  - should find some real use-cases for this.  could be it's not needed

## Internal things

- pointers to things we need (e.g. source layers, services, event handles)
- promises to execute filters or return cached results (see Internal Filter Request Logic section below for details)
- state storage as needed (e.g. SQL strings)
- validation mechanisms. i.e. ways to know if any executed filter results are still valid
  
## Linkages

- how does the object see its related layer, map, grid plugin?
- supply pointers on constructor?
  - assumes things pointed to stay the same
- supply pointers on function calls
  - more flexible, but need to pass vars more often
- use services / lookups
  - if our filter object is a child of the layer record, we can use internal pointer to get to layer.  but grid plugin is a client side beast, so would need to be passed in
  - if we have a filter manager on the client, can use various angular services to find things and feed them into worker functions  
  - can supply a lookup function that returns an up-to-date result
- this needs discussion with API, plugin, and Angular experts. it also depends where the data structure exists (in layer object, in filter manager, somewhere else).
  	
# Invocations of Filters

## Legend Checkbox

There is existing logic to take the checkbox configuration and return SQL that describes it

- Legend SQL is passed to filter manager. Events are raised.
- if all checkboxes are checked, filter should be cleared
- if no checkboxes are checked, should have proper null query (e.g. `1 = 2`, or whatever is currently implemented)

## Map Extent Filter

- informs the filter manager that Extent filter is on
- on every extent change to invalidate / update the filter. Need to decide if this is handled in the filter manager, or on the extent change event.
- filter gets cleared when extent filter is turned off

## Datagrid Filter (Column or Global)

- grid uses its internal processing (determined by plugin implementation) to handle it's row filtering
- grid informs filter manager of filtered set whenever it updates, and when it clears (no active filters). 
- need to suss out the communication method, as the "i updated" call will be invoked inside the plugin. The plugin interface will need a consistent and documented way to do this.

## Time Slider Filter

Features with different time values have different OIDs. They are essentially no different than attribute filter. We can support this when an official time slider gets made; will just need to add some more properties and conditionals to the filter logic.  We can also utilize the API SQL option for an off-the-cuff version.

## Future API Call

Current design can handle SQL clause against layer attributes.

A future design could be extended to handle an array of OIDs, though it could with some modification (it's just more logic branches need to be added). However, it can encode OIDs as SQL (e.g. `OBJECTID IN (3,4,6)`).

# Internal Filter Request Logic

All request flows will trigger a filter changed event, notifying anything that needs to be aware of a change in filter state.

## Request from Feature Layer or Dynamic Layer

Happens when a layer wants to update what is visible on the map

- if Symbol, API, or Grid filter is present, apply the SQL from filter to the Definition Query of the layer
  - all valid items should be joined by `AND` statements

Note that Dynamic Layers have arrays of Definition Queries, Feature Layers just have a string property

We may need to entertain size limitations on the Grid filter list (many columns on global search). 

~~For Feature Layers, we can also entertain applying OID lists post query with an approach similar to what file layers do; iterate the graphics array and manually change feature visibility. Given the behavior of OnDemand Feature Layers, we would have to re-apply this logic with every extent change.~~

## Request from File Layer

Happens when a layer wants to update what is visible on the map

- if Symbol, API, or Grid filter is present, convert the SQL from filter to RQL
  - all valid items should be joined by `AND` statements
- set all graphics in layer's graphics array to invisible
- apply RQL on the layer's graphics array. turn on visibility of all graphics that pass the query

- store a result array of OIDs that we turned on (this can be used by identify requestor).

Alternate approach: Use RQL to extract valid OIDs (we can even entertain not querying on grid Ids and merge results with grid id array). Then iterate graphics and turn on/off visibility based on result array.
Alternate approach: Don't include the grid filter in RQL. Then in visibility set, do additional array check on raw ids

I'm not sure which of the three variants is most efficient (i.e. how many scans of the graphics arrays and OID arrays need to be done). 
  
## Request from Grid

Happens when a grid wants to update what rows are visible based on non-grid filters

- grid would ask for map promise of OIDs
- File Layer source
  - if Extent filter is present, run ESRI Query on layer using map extent. Pipe result OIDs to next step
  - if Symbol or API filter is present
    - convert the SQL from filter to RQL
	- apply to layers graphics array, extract OIDs
	- do exclusive merge with Extent OIDs if they exist
	- pipe result OIDs to next step
  - promise returns OIDs
- Feature Layer source
  - if Extent, Symbol or API filter is present, run ESRI Query on layer using map extent and/or definition query. Query uses Feature Layer as input
  - promise returns OIDs of query result
- Dynamic Layer source
  - if Extent, Symbol or API filter is present, run ESRI Query on layer using map extent and/or definition query. Query uses child layer URL as input
  - promise returns OIDs of query result  
- this promise is maintained to be re-used until the filter is invalidated
- grid would use the array to filter rows (implementation is internal to the plugin)

Note: the ESRI Query logic will be updated to use a variant that only returns OIDs. This allows us to not have to loop web-calls against the server return limit.

## Request from Identify

Happens when Identify wants to ensure it's results are within any active filters

- File Layer source
  - if stored result, use it
  - else we essentially re-execute the `Request from File Layer` logic above to get OIDs.
    - we might want to consider some params/variants so we skip the "change visibility of graphics" part for this.
  - then use array to filter out any results post-identify
- Feature & Dynamic Layer source
  - if any filter is present, apply the SQL to the identify request

# Design Variation Options

## Restrict OID Array-Based Filter to reasonable amount 

E.g.  Limit our arrays to a number that doesn't grind our system, like 100 features, 1000 features.  Needs some experiments to get an appropriate limit.

Would impact grid filter applied to map, map filter applied to grid.  Would alleviate the size of web calls containing massive arrays of OIDs. May be a necessity if we encounter request size limits in `esriRequest` library. Doing so diminishes the functionality of the filters, especially if we implement table export. May need to have some type of notification to indicate when the limit has been hit (e.g. `Too many results, some results may not be displayed`).

## Remove filter powers from Dynamic Layers

Essentially would say, if dynamic layer, you cannot apply the extent filter into grid, nor may you apply the grid filter into the map.  The benefit is we avoid the constant passing of large arrays of OIDs back & forth from the server. 
Would probably anger some people.  Tagging this as `likely untenable` but documenting for completeness

## Table filter applied pre-Identify

For Feature & Dynamic Layers, our design currently has the array of OIDs from a table filter being scanned after an Identify result returns from the server.  This is to avoid passing very large SQL `IN ()` statements to the Identify Query.  The risk of doing this is we can force the server to return results that will be discarded.

We can entertain an enhancement where if the size of the table OIDs array is below a threshold, we can apply it to the Identify Query pre-request.  Uncertain if it's worth the effort; the win/loss for redundant network traffic can vary wildly based on the dataset and the filters the user has chosen to apply.

# Items Open For Design Discussion

## Event Framework

- Angular events?
- API-ish observables / streams?
- Callback functions?
- Others?

## Code Location

- Ideally stateless logic routines should exist in geoApi
- The filter data object has been proposed to be part of the geoApi `FC` object, but could be placed elsewhere
- Filter manager itself likely should be an Angular service
  - all the other Angular parts need to communicate to it.
  - can leverage angular events
  - may want to consider how it relates to RZ API stuff?

## Interactions with Grid Plugins, Observables

More design discussion on this matter can be found [here](https://gist.github.com/dane-thomas/1788a00ab2c3290f28dca5e2f3da7918)

---

*Initial Draft is preserved here for reference*

## Things that filter / deal with filters

- legend checkboxes
- datagrid columns (needs the apply to map button)
- map extent (i.e. grid filters to what is on map)
- time sliders
- ensuring identify results respect filters (both server based and client based)
- currently no support for file based feature layers
- API functions that have yet to be written
	- e.g. apply filter to grid
	- e.g. apply filter to layer?

## Squad Goals

- Centralize filter logic (filter sheriff).
  - The sheriff keeps track of current filters (including managing filters from multiple sources -- e.g grid filter, extent filter, icon filter).
  - Any control that updates a filter informs the sheriff of it's change.
  - The sheriff broadcasts an event indicating when a filter has updated. Things that display filter sensitive data react to the event (e.g. grid, map).
  - The sheriff can answer questions about filters (e.g. when an identify call needs to know about active filters)
  - Open question: where should this reside? GeoAPI Record class? GeoAPI FC class? A new GeoAPI class that is instantiated by a Record or FC class?
- Implement filtering on File Layers / WFS Layers
  - Need a way to take SQL WHERE clause and apply to an array of features
  - [RQL](https://www.npmjs.com/package/rql) can effectively search an array of features, but requires the SQL WHERE to be converted to an RQL query. E.g. `A < 5 AND B = RED` becomes `and(lt(A,5),eq(B,RED))`
  - Can search out an alternate library that can natively apply a SQL WHERE clause to array of javascript objects
- Update dynamic layer identify to utilize the [layerDefinitions](https://developers.arcgis.com/javascript/3/jsapi/identifyparameters-amd.html#layerdefinitions) property on the server request instead of the current query-to-svg matching that occurs post-request. See geoApi `dynamicRecord` class, search for `validSymbologies` variable.
- Investigate ways to enhance our filter-by-extent, especially for dynamic layers
  - Since dynamic layers don't reveal their geometry, we currently have to ask the server for all object ids in the map extent, then filter out table rows that dont have objectids in that list. For Canada views, this can be a very large list of ids requiring multiple service calls
  - could investigate using the `executeForIds` call on `QueryTask` inside `geoApi.queryMapserver()`. It looks like this function has been written to be most flexible for handling any query, so we use the standard `execute` call. But when restricting to just IDs, it allows the server to bypass the maximum results limit, thus eliminating our multi-call approach for large datasets.  
  - More ideas?
- Create a list of reasonable API calls related to filtering we can envision being implemented in the future.
- Ensure new design can expand to include time slice info. Consider ESRI time parameter. Consider WMS time parameter (not certain if it applies. WMS typically doesnt have features, but possibly in future?).
- Think a little about WFS source filtering (i.e. changing parameters on the URL that determine the data retrieved). This would technically involve re-loading the layer, so likely is out-of-scope.

**Comment by james-rae** [comment]
### Thoughts on column filters, API synchronizations

What if we use the `table.column.filter` structures in the config as a governing body for grid filter information?

* This allows us to set grid filters via the API prior to the grid being created.  It would be similar to a filter being set via the config file.
* I believe if the `table.column` stuff is not defined in the config, it gets autopopulated when the table opens. This would need to migrate to layer load event.
* The `filter` config node is tailored to grid style filters (i.e. what you would see at the top of the column). We would need to decide how we expose this on the API.  E.g. have API user provide things in a similar format, or provide in `SQL WHERE` format and convert.
  * `SQL WHERE` could be problematic as an API user might get real fancy and attempt to submit strings that are too complex for a column filter.
  * Likely easier to convert from column format to `SQL WHERE` format internally when we need it.
  * Config schema is already in column format so might be prudent to have API follow the same format.
  * That said, if we have an API function to apply a filter to a layer directly, it would be in `SQL WHERE` format, so our API would use two different conventions.

### Thoughts on map filter vs grid filter

It's a good observation, we have a few competing formats / paradigms in play.

* Definition clauses being applied against the layers. `SQL WHERE` format. Arrays of object ids being extracted to apply against the grid.
* Grid column definitions. Restricted format (string equality, numeric and date range).
* Spatial intersection for extent, which is not encoded as text. We use geotools to get an array of object ids inside the rectangle.
* Potentially another paradigm to support on-map filtering of file layers / WFS layers (e.g. RQL syntax if we end up adopting something like that).

Primary difference is that grid column filters are limited by our UI, whereas layer filters are limited by `SQL WHERE` syntax.  Anything in grid filter format can be converted to `SQL WHERE`.  Some things to consider for how to arrange this.

* If the fancy grid has an internal filter system that is more efficient than us searching arrays of object ids, then we want to utilize it
* Column definition format is already locked into the config schema
* Both extent filtering and symbol filtering utilize an array of object ids to inform the grid of what to show.
  * Currently don't have a solution for extent filtering to avoid this.  Dynamic layers have geometry hidden so server needs to do spatial intersection
  * Would like to see an investigation on how to use something else for symbol filtering if extent filtering is turned off.  The queries work against attributes so we might be able to convert to local operations.
* Crazy idea: if we end up adopting RQL, we make that our common denominator for the grid.  Have functions `gridQueryToSqlQuery()` and `sqlQueryToRqlQuery()`. So anything can be converted to `SQL WHERE` for ESRI Layer filters, and converted to RQL for grid filters and File/WFS filters.

**Comment by dane-thomas** [comment]
A couple quick notes about filtering with the fancy grid. 
- The table filtering does seem to be quick and simple to use
- There's a way to get the column filters in a nice way. `getFilterModel()` returns something like this:
![image](https://user-images.githubusercontent.com/8885149/47117771-4eae2200-d233-11e8-9006-88ebd41b113e.png)
- It also emits an event `filterChanged` whenever the filter is changed which should allow us to convert the table filters into something we can use for map filtering.

As for filtering the symbols we'd need to determine a way to convert the queries into something the fancy table can consume. Since the table is an intention it may be better to have users implement this conversion (and the reverse) grid side so other grid implementations can also make use of these features. We'd need to have a set of guidelines as to the format of the filters the viewer gives out and expects in.

**Comment by james-rae** [comment]
Another issue to consider, as pointed out by @shrutivellanki & @dane-thomas

The "global search" bar above the grid will search across all columns. We've had requests from clients that they would like the result of this search to also be applied to the map.  Implementation becomes problematic.

### List of OIDs

In this approach, we let the grid handle the cross-column filter, then extract an array of object ids of remaining rows and apply that to the map layer filter.  

Good because we avoid the complexity of the cross-column search. Bad because the list of object ids can be in the thousands, smashing the server and potentially not working if we're not using a proxy to handle the large request.  It also means we need to write additional logic to stop the filtered points from appearing in identify results when using dynamic layers.

Possible alternate: We only do this trick if we are dealing with feature layers, and do the feature-to-OID matching on the client. Would mean no support for dynamic layers, which can be confusing as the grid presents both types of layers in the same way.

Possible alternate: Put a limit on the result size.  E.g. if grid has more than 100 rows, we do not apply a map filter. Again, can be confusing as a user can experience arbitrary behaviors (would adding onscreen messages suffice? "too many results, map is not reflecting the search results").

### Fancy SQL

In this approach, we generate an SQL WHERE clause that will execute the cross-column filter. E.g. if user types `DUCK` we generate a clause nugget something like `((FIELD_1 LIKE '%DUCK%') OR ... OR (FIELD_N LIKE '%DUCK%'))`. We also need to consider the data-type of each field, and decide what the appropriate clause structure is for numerics and dates.

Good because it means the filter clause is in the same format as column filters.  Bad because tables with many columns and a long search term can generate an overly long clause, and we need to write the logic and get the wildcards working on the different types.

### Lazy

Maintain the current standard where global search does not apply to the map.

**Comment by ShrutiVellanki** [comment]
@james-rae 

I could be completely wrong here ...but I wonder if there's a way to trick our code into thinking that a global filter is actually a number of column filters working at once....like lets say the global filter searches for `DUCK` which matches two entries: 

- one has `DUCK` in the `Country` column
- the other has `DUCK` in the `Facility Name` column

reverse engineer each individual column filter for `DUCK`, then apply the multiple resulting column filters to the map

so similar to your Fancy SQL point, but it would sneakily drop the clauses for column filters that we know would not be engaged. 
 - so limit it to `(FACILITY_NAME LIKE '%DUCK% && COUNTRY LIKE '%DUCK%)` vs `((FIELD_1 LIKE '%DUCK%') OR ... OR (FIELD_N LIKE '%DUCK%'))`

Maybe we could achieve this by seeing which column the searched item pops up. As far as I can tell it shouldn't be too complex because global search only deals with string matching.

**Comment by dane-thomas** [comment]
@ShrutiVellanki 

Interesting idea. The only issue I see is finding a way to determine which columns contain the matches since the grid doesn't really do a ctrl-f find kind of highlighting. 

@james-rae 

Looking through the ag-grid quick (global) filter docs brought up another possible solution.

### Global Filter Cache
https://www.ag-grid.com/javascript-grid-filter-quick/#quick-filter-cache
> When the cache is enabled, each node gets a 'quick filter text' attached to it by concatenating all the values for each column. For example, a {Employee Name, Job} table could have a row with quick filter text of 'NIALL CROSBY\nCOFFEE MAKER'. The grid then does a simple string search, so if you search for 'Niall', it will find our example text. Joining all the columns values into one string gives a huge performance boost. The values are joined after the quick filter is requested for the first time and stored in the rowNode - the original data that you provide is not changed. 

We'd have to implement something like this ourselves but it seems to be just a matter of storing the concatenated string and doing the simple string search on it.

**Comment by james-rae** [comment]
Pod conversation:

Spatial filters end up having to be arrays of object ids, due to supporting dynamic layers (geometry is on the server only) and that internal grid filter methods rarely have spatial support.

So in pontificating how a table intention is made aware of filters coming from outside the table (i.e. we could have different filter types, different formats, etc), it seems advantageous to make the input to the table intention filter be the array of object ids.  

* Array of integers is simple
* Grid implementers don't need to worry about supporting formats like SQL or using fancy libraries. A native array search is all that is required.
* Handling of other filter formats into object id arrays is performed by RAMP code outside the table. 
* Allows for future enhancements of supporting other layer types without impacting the grid internals.

Potential flows for symbol filters

### Dynamic Layer / Server Based Feature Layer 

Option 1: We stick with current approach of appending the symbol SQL clause to the layer's definition clause (which updates the map image) and then get the list of valid object ids from the server.  Not the most efficient, but proven and straightforward.

Option 2: If grid is closed, we do nothing with respect to the grid (we update the map as in Option 1). If grid is open, we know we have all attributes downloaded.  Apply the SQL clause to the attribute set (using whatever library we end up using) to extract object ids that way.  Would avoid the server trip.  Would need to handle synchronizations if person opens a grid when a symbol filter is already on.

### Local Feature Layer (File, WFS)

There is no esri server, nor does the layer support a definition clause. However, we can be assured that all the geometry/attributes are present in the local layer.  This means we can apply the same approach as in Option 2 above (using library against attribute set) to determine which features are valid and extract the object id list. We also use this result to toggle the visibility of features on the map.

**Comment by ShrutiVellanki** [comment]
> So in pontificating how a table intention is made aware of filters coming from outside the table (i.e. we could have different filter types, different formats, etc), it seems advantageous to make the input to the table intention filter be the array of object ids.

This approach has worked out well for me with syncing symbology filters to `enhancedTable`:

**Step 1**: [Define a query based on currently toggled symbologies](https://github.com/ShrutiVellanki/fgpv-vpgf/commit/f6024256bd1f1c5497d819928e8f164785679349#diff-3ccf617b00494a3f47c4ce5439842eedR151) (done by using definition clause)

**Step 2**: [Get a list of currently shown symbologies on map](https://github.com/ShrutiVellanki/fgpv-vpgf/commit/f6024256bd1f1c5497d819928e8f164785679349#diff-3ccf617b00494a3f47c4ce5439842eedR139)

**Step 3**: [Convert the above list to a list of ValidOIDs which sits on the corresponding legendNode](https://github.com/ShrutiVellanki/fgpv-vpgf/commit/f6024256bd1f1c5497d819928e8f164785679349#diff-3ccf617b00494a3f47c4ce5439842eedR141)

**Step 4**: Each time validOIDs [list is changed](https://github.com/ShrutiVellanki/fgpv-vpgf/commit/f6024256bd1f1c5497d819928e8f164785679349#diff-01471fae5bc9c54e5df5e1a02b51f70eR756) --> [fire an observable](https://github.com/ShrutiVellanki/fgpv-vpgf/commit/f6024256bd1f1c5497d819928e8f164785679349#diff-01471fae5bc9c54e5df5e1a02b51f70eR762)

**Step 5**: Finally, in the `enhancedTable` plugin [filter the symbologies when the observable is fired](https://github.com/fgpv-vpgf/plugins/compare/develop...ShrutiVellanki:filter-sync?expand=1#diff-598ba6f22c087adc8646060378c27111R161)

**TODO**
- There is still debate around whether the watch/observable method is the best approach for this 
   - @dane-thomas brings up that a table API could handle this, and be advantageous for writing tests
- we have to centralize the conversion of `validOIDs` for different purposes (i.e filter by extent) in the viewer repo (so that this list is synchronised, and the code isn't scattered around in the codebase)

**Comment by dane-thomas** [comment]
As we discussed, I'm not a fan of this watch here. Since you're using an obseravble the better way to do this would be to fire the obervable whenever the `ValidOIDs` array is changed rather than watching for changes to fire the observable. Seems like one extra layer of complexity for no reason.
