### ISSUE TITLE
Export map generation randomly fails

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3067]
It seems there is a bug in the geo legend wrapping logic and it's breaking the export functionality in an unpredictable way.

I traced it to the `packLayersIntoOptimalSections` function `src/legend.js` in `geoApi`. It looks like there is a case where `bestPerm` is never assigned anything and it stays null which then breaks when `assignLayerSplits` tries to iterate over it.
You can see it breaking on http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html.

Load it and try exporting - you will see a "sad Canada" image.

A temporary work around is to set export `columnWidth` to the width of the window - this way no reflow will be be attempted.

**Comment by AleksueiR** [comment]
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3044

**Comment by ShrutiVellanki** [comment]
Can confirm was included in release `v2.5.0`  
- checked out the `v2.5.0` tag
- the changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3085 were included in the code

No more sad canada images that randomly pop up when exporting as tested on [current develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html)

Closing issue.
