### ISSUE TITLE
WFS Layers not encoded/decoded properly in bookmarks

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3071]
Possibly related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2893

The issue was found when testing sample 76 in this PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3065
- When switching between Lambert/Mercator or English/French the WFS layer would disappear (a problem with parsing the bookmark)
- A bookmark entry was generated for the WFS layer, but when tested in [bookmark decoder](http://fgpv.cloudapp.net/demo/develop/prod/samples/bookmark-decode.html) no entry would show up

Similar problems of not producing a proper bookmark happen here: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=75
- if you notice the **Hydrometric Stations WFS Layer** won't show up in the [bookmark decoder](http://fgpv.cloudapp.net/demo/develop/prod/samples/bookmark-decode.html)

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b3. Used sample #75-76. As expected.
