### ISSUE TITLE
Hide Symbol Checkboxes for Raster Layers

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3075]
`Raster Layers` are hosted in dynamic layers, but have no attributes.  So the filter checkboxes that appear in the legend do nothing.   

We should detect when a source is a raster layer and not generate the checkboxes.  I believe there is already code that does this for other layer types (tiles, perhaps).

[Sample Service](http://www.agr.gc.ca/atlas/rest/services/mapservices/crop_spatial_density/MapServer/), load as dynamic with index `0` as the child layer

**Comment by YaroRoodzit** [comment]
Verified with build v2.5.0-b3. As expected.
