### ISSUE TITLE
Enhanced Table #1: Missing Features 

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3077]
List of improvements to be added to `enhancedTable` (mostly for the purpose of matching existing datagrid as closely as possible): 

- [x] Missing Settings and Clear Filter button on bottom right
- [x] Count of entries and numbers currently showing
- [x] Clicking Item in legend should toggle enhancedTable
- [x] No option to Hide Filters in Menu

#### 1. Missing Settings and Clear Filter button on bottom right
   - As of right now have to manually clear each filter
   - Settings button important to access functionality (shown below) which is also absent from table
   - Remember to add proper hovertext to both buttons
![1a](https://user-images.githubusercontent.com/25359812/46809660-f65fb780-cd3c-11e8-8464-b1d48d2715ca.PNG)
![1b](https://user-images.githubusercontent.com/25359812/46809668-f9f33e80-cd3c-11e8-8298-0d60c90598ca.PNG)

#### 3. No option to Hide Filters in Menu
   - current table: 
   
![capture](https://user-images.githubusercontent.com/25359812/46814384-9a9a2c00-cd46-11e8-8540-1101d28e1d6c.PNG)

**Comment by milesap** [comment]
Re: **1. Missing Settings and Clear Filter button on bottom right** I believe we'll proceed without the settings feature. It's a lot of UI work for simply hiding & reordering columns for keyboard accessibility. We'll still need to finalize how hiding and reordering columns will remain keyboard accessible, but one easy way would be to display a text input box with values `[A-Z]*`, one letter per column. So an 11 column table would have the value `ABCDEFGHIJK`. You can reorder columns by changing the value in the text box. To make the first column the last you would change it to `BCDEFGHIJKA`. To hide the second column just omit it `ACDEFGHIJK`. This text box could be displayed when keyboard navigation is detected or via some accessibility toggle button.
