### ISSUE TITLE
Include French version of open.png and menu.png in "Help" content

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3078]
1. In "Cartes de base" content (/help/default/images/basemap/) use attached French version: open_fr.png
![open_fr](https://user-images.githubusercontent.com/2006029/46813417-a4229480-cd44-11e8-8918-a97d01a253a2.png)

2. In "Sous-menu Couches" content (/help/default/images/layer_submenu/) use attached French version: menu_fr.png
![menu_fr](https://user-images.githubusercontent.com/2006029/46813424-a84eb200-cd44-11e8-8c8c-eebc7aaea04f.png)

**Comment by YaroRoodzit** [comment]
Verified with version v2.5.0-b3. As expected.
