### ISSUE TITLE
Enhanced Table #7: Make Table Navigation Accessible

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3080]
List of improvements to be added to `enhancedTable` (mostly for the purpose of matching existing datagrid as closely as possible):

#### 1. Table Accessibility Unintuitive: 
   - When you enter tab mode to go around the screen with an open `enhancedTable`, you are forced to tab around: 
        - every other layer
        - zoom buttons, home buttons etc. 
        - and then finally you are able to access the table

#### 2. Navigating through cells:
- navigating through cells (both horizontally and vertically) is not currently possible 
- the table doesn't seem to have a way to exit out of tabbing through filters and into the cells themselves (unless you click on one of the cells)

**Comment by dane-thomas** [comment]
Related: #3088
See for discussion on points 3 and 4

**Comment by AleksueiR** [comment]
Is it possible to create Focus Manager links from the first filter control to the first table cell and from the last table cell to whatever control follows the table? These links were designed to bridge such untabable gaps.

**Comment by dane-thomas** [comment]
https://github.com/fgpv-vpgf/plugins/pull/24 addresses point 2 of this issue. 

The first point still needs to be handled.

**Comment by dane-thomas** [comment]
fgpv-vpgf/plugins#24 has been updated to address both points in this issue.
