### ISSUE TITLE
Datatable Breaks when Symbologies are Toggled with a Reloaded Layer

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3100]
There is an issue that is in `table.service.js` found by putting a `console.log(validOIDs)` in the following function:

```js
 function filteredState() {
        const legendBlock = stateManager.display.table.requester.legendEntry;

        // we're not filtering by either symbology or extent, so resolve with all oid's as valid
        if (!service.filter.isActive && typeof legendBlock.symbDefinitionQuery !== 'string') {
            validOIDs = stateManager.display.table.data.rows.map(row => parseInt(row[stateManager.display.table.data.oidField]));

           
            console.log(validOIDs);

            return $q.resolve();
        }

        return queryMapserver().then(oids => (validOIDs = oids));
    }
```

where the `validOIDs` resolve as an array of `NaN` when a reloaded block's visibility is set to true (after it was reloaded from a false visibility state).

This causes the table to be empty despite the block's visibility being true because obviously, `NaN` does not correspond to any `OIDs`

Issue was first found in this PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3051. Although, as found by @dane-thomas  and myself, it existed much before then, with the datatable breaking sometimes when symbologies were toggled randomly for a reloaded layer. (and the root cause was the same issue)

**Comment by RyanCoulsonCA** [comment]
This issue seems to be fixed. Disabling a layer, then reloading and re-enabling the layer displays the table properly.

![3100test](https://user-images.githubusercontent.com/25874602/57863452-233ee600-77c8-11e9-8505-063ec21a51d8.gif)
