### ISSUE TITLE
Define initial map extents based on screen size

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3108]
![image](https://user-images.githubusercontent.com/5294596/47575411-07e5b980-d910-11e8-89e0-077d2b4a64d9.png)

When viewing a RAMP map in mobile view, the extent can seem extremely zoomed out compared to a full resolution desktop experience, which by default will show the extent of Canada. 

This feature request would allow a separate configuration option for mobile views or smaller resolutions.

**Comment by AleksueiR** [comment]
There is a legend config option to have the legend open/closed on an initial loading based on the screen size (large, medium, and small): https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/schema.json#L901

The extent should probably follow the same pattern - depend on the size of the map, not trying to detect a mobile browser. Do you think we need three extent options (`large/medium/small`) for all extents (`default/full/maximum`)?
