### ISSUE TITLE
Setting 'disabledSearches' disables the option to search for scale

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3111]
Setting the `disabledSearches` array in the config file, be it empty or populated with "NTS", "FSA", or "LAT/LNG" values, disables the option to search for scale.

![searchscale_bad](https://user-images.githubusercontent.com/2006029/47670184-f9530880-db82-11e8-8a96-ee1c29a23a81.png)

Removing the `disabledSearches` array from the config file enables the option to search for scale.

![searchscale_good](https://user-images.githubusercontent.com/2006029/47670192-feb05300-db82-11e8-9297-252cdf0084ef.png)

Also note that having to list the enabled search types in an array named `disabledSearches` is counter intuitive.

**Comment by mweech** [comment]
"disabledSearches" should be renamed to "enabledSearches" and a more complete default provided initially or default to "enabledSearches" being missing.

**Comment by james-rae** [comment]
New issue made for renaming config element, as above request breaks schema. 
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3177

**Comment by YaroRoodzit** [comment]
Tested with  build v2.6.0-b2.
Used sample #21. As expected.
