### ISSUE TITLE
Should corresponding filter Type be removed from drop down option when disabling "NTS", "FSA", or "LAT/LNG" in Geosearch?

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3112]
![type](https://user-images.githubusercontent.com/2006029/47671082-2dc7c400-db85-11e8-88d2-aa39d60450c4.png)

**Comment by AleksueiR** [comment]
This is a good point - if any of the options are disabled, they should be removed from the dropdown.

**Comment by james-rae** [comment]
If someone takes this, and is not Jahid, see me first. I have some code to supply you with.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. Sample 87.
Issue resolved. 
NTS and FSA are not in the result type dropdown .
