### ISSUE TITLE
Metadata option should not be available unless defined in layer configuration

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#3113]
Tested build

http://fgpv.cloudapp.net/demo/v2.5.0-b4/prod/samples/index-fgp-en.html?keys=JOSM

**Steps to Reproduce**

- Add  dynamic Service layer http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_agri_environmental_indicators/MapServer

- Once  the layer loads, select Metadata for one of the sublayers

- Console gives the below error and Metadata does not load

![image](https://user-images.githubusercontent.com/18539315/47855531-3d305280-ddbb-11e8-850f-9de130533a38.png)

**Comment by YaroRoodzit** [comment]
Tested with version 2.6.0-b1.
Used sample #6 ( /index-samples.html?sample=6 ).
Works as expected.
