### ISSUE TITLE
Layer states - Visibility, Bounding Box, Opacity not maintained while bookmarking the viewer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#3114]
Tested build :http://fgpv.cloudapp.net/demo/v2.5.0-b4/prod/samples/index-fgp-en.html?keys=EcoAction

Any changes to the states of layers like changes in opacity, enabling bounding box, visibility is not maintained while performing "Get Link, Back to Cart or Share" function

Please advise if this is now changed.

**Comment by james-rae** [comment]
Check after fixing https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3118 ; both relate to bookmark use

**Comment by YaroRoodzit** [comment]
Tested with version 2.5.0-b5.
Issue resolved. Layer properties are preserved and maintained while bookmarking the viewer.
