### ISSUE TITLE
Feature Layer misaligning when panning in Chrome

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3119]
Noticed the following on Nov 1, 2018.

When panning in Chrome, sometimes after the pan the points of a feature layer would jump/misalign.  Further investigation yielded:

* Mainly affects Chrome. IE works great :trophy: . Firefox works but has this ugly stutter during the pan, where the points are off / duplicated then correct themselves.
* Affects both wet (index-fgp) and non-wet (index-samples), though seems to occur far less in non-wet
* Dynamic layers are unaffacted.
* Feature & File layers are affected
* CCP seems ok. It's using wfs, which is file layer, so odd why. Possibly because its only file layer, and there are no server based layers
* CAM is ok (dynamic layers only)
* Occurs in older versions of RAMP. We tested as far back as v2.0.0.
* Occurs on multiple EC desktops
* Occurs on non-EC computer/network (Mac OS 10.13 with latest Chrome)
* When points shift, the mouse events (hover, click) remain at the correct location
* A [basic sample site](http://maps-cartes.dev.ec.gc.ca/sandbox/panparty.html) of just basemap & feature layer does not exhibit the problem.

Ideas of what changed / caused this

* It's been like this for 18+ months and nobody noticed (tagging this as possible but highly unlikely)
* A 3rd party library that RAMP is using has been changed
* Something in Chrome codebase changed that affects something we are using in RAMP

Ideas for how to narrow down root cause / solution

* Cry
* Add map features to the simple sample site until the behavior starts
* Eliminate features from a copy of RAMP until the behavior stops

**Comment by james-rae** [comment]
More behaviors noticed.

Was able to reproduce on CESI prod (feature layers).

Notice when opening the layers options menu, the feature layer flickers and the server gets hit with a redraw. Sometimes the flicker doesn't recover, and some or all points go invisible. They re-appear when you pan the map.  One time opening he options menu caused a small shift in the position of the points.

**Comment by james-rae** [comment]
Found another occurrance of the issue.  In [CCP with WMS layer](https://climate-viewer.canada.ca/climate-maps.html#/?t=annual&v=tmax&d=dcs&r=rcp85&cp=-95.80098000546008,59.67409464609375&z=3&ts=3), if you do a some keyboard panning, then some mouse panning, you can get the WMS layer to un-align with the basemap.

* Have not been able to trigger with just mouse panning
* Can reproduce in Chrome, Firefox, IE11
* When keyboard panning east/west, we notice a small bump southbound after the first 2-3 pans
* Once out of synch, the map appears to stay out of synch (though the displacement can vary slightly)
* Cannot reproduce this on the WFS point layers.

**Comment by james-rae** [comment]
More testing. 
Was unable to reproduce feature layer in Chrome in non-WET page.  WET page still very eagerly exhibits the issue. 

Also tried the [Lake Winnipeg Basin](http://environmental-maps.canada.ca/lwbsf/App/LWBSF_FIBLW?GOCTemplateCulture=en-CA) map (Which uses WET).  Upon turning off visibility of the green basin polygon, all the points raced to the south-east.  Turning back on, green polygon went north-west.
Two other team members could not re-produce. Updated Chrome from v69 to v70.  Could not reproduce.  Added [JOSM](http://section917.cloudapp.net/arcgis/rest/services/TestData/Oilsands/MapServer/0) to the Lake Winnipeg map and then could get the freakout to happen.

Pontifications:
WET or something related to WET seems to be triggering the issue or making it happen more easily.
Also seems to trigger more often if the feature dataset is larger.
Given how grievous the initial jumps were in Lake Winnipeg, it lends a shred of support that this is a new change, as this likely would have been seen during the testing of that site.

**Comment by mweech** [comment]
Removed from releases and milestones until we have a better idea of what might be causing this and what a solution may be.

**Comment by JahidAhmed** [comment]
Note: tested on Chrome v70.

Tested on local build, [Develop](http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html), [CESI](http://indicators-map.canada.ca/App/CESI_ICDE) and a [Basic Page](http://maps-cartes.dev.ec.gc.ca/sandbox/panparty-jahid.html).

Tested [JOSM Mercator](http://section917.cloudapp.net/arcgis/rest/services/TestData/Oilsands/MapServer/0), [JOSM Lambert](http://section917.cloudapp.net/arcgis/rest/services/TestData/OilsandsLambert/MapServer/0) and [Air quality: Volatile organic compounds](https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/30).

The Air Quality layer is a smaller layer, as compared to JOSM, and I also tested by including filters to minimise the number of points shown (not sure if this makes any difference). I was able to reproduce the issue consistently on all the pages (doesn't seem limited to WET pages) with all layers (doesn't seem limited to large layers) except for the basic page linked above where it happened very infrequently, but did occur at least a couple times.

I haven't been able to find the root of the problem, or any potential solutions as of yet. But I'll continue looking into it. Just adding this comment to update on my findings, and if anyone has any ideas or thoughts.

Attached a couple GIF's below to help see what's happening, though they might not be very clear.

Develop branch, JOSM layer
![developjosm](https://user-images.githubusercontent.com/9637542/49172822-055ff080-f310-11e8-82d0-27e09613242e.gif)

CESI build, Air Quality layer (small grey dot on screen, may be hard to see)
![cesiairquality](https://user-images.githubusercontent.com/9637542/49172886-2de7ea80-f310-11e8-8225-ee51575c8fa7.gif)

**Comment by mweech** [comment]
Has been reproduced on RAW Esri JS API map.  Not a RAMP specific issue, but will remain as a known issue to monitor.
