### ISSUE TITLE
 Image size change not available for Export . 

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3120]
Tested with build v2.5.0-b4.
 Image size changes not available for Export.
![image](https://user-images.githubusercontent.com/38046459/47923121-f6139180-de8e-11e8-8b0f-7a6052d1f381.png)

**Comment by AleksueiR** [comment]
Export sizes were taken out as a side effect of implementing local printing - it's not possible to locally generate an image larger than the size of the map. Read here for details: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3044#issuecomment-425940220
