### ISSUE TITLE
Enhanced Table #13: Date Picker for Filter

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3121]
### Problem
Ag-grid comes with support for date filters using the browser's built-in date picker. Since the implementation differs across browsers there's no guarantee for consistency in how it would work. Also the accessibility isn't great in Firefox and haven't been able to test it in IE. 

### Ideas
1. Create a controller for the date picker
  Do something similar to how the other buttons on the panel are made using angular. The main issue I see is the same controller would be used for multiple date pickers meaning the date values would be shared. Would appreciate if someone who knows more about how this works could confirm/deny.

2. Somehow compile the template that's being injected before adding it to the DOM
  Not sure if this is possible but should allow the use of the `md-datepicker`. 

3. Add a date picker to the panel api
  Would include the date picker as a panel element. Not sure how/if injecting this into the table and getting the values from it to the filter would work. 

4. Find a new date picker library
  Would need to find one that's both accessible and has a material theme. 

5. ~~Find a new grid?~~

My current preferred idea is 4 unless either 1 or 2 are possible. 

Any thoughts on the above or other ideas?

**Comment by AleksueiR** [comment]
6. Build our own grid.

**Comment by AleksueiR** [comment]
Can you just use Angular Material Date picker? It's accessible and use Material Design:
![](https://i.imgur.com/WnBsVcp.png)

https://material.angularjs.org/latest/demo/datepicker

**Comment by dane-thomas** [comment]
Because the grid is rendering the header we'd need a way of compiling the angular template. Basically it's just inserting `<md-datepicker>` into the DOM instead of compiling it. This is what ideas 1 and 2 were trying to address. I wasn't able to find a way to get that working but if you know how to do it that'd be the ideal solution!

**Comment by AleksueiR** [comment]
I might be missing something, but we compile Angular templates and insert them into random places all the time. Something like this should work:

```js
const pickerTemplate = $compile(`<md-datepicker ng-model="ctrl.myDate" md-placeholder="Enter date" disabled></md-datepicker>`)(scope);

const tableHeaderElement = /* get the corresponding HTML element */
tableHeaderElement.append(pickerTemplate);
```

**Comment by dane-thomas** [comment]
Update:

The final conclusion was to use the angular material datepicker and also adding a function to handle angular compiles that returned a scope. This allows the table to access the datepicker's scope and apply the values received to the filter.
