### ISSUE TITLE
Broken datatable for file-based layers with visibility off

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#3127]
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

Changes were made to the table functionality where if the layer visibility is off, the table does not display any results. This results in an error for file-based layers.

![image](https://user-images.githubusercontent.com/9637542/48151104-715db480-e28e-11e8-9f6a-156d44a404ff.png)

If the visibility is off and you try to open the table, it will indefinitely remain in the `Building table` state.

![image](https://user-images.githubusercontent.com/9637542/48151143-85a1b180-e28e-11e8-9b0e-da954dfeba51.png)

If you toggle the visibility after the table is already open, it throws the errors shown above but does not break the table (it has no effect, so nothing actually gets filtered out).

**Comment by YaroRoodzit** [comment]
Tested with version 2.6.0-b1
Problem resolved. Works as expected.
