### ISSUE TITLE
The term 'Hide' in the slow layer alert toast is confusing

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3130]
The term **Hide** is used inconsistently. It is displayed on the button that closes the "**[layer] taking longer than expected**" alert toast. It is also displayed in the Layers menu on the icon to **Hide all** layers.

A user might think that clicking on the **Hide** label in the alert toast will hide the slow loading layer from the map. **Close** is a more appropriate term to display and used throughout the viewer to convey the action of closing pop-ups, windows, etc.

**Comment by mweech** [comment]
@AleksueiR : Replace "HIDE" with "Dismiss" ?

**Comment by YaroRoodzit** [comment]
Tested with version 2.6.0-b1.
Works as expected.
