### ISSUE TITLE
API Legend: Allow Symbologies to be toggled by index instead of name

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3131]
Find a better way to toggle on and off symbologies other than passing in an array of names. Otherwise:
     - could fail when multiple symbologies have same name
     - could fail on language switch

The way we [currently do it](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/legendAPI/api/src/legend.ts#L432)

```js

    /**
     * Toggles the Symbologies for LegendItems of type legendNode with toggle-able symbology items (in a symbology stack).
     * @param names List of strings matching the name of the symbologies to toggle
     */
    toggleSymbologies(names: Array<string>): void {
        if (this._availableControls.includes(AvailableControls.Symbology)) {
            names.forEach(name => {
                // toggle only if the symbology item has toggle button
                if (this._legendBlock.symbologyStack.toggleList[name]) {
                    this._legendBlock.symbologyStack.onToggleClick(name);
                }
            });
        }
    }
```

**Comment by james-rae** [comment]
Suggest using an ordinal/positional approach.  E.g. toggle the symbol at index `2`. 
If API doesn't already, we could add another function that returns the names of symbols in order.

(Note: function names are fictional in examples)

For use cases, odds are an implementer knows the data they're interacting with, so can just use the ordinal.

```
RZ.getLegendItem('dots_layer').toggleSymbol(3);
```

If they need to inspect the name to find the ordinal, they can do something like

```
var myLegItem = RZ.getLegendItem('dots_layer');
var myNames = myLegItem.getSymbolName();
var myPos = myNames.indexOf('Red Dot');
myLegItem.toggleSymbol(myPos);
```

We can also decide to overload the function parameter or not.
e.g. could always take array of indexes.  `myLegItem.toggleSymbol([2]);`, `myLegItem.toggleSymbol([2, 4, 5]);`.   Could enhance to be smart and treat a single integer the same as a 1-element array.  Do what makes most sense.
