### ISSUE TITLE
Audit & upgrade dependencies for v3 release

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3137]
Upgrade all dependencies to latest version and fix issues as they arise. Audit packages with vulnerabilities and remove/replace as needed. 

![v](https://user-images.githubusercontent.com/10187181/48906814-a98af880-ee33-11e8-9e70-8700e286690e.png)

😟

**Comment by mweech** [comment]
Removed assignment to make available for pickup.
