### ISSUE TITLE
Replace ie-polyfills.js with a host page driven call to polyfills.io

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3141]
Originally discovered when `Help`, `About`, and `Share` dialog panels wouldn't open in IE Edge. RAMP did not version check IE browsers and incorrectly polyfilled Edge.

Tested on the latest develop.

**Comment by AleksueiR** [comment]
Dialogs fail to open because of the `ie-polyfills` - I guess some of them interfere with IE Edge native implementations. Removing polyfills makes dialog open up again.

**Comment by AleksueiR** [comment]
This bug is separate from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3147.

**Comment by YaroRoodzit** [comment]
Tested with version 2.6.0-b1.
HELP still an issue with EDGE. 
1.Cannot be opened with /index-fgp-en.html
2. HELP  tabs not available from /index-samples.html

No problem found with IE11

**Comment by YaroRoodzit** [comment]
The issue was re-tested. Looks that previously it was some caching problem so disregard the previous comment. HELP works properly with IE11 and EDGE .
