### ISSUE TITLE
Allow custom legend placeholders to have filters

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3143]
Concept we've toyed with.  You can take a real layer and override what it's legend/symbol stack looks like in a structured legend.  E.g. a layer with 50 different plant names, you can collapse to a few items (e.g. Shrubs, Trees, Fungi).

Would like to be able to add a custom definition query to the custom symbol element to allow symbol filters to work.  Would follow same structure/functionality as what we get when using the "from the server" legend.

**Comment by james-rae** [comment]
With the implementation of custom renderers on feature-based layers ( https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2878 ), the pending fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3237 , and the upcoming new filter engine (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3055), we will be able to filter on the custom renderer's definition in `v3.0.0`.  
This will still mean there is no support for dynamic layers.
But we can consider this half-supported, as anyone who wants to customize their symbol stack and the filters can do so with a custom renderer when using vector-based layers.

**Comment by james-rae** [comment]
Additional use case found.  If we have a layer with simple graphics on the map, but want fancier graphics in the legend, the `customRenderer` approach wont support that.  See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3518

**Comment by ShrutiVellanki** [comment]
## Custom Symbology Stack Solution: 

Focused on addressing use case in #3519

### Problem: 

> Concept we've toyed with. You can take a real layer and override what it's legend/symbol stack looks like in a structured legend. E.g. a layer with 50 different plant names, you can collapse to a few items (e.g. Shrubs, Trees, Fungi).
> 
>   Would like to be able to add a custom definition query to the custom symbol element to allow symbol filters to work. Would follow same structure/functionality as what we get when using the "from the server" legend.

### Analysis: 
- `customRenderers` can support custom images for attributes ([see demo]()) that apply directly to map. This makes them a good candidate for *custom symbol elements that allow symbol filters to work*.
- It would be nice to preserve the current behaviour of symbols. Could have two types of symbologies: 
    - legend-only symbology stacks
    - custom element & custom filter stacks 
- For the filter portion, could use an `sql` query that could easily apply to map and filter the table (suggested by @james-rae)

### Solution

#### Schema

```json
"symbologyStack": {
"type": "array",
"items": {
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "sqlQuery": {
                    "type": "string"
                }
            },
            "required": [
                "image",
                "text",
                "sqlQuery"
            ],
            "additionalProperties": false
        },
        {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            },
            "required": [
                "image",
                "text"
            ],
            "additionalProperties": false
        }
    ]
}
```

#### Sample Schema

```json
{
  "layerId": "powerplant100mw-naturalGas",
  "symbologyStack": [
    {
      "image": "http://fgpv.cloudapp.net/demo/__assets__/beautiful.png",
      "text": "",
      "sqlQuery": ""
    },
    {
      "image": "http://fgpv.cloudapp.net/demo/__assets__/step1.gif",
      "text": "",
      "sqlQuery": ""
    }
  ],
  "symbologyRenderStyle": "icons"
}
```

#### Implementation Plan

Need to ensure that solution: 
- shows symbology checkboxes that
    - sync with datatable
    - sync with map
- custom symbology images are reflected on map (as map points)

---

**For Simple Renderers:**

![](https://i.imgur.com/ZmeHVJ7.png)


**For Unique Value Renderers:**

![](https://i.imgur.com/YQOxzyo.png)


**Plan for Custom Symbology Layers:**



Pass in a flag/custom config snippet from `symbology-stack.directive.js` indicating that the symbology stack should use a unique value renderer. 
- modify automatically generated `simpleRenderer` to be a `Unique value renderer` with `uniqueValueInfos`
    - use custom images from `config` and `sqlQuery` from config to supply information for `definitionClause` and `symbol`
    - use existing auto-generated simple renderer info for the rest of the renderer

**Problem to figure out:** 
- [THIS](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/symbology.js#L400) is the function `symbology-stack.directive` executes 
    - executed BEFORE [THIS](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/symbology.js#L961) is hit (triggered by `attribute.js`)
- If I am implementing this by passing in a config snippet from `symbology-stack.directive.js` need to set some sort of watch so it can jump in and interfere at the `SWITCH`

**Comment by ShrutiVellanki** [comment]
Implementing the custom symbology capabilities as outlined in #3518

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b4
Works fine in most cases. A related issue has been registered (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3630).
