### ISSUE TITLE
Funny business when adding same GeoJSON

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3144]
Yaro has reported the following behaviors.

Add the same GeoJSON file (via wizard) twice. Turn off visibility of one layer. Both become invisible.

Add same GeoJSON file (via wizasrd) thrice. Only two layers appear.

Initial thought: something is re-using the same id for the layer.

**Comment by mweech** [comment]
@YaroRoodzit please provide a link or email us the sample file.
