### ISSUE TITLE
RAMP fails to load if `legend` component is missing from the config's `export` section

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3146]
### Reproduce:
1. remove `legend` from the `export' section of the config
2. load the map
3. observe map failing to load

Code [over here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/core/config.class.js#L1893) expects defaults for this component which are not being set and assignments fails.

Try this config:
```json
"export": {
      "title": {
        "value": "Title"
      }
    },
```

**Comment by AleksueiR** [comment]
Defaults are now being applied to the legend export config component:
```js
// apply legend export component defaults
            source = {
                ...{
                    showInfoSymbology: false,
                    showControlledSymbology: false,
                    columnWidth: 350
                },
                ...source
            };
```

**Comment by YaroRoodzit** [comment]
Tested with version 2.6.0-b1. Sample #80.
Tested with EDGE, IE, Chrome and FF.
Issue resolved.
