### ISSUE TITLE
Export doesn't work in IE Edge

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3147]
When using Microsoft Edge, when a user tries clicks the download as png or download as jpg button the page will either 
- crash or 
- open a small window and freeze, even clicking close doesn’t do anything (see ‘Viewer image download bug.PNG’ attached).

These bugs do not occur in other browsers. However, in other browsers the download as png or jpg pop-up loads very slowly (it takes 13 seconds to load on my computer and on my colleague’s newer computer). Is it possible to have this load faster?

Reported by CCCS.

**Comment by AleksueiR** [comment]
The problem seems to be with trying to render any text on the canvas. Rendering any legend information like layer names or footnote or timestamp goes into an infinite loop crashing the page.

So far, I traced it to the [textflow](https://github.com/fgpv-vpgf/svg.textflow.js/blob/master/svg.textflow.js) SVGjs extension. `this` is not defined inside the extension. It's a given that this code works everywhere else, even in IE11!. :rage3:

**Comment by AleksueiR** [comment]
The `textflow` function executed [in the following call](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/export/export-generators.service.js#L556) does not get `containerSvg`  assigned to `this`. This `this` undefined, the function enters an infinite loop because [`this._width` is not defined](https://github.com/fgpv-vpgf/svg.textflow.js/blob/master/svg.textflow.js#L119).
```js
const footnoteSvg = containerSvg.textflow(containerSvg, footnoteText, containerWidth - 20 * 2);
```

Either trying to `call` or `bind` the function with the proper `this` doesn't work. Still undefined:
```js
const footnoteSvg = containerSvg.textflow.call(containerSvg, footnoteText, containerWidth - 20 * 2)
// or
const a = containerSvg.textflow.bind(containerSvg);
const footnoteSvg = a(footnoteText, containerWidth - 20 * 2)
```

The SVGjs library version is pinned in GeoAPI, so it's not their update that is responsible.

**Comment by AleksueiR** [comment]
Confirmed the bug to exist on the latest Edge: 44.17763 /18.17763 😭

**Comment by AleksueiR** [comment]
Reproducible Codepen with SVG + textflow which kills Edge: https://codepen.io/AleksueiR/pen/rQoJGd?editors=1010

**Comment by AleksueiR** [comment]
Working in Edge pen: https://codepen.io/AleksueiR/pen/pQqVrv?editors=1010 🌮 🐴 📯

**Comment by YaroRoodzit** [comment]
Tested with version 2.6.0-b1.
Export dialog works properly in IE and Edge, but  RAMP fails to download exported image when EDGE in use. (#3184)
No problem with IE and other browsers.

**Comment by YaroRoodzit** [comment]
Tested with build v2.6.0-b2.
Export dialog and download works properly.
