### ISSUE TITLE
Layer title has not been changed for CMIP5 in layer properties and layer data.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3150]
Tested with version: 2018-11-27
Layer title has not been changed for CMIP5 in layer properties and layer data. See attached for clarity.
![image](https://user-images.githubusercontent.com/38046459/49093923-256db200-f233-11e8-8df9-cebbc1e969a6.png)
![image](https://user-images.githubusercontent.com/38046459/49094076-6239a900-f233-11e8-9dbc-58af51570df7.png)

**Comment by mweech** [comment]
"These are note the repos you are looking for..."
