### ISSUE TITLE
Enhanced Table #8: Apply to Map button

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3156]
Branches off from #3088

In the mentioned issue there was an idea to scrap the settings panel on the old table and move all functionality from it to the table itself. Additionally with some of the design changes that were decided for the table, there is no longer a footer where we can put an `APPLY` button to apply the filters to the map. 

There are currently three ideas for migrating this functionality to the new table:
1. **Debounce the input to the filters and apply directly to map**
    Modify the filters so they wait for a specified amount of time then apply the filter from the column to the layer with out any button press from the user. 

2. **Button in the header**
    Add a button in the header that would apply the filters to the map. It would need to be decided where the button would go and how to place it since the header is somewhat crowded already. 

3. **Apply button for column filters**
    For ag-grid there's an option to add a button to apply the column filter. We could use this same button to trigger the apply to map. 

For now, the preferred solution is option 1 since it prevents us from having to add another button to the table panel and mimics the way the filters currently work for the table.

**Comment by mweech** [comment]
Option #1 sounds like what I would expect to happen on filtering the grid, but may not be expected functionality for all so we can not just switch without having a fall back to a "lazy apply".  How about a toggle option in the menu?

**Comment by mweech** [comment]
@dane-thomas can you please summarize why this is blocked.

**Comment by james-rae** [comment]
It's waiting for me & the filtering engine ( https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3055 ).  Once my code is working the apply to map trigger should be able to plug in, provide it's info, and everything else updates itself.

**Comment by dane-thomas** [comment]
After discussion with @AleksueiR we decided to change the `Apply to map` button to `refresh map data`. 
![image](https://user-images.githubusercontent.com/8885149/51039874-3759a900-1584-11e9-8a05-6d880952e5af.png)

The button has been added to the UI with a placeholder function that needs to be filled in once the filtering engine is complete. 
[Code Changes](https://github.com/dane-thomas/plugins/commit/edd8e3de43d0bcf69ce53b507a6aefeafcca480c)
