### ISSUE TITLE
Feature selection turns off all layers but the last one listed in multi layered basemaps

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3172]
In the latest release and previous releases, only the bottom layer is visible after feature selection. All layers of a multi layered basemap should be visible after feature selection e.g transport base + shaded relief. 

![selection_and_base_layers](https://user-images.githubusercontent.com/2006029/49527235-79a21300-f87f-11e8-9b22-4edc75aafdc1.gif)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. Sample 87.
Issue resolved.
The basmap doesn't change during the identify process.
