### ISSUE TITLE
Make columns in table config more forgiving

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3173]
If you supply a `table.columns[]` item in a layer's config, and it has a `data` value that doesn't exist on the map service, the grid will fail to open.

While it's good to know when a config is ill-defined, it could also be the case that a 3rd party service definition changes field names without letting you know, and thus breaks your grid.

Would suggest the code be updated to not totally fail, but to ignore invalid column configs and maybe put a loud warning on the console.  `customizeColumns()` in `table-default.directive.js` is one fail point, there may be more

**Comment by RyanCoulsonCA** [comment]
After testing, this issue seems to be fixed.

The following snippet was put into config-sample-39.json, and the table opened fine.
```javascript
"table": {
          "columns": [
            {
              "data": "Country"
            },
            {
              "data": "OBJECTID"
            },
            {
              "data": "asdasdsas"
            }
          ]
        }
```
