### ISSUE TITLE
Support client side layer attribute alias definitions

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3175]
We can override what grid column names are in the config, but cannot override normal field aliases, which affect the identify pane.   We rely on the map service having an alias defined, otherwise we get the raw field name.   If a person wants something else, they must define a custom identify template.

Also, now that we support WFS3, which doesn't have field aliases, this limits those layers to the same constraints.

Consider adding something to the layer config structure that can define a field alias for Feature Layer, WFS Layer, File Layer, or Dynamic Layer (would be at the child level of the definition).
This alias would override any server-based aliases that are lurking around.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b4
Test sample #90
Works as expected.
