### ISSUE TITLE
GeoSearch Lat Long Regex tests are broken

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3178]
Currently it looks like the only pattern that geosearch will recognize is `<number> <number>` for decimal degrees.

The comments beside the regex strings suggest we should be able to delimiters in decimal degrees, like `<number>, <number>` or `<number>; <number>`

And the DMS regex appears to not match anything.  Should pick up `<deg> <min> <sec> , <deg> <min> <sec>` (with varying middle delimiter)

**Comment by bkutty** [comment]
Tested the fix on http://fgpv.cloudapp.net/demo/v2.6.0-b3/prod/samples/index-fgp-en.html.
Works fine except for 1 issue identified in IE similar to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2533
