### ISSUE TITLE
Metadata shows two email addresses

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3180]
E.g. Sample 6 metadata shows

```
Contact Information
Nathalie Trudeau

Government of Canada; Environment and Climate Change

Director, Information and Indicators

Nathalie.Trudeau@ec.gc.ca
Nathalie.Trudeau@ec.gc.ca
```

and the raw email in the `mailto` hyperlink is  (where `%0A` is a linefeed character)
```
%0A                    Nathalie.Trudeau@ec.gc.ca%0A                    %0A                      %0A                        Nathalie.Trudeau@ec.gc.ca%0A                      %0A                    %0A                  
```

The XML template uses the `electronicMailAddress` node to populate this field. 
The metadata source has the following in that node

```
<gmd:electronicMailAddress xsi:type="gmd:PT_FreeText_PropertyType">
  <gco:CharacterString>Nathalie.Trudeau@ec.gc.ca</gco:CharacterString>
  <gmd:PT_FreeText>
    <gmd:textGroup>
      <gmd:LocalisedCharacterString locale="#fra">Nathalie.Trudeau@ec.gc.ca</gmd:LocalisedCharacterString>
    </gmd:textGroup>
  </gmd:PT_FreeText>
</gmd:electronicMailAddress>
```

So looks like the metadata is including a French version of the email as a child element.  After we strip out the XML tags for display, we get the double item.

Will probably need to enhance `xstyle_default_i18n.xsl` to deal with these child elements.

**Comment by AleksueiR** [comment]
Is it possible for the French version to be different? If so, instead of modifying the `xsl` to drop the French email, we can remove duplicate email addresses in the template.

**Comment by mweech** [comment]
i believe emails are generally suggested to be bilingual, but my guess are there are outliers in the metadata records.

**Comment by spencerwahl** [comment]
After a lot of working with the xls file... I can't get it to select only one of the email addresses.

The mailto link is fixable by changing it to 
```
<a href="mailto:{//gmd:pointOfContact//gmd:electronicMailAddress/gco:CharacterString/text()}?Subject={//gmd:identificationInfo//gmd:title/gco:CharacterString/text()}">
```

but all attempts at displaying only one email address failed, didn't make it to the point where we'd be selecting on language.

**Comment by AleksueiR** [comment]
Seems like the French xsl was lost in time: https://github.com/RAMP-PCAR/RAMP-PCAR/tree/master/src/assets/metadata

**Comment by spencerwahl** [comment]
Have the french xsl back, chooses between them based on current language. Also, mailto link fixed.

Still have the double displayed email addresses, seems like it may be an issue with chrome's XSLT processor... it works on an xslt tester.

**Comment by spencerwahl** [comment]
End result of this issue; mailto link fixed, french xsl is back,

Opening a new issue to keep the double email address display logged.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. Sample 6.
The correct email address is opened in Outlook.
