### ISSUE TITLE
No matter which custom symbol in legend is clicked on to enlarge, last image in symbologyStack is enlarged.

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3183]
Snip of structured legend used in testing with  2.5.0:
`

	children": [{ 
		"layerId": "Small-scale and distributed generation***SmallScaleandDistributedGeneration",
		"symbologyStack": [{
			"image": "../images/legend/piecharts.png",
			"text": ""
		}, {
			"image": "../images/legend/smalscaletable.png",
			"text": ""
		}]
	}]

`

![customsymbolsinstack](https://user-images.githubusercontent.com/2006029/49836566-21807a80-fd71-11e8-93bd-d621940b41a6.gif)

**Comment by james-rae** [comment]
Have traced it to here:

[this code](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.6.0-b1/src/app/ui/common/expand-image.directive.js#L39) seems to run correctly when the legend is built.  Both times when it executes, `imageUrl` is undefined and gets set with the correct image path.

[this event handler](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.6.0-b1/src/app/ui/common/expand-image.directive.js#L82) however always has the value of the last item in `imageUrl`.  I don't know angular well enough to know if it should be creating instances of this service for each magnifier button, or if there is only one and we have our variable in the wrong spot (i.e. there is only one `imageUrl` var for all buttons).  Could be just a matter of changing the magic constants in the `directive` object? Maybe the linking between the html template and directive is off?

Anway passing it on to someone who understands angular.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. Sample 87.
Testing failed because the test sample (Sample 87) does not have an icon for "Full -size image".

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5 
For testing requires a sample of at least two symbols with the possibility of enlarging.
Sample 87, has only one currently.

**Comment by james-rae** [comment]
Thanks Yaro. 
We just did a local test with 3 large pics just to double check the edge cases (a good suggestion).
The original issue would trigger with just one picture expanding, as long as it wasnt the last. 
We're comfortable for release, and will improve the quality of the test pages in a future release.
