### ISSUE TITLE
RAMP fails to download exported image when EDGE in use.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3184]
Tested with version 2.6.0-b1.
 RAMP fails to download exported image when EDGE in use. No problem with IE,Chrome or FF.
![bs_win10_edge_18 0](https://user-images.githubusercontent.com/38046459/49881134-9ac4af80-fdfb-11e8-8b44-adc38d9e6652.jpg)

**Comment by AleksueiR** [comment]
The error message says `toBlob` is not supported. A missing polyfill?

**Comment by AleksueiR** [comment]
Ok, polyfill.io lists Edge as having native `toBlob` functionality and the polyfill is not supplied. It can be forced with a `|always` flag on the url, but this is an overkill.

Edge (and event IE11) have this native implementation, but this was not acknowledged by polyfill.io until Edge/IE version 15 (green means native support):
![](https://i.imgur.com/FberODG.png)

However, if you run polyfill.io live tests, Edge comes up as needing the polyfill after all (screenshot from Edge):
![](https://i.imgur.com/Wh7RAFY.png)

It transpired the Edge's native `toBlob` function is prefixed as `msToBlob`: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/htmlcanvaselementtoblobmethod/?q=canvas

Even more, `msToBlob` is a synchronous function as opposed to the standard `toBlob`; it doesn't accept a callback and returns the blob value directly.

**Comment by YaroRoodzit** [comment]
Tested build v.2.6.0-b2.
Issue resolved .
