### ISSUE TITLE
Config column widths not being respected

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3193]
It appears the `width` config option for table columns is not being used.

[Schema definition](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.6.0-b2/schema.json#L503) (also, this description should be updated to indicate the unit of the width; probably pixels)

Code that [calculates widths](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.6.0-b2/src/app/ui/table/table-default.directive.js#L322).

Sample 37 has a config with [widths set](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.6.0-b2/src/content/samples/config/config-sample-37.json#L97)

**Comment by mweech** [comment]
Word wrap not applying still

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5 . Sample #37.
Issue solved.
