### ISSUE TITLE
Fullscreen will not exit in Chrome

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3194]
You can enter into fullscreen, but cannot get out.  Buttons and `Esc` key are disrespected.

Fix found by @spencerwahl  was to update `screenfull` library from `v3.3.2` to `v3.3.3`

**Comment by bkutty** [comment]
Tested successfully this fix on  http://fgpv.cloudapp.net/demo/v2.6.0-b3/prod/samples/index-fgp-en.html.

**Comment by bchagnon** [comment]
Although exiting full screen works now with this fix, it generates a console error in v2.6.0:

`
screenfull.js:98 Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
request @ screenfull.js:98
toggle @ screenfull.js:108
p @ full-screen.service.js:109
(anonymous) @ full-screen.service.js:59
(anonymous) @ angular.js:20821
h @ angular.js:6439
(anonymous) @ angular.js:6718
setTimeout (async)
i.defer @ angular.js:6716
a @ angular.js:20819
h @ full-screen.service.js:58
screenfull.js:98 Uncaught (in promise) TypeError: fullscreen error
    at Object.request (screenfull.js:98)
    at Object.toggle (screenfull.js:108)
    at p (full-screen.service.js:109)
    at full-screen.service.js:59
    at angular.js:20821
    at h (angular.js:6439)
    at angular.js:6718
request @ screenfull.js:98
toggle @ screenfull.js:108
p @ full-screen.service.js:109
(anonymous) @ full-screen.service.js:59
(anonymous) @ angular.js:20821
h @ angular.js:6439
(anonymous) @ angular.js:6718
setTimeout (async)
i.defer @ angular.js:6716
a @ angular.js:20819
h @ full-screen.service.js:58
focus-manager.js:715 focusManager *stopPropagation* is disabled on elements inside or part of the viewer
`
