### ISSUE TITLE
File Based Layers have Snapshot Option

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3197]
File based layers have all their data cooked into the layer, so they are technically always in Snapshot mode.  Currently, file based layer will have the Snapshot Mode `Enable` button active in it's settings panel.

1. Ensure file layers are being set to snapshot when they are made.  If they're not, making it so may be all that is required for this issue.
2. If Snapshot Mode option is still available, look into the UI code for the settings panel to fix the button disabling logic

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5
Issue solved.
