### ISSUE TITLE
Investigate vulnerablility in macaddress library

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3202]
NPM has marked this as a critical vulnerability. See https://nodesecurity.io/advisories/654

We are importing `macaddress` via these two libraries
`optimize-css-assets-webpack-plugin`
`css-loader`

See if we can mitigate by following the advice in the advisory, or by updating or changing the libraries

**Comment by milesap** [comment]
PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3206 brings macaddress to the patched 0.2.9 version.
