### ISSUE TITLE
Console error when exiting Fullscreen in Chrome 

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3215]
See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3194#issuecomment-452331644

Not a critical issue, but good to have the console clean.

If the root problem is caused by the `screenfull` library, we may need to watch the repo and update our version when they patch it.

**Comment by JahidAhmed** [comment]
May have been fixed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3352

**Comment by YaroRoodzit** [comment]
Same issue with IE.
Errors in the console when you press Esc to exit full-screen mode.
![image](https://user-images.githubusercontent.com/38046459/58963483-416e8500-877b-11e9-9910-d403f40405bf.png)

**Comment by james-rae** [comment]
This error message appears to be something different (looks like panel API, not the `screenfull` library).  

Have created new issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3560
