### ISSUE TITLE
API Legend #7: Wire in Panels API Settings, Metadata, Datatable

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3221]
**NOTE: Cannot be implemented until Settings, Metadata and Tables are ported over to `Panels API`**

 Make sure on BOTH `LegendItem` and `LegendGroup`:
- `toggleSettings`
- `toggleMetadata`
- `toggleDatatable` 

functions are are wired in to the correct panels once everything is ported over to `Panels API`

**Comment by mweech** [comment]
Unblocked as dependencies are now in QA.
