### ISSUE TITLE
API Legend #8: -  Ability to set LegendItem and LegendGroup ids through config

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3222]
Current `LegendItems` and `LegendGroups` get an auto-generated id (for example `node_1` or `group_5`)
 
We should have an option to set IDs for these through the config. This solves the reload case, where we lose track of the `LegendItems` and `LegendGroups` we are referring to because of constantly changing IDs.

**Comment by AleksueiR** [comment]
What if we auto-generate ids from layer/group names legend items belong to?
