### ISSUE TITLE
API Legend #11: Get click observable to return a LegendItem/LegendGroup

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3225]
We currently have a [click observable](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/legendAPI/api/src/legend.ts#L107) that fires every time a `LegendItem` or `LegendGroup` is clicked. 

Change it so that it returns the corresponding `LegendItem` / `LegendGroup` every time it is fired.

Click observable example: http://fgpv.cloudapp.net/demo/v3/dev/samples/api/legendTests/ConfigLegendTests/visibility-click-tests.html

**Comment by JahidAhmed** [comment]
Looks like this was done somewhere along the way and a `LegendItem` is correctly returned.

However, `LegendGroups` aren't returned since there's an explicit check in place to see whether the clicked item is not a group, so the observable isn't fired for those.
