### ISSUE TITLE
EnhancedTable #15: Attributes not Populated on Table Reload 

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3235]
1. On table reload, in `toc.service.js`, the function `reloadBoundLegendBlocks` fires the [_tableToggled](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3231/files#diff-9a8e1a13d9871e3f8b6d3e57d750af4fR197) observable

2. The table [reacts to this](https://github.com/fgpv-vpgf/plugins/pull/36/files#diff-13aa79c42d44c580a4f286f8f28db5b2R65) and [simulates a table click](https://github.com/fgpv-vpgf/plugins/pull/36/files#diff-13aa79c42d44c580a4f286f8f28db5b2R77)

3. This [closes the previously open table](https://github.com/fgpv-vpgf/plugins/pull/36/files#diff-13aa79c42d44c580a4f286f8f28db5b2R27), and attempts to repopulate and reopen the table with the [newly reloaded layer data](https://github.com/fgpv-vpgf/plugins/pull/36/files#diff-13aa79c42d44c580a4f286f8f28db5b2R43)

However the attributes array never gets repopulated, meaning the table never reopens on reload.

**Comment by dane-thomas** [comment]
After discussion with @james-rae it was decided to just close the table after reloading the layer rather than reopening after closing since there isn't usually a case where reopening the table is _required_

**Comment by dane-thomas** [comment]
Was able to debug the issue with reopening the table.

The table will now close and reopen on layer reload.
