### ISSUE TITLE
Enhanced Table #18: Print Function Results in Cut Off Pages, Stubborn Dialog Box

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3238]
Print Dialog in question:

<img src="https://user-images.githubusercontent.com/25359812/51142042-ced72a00-1818-11e9-9fc5-21c27e9e8126.png" height="200px">

## Steps to reproduce
 
- Open *Electric Transmission Line* datatable [here](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=29) (or any datatable with lots  of columns)
- Open menu, click on *Print* 
- You will be redirected to a page with a print dialog box below which there is a html datatable
![image](https://user-images.githubusercontent.com/25359812/51142145-1493f280-1819-11e9-8584-58f842555807.png)

### a) Default Printout
If you hit "OK" to print the datatable: you will get a printout that 3-4 columns maximum per page. The rest of the datatable's columns are cut off entirely (they do not show up on the next page).

![image](https://user-images.githubusercontent.com/25359812/51142735-bbc55980-181a-11e9-9024-ceeb743d3f2d.png)

### b) Printing Landscape
Printing in landscape mode to Adobe sometimes makes first few rows of table look funky
![image](https://user-images.githubusercontent.com/25359812/51142829-f4653300-181a-11e9-8e44-5cf2d1d95c51.png)

## Problem 2: The Dialog Box

- The print dialog box won't let you copy the contents of the html table behind it (which might be useful). 
- Clicking *cancel* on the dialog box shuts down the page entirely and takes you back to the map
- The print dialog box will show up by default so there is no option to prompt it

## Ideas for Improvement
- New idea for printout to include all columns (best)
- Don't automatically show the print dialog box, just show  HTML page behind it letting user copy/paste contents and dealing with the actual printing themselves

**Comment by mweech** [comment]
I do not get a strong sense that this is a well used feature.  Many people find it surprising that the datagrid exists, let alone printing from it directly.  At the same time, the export feature would allow someone to pull a table into Excel and export as they would see fit.

Another thought, would be to instead have the ability to open a "print friendly" version of the datagrid.  Perhaps a scrollable panel that opens and uses a straight HTML formatted table?

**Comment by mweech** [comment]
The real issue is the potential for the datagrid to have more data than can be reasonably fit onto a piece of paper.  ag-grid does a reasonable enough job of trying to do this export, however it will frequently provide undesirable output unless the map is specifically tailored to only show a reasonable number of columns.  Based on the fact that most maps will not reasonably fit into a printer-friendly width, this feature should be changed to DISABLED BY DEFAULT.  A map author can then enable the print feature if they deem the data table can fit the constraints.
