### ISSUE TITLE
Config Discussion: plugins

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3256]
This issue is to finalize what plugin configs belongs in the ramp config (proper - schema validated) and what should be either external or in its own section.

The `enhancedTable` plugin currently consumes the ramp config and reads from the [tableNode](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/56a57621b39c86ffa020d8d7e58d67084c57ac9e/schema.json#L439) section. Things like `applyMap`, `lazyFilter`, and `maximize` make sense for this plugin but not necessarily for simple table or a third party plugin. The user may be setting these options expecting them to work when the plugin implementation ignores them. Plugins may also have their own unique config requirements.

## General plugin config

The following applies to all plugins.

### Plugin configuration through ramp config

Here the ramp config should have a section called `pluginConfig` which is an object of `pluginName : configObject` pairs. 

```json
"pluginConfig": {
  "myPlugin": {
    "showDistanceToMoon": "Ney"
  }
}
```

Plugin configs found in this section of the ramp config do two things:

1. Ramp will load a plugin called `myPlugin`. You would not need to specify this plugin on the map element under `rv-plugins`.
2. It will pass the `myPlugin` config object to that plugins `preInit` method as a first argument (and the complete config as the second).

This section is not schema validated (section is defined as `any`).

### Plugin configuration through data attributes on script tag

This method involves setting `data-*` attributes on the script tag that loads the plugin. 

`<script src="myPlugin.js" data-showDistanceToMoon="Ney" />`

Ramp gathers these attributes and passes them as a config object to the `preInit` function of the plugin. Users would need to register the plugin on the ramp elements `rv-plugins` attribute.  

## Intention (replaceable ramp features) config

This section is for ramp features which are plugin replaceable or for plugins themselves (intentions).

### Minimum required config

This idea is to define a set of configuration parameters that are required to be implemented by both the default ramp functionality and any plugins that wish to replace the default functionality. While we wouldn't enforce this at runtime, the docs would be clear about this requirement. If a plugin fails to implement a required config option it is deemed a bug with the plugin.

If the plugin has additional config requirements we can either:
- Allow them to be added in addition to the minimum requirements
- Have them defined in the `pluginConfig` section, and both sections are merged and passed to the plugin.

### Strictly pluginConfig

All plugin configuration is in the `pluginConfig` section. If there are required config options ramp will check if they are defined at runtime or throw an error.

## Solution

I generally support the **Plugin configuration through ramp config** for all plugins and **Strictly pluginConfig** for intentions since it:
- keeps a plugins config in one place
- keeps all ramp related configuration information in one central place

Any thoughts, ideas, suggestions are welcome. The above assumes a map author has modify access to both the host page and the configuration, if this is not always the case let me know.

**Comment by james-rae** [comment]
Tend to agree with your solution rationale. 
I lean towards the `pluginConfig` as it will let a 3rd party do whatever they wish in their own project and we simply don't need to worry.
Having the special "intention plugin" (or whatever they are called now ; things like `table` that have special access to the core beyond what is exposed via the API) have config elements in config proper seems like a reasonable exception.

**Comment by mweech** [comment]
Think the idea of having a named section for each plugin works well.  Naming may become interesting, and wonder if we should allow for some kind of namespace.  i.e. eccc.FancyDrawingTool vs nrcan.FancyDrawingTool. 

Intentions.. Like the idea of merging plugin config snippet with the same name into the regular config block for that component.  we may want to declare a limitation whereby duplicates in the plugin block are ignored or something like that to avoid the core intention being mistakenly messed up by rogue plugin config snippets.  

Otherwise, if you want to keep intention config contiguous (easier to write/maintain), then we should differentiate intention config blocks vs plugin config blocks easily.  I think this ties back to having a  namespace  i.e. rv.intention.Grid, rv.intention.GeoSearch, etc

**Comment by milesap** [comment]
Solution:

Allow a non schema validated section of the ramp config named `plugins` to contain `pluginName: pluginConfigObject` key value pairs. A plugin receives it's config snippet as a first parameter to its `preInit` method (if defined).

Solution has been merged into v3 branch with PR **https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3264**
