### ISSUE TITLE
Enhanced Table #20:  Minor Table Bugs, Post Integration Cleanup

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3263]
Edited because some previous problems were fixed after pulling: https://github.com/fgpv-vpgf/plugins/pull/41. 

### **Bugs**

1. **Filtering numbers using a text column filter doesn't work**
![image.png](https://images.zenhubusercontent.com/5aea0e2a4b5806bc2bd18707/41afa2ab-9bd4-4f9c-983f-f0a125ea382f)

2. **Only 13 datapoints are shown for Features Refinery on map when there are 155 records on table**
  - because column filter for `OIDs` is hidden, datatable doesn't detect the filter but  map does
  -  datatable needs to filter these 13 points on open to be synced with map

3. Fix `simpleTable` rendering under `enhancedTables`

4. Fix selector filter issue: 
- open `enhancedTable` with `selector`  that have default values
- clear filters
- close table
- reopen table
- table shows up as empty which is wrong

### Post Integration Work

- cleanup of legend.block/proxywrapper .definitionQuery . Ensure app is using modern channels for adjusting filters.
~~- look into renaming layerproxy property .filterState to .filter, and using something else to determine if filter flag is on.  Grid plugin will need to update it’s code to use new property name.~~

**Comment by james-rae** [comment]
Item 2: there are no aliases from WFS. Only can happen if they are defined via the config.

Item 3: looks wrong. just noting that all WFS/File fields are treated as `string` type, as they don't define a datatype

**Comment by ShrutiVellanki** [comment]
> * look into renaming layerproxy property .filterState to .filter, and using something else to determine if filter flag is on.  Grid plugin will need to update it’s code to use new property name.

came from [this]() comment on `legend-block.class.js`

however

`this.filterState.isActive( )` may not be the best for setting filter flags on map load. 
- It is not too reliable because its parents states (from `AttribFC` or `DynamicFC`) are still in `rv-loading` or `rv-refresh` before map load.
- When I tried using  that instead of `this._layerConfig.filter` (which is definitely there before `rv-loaded` some filter flags DID show up while others didn't
- `get filter` seems to be used only on first map load (after that filter flag is controlled via set filter on tables plugin)...from what I found it is being called in two places:
   - [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8abc131639f98a5a647de3685f485130c83593b3/src/app/ui/toc/legend-control.directive.js#L67) ...isVisible calls it in the if statement, and multiple places in legend.service.js like [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/geo/legend.service.js#L792)
   - this mean that porting it to `this.filterState.isActive()` would not be beneficial for its usecase
