### ISSUE TITLE
Enhanced Table: Extent filter doesn't apply on table open

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3267]
When filter by extent is enabled, the table is not filtered by extent immediately after opening. 
After the map is panned the table is filtered by extent.

**Comment by ShrutiVellanki** [comment]
Sorry I didn't notice this and made an issue for this by accident which I now closed: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3270

That being said I *think* you may be talking about two separate things.

-  Point one on the linked issue refers to *filter by extent* being enabled on a table by default. It was probably a left over of a previous table's *filter by extent* being checked. 
     -  I don't think tables should have that checked on table open, because as far as I know, there is no option for it in the config.
    -  I also don't think tables should have *filter by extent* checked just because it was enabled on the previously opened table... at least that wasn't the behaviour on `v2.6.0`
-  Point two on the linked issue refers to *filter by extent* not updating the table when enabled unless the map is zoomed/panned

I hope this makes sense. Let me know if you have any questions.

**Comment by dane-thomas** [comment]
Alright, thanks for the details :+1: 

I think the first point you mentioned is slightly different than the original point but also a relevant bug. 
It should be applied on open if filter by extent is enabled on an open table, that table is closed then reopened. (All the same table)

I missed your second point in the issue. It should filter the table by extent right as it's enabled on the table. Will add that fix as well. Thanks!
