### ISSUE TITLE
Support for selecting amongst different WMS styles

### ISSUE THREAD

**Issue by alexandreleroux** [fgpv-vpgf/fgpv-vpgf#327]
Feature request: if a WMS layer has multiple styles in its GetCapabilities, the ability for the user of the FGPViewer to select a different style than the default one. Thanks -- Alex

**Comment by AleksueiR** [comment]
Is it possible to switch the style after the layer loaded?

**Comment by alexandreleroux** [comment]
@AleksueiR This is not possible as far as I can tell in the current version. This is what this feature request is about.
