### ISSUE TITLE
Full screen yo-yo effect

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3291]
Cannot exit full-screen mode in Chrome.

Steps:
- open prod sample
- click "Full screen" from the side menu
- observe the map full-screen
- click "Full screen" again to exit
- observe the map existing the full-screen mode and switching back to it
- click "Full screen" again to exit
- you cannot get out (sometimes pressing Esc or F11 helps)!

Bug found on latest develop and v3 branches.

**Comment by james-rae** [comment]
Possibly related / helpful: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3194

**Comment by AleksueiR** [comment]
Could be, but that bug was fixed by upgrading the screenful library; this happens after the upgrade (unless upgrade was never done in the first place).

**Comment by james-rae** [comment]
Upgrade was done.  But there was a time ramp worked prior to having that update.  Maybe we need another update? [Waves hands around].

**Comment by AleksueiR** [comment]
We are using the latest version of screenful - 4.0.0 (https://github.com/sindresorhus/screenfull.js/releases).

This issue might be related: https://github.com/sindresorhus/screenfull.js/issues/121

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. 
Problem solved.
