### ISSUE TITLE
Grid Title is mis-aligned in basic grid

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3300]
[Test page](http://fgpv.cloudapp.net/demo/v3.0.0-b1/prod/samples/index-fgp-en.html?keys=JOSM).  Open the grid to see it.

![gridtitle](https://user-images.githubusercontent.com/7585245/53037734-f8ebbf80-3448-11e9-9a46-ce945910f1e2.jpg)

**Comment by spencerwahl** [comment]
WET styles are pushing the title down with a margin. Simplest solution is probably override the `margin` and adjust `top` as needed, this *should* make it consistent between WET and non-WET pages.
