### ISSUE TITLE
WFS Import Wizard does not present customization options

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3301]
Upon hitting step 3 of the import wizard for a WFS service, we get presented with a warning about the browser being unresponsive while the layer loads.

But then the standard choices to select Layer Name, Name Field, Symbol Colour, etc, are not presented.

If possible, the wizard should attempt to provide that choice.  Might involve having a pause between downloading the geoJson and converting the geoJson to a local ESRI feature layer, and inspecting the geoJson to extract a list of field names

**Comment by mweech** [comment]
May need to push addition of WFS support to 3.1.  TBD.

**Comment by AleksueiR** [comment]
Is this issue is removed from v3.0, the `5.1.5` section of the UI breakdown doc will need a cleanup or a note saying "Coming soon, in v3.1".

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. 
Service used for test : https://geo.weather.gc.ca/geomet/features/collections/ahccd-trends/items?measurement_type__type_mesure=temp_max&period__periode=Ann&startindex=0&limit=1000
Proper options are available to user in the 3rd step of the wizard.
Issue resolved.
