### ISSUE TITLE
Geo search in v3 no longer support lat/long lookups

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3303]
This functionality is available in [v2.6](http://fgpv.cloudapp.net/demo/v2.6.0/prod/samples/index-samples.html).

A lat/long search should result with a list of results in vicinity of the entered coordinates; the first result should be a shortcut to these coordinates.

![](https://i.imgur.com/NVzirog.png)

**Comment by YaroRoodzit** [comment]
Tested build: v.3.0.0-b2
Not fixed yet.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
