### ISSUE TITLE
Global Table Search not tied to Clear Filter

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3305]
The global search box in the enhanced table has an `X` clear button in it.  There is also a button on the grid button bar called `Clear Filters`.  

The button does not clear the global search field, and will not enable if only a global search is on.  We experienced some confusion after clicking the Clear button and then our grid was still filtered.

Suggest either having the Clear Filters button also clear the global search box, or change the name of the clear filters button to something like `Clear Column Filters`

**Comment by AleksueiR** [comment]
The `Clear Filters` buttons should also reset the global search box and it should be enabled when just the global search keywords are entered.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Issue resolved.
Placing text in the global search field activates the "Clear Filter" button. Clicking the "Clear Filter" button clears the global filter.
