### ISSUE TITLE
Permit GeoSearch to rank results based on type

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3307]
The Minister's Office has requested a ranking of geosearch results in support of the Climate Action Map. 

Use case: Search for the city of Ottawa. You will have to sift through dozens of results with "Ottawa" in the name, before you find the City of Ottawa. This issue would result in ensuring population centers would display higher in the search results within the RAMP-based application. 

The proposed ranking could look like this:

1. City
2. Hamlet
3. Indian Reserve
4. Lower Tier Municipality
5. Other Municipal District Area – Major Aggregate
6. Other Municipal District Area – Miscellaneous
7. Province
8. Single Tier Municipality
9. Territory
10. Town
11. Upper Tier Municipality
12. Village
13. Unincorporated place
14. All other results. 

### Implementation Details
- [ ] Configuration schema is updated with new options
- [ ] Modify Geosearch queries to filter results
- [ ] Sort Geosearch results
- [ ] Update Help and RAMP documentation

### Acceptance Criteria
1. RAMP configuration options for Geosearch will be added to support both the definition of a limited subset of categories, as well as defining an initial prioritization of search result categories following:
    - "categories" (not required) which will define the arguments that map to the "concise" parameter of geogratis: http://geogratis.gc.ca/services/geoname/en/codes/concise
    - "sort-order" (not required) which will define the sort order of defined "categories". If a category is missing from the "sort-order", it will be appended to the bottom of the sorted list.  A "sort-order" can be defined without limiting results via "categories"
    - "official-only" will be a boolean that would map to the "category" parameter of geogratis
2. Geosearch results will be limited to 1K results based on geogratis service limitations
3. "Theme" parameter will not be supported at this time.
4. Sorting of results will take place while processing results from Geogratis service and be considered tied to the service being queried. A generic search results sorting function is not required.
5. Help documentation has been updated
6. RAMP Documentation has been updated to reflect changes

**Comment by AleksueiR** [comment]
The results can be sorted by feature type adding `&sort-field=concise`:
http://geogratis.gc.ca/services/geoname/en/geonames?q=toronto&sort-field=concise

But this doesn't let you specify your own sorting order.

If we are simply getting all the geogratis results upfront, we can easily sort them on the front end though.

**Comment by milesap** [comment]
To keep geosearch ramp agnostic I'm thinking we sort within ramp. The returned `resultObject` (https://geosearch-docs.fgpv-vpgf.com/v2.0.3/#/demo1?id=resultobject) provides a `type` property to sort on. 

Estimate is around a `5`

**Comment by AleksueiR** [comment]
What is the default cap on the number of returned items? Should we try to grab as much as possible for better sorting on the client then?

**Comment by spencerwahl** [comment]
Default is 100, max is 1000

**Comment by milesap** [comment]
You can up the result count when you initialize geosearch as well https://github.com/RAMP-PCAR/geosearch/blob/master/src/definitions.ts#L9

**Comment by AleksueiR** [comment]
How hard would it be to make additional requests and grab all the results, if there are more than 1k of them? Or is 1k enough?

**Comment by mweech** [comment]
Here is an example of a Toronto search filtered to just the items listed and the Official names, to eliminate the weird results: http://geogratis.gc.ca/services/geoname/en/geonames?q=toronto&concise=CITY,HAM,IR,LTM,MUN1,MUN2,PROV,STM,TERR,TOWN,UTM,VILG,UNP&sort-field=concise&category=O

I would move this is a pretty good model for what a user would expect as result... is this maybe an acceptable trade off?

**Comment by mweech** [comment]
Also, theme based on Populated Areas: 

http://geogratis.gc.ca/services/geoname/en/geonames?q=ottawa&sort-field=concise&theme=985

**Comment by milesap** [comment]
I'll change my vote in favor of sorting/filtering on geosearch by passing it a list of result types such as `[CITY, HAM, PROV, TERR, TOWN, UTM, VILG, UNP]` and an official results only flag. For themes, maybe allow the codes as well as some predefined theme names which get converted to theme id's so it's more use friendly.

**Comment by milesap** [comment]
Discussion thread opened: https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/14

**Comment by JahidAhmed** [comment]
Just wanted to provide a progress update; the implementation of the RAMP configuration options, along with the actual filtering and sorting, are complete. Just the documentation remains to be updated, and then final testing before opening a pull request.

**Comment by dan-bowerman** [comment]
Fantastic! Can you share a snippet of how the config might look?

**Comment by JahidAhmed** [comment]
Hi @dan-bowerman! Here's an example:
```js
"search": {
      "settings": {
        "categories": [ "CITY", "HAM", "IR", "LTM", "MUN1", "MUN2", "PROV", "STM", "TERR", "TOWN", "UTM", "VILG", "UNP" ],
        "sortOrder": [ "UTM", "HAM", "TERR", "IR", "UNP", "TOWN"],
        "maxResults": 1000,
        "officialOnly": true
      },
      "disabledSearches": ...,
      "serviceUrls": {
        ...
      }
}
```
There is a `settings` object which will contain any geosearch related configurations, and this all goes inside the main `search` object, alongside the already existing `disabledSearches` array and `serviceUrls` object.

The 4 options shown above are all optional and more detail about how they all work can be found inside the discussion thread located [here](https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/14) or the `Acceptance Criteria` in the issue description above!

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b2
Tested sample: 89
Works as expected.
