### ISSUE TITLE
Size of search text is cutoff within data grid

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3309]
Tested with build:v3.0.0-b1

When tested data grid using this version, size of search text is cut off. This issue is applicable to only IE 11. For Firefox and google chrome it works fine. Refer to screenshot below.

![search text](https://user-images.githubusercontent.com/46937257/53265153-83335e00-36ab-11e9-926f-b5dec7106815.JPG)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Not fixed. Same issue.

**Comment by james-rae** [comment]
Fix included in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3294 , will re-test in `-b3`

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
