### ISSUE TITLE
Preserving Extent during Projection Change

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3316]
We use the bookmark (version `B`) to preserve state when doing a projection change. The bookmark encodes the center point and map scale. Upon arriving in the new projection, we set the center, then find a scale in the new schema that is closest to, but not greater than, the bookmark scale.

@yaroroodzit noticed that in certain scenarios, the new extent will be omitting areas that were in the old extent, even though the scale was lower after projection change.

View in Lambert (Scale `1:2,000,000`)

![mapproj_lambert](https://user-images.githubusercontent.com/7585245/53439657-8b074100-39d0-11e9-9517-e2fc17cfae13.jpg)

View in Mercator after reprojection (Scale `1:2,311,162`).  Purple polygon represents the Lambert extent

![mapprojmercator](https://user-images.githubusercontent.com/7585245/53439672-935f7c00-39d0-11e9-942f-9900c63ddece.jpg)

Zoomed out view in Mercator showing all of the Lambert extent.

![mapprojmercatorzoom](https://user-images.githubusercontent.com/7585245/53439683-9a868a00-39d0-11e9-8e79-22993b902908.jpg)

To solve, would require the bookmark to encode the entire extent and use the special extent projection algorithm.  May be advantageous to delay and include this in a full-state-storage solution rather than a modded bookmark. https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275

**Comment by mweech** [comment]
Extent after projection change is based on centre point of map (i.e. point of focus) and zoom level.  Maintaining extent would result in a larger zoom level change.   Although this might change the features that are in view, this is to be expected when changing projection (this is not an arbitrary switch).
