### ISSUE TITLE
Binding problem with "Coords Info".

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3318]
Tested with build : v3.0.0-b1
Steps to reproduce:
1. Load test URL:  http://fgpv.cloudapp.net/demo/v3.0.0-b1/prod/samples/plugins/coordInfo/coordinfo-index.html
2. Select "Coords Info" and click on map. 
![image](https://user-images.githubusercontent.com/38046459/53501610-7aaba080-3a7a-11e9-9e4f-d66daae14a8b.png)

**Comment by james-rae** [comment]
Worth noting the angular bindings will take effect after you move the mouse.

Good catch, Yaro

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2.
Issue resolved.
