### ISSUE TITLE
Language Change Bookmark Outside of Viewer

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3319]
Found by @YaroRoodzit 

[Test page link](http://fgpv.cloudapp.net/demo/v3.0.0-b1/prod/samples/index-fgp-en.html?keys=JOSM)

To reproduce:
1. Load above link
2. Click `Francais` at the top of the page (don't use the hamburger menu language change)
3. Wait for map to reload.
4. Uncheck visibility of Oil Sand layer
5. Click `English` at the top of the page.

When map reloads, Oil Sand layer will be visible again.

This only happens when using the external language control.  Using the internal hamburger menu is fine.
It could be a problem with how the test pages `index-fgp-<lang>.html` are interfacing with the api / new plugins.

**Comment by mweech** [comment]
Re-estimate following analysis.

**Comment by spencerwahl** [comment]
Update: bookmarks are correct, code that applies bookmark state to rcs layers is incorrect.

The bookmark has the old language's key i.e. `rcs.josm.en` and the new layer is `rcs.josm.fr` so it doesn't match correctly.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2.
Issue resolved.
