### ISSUE TITLE
The default choice for the Primary Field is not fully justified.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3325]
Tested with build: v3.0.0-b1
In the current version,the dropdown for the Primary Field is preselected with a value but logic behind this are not clear.
As a suggestion, maybe we should live the field empty and mark as user selection required.
![image](https://user-images.githubusercontent.com/38046459/53648285-867b9c00-3c0d-11e9-81d2-77ebf43831ec.png)

**Comment by mweech** [comment]
To be addressed with other User Added Layers issues..

**Comment by mweech** [comment]
Misunderstood this issue.  It's just an initial selection to save mouse clicks if possible.  Win some you lose some.
