### ISSUE TITLE
In the “Add Layer” section of the "Help" file, the creation of a CSV file and the use of Latitude and Longitude values ​​are insufficiently covered.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3326]
Tested build: v3.0.0-b1
In the “Add a layer” section of the help file, creating a CSV file and using latitude and longitude values are not described in detail and can cause confusion to the user.

**Comment by AleksueiR** [comment]
Can we reuse some of the [UI overview info on the layer wizard](https://gist.github.com/AleksueiR/03a27c47af53a51692645cef3eed171b#51-add-layer-layer-import-wizard) and add it to the Help?

**Comment by mweech** [comment]
I am not sure the help file should cover how to create a CSV file.  Perhaps it should detail any limitations...?

**Comment by mweech** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/210
