### ISSUE TITLE
Zoom to Feature fails in certain scenarios

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3331]
This has been around since `v2.1.0`

In certain scenarios, the "zoom to feature" will not work (from data grid or from details panel). Primarily, these are Dynamic Layers, or a server hosted Feature Layer in `on-demand` mode that doesn't have the target feature visible on the map.

However, in certain build scenarios, a global variable named `map` will be present (it seems to be linked to an svg item `g#map`, which contains the icon to open the basemap menu).  The presence of this global will mask the error if the layer is in a compatible projection (which it usually is).  This explains why the error went undetected for so long.

Solution is to fix a variable reference in geoApi - `map` to `opts.map` in `attribFC.fetchGraphic()`

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2.
Issue resolved. 
The map zoom function works correctly.
