### ISSUE TITLE
Enhanced table: UI fixes needed

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3338]
Some small tweaks for the table panel:

## 1. Header is not delineated
Material panels use a light-grey border to separate their headers from the body. The enhanced table is missing that.
![](https://i.imgur.com/M3DDzK0.png)

We also can move the number of records shown into the header as a subtitle:
![](https://i.imgur.com/VDLSqJY.png)

## 2. The table padding is inconsistent
Horizontal padding of the panel is much larger then vertical:
![](https://i.imgur.com/G2rvHm5.png)

The default padding value for panels is 8px. Try that first and see how it looks. The horizontal and vertical values might differ a bit, but the result should appear balanced. Something like this:
![](https://i.imgur.com/r24swDe.png)

## 3. Header icon-button are incorrectly sized
The default size of the icon-buttons is 40x40 px (see the icons in the main app bar). The size of the icon itself is 24x24 plus the 8px padding. Right now, table header icon-buttons are 36x32 and look bunched up.

![](https://i.imgur.com/8Fo9nYS.png)

Also, please add a vertical line between the search icon and the column selector button, like in the main app bar:
![](https://i.imgur.com/gTEIX7u.png)

## 4. The icon-button focus highlight is eccentric
When focused, the the icon and its ripple container are not centered (the ripple actually extends outside the button container):
![](https://i.imgur.com/X8kE2La.png)

The rippled container should be fully inside the button container and centered.
![](https://i.imgur.com/gzpLIkh.png)

## 5. The focus highlight on column reorder button looks odd
It's a small icon-button, so the ripple container is a circle, but the button itself is squashed squeezing the ripple as well (the ripple is offset as well). 
![](https://i.imgur.com/EwIOInP.png)

I think, in this case, it would be better to use a rectangular ripple container, like one used on the text buttons - it will match nicely the hover/focus effect on the column header button:
![](https://i.imgur.com/s1iMeFp.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Works as expected.
