### ISSUE TITLE
Enhanced table: panel menu closes on up key presses

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3342]
Trying to move through the menu items up using the keyboard causes the menu to close.

Steps:
1. Open the menu (either tab or click)
2. Press the down key to traverse the menu items 
3. Press the up 
4. Observe the menu closing.

![](https://i.imgur.com/4FwCmdT.gif)

Affected: v3

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Issue solved.
