### ISSUE TITLE
Enhanced table: cannot open the table before the layer is loaded

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3343]
On [the 2.6 sample page](http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html?sample=1), clicking on a layer before it's fully loaded immediately opens the table and starts loading/processing data:

![](https://i.imgur.com/n6UbmCc.gif)

On [the 3.0 sample page](http://fgpv.cloudapp.net/demo/v3/prod/samples/index-samples.html?sample=1), clicking on the layer before it's loaded does nothing. The table will only open after the layer is loaded.

![](https://i.imgur.com/w2VaGIf.gif)

v3 behaviour should match that of 2.6 and open the table right away, even if the data is not ready.

**Comment by ShrutiVellanki** [comment]
Update: 

:construction: :construction: :construction: :construction: :construction: 
@dane-thomas and I decided it would be more efficient for me to take care of migrating this to the new Panels API...so don't close yet! I've resumed working on this again 
:construction: :construction: :construction: :construction: :construction:
