### ISSUE TITLE
Issue while performing refresh for user added service layer   

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3345]
Tested with build:v3.0.0-b1

When I try to click on reload after setting up refresh interval, I noticed below issues:

1.	Data table automatically populate. Not sure if it is expected. (Happening for both IE 11 and Firefox)
2.	When you click on reload, setting window should be closed but it is not closing. (Happening for both IE 11 and Firefox)
3.	Drop down menu to increase interval is missing in IE when compared to fire fox. (Only IE 11)
4.	It seems like layer is not refreshing as the setting window does not close after clicking on Reload (Both IE11 and Firefox)

Steps to reproduce:

1. Use IE 11 or Firefox and set up refreshing interval for user-added service layer:                                                           http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/30
2. Click on reload after setting up refresh interval.

Screenshots:

IE 11
![schreenshot_ie 11](https://user-images.githubusercontent.com/46937257/54049410-6c603180-41aa-11e9-9f1b-9bba91f2d950.JPG)

Firefox:
![schreenshot_firefox](https://user-images.githubusercontent.com/46937257/54049430-78e48a00-41aa-11e9-9869-b31218562667.JPG)

**Comment by ShrutiVellanki** [comment]
Hello, 

So I used the same layer as you and set a refresh interval of `0.01`...it is easier to see the points refreshing with a smaller interval.

> 1. Data table automatically populate. Not sure if it is expected. (Happening for both IE 11 and Firefox)

This is expected

> 2. When you click on reload, setting window should be closed but it is not closing. (Happening for both IE 11 and Firefox)

I followed the same steps as you, and after pressing reload, settings closes and reopens for me. This is expected behaviour.

> 4. It seems like layer is not refreshing as the setting window does not close after clicking on Reload (Both IE11 and Firefox)

The layer is refreshing! You can see this with an interval of `0.01`, the dots will be blinking. 

> Drop down menu to increase interval is missing in IE when compared to fire fox. (Only IE 11)
This is correct, I'll verify if its worth adding and add it if need be.

**Comment by ShrutiVellanki** [comment]
Closing issue based on this conversation with @mweech 
![image](https://user-images.githubusercontent.com/25359812/55491266-2bb9d380-5603-11e9-9335-f069945fb832.png)
