### ISSUE TITLE
Console errors in `v3`

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3347]
The following console error appears for maps in [`index-samples`](http://fgpv.cloudapp.net/demo/v3/dev/samples/index-samples.html) as soon as map is loaded: 

![image](https://user-images.githubusercontent.com/25359812/54150455-e85ab380-440e-11e9-8ac9-580fbd9a07bf.png)

Following console error  appears whenever a layer is clicked on/table is opened in all demo samples: 
![image](https://user-images.githubusercontent.com/25359812/54150523-0fb18080-440f-11e9-82f7-726df9d2f3e7.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Issue solved.
