### ISSUE TITLE
Maximized table needs to go transparent on zoom when using details panel

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3348]
### Steps to reproduce on [`v3`](http://fgpv.cloudapp.net/demo/v3/dev/samples/index-samples.html):

1. Open a table by clicking on corresponding layer
2. Maximize the table
3. Click on details button on any row
4. Click on zoom button in details panel ([pictured here](https://user-images.githubusercontent.com/25359812/54151294-e2fe6880-4410-11e9-99fe-65ec36870b56.png)) or click on expand button ([pictured here](https://user-images.githubusercontent.com/25359812/54150973-21475800-4410-11e9-9ea0-fc3472dcb5b8.png)) to open details pop-up ([pictured here](https://user-images.githubusercontent.com/25359812/54151821-11c90e80-4412-11e9-84b8-50e3ee9a5f2b.png))
5. Click on zoom button on either one of these panels. You will notice that the table details panel does not go transparent behind it, so you are not able to see the zoomed in point unless you close the table.
- This works in [`v2.6.0`](http://fgpv.cloudapp.net/demo/v2.6.0/dev/samples/index-samples.html)
- Simply clicking on the zoom button in a maximized table's row activates this transparency even in `v3`

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Issue solved.
Table goes transparent when the map zoom activated.
