### ISSUE TITLE
Can't load non wfs service

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3358]
Trying to load a non wfs service (i.e. http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/30) fails with `Service does not respond`.

[Suspect line of code](https://github.com/ShrutiVellanki/fgpv-vpgf/blob/5a90730c7dfc0c03553b71be7a2eba6b4b9ebb97/src/app/ui/loader/layer-source.service.js#L91)
I think we just need a check to see f the url doesn't have `items` or `collections`.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Issue solved.
