### ISSUE TITLE
Define RAMP Accessibility Guidelines

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3359]
Draft a RAMP Accessibility Guidelines document that will be added to the RAMP Developer Documentation (#3257).  This is based on the initial discussion posted by @ShrutiVellanki here: https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/3

The guide should cover the following subjects and be declarative in nature:

1. Define general principles of RAMP that is aimed at accessibility.  i.e. providing alternative means to access feature based data and allowing identify actions to be accomplished via a keyboard
2. Define component groups, rules for ordering and cross map navigation
3. Describe and define guidelines for keyboard based navigation to ensure consistent usage between components
4. Hover Text/Labels; guidance on how to label items and provide alternative text

The guide should also seek to minimize describing the rationale for accessibility choices and instead should reference the guidelines being addressed with each choice.  This will assist with performance of accessibility checks and keep the guide brief and easy to follow.  

The guide should end with a summary matrix of the WCAG 2.0 AA guidelines (based on accessibility self-assessment tests we use).  The matrix will note the specific RAMP Accessibility guidelines that addresses it, or note that it is a "host page" responsibility.

**Comment by ShrutiVellanki** [comment]
Obligatory over a week update: 

- Markdown so far: https://hackmd.io/0ZK3ko89T-qjrMxunG_VBg?both
- Summary Matrix: https://hackmd.io/UUFAq9orSjGY4DKRgELjNQ
