### ISSUE TITLE
Convert Areas of Interest plugin to Panel API

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3363]
Convert the Areas of interest plugin to use the Panel API

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
- Fail to exit full screen mode. Problem exist in "Pictures Demo" page and "No Pictures Demo" page.
- Unnecessary scrollbar is displayed on "Pictures Demo" page. 
- No layer symbols are displayed  in menu for layer legend on "Pictures Demo" page.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
