### ISSUE TITLE
Convert enhanced datagrid plugin to use the Panels API

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3368]
Convert the enhanced datagrid plugin to make use of the panel API.  Will resolve https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3288

~~Loading screen also has to be separately converted to Panels API as well.~~

**Comment by dane-thomas** [comment]
> Loading screen also has to be separately converted to Panels API as well.

Will not be covered in https://github.com/fgpv-vpgf/plugins/pull/67 but in https://github.com/fgpv-vpgf/plugins/pull/61 since it seems like a lot will change in the migration

**Comment by dane-thomas** [comment]
Moved back to in progress as there are some small issues with the table opening on the [v3-panel-migration](https://github.com/fgpv-vpgf/fgpv-vpgf/tree/v3-panel-migration) branch after changes to the `panels api`.

**Comment by YaroRoodzit** [comment]
Tested build: v.3.0.0-b2
As expected.
