### ISSUE TITLE
Convert Geosearch to use Panel API

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3369]
Migrate geosearch to use the panel API.

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
- Search by coordinates are not available 
- No Help information available regard Geosearch 
- Province and Type filters drop-down list does not work. Stuck with message : Loading filters.

**Comment by ShrutiVellanki** [comment]
@YaroRoodzit , going to address your third point with this issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3448

**Comment by james-rae** [comment]
New issue for missing help documentation: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3449

**Comment by james-rae** [comment]
#3303 will cover the 3rd bullet point.  Next build will just re-verify that panel acts like proper panel, and use these other three issues to track the bugs listed above.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
