### ISSUE TITLE
Enhanced Table: Does not open for certain samples

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3373]
e.g. try and toggle a table open for sample 4, table won't open. 

This is the error in the console: 
![image](https://user-images.githubusercontent.com/25359812/54614965-adbad180-4a33-11e9-8688-84ab85190a2e.png)

Second error for sample 75: 
First layer sometimes won't open because `"Layer Proxy not yet resolved"`

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
- Resolved for Sample 4.  
- Sample 75. Tables can be opened , but errors displayed in console. 
![image](https://user-images.githubusercontent.com/38046459/56907605-9cbda100-6a72-11e9-92a1-1ef38b3355bc.png)

**Comment by JahidAhmed** [comment]
It seems the errors relating to the table are no longer a problem and the errors in Yaro's comment above 
look like they are unrelated to any table behaviour. It appears that the error is a result of a CORS issue with one of the image layers (Temperature) which is failing to load.

**Comment by james-rae** [comment]
Will be replacing layers over the summer when migrating to new QA pages (layers on our servers for stability).  Will consider this issue done.
