### ISSUE TITLE
Cannot tab through the context menu if the first item is disabled

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3378]
#### Steps:
- tab to the context menu where the first item is disabled
- click `Enter` to open the menu
- observe the focus not being set on the menu elements

#### Demo:

![](https://i.imgur.com/jGgEbpS.gif)

#### Affected
Latest dev and v3.

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
Keyboard navigation works correctly with  Sample 6.
