### ISSUE TITLE
Server Geometry Request Oversimplifies Result

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3379]
When fetching an individual non-point geometry from a service that is natively in a projection different from the basemap, we noticed the result was oversimplified (usually reduced to a triangle). 

Investigation shows the `outSR` parameter on the request to get the geometry was being improperly encoded; `"Object object"` instead of the stringified SR JSON.

Solution is to stringify the map spatial reference object as it's added to the web request

Fun fact: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2475 was likely the same issue, and possible the source service was migrated to a matching projection between logging and debugging.

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
Issue solved.
