### ISSUE TITLE
Documentation Enhancements

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3386]
### Requests from Mr Weech:

Overall Notes:
- Should review https://github.com/fgpv-vpgf/fgpv-vpgf/issues/839 for gaps to make sure they are noted and also to determine if some of those gaps could be easily filled with existing legacy documentation
- Update fgpv-vpgf/fgpv-vpgf page header to not use a sample link
- Repo readme.md page:
  - Remove code climate from README.md
  - Rename heading to RAMP2
  - Remove "Description" heading
  - Replace description text with: 
- The Reusable Accessible Mapping Platform (RAMP), also known as the Federal Geospatial Platform Visualizer (FGPV), is a JavaScript based web mapping platform that provides a reusable, WCAG 2.0 AA compliant common viewer platform for the Government of Canada.  
For more information on this project, please jump to one of the sections below:
    - Usage
    - Documentation
    - Building the Project
    - Support
  - Documentation section:
- Remove hyperlink from title
- Re-organize section to introduce the existence of comprehensive viewer documentation and then provide a main link to the root of the documentation site (https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/home).  Organize the sectin descriptions in a list as you have done to describe the content that will be available on the documentation site
- There is just a random "Interactive Schema Documentation" heading in the page under "Building the Project".. Should move up to documentation section
  - Update plugins and geoapi readme.md to point somewhere smart

Splash Page:
- Documentation
  - Link to RAMP Viewer Documentation HOME PAGE
- Samples:
  - Add a list of sites using RAMP with a short blurb, and a screenshot
  - Format as title with description below title and a screenshot on the right side
  - Also include a link to index-samples.html not just client projects or catalogue viewer links
  - All links should be externally accessible
- Github
  - Link to fgpv-vpgf/fgpv-vpgf page

RAMP Viewer Documentation (https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/)
  - https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/home
- Need to fix all pages to stop going to the splash page when clicking on “Home”
- Reuses README.md at the moment..
    - We should modify content to point to README.md for Usage/quick guide, support and building the project information
    - Page should predominantly just contain the RAMP description and then the Documentation summary
    - Need to give a high level overview of our docs navigation, i.e. the top bar changes depending on subsection, while the left is to navigate on the page your on
- Need to add the UI Overview to the Developer guide instead of leaving as stand alone
- The section https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/technical/architecture is missing
  - https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/developer/intro
- Home button needs to not go to splash page, but home page of docs
- INTRO page:
    - Should expand on ramp concepts
    - Some of the intro sections are a bit big (i.e. plugins and maybe API), reduce and fold content into their sections, and make sure each sections with a heading at the top is introduced at a high level on this page
- Shema-to-docs page should be referenced somewhere as a section as well
- Add UI overview to dev guide
  - https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/contribute/getting_started: 
- should we add quick start and support sections here from README.md…?
- how does this fit with repo contributing.md files
  - https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/mapauthor/intro
- Key concepts
    - Need to introduce the two key concepts being the assets necessary to run ramp and the deployment model choice… should also mention a map with plugins for custom development and note we WILL NOT COVER THIS IN THE MAP AUTHOR GUIDE
    - Include a simple block diagram from ramp presentation (shows page, script/config, etc..)
    - Align description here with contents of that simple slide view
- i.e. loading scripts
- Ramp RELEASE library copy
- Config file
- GEOSPATIAL DATAFILE,… this is the point!
- https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/mapauthor/custom_attributes
    - I know what custom attributes are for, but not sure if anyone new to the project would if they saw that page. Each page needs a contextual introduction
- https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/mapauthor/wcag_compliance
    - There is no title on the page
    - Should provide an example of each
    - Should maintain same header links as current map authoring section

### Additional things from Mr Rae	

Index.html title: `./docs`.  Enhance to better title

What url should our source code be pointing to?
- https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/ 
- https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3.0.0/#/
- https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/master/#/
The specific ones will mean doc site works while being worked on. But means an update needs to happen to the source every release. Master will always be most recent release, but difficult to test latest version of docs.

Remove the built in TOC of the UI guide, as docute makes one on the left of the page, and doesn’t appear to work either.

**Comment by AleksueiR** [comment]
> the top bar changes depending on subsection

Others might disagree, but I find the page-dependent top navigation confusing and distracting. 

I suggest to group all the sections into several major buckets displayed in the top nav, and used their dropdowns menus to provided direct access to individual sections, like it's done here with the API things:
![](https://i.imgur.com/jUBYz7T.png)

**Comment by mweech** [comment]
I completely agree with @AleksueiR .  I find the top navigation confusing which is why I was requesting some guidance on how to use it (since im :older_man: ).   But if a few people feel the same we should look at changing the navigation method.

**Comment by AleksueiR** [comment]
Here's my suggestion on the top navigation menu structure:

- Home `[v3/#/home instead of the splash page]`
- Overview`[v3/#/ui-overview]`
- Developer `[dropdown menu with sections]`
  - Guides
    - Introduction `[v3/#/developer/intro]`
    - Contributing `[v3/#/contribute/getting_started]`
    - Accessibility `[TBD]`
    - Plugin Development `[v3/#/developer/plugins]`
  - API
    - Overview `[v3/#/developer/api-overview]`
    - Panels `[https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/developer/panels]`
    - Layers `[???]`
    - Legacy API `[https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/v3/#/developer/legacy_api]`
  - Technical Documentation
    - Architecture Overview `[v3/#/technical/architecture]`
    - Interactive Schema `[https://fgpv-vpgf.github.io/schema-to-docs/]`
    - Annotated Source Code `[Technical JSDocs]`
- Map Author
  - Introduction `[v3/#/mapauthor/intro]`
  - Custom Attributes `[v3/#/mapauthor/custom_attributes]`
  - Details Templating `[v3/#/mapauthor/details_templating]`
  - WCAG Compliance `[v3/#/mapauthor/wcag_compliance]`
- Plugins `[specific plugin documentation; docs on how to develop plugins are under the "Developer" menu item]`
  - Area of Interest `[TBD]`
  - Back to Cart `[TBD]`
  - Enhanced Datatable `[v3/#/developer/datatables]`
  - Geosearch [`https://geosearch-docs.fgpv-vpgf.com/v2.0.3/#/`]
- Samples `[a single page with a list of sample pages]`

---

The three-level deep `Developer` menu item will look like this:
![](https://i.imgur.com/Bf5EtIn.png)

@mweech I know you want to move the `UI Overview` under the dev section, but I think it should stay at the top level (and it's not because I wrote half of it), because it's relevant to the map authors as well as devs, and it does cover a fair bit of functionality and not only UI components.

**Comment by james-rae** [comment]
Outstanding items not included in the above PR

> Should review https://github.com/fgpv-vpgf/fgpv-vpgf/issues/839 for gaps to make sure they are noted and also to determine if some of those gaps could be easily filled with existing legacy documentation

- Function Specific Docs (look at stealing from [this older doc site](http://fgpv-vpgf.github.io/fgpv-vpgf/v2.3.0-semi-weekly01/) )
- Exception handling & Logging

> Developer Intro Page: Should expand on ramp concepts

Not done.

> Contribute getting started: should we add quick start and support sections here from README.md…? how does this fit with repo contributing.md files?

Questions are still unanswered

> Map Author Intro page: Key Concepts

All 3 bullets have not been done (introduce key concepts, simple block diagram, align contents with block diagram)

> WCAG Compliance: Should provide an example of each

Not done.

> Samples: Format as title with description below title and a screenshot on the right side

Have not found a way to do this well in markdown. Can make an image sit on the right, but text on the left will flow around it as it pleases, meaning the headings and content for the next sample can end up beside image of the initial sample.  Sample screenshot size is also a bit on the large size (reducing them makes all the text become illegible)
