### ISSUE TITLE
EnhancedTable: Details and Zoom Broken for Certain Layers

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3396]
### Steps to Reproduce:
1. Open the table here: http://fgpv.cloudapp.net/demo/v3/dev/samples/index-samples.html?sample=2
2. Click on details button for multiple rows
3. You will notice that all Details in the details panel will be the same: 
![image](https://user-images.githubusercontent.com/25359812/55434965-d4febc00-5566-11e9-8045-168a7c20b257.png)
4. None of the Zoom buttons work

Notice that this works for other layers... may have something to do with `powerplants` being a controlled ID and nested inside `EcoGeo` because identify produces results like this: 
![image](https://user-images.githubusercontent.com/25359812/55435330-9c131700-5567-11e9-9723-4b80691ed07e.png)

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
Issue resolved.
Detail and zoom buttons work correctly.
