### ISSUE TITLE
Enhanced Table: Sort state not stored

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3412]
Sort state is not being saved on table close and reopen. Instead, a sort is applied to the first sortable column of the table. The is intended for a table that opens without any sort by default. 

In [v2.6.0](http://fgpv.cloudapp.net/demo/v2.6.0/dev/samples/index-samples.html) the table does store the state of the column sorts.

**Comment by YaroRoodzit** [comment]
Tested buid : v3.0.0-b4
Issue solved.
The sorted state is saved when the table is closed. The selected sorting is still applied after re-opening.
