### ISSUE TITLE
Enhanced Table: Column reorder buttons not disabling

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3413]
Move left button for left most column not enabled after moving right. 
Move left button for the column that takes its place it not disabled. 

This is also happening with the sort. The sort indicator arrows are immediately updated on clicking the title button. 

The buttons do appear to take on the correct state after moving the cursor off of the table so can probably be solved with a `$apply`.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
Column reorder buttons work properly.
