### ISSUE TITLE
EnhancedTable: broken cell navigation

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3414]
http://fgpv.cloudapp.net/demo/v3-panel-migration/dev/samples/index-samples.html

Try navigating through cells of table by tabbing or using arrow keys, navigation does not work properly. 
- This should work properly as a part of this: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3294 larger issue
- However I will not be overriding with my new `InternalsFocusManager` it on @AleksueiR suggestion because it would be more ideal to restore the `ag-grid` tabbing system as it worked before 

### Points:

- Clicking into a cell sometimes highlights and sometimes does not. The cell does get selected as using the arrow keys after seems to move the focus to the cells around them. When it does highlight (in chrome) it gets stuck highlighting the clicked cell and also highlights the cell being moved to. 

- Clicking or using the keyboard to activate the details or zoom buttons works but the cell doesn't stay highlighted although it is still focused. 

- Tabbing from the filter lists to the grid without highlighting any of the filters doesn't focus a cell in the table.
- Reaching either the left or right edge of the visible table when navigating using the arrow keys causes the arrows to switch to controlling the scrollbars for a short time then back to controlling cell selection.

**Comment by ShrutiVellanki** [comment]
Fixed by this: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3421

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
