### ISSUE TITLE
Panel UI fixes

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3422]
The alignment for some panel buttons do not align with the rest of the ui.

For example the close and expand buttons for the details panel: 
![image](https://user-images.githubusercontent.com/8885149/56216660-d7b1e480-602f-11e9-93c6-1d066e938014.png)

The close button for the add layer panels: 
![image](https://user-images.githubusercontent.com/8885149/56217071-94a44100-6030-11e9-8613-b68fdbaee4b2.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue resolved.
