### ISSUE TITLE
Layer remove button

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3427]
A bug was introduce between version 2.6 and 3.0 for layer remove button. In version 2.6 it behaves properly but in version 3.0, all layers are removed from the panel.

v2.6: http://fgpv.cloudapp.net/demo/v2.6.0-b3/dev/samples/index-samples.html?sample=81
v3.0: http://fgpv.cloudapp.net/demo/v3.0.0-b2/dev/samples/index-samples.html?sample=81

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
