### ISSUE TITLE
Pointer cannot capture an empty area of ​​the map when using Chrome.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3428]
Tested build :  v3.0.0-b2
I realized that the pointer can not capture and move an empty area of ​​the map when using Chrome. There is no such problem with IE or FF.

**Comment by james-rae** [comment]
Two of us cannot replicate; both on Chrome `v73.0.3683.103`

However I did see this happening on Yaro's PC so it wasn't imaginary.

**Comment by YaroRoodzit** [comment]
I have the same Chrome version , but i still use Win 7. Maybe this is a reason.

**Comment by YaroRoodzit** [comment]
Here is the error I get during capture:    
![image](https://user-images.githubusercontent.com/38046459/56670723-5a1a5400-6681-11e9-9c72-26c376af32de.png)

**Comment by mweech** [comment]
Note: BrowserStack has coverage for Desktop OS versions as well.

Could not reproduce on the Windows 7 VM with Chrome v73
