### ISSUE TITLE
Filtered records shown in the data grid are different from the displayed points of the map.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3430]
Tested build: v.3.0.0-b2.
Filtered records in the data grid are different from the displayed points of the map.
Try different filters. For example, "Station ID" or "Station Name". The map points displayed usually exceed the number of records in the data grid.
![image](https://user-images.githubusercontent.com/38046459/56740708-7381d580-673f-11e9-9d6e-58ca30781de6.png)
![image](https://user-images.githubusercontent.com/38046459/56740873-c22f6f80-673f-11e9-83bc-47b65656bb05.png)

**Comment by james-rae** [comment]
Filter engine for Files/WFS was not enforcing start-of-line and end-of-line when converting sql `LIKE` to javascript regex.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
