### ISSUE TITLE
Dynamic service fails to load side panel attribute fields 

### ISSUE THREAD

**Issue by mcharala** [fgpv-vpgf/fgpv-vpgf#3435]
The Physiographic Regions web mapping service is comprised of three layers. Each layer is registered at difference scale dependencies.  

When all layers are turned on, the services populate the side panel with attribute field information. However, the side panel fails to load any given layer's attribute field information when one of three dynamic layers are turned off. 

This issues only occurs in FGPV 2.5.0. 

https://webservices.maps.canada.ca/arcgis/rest/services/NRCan/phys_reg_en/MapServer

**Comment by james-rae** [comment]
Thanks for the report, `mcharala`.  I can see the behavior you describe on `v2.5.0` and `v2.6.0`. 

That said it appears to have been resolved in the soon-to-be-released `v3.0.0`.  Will leave this open and revist/re-check once it releases.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
