### ISSUE TITLE
No Input guides appear for the data table in IE 11

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3437]
Tested with build: V3.0.0-b2

When I view data table in IE 11, no input guides appear. Below are steps to reproduce:

1.	Go to below URL using IE
         http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html
2.	Add layer (E.g. Canada. Jason)
3.	When you view table, input guides appear to be missing.

Refer to screenshot below:

![IE](https://user-images.githubusercontent.com/46937257/56824704-355ee180-6825-11e9-9117-45be3a7995f6.JPG)

**Comment by james-rae** [comment]
Just noting this only appears to happen in `index-fgp` pages; likely something to do with styles on those pages and not ramp internals.

**Comment by dane-thomas** [comment]
It appears that the height of the input box is being restricted by something only in IE for the specific page mentioned. I can't seem to trace what's causing it and haven't been able to find a work around that doesn't effect other browsers either.
