### ISSUE TITLE
Areas of Interest sample issues

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#3440]
Found by @YaroRoodzit 

1. Extra scrollbar on the AoI panel.
![](https://i.imgur.com/g47G0Vf.png)

2. Error thrown when entering and exiting fullscreen
> index.ts:209 Uncaught Error: API(panels): Failed to open panel as all or part of it would render off the screen.

**Comment by ShrutiVellanki** [comment]
for the scroll bar, my latest PR would probably address it (since I was trying to get rid of the double scrollbar on the `enhancedTable`)

https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3421/files#diff-9a9442507a71382621e5f5bbfb8af562R170

**Comment by james-rae** [comment]
A third item to investigate, mentioned https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3363#issuecomment-487620492

The legend in the "pics" variant is not displaying all the symbology.  If this is by design/in the config, then can ignore.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
