### ISSUE TITLE
Details Bug for Dynamic Layers

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3441]
Found by @YaroRoodzit 

### Steps to Reproduce
1. Go to [sample 6](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=6)
2. Click on an area of the map without any points 
![image](https://user-images.githubusercontent.com/25359812/56913217-13f93200-6a7f-11e9-8fb6-bdfcc0db1107.png)

As you can see the Details shows `"Searching..."` forever

### Expected Behaviour (`v3.0.0-b1`)

![image](https://user-images.githubusercontent.com/25359812/56913278-368b4b00-6a7f-11e9-9739-27e9fb888fc9.png)

Details should show "Nothing Found" after it finishes "Searching"

**Comment by james-rae** [comment]
Older version had the `Nothing found` label managed in angular directive, so would auto-detect the situation and update.

Migration to panel API put the logic in module code, and the nothing check was only running at initialization.  
Added the label update to the code that watches as results come in.

**Comment by ShrutiVellanki** [comment]
@YaroRoodzit pointed out that if you click on an empty portion of the map and then click on a point, this happens on and off:
![image](https://user-images.githubusercontent.com/25359812/58126670-727a8180-7be1-11e9-847a-b50395562660.png)
(Point is found in the legend but the Details doesn't show it). 

May be related to this. Reopening.
