### ISSUE TITLE
Support for WKT instead of WKID

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#3442]
I would like to make a custom config file that uses a Tile cached basemap with a custom projection (not a WKID).

The projection is:
PROJCS["Sphere_ARC_INFO_Azimuthal_Equidistant",GEOGCS["GCS_Sphere_ARC_INFO",DATUM["D_Sphere_ARC_INFO",SPHEROID["Sphere_ARC_INFO",6370997.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-90.0],PARAMETER["Latitude_Of_Origin",90.0],UNIT["Meter",1.0]]

The service is here:
https://geoappext.nrcan.gc.ca/arcgis/rest/services/FGP/NCR_RCN/MapServer

It also has a text overlayer here:
https://geoappext.nrcan.gc.ca/arcgis/rest/services/FGP/NCR_RCN_A/MapServer

And it looks like this:
![image](https://user-images.githubusercontent.com/5502696/56970791-ef13c600-6b35-11e9-8a1d-ae57adec9492.png)

@bchagnon @jolevesq Do either of you have any other ideas on how to use these tile cached services in FGPV?

Thanks,
Patricia

**Comment by ppollock** [comment]
The tiling scheme is here:

[CircumpolarTilingScheme.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3131907/CircumpolarTilingScheme.zip)

**Comment by james-rae** [comment]
Hi Patricia.

As it stands, supporting this type of tile projection would be a limitation/shortcoming of the RAMP viewer.  Everything for base-projection is working off WKID at the moment.

Suggest leaving this issue open so it's on our radar as an improvement that has a real-world usecase.

**Comment by mpath** [comment]
Issue tested in Build: V3.2.0-b3.
