### ISSUE TITLE
The viewer is stuck forever if shared URL is damaged.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3443]
Use "Get Link" or "Share" option to create URL . Delete or change part of the information string. Try to load modified URL. Viewer will be stuck forever on loading of  incomplete or damaged URL.

**Comment by james-rae** [comment]
Adding some robustness to the bookmark parser is a good idea.
Will do in a future release

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5
Issue solved.
