### ISSUE TITLE
NPRI Layer Bookmark Issue

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3444]
Found by @YaroRoodzit 

Steps to reproduce: 
1. Go here: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html?keys=NPRI_CO
2. Deselect all symbologies except one: 
![image](https://user-images.githubusercontent.com/25359812/56978332-3c4b6400-6b45-11e9-99f1-61332e975faf.png)
3. Get shareable link, paste link in the browser
4. You will get this: 
![image](https://user-images.githubusercontent.com/25359812/56978389-571dd880-6b45-11e9-9af5-306b221b251e.png)

**Comment by james-rae** [comment]
Symbol filters are not encoded in the bookmark (same for grid filters).

Bookmark upgrades and full-state-storage services have long been pontificated, never prioritized
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1275
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1359
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1962
