### ISSUE TITLE
Coordinate Info plugin stops working after projection change.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3446]
Tested build : V3.0.0-b2
Test URL: http://fgpv.cloudapp.net/demo/v3.0.0-b2/dev/samples/plugins/coordInfo/samples/coordinfo-index.html
 Co-ordinate tool stops working after changing the projection between Mercator-Lambert.

**Comment by james-rae** [comment]
Steps to trigger: 

- Turn on co-ordinate tool in one projection.
- Then change to different projection (keeping tool on).

Will notice the tool appears as unchecked, though first click appears to set it into the unchecked mode again.  A second click will check the menu, but the tool will not function when the map is clicked.

**Comment by spencerwahl** [comment]
Some info for whoever picks this up:
As far as I know the projection change (and resulting RAMP restart) causes the plugin to get re-initialized.

This is either just leaving the mouse as a crosshair, making the user thing coord-info is on when its not *OR* coord-info is still on but its the old on and therefore wont work.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
