### ISSUE TITLE
Datatable does not close when removing dynamic children and delay to close

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3447]
### Problems
As noted in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3439#issuecomment-487682973 the datatable doesn't close when removing children of a dynamic layer. Only once all children of the dynamic layer is removed will the table close. 

There is also a short delay for closing the table once a layer is removed since it waits for the undo toast to close. 

### Solution
Add an observable in legend.ts for removal of elements from the legend. Trigger right as element is removed from legend. Swap out layer remove for legend item remove in table.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
