### ISSUE TITLE
Geosearch: Province and Type filters drop-down list does not work

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3448]
Tested on [develop](http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html)

As pointed out by @YaroRoodzit here https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3369#issuecomment-487609717

Instead of a drop down list, you just get "Loading Filters" for both `Provinces` and `Types` filters

![image](https://user-images.githubusercontent.com/25359812/57031518-f14d5180-6c15-11e9-9fa2-191e9699521b.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue resolved.
