### ISSUE TITLE
Add Help content for GeoSearch

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3449]
As it's very prevelant, some basic help doc would makes sense in our in-app help page.

In particular, it's not clear that our geosearch does not do address search.  Punching in an address usually gives no results.

### Acceptance Criteria
- [ ] Documentation is more precise on expected inputs
- [ ] Documentation is more specific in terms of expected results
- [ ] Usage of Geosearch UI controls is fully explained
- [ ] Identify limitations of Geosearch such as addresses not being covered at this time

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.

**Comment by mweech** [comment]
Needs estimation based on updated Acceptance Criteria and assignment for implementation.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b4
Implemented as expected.
