### ISSUE TITLE
Issue with Apply filter to map option

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3450]
Tested in: V3.0.0-b2

When you select clear filter after applying filter to data table, apply filter to map option should not be available if you never applied filter to map.

Steps to reproduce:

1.	Go to http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html
2.	Import file
3.	Choose file (E.g. ne_10m_airports)
4.	View Table
5.	Apply filter to table using object ID (E.g. Min 0 and Max 100)
6.	Click on clear filter
7.	Apply Filter to map option is available and you can still apply filter to map, although it does nothing to map as filter is cleared.

Note: Reproducible in both IE and google chrome browsers

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
