### ISSUE TITLE
Records notes below table title is cut-off

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3453]
Tested with: V3.0.0-b2

Noticed that when you apply filter to table, the notes appear below table title for the number of records is cut-off. This is using Google chrome.  Just to note that we do have an issue logged for IE 11 which is similar issue relating to size of the search area (Issue # 3309). 

Steps to reproduce:

1.	Using Google chrome, go to http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html?keys=EcoAction
2.	Enter “Atlantic” in search
3.	Refer to the notes appear below Feature: Nature. As shown in screenshot below, it is cut-off.

![Search issues](https://user-images.githubusercontent.com/46937257/57089007-7ea1ac00-6cd1-11e9-8a67-3e55c9c5cbdc.JPG)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
