### ISSUE TITLE
The WMS layer has moved from its original position on the base map after zooming in full screen mode.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3456]
Tested build: V3.0.0-b2
Steps to reproduce:
- Start with URL:     http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html
- Import WMS layer
http://geoportal.gc.ca/arcgis/services/Arctic_Voyage_Planning_Guide_ENG/MapServer/WmsServer
Select all sub-layers.
- Select Full screen mode
- Try to zoom IN / OUT by scroling mouse or -/+ buttons
All layer has moved from its original position on the base map. Layer stuck with loading bar forever.

**Comment by YaroRoodzit** [comment]
After quite a long wait and going to the windowed mode, I got the following view:

![image](https://user-images.githubusercontent.com/38046459/57100510-211b5880-6ced-11e9-8fb1-ed50f66d9785.png)

**Comment by mweech** [comment]
This is a case of how a server can't even keep up with the demand of a single viewer instance.  The Dynamic MapServer version of the service suffers in a similar way but at least benefits from individual layer toggling.  After a while, the WMS layer will catchup and render, but it is a very long processing time when trying to render ~30 layers into a single potentially very large map image.

**Comment by YaroRoodzit** [comment]
It is strange that the problem appears only in full screen mode. I didn't see any issue or performance problem with this layer when window view was in use

**Comment by james-rae** [comment]
I think Mikes comment means full screen results in larger map area on the screen.  Service has to generate bigger picture, slows down, and map looks funny until the slow request resolves
