### ISSUE TITLE
Details and Geosearch does not open in Mobile View

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3457]
#### Steps to Reproduce: 

1. Open sample page on [`develop`](http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html)
2. Switch to mobile view
3. Open a datatable, and press on any details button, or try to open the geosearch panel

#### Problem:
- The details and geosearch panels won't open 
- The following error message is shown on the screen
![image](https://user-images.githubusercontent.com/25359812/57101046-64c29200-6cee-11e9-9432-be710cc2b6b1.png)

#### Expected Behaviour: 
- on [`v2.6.0`](http://fgpv.cloudapp.net/demo/v2.6.0/prod/samples/index-samples.html), panels would show like this: 

![image](https://user-images.githubusercontent.com/25359812/57101168-a2bfb600-6cee-11e9-84e2-c3f62bee64d9.png)

![image](https://user-images.githubusercontent.com/25359812/57101201-b10dd200-6cee-11e9-9185-0f345bbb87c5.png)

**Comment by james-rae** [comment]
Also adding that the grid doesn't have the mobile styles (thanks Aleks for finding that), will include the fix on this issue

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
