### ISSUE TITLE
UX issue while toggling between apply filter to map and clear filter functions

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3463]
Tested in: V3.0.0-b2

Noticed minor UX issue when I toggled between clear filter and apply filter to map. Issue is reproducible when using IE 11 or MS Edge browser.

Steps to reproduce:

1.	Using IE 11 or MS Edge, go to http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html
2.	Import layer using import file option (E.g. ne_10m_airports)
3.	Enter word “Airport” within the column FEATURECLA
4.	Click apply filter to map
5.	Go to clear filter and noticed that apply filter to map text still highlighted.
6.	Go to apply filter to map and noticed that clear filter text is still highlighted. 

Below is screenshot:

![UX Issue with filter](https://user-images.githubusercontent.com/46937257/57247403-bb411080-700d-11e9-8d08-3a0b9ea20024.JPG)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
