### ISSUE TITLE
Some improvement is required with the label “backToCart”.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3464]
Tested build: V3.0.0-b2
1. Why does the first word begin with a lowercase letter in the “backToCart” tag and the rest of the phrase with capital letters?
Is there a reason for this? Otherwise, it has to be consistent.
![image](https://user-images.githubusercontent.com/38046459/57250703-14ad3d80-7016-11e9-99e1-3888e4971ca0.png)

2. Label "backToCart” is cutted off in Safari browser.
Tested with BrowserStack.com.
![image](https://user-images.githubusercontent.com/38046459/57250811-4aeabd00-7016-11e9-9865-06dc7b664b30.png)

**Comment by mweech** [comment]
Cleaning up these controls makes sense.  Given FGP web presence is changing dramatically this year, just having a more vanilla (non GCgeo) themed page with decent controls to do RCS/Bookmark testing would suffice.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5
The issue is mostly resolved. Including Mac(Safari) and Android devices( Chrome). However, still exist for  all iOS devices . "Get Link " and "Back to  Cart " labels are partially displayed.
See example:    

![image](https://user-images.githubusercontent.com/38046459/58348352-80711200-7e2e-11e9-8581-e679390b9008.png)
