### ISSUE TITLE
Enhanced Table: Messed up in Tablet view / Medium Browser Screens

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3466]
Tested using [develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html) in tablet view 

#### Issue 1: Title Gets Eclipsed and Right Most Buttons Disappear
![titleEclipse](https://user-images.githubusercontent.com/25359812/57329002-dd579300-70e0-11e9-85f9-37ac3ec0d010.gif)

#### Issue 2: Table becomes an unusable at  certain screen sizes 

(eg: LG Optimus phone rotated to the side)

![image](https://user-images.githubusercontent.com/25359812/57329428-bb124500-70e1-11e9-9dc1-22c8d863c25c.png)

(eg: shrinking browser window)
![unusableSliver](https://user-images.githubusercontent.com/25359812/57329783-64f1d180-70e2-11e9-9346-ab4c5b10e472.gif)

#### Issue 3: IE Specific - Control Buttons are mashed together in IE
![image](https://user-images.githubusercontent.com/25359812/57329917-b732f280-70e2-11e9-9046-77e10e2b9b3d.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
