### ISSUE TITLE
EnhancedTable: Clicking on LegendItem does not toggle the table

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3469]
Works fine using close button.

Table used to open and close on pressing the corresponding legend item on [`v3.0.0-b2`](http://fgpv.cloudapp.net/demo/v3.0.0-b2/dev/samples/index-samples.html).

![yesToggle](https://user-images.githubusercontent.com/25359812/57387255-fb2a0400-7183-11e9-9df6-2d8dde0f5c2e.gif)

 Broken on [`develop`](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html).

![noToggle](https://user-images.githubusercontent.com/25359812/57387235-f2d1c900-7183-11e9-873b-2e23a58050b5.gif)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
