### ISSUE TITLE
UX issue while closing settings panel for WMS layer

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3470]
Tested in: V3.0.0-b2

When you import WMS layer using import service and try to close settings panel, close button located within settings panel is broken. You can still close settings panel but it is hard to recognize close button. Noticed this issue using IE 11 browser.

Steps to reproduce

1. Using IE 11, go to http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html
2. Import WMS service layer: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities
3. Click on settings panel and notice that close button is broken

Screenshot:
![cannot close settings pannel](https://user-images.githubusercontent.com/46937257/57394953-d5f1c180-7194-11e9-82f9-434c57b95d9f.JPG)

**Comment by AleksueiR** [comment]
Is this just the settings panel's problem? Any panel can potentially have a title overflowing and pushing the header controls out.

**Comment by dane-thomas** [comment]
The problem was with the close button having a `min-width` of 0 so the container holding the icon kept shrinking. The css changed was in `panels.scss` so it should be fixed for any panel.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
