### ISSUE TITLE
EnhancedTable: Disappearing Headers in IE

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3475]
![disappearingHeaders](https://user-images.githubusercontent.com/25359812/57478624-6994c200-7269-11e9-8501-8e59e4542c91.gif)

- Using the keyboard to scroll through the table makes headers disappear
- this also has the added effect of breaking the bottom scrollbar afterwards

**Comment by dane-thomas** [comment]
Just to note, this seems to happen in Firefox, Chrome, and Edge as well but it gets corrected whenever the table is hovered or focused. The correction seems to fail in IE.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5
IE problem with disappearing headers resolved.
