### ISSUE TITLE
EnhancedTable: Load Screen Shows Greater Numerator than Denominator

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3476]
Title is self explanatory. Inconsistent and hard to reproduce. Pointed out by several people.

Referring to this screen
![loadscreen.png](https://images.zenhubusercontent.com/5aea0e2a4b5806bc2bd18707/a832df46-2bf9-4f3a-8ab1-a496927855a5)

**Comment by mweech** [comment]
We had attempted to add a sense of definitive loading progress, espeically given some layers were large and caused lengthy upload time with the Enhanced Datagrid under previous versions of the viewer.  I believe this may be less relevant and we may want to consider reverting to a non-specific loading animation.

Thoughts @AleksueiR ?

**Comment by james-rae** [comment]
I think there also may be some "preditive" code that gives the impression of progress while big chunks are downloading.  If we switched back to showing actual download, would mean small datasets go from 0 to done and large sets (which are usually slower) would be in 1000 record increments (or whatever the service limit is)

**Comment by AleksueiR** [comment]
We still have some large layers and I think a deterministic is always (mostly) better than an undeterministic one.
@james-rae is correct - there is a predictive logic to show the progress based on intervals between loading chunks of data. I don't remember any issues with the prediction running over the actual number of records on the old table. Maybe something got inadvertently changed during the migration. I think we can at least look at the predictive code first to see if a quick fix possible like adding a condition to cap the predicted number of records to the total number of records before reverting to the old way of showing loading progress.

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b5
Never seen such a problem. I can not reproduce.
