### ISSUE TITLE
Initially, "Zoom to Feature"  does not work from Details window.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3481]
Tested build: v3.0.0-b2
"Zoom to Feature"  does not work from Details window or from details content window.
"Zoom to Feature" start to work properly only after use in datagrid. There is no problem with zooming used from data grid table. 
Issue exist for different browsers and can be seen with different layers.  
Steps to reproduce:
1. Use http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html?keys=JOSM
2. Click for details any map point 
3. Try clicking "Zoom to Feature" . Zoom failed. Error appears in console.
![image](https://user-images.githubusercontent.com/38046459/57549625-10449580-7332-11e9-8b15-53c00726e400.png)
4. Open content window and try "Zoom to Feature" . Zoom failed. Same error appears in console.
5. Close window and details. Open datagrid and click "Zoom to Feature". No issue. Working properly.
6. Close data grid . Click on back to Canada tab. Click any map point for details. Click "Zoom to Feature". No issue. Working properly.
7.  Open content window and try "Zoom to Feature". No issue. Working properly.

 Problem is back after page refresh or "back to Cart" used.

**Comment by spencerwahl** [comment]
Zoom functionality was fixed to work with new panels. Additionally will fade out any panels covering the zoom area to ensure the point is visible.

**Comment by YaroRoodzit** [comment]
Tested build: 3.0.0-b5
Issue resolved.
