### ISSUE TITLE
symbologyExpanded property in config kills build

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3495]
Reproduced both by @JahidAhmed and myself

Paste the below config snippet into any config sample
- try `npm run serve`
- at least on `develop`, you will get the following error (doesn't build at all)
- works when you remove `"symbologyExpanded": true`

![image](https://user-images.githubusercontent.com/25359812/57795460-0cd75280-7714-11e9-99fa-9f25178d1e76.png)

Config Snippet:

```js
{
  "id": "0",
  "layerType": "esriDynamic",
  "url": "https://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/CAM/MapServer",
  "tolerance": 20,
  "singleEntryCollapse": true,
  "symbologyExpanded": true,
  "layerEntries": [
    {
      "index": 0,
      "name": "Keyword search",
      "table": {
        "lazyFilter": true,
        "search": {"enabled": false},
        "columns": [
          {
            "data": "OBJECTID",
            "visible": false
          },
          {
            "data": "Category"
          },
          {
            "data": "Recipient_type"
          },
          {
            "data": "Department___Agency___Crown_Corporation"
          },
          {
            "data": "Province_Territory"
          },
          {
            "data": "Municipality___Community"
          },
          {
            "data": "Program_name"
          },
          {
            "data": "Project_name"
          },
          {
            "data": "Project_description"
          },
          {
            "data": "Ultimate_recipient_name"
          },
          {
            "data": "Funding_date___estimated_start_date"
          },
          {
            "data": "Program_contribution"
          },
          {
            "data": "Estimated_total_project_cost"
          },
          {
            "data": "Additional_information"
          },
          {
            "data": "Icon",
            "visible": false
          }
        ]
      }
    }
  ]
}
```

**Comment by james-rae** [comment]
According to the schema, this property is on the legend entries, not the layers.
See `infoSection` and `entry`

**Comment by james-rae** [comment]
It could be the real issue is "no support for expanded symbols in autolegend mode"?

**Comment by ShrutiVellanki** [comment]
Sorry yeah I was wondering this, because the config snippet from above is the one we both copy/pasted from here:  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3477#issue-442401838
- also it doesn't error out if you run a map with this config from the plugins repo (though that repo is very broken)

**Comment by JahidAhmed** [comment]
The issue seems to be what James' said in his 1st comment. `symbologyExpanded` should be under the legend entry section, and a couple other examples showing this would be sample 7, 8, and 70.

**Comment by spencerwahl** [comment]
As an aside, the plugin repo doesn't error because it doesn't validate configs

**Comment by james-rae** [comment]
This solves a bit of a mystery.   Along with the "hidden columns" bug report was also a notification that symbols were not expanding. Appears to be malformed config for expansion (or alternately a revelation of the lack of expansion support for autolegend).

Will confer with Dan and open a new issue for more expansion support if we need it.
