### ISSUE TITLE
webpack-dev-server vulnerability found in package.json

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3496]
Investigate the posted issue across all affected repositories. 

https://github.com/fgpv-vpgf/fgpv-vpgf/network/alert/package.json/webpack-dev-server/open

**Comment by RyanCoulsonCA** [comment]
Just looked into this. The vulnerability is fixed on the `develop` branch (webpack-dev-server is at 3.1.14), but the warning bot only looks at `master`, so it's still detecting the vulnerability. The issue should be fixed once 3.0 is released.

**Comment by AleksueiR** [comment]
Also, this vulnerability is on `webpack-dev-server` which is only used when serving code locally. None of the `webpack-dev-server` is used in the production build.
