### ISSUE TITLE
Button focus highlight for “ Close Panel” is compressed when page minimized.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3500]
Tested build: v3.0.0-b4
URL used for test: http://fgpv.cloudapp.net/demo/v3.0.0-b4/prod/samples/index-fgp-en.html?keys=JOSM

![image](https://user-images.githubusercontent.com/38046459/57871836-407bb080-77d8-11e9-99ae-7d75a93600a1.png)

**Comment by RyanCoulsonCA** [comment]
After looking in to this a bit, I can see that all of the control buttons on the right side have a parent with a `table-control` class, except the `close panel` button. Adding a parent element to the close button with the class `table-control` fixes the problem with the button being compressed. At this point I'm just trying to figure out the best way to do this.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b2
Issue solved.
