### ISSUE TITLE
Grid Column - Sort Arrow can overlap Reorder Arrow

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3507]
Likely a combination of fixed width and long title.

![AngryArrow](https://user-images.githubusercontent.com/7585245/57940724-1e973200-789b-11e9-994e-752af87add7e.jpg)

Sample to reproduce

```text
{
  "id": "AngryArrows",
  "name": "Electric Transmission Line",
  "layerType": "esriFeature",
  "table": {
    "columns": [
      {
        "data": "OBJECTID",
        "sort": "desc",
        "width": 200,
        "title": "This is a longer title for OBJECTID"
      },
      {
        "data": "Country",
        "width": 300
      }
    ]
  },
  "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/1"
}
```

**Comment by james-rae** [comment]
To make things weirder, Sample 37 has similar config and doesn't reproduce this problem.

**Comment by dane-thomas** [comment]
The issue is probably due to the the `max-width: 80%` for the `custom-header-label` element in the enhanced table's `main.scss`

**Comment by yileifeng** [comment]
One solution that might work is to adjust the column width in the `ColumnNode` constructor according to the given column title length. This will also have a min and max width value such that the two arrows will never overlap, along with a number to increment the width in between this range. I did some trial and error tests and found the numbers that would make this work. 

However, in this case, the column width specified in the config file will likely be changed. Let me know if this is something that takes priority and I will scratch this idea.

**Comment by dane-thomas** [comment]
If a column width is set in the config the map author would expect that as the width. If the arrows will always have a dedicated amount of space then we could mention in the documentation that the width only effects the title. 

That said, I still think the most intuitive solution would be for the config column widths to be respected.

**Comment by yileifeng** [comment]
After testing most of the config files with specified column widths/titles using the method above, the width is actually left unchanged for almost every case. If no width is specified in config, then I don't think we have this problem.  

I think the only time the overlapping arrows ever occur (which is when the column width gets modified) is when a smaller than expected width is specified in the config file, to go along with a longer title. So maybe for these very uncommon cases, it could make sense to use this method, to help prevent this overlap and make UI look nicer.

**Comment by AleksueiR** [comment]
Hm, I don't think messing with widths is necessary here. 

You can set the `div` wrapper around the button and arrows to `display: flex`, give `flex-shrink: 0` to `.rv-sort-arrow` and change `reorder-icons`'s position to `relative`. This way the elements will never overlap and the column width will always stay as described in the config.

**Comment by yileifeng** [comment]
I tried the solution with the CSS properties. It fixes the original sample with specified width of 200: 


![200px width test alex](https://user-images.githubusercontent.com/31557789/58260571-b1751800-7d44-11e9-8223-b2cb8a047763.PNG)


But then I try changing the width in the config to a smaller number like 100 and the reorder arrows overlap with the next column: 

![100px width test alex](https://user-images.githubusercontent.com/31557789/58260703-ef723c00-7d44-11e9-80b2-195c010ce577.PNG)


I tested the original solution I used for the same test (width = 100) and it would adjust the width for a case like this to a number like 260. It looks like this: 

![100px width test original](https://user-images.githubusercontent.com/31557789/58260980-745d5580-7d45-11e9-9914-fc627132884f.PNG)

So, this might work but I am not sure if there are other ways to go about this (using CSS properties or other methods).

**Comment by ShrutiVellanki** [comment]
In a worst case scenario we could always see if the column width is longer than normal and make the title truncate before it normally would. Like "if `column-width: 100`, `max-width` of text should be `30px`"

Link on how to truncate text: https://stackoverflow.com/questions/26973570/setting-a-max-character-length-in-css/26975271

If text is already being truncated, and the hover tells us what we need to know about the column title, I don't see any harm in truncating it further. (But if there's a better way by all means please do that first)

**Comment by AleksueiR** [comment]
The `.custom-header-label` element is an `md-button` and its minimum width is set to 88px. If the total column width is only 100px, the label will push the arrows outside the column header wrapper and overlap the next column. Just remove the `min-width` and it will shrink correctly as the column is shrinking.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b1
Test sample: 37
Issue solved.
