### ISSUE TITLE
Table does not build after reloading layer 

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3509]
To replicate: 

Load
http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html?keys=JOSM 

Open the datatable. 
Then, reload the layer via the settings menu. The table should remain open after the reload. 

Attempting to open the datatable again via the settings menu while it is already open results in the table not building successfully. 

May be related to #3499.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b1
Issue solved.
