### ISSUE TITLE
Data table Help content is out of date

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3511]
Our help content still has the `datatables` screenshots, the old button icons, references to the control panel (for sorting, reordering, column visibility).

### Acceptance Criteria:

- [ ] Help documentation has an overall description of the component and its general features
- [ ] Help documentation explains the 
  - [x] filtering (+ "clear filter" and "apply to map" buttons)
  - [ ] search capabilities 
  - [x] column reordering and sorting
  - [x] and column visibility menu
- [ ] Help documentation explains the controls available on a feature basis
- [ ] Help documentation provides help on the features in the menu
  - [ ] table view mode (split / maximized)
  - [ ] filter by extent
  - [ ] "show filters" option
  - [ ] export (and its limitations)
- [ ] Help documentation briefly explains how to navigate the table using a keyboard (tabbing and arrow keys)
- [ ] Language of text in screenshots matches the language of the documentation

Related to #2966

**Comment by AleksueiR** [comment]
We can always steal screenshots from the Overview guide and use them in the Help document.

**Comment by mweech** [comment]
Needs confirmation of estimate based on added acceptance criteria and subsequent assignment for implementation.

**Comment by YaroRoodzit** [comment]
Tested build:  v3.1.0-b5 
Implemented as designed.
