### ISSUE TITLE
Console errors when clicking on a data point

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3523]
The console is spammed with errors when you click on a data point. It only seems to happen the first time you click on a point. Some points give more errors than others.

## Steps To Reproduce
1. Open browser console
2. Load up http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=2 
3. Click on a data point, you should see tons of console errors pop up

## Example
![image](https://user-images.githubusercontent.com/25874602/58429714-c0c1d180-8074-11e9-839b-1dbd21bfdada.png)

**Comment by RyanCoulsonCA** [comment]
We may want to make this into it's own issue later, but this is another error that pops up in the console when clicking on a data point:

![](https://i.imgur.com/cNKTKIF.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b4
Issue solved.
