### ISSUE TITLE
Layout issue with "Areas of Interest Demo " when IE in use.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3527]
Tested build: v3.0.0-b5
Layout issue with "Areas of Interest Demo " when IE in use. See attached for clarity.
![image](https://user-images.githubusercontent.com/38046459/58508085-31deb300-8161-11e9-92d9-f353a8c8601a.png)

**Comment by mpath** [comment]
Tested in build: V3.1.0-b8
Issue resolved.
