### ISSUE TITLE
Zoom Marquee

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#353]
Add zoom marquee functionality to the navigation controls on the screen.  Will allow the user to zoom into a drawn bounding box.  Similar functionality exists if the user holds down the "shift" key, however this tool would allow the user to complete such an action without utilizing the keyboard.

**Comment by mweech** [comment]
concerned we may start cluttering the tools with something that can be accomplished manually or through a mouse shortcut that is already available.

**Comment by jolevesq** [comment]
Agree! It can be done by shift + mouse click. We have it in GCViz as a button because UX team found the button more intuitive. We can wait and see if there is really a use case and users demand for this.
