### ISSUE TITLE
Console errors are displayed when opening index-fgp-en.html.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3536]
Tested build: 3.0.0-b5
Console errors are displayed when opening index-fgp-en.html.
http://fgpv.cloudapp.net/demo/v3.0.0-b5/prod/samples/index-fgp-en.html
   Please fix what is possible.
- in Chrome
![image](https://user-images.githubusercontent.com/38046459/58657655-c1fd3380-82ec-11e9-8b72-c2dd5b5ad260.png)
- in IE

**Comment by james-rae** [comment]
The API depreciation and WET CORS error can be ignored for now.
However the missing plugin should be investigated (possibly due to plugins only building on the `dev` folder - which if thats the case, can look into why its not building in `prod` folder)

**Comment by AleksueiR** [comment]
I don't think the plugin is missing -- right now the table plugin is being bundled with the core code and is not loaded at run time.

**Comment by james-rae** [comment]
The plugin error was due to `backToCart`, not the table plugin.
Things are working now, likely solved by the fix applied by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3678
