### ISSUE TITLE
Keyboard navigation is stuck inside the sublayers if layers legend has been extended.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3542]
Tested build: v3.0.0-b5
Test URL: http://fgpv.cloudapp.net/demo/v3.0.0-b5/prod/samples/index-fgp-en.html?keys=JOSM,CESI_Other
Keyboard navigation is stuck inside sublayers if the layer legend has been extended.
The layer legend must be hidden to return to navigation through the viewer.
For example, "Setting" function has no such problem, and additional steps are simply added to the navigation steps. If possible, we should stick to this approach.

**Comment by mpath** [comment]
Tested in build: V3.1.0-b8
Issue resolved.
