### ISSUE TITLE
Strange behavior when navigating with keyboard in the layers menu, which includes expandable layers.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3544]
Tested build: v3.0.0-b5
Test URL: http://fgpv.cloudapp.net/demo/v3.0.0-b5/prod/samples/index-fgp-en.html?keys=JOSM,CESI_Other
- Keyboard navigation requires pressing “Tab” three times in order to go through the fake step “Hide layer” / “Show layer”.
![image](https://user-images.githubusercontent.com/38046459/58732746-7025dd80-83c0-11e9-81f1-a7afeafd035a.png)
-  Pressing “Space” on the fake “Hide layer / Show layer” steps will turn some sublayers on and off.

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
