### ISSUE TITLE
Error displayed in EDGE console when projection changed.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3547]
Tested  build: 3.0.0-b5
Test url: http://fgpv.cloudapp.net/demo/v3.0.0-b5/prod/samples/index-fgp-en.html?keys=CESI_Other
Browser : Microsoft Edge
Error are displayed in the console when projection switches between Lambert-  Mercator.
![image](https://user-images.githubusercontent.com/38046459/58812452-eceace80-85ef-11e9-81c2-840bb45f99d9.png)

**Comment by yileifeng** [comment]
Additional tests using Chrome (can log a new issue but similar problems): 

Changing projection using http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html?keys=CESI_Other also gives this error: 
![projection change additional error on fgp-en](https://user-images.githubusercontent.com/31557789/59610885-4cfd6c80-90e8-11e9-9105-298a56580a28.PNG)

Changing projection using `index-samples` gives the same error but worth noting that changing language using `index-samples` also produces the error. 

Changing languages AFTER projection change using http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html?keys=CESI_Other results in these errors: 
![projection change + language change on fgp-en](https://user-images.githubusercontent.com/31557789/59610993-7fa76500-90e8-11e9-9871-35b60d18648c.PNG)
