### ISSUE TITLE
Meet Keyboard Trap WCAG 2.0 Guideline

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3548]
From here: https://www.w3.org/WAI/WCAG21/quickref/#no-keyboard-trap

> If keyboard focus can be moved to a component of the page using a keyboard interface, then focus can be moved away from that component using only a keyboard interface, and, **if it requires more than unmodified arrow or tab keys or other standard exit methods, the user is advised of the method for moving focus away**

For `enhancedTable` and other focus list / tree navigation to come, we currently use `ESC` when an `item` is highlighted to focus out to the parent list `list`. For example over here, pressing `ESC` focuses out from the `REFERENCE PERIOD` column to the parent `list` (in this case the filters row): 
![escKey](https://user-images.githubusercontent.com/25359812/58813225-4bfd1300-85f1-11e9-9a80-cac9579306ee.gif)

Thus we need to find a way to advise the user of using `ESC` to focus out.

#### Solution
 
@JahidAhmed suggested putting it https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3511 for now, but since this focus list / tree navigation is going to be implemented in places other than the `enhancedTable` it could potentially need its own section in Help files

**Comment by AleksueiR** [comment]
I would think the `Esc` key should fall under the `other standard exit methods`.

**Comment by ShrutiVellanki** [comment]
Closing. @AleksueiR  pointed out that as long as we can use the `tab`/`backtab` to tab out to the next/previous list, it shouldn't matter that we are using `esc` to focus out to the current list
