### ISSUE TITLE
Focus Manager Activate RAMP Dialog Gets Stuck

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3549]
Steps to reproduce: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html?keys=EcoAction

- tab into map to activate identify help dialog
- Press `Esc+Tab`  or `Tab` as instructed to not focus on map
- It will just end up focusing on the legend flag icons
- Then it retriggers identify pop up window until it runs out of flag icons to focus on
- When you press enter, it can't focus on the viewer since the last focused element is a legend flag icon

![identifyIssue](https://user-images.githubusercontent.com/25359812/58829141-1d912f00-8615-11e9-8ab1-7a69bf8f5c89.gif)

Each time you see that dialog keep popping up i did an `Esc + Tab`. Also happens if I just do a `Tab` each time. You'll notice focus eventually shifts to the gear and datatable icon under nature

**Comment by AleksueiR** [comment]
If #3557 is implemented first, this won't be an issue.
