### ISSUE TITLE
"Get link" require improvement.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3556]
Tested build: v3.0.0-b5
As an improvement to the user interface, can we select the entire URL after clicking “Get link”.
The created link is very long. Part of it can be easily lost when copying.
Thank you.

**Comment by AleksueiR** [comment]
As soon as the "Get link" dialogue open, the full link is pre-selected and you only need to press "Ctrl + C" to copy it. Also, if you click away to deselect the link, and then click the link once, it's also fully selected and ready to be copied.

It's actually non-trivial to copy just a part of the link: you need to click the already selected link once to deselect it, and then try to select part of the link by pressing the left mouse button and dragging.

**Comment by YaroRoodzit** [comment]
@AleksueiR. Looks like you're confusing with "Share" option . For the "Share" the full link is pre-selected and you only need to press "Ctrl + C" to copy it,but "Get link" behave differently.

**Comment by AleksueiR** [comment]
Ah, you are right. My bad then.

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
