### ISSUE TITLE
Replace Focus Manager with a less aggressive system 

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3557]
Build a new system for handling focus in a less controlling way according to [this discussion](https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/3?from_comment=5#discussion-3-comment-5) and this [Accessibility Guide](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3359) issue.

Related #3294.

**Comment by mweech** [comment]
Sounds like something that requires a discussion!

**Comment by AleksueiR** [comment]
We can continue using this one: https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/3?from_comment=5#discussion-3-comment-5
