### ISSUE TITLE
GeoSearch does not work after changing languages with filters applied

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3558]
To replicate: 

1. Load a sample page 
2. Use geosearch to search for anything 
3. Apply a province or type filter 
4. Change languages with the filter applied 
5. Attempting to use geosearch again to search for something does not seem to work

This seems to work when the filter is cleared before changing languages. 

**Expected behavior**: 
![expectedbehavior](https://user-images.githubusercontent.com/31557789/58983399-b1ddcc00-87a4-11e9-8af7-9b62d1d66868.PNG)

**Actual behavior**: 
![actualbehavior](https://user-images.githubusercontent.com/31557789/58983697-67108400-87a5-11e9-90db-960395c433a8.PNG)

Note: Everything seems to be fine after changing and clearing the filters again

**Comment by yileifeng** [comment]
Another problem: the filters do not work either after language change with a a province/type filter applied

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b2
Issue solved.
