### ISSUE TITLE
Font size for layer name tooltip

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3566]
Hi,

Is it possible to increase the font size for the tooltips? Specially for the one who shows the layer name when the layer name is too long. It is hard to read for long and complex layer name.

![](https://i.imgur.com/tiFK8oE.png)

Thanks

**Comment by spencerwahl** [comment]
Hi Johann,

The font size should be able to be increased selecting on `.md-tooltip` in your CSS:

```
.md-tooltip {
    font-size: 20px !important;
}
```

If you find that increasing the font size makes the text look too large for the tooltip you can change the padding using something like:

```
.md-tooltip {
    font-size: 20px !important;
    padding: 2px 8px !important;
}
```

**Comment by jolevesq** [comment]
@spencerwahl Thanks for the answer
