### ISSUE TITLE
Geosearch search term pops up after clear

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3569]
Steps to reproduce on http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html: 
- Open geosearch
- Enter a search term (e.g. `Ontario`)
- Highlight and hit backspace to clear the search term
- Press the `X` to close geosearch
![image](https://user-images.githubusercontent.com/25359812/59202414-66dc0400-8b6a-11e9-8534-64adcb715c6a.png)
- Reopen geosearch, you'll see the search term pop up OR switch languages and reopen geosearch and you'll see the search term pop up

@JahidAhmed pointed out that clear happens on keyup (so hitting `backspace` on character at a time to clear term) but not on highlight which might be the cause of the issue

**Comment by YaroRoodzit** [comment]
Tested build: V3.1.0-b2
Issue solved.
