### ISSUE TITLE
Better message for the datatable reload toast

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3570]
With permanent toast notifications, `dismiss` should be used instead of `close` for consistency and to avoid possible confusion about what exactly is being closed - it could be assumed the `close` button closes that datatable.

![](https://i.imgur.com/VeJqqCh.png)

**Comment by james-rae** [comment]
Suggest, `dismiss`, unless we also play a .wav of a British headmaster yelling DISMISSED!

**Comment by AleksueiR** [comment]
Right, just `dismiss`. Sorry about the typo :/
