### ISSUE TITLE
Tags for "Columns" and " Options" are not visible in IE.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3574]
Tested build: v3.1.0-b1
Test URL: http://fgpv.cloudapp.net/demo/v3.1.0-b1/prod/samples/index-samples.html?sample=2
Samplem 02.
Accidentally disappearing labels in the drop-down lists
Tags appear when the cursor moves down in the drop-down list.
The issue exists and reproduced using IE. With Chrome or Edge, this problem is not observed.

- Missing columns
![image](https://user-images.githubusercontent.com/38046459/59298999-adf4f280-8c59-11e9-905a-38aff386daf3.png)

- Missing options
![image](https://user-images.githubusercontent.com/38046459/59299086-df6dbe00-8c59-11e9-8c6a-e4c93010aa74.png)

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
