### ISSUE TITLE
UI improvements for "..." menu buttons.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3575]
Tested build: v3.1.0-b1
As part of UI improvement it would be nice to add pop-up help tags for  "..." menu buttons in layers menu and data grid.
Same as we have for the rest of buttons.
e.g. something like "Options".
See attached for clarity.
![image](https://user-images.githubusercontent.com/38046459/59301546-db449f00-8c5f-11e9-87cb-b79941c8ba9c.png)

**Comment by AleksueiR** [comment]
@RyanCoulsonCA please use ~~`Click here to win an iPad`~~ `More options` text as tooltip.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b2
Issue solved.
