### ISSUE TITLE
Failing to open datatable after changing languages 

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3576]
To replicate: 

Load
http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html?keys=JOSM 

Change languages one time and try opening the datatable (it should be stuck loading). 

Change languages again and try opening the datatable (it does not load). Attempting to open the datatable in this case gives this error: 

![opening datatable changing languages issue](https://user-images.githubusercontent.com/31557789/59353806-cb759b00-8cf1-11e9-8c3c-fef7fd680346.PNG)

Changing languages in general will also cause a lot of additional errors but that is covered in #3534.

**Comment by yileifeng** [comment]
Check again (should work?) if #3578 is merged

**Comment by RyanCoulsonCA** [comment]
Just checked. Can confirm that the data table now opens correctly after a language change.
