### ISSUE TITLE
UI Docs links don't jump to right page/page section

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3579]
**Steps to Reproduce:**

http://fgpv-vpgf.github.io/fgpv-vpgf/v3.0.0/#/ui-overview?id=_2-1-main-application-bar

1. Go to the above link
2. Go click on any one of the links you see (e.g. Import Wizard)
![image](https://user-images.githubusercontent.com/25359812/59374508-fd9af300-8d19-11e9-9e4b-0524e79d3900.png)
3. You will notice that the URL changes in the search bar but it doesn't jump to the right section of the page.

**Comment by AleksueiR** [comment]
Links used in the body of the document use this from:
`#/ui-overview?id=314-build-information`

And the docute site expects them to be in this form (notice an underscore in front of the section number and a dash separating section and subsection numbers):
`#/ui-overview?id=_3-14-build-information`
