### ISSUE TITLE
Map points are not displayed for the “EcoAction” layer.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3580]
Tested build: v3.1.0-b1
Tested with IE and Chrome.
![image](https://user-images.githubusercontent.com/38046459/59377419-350c9e00-8d20-11e9-978d-a0b976b9cc86.png)

**Comment by james-rae** [comment]
Likely was a service issue.  Layer is looking good over last month.
