### ISSUE TITLE
Update Accessibility Guidelines to WCAG 2.1 AA from WCAG 2.0 AA

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3585]
Update the [current docs ](https://github.com/ShrutiVellanki/fgpv-vpgf/blob/accessibility-docs/docs/developer/accessibility_guidelines.md) to include the  [new points](https://www.w3.org/TR/WCAG21/#x0-5-1-new-features-in-wcag-2-1) introduced in the **WCAG 2.1 AA** Guidelines. 

Whoever picks this up will need to include everything that is labelled `A` or `AA` (don't need to worry about `AAA`). 

**Steps:**
- Update the summary matrix
- Mark if each guideline is a host page responsibility or RAMP's responsibility
- If the guideline is RAMP's responsibility, add a section or subsection in the docs describing how developers should meet guideline (add examples if possible)
- Update existing links to refer to the `2.1` page
- Make sure the section numbering is correct

**Comment by dan-bowerman** [comment]
Attached is a WCAG 2.1 AA checklist. Another issue will be created for a fresh review.

**Comment by dan-bowerman** [comment]
[Accessibility BeSD Assessment_WCAG_AA2.1.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/6541685/Accessibility.BeSD.Assessment_WCAG_AA2.1.xlsx)
