### ISSUE TITLE
HTML table column data rendered incorrectly

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3588]
Column data that is HTML gets rendered as a string. Need to update the default column renderer so it can handle HTML as well as plain text. 

![image](https://user-images.githubusercontent.com/8885149/59515974-54c1d480-8e8e-11e9-954e-9aae33d66de0.png)

**Comment by YaroRoodzit** [comment]
Tested  build: v3.1.0-b2
Works as expected.
