### ISSUE TITLE
EnhancedTable: column order defined in config should be respected 

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3589]
worked on [`v2.6.0`](http://fgpv.cloudapp.net/demo/v2.6.0/prod/samples/index-samples.html?sample=39) but not on [develop](http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html?sample=39)

```js
"columns": [,
            {
              "data": "Country",
              "filter": {
                "type": "string",
                "value": "Canada"
              }
            },
            {
              "data": "Latitude",
              "filter": {
                "type": "number",
                "value": "48,49"
              }
            },
           {
              "data": "OBJECTID",
              "filter": {
                "type": "number",
                "value": "0,25"
              }
            }
]
```

^ that config should show `OBJECTID` as the right-most column

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b2
Test sample: #39 
http://fgpv.cloudapp.net/demo/v3.1.0-b2/prod/samples/index-samples.html?sample=39
 Works as expected.
