### ISSUE TITLE
Toggling visibility of one child entry shows all child entries 

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3593]
Re-test issue after #3152 is merged. 

To replicate: 

Load 
http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html?keys=JOSM 

Then: 

- change languages

- hide the parent group  

- check to toggle the visibility of one of the child entries

- data points from all the layers seem to appear on the map and in the datatable 

![one child entry enables visibility of all](https://user-images.githubusercontent.com/31557789/59529198-6024f800-8eae-11e9-84be-f59782b70f7a.PNG)

**Comment by james-rae** [comment]
Worth checking if this only affects RCS layers, or all layers.  If only RCS, can be due to funny business with layer id changing between language (e.g. `rcs.JOSM.en` --> `rcs.JOSM.fr`)

**Comment by RyanCoulsonCA** [comment]
The way the children elements work in the structured legend have been changed since this issue was posted, and with the new functionality they work as intended.

**Comment by ShrutiVellanki** [comment]
Possibly related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3637

**Comment by dane-thomas** [comment]
Pressing show all should steamroll changes down through all children, including symbology.

**Comment by dan-bowerman** [comment]
Test is this is still relevant. Close if it isn't.

**Comment by sharvenp** [comment]
This no longer seems to be an issue, toggling the sublayer visibility in the legend updates the map accordingly.

![3593_visibility_bug](https://user-images.githubusercontent.com/34178949/124829184-4566c580-df46-11eb-8efd-837dea23910c.gif)
