### ISSUE TITLE
Allow registration of export plugins

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#3599]
- Allow export plugins to register with the "export slot" (look at ESPG/table)

- Have export enter a new flow if plugin present
For now only logic should be showing the dialog

- Create a new simplified template (leave current template there too) to use when export plugins are present
Remove export sizes, title, settings, size selector and settings button.

**Comment by AleksueiR** [comment]
- export plugin slot is added
- logic to handle export plugin is partially created
- simplified template to display export plugin output is created
