### ISSUE TITLE
Create a sample export plugin

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#3603]
Create a simple sample export plugin which renders the map and watermark image on top of it for testing plugin loading and component positioning.

**Comment by AleksueiR** [comment]
Seems like I'm already working on this anyway...

**Comment by AleksueiR** [comment]
Here's a POV export image:
![sample-map (15)](https://user-images.githubusercontent.com/2285779/61140013-9bf4b280-a498-11e9-8faa-ec98dd3e2468.png)

**Comment by mpath** [comment]
Tested in Build: V3.1.0-b8
Issue Resolved.
