### ISSUE TITLE
Datatable "records shown" label is missing French translation

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3605]
`x of y records shown (filtered from z records)` label in the datatable header is hardcoded and doesn't have a French translation.

![](https://i.imgur.com/mQDKSyV.png)

![](https://i.imgur.com/LxTjyaV.png)

**Comment by james-rae** [comment]
Text can be leveraged from 2.6.0

> Affichage de l'élément 1 à 2 sur 2 éléments (filtrés de 3 éléments au total)

**Comment by james-rae** [comment]
Also, person fixing this should do a sweep of grid plugin for any other hardcoded text

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b5
Issue solved.
