### ISSUE TITLE
Label is overlapping check mark in IE .

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3608]
Test build: v3.1.0-b2
Sample #88 
http://fgpv.cloudapp.net/demo/v3.1.0-b2/prod/samples/index-samples.html?sample=88
 No issue when Chrome in use.
![image](https://user-images.githubusercontent.com/38046459/59800871-acf53e00-92b5-11e9-87ca-82dc9313d258.png)

**Comment by RyanCoulsonCA** [comment]
This is caused by the usage of `overflow-wrap` in the CSS for the column visibility menu. The legacy name for this is `word-wrap`, and this is what IE is looking for. Will PR a fix that uses both `overflow-wrap` and the legacy `word-wrap` so this works on both browsers.

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
