### ISSUE TITLE
Field in details panel not displaying correctly

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3610]
## Steps to Reproduce
1. Go to http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=75
2. Click on one of the data points from the `Hydrometric Stations` layer

## Example
Notice the `links` field in the image below.

![](https://i.imgur.com/cxYu4x4.png)

**Comment by yileifeng** [comment]
So the eventual plan to handle complex attributes such as the links attribute in this instance is found here: 
https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/17

As for this issue specifically, I am planning to just add a separate check in the HTML file to format a separate list for each of the links objects (and extract the href and title) that will look something like this: 

![new links formatting](https://user-images.githubusercontent.com/31557789/60669618-bc8b8f80-9e3c-11e9-8fe8-f062e0f6ca47.PNG)

This can at least be a temporary placeholder solution until the new feature gets implemented.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b5
Tested sample: # 66
http://fgpv.cloudapp.net/demo/v3.1.0-b5/prod/samples/index-samples.html?sample=66
Issue solved.
