### ISSUE TITLE
EnhancedTable: cutoff cell text does not appear on hover

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3614]
Found by @JahidAhmed 

e.g.  hovering over the following text (`sample 1`, `Natural Gas Pipeline`)

![image](https://user-images.githubusercontent.com/25359812/60026504-ad048d80-9669-11e9-89b0-59725342de78.png)

does not display the full text on cell hover. 

Ideally we want something like this: 

![image](https://user-images.githubusercontent.com/25359812/60026650-f3f28300-9669-11e9-885a-f5623b215559.png)

**Comment by ShrutiVellanki** [comment]
Thought this would be a simple fix (adding the `title` attribute to the cell so that it displays the full text on mouse hover). However this hover does not activate when using keyboard navigation. This excludes sighted keyboard users from looking at the full cell text. 

Solution to this was suggested by @AleksueiR: 

> The best approach for solving this seems to be in providing an on-focus tooltip/popup with the full text of the table cell. Not just on-hover though. This tooltip potentially might have long text strings and I think it would be better if it didn't disappear when the mouse cursor is moved away.
> This was actually already implemented in at least version 2.6:
> ![image](https://user-images.githubusercontent.com/25359812/61058061-8615bd80-a3c4-11e9-9c11-26ebc9ef8d2f.png)
> http://fgpv.cloudapp.net/demo/v2.6.0/prod/samples/index-samples.html ("Liquids Pipeline" layers, row 12)

Will revisit a few days / weeks later after Centralized Feature Design Work is done. Free for pickup.

**Comment by mpath** [comment]
Tested in Build: V3.1.0-b8
Issue Resolved.
