### ISSUE TITLE
Minor console error after reload

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3625]
Sample 3. 
If you reload the layer using the legend parent option menu (i.e. Click `...` for Energy Infrastructure of North America legend row; click `Reload` at bottom of options panel), the layer will reload but will get a null dereference console error.

The following line in `toc.service.js` is what's blowing up, and likely needs to be changed to check that `proxyWrapper` exists (or fix something else to ensure it exists)

```text
// clear the state for the datatable to match the refreshed legend
var fs = legendBlock.proxyWrapper.filterState;
```

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
