### ISSUE TITLE
Magnifying glass and checkbox overlap

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3631]
Tested build: v3.1.0-b4
Test sample : 91
http://fgpv.cloudapp.net/demo/v3.1.0-b4/prod/samples/index-samples.html?sample=91

See attached for clarity.
![image](https://user-images.githubusercontent.com/38046459/60685936-ed3aeb80-9e73-11e9-9509-ea2a31726bcb.png)

**Comment by AleksueiR** [comment]
The magnifying glass icons shouldn't be even displayed in this case.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b7
Issue solved.
