### ISSUE TITLE
Number filter shows NaN on table reload

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3632]
## Steps to Reproduce
1. Open the table of a layer that includes a number filter
2. Type a number into the filter (either `max` or `min`)
3. Either reload the table or close and reopen it

Tested on `develop` build
## Example
![](https://i.imgur.com/b2DMUN7.gif)

**Comment by YaroRoodzit** [comment]
Tested build: v 3.1.0-b7
Sample: 1
Issue solved.
