### ISSUE TITLE
Issues opening WFS data grid

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3634]
Am frequently seeing problems attempting to open the data grid when a WFS layer is involved. The grid will march the loading counter to the maximum and then never draw, with the progress animation at the top constantly re-starting.

See Sample 66, Hydrometric layers.

> TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
Uncaught Error: ag-Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage.

**Comment by YaroRoodzit** [comment]
Tested build:v3.1.0-b7
Sample : 66
Issue solved.

**Comment by YaroRoodzit** [comment]
Tested build: v 3.1.0-b7
Sample: 66
Issue solved.
