### ISSUE TITLE
Toggling visibility of child symbology turns on parent item

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3637]
Possibly related: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3593

Follow these steps: 
- hide the parent group
- check to toggle the visibility of one the child entries *off*
- parent layer is turned back on (this shouldn't happen anymore unless parent layer is explicitly turned back on)

![daGif](https://user-images.githubusercontent.com/25359812/60739191-05237580-9f2f-11e9-84f3-84ff992d6a42.gif)

**Comment by james-rae** [comment]
Ideally this gets auto-fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3630 . The invisible layer will have all symbols unchecked; checking the first symbol will turn on the visibility

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b7
Issue solved.
