### ISSUE TITLE
Geosearch takes a long time with certain queries (especially clear filter)

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3638]
Found by @YaroRoodzit 

http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html

1. Open geosearch
2. Type `Park`
3. Select `Alberta` as province
4. Takes a while to show there are no matching results (1st problem)
5. Click `Clear Filters`
6. Takes a *really* long time to show all the results for `Park` again (2nd problem)

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
