### ISSUE TITLE
Track Layer Loading in GeoAPI

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3639]
Design can be found [here](https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/10)

Will track the layer loading state in the `LayerRecord` hierarchy within geoApi. This will include the handling of special cases such as file-based layers and WMS with pre-canned capabilities.

Will then remove the custom logic throughout the viewer core and instead utilize the new simpler properties in geoApi.

Simultaniously, will update the ESRI API to the latest version and mitigate the problems caused by the changes in the loading flag behaviors (which is why RAMP is currently parked on v3.22)

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b7
Works as designed.
