### ISSUE TITLE
Zeros in CSV co-ord columns appear as blanks in the grid

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3652]
Any lat or long value in a CSV file that is `0` will get processed correctly when creating the point geometry, but in the datagrid the value is blank.  Only seems to affect the lat or long fields, zeros in other fields show as `0`.  Probably some falsey logic at work

**Comment by mpath** [comment]
Tested in build: v3.1.0-b8
Issue resolved.
