### ISSUE TITLE
Accessibility issue with 'More Options' button in legend

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3663]
# Steps to Reproduce
1. Open any sample ([here's one](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html?sample=1))
2. Press `tab` until one of the `more options` buttons for one of the layers in the legend is selected
3. Press `space` or `enter` to open the `more options` menu
4. Press tab to try and navigate through the options
5. Notice that the menu closes after pressing `tab` once

# Example
![accessibilitymoreoptions](https://user-images.githubusercontent.com/25874602/61534801-90583d00-a9fe-11e9-9a77-c1574ace1d6c.gif)

---
Tested in Chrome

**Comment by ShrutiVellanki** [comment]
As far as I know, this is actually intentional. To navigate through the menu items we use the up/down arrow keys on the keyboard. 

Though if it was confusing to you it may be confusing to others so it still brings up an interesting point...

**Comment by RyanCoulsonCA** [comment]
That makes sense. Related to `More options`, this is a bug I found when trying to navigate through the menu with the first item disabled:

![accessibilitymoreoptions1](https://user-images.githubusercontent.com/25874602/61544195-edf68480-aa12-11e9-8a75-ebc7f6575c24.gif)

**Comment by ShrutiVellanki** [comment]
@RyanCoulsonCA nice catch! Looks like a regression because we had this exact issue before: 
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3387

you can look at the fix, it should be similar

**Comment by RyanCoulsonCA** [comment]
> @RyanCoulsonCA nice catch! Looks like a regression because we had this exact issue before:
> #3387
> 
> you can look at the fix, it should be similar

Looks like the code was accidentally removed in a previous PR. I've re-added your code to fix it in this PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3666.

**Comment by AleksueiR** [comment]
"accidentally removed" translates to "muffins"

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b7
Works as expected.
