### ISSUE TITLE
Enhanced Table: Column Filters not respected when hidden on table reopen

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3674]
Steps to reproduce: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html

1. Open `Natural Gas Pipeline`
2. Type `Mexico` in `Country` column
3. Toggle off `Show Filters` from the table menu, you'll notice filters are gone, but table is still filtered to show only `Mexico` values for `Country Column`

![image](https://user-images.githubusercontent.com/25359812/61888843-470e5e80-aed2-11e9-9703-f93171c9a83a.png)

4. Close and reopen the table --> The table is unfiltered

![image](https://user-images.githubusercontent.com/25359812/61888931-7d4bde00-aed2-11e9-9763-f6a5d991436d.png)

5. Toggle on `Show Filters`, the table is filtered for `Mexico` again

![image](https://user-images.githubusercontent.com/25359812/61888969-99e81600-aed2-11e9-87e2-886cc28d39a2.png)

**Comment by ShrutiVellanki** [comment]
This may be similar: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3494

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b2
Issue resolved.
