### ISSUE TITLE
Minor filtering bug when re-opening grid 

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3675]
To reproduce: 

Open the datatable for any layer. Filter a column using at least one special character: 
![FILTERBYCOMMA](https://user-images.githubusercontent.com/31557789/61902434-176e4f00-aef0-11e9-9973-35e98152af51.PNG)

Close and re-open the table to see that the filtered value has a backslash `\` in front of the special character. 
![FILTERBYCOMMARELOAD](https://user-images.githubusercontent.com/31557789/61902443-1d643000-aef0-11e9-8896-34240b08339e.PNG)

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
