### ISSUE TITLE
Can't select text from grid cells

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3681]
## Issue
You can't select text using the mouse within grid cells. This was possible in v2.6.0.

## Steps to Reproduce
1. Open any sample
2. Try to select the text in a grid cell using the mouse

## Example
![](https://i.imgur.com/V9uMmka.gif)

**Comment by mpath** [comment]
Tested in Build: V3.1.0-b8
Issue resolved.
