### ISSUE TITLE
Applying filters to map for lat/long coordinates 

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3689]
To replicate: 

Convert the test file to CSV format 
[test.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3453522/test.xlsx)

Import the file and filter either the `LAT` or `LONG` columns. Click on apply filters to map and notice that there are no changes being made. 

A possible reason for this bug is that the grid is not checking that the filter is an integer, treating it as a string (looks like there is a `toUpperCase()` call in `filterToSql` in `panel-manager.ts` with no check that may be relevant) and when the filter is being converted to SQL and passed to GeoApi, it would fail.

**Comment by james-rae** [comment]
Worth looking at how the attribute becomes an number in the first place.
Adding a CSV goes CSV --> GeoJSON --> ESRI JSON --> Feature Layer.

With GeoJSON, every attribute is treated as a string (there is no data-typing of attributes in GeoJSON).

CSV is a bit special in that those two attributes are plucked out to create the geometry as well, so they might be getting casted to numbers, or perhaps are injected back into the attributes afterwards.

Also worth noting that having them in number form in the grid is useful (you can filter on a range of co-ords).  But would need some special logic to know these GeoJSON-based fields are not strings as one would expect.

**Comment by RyanCoulsonCA** [comment]
Quick addition: This error is printed in the console when clicking `apply to map` with a filter on `LAT` or `LONG`

![](https://i.imgur.com/6kHyB1q.png)

**Comment by james-rae** [comment]
yep the grid is confused and thinks its strings, as is wrapping it in `UPPER()` when it exports the filter in SQL. Then AQL tries to uppercase a number. 🎉

**Comment by mpath** [comment]
Tested in Build: V3.1.0-b8
Issue resolved.
