### ISSUE TITLE
Grid number filters dont allow negative symbol

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3694]
A user cannot type the `-` symbol in a min/max filter box in the data grid.  However you can compose a negative number in `notepad.exe` and then paste it into the filter box ok.

[This service](http://section917.cloudapp.net/arcgis/rest/services/TestData/Oilsands/MapServer/0) has negative numbers in the `longitude` field

**Comment by mpath** [comment]
Tested in build: V3.1.0-b8
Issue resolved.
