### ISSUE TITLE
Stack icons not visible with collapsed legend

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3695]
Analysis by @ShrutiVellanki 

@JahidAhmed noticed that https://indicators-map.dev.ec.gc.ca/App/CESI_ICDE symbology stack wasn't showing up when the legend was collapsed.

Looks like a style of `visibility:hidden` or `visibility:visible` was being applied to this element.

- I searched for modifications of it through `style.visibility = hidden` in the codebase
- I searched for `visibility:hidden` in the stylesheet

no results for either of the two so looks unintentional. Set visibility to `inherit` which seems to preserve style for other samples as well.

**Comment by mpath** [comment]
Tested in Build: V3.1.0-b8
Issue resolved.
