### ISSUE TITLE
Apply negative number values filters to map

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3699]
To reproduce: 

Use any layer with lat/long columns. Typing in a negative value to filter lat/long columns and applying to map will not work (this cannot be reproduced until #3698 is merged, so just trust me until then) 

The problem looks to be in the `sqlNodeToAqlNode` in `query.js`, where support is required to handle prefixes such as `-`. If anyone can think of additional prefixes that may need handling, comment below.

**Comment by james-rae** [comment]
Looks like `+` is a valid prefix. The new `Prefix` type handler should accept it and do nothing.

**Comment by mpath** [comment]
Tested in build: V3.1.0-b8
Issue resolved.
