### ISSUE TITLE
Upgrade to Angular 1.6.3

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#370]
Release notes: http://angularjs.blogspot.ca/2016/02/angular-150-ennoblement-facilitation.html
Migration guide: https://docs.angularjs.org/guide/migration#migrating-from-1-4-to-1-5

**Comment by AleksueiR** [comment]
I check the 1.4 -> 1.5 migration guide, and it doesn't seem any of the breaking changes will affect us.

**Comment by milesap** [comment]
Should we go to 1.5 or to 1.6.2? Haven't looked at their differences yet, but this issue was open for a while.

**Comment by milesap** [comment]
Going straight to v1.6.3

#### Testing
Any and all things can be broken - but generally it looks good. There may be some odd issues that crop up, please test in all browsers as well.
