### ISSUE TITLE
Double negative sign filtering for numeric columns

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3702]
To reproduce: 

Open any datatable that contains a lat/long column (or any number column). 
Type in two consecutive negative signs and notice that the filter value is replaced with a maximum negative number value. 

![doubleNegativeNumFilter](https://user-images.githubusercontent.com/31557789/62871770-17d95900-bcea-11e9-8cde-4bce54c67125.PNG)

This should instead never be allowed as the filter input since double negative sign is not a valid number to filter. This is related to the solution for #3694 and is likely an edge case that needs to be checked since a single `-` is currently being treated as a `Number.MAX_VALUE` to properly apply grid filters.

This would also be an edge case that needs to be handled in GeoApi when checking for prefixes, as there is no numeric value following the `-`.

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b1
Issue resolved.
