### ISSUE TITLE
Show all sometimes works for dynamic layers

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3707]
The `show all` functionality in the legend doesn't work consistently with dynamic layers that have multiple symbology in its stack.

Tested using Sample 1 and RCS key `NPRI_CO`

**Comment by james-rae** [comment]
possibly related https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3763

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Tested by Sample#88.
Issue solved.
