### ISSUE TITLE
bug(ui): zoom to feature from datatable blanks out overview map

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#371]
Steps:
1. Load viewer; ensure overview map is working 
2. Open TOC
3. Open datatable panel for a layer with some data
4. Click on any row; see the map zoom
5. Close datatable panel
6. Observe the overview map is blank now.

The overview map is restored after you manually or zoom the map.

**Comment by mweech** [comment]
Could not reproduce.  May have been fixed with the basemap loading as Dynamic layer fix.
