### ISSUE TITLE
Enhanced Table does not load in IE

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3722]
## Issue
The table doesn't open for some layers in IE. The following error is printed in console:
![](https://i.imgur.com/fulHISB.png)

The issue is that Number.isInteger is not supported in Internet Explorer, so a workaround will have to be found.

## Steps to Reproduce
1. Open the [sample page](http://fgpv-app.azureedge.net/demo/branches/develop/dev/samples/index-samples.html) in IE.
2. Try to open the table for one of the layers
3. Notice that the table does not open.

**Comment by AleksueiR** [comment]
test comment -- please ignore
