### ISSUE TITLE
Investigate build failing to deploy docs

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3726]
The docs generation and deployment to ghpages is no longer being triggered on tagged builds. Seems to have started around the time the build was changed to start deploying to an Azure CDN. Investigate/fix and re-point the v3.1.0 tag.

**Comment by AleksueiR** [comment]
Do you know what caused the breakdown?

**Comment by milesap** [comment]
I "think" it is being caused by an incorrect `.travis.yml` configuration. Travis used to log the doc deployment (either performed or skipped) but now there is no mention of it. The yaml is valid syntax but likely contains a subtle change that makes Travis ignore it.
