### ISSUE TITLE
Double scroll bar in GeoSearch

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3734]
Only seems to occur in Chrome and Edge.

The outer scroll bar shouldn't be there, and it does not react to mouse events (if you click or drag the scroll bar, the map reacts to the action)

![doublescrool](https://user-images.githubusercontent.com/7585245/64280318-d3269380-cf1e-11e9-909d-0d68133510d2.jpg)

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b2
Issue resolved.
