### ISSUE TITLE
Fancy character filters acting funny in lazy filter mode

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3736]
Discovered by @mpath 

See sample 88, layer `Keyword Search`.

Open table, scroll to column `Program Contributions`. 

This field has money amounts as text, so things like `$123,456`.  Filtering on the number characters works fine, but attempting to filter on the `$` or `,` result in no rows.

Note that this layer has the `lazyFilter` enabled in it's configuration (this means you don't need to put a `*` at the beginning of a search to match items in the middle of the string)

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b2
Issue resolved.
