### ISSUE TITLE
No horizontal scroll in empty table in Chrome

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3737]
Using Chrome: 
See sample 88, layer `Keyword Search`.

Open table, enter an invalid search in a text field (something that will match no rows). 
The table removes all rows (correct).
The scroll bar disappears from the bottom of the grid (bad!).

The focus also tends to leap, so if you type the bad filter in a column thats not in the initial view, it then jumps off screen and you can't scroll back to it; your only course of action is the clear filters button.

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b2
Issue resolved.
