### ISSUE TITLE
bug(ui): improve formatting of feature details

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#374]
In the details pane (opened by clicking a map feature), two things can be improved

* the left column (the field names) uses an ellipsis to hide long names. Add some type of thing that will show the full name if the mouse hovers over it (see RAMP as an example of this).
* if the right column has a long value that does not have a breaking character, it will add a horizontal scroll bar. Some CSS magic is likely required

![feature](https://cloud.githubusercontent.com/assets/7585245/13537110/48423524-e211-11e5-84db-f42f42e85fd6.jpg)

**Comment by james-rae** [comment]
Was not touched last week.  Fixes still pending

**Comment by james-rae** [comment]
Still not touched, Spencer has volunteered to take it on.  Alex has indicated the "popup over truncated text" is difficult

**Comment by spencerwahl** [comment]
In PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/540

![image](https://cloud.githubusercontent.com/assets/8732588/14897280/6832b368-0d4f-11e6-8b23-0d36e3dd0960.png)

![image](https://cloud.githubusercontent.com/assets/8732588/14897300/7faba5cc-0d4f-11e6-810d-d5d5880a8519.png)
