### ISSUE TITLE
Regression: Delay drag-n-drop start on mouse move

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3752]
The fix for #821 got steamrolled since May 25, 2017 https://github.com/fgpv-vpgf/fgpv-vpgf/commit/017dbefe50d5a92d2d55d3bf4e2fbffbaba5843e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L95, but no one noticed it since more of our sample pages are structured legend where it's not possible to reorder layers.

Demo:
http://fgpv-app.azureedge.net/demo/branches/develop/prod/samples/index-samples.html?sample=54

**Comment by mpath** [comment]
Tested in Build: V3.2.0-b2
Issue resolved.
