### ISSUE TITLE
Global table search incorrect map filters for coordinates

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3754]
To reproduce: 

http://fgpv-app.azureedge.net/demo/branches/develop/prod/samples/index-samples.html?sample=1 (or any table with coordinate values) 

Use `Natural Gas Pipeline` or any other layer with coordinate values. 

In global search, filter with a coordinate value such as `31.334` and click apply to map. 

The data point(s) is not reflected on the map and filtering with something like `334` also fails so it does not appear to be a decimal point related problem or special chars related problem. 

However, using global search for `31.` and applying to map will show a point on the map with its `volume` attribute containing `31.` so it looks like global search is not working specifically for the lat/long coordinate columns. 

Will need to test against both file-based and ESRI layers as the SQL parsing can be different.

**Comment by yileifeng** [comment]
May be related: 

After applying to map for a coordinate value, try entering a completely different coordinate value (e.g. `32.67`). 

The apply filters to map will remain disabled as it still does not detect any results. This should hopefully be fixed once the global search map filters for coordinate values are fixed.

**Comment by yileifeng** [comment]
More strange global table search behavior: 

For `Natural Gas Pipeline`, enter `naco` in global search and all filters work appropriately. Then, enter `naco mexico 2` and the table remains filtered but map filters will not work. Not at all sure what the intended behavior here is supposed to be as global search does not follow `lazyFilter` rules.

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Tested by Sample#1.
Issue solved. 
Global search works properly for coordinates or any other filters.
