### ISSUE TITLE
Enhance the look of the projection warning

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3759]
The warning is very informative, but covers half of the title.
Propose ideas to make it nicer.

![Reproject](https://user-images.githubusercontent.com/7585245/65349769-3d436780-dbb2-11e9-8c83-3a7f17c96a3d.png)

**Comment by AleksueiR** [comment]
We used to have this warning before:
![](https://i.imgur.com/iFDg4JX.png)

I could only find it back in 1.7:
http://fgpv-app.azureedge.net/demo/tags/v1.7/prod/samples/index-one.html

Maybe we can just lift the relevant code.

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b3.
Works correctly. By design.
