### ISSUE TITLE
Match map filters with global table search quick filters behavior 

### ISSUE THREAD

**Issue by yileifeng** [fgpv-vpgf/fgpv-vpgf#3762]
Comes from: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3754#issuecomment-532274227 

Ideally would like to match behavior of global table search's use of quick filters seen here: https://www.ag-grid.com/javascript-grid-filter-quick/ to keep the filtered results consistent between the table and map filters. 

Quick filters will check all searched words against the full row and only return rows that contain all the keywords. 

For example: http://fgpv-app.azureedge.net/demo/branches/develop/prod/samples/index-samples.html -> `Natural Gas Pipeline` -> global search on `naco morgan` -> one unique result is produced in the table -> apply to map (no points shown)

- Would require splitting the search value on spaces and processing the sql differently based on this.

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Tested by Sample#1.
Issue solved.
Global search works properly for all searched words.
