### ISSUE TITLE
Issue with Toggle Visibility for Sample 88

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3763]
Tested in Build: V3.2.0-b2
Noticed that Toggle visibility does not work for Sample 88

Steps to reproduce:
1.Go to Sample 88 and click Hide All. Layers are hidden as expected.
 2. Click Show all, notice that Liquids pipeline and 2 Column filter layers are marked and shown on Map. However, Keyword search layer is not marked and not shown on map.

![Issue with Legend smaple 88](https://user-images.githubusercontent.com/46937257/65355094-25261500-dbbf-11e9-9c9c-bcb84ae9d988.JPG)

Reproducible in all browsers. 

Test Case # 57985
Test case link:  http://tfs.int.ec.gc.ca:8080/tfs/DC/RAMP/_testManagement?planId=57899&suiteId=57983&_a=tests

**Comment by RyanCoulsonCA** [comment]
This issue is fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3766.

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b3
Issue solved.
