### ISSUE TITLE
Clicking show all button breaks symbol memory

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3767]
## Steps to Reproduce
This is easier to reproduce using [this](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3707/dev/samples/index-samples.html?sample=88) demo (the fix for https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3766), but I've been able to replicate the bug on `develop` a few times as well.

From @james-rae:
> * Click Hide All
> * Click Show All
> * Expand symbols for keyword search.
> * Uncheck one of the symbols.
> * Turn visibility of keyword search off
>  * Turn visibility of keyword search on.
>
> You'll see the unchecked symbol is now checked again. It looks like the Show All command causes the symbol memory to break for one round of layer visiblity toggles. If you repeat the symbol visibility routine it will work the next time

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Tested by Sample#88.
Issue solved.
