### ISSUE TITLE
Map `click` observable behaviour

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#3768]
The `click` observable on the map API only emits on an identify, not in other cases such as when the 2nd click removes the identify highlight (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2604).

Need to emit whenever a user clicks anywhere on the map (based on documentation): "Emits when a user clicks anywhere on the map or when an identify operation is performed"

Other behaviour should also be discussed such as when an identify happens through the API `mapApi.identify(<XY>)` and keyboard identify, this will cause the observable to emit as well.
- However based on current documentation, API identify seems like expected behaviour: "This includes identify requests made via the API method `identify`"

**Comment by james-rae** [comment]
> Other behaviour should also be discussed such as when an identify happens through the API mapApi.identify(<XY>) and keyboard identify, this will cause the observable to emit as well.

Our observable result object has the bonus property `apiInitiated` to let listeners know if a real device was involved or not.
