### ISSUE TITLE
 Project description text is cut off for first row within data table in maximize mode

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3770]
Tested in Build: V3.2.0-b3
Sample 92 of Index-samples.html

Project description text is cut off for the first row when checking Fancy Plants/Clean Air data table in maximize mode. Reproducible with Azimuthal Equidistant Maps and Lambert Map of Sample 92.

![Azimuthal map](https://user-images.githubusercontent.com/46937257/65632896-c4288380-dfa8-11e9-87f9-ce5a54c487bf.JPG)

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Tested by Sample#92.
Issue solved.
