### ISSUE TITLE
Table tooltip sometimes doesn't show up

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3775]
## Issue
There are cells that contain text that are slightly too large to display in their entirety, but are not large enough to display a tooltip. Currently the only way to view the full text is to click the `details` button.

## Steps to Reproduce
1. Visit [this](http://fgpv-app.azureedge.net/demo/branches/develop/dev/samples/index-samples.html?sample=1) sample page
2. Open the table for the `Natural Gas` layer.
3. Click on the cell under `Name of Pipeline` for `OBJECTID = 3`. Notice how the cell contents is cut off, but no tooltip appears.

## Example
![](https://i.imgur.com/GRnFVo8.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Issue solved.
