### ISSUE TITLE
bug(ui): datatable zoomTo target should be offset

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#378]
When zooming to a feature from a datatable, the map centers on the point which gets positioned on the lower edge of the datatable panel. As the panel takes half of the vertical space, the zoomto target should be offset "up" so the actual point ends up in the center of the visible half of the map.

**Comment by cynngah** [comment]
just need to wire up calculations to the offset and do some testing to make sure it's working
