### ISSUE TITLE
API JsDoc Site is not up to date

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3786]
Appears the API docs generated from JsDocs are not getting updated on pushes to `master`

e.g. [ConfigLayer page](http://fgpv-vpgf.github.io/fgpv-vpgf/ghpages-docs/developer/api_tech_docs/classes/_api_src_layers_.configlayer.html) does not have `setFilterSql` function anywhere on it.

**Comment by milesap** [comment]
The monorepo changes seem to have altered a large portion of the old build process. Build scripts found in v3.2.0 are missing on master:

https://github.com/fgpv-vpgf/fgpv-vpgf/tree/v3.2.0/scripts
https://github.com/fgpv-vpgf/fgpv-vpgf/tree/3c2e3160dee44ed2a9fa908368eab2f1f1c66f39/scripts

Assigning to @spencerwahl to check that the changes introduced with the momorepo did not break/remove needed build steps.

**Comment by spencerwahl** [comment]
Those scripts are sitting in https://github.com/fgpv-vpgf/fgpv-vpgf/tree/3c2e3160dee44ed2a9fa908368eab2f1f1c66f39/packages/ramp-core/scripts

I assume the travis folder should be moved to the root, does anything else need moving?
