### ISSUE TITLE
Feature Layer missing outfields config option

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3787]
The `outfields` config option appears to only be implemented for child layers of Dynamic Layers. This option lets you only take a subset of attributes from the server instead of all of them (will impact size of attribute set download).

Don't see a reason why the same option shouldn't be available for Feature Layers, as it utilizes the same attribute download engine

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b2
Issue solved.

**Comment by james-rae** [comment]
Additional enhancements found in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3803
