### ISSUE TITLE
WCAG Keyboard accessibility with FireFox

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3810]
In FireFox, the keyboard become unaccessible as soon as we click on close side menu from the keyboard. On the legend menu, the show/hide all and expand/collapse groups does the same thing. I did a quick test and find other problems (basemap from menu bar, enter basemap selection, close not inside the focus element so I hit ESC key... lost keyboard focus. Hit ESC on side menu does the same thing. I think It may be good to round of WCAG tests on FireFox if we want to support it. If not, we will have to say it is not fully supported inside our doc.

**Comment by YaroRoodzit** [comment]
Tested build: v3.3.0-b3
Tested  with FF and Chrome.
Issue solved.
