### ISSUE TITLE
feat(core): prevent map breaking if rcs goes down

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#382]
In case some config partials can't be retrieved (right now everything just breaks), load the map with the local config if any.
Display an appropriate message to the user.

https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/386#-KCatfOjt1UsYMp5CFI7

**Comment by spencerwahl** [comment]
PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/506
