### ISSUE TITLE
WCAG - Unnamed buttons in Settings panel

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3849]
From the OSDP WCAG review - 

> The map is non-text content and not all of the purpose or functionality are accessible via text alternatives.

Many of the buttons available in the "Settings" (aka "...") section do not have names. Give them names that describe their function.

**Comment by spencerwahl** [comment]
I have not been able to find any buttons without an `aria-label`. I found two buttons in the table that were labelled `Menu` instead of anything specific.
