### ISSUE TITLE
WCAG - Data grid: column headers need to be related to column data

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3850]
From the OSDP WCAG review - 

> The Data table feature generates inaccessible data tables. The data tables do not have   column headers identifying the content or purpose  of the columns.

If at all possible, associate header cells with their respective data column; add aria relationship to the row/columns. May not be possible with generic data?

**Comment by james-rae** [comment]
Related older issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3805

I did a spot check on one of the test pages and could find a `role="columnheader"` tag in every column header. We're hoping Darold can provide us a sample where columns are existing without the tag.

Other possibilities are

- tags are there but in the wrong spot (column headers have many many DIVs for a box of text)
- there is another tag besides `role` that they are expecting
- the columns that house the icon and action buttons have no text (primarily to allow them to stay slim), could be this is the root of the issue

**Comment by JahidAhmed** [comment]
Looked into the possibilities James mentioned above and other Aria attributes, but need to clarify/research this a bit further. Will continue with this after Github Actions migration is complete.

**Comment by dan-bowerman** [comment]
We haven't heard any more about this one, and everything looks correct on our end. If reproduceable steps are provided to show us the problem, we can revisit this if need be.
