### ISSUE TITLE
GeoMet WMS is choking the viewer when trying to consume and display layers

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3855]
The GetCapabilities function calls from GeoMet are returning too much data (12+MB of XML, and growing) and this is affecting the RAMP viewer in the FGP Catalogue when viewing individual GeoMet-hosted services. This is largely due to a limitation in Esri’s JavaScript API. Changes to the Catalogue strategy for harvesting metadata from the service did not succeed. It looks like the change needs to be made to RAMP to resolve. 

From James on Slack:

> - Original code, when you make a WMS layer, the ESRI api asks the server for all its metadata and uses that to populate most of the WMS layer object.
> - When we started using the GeoMet services in CCCP (aka Tom Server), we found the metadata response was around 14 MB. Would cause "too big" errors if using a proxy, time out errors if usings CORS.
> - A new flag was added to the RAMP config to stop ESRI from getting that metadata. When the flag is on, we provide fake metadata to the WMS layer and that stops it from asking the server. Currently our fake metadata only contains the basics scraped from the layer config -- the layer id and the text name of the layer.  This was enough for the CCCP project, since it was very customized (no wizard, no default legend symbols...everything was hardcoded structured legends).
> - NrCan is now trying to consume stuff from the Tom Server and encountering similar issues. Since they are using a lot of the default stuff in RAMP, the workarounds we added for CCCP project are not good enough. In particular, because the fake metadata only has layer id and name, there is no auto-magic grabbing of the WMS legend image (while ESRI servers expose a symbol stack, WMS usually just has an image of a legend).  Note that the Tom Server can take a special parameter to return a much smaller metadata (focused on specific layers), but the ESRI api can't run that parameter, it can only ask for everything. We can make the special call with custom code.
> - I've looked at the code and the ESRI api and have a few ideas, but need some feedback from NrCan for what is feasible on their end. (edited) 
> 
> **Config Only Solution**
> - We add another optional property in config schema wmsLayerEntryNode where a legend url can be supplied.
> - NrCan adds that url value in each alternate-rcs entry
> - Our no-capabilities logic uses that url in the fake metadata
> - Possible we will need some additional changes in the code that extracts legend from the layer. Need to see if the layer structure remains the same or not.
> - Doing this will not pick up any changes to the legend url in the service. If Tom updates a legend url on the server then we’ll have a dead link until alternate-rcs gets updated
> 
> 
> **Layer Load Solution**
> - We would somehow have to make an asynch web call prior to creating the WMS layer to fetch the legend url. This pipeline is synch right now.
> - Alternative is see if we can inject the legend url after layer creation. Then we can have the asynch part be another element of the “loading” activities, and shove the result into the layer between “loading” and “loaded” phase.
> - The web call would be dealing with XML result, not JSON. Assuming our lib can handle that? We really don't make these calls in ramp. Can we use the wizards getCapabilities function (would need some modding)?
> - The code is risky, because the technique would work on Tom server but could fail on other WMS. The "layers" param on GetCapabilites is a special add on.
> - Also the "legend" structure in the XML can vary quite a bit, if memory serves. Would we code just for one expected structure? Support every possible XML spec?
> 
> Looks like any support for WMS "styles" would not work in either solution. The ESRI fake metadata class only has room for a legend url.

**Comment by jolevesq** [comment]
Hi @dan-bowerman. Do you know when you will start to work on this and how long it will take. We have many request from clients to access this WMS. Thanks!

**Comment by dan-bowerman** [comment]
Hi @jolevesq, we will be addressing this shortly, I do not have an exact ETA but expect a new release in the next few weeks. I'll reach out to you when this happens, or if we have questions about the problem.

**Comment by dan-bowerman** [comment]
James has info to share here with Ryan and Yi Lei for a potential solution.
