### ISSUE TITLE
WFS3 GeoMet layers do not work in RAMP when consumed via pygeoapi 0.9.0 endpoint

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#3857]
MSC has updated their `pygeoapi` library from 0.6.0 to 0.9.0, which closes a lot of URL parameters we were previously using to obtain desired results in the CDV.

We are working with this service (internal to ECCC only): https://api.wxod-dev.cmc.ec.gc.ca/collections/ltce-stations/items 

Stuff to do:
1. Modify how RAMP3 handles these services. Ensure 0.9.0 and 0.6.0 can be worked with interchangeably (Tom says we don't need to support both, but given timelines and unknowns, we should assume we need to support both for the next release). 
2. For testing, work with existing datasets that has already been migrated to 0.9.0: https://api.wxod-dev.cmc.ec.gc.ca/collections?f=html, make sure they display correctly.
3. Then add LTCE as new layers, with stub entries as necessary, to drive client discussion for how they want to lay it out in the mapping application. 

**Notes from BeSD**:
- Spencer: For reference, here is a query that RAMP would currently make;
https://api.wxod-dev.cmc.ec.gc.ca/collections/ltce-stations/items?request=GetFeature&resultType=hits&limit=0 

- The issues we have found;
  - `resultType` makes queries on the new layer fail, only ‘`resulttype`’ works
  - `resulttype=hits` makes both old and new layers return no items
  - `request` makes queries on the new layer fail
  - `limit` is now forced to be strictly positive; we used ‘limit=0’ previously to get the number of items in the WFS before trying to get any data

- Spencer: This seems to be the spec they're working against; http://docs.opengeospatial.org/DRAFTS/17-069.html

**Notes from Tom**:
- TK: given pygeoapi is pre 1.0 we are not expected to have backwards compatibility.  We are doing this to iterate along with _OGC API – Features_ (no longer called WFS3)
- timeline: we are awaiting an OPS deploy date from SSC and will relay accordinglyQ
- Q: Are these changes specific to GeoMet, or should we be anticipating every WFS3 service to follow soon?
TK: it depends on the changes
The limit change was an update to OGC API – Features
	the resultType= -> resulttype= was pygeoapi specific
	request= was never supported
- Q: Are there any 0.9.0 services available externally that we can work with while we implement these changes? 
TK: you can test demo pygeoapi services at https://demo.pygeoapi.io which can help 
(Dan: Stable appears to be 0.8.0 while master is 0.10.0.. need more clarity on release schedule and stability of access to data)
- Q: What is the risk that a future version won’t break our application compatibility with these services? 
TK: at this point I would say the risk is low given the ratification of OGC API – Features proper.  We will ensure that Kevin coordinates with your team accordingly given he goes through the same exercise when updating the climate data extraction tool UI when we update our pygeoapi setup

**Comment by spencerwahl** [comment]
The spec mentioned above was before I knew that WFS3 is now called "OGC API - Features"; https://www.ogc.org/standards/ogcapi-features

Going to work against the specs there as well as what I can find out from pygeoapi demos
