### ISSUE TITLE
Build process is not transpiling to raw javascript

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3867]
The output library (`rv-main.js`) contains arrow functions (`() => {}`) and thus won't run in IE11. This appears to have been the case since `v3.3.0`, which was when the build changed to use the monorepo tech.

Solution 1: work the transpiler (babel) back into the build pipeline.
Solution 2: detect IE, run code `alert('You have IE');`

**Comment by JahidAhmed** [comment]
Currently attempting Solution 1, and making some other changes to how babel works in our code. However, need to sort out a couple other build issues blocking this issue first.
