### ISSUE TITLE
Navbar Icon Spacing Appears Off

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3884]
Appears to be either extra padding below the divider lines, or some of the icons are not being centered in their zone.

Given the bar is hanging over the scale pane, I'm guessing there is extra padding somewhere.

![navbar2](https://user-images.githubusercontent.com/7585245/115409365-aee4fc80-a1bf-11eb-9998-b2db81d88c48.png)

**Comment by an-w** [comment]
Looks like it's from a `margin-top` added each `.rv-icon-16` from [this PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3773/files#diff-24b1fc4317a8f9638c55799a47880ad9ba52651f39465d8e9c5d00c371221ac6R160). Also affects the help search box.

![Screenshot 2021-04-20 103816](https://user-images.githubusercontent.com/70066822/115416390-bf987100-a1c5-11eb-8a32-15b48091705d.png)
