### ISSUE TITLE
Firefox overview map gone

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3906]
When we navigate on this site: https://osdp-psdo.canada.ca/en/osdp/explore with Firefox, the overview map sometime is not loaded and we need to do a hard reload to bring it back. sometimes the overview map is there on load, sometimes not. If we scroll the page when the map is loading, the overview map is likely to be gone.

Tried with other site, and not able to reproduce.
Tried with this site on Mac OS and not able to reproduce

**Comment by jolevesq** [comment]
For this sample, I modify the content of details panel on opening. I think the expand button should use the content of the details panel window, but it doesn't.

You can try with this as well:

- Go to https://osdp-psdo.canada.ca/en/osdp/explore
- Search for Roberts Bank
- Click map area button on the first element
- Click on an item of the BC Major project inventory
- When click on expand (single element), the content is blank.

This layer is loaded from RCS and I use code to add configuration:
```
 // if BC layer added automatically, set template and parser
if (layer.id.contains('ea4c0bdb-a63f-49a4-b14a-09c1560aad0b')) {
   layer._viewerLayer.config._details = { parser: "templates/wms-bc-script.js", template: "templates/wms-bc-template.html" };
    layer._viewerLayer.config._featureInfoMimeType = "text/html";
}
```

It works, I am able to to use the custom details info but when we expand I get a blank page.

**Comment by james-rae** [comment]
Wasn't able to reproduce (30-some tries). 
Good idea to get some others to try (in case it's a browser version / screensize / platform thing), and do a quick look-over of the overview map initialization code to see if there are any failure points that stand out.

I did notice the site appears to be remembering my extent with some type of session storage (or some other mechanism). Could you provide details on how that is operating? Could be the restoration (which affects extent --> affects overview) is the cause, especially if you only see it on this site.

**Comment by milespetrov** [comment]
Cannot reproduce either after 20 attempts (both scrolling and no scrolling) with FireFox 88.0.1 (64-bit).

**Comment by jolevesq** [comment]
@dan-bowerman, @james-rae: So now you have been able to reproduce the bug on your side. Just let me know things you need from OSDP to help you find what is going on. Thanks
