### ISSUE TITLE
Details, table symbology issue

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3925]
When we try to add this layer: https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/FGP/PATH/MapServer/0 the details panel and the datable will not open. There is an error here https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/packages/ramp-geoapi/src/symbology.js#L246 when the code tries to find the field used for the unique renderer.

```
Drawing Info:
Renderer:		
Unique Value Renderer:
		Field 1: N/A
		Field 2: N/A
		Field 3: N/A
```

The problem with this layer is the symbology is made with Arcade and the information is not accessible from the REST end point. ESRI is aware of that but because it works with their product they are not willing, at the moment, say it is a bug and do something to have REST metadata in sync with the service.

To bypass this error, can we trap when field are not supply and use a dummy image for symbology to show in the table and details panel?

**Comment by james-rae** [comment]
Interesting catch.

For RAMP2, I think placeholder symbol makes the most sense at the moment. Code would enter the `uniqueValue` block, see the `valueExpression` property and lack of `field#` properties.

Will take some experimenting...safest approach is to convert to a Simple Renderer with one dummy symbol.  That will ensure everything symbol-related in RAMP will hang together.  The bad part of this is you lose the list of symbol descriptions (in your sample, would be "Active / Actif", "Cancelled / Annulé", etc). 

We could scrape those labels into a "fake" unique value renderer, but then I would expect things like symbol filters, symbol lookup on features, etc, to fail as it would not have any bindings to the underlying attributes. Maybe there is an easy hack. 

Going forward in RAMP4, might be worth seeing if the API has better support for Arcade that can be leveraged. If Arcade is becoming more popular, might be a gap we need to fill.

**Comment by jolevesq** [comment]
@james-rae For sure user will loose info but at least the details and table will load. Can this be added to 3.3.4?
