### ISSUE TITLE
Share button not working

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3937]
On OSDP website the share button is not working.... Below some exchange about the problem. Once we have a URL to test we will update the issue

Johann Levesque @jolevesq Oct 09 2020 09:36
@james-rae Hi, me again... quick question about legacy API: Do you know why queue(action: string, priority: number, ...args: any[]) is not triggered sometimes. The page has the rv-wait but the queue object is not initialized. You can see it here: http://fgpv-app.azureedge.net/demo/tags/v3.2.0/dev/samples/index-fgp-en.html?rv=B,ZjdmOWYxNjYw,LTE5OTgxNjkuNjU2MDQwOTcy,NjU3NzYwLjYzMzQzNDg5MjY,MzUwMDAwMA,M2M5MjA4Yzk4MWFjYzk4MWIwYzk4MWI0Yzk4MWI4Yzk4MWJjYzk4MWMwYzk4MWM0Yzk4MWM4cmNzLjRkMDA3Y2JlLTAyMTItNGVjOC04ZjAzLTIzYTJmNTYxYjU2YS5lbg

James Rae @james-rae Oct 14 2020 08:43
Hi. So for that page, the app doesn't load and I get an error in the map assembly due to the bookmark having f7f9f166 encoded as the basemap id. The basemap doesn't exist, so it explodes.
I'm not sure how queue() fits into any of this.

Johann Levesque @jolevesq Oct 20 2020 12:33
I do not think it is the problem. If I add rv-wait to my map div, the map will not load at all. It wait forever for something. The basemap exist, it is de default basemap for the map with the Share. Something is wrong when legacy api is loaded but I do not why...

**Comment by jolevesq** [comment]
@dan-bowerman @james-rae : For the share button, you can use this link: https://green.dev.osdp.aws.nrcan-rncan.cloud/en/explore. Make sure you are on your VPN to access the site.

On this site, they are using an empty config file. When we share, it creates the url but it didn't take the selected basemap or extent.

Then you can do a search for Robert Banks and it will load the page with some layer loaded trough the API. Those layer are not loaded with the share URL as well.

**Comment by jolevesq** [comment]
@dan-bowerman @james-rae for the share button, there is a new url to use: https://uat-osdp-psdo.canada.ca/dp/en/explore

Can you try it and let me know if you have access. If you can test it quickly it will be appreciated. This issue is now on top of the list.

**Comment by james-rae** [comment]
I can access it, but only when on the intranet VPN. Can reproduce what you describe.

**Comment by jolevesq** [comment]
Yes, you have to be on the VPN to access the link. When I try to share I get this link but when I load it, nothing is kept (https://uat-osdp-psdo.canada.ca/dp/assets/osdp/osdp-Empty-en.html?rv=B,ZjdmOWYxNjYw,MTY3NTM1MS4yNjU0MDA5Njc2,LTE3MTIyOS4yMTk2MTI3NTEwNA,MzUwMDAwMA)

**Comment by james-rae** [comment]
Solved by adjusting the use of `rv-wait` and `.initialBookmark()` on the host page
