### ISSUE TITLE
Miss layer type icon inside legend

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3945]
When you add this layer https://maps-cartes.services.geo.ca/server_serveur/rest/services/IAAC/assessment_inventory_en/MapServer/0 as feature layer, it misses the layer type icon in the legend. When we move the mouse where the icon should be we can see the number if feature inside the layer but geometry is undefined. This layer is a esriGeometryMultipoint geometry. Is it a supported geometry in RAMP?

**Comment by james-rae** [comment]
Yep looks like the logic for that icon needs to be extended to support more types.

Fix would likely be in file `legend-element-factory.class.js`, subclass `TypeFlag`, function `get _icons()`
