### ISSUE TITLE
Focus can get trapped in the legend when navigating with TAB key

### ISSUE THREAD

**Issue by RyanCoulsonCA** [fgpv-vpgf/fgpv-vpgf#3955]
From @yileifeng on #3952:

Another thing unrelated to this PR and not sure if it is worth pursuing if no one is complaining, but I often end up with the focus trapped when expanding symbology using keyboard navigation (even after collapsing the symbology). 

![symbol-focus.gif](https://files.reviewableusercontent.io/images/reviewable/31557789/gkMWkqjRaASNpxkJPwkiDfem/symbol-focus.gif)

**Comment by RyanCoulsonCA** [comment]
The problem seems to be related to pressing TAB while the `expand` animation is still running. If you start the animation and spam TAB as fast as you can, you'll just end up cycling between the elements you were able to focus on while the animation was running.

I'm going to do some investigating to see if there's a good fix for this. If anyone knows anything about it and has any recommendations, that'd be helpful as well.

**Comment by spencerwahl** [comment]
I believe FocusManager links all the tabbing together with a linked-list.. I would look there, it might be inserting the new symbology buttons in the wrong place and cutting out the rest of the linked-list

**Comment by RyanCoulsonCA** [comment]
Yep, it looks like the problem does have to do with the linked list.

Do we know if [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js#L308) was here for any specific reason? When I remove it this issue no longer occurs. As far as I can tell it doesn't change how the app works either, unless I'm missing something subtle.
