### ISSUE TITLE
Details text field convert to HTML

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4001]
When we click on this point (OBJECTID = 228), inside the description field there a piece of text:

This crossing is to be reconstructed using a three pole structure consisting of 50' class 1 poles within the Lumsden Pond Provincial Park ```P.Id.``` No. 55198360, spanning the watercourse a distance of 121.7m with three 336acsr conductors, to a two pole structure consisting of two 60' poles on NSPI lands ```P.Id.``` No. 55489553.

P.Id. in convert to an hyperlink when it should not. It links to a blank page. It is confusing for the user. In fact, p.id is a real website and even Jira automatically create an hyperlink from it. If it is done automatically in RAMP, can we have a black list inside the configuration to remove parsing from some piece of text?

https://maps-stage.services.geo.ca/server_serveur/rest/services/NRCan/TC_Assessments_EN/MapServer/0

**Comment by james-rae** [comment]
Weird one. Verified the service is just plain text `p.id`. Something in the angular parser is interpreting that as a html hyperlink, which is silly.  Maybe it thinks it's an `id` tag of a `<p>` element?

Will need someone who knows angular to take a look. My best guess is [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.3.4/packages/ramp-core/src/app/ui/details/details-record-esrifeature-item.html#L82) is the source of the auto-formatting but that's not helpful as `autolink` is stock angular I believe.

First approach should be to see if the formatter/filter can be smartened up to ignore dumb stuff like `p.id`.
Second approach will be to think of something better than my third approach.
Third approach is add a flag in config to suppress any html-ification of text in the details. Not sure best spot, boolean on `columnNode`?. This seems way overkill for one instance and a weird error at that.

**Comment by spencerwahl** [comment]
`autolink` seems to be custom in [this file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.3.4/packages/ramp-core/src/app/core/formatters.filter.js#L48).

`linkifyjs` (what the formatter uses) does seem to think `p.id` is a good thing to make a link. I believe the formatter just takes a chunk of html from tag to tag and runs it through linkify and anything linkify thinks is a link gets changed.

James' first approach should be doable by adding a [validate](https://linkify.js.org/docs/options.html#validate) function. But we should be sure that we won't be breaking anything for other people. The simplest would be checking if the string starts with `www.` but that would then make `google.com` not link.

**Comment by jolevesq** [comment]
@dan-bowerman Will this be part of the next release?

**Comment by RyanCoulsonCA** [comment]
Hmm yeah, I'm pretty sure linkifyjs turns this into a URL because `.id` is a valid top-level domain. I could add a validator to check for `http/https` or `www.` but like Spencer said, I'm not certain that it wouldn't break something for someone. 

A valid domain name must be at minimum 2 characters long, so if this is a one-off sort of issue, we could just add a validator that makes sure the "domain name" is at least 2 characters long before turning it into a link. This would make `p.id` not link, but something like `hi.id` would.

**Comment by dan-bowerman** [comment]
Here is the production link (we cannot resolve the staging link in OP): https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/TC_Assessments_EN/MapServer/0
