### ISSUE TITLE
Details not working and layer config error

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4002]
When we load this layer (000183ed-8864-42f0-ae43-c4313a860720 - "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer") in 3.3.3 everything works well. When we load it in 3.3.4 from loadbyUUID, from keys parameter or the plus sign there is an error in the console

```rv-main.js:38 TypeError: Cannot read property 'layerConfig' of undefined
    at rv-main.js:1243
```

At the same time, details is not working for this layer.

**Comment by james-rae** [comment]
I don't have access to your RCS (or RCS-like) service, can you provide details on how you are loading the layer? Specifically, which sublayers, and if it's feature or dynamic layer. 

I've tried a couple of loads via the `+` wizard and things seem to work so need some specifics.

**Comment by jolevesq** [comment]
@james-rae Hi, can you test this by going to https://osdp-psdo.canada.ca/dp/en/explore then in the search input below the map type 900A. On the second record, click add to map.

Then if you look at the console there is a layer config error and the detail panel is not working anymore. We have theh same behavior on OpenMaps(https://search.open.canada.ca/openmap/000183ed-8864-42f0-ae43-c4313a860720) and GcGeo(https://gcgeo.gc.ca/viz/index-en.html?keys=000183ed-8864-42f0-ae43-c4313a860720)

The RCS return value: 
```
[
    {
        "layers": [
            {
                "layerType": "esriDynamic",
                "service_url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer",
                "name": "Mineral Areas, Producing Mines, and Oil and Gas Fields (900A)",
                "id": "rcs.000183ed-8864-42f0-ae43-c4313a860720.en",
                "url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer",
                "layerEntries": [
                    {
                        "index": 1
                    }
                ]
            }
        ]
    }
]
```

**Comment by jolevesq** [comment]
@james-rae Yeah, when we add from the wizard it works. Is it a fix that should be made inside the RAMP itself?

**Comment by dan-bowerman** [comment]
@jolevesq We will look into it, it does seem to be a problem with RAMP itself and a fix will be pursued.

@james-rae I wonder if this is the same bug preventing identify from working properly in this sample?: https://maps-cartes.dev.ec.gc.ca/sandbox/ramp-website/index.html#/samples/sample_context (ECCC VPN required)

**Comment by james-rae** [comment]
@dan-bowerman Yep, same error location, same configuration scenario. Very good odds a fix here will clear that site up as well 🎲

**Comment by jolevesq** [comment]
@dan-bowerman @james-rae we are experiencing a lot of weird stuff at the moment. I think most of them are server related but if you are able to find the exact cause and a solution it would be great so we can remove one variable of our bug fixing. Thanks.

**Comment by jolevesq** [comment]
@dan-bowerman Hi, I see code has been merge related too this issue. Do you know when it will be available as a release?
