### ISSUE TITLE
Legend items are lost when switching basemap

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4016]
When we switch from LCC basemap to Web Mercator with the viewer using keys to load the layers, the legend items disappears. Use to works fine in version 3.3.4.

Not working: https://staging.gcgeo.gc.ca/viz/index-en.html?keys=000183ed-8864-42f0-ae43-c4313a860720
Working: https://gcgeo.gc.ca/viz/index-en.html?keys=000183ed-8864-42f0-ae43-c4313a860720

**Comment by james-rae** [comment]
Unfortunately we can't run your staging site. The page is accessible (when on VPN) but all your libraries hosted on `viewer-visualiseur-stage.services.geo.ca/apps/RAMP/` give us a 403. Am assuming it's an NrCan only server.

Regardless, the only change in `v3.3.5` that would affect this is https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4005

My suspicion is something in the projection change (and bookmark encoder/decoder that facilitates the change) is putting a `stateOnly: true` flag on the child layers that appear from your key'd layer (the layer targets a layer group).

For the dev who digs deeper into this, you can likely hack in a fake RCS response (temporarily) if that makes things easier. The response json in this example is

```json
[
  {
    "layers": [
      {
        "isTimeAware": false,
        "layerType": "esriDynamic",
        "service_url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer",
        "name": "Mineral Areas, Producing Mines, and Oil and Gas Fields (900A)",
        "id": "rcs.000183ed-8864-42f0-ae43-c4313a860720.en",
        "url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer",
        "layerEntries": [
          {
            "index": 1
          }
        ]
      }
    ]
  }
]
```

**Comment by james-rae** [comment]
[The guilty party](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.3.5/packages/ramp-core/src/app/core/bookmark.service.js#L555), most likely

**Comment by james-rae** [comment]
Johann, if you're feeling brave, you can attempt a fast hack.
Edit `rv-main.js` in a text editor.

Search for string
`a.layerEntries.push({stateOnly:!0,state:c,index:c.index})`

Change to 
`a.layerEntries.push({stateOnly:!1,state:c,index:c.index})`

(just flipping true to false, essentially).

I make no promises!!! But could give you an immediate fix instead of waiting for a new release.

**Comment by jolevesq** [comment]
@james-rae @dan-bowerman Works perfectly, Thanks.
