### ISSUE TITLE
Support GeoJSON Geometry Collection

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4017]
Can we add support for GeoJOSN Geometry collection. This file is valid GeoJSON but it doesn't load in the viewer.

https://raw.githubusercontent.com/jolevesq/contributed-plugins/OSDP/osdp/src/samples/geoJSON/polygons.json

**Comment by james-rae** [comment]
GeoJSON gets converted to a Feature Layer. Feature Layer is schema-locked to a geometry, renderer, and set of fields.

A Geometry Collection can hold an arbitrary set of stuff. So while your sample file happens to have two polygons, someone could easily drop in lines and points. 

`FeatureCollection` <--> `FeatureLayer`
`GeometryCollection` <--> `GraphicsLayer`

The only work around would be to write some type of converter and then handle the invalid cases, how to present that to users. A more involved solution is to reconize geometry collections and import them as `SimpleLayer`, though would not have grid, identify, etc.  I'd say all this is something for the managers to haggle out as a priority. 

Not sure what your process is for getting and consuming those files; if they're always feature collections posing as geometry collections maybe you could pre-convert them.

**Comment by james-rae** [comment]
Looking at the file again I see the `GeometryCollection` is at the geometry level, while the top is a `FeatureCollection`. But the problem remains, you can have a mixed bag of geometry in that. We'd also need to figure out how to process a "clean" collection. E.g. in your file, would this become two features with one polygon each? Would they merge into a multi-polygon?
