### ISSUE TITLE
How to ensure that the object clicked in the map area is the same one given focus on the details pane

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4018]
Hi,

Issues from our client, see description below;

***
When the user clicks on an object in the map area, they expect to see the details about that object in the details pane.  This does not work as expected.  Rather this works if no object was previously selected on the map area. If an object was selected previously, the details pane fails to forget the prior selection when the new selection is made, with a net effect of not showing the user’s selection.

Example: Select a polygon (layer A) after the map first opens and the details for that polygon will be shown.  But select another polygon (layer B) and what the user sees is “nothing found” (because there is no polygon in layer A.  The reason for this is the details pane focus remains on the layer A, and not on the layer that was just clicked (layer B).  This causes a lot of user friction.

On reflection, this is a bug and not a feature enhancement.  The user should see displayed the information on what they clicked.  What they clicked prior to doing that has no relevance, as they have moved on.
***

So if a user click on an item and nothing is present in the previous search, it should move the next layer where something is found.

**Comment by james-rae** [comment]
Appreciate the feedback, always helpful. We will discuss.

Dev notes if we make a change: search for variable `previouslySelected`, this is where the logic block is lurking.
