### ISSUE TITLE
Long name in legend

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4022]
We use to have a way to see long name in legend on hover but doesn't seems to work anymore.

**Comment by james-rae** [comment]
Can you provide the service you're using, and any details about your legend structure (autolegend or structured, if deeply nested, etc)?
It's working for me, the full name appears in a mousetip appearing to the right of the legend item.

Also, assuming `v3.3.5`?

**Comment by jolevesq** [comment]
@james-rae when layer has a data table, long name will show on hover but when there is not like for WMS, the control is not tabable and the name will never show. Hope this help.

**Comment by james-rae** [comment]
Feels like the flipside of what we were discussing in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3819 , which never had a great solution

**Comment by jolevesq** [comment]
Can we add tabindex to all layers container (button or not) so they get tab and show the layer name?

**Comment by dan-bowerman** [comment]
If we're violating rules (See #3819) by invoking long-names on function-less services, maybe an info icon displaying the name would work instead (something to tab to?)

**Comment by james-rae** [comment]
Somewhat related - similar problem with symbology and not being able to keyboard-trigger the tooltip https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4129
