### ISSUE TITLE
trouble adding datacube WMS layer

### ISSUE THREAD

**Issue by fenugrec** [fgpv-vpgf/fgpv-vpgf#4028]
Via this viewer ( https://search.open.canada.ca/openmap/0fe65119-e96e-4a57-8bfe-9d9245fba06b ), running 3.3.5 [9359a2a98] , I'm having trouble with what should be a simple task... not sure what I'm doing wrong. I'm adding a layer and trying different variations of this URL : 

- https://datacube.services.geo.ca/ows/elevation
- https://datacube.services.geo.ca/ows/elevation?SERVICE=WMS
- https://datacube.services.geo.ca/ows/elevation?service=wms&request=GetCapabilities

then selecting "OGC web map service",  click "Continue", and I keep getting an "Incorrect file format".

Here are some example requests that I see in my browser's debugger :

```
GET /wmsproxy/ws/wmsproxy/executeFromProxy?https://datacube.services.geo.ca/ows/elevation?service=WMS&version=1.3&request=GetCapabilities HTTP/1.1
************* response : *************
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd"><ServiceExceptionReport version="1.1.1"><ServiceException>The URL https://datacube.services.geo.ca/ows/elevation? cannot be read</ServiceException></ServiceExceptionReport>


GET /wmsproxy/ws/wmsproxy/executeFromProxy?https://datacube.services.geo.ca/ows/elevation?service=wms&request=GetCapabilities HTTP/1.1
************* response : *************
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd"><ServiceExceptionReport version="1.1.1"><ServiceException>The response is not supported or invalid</ServiceException></ServiceExceptionReport>
```

Any ideas ?

**Comment by james-rae** [comment]
My suspicion is the `wmsproxy` and the new `geo.ca` domain. 

At some point recently we noticed the basemaps at `nrcan.gc.ca` were redirecting to (new?) domain `geo.ca` and causing bombs with sites we had that were using a cross origin whitelist.

I don't know who maintains the `wmsproxy` here but would imagine it has a similar whitelist and is lacking the new domain. The theory aligns with the message in the console 

> The URL https://datacube.services.geo.ca/ows/elevation? cannot be read

 Unfortunately I don't have a name to give you for a proxy owner, I'm not associated with the `open.canada.ca` team.

**Comment by fenugrec** [comment]
Thanks for the fast reply !

So it probably isn't just me entering a wrong URL (btw the UI could probably benefit from a bit of guidance on how to format the URL, i.e. if I should be including everything up to `GetCapabilities`, or `?SERVICE=WMS` or just the base url )

I'll try to find a contact at Open Maps to see if they have any insight.
#probably-not-a-bug
