### ISSUE TITLE
Current Basemap Selection is not indicated in the Basemap Selector

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#404]
The basemap selector does not indicate the basemap that has been selected.  This should be visibly obvious.

**Comment by mweech** [comment]
Overflow of text for Basemap titles should be addressed as this is causing the basemap selection indicator to be pushed out of sight.

**Comment by mweech** [comment]
PR #436

**Comment by ec-dev** [comment]
In PR #441
