### ISSUE TITLE
adding legend url programmatically

### ISSUE THREAD

**Issue by prosperva** [fgpv-vpgf/fgpv-vpgf#4055]
Is there a way to add the legendUrl in the RAMP config file? ocgWMS layer types are able to load legend. What I have is a json layer and I do have a legend url. Looking at the code, the legend is only pulled automatically when the layer is of ogcWMS

**Comment by prosperva** [comment]
Added symbologystack property fixes this. My new qu'asti on is how do you load JSON and legend all together.

**Comment by james-rae** [comment]
Hi, thanks for the question. I don't think there is a direct way to just use an image url, but will do my best to find some work-arounds. I havn't looked at this code in years so apologies if I get any limitations wrong.

By json I'm assuming you mean a `GeoJSON` layer.

### Symbol Stack

You found the `symbologyStack`; I believe this only works if your legend type is set to `structured`. I imagine `autopopulate` mode would ignore it.

Assuming you have the layer defined in your config with an `id` of your choosing, you could then define a legend entry having `layerId: yourLayerId`. This should line up the symbol stack with your layer.

### Custom Renderer

An alternative that might appeal, depending on your layer, is to use a custom renderer instead. Add a `customRenderer` property to your layer configuration object, and set it to an ESRI renderer definition using the ArcGIS Server format ([Renderer definitions](https://developers.arcgis.com/documentation/common-data-types/renderer-objects.htm) , [Symbol definitions](https://developers.arcgis.com/documentation/common-data-types/symbol-objects.htm)). This is a bit more seamless, and you will also get the "filter by symbol" checkboxes in your legend. But if your legend image is on the fancy side, this might not be good enough. This should also work in both legend types.

Basic example (a layer with a status field, using red & green circles for good/bad).

```text
{
  id: "myLayer",
  name: "My Layer",
  ...
  customRenderer: { 
    type: "uniqueValue",
    field1 : "status",  
    uniqueValueInfos: [
      {
        value : "good",
        label: "Good",
        symbol: {
          type: "esriSMS",
          style: "esriSMSCircle",
          color: "#00FF00",
          size: 10
        }
      },
      {
        value : "bad",
        label: "Bad",      
        symbol: {
          type: "esriSMS",
          style: "esriSMSCircle",
          color: "#FF0000",
          size: 10
        }
      }
    ]
  }
}
```

These renderers can take images sprites, but generally you want to keep them small-ish (20x20 ?).

### Raw Payload

If you're using the latest release (`v3.3.6`), GeoJSON configs now have a new parameter `rawFile`, which you can stick the content on your file on and have it load directly from the config. This might help if there is any file loading problems, assuming that is an option.

**Comment by prosperva** [comment]
@james-rae I finally got to try the idea of a customRenderer and came up with code:

` {
        "layerChoice": "file",
        "layerType": "esriFeature",
        "fileType": "geojson",
        "colour": "#ff0000",
        "tolerance": 5,
        "outfields": "*",
        "controls": [
          "opacity",
          "visibility",
          "boundingBox",
          "query",
          "snapshot",
          "metadata",
          "boundaryZoom",
          "refresh",
          "reload",
          "remove",
          "settings",
          "data",
          "styles"
        ],
        "disabledControls": [],
        "enableStructuredDelete": false,
        "state": {
          "opacity": 1,
          "visibility": false,
          "boundingBox": false,
          "query": true,
          "snapshot": false,
          "hovertips": true
        },
        "table": {
          "title": "",
          "maximize": false,
          "lazyFilter": false,
          "applyMap": false,
          "showFilter": true,
          "filterByExtent": false,
          "searchStrictMatch": false,
          "printEnabled": false,
          "columns": []
        },
        "name": "Active Fires",
        "customRenderer": { 
          "type": "uniqueValue",
          "field1" : "hectare",  
          "uniqueValueInfos": [
            {
              "value" : "good",
              "label": "Good",
              "symbol": {
                "type": "esriSMS",
                "style": "esriSMSCircle",
                "color": "#00FF00",
                "size": 10
              }
            }
          ]
        },
        "id": "active_fires",
        "metadataUrl": "",
        "url": "https://cwfis.cfs.nrcan.gc.ca/geoserver/public/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=public%3Aactivefires_current&outputFormat=application%2Fjson"
      },`

But it is not rendering. What am I doing wrong?

**Comment by prosperva** [comment]
Never it is working but is there a way to do conditions on values? For example, if field1 == 30?

**Comment by james-rae** [comment]
You are currently using a unique values renderer. This looks for exact matches of values. You need to add an object to the `uniqueValueInfos` array for every possible value.

Given you are symbolizing on hectares, this will probably be a mountain of work, and you'll have to change the renderer any time the data changes. I.e. you need a unique value definition for every exact hectare value in your dataset.

I recommend one of these approaches.

1. Use a `classBreaks` renderer against the hectares. This will let you symbolize on ranges of numbers. E.g. red circle for < 100, yellow circle for 100 to 1000, green circle for 1000+.
2. If you need specific symbols for specific features, use a more appropriate field, or if possible, add another field to your dataset that provides information on how the feature should be styled. Then use a unique value renderer.

In general, class breaks is used to symbolize against ranges of numbers. Unique values are used to symbolize against specific values (usually a status or group membership type of field).

**Comment by prosperva** [comment]
I started exploring idea 1 and I have this
<img width="303" alt="Screen Shot 2022-11-10 at 10 23 54 AM" src="https://user-images.githubusercontent.com/1531271/201164376-e61cb761-8ea9-47cb-8859-a9322e8b5c58.png">

But it is not displaying
<img width="1413" alt="Screen Shot 2022-11-10 at 10 25 54 AM" src="https://user-images.githubusercontent.com/1531271/201164731-fb72cd77-3dea-4e82-95ce-bcb1dae02d07.png">

Would you have an idea why?

**Comment by james-rae** [comment]
The image is only a subset of your renderer definition. Please provide the entire object.

**Comment by prosperva** [comment]
<img width="1127" alt="Screen Shot 2022-11-10 at 11 33 00 AM" src="https://user-images.githubusercontent.com/1531271/201178046-1ca0b87c-b43c-4f75-a687-27e474ad070b.png">

**Comment by james-rae** [comment]
Looks like you have `field1` when the [spec](https://developers.arcgis.com/documentation/common-data-types/renderer-objects.htm) uses `field`

**Comment by james-rae** [comment]
Also, some github tricks for you , if you put  ``` on lines before and after your code, you can embed it nicely instead of posting giant screenshots.

e.g.
```
json is fun
{
  "val": "very big very big very big very big very big very big very big very big very big very big very big very big very big very big very big very big very big very big "
}

**Comment by prosperva** [comment]
> Looks like you have `field1` when the [spec](https://developers.arcgis.com/documentation/common-data-types/renderer-objects.htm) uses `field`

Thanks. My eyes are playing tricks on me.

**Comment by prosperva** [comment]
My final question to option 1 you suggested above, will it be possible to modify customRenderer to draw this type of legend
<img width="185" alt="Screen Shot 2022-11-10 at 1 08 44 PM" src="https://user-images.githubusercontent.com/1531271/201195749-65bc5319-c968-426b-bd7d-570b0cbeff73.png">

This is essentially the same data, but it has another field called type where each type would be drawn using a different color. (e.g. Out of control, being held, under control, other)

Dataset URL: https://cwfis.cfs.nrcan.gc.ca/geoserver/public/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=public%3Aactivefires_current&outputFormat=application%2Fjson

**Comment by james-rae** [comment]
I don't think so, not via RAMP. It only supports the three renderer types, and I'm not even sure how to do this with fancier renderers in the ESRI API.

You could split into four layers, but then other parts of the app may not act the way you want (e.g. opening a data table would only show records for one of the colours). 

If you have the ability to control the output of your WFS, you can add a new field just for the symbol. It would have 12 distinct values, assigned accordingly. Then you could use a unique value renderer against that new field, having 12 definitions of the desired colour & size. If you can do this then I think you can get what you like, except your legend won't have those nice "group headings", you'd need to either hardcode a picture or name things a bit differently.

**Comment by prosperva** [comment]
Wild idea: provide a way in `RAMP` to override the legend section, then that way you have total control of the behaviour (add your own HTML and JS)

**Comment by james-rae** [comment]
Not on this codebase. Too old, too convoluted.

RAMP4 will have the ability for devs to write an alternate legend module and just replace the basic one (or copy the out of box one and mod it), but then it's on the author to make things work. Will be interesting to see how that pans out, level of effort vs level of customization

**Comment by prosperva** [comment]
Thanks @james-rae. I will keep an eye out for the RAMP4 release.

**Comment by prosperva** [comment]
Hi @james-rae I am still stuck at this one. The markers are not showing. Here is my setup:

```
{
      "layerChoice": "file",
      "layerType": "esriFeature",
      "fileType": "geojson",
      "colour": "#E633FF",
      "tolerance": 5,
      "outfields": "*",
      "controls": [
        "opacity",
        "visibility",
        "boundingBox",
        "query",
        "snapshot",
        "metadata",
        "boundaryZoom",
        "refresh",
        "reload",
        "remove",
        "settings",
        "data",
        "styles"
      ],
      "disabledControls": [],
      "enableStructuredDelete": false,
      "state": {
        "opacity": 0.5,
        "visibility": true,
        "boundingBox": false,
        "query": true,
        "snapshot": false,
        "hovertips": true
      },
      "table": {
        "title": "",
        "maximize": false,
        "lazyFilter": false,
        "applyMap": false,
        "showFilter": true,
        "filterByExtent": false,
        "searchStrictMatch": false,
        "printEnabled": false,
        "columns": []
      },
      "name": "Fire M3 Hotspots",
      "id": "fire_m3_hotspots",
      "customRenderer": { 
        "type": "classBreaks",
        "field" : "age",
        "classificationMethod": "esriClassifyManual",
        "minValue": 0,
        "classBreakInfos": [
          {
            "classMaxValue": 6,
            "label": "0 - 6 hours",
            "symbol": {
              "type": "esriSMS",
              "style": "esriSMSCircle",
              "color": "#E20000",
              "size": 10
            }
          },
          {
            "classMaxValue": 12,
            "label": "6 - 12 hours",
            "symbol": {
              "type": "esriSMS",
              "style": "esriSMSCircle",
              "color": "#FF9D00",
              "size": 10
            }
          },
          {
            "classMaxValue": 24,
            "label": "12 - 24 hours",
            "symbol": {
              "type": "esriSMS",
              "style": "esriSMSCircle",
              "color": "#FFFF00",
              "size": 10
            }
          }
        ]
      },
      "url": "https://cwfis.cfs.nrcan.gc.ca/geoserver/public/ows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&typeName=public%3Ahotspots_last24hrs&outputFormat=application%2Fjson"
    },
```

**Comment by prosperva** [comment]
This did not work. I also lose the datagrid capability when I switch to ogcWfs.

**Comment by prosperva** [comment]
Digging through HTML, it seems like it is not grabbing the symbol values i.e. color, opacity. Inspecting it shows the following:

```
<circle id="SvgjsCircle1267" r="6.5" cx="16" cy="16" fill-opacity="0" fill="#ffff02" stroke-miterlimit="4" stroke-linejoin="miter" stroke-linecap="square" stroke-opacity="0" stroke-width="0" stroke="#000000" transform="matrix(1,0,0,1,0,0)"></circle>

<circle id="SvgjsCircle1270" r="6.5" cx="16" cy="16" fill-opacity="0.03529411764705882" fill="#ffffff" stroke-miterlimit="4" stroke-linejoin="miter" stroke-linecap="square" stroke-opacity="0" stroke-width="0" stroke="#000000" transform="matrix(1,0,0,1,0,0)"></circle>

<circle id="SvgjsCircle1273" r="6.5" cx="16" cy="16" fill-opacity="1" fill="#ffffff" stroke-miterlimit="4" stroke-linejoin="miter" stroke-linecap="square" stroke-opacity="0" stroke-width="0" stroke="#000000" transform="matrix(1,0,0,1,0,0)"></circle>
```

**Comment by james-rae** [comment]
Solved it. We are both guilty of not reading the specs. Server renderers define color as an array of integers, not a string hex code.

so needs to be `"color": [255, 123, 3]`

**Comment by james-rae** [comment]
Also the `ogcWfs` type was not working because this service appears to be v2 of WFS and we only support v3. Our data loader explodes when it encounters the XML return. But I'm glad you're able to trick the app into thinking it's reading a JSON file.

**Comment by prosperva** [comment]
> this service appears to be v2 of WFS and we only support v3. Our data loader explodes when it encounters the XML return. But I'm glad you're able to trick the app into thinking it's reading a JSON file.

I found out that through here: https://developers.arcgis.com/web-map-specification/objects/esriSMS_symbol/

I was reading your answer when I was testing

**Comment by prosperva** [comment]
> Solved it. We are both guilty of not reading the specs. Server renderers define color as an array of integers, not a string hex code.
> 
> so needs to be `"color": [255, 123, 3]`

I found out that through here: https://developers.arcgis.com/web-map-specification/objects/esriSMS_symbol/. I was reading your answer when I was testing
