### ISSUE TITLE
No Basemap in Overview Map at Full Extent

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#406]
The basemap utilized by the overview map is not valid at the zoom level used when the viewer is at Full Extent.  There likely has to be a max zoom level specified for the Overview Map control.

**Comment by mweech** [comment]
Once the basemap is in view, the current map extent rectangle is sized to use the full width of the overview map.  This should be reduced in size (~50%).

![](https://i.imgur.com/EMrPDgH.png)

**Comment by james-rae** [comment]
Week Mar 28-Apr 1
Investigation and testing variants of the code. Overview map works as expected in simple website.  Two ongoing leads
* is cause by recently noticed "basemaps behaving like dynamic layers" issue
* custom css resising/messing with overview map is breaking things
