### ISSUE TITLE
The legacy centerAndZoom sets the wrong center

### ISSUE THREAD

**Issue by milespetrov** [fgpv-vpgf/fgpv-vpgf#4061]
You can see the map pan/shift a bit when you run  `RV.getMap("fgpmap").centerAndZoom(RAMP.mapInstances[0].center.x, RAMP.mapInstances[0].center.y, 4326, RAMP.mapInstances[0].zoom);` in the dev console.

Sounds like a precision issue somewhere in the code. The `RAMP.mapInstances[0].center` object seems precise enough `{x: -57.84282243778783, y: 54.43906496234642}`

**Comment by james-rae** [comment]
Interesting. The "jump" is far more severe if you're at a Canada-level scale then a city-level scale. Hmmmm

**Comment by james-rae** [comment]
Looks like it's the `.center` that is off.

**Comment by james-rae** [comment]
Need to dig more, but I believe this is a problem with how RAMP2 dealt with co-ordinates via the API. 

Every API output is forced into lat/long projection. The `.center` call is deriving the center of the map extent. **BUT** it is using a projected extent, not the raw extent. Regular geometry can be re-projected seamlessly, but extents are special in that they need to have right-angle corners in their projection. Going from Lambert (cone shaped) to Lat/Long (sphere) involves some distortion & warping.

A possible fix is to re-route the `.center` method to interrogate the raw extent, get the center point in the map's projection, then re-project the point, and return that.
