### ISSUE TITLE
Map loads in certain browsers

### ISSUE THREAD

**Issue by prosperva** [fgpv-vpgf/fgpv-vpgf#4075]
Map is loading in 

- `Chrome`
- `Opera`
- `Safari` 

but NOT in 

- `Firefox`
- `Chrome Incognito Mode` 
- `MS Edge` 

I am getting this error: 

`Failed to load resource: the server responded with a status of 431 (Request Header Fields Too Large)`

I am serving the config in ReactJS it comes in a string

```
 <div
      is="rv-map"
      style={{
        backgroundColor: "white",
        marginLeft: "50px",
        marginRight: "50px",
        height: "750px",
        display: "flex",
      }}
      rv-langs={langValues}
      data-rv-config={configValue}
></div>
```

Setting `data-rv-config` as a file name works but I need to set certain values in the config `json` programmatically (for example `layer visibility boolean value`) before the map is loaded. `visibility` value is loaded from other variable and set for layers I have for the map.

Looking in RAMP code, error points to line 38 in `rv-main.js`. I am using `RAMP 3.3.6`

**More info present in the console**

<img width="1645" alt="Screen Shot 2022-11-17 at 7 56 59 PM" src="https://user-images.githubusercontent.com/1531271/202608200-1ab5c336-6da9-4e53-80c9-17fd558a99f0.png">

**Comment by prosperva** [comment]
It seems like the map is is being drawn while I am still calculating the visibility. The function that calculates the visibility looks as follows:

```
function isLayerVisible(layerId: string) {
  if (localStorage.getItem("selectedLayers") != null) {
    let savedLayers = localStorage.getItem("selectedLayers")!.split(",");
    return savedLayers.includes(layerId);
  }
}
```

**Comment by james-rae** [comment]
Instead of using a div that takes `data-rv-config`, perhaps you could try this approach

https://fgpv-vpgf.github.io/fgpv-vpgf/develop/docs/#/mapauthor/intro?id=_2-api

Run your custom code that generates your desired config file, then use the `RAMP.Map(<mydiv>, <myconfig>)` to create the map when you are ready.

I rarely use this so hoping it still works / does what you need.

**Comment by prosperva** [comment]
I noticed that this takes a file as an argument though. This means that the file is static whereas inky case I am modifying a variable before it is passed to the map id

**Comment by prosperva** [comment]
Has the RAMP team discussed making `RAMP` an `npm` package for people using `React` or `Angular`.
