### ISSUE TITLE
Identify Results Not Using Layer Symbology

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#408]
Results of Identify query are using Ipsum Lorem graphics.

**Comment by AleksueiR** [comment]
This might not be the best approach after all :(
Showing icons in the details results selector makes sense if there only one icon per layer.

**Comment by mweech** [comment]
Not sure why not? Each of those entries listed in the feature list should tie back to the features parent layer grouping (service or group level as the case may be) and utilize that title.  The symbol would would then be dictated by the symbology of the specific feature as represented in the legend.  

Based on that you would have a list of Features using varying (or the same) icon/titles which would be the expected outcome for a stacked set of features.
