### ISSUE TITLE
Remove HTTP URL trickery

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#4087]
Parts of the RAMP core will generate certain URLs using the protocol that the host site is in. In particular, the URL to the ESRI JS API and the ESPG projection lookup service (if no urls are supplied in the config, which is typical case).

Since `http` is now becoming less common, and CORS is more common, we are finding this url logic can cause CORS errors when attempting to access the `http` version of those services. Most notably when attempting to run RAMP in develoment mode using `localhost`. We could probably config our `rush` scripts to serve via `https` but this could also happen in any `http` host sites, as well it would not be shocking if those two services depreciated their `http` endpoints.

Remove the trickery. Always use the `https` version of those URLs.

- `epsg.feature.ts`
- `config.service.js`
- `global.registry.js` (not used but clean it up anyways).

Note there is also some stuff in `loader-service.directive.js`, but I think we should leave this as is, since the affected URL is user supplied and `http` may be valid in niche scenarios.

**Comment by prosperva** [comment]
I support this one @james-rae.  I have had to create a localhost certificate to solve CORS issues.
