### ISSUE TITLE
Disable Layer Queries

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#409]
Allow each map service to have Identify/GetFeatureInfo queries be disabled.  This is helpful when a user is experiencing long response times from a particular layer or just wish to add a layer for background context but are not interested in the data contained in the layer itself.  This setting should be available in the settings menu and result in an indicator being displayed in the Legend which shows that the layer is not responding to queries.

**Comment by jolevesq** [comment]
We should be able to set this from the configuration file for thematic map as well. Ability to have or not the function and to have on or off by default

**Comment by jolevesq** [comment]
I will add a new options identify in the data section of setting (like snapshot) enable true, value true. We will be able to set it from config and when a identify/GetFeatureInfo is call, it will look for the option.

If someone have a better idea, let me know!

**Comment by jolevesq** [comment]
@AleksueiR @alyec to be able to set bypass the layer for identify I did this when it is a multilevel service likeAAFC AGRI Environmental indicator. This way when I set the middle level Air Quality, it is caught in my if statement

 `if (!legendEntry.getVisibility() || !legendEntry.options.identify.value || !legendEntry.parent.options.identify.value) {
                                    return;
                                }
`

It is ok for a 3 levels service but if there is more I need a recursive function to know if one parent is false. Do we have a function like that somewhere in the code?

At the same time, if user disable all identify, the panel show empty with no message. I think we should put a message inside the panel or do not show the panel at all. I think the message is more explanatory. What do you think?

**Comment by AleksueiR** [comment]
Where are you adding the checks?

I think turning off query option on parent item should propagate to its children (similar to how [`setVisibility`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/legend-entry.service.js#L262) on the legend group entry works) and then you don't have to check if the parent is turned off.

**Comment by jolevesq** [comment]
I set the value by default in the schema. Then I modify it to false in `setting.directive.js` when a user click on the option to disable it. II do the check in `identify.service.js` and it works well for everything except the multi level service. Is it suppose to be somewhere else?

**Comment by AleksueiR** [comment]
Oh, I haven't noticed your commit.

In `settings.directive` you probably want something like this:
```js
function toggleIdentify() {
    self.tocEntry.setQuery();
}
```
and have `setQuery` function toggle query setting on children, if any.

Also, there is no need to modify the schema - we already have `queryOptionNode` which is reserved for turning off identify function.

**Comment by jolevesq** [comment]
I saw the queryNode but I thought it was for something else. Thanks for the info, I will modify my code.

**Comment by jolevesq** [comment]
@james-rae @alyec @AleksueiR If a parent is change from true to false it will cascade to all children. Question about what do we do for the opposite, we change a child. Do we modify the parent so the item is visible (in the sample below, changing level 2.2 to true will change level 1 to true as well. If we dont do this it is hard for the user to understand why he cant see the layer if he change the value at level 2.2. Do you agree?

level 1 {
 query: false;
   level 2.1 {
       query: false;
   }
   level 2.2 {
      query: false;
   }
}

**Comment by jolevesq** [comment]
@AleksueiR @alyec @james-rae 

The solution will look like this to be able to set all children and parent... If you have concerns before I pull this to PR, let me know.

```
        /**
        * Toggle the query value option. This option is use to let the layer appears in
        * the identify window.
        * @private
        */
        function toggleQuery() {
            const value = !self.display.data.options.query.value;

            // assing value to tocEntry then to all children
            const tocEntry = self.tocEntry;
            tocEntry.options.query.value = value;
            setTocEntryChildrenQuery(value, tocEntry.items);

            /*
            * if value is true (enable), cascade to parent so the layer will be
            * visible. If we don't do this, it is hard for user to understand why
            * the layer is set enable is not visible
            */
            if (value) {
                setTocEntryParentQuery(tocEntry);
            }
        }

        /**
        * Applies current query value from the settings panel to all children.
        * @private
        * @param {Boolean} value query value.
        * @param {Object} itemsArray array of children items to set.
        */
        function setTocEntryChildrenQuery(value, itemsArray) {
            if (typeof itemsArray !== 'undefined') {
                itemsArray.forEach(ele => {
                    ele.options.query.value = value;
                    setTocEntryChildrenQuery(value, ele.items);
                });
            }
        }

        /**
        * Applies enable query value to all parents so the child layer can be seen in identify panel.
        * @private
        * @param {Object} tocEntry tocEntry to set the parent from.
        */
        function setTocEntryParentQuery(tocEntry) {
            if (typeof tocEntry.master !== 'undefined') {
                tocEntry.parent.options.query.value = true;
                setTocEntryParentQuery(tocEntry.parent);
            }
        }
```

**Comment by AleksueiR** [comment]
I think there is some confusion with how identify for dynamic layer works. Say with have a layer:
```
Cool Dynamic layer
- sublayer 1
- sublayer 2
- subgroup 1
    - sublayer 3
    - sublayer 4
- subgroup 2
    - sublayer 5
    - sublayer 6
```
In my understanding, assuming `query` is enabled for everything, in the identify panel the user will see:
```
- sublayer 1
- sublayer 2
- sublayer 3
- sublayer 4
- sublayer 5
- sublayer 6
```
Subgroups are ignored as they don't contain data.
Setting `query` to `false` on `subgroup 2` will show in the identify panel as:
```
- sublayer 1
- sublayer 2
- sublayer 3
- sublayer 4
```
Subsequently setting `query` to `true` on `sublayer 5` (a child of `subgroup 2`) will give:
```
- sublayer 1
- sublayer 2
- sublayer 3
- sublayer 4
- sublayer 5
```
In the last case, the `query` option of `subgroup 2` is still set to `false` though. The behaviour mirrors that of the `visibility` option.

Subgroups are ignored already: the [`walkItems`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/legend-entry.service.js#L303) function used [here](https://github.com/jolevesq/fgpv-vpgf/commit/8592f77d0519f2ae75122059297bb8b50bc06a84#diff-b4009ff3ab0f2d983d451e72893dcd3dL168) to iterate over items of a dynamic layer when creating an identify query ignores subgroups by default as they don't contain any data.

Let me know if this is at all helpful or even more confusing :smile: We can discuss this over webex if needed.

**Comment by jolevesq** [comment]
@AleksueiR Thanks for the explanation. It is almost the way I made it work except I set subgroup 2 to enable when a child got enable. I understand your point and for the visibility because you see the all setting at the same time ( a user can understand why a child is not visible because of the parent). For the disable, you have to go inside the setting panel to see the parameter. If I set subgroup 2 to false then later sublayer 5 to true. There is no easy way to understand why it is not working. I have to go back and open panel setting to see what is going on. The more level of deepness, the more lost the user will be. Let me know if you want to work it your way I will just remove ```setTocEntryParentQuery``` and it will do the job. Thanks

**Comment by AleksueiR** [comment]
That's a very good point - there is no visible indication that `query` is turned off right now.
We discussed it and think a good solution would be to display a `query-off` flag on the legend entry when it's turned off. Something like this:
![2016-05-24 14_32_58-adobe photoshop cs3](https://cloud.githubusercontent.com/assets/2285779/15515473/702bf36e-21bc-11e6-9bcf-058743537ecb.png)
This way it's easy to tell which layer or sublayer will not appear in the identify results. This will be a separate task.

What do you think? If you are okay with this, please, keep the behaviour as described in my comment above.

Thanks you.

**Comment by jolevesq** [comment]
@AleksueiR I agree, this way both visibility and query will behave the same way. It will be easier for the user to understand how the viewer works. I will remove my setParent function and will be able to to send it to PR tomorrow. Thanks
