### ISSUE TITLE
Demo Build process is broken

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#4097]
Here are three PRs that have failed. As usual, I don't see an error in the build log (though good chance it's right there in front of my eyes 👀 ).

https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4094
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4095
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4096

**Comment by milespetrov** [comment]
Looks like she's all patched up (pushed update to develop). New PR #4100 is building, older PR's will continue to fail.
