### ISSUE TITLE
Display Layer Bounding Box 

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#413]
Each layer should have the ability to display a bounding box.

**Comment by mweech** [comment]
#110 - swap control for a switch style control.

**Comment by james-rae** [comment]
## High Level Design

Creation of bounding box layer is triggered the first time a user attempts to view the box.  

* Create a graphics layer
* Create a rectangle polygon.  Co-ords come from the layer object extent.
  * If layer is in a different projection from the basemap, may need to reproject
  * May want option for config file to override the box extent
* Add the polygon to the graphics layer
* Link the graphics layer to the main layer's entry in the layer registry (e.g. `.bbLayer`)
* Add the graphics layer to the map (insertion point depends on approach below)
* Have the toggle turn on and off the visibility of the graphics layer


## Layer Ordering

We will quite likely need to refactor our add layer / reload layer / reorder layer  / insertion logic

### Approach 1

All bounding box layers are on top

PROS
* bounding boxes are always prominantly visible
* logic for image based layers stays the same

CONS
* for feature/graphics layer, need special logic to determine the "top" and "bottom" of the user data layers (top being where the bounding boxes start; bottom being potential vector basemaps)
* adding new layers also needs to be aware of insertion point...can't just add to the top of the map stack


### Approach 2

Have bounding box layers directly above respective layers

PROS
* layer position logic does not change
* adding layers logic does not change

CONS 
* re-order has to move two layers in unison
* possible for a bounding box to be partially obscured by visible layer above it
