### ISSUE TITLE
Allow for a User to Go Back to Cart

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#415]
When the viewer is tied together with a Data Catalogue instance, allow the user to return to the cart.  This functionality may be available as a link in the WET page container, or as a menu option directly in the viewer.  The URL for the cart should be configurable.

When going back to cart, the functionality should be as simple as "<cartURL>?keys=ID1,ID2,etc" and not require the catalogue to pass state back to us again.

**Comment by mweech** [comment]
http://fgpv.cloudapp.net/demo/develop/index-fgp-en.html and http://fgpv.cloudapp.net/demo/develop/index-fgp-fr.html pages and operate the same as it is implemented in RAMP where the Get Link parameters are reused: http://dev.gcgeo.gc.ca/RAMP/ramp-en.html?keys=88abdb3f-e9d7-46ee-af0c-1530cb0de66b&bm=0 to become “/geonetwork/mapcart/eng? keys=88abdb3f-e9d7-46ee-af0c-1530cb0de66b&bm=0”

**Comment by mweech** [comment]
Blocked until GetLink/Bookmark is implemented. #280

**Comment by AleksueiR** [comment]
Notes from UX review:
- back-to-cart functionality should be supplied by a component on the host page, not the viewer itself
  - serializedmap is stored in local storage and pass back only layer keys to avoid CKAN issue
  - on startup, host page checks for serializedmap data in local storage
  - need a demo page to show this funcionality
  - viewer api needs a function to provide serializedmap object
- back-to-cart component is a separate Github repo

**Comment by alyec** [comment]
From a quick discussion with @spencerwahl I think [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is the best option for back to cart functionality.

**Comment by mweech** [comment]
Please implement this on the index-fgp-en.html sample page.

**Comment by spencerwahl** [comment]
Work left:

- [ ] finish marking RCS layers as such
- [ ] finalize API call
- [ ] finalize key-list retrieval flow (use broken up bookmark parsing to modify the list of layers)
- [ ] local storage testing

**Comment by mweech** [comment]
estimate 3 points more to go.
