### ISSUE TITLE
Enable Point Information Display when viewing Datagrid

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#416]
When selecting a record in the datagrid the point information panel should provide an output similar to that which is provided by Identify.

- [x] reuse map click (in identifyService) to display the proper data and trigger the point click details panel
- [x] make another button in datagrid which triggers the above logic
- [x] make tooltip so people know they're getting details when clicking on said button

**Comment by mweech** [comment]
Reopening issue: EcoAction layer does not have point information support when viewing the datagrid.  Please fix.

**Comment by cynngah** [comment]
Not entirely sure if the issue is just having the buttons appear on the grid or if further support is required for dynamic layers. Will be a 1-2 if it's just the icon issue but if further support is needed it might be around a 4-5. The same goes for zoomTo actually. Will update as I find out more.

**Comment by cynngah** [comment]
Ok it just seems to be an icon issue. Will PR soon.
