### ISSUE TITLE
Zoom to Feature

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#417]
When browsing the datagrid a user is provided with a hyperlink to allow them to "Zoom to" the feature.

**Comment by mweech** [comment]
dupe of: #344

**Comment by cynngah** [comment]
Problem with referencing the wrong object after geoService refactor.
Zoom to feature, after changed to reference correct object, only works on Mercator basemaps now. Currently working to support Lambert and other projections for zoom (currently zooms to some crazy point on the other side of the earth).

**Comment by cynngah** [comment]
current fix:
> * Not taking into account Zoom Scale Dependency (may zoom to levels where feature is invisible)
* Will error for File-Based layers
* Existing Object ID Bug (needs OID in first column)
