### ISSUE TITLE
Export Datagrid Data

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#418]
If Data Tables plugin support for exporting content of a datagrid works out of the box, enable the datagrid menu option to export the datatable.

**Comment by AleksueiR** [comment]
Added default browser printing (works in Chrom and Firefox) and export to CSV options. 

It is possible to export as PDF and XLSX but it requires some 3Mb of JS libraries. We can add it later along with conditional loading when allowed throug the config.
