### ISSUE TITLE
Expand Point Information View

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#420]
A user should be able to expand the feature details window for content that does not fit in a narrow vertical scrolling window, such as HTML tables.

**Comment by jolevesq** [comment]
I played a lot with the detail panel when I work on "disable query" task. I found annoying that the data panel open on top of the legend. Should it be better to react the same way as the metadata panel?

**Comment by AleksueiR** [comment]
@milesap Why remove the label?

**Comment by mweech** [comment]
@jolevesq I think that depends on resolution of the user.  At lower resolutions and mobile scenarios it takes ALOT more viewable space from the map, particularly if it isn't being used in full screen.  I can see a desire to have the point information panel popout if selected, or auto by min viewable area in full screen mode.

**Comment by jolevesq** [comment]
@mweech you are right and it always depend on what is the task. If I don't play with the legend I want it on top of it for sure. We can maybe add other position for the panel in the futur.

**Comment by mweech** [comment]
captured those possibilities under #670

**Comment by jolevesq** [comment]
@mweech @AleksueiR when you say expend, you want to be like the expand metadata window?

**Comment by AleksueiR** [comment]
This one turned out pretty complex, I think it should be PRed separately, not lumped with something else.

**Comment by AleksueiR** [comment]
Belated update:
- suggested design puts the expand button underneath the close button (if put the left of the close button, it reduces space available for feature name)
![](https://files.gitter.im/AleksueiR/qXmW/2016-05-27-10_50_17-title.png)
