### ISSUE TITLE
Pass Query String from Containing Web Page

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#422]
In order to enable integration with the Catalogue the viewer must be able to obtain the query string from the containing webpage.

**Comment by james-rae** [comment]
Started Fri Apr 8th. Basic design done, refactoring other functions to be more generic (a number of things are only triggered at startup, need to be triggerable from our application api)

**Comment by james-rae** [comment]
Note new issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/502 to deal with ideal way for a host page to use this functionality
