### ISSUE TITLE
Perform English/French Language Switch from WebPage Container

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#423]
Allow the viewer to be a component on a containing web page (i.e. using WET) that would have external control over the viewer language.

May need to address some WET compatibility issues regarding loading of libraries included in both the viewer and WET (#252).

**Comment by spencerwahl** [comment]
Update: Almost ready for PR; running into some rebasing issues.

**Comment by spencerwahl** [comment]
PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/433
