### ISSUE TITLE
UI problems for opacity slider

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#429]
![](https://i.imgur.com/pUSBD5e.png)

- Opacity label missing
- second % label
- first % label is bound to the wrong variable (and only shows up as "%")

**Comment by AleksueiR** [comment]
Opacity slider feels a bit sluggish; notice how the slider handle lags behind the mouse cursor.

![](https://fgpdoc.zz9.ca/index.php/s/nSFomd7QknEXIv0/download)


Default implementation:
![](https://fgpdoc.zz9.ca/index.php/s/79tasnhm8eSfNo7/download)
