### ISSUE TITLE
bug(geo): basemap doesn't load if no layers specified in the config

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#430]
Basemap also doesn't seem to load with certain layers, but loads with others. With limited poking around, I found it does load with [this]( http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_census_of_agriculture_2011_ccs/MapServer) layer.

No funny error in the console.

Steps:
1. Empty `layers` array in the config file
2. Load the app
3. Observe empty basemap

**Comment by mweech** [comment]
obsolete.
