### ISSUE TITLE
Enable Layer Settings Support for Group/Dynamic Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#434]
Esri Dynamic Feature Layers (Group Layers) do not have a settings panel enabled at this time.  Enable the utilization of the settings panel such that the following options are possible:

- [x] A Group Layer will have the ability to change the opacity of all sub layers
- [ ] User can select to display a bounding box for each individual sub layer (#413)

**Comment by AleksueiR** [comment]
See #476 for details.

**Comment by AleksueiR** [comment]
Opacity for dynamic layers is done, although it presently fails for layers with many children. See #479.

**Comment by AleksueiR** [comment]
See PR #481 for details.
