### ISSUE TITLE
Replace index-wet.html with a better WET Demo Page

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#444]
- [x] Replace the existing index-wet.html demo page with a web page template provided by the Web Presence team. 
- [x] Wire in English/French language switching

**Comment by spencerwahl** [comment]
Not started yet

**Comment by spencerwahl** [comment]
PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/480
