### ISSUE TITLE
Layer Reloading

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#450]
Implement reloading of layers.  Utilized in cases where a layer fails to respond initially, or for switching between Snapshot & OnDemand loading of Feature Layers.

**Comment by james-rae** [comment]
Week Apr 4-8
Not started

**Comment by james-rae** [comment]
Will utilize approach in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/514
