### ISSUE TITLE
Release R2 Viewer Alpha

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#453]
Upon completion of outstanding PR requests (#439 & #447).

Release Name: R2 Viewer Alpha
Version: 0.12.0.  

- [x] Sync to master
- [x] Tag release & notify team
- [x] Add Release Notes

**Comment by mweech** [comment]
Assign back to me to complete the Release Notes.

**Comment by AleksueiR** [comment]
[Publication Steps](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Weekly-Repo-Publication-Steps)

**Comment by mweech** [comment]
Done.

https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/v0.12.0-alpha
