### ISSUE TITLE
App fails to load with "net::ERR_SSL_PROTOCOL_ERROR"

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#468]
> https://code.jquery.com/jquery-2.2.1.min.js Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

Firewall issue perhaps, as it's working on the external network.

**Comment by AleksueiR** [comment]
Seems to be working now.

**Comment by mweech** [comment]
not reproducable.
