### ISSUE TITLE
bug(proxy): fails to fetch layer image

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#479]
> appears to be a proxy issue. once the request gets over 2000-ish characters, it needs to use a proxy. If the proxy is working correctly, the image with transparency will work. 
> You can play with a guts example if you like to see the behavior. URL, source  Devmap e:\wwwroot\RAMP_Sample\iamerror\fatopacguts.html . comment out or edit line 70 to mess with proxy. add/remove indexes from line 94 to adjust the size of the request. transparency is working on sub-layer 2 with cheesy toggle to flip it.

> @james-rae

**Comment by alyec** [comment]
Added layer to the proxy whitelist.
