### ISSUE TITLE
Style Collisions Occuring in WET Pages

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#482]
Scrollbar appears when mousing over the edge of a layer entry for a group layer that has been collapsed.

![image](https://cloud.githubusercontent.com/assets/7583387/14536350/f21c1ab2-023f-11e6-9ed7-1956f7ee6dbe.png)

**Comment by AleksueiR** [comment]
What browsers? WOMM.

**Comment by mweech** [comment]
Chrome and in index-fgp-en.html

**Comment by AleksueiR** [comment]
Ah, that would explain it - styles collision.

**Comment by AleksueiR** [comment]
Fonts in drop-down menus are also overridden as the menu is created outside app's container:
![](https://i.imgur.com/DTk1x5a.png)
