### ISSUE TITLE
Fix protractor tests

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#486]
Initially app-seed was sneaking into protractor builds... this causes problems with bootstrapping for the tests. The initial solution was to defer bootstrapping by setting window.name to `NG_DEFER_BOOTSTRAP!` and appending `angular.resumeBootstrap();` to the end of core.js (only for protractor builds!).

This allowed index-protractor to load but the tests are still failing;
- Travis: `timeout: timed out after 30000 msec waiting for spec to complete`
- Local: `Failed: unknown error: [ng:btstrpd] App Already Bootstrapped with this Element '&lt;body ng-app="app" rv-config="config.en-CA.json" class="ng-scope"&gt;'`

Partial solution which gets index-protractor to load: https://github.com/spencerwahl/fgpv-vpgf/commit/aae93a07046a4f07932c2a0a20bb5f1e9f108eba

**Comment by milesap** [comment]
Let's give this another go

**Comment by milesap** [comment]
It was fixed, not used, and removed 😃
