### ISSUE TITLE
Improve toc entry highlight

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#489]
Make toc entry highlight on selection more prominent.
Remove garbage text from the bottom of the settings panel.
Add layer name to the header of the setting panel.
Add content animation (fade in/out) when switching settings panel between toc entries.

**Comment by spencerwahl** [comment]
PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/536

note: animations were removed from the scope
