### ISSUE TITLE
Remove settings menu option if no settings available

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#490]
If there is no settings available for a specific toc entry, remove the setting menu option.

![](https://i.imgur.com/z9AwW7G.png)

**Comment by james-rae** [comment]
Items in the legend with this situation for the basic develop configuration are

* AAFC AGRI Evnironmental Indicators --> Farm Land Management
* AAFC Plant Hardiness Zones --> Plant Hardiness Zones of Canada 2000
* Eco Geo --> All Children

**Comment by jolevesq** [comment]
I have few questions about this one. In the config file, there is no setting to say if we want the setting option to be on the parent or the children.It will depend the type of setting. For example, opacity it can't be on both but for bounding box it can. We need more granularity in the config file to be able to set this. It will be especially true when we will use structure legend.

In the config file, options in setting are mixid with visibility that is not in setting panel. Should it be better to group what need to be grouped on the UI?

We should have a config like that:

{
      "id":"ecogeo",
      "name": "Eco Geo",
      "layerType":"esriDynamic",
      "layerEntries": [{"index": 6}, {"index": 7}, {"index": 8}, {"index": 9}],
      "url":"http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer",
      "metadataUrl": "http://intr...",

     " options": [
         "root": {
            "visibility": {true},
           "setting" []
         },
         "6": {
            "visibility": {false},
           "setting": [
                "opacity": { value: 0.5 },
                "boundingbox": true
           ]},
         "7": {
            "visibility": {true},
           "setting": [
                "opacity": { value: 0.25 },
                "boundingbox": false
           ]},
    }

It mess up the layer section. It is why in GCViz I put all those thing in the legend section. Because it is where all setting is setup.

Any comments?

**Comment by mweech** [comment]
I can't contribute much re: structure of the configuration file and how elements are grouped, however from a scope POV we are currently focused on the unstructured legend as would be necessary to meet the FGP deadlines first.  A major deliverable beyond v1.0 will be to address structured legends.  It is currently out of scope.  Once we delve into this area, we will have to do a bit of a review and identify all the specifics we would like to address in a structured legend scenario.

**Comment by alyec** [comment]
We do have the ability to set options on children of the main layer entry in the schema.
Main entry for a dynamic layer:
  https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/schema.json#L283
Entry for a node in `layerEntries`:
  https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/schema.json#L382

There was some discussion about how to split up the legend in structured mode on the wiki, but as Mike said we aren't actively working on it.  This is where we left off: https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Config-Schema#legend (essentially legend would provide the layout, but layers would still have the initial state of all the options).

**Comment by jolevesq** [comment]
Thanks Aly.  It was easy to remove setting from the 3 layers in the sample. I put ng-if="self.entry.options.setting" on the setting button in the panel. Now i will try to understand how it works and set it up for one child inside the dynamic layer sub group.

**Comment by AleksueiR** [comment]
The settings section of the config only indicates if the user is allowed access to the settings panel. The defaults is `true`, but the config author can set it to `false` preventing user from changing preset values for opacity/bounding box/etc. 

```json
{
  "id":"layer",
  "name": "layer name",
  "layerType":"esriFeature",
  "url":"http://my-layer/0",
  "options": {
    "settings": { "enabled": false }
  }
}
```

Setting `settings.enabled` to false will also grey out the `Settings` in the legend entry menu: 
![](https://i.imgur.com/Z3Bp3FK.png)

Here we are trying to remove the `Settings` option altogether if there are no actionable options in the settings panel regardless of the `settings.enabled` value set in the config. This can be done by removing the `settings` property from the legend entry object. With this section absent, the template will not draw the corresponding menu item.

The default values for legend entries are constructed at the build time from the schema and then injected into [geo.constant.service.js#L39](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/geo/geo.constant.service.js#L39).

I think it makes sense to add this check when the layer config options are merged with default values in `legend-entry.service.js` [here for single/child legend entries](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/geo/legend-entry.service.js#L88) and [here for group legend entries](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/geo/legend-entry.service.js#L305). Right now we have `boundingBox`, `opacity` and `snapshot` options which can appear in the settings panel. If all of them are `undefined`, the `settings` section should be removed as well.

**Comment by jolevesq** [comment]
I will do it this way. Every time we add a new parameters in setting we will have to remember to update this check.

**Comment by AleksueiR** [comment]
Yes, this is true, but this will be a schema change which doesn't happen to often anyway. We can actually enumerate options displayed in the settings panel in schema defaults (or maybe add a property indicating that this particular option will be in the settings panel) and check against them in the code. This way we don't need to modify the check itself.
