### ISSUE TITLE
Datagrid zoom-to-feature depends on object-id in first column

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#495]
See file `filters-default.directive.js`
`// FIXME: Assumes OBJECTID always first column`

This code always assumes the object id of the feature is in the first column of the grid.  In reality, it could be in any column, or not in a column at all (object id has no meaning to a user, there is no value in showing it).

In RAMP, we had an always-hidden grid column at the end of the table that contained system-ish information, including the objectid.  This is a potential fix for this.

**Comment by james-rae** [comment]
Alternative solution if we cannot manage the hidden column.  In the first row of the grid we are injecting image tags for the symbol and zoom icons.  We can add a data attribute storing the object id inside these tags, so it will be in the grid, but not rendered by the browser. The zoom function can then extract from the first column, even if the visible data is not the object id.

**Comment by AleksueiR** [comment]
Another option is to store a pointer to the column containing object ids. This saves a bit of data duplication.
