### ISSUE TITLE
Datagrid zoom-to-feature will zoom past a scale dependent feature.

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#496]
This was not implemented at the time due to the basemap-as-dynamic layer issue.

Enhance the zoom-to-feature to consider scale dependent features, and only zoom to a level where they will be visible.

[Code from RAMP](https://github.com/RAMP-PCAR/RAMP-PCAR/blob/release/Groundhog/src/js/RAMP/Modules/datagridClickHandler.js#L180) can be stolen to accomplish it.

**Comment by mweech** [comment]
Blocked as it is related to #411.
