### ISSUE TITLE
Efficiency of config load and language switch

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#498]
## Current Situation

When the application loads, it generates a configuration file for each supported language. This includes pulling in RCS configuration snippets; RCS is called once per language.

The advantage is that having cached versions of configs allows for a quick and 'easy to code' language switch.

The disadvantage is it is a performance hit (magnitude has not been tested) at startup.
## Proposal 1: RCS Returns All Languages

Have RCS return all languages for keys in one bundle.  This removes the need for multiple calls, which is the heavy part of the transaction (the data itself is moderately sized json data).  
Requires a change to RCS (guts and interface).  Also a change to the config loader in the app, but minimal.

Future enhancement: if large pieces of data start getting stored in the RCS (e.g. full blown legends), make that downloadable with a separate call and grab them as needed, not at startup.
## Proposal 2: Only Load Config Information For Current Language

No longer load all language configs at startup.  Only the active language.  When a language switch occurs, download and process the new config info.
Faster startup than Proposal 1, slower language switch.  
RCS is not changed
Significant refactor to config load and language switch code in the viewer.

Future enhancement: cache configs after first load, optimizing the rare case where someone can't make up their mind about language and keeps switching it.

**Comment by mweech** [comment]
Vote for proposal #2. Initial loading time should be prioritized over efficiency of switching language which should be done far fewer times than the initial load  (occurs for every user).  Lack of RCS changes being required is also a plus.

**Comment by yblain** [comment]
Is this still an issue?
