### ISSUE TITLE
chore(build): switch gulp build process to jspm (when adopting Angular 2)

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#50]
We might want to switch the entire (or most of it) build process to jspm when adopting Angular 2 and ES6 modules.

**Comment by jolevesq** [comment]
You don't want to do it now? Will not be easier to make this change soon in the project then later?

**Comment by alyec** [comment]
I was talking to Alex about this, I said it might be easier for people to deal with moving to a new toolchain + new dependencies (Angular 2) together.  Each time we switch things everyone has to learn the new tools so I suggested not doing them separately, but might be worth polling the team to see what the actual preferences are.

**Comment by mweech** [comment]
@alyec is this still valid? webpack is the new target?

**Comment by alyec** [comment]
webpack looks the most promising at the moment; we probably need to look at all build tools available when we get around to this as JS has something new every week

**Comment by mweech** [comment]
there is nothing driving this change and no definite tool that we want to switch to.  closing until a more specific request can be proposed.
