### ISSUE TITLE
Conditional dependency loading

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#500]
Some of the dependencies (like datatable and its plugins) might not be needed at all based on the map configuration. An embedded map, for example, might not need to display layer data, so we can dispense with loading datatables and its plugins.

Right now, dependencies are loaded in the [injector](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/injector.js#L1), and the config files are loaded only after the map instantiates, after everything else is ready. We can move config loading into the injector (probably need to combine that with the global registry as well) and decide with dependencies to load. The loaded config files can be passed to map instances through the global registry after that.

Some datatable export plugins (#452) are very heavy and they also should be loaded conditionally if the map author specifically allows for PDF or XSLT data export.

**Comment by mweech** [comment]
Noted by @AleksueiR during the workshop that this issue is out of date and not as valuable anymore.
