### ISSUE TITLE
featureIndex being hard coded to '0'

### ISSUE THREAD

**Issue by cynngah** [fgpv-vpgf/fgpv-vpgf#505]
Feature index should reflect the actual index of the layer.

Currently in toc.service.js toggleLayerFiltersPanel function with a FIXME

**Comment by spencerwahl** [comment]
Blocked by layer renderer issues: [to be replaced by issue link]

**Comment by AleksueiR** [comment]
This issue is fixed. Datatable does not display attributes from dynamic group layers because of #522.
