### ISSUE TITLE
feat(ui): enable nav buttons

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#51]
Nav buttons are currently decorative.  As soon as the geo module / geoapi is more developed add some functionality for navigation.

**Comment by AleksueiR** [comment]
So far, only `Zoom in`, `zoom out` and `Canada view` controls are available on the nav component.

**Comment by AleksueiR** [comment]
`zoomIn` and `zoomOut` buttons are connected.
Right now you need to wait until the zoom animation completes before triggering the next one; will enhance logic after event wrapping in gapi is done.

We can probably use some gcviz code, to connect marquee zoom button: https://github.com/GeoCanViz/GeoCanViz/blob/f5a7bb99a44ed774795dfff9055870ed4b39a5ac/src/js/widgets/viewmodels/mapVM.js#L231

**Comment by AleksueiR** [comment]
Do we need zoom marquee in the beta build? If not, we can open a separate issue and close this one.

**Comment by jolevesq** [comment]
I don`t think we need it. This is something that can wait for a while.

**Comment by mweech** [comment]
Zoom Marquee captured under #353 
Zoom animation blocks further zoom clicks under #354
