### ISSUE TITLE
Allow Layer Re-ordering to be performed using the Keyboard

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#511]
Provide the ability for the user to perform layer re-ordering (#271) using a keyboard instead of the mouse.

**Comment by jolevesq** [comment]
Angular does not seem to be keyboard accessible. We will have to implement the functionality's (https://www.sitepoint.com/accessible-drag-drop/)

**Comment by AleksueiR** [comment]
Did you mean Dragula? Angular Material is quite keyboard-friendly.

**Comment by jolevesq** [comment]
You are right, I mean Angular-Dragula

**Comment by AleksueiR** [comment]
Here's another example I used before from Open Ajax Alliance: http://oaa-accessibility.org/examplep/draganddrop1/

**Comment by jolevesq** [comment]
Some comments from a discussion between me and Alex:

- Create a drag handle inside the legend entry the user can tab to and focus (it should be impossible for mouse user to set focus on this handle). Container element focusable can interfere with mouse users.
- On focus, CTRL+M will select the element. It will highlight the container inside where it can moves
- Arrow will move the focus to up/down entry element
- On Enter it will drop the selected element below the element with the focus
- Esc will cancel everything

**Comment by jolevesq** [comment]
I have followed https://www.sitepoint.com/accessible-drag-drop/ for keyboard navigation. I haven't use CTRL+M. We can add it if need be.

- SPACE bar on the handle will grab the element
- Focus is set the first availalble area to move to
- Focus is block inside moveable element. User TAB thought the elements to the selected area
- ENTER will drop the element below the selected one
- ESC will cancel

When in drag mode, all functionalities are disable(e.g. controls are note tabbable). As soon as the drag is over, all functionnalities come back and focus is set on the drag originator handle

**Comment by mweech** [comment]
@jolevesq @AleksueiR Given Johann is on leave as of next week, I wanted to make sure transitioning this task is on the radar for tomorrow...

**Comment by AleksueiR** [comment]
There are some ~~limitations~~ bugs with reordering: trying to reorder while some of the layers are still loading messes everything up and any reorder after that will be wrong.
