### ISSUE TITLE
Change RCS /docs API call to unwrap layers

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#513]
Currently RCS `/docs` will return something like

``` js
[{layers:[{fancyPoints}]},{layers:[{snazzyLines}]},{layers:[{blandPolygons}]}]
```

With each element in the layers array having length one.  This makes it a stand alone config fragment which can be easily merged with other configs.  However, the viewer does not use it in this manner.  Some options:
- change `/docs` to return something which the viewer doesn't have to unwrap
- expose a new endpoint `/layers` which returns a nicer format
- leave it alone

**Comment by james-rae** [comment]
Preference 1. Lazy 2. add `/layers` 3. change `/docs` , but I think all are reasonable

**Comment by spencerwahl** [comment]
Just looked back at this code; this is what we currently have (blame past-Spencer):

```
const result = { layers: [] };

resp.data.forEach(layerEntry => {
    // if the key is wrong rcs will return null
    if (layerEntry) {
        result.layers.push(layerEntry.layers[0]);
    }
});
```

I think the easiest solution is to leave docs as is, change the above to:
```
const result = [];
resp.data.forEach(layerEntry => {
    // if the key is wrong rcs will return null
    if (layerEntry) {
        result.push(layerEntry);
    }
});
```

And we can also change mergeConfigParts to:
```
function mergeConfigParts(targetConfig, configParts) {
    configParts.forEach(part => {
        angular.merge(targetConfig, part);
    });
}
```

The only thing I'm unsure of is any performance issues with angular.merge

**Comment by james-rae** [comment]
agreed.  this will also resolve the FIXME in function `rcsLoad`

**Comment by mweech** [comment]
obsolete
