### ISSUE TITLE
Synchronize Map Service order with Service order in Legend

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#514]
When changing the order of the layers as they appear in the legend, it is necessary to synchronize these changes with how the services are drawn on the map.  Currently services are being added to the map in the order in which they respond to asynchronous loading calls.

Need to determine the most efficient manner to complete the synchronization.  TOC should drive the order as this would allow for structured legends to be more easily implemented at a later date.

**Comment by james-rae** [comment]
In RAMP, we had a very convoluted system of flags and counters to keep the two in synch.  Alex has suggested a more elegant model

Rough idea:

```
user drags layer to new location.

iterate down the legend, starting at the item directly below where the new item is
return the first non-error'd legend item
store it's layerId as target

iterate through the map stack (keeping in mind different stacks for image and features)
find the layer with id == target
perform a re-order to move dragged layer above target layer
```

**Comment by james-rae** [comment]
It looks like good feedback for above idea.  As this is required for the issue referenced above, I will probably start on the logic unless anyone objects soon

**Comment by james-rae** [comment]
# Design Notes

## How ESRI API Works for Layer Order

The map has two arrays representing it's two stacks.
`map.graphicsLayerIds` <-- list of feature graphic layer id strings
`map.layerIds` <-- list of raster layer id strings
Order in the array represents the draw order
0 is the bottom of the draw stack

Two main functions that use layer order
`map.reorderLayer(layerObject, newIndex)`
`map.addLayer(layerObject, insertIndex<optional>)`
In both these functions, the index is relative to the local stack (feature or raster), not the grand combined stack.

## Legend Data in Viewer

This [Pull Request](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/529) shows the latest changes and key locations of legend data in the viewer.

## Functions to Create

### Find Valid Layer Base in Legend

#### Usage

Called at the completion of a layer reorder drag event, to determine where the dragged layer should go.
Called at reload button click, to determine where layer should be re-inserted (in error case, it is possible the layer has been kicked out of, or was never in, the map, so we cannot rely on the map id arrays)

#### Main Steps

Determine the starting position as an index (i.e. where layer was dragged to, or where reload was clicked

From starting position, move down the ordered legend array.
- if layer is in error state, skip and continue
- else return the layer id of this entry

If no valid layer is found, should return a special token to indicate the bottom (e.g. `null`, `~~bottom~~`)


### Find Insertion Index in Map

#### Usage

Used to determine the appropriate index for a layer reorder or insertion to the map

#### Main Steps

Parameter: layerid (string) the layerid that is below our insertion point
Parameter: layerFlavour (string) indicates if we are on the feature or raster stack

`idArray` = is the appropriate map id array based on the layerFlavour (`graphicsLayerIds` or `layerIds`)

If layerid is not bottom token, return `idArray.indexOf(layerid) + 1`

if bottom token, we cannot just return 0, as there may be non-user layers lurking around (e.g. basemaps, highlight graphics layers, weird orphaned error'd layers that wern't given the boot).

`userIds` = Make an array of valid layerids using the layer registry

`i` = 0  

loop
-  if `idArray[i]`  is in `userIds`, then return `i`
-  else `i++`

if nothing was found, return `idArray.length`
