### ISSUE TITLE
Trying to print "Plant Hardiness Zones of Canada 2000" hangs the browser

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#515]
This layer has a lot of features:
![](https://i.imgur.com/WDJ2Oaj.png)

Exporting to a .csv takes a while but it works in the end.

**Comment by mweech** [comment]
Good bug to start a discussion..

It is inevitable that we will run into some upper limits on performance re: # of features in a layer.  A few ideas that have been thrown around:

1. Perform some tests with heavy layers to determine a relative sweet spot for performance and then build in warnings to the user that a layer is "heavy" and ask for confirmation before loading the feature details in the datagrid
2. Paginate the pulldown of features.  Would require custom code to enable some of the other freebies we get along the way (i.e. # of features in a layer)

**Comment by mweech** [comment]
There was no discussion.
