### ISSUE TITLE
WMS Legends inserted as Layer Symbology Graphics

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#517]
WMS Legend graphics are being inserted into the graphical element for layer symbology.  This should be replaced by a generic symbol for to represent OGC WMS layers and have the legend provided in a similar fashion to how RAMP displays it.

**Comment by mweech** [comment]
@AleksueiR thoughts on how to display the graphic? stay with how RAMP does it or is there a more elegant alternative?

**Comment by AleksueiR** [comment]
I think we should keep the icon representation of wms legends and scale them up when the legend is expanded. 
This ...
![](https://i.imgur.com/uYqWFXi.png)
...will expands into this:
![](https://i.imgur.com/FtBT0ZR.png)


Having tiny versions of wms legend images as layers' icons will give toc entries some distinctiveness and help users to quickly tell them apart.

In RAMP wms layers look the same sans names:
![](https://i.imgur.com/Cd0manz.png)

I think it's much better with variable icons:
![](https://i.imgur.com/hqjLazc.png)
