### ISSUE TITLE
Mouse is offset in WET-hosted map

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#521]
In map viewed in `index-fpg-en.html`, the mouse clicks are registered about 5mm to the right of the cursor.  Easiest way to see this is to hold the shift key and drag the mouse, triggering the marquee zoom.  Identify clicks must also be offset to register a hit.

Best guess is WET CSS is messing things up with a padding or margin pushing things around.

**Comment by AleksueiR** [comment]
I vote for the padding/margin cause.

**Comment by mweech** [comment]
Has some overlap with #482.

**Comment by AleksueiR** [comment]
Duplication of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/623, possibly.

**Comment by mweech** [comment]
fixed in #623
