### ISSUE TITLE
Proposed Changes to Legend, Symbology, and Attribute Loading

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#522]
## Current Situation and Issues / Opportunities with it

Displaying icons for individual features (grid rows, and in future, details pane and map tips) is accomplished by using the layer's renderer to determine the appropriate icon.  Not every layer has a renderer on the client side :rage4:.  This was an oversight, chalking it up to still thinking in a RAMP headspace.  Currently, icons won't be derived for non-feature layers.

Layer legend information is grabbed from a Legend service.  Code to support ESRI layers without this service (Feature Service & File-based) is in testing phase; it converts a renderer to legend content.  It may be possible to use this approach for the majority of layers, avoiding an unneccessary call to the legend service.

When loading attribute data, the application waits for all attribute sets to load prior to registering the layer with the map. In cases of Dynamic Layers, this means data for all sublayers.  This can lead to one jumbo sublayer holding up the layer loading process.

## Proposed Changes

Update the [attribute loading process](https://github.com/fgpv-vpgf/geoApi/wiki/Attribute-Loader-Architecture#attribute-data-structure) to include the following

* Each feature layer bundle will also grab and store the renderer for that layer.  We are already querying the service, so there are no additional calls.
* Data in the attribute bundle will be split into two separate promises -- one containing layer metadata (`oidField`, `fields`, `renderer`), the other containing attribute information (`features`, `oidIndex`).  This will allow us to register and generate a legend prior to attributes loading, and will allow attributes from light sub-layers to be viewed while waiting for heavy sub-layers to finish loading.

Sample structure of bundle ( Promise indicates a promise object resolving with inner contents)

```
{
    "layerId": "<layerid>",
    "layerIdx": 3,
    "attribData": Promise(
		{
			"features": [
				{
					"attributes": {
						"objectid": 23,
						"name": "Bruce",
						"age": 27
					}
				},
				...
			],
			 "oidIndex": {
				"23": 0,
				...
			}
		}
	),
	"layerData":  Promise(
		{
			"fields: [
				{
					"name": "objectid", 
					"type": "esriFieldTypeOID", 
					"alias": "OBJECTID"
				},
				...
			],
			"oidField": "objectid",
			"renderer": {...}
		}
	)
}
```

Attempt to use renderer-to-legend code for all applicable layers.  If this becomes problematic, we can always fall back to using server legend service (as it works now).

Tile service will continue to use the Server Legend service, as it is far more efficient than querying the renderers of all child layers.

Update code that accesses attributes to adopt new bundle structure (mainly grid load and identify results for feature layers).

Update icon mapping code to adopt new bundle structure, and use cached renderer instead of layer renderer for lookups.

**Comment by AleksueiR** [comment]
I believe we can also simplify how symbology is mapped to features - instead of mapping the renderer to the legend endpoint and then mapping that to the attributes, features can be directly mapped to the renderer. Here's a [gist](https://gist.github.com/AleksueiR/56396aebd55f39cdad859e71a4df4e4c) with some related code.

**Comment by james-rae** [comment]
May make sense to sneak https://github.com/fgpv-vpgf/fgpv-vpgf/issues/485 into this refactor, as the same codebase is affected

**Comment by alyec** [comment]
One extra suggestion based on a pod discussion.  We should defer the attribute promise for dynamic layers until the data is actually needed (will not affect identify).  Add a config option to trigger eager loading to hint to the viewer that layers are small and can be fully loaded up front.

**Comment by mweech** [comment]
This issue is concerned with implementation of geoApi changes and not tied to UI.  These will be accomplished as part of #537.

**Comment by james-rae** [comment]
Part of this change is to get renderer info for all layers, which will be utilized by the code in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/397
