### ISSUE TITLE
Setting opacity on dynamic layer subgroup has no (strange) effect

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#528]
Setting opacity on the root group of a dynamic layer changes the opacity of the whole layer; setting it on the a leaf, changes leaf's opacity relative to other sublayers; setting opacity on a subgroup (any value) seems to reset opacity of its children. See below:

![](https://fgpdoc.zz9.ca/index.php/s/rsyKw4qgK4ztCIK/download)

I suggest we either propagate the opacity value to group's children or remove the opacity setting from dynamic layer subgroups.

**Comment by jolevesq** [comment]
I think we should not remove opacity to children by default. This way user have the ability to change opacity of all layers individually. You should remove opacity setting  to the root and let it to the children.

**Comment by AleksueiR** [comment]
Not from the leaf-children, subgroup-children. In the gif above, `Air Quality` is a subgroup of the `AAFC AGRI Environmental Indicators` layer. We should definitely keep the opacity controls for leaf-children.

**Comment by mweech** [comment]
behavior is really unpredictable, especially when playing with the additional parent level transparency control.

**Comment by jolevesq** [comment]
When I play with, AAFC AGRI Environemntal Indicator, only the root level opacity works. When I set children, nothing happen.

**Comment by AleksueiR** [comment]
It does work, it just really slow.

**Comment by jolevesq** [comment]
This is very confusing. I had to wait almost 10 seconds to set opacity on relative soil. If I change opacity on air quality, nothing happen. Root level is very fast. Do you know why children is so slow.

Another weird thing, opacity on last level children  do not change opacity but color...

To make a resume, works fine on root, nothing happen on middle group container (air quality) and slow with weird behaviours in lat child (2011 Greenhouse, see image below)

![screen shot 2016-06-08 at 9 21 56 am](https://cloud.githubusercontent.com/assets/3472990/15895693/a4bfee7e-2d5a-11e6-8cbe-4808a32019bc.png)

**Comment by AleksueiR** [comment]
This doesn't seem to be relevant anymore in 2.0. Setting opacity on dynamic group, propagates the value to its children; if the layer doesn't support child opacity, it's set on the layer itself.
