### ISSUE TITLE
Support grids with no object id column

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#534]
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/495 resolved our dependency on having the object id in the first column of the grid.  In the future, we may have a further problem where the object id is omitted from the grid alltogether (a valid use-case, as the ID means nothing to a user).

Currently, our attribute loading and grid population logic take everything, including object id, so this issue is not an immediate problem.

One potential solution - we move the logic from `filters-default.directive.js - createTable()` and place it in `layer-registry.service.js - formatLayerAttributes()`.  Have the formatter automatically add object id as an additional "last column", and continue to have the datagrid hide it.  This way we can map the object id to the grid row without having to put the id in the visible columns.

**Comment by AleksueiR** [comment]
I would also suggest we figure out and add an icon id at this point (`formatLayerAttributes`), so we don't have to constantly crunch the same data attributes every time a table is rendered.

**Comment by cynngah** [comment]
After some testing, it seems like there is no need to store object ID in a hidden column anymore. Retrieving object ID with `row.data()[displayData.oidField];` works fine even when the object ID is not present.
