### ISSUE TITLE
Integrate on demand attribute loading

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#537]
In order to provide datagrids for Group Layer children (#174), symbology had to be temporarily removed until such time as (#522) was accomplished.

**Comment by AleksueiR** [comment]
fgpv-vpgf/geoApi#105 PR will be be integrated before symbology can be added to the group layer datatagrids.

**Comment by AleksueiR** [comment]
- [ ] connect on-demand attribute promises to datatagrid
- [ ] fix broken identify
- [ ] restore feature count for toc entries
