### ISSUE TITLE
chore(build): update bezier-easing dependency to 1.1.1

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#54]
Use `get` function; read more here: https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KyQZYcl5rvw4AkkuK

**Comment by spencerwahl** [comment]
1.1.1 is only available on npm, not bower

**Comment by milesap** [comment]
bower continues to only support [v1.0.0](https://github.com/mattstyles/bezier-easing). Closing after a very long wait :disappointed:

**Comment by AleksueiR** [comment]
No support needed - you can target a github release or a branch with bower.

**Comment by milesap** [comment]
Ok let me know the target value and I'll update this

**Comment by milesap** [comment]
No luck with `bower install https://github.com/gre/bezier-easing/#2.0.3` including the `--save` and `--force` flags

> bower                     ENORESTARGET URL sources can't resolve targets

**Comment by AleksueiR** [comment]
`.git` is missing: `bower install http://github.com/gre/bezier-easing.git#v2.0.3`

**Comment by milesap** [comment]
I tried that but got another error ` ECONFLICT Unable to find suitable version for bezier-easing` which is odd as we are giving it the version explicitly

**Comment by AleksueiR** [comment]
We are referencing 1.0.0 version in the bower file. Try updating it and running `npm install` or remove that line and running `bower install http://github.com/gre/bezier-easing.git#v2.0.3` again.

**Comment by milesap** [comment]
So I removed the line in bower, which gave the same issue so I deleted the bezier-easing folder in lib which seemed to make it work. However the page fails to load indicating `Uncaught ReferenceError: BezierEasing is not defined`

**Comment by AleksueiR** [comment]
They must have changed the global library name or something else. :(

**Comment by milesap** [comment]
It's still `BezierEasing` - strange

**Comment by milesap** [comment]
No longer relevant, also removing animations on v2
