### ISSUE TITLE
Viewer does not load in IE

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#541]
Problem: A line using `Array.from` was moved into injector.js which is before the polyfills.

This line should be replaced with something IE can handle.

**Comment by AleksueiR** [comment]
We decided to move back to using [slice](http://blog.cluster-text.com/2013/04/29/a-trap-when-looping-on-getelementsbyclassname/):
```js
[].slice.call(document.getElementsByClassName('fgpv'));
```

**Comment by spencerwahl** [comment]
PR #543
