### ISSUE TITLE
Add scrollbar to layer selector in details panel when overflowing

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#545]
If the map is in a small container or a number of queryable layers is large, the layer selector in the details panel can overflow. By default, the scrollbar is hidden, but it should be visible when the selector is expanded on hover. Truncate overly long layer names and maybe make the selector itself a bit wider.

![](https://i.imgur.com/as4oaRb.png)

**Comment by mweech** [comment]
Users will need to see the full text of the layer in question.  Implementation will need to make sure that is available, via either a tooltip, or full display of layer names.

**Comment by spencerwahl** [comment]
- [x] add scrollbar to expanded details selector
- [ ] add layer group name to details title
- [ ] prevent close button from covering title
