### ISSUE TITLE
Change how translations are loaded

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#550]
Right now we split a CSV file into multiple json files, and then access those files at run time.

An alternative approach is to inject that json into a constant at build time; this will cut down on file accesses and should simplify future usage of the translation objects.

- inject the translations objects in a similar way to the version number
- change the way translateProvider receives the translations
- change the $http.get in the shell directive

**Comment by mweech** [comment]
no feedback on this discussion nor a good sense of what needed to be done when asking for estimates.  will not be including this in current sprint.

**Comment by AleksueiR** [comment]
What if there are multiple languages (not only English and French)? Do we still want to included all of them in the source or just En/Fr and download when needed?

**Comment by alyec** [comment]
This got rolled into #768 and is included in PR #804 closing for now.  We may revisit if we do add support for several different languages.
