### ISSUE TITLE
Add a legend entry placeholder to toc when adding layers to the map

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#551]
Right now, a legend entry is inserted into the toc only after the esri layer `load` event. If a layer fails on the initial load, nothing is added to the toc and there is no way for the user to manually reload that layer.

Need to insert a placeholder legend entry when adding a layer to the map object, and replace the placeholder with a proper legend entry on the `load` event or set it to the error state if loading fails.

**Comment by mweech** [comment]
#450 will allow for these layers to be retried after failing on initial load.

**Comment by spencerwahl** [comment]
- [ ] create new placeholder template
- [ ] add placeholder before layer-load callbacks
- [ ] replace with actual layer on successful load, toggle to error state if unsuccessful
- [ ] modify layer entry code to place layer where the placeholder was

**Comment by spencerwahl** [comment]
(Very) Early weekly update in case someone needs to take over:

Current work is on: https://github.com/spencerwahl/fgpv-vpgf/tree/layerPlaceholders

- added a simple placeholder template
- added an `addPlaceholder` function to legendService which essentially mocks an entry (as theres no layer to create one with) and tries to add it to the legend
- added untested code to replace the placeholder with the actual layer or toggle the state to error

Tests build, map loads, layers load, but the legend isn't being populated. Devtools are freezing on me so I'm unsure of the exact cause.

**Comment by spencerwahl** [comment]
Estimate turned out to be too small, ran into problems with layer-loading events (the handshake triggers the load event, update-end is when data appears) as well as not accounting for enough PR time. 8 would have been more accurate.
