### ISSUE TITLE
Update Legend Service to Account for Scale Dependent Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#552]
Stolen from James's post below: 
- [x] Determine if a layer is visible, yet off-scale. Steal [ramp code](https://github.com/RAMP-PCAR/RAMP-PCAR/blob/master/src/js/RAMP/Modules/filterManager.js#L757) for the way to do this.
- [x] Check the state of each layer every time the zoom level changes.  Utilize the `extent-change.levelChange` event property so we are not checking on pans.
- [x] Also run the check when a layer has it's initial load
- [x] Update the legend item's state using the `setLayerState` function in legend service

**Comment by james-rae** [comment]
Things to do

Determine if a layer is visible, yet off-scale. Steal [ramp code](https://github.com/RAMP-PCAR/RAMP-PCAR/blob/master/src/js/RAMP/Modules/filterManager.js#L757) for the way to do this.

Check the state of each layer every time the zoom level changes.  Utilize the `extent-change.levelChange` event property so we are not checking on pans.

Also run the check when a layer has it's initial load

Update the legend item's state using the `setLayerState` function in legend service

**Comment by james-rae** [comment]
In progress. Design is done, refactors to modules have changed where properties are so a bit of backtracking. Detection code is written, map trigger written, working on applying it correctly to states. Have not been 100% on this task.

**Comment by james-rae** [comment]
Update:  the "steal code from RAMP" approach does not support child sub-layers of Dynamic Layers.  RAMP used an API call that would determine if a layer was on or off scale.  This means that if one component layer of a Dynamic Layer is on scale, it is considered on-scale, regardless if all other component layers are not.

Will adjust geoApi to grab the actual scale boundaries during the attribute metadata scrape, and utilize these numbers to determine the scale status of all layers and sub-layers

**Comment by james-rae** [comment]
Will require some integration / refactoring when https://github.com/fgpv-vpgf/fgpv-vpgf/issues/426 is completed
