### ISSUE TITLE
Update Legend to Indicate Layer is Out of Scale

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#553]
- [x] Logic: compare maxScale to current zoom scale; check whenever a zoom is completed
- [x] UI: Display meaningful message (probably beside the layer info in red text under the layer name); hide when logic returns false and display when logic returns true

**Comment by james-rae** [comment]
Step 1 will be covered by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/552 .  This code should be able to reference the `flags.scale` property of the legend entry to determine if the layer is on or off scale

**Comment by cynngah** [comment]
Blocked until #552 is completed. Need the logic to be able to test whether the icon is showing up properly.
