### ISSUE TITLE
Heavy dynamic layers don't load attributes

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#555]
I noticed that attributes for these two heavy layers don't load anymore (since last week of april):

http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_census_of_agriculture_2011_ccs/MapServer
http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_agri_environmental_indicators/MapServer

**Comment by james-rae** [comment]
Appears to be working ok now. 
The first URL you posted is also affected by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/485
