### ISSUE TITLE
Zoom to Feature adds Highlighting for Emphasis

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#557]
When completing a Zoom to Feature request from the data grid, it is not always obvious the Feature that is being Zoomed to, particularly for feature rich areas of the map such as the JOSM layer (see screenshot).

We need to highlight the feature that has been zoomed into.

![capture2](https://cloud.githubusercontent.com/assets/7583387/14963015/bd9874b4-106f-11e6-917f-b4cbb2f2c7b1.PNG)

(my drawing ability > *)

**Comment by mweech** [comment]
Looking for suggestions of best way to emphasize the feature.

**Comment by AleksueiR** [comment]
For features layers we can use the RAMP approach of cloning the target graphic, adding a tooltip, and making other layers slightly transparent.

**Comment by james-rae** [comment]
The zoom framework pulls down the geometry for the thing being zoomed to, even if it is displayed as a dynamic layer. Applying the geometry, plus the renderer (which we will now have), to a graphic layer, should make a clone for anything based of a feature source (even WFS should technically work).
I believe GCViz uses a similar approach

**Comment by mweech** [comment]
This will leverage the functionality being implemented in #677.
