### ISSUE TITLE
Make Viewer Fullscreen Option more Obvious

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#559]
Fullscreen option is currently buried in left-side menu, making it harder to find.  Need to establish a more obvious option for the user to switch to fullscreen mode.

Thoughts:
- Would be different depending on the space available to the viewer
- Should be allowed to disable feature in thematic maps
- Mobile would likely work differently

**Comment by AleksueiR** [comment]
Notes:
can use the overscan icon for full screen; 
![2016-05-24 11_41_09-material icons - google design - waterfox](https://cloud.githubusercontent.com/assets/2285779/15510214/8dd4a888-21a4-11e6-9c9c-850284ae6204.png)

**Comment by AleksueiR** [comment]
## Notes from UX review:

#### when embedded into a host page
-  if the embedded container is very small (say smaller than 200px or 10%), 
  - the whole map acts is a full-screen button (on mobile this mode is on by default) or 
  - an overlay with full-screen button is shown on hover/focus (configurable);
- with larger app containers, the full-screen button is (possible) in the lower right corner, (apart from other buttons ?);

#### when used a single-page application
- the full-screen button is hidden

**Comment by milesap** [comment]
On hold - not in current sprint

**Comment by jolevesq** [comment]
There is an icon in angular material, should we use this one?

**Comment by AleksueiR** [comment]
We are going to add more functionality (open legend and open basemap selector) to the left-side menu to make it __easier__ to find, and I don't think the argument that

> Fullscreen option is currently buried in left-side menu, making it harder to find

holds any more. Needs more discussion, I think.

A mad suggestion:
- when viewer container is small (medium and small layouts) and is embedded in a host page (not taking the full page), show the full-screen button in the place of the map overview (we hide the map overview on medium and small layouts anyway).

**Comment by mweech** [comment]
Removed from Usability results epic.  Will remain in backlog and handled as a feature request.

**Comment by milesap** [comment]
Summary (applies only for layouts that do not have `rv-fullscreen` attribute:
- Add a fullscreen mapnav button (under the help button) for large layouts
- Add  fullscreen icon in top right corner for small/medium layouts 

If this is the case we would not implement the idea where small/medium layouts have an overlay covering the entire map which acts is a full-screen button.

**Comment by AleksueiR** [comment]
Small correction:
- Add fullscreen icon in top right corner for small/medium layouts __and remove fullscreen mapnav button (otherwise you will end up with two fullscreen buttons)__

Also, mapnav/overview fullscreen buttons presence should be controlled by the `navBar` config section.

Agree with not implementing the fullscreen overlay.
