### ISSUE TITLE
Fix dist packaging

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#566]
`gulp dist` currently bundles everything as part of the build.  There should be an option to build only the main viewer library.  Some options:
- injector.js with remote loading
- single JS file (loads all the CSS and JS together)
- injector.js with local library bundle (JS and CSS loaded by injector)

Some notes from our discussion: if we don't load CSS quickly the map loading spinner will not be displayed.  Single JS files are easy to work with, especially when building an app with multiple dependencies it is helpful if libraries do not require you to load their parts in a specific order.

**Comment by mweech** [comment]
out of date
