### ISSUE TITLE
bug(geo): retrieving feature count sometimes fail

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#570]
When trying to get feature count, the query call sometimes fails with
```json
angular.callbacks._c({"error":{"code":400,"message":"Unable to complete operation.","details":[]}});
```

When this happens, feature count is not shown:
![](https://i.imgur.com/r4aQTae.png)

@james-rae, James, do you have an idea why calls might fail? Can it be because of many calls made simultaneously (think dynamic layer with many children)?

Two options to handle it:
1. Keep trying to get feature count since we know the layer itself is not broken and this error must be temporary. (If errors occur because of the number of calls, we can stagger them out a bit).
2. Give up and show an error message.

**Comment by james-rae** [comment]
Service appears to have an issue we've seen before, where every second call fails.  Believe the source is an issue with load balancer or web adaptor (thanks Dan!). 

For us, either of your two options should be acceptable in this case (try twice if you chose the first option).
