### ISSUE TITLE
Attribute Formatting Framework

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#573]
Would like to have a good, flexible way to format attribute data for the user.  This can include
- date formatting
- numeric formatting
- turning URLs into hyperlinks

The formatting specification should be configurable, and there should also be some defaulting logic to take advantage of field metadata (e.g. an ESRI date field could auto-format without config specification).

Things that could use this include
- datagrid content
- details pane content
- maptip content
- metadata content

See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/455 for some initial idea discussion.  As well, code added in that issue specifically for date formatting should be leveraged (if possible) in the formatting framework

**Comment by mweech** [comment]
No discussion since opening 2.5 years ago.
