### ISSUE TITLE
bug(ui): basemap description is truncated

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#574]
Basemap description is truncated; need a better way to present this information.

![](https://i.imgur.com/rROTFbn.png)

Maybe something like this:
![](https://i.imgur.com/6PuUPYp.png)  ![](https://i.imgur.com/HLZhWec.png)

**Comment by mweech** [comment]
Like having more prominent basemap description available.  Much more usable.

How would the description come into view?  Is it statically available at all times, and in that case, would it not become fairly real estate heavy?

**Comment by AleksueiR** [comment]
The description shows up on hover/focus (didn't have time to make a gif).

**Comment by AleksueiR** [comment]
Hover effect gif:

![basemap_description](https://cloud.githubusercontent.com/assets/2285779/15144528/ed863ed6-167d-11e6-9582-a1e92c4320df.gif)
