### ISSUE TITLE
RCS error messages appears twice

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#593]
The error message indicating that RCS is not responding appears twice. @spencerwahl suggested it is due to getting data for English and French config files.

![rcs_fails](https://cloud.githubusercontent.com/assets/2285779/15216692/3116ea98-1826-11e6-935a-637c6c2589c3.gif)

**Comment by james-rae** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/498

**Comment by james-rae** [comment]
Revisited in RAMP `v2.3.0`.  Tweaked RCS endpoint to bad url.  No toasts appear at all.

Need to look into why they're not triggering.
