### ISSUE TITLE
Stop Pulling Tiles for Blank Basemap Entries

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#595]
Our basemap selector generates it's thumbnails by grabbing some random tiles from the basemap it represents.

We have two entries in the selector to represent blank basemaps.  The logic to pull tiles is still being applied on these, resulting in `404 (Not Found)` errors in the console (as it attempts to pull tiles from a non-existent service)

Add a check to prevent the thumbnail grab on the blank entries.

**Comment by AleksueiR** [comment]
Set url of the blank basemap to the empty gif:
```
data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7/
```

**Comment by AleksueiR** [comment]
We should also stop pulling blank overview image: 
> init.js:134 GET http://localhost:6001/images/overview.png 404 (Not Found)
