### ISSUE TITLE
bug(ui): jitter of legend entry toggles on hover (wet page only so far)

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#603]
You can see visibility toggle moving up and down 1px when the legend entry is hovered over.

![wet_page_jitter](https://cloud.githubusercontent.com/assets/2285779/15255898/a57c8046-190c-11e6-8a22-ef2a128fb6be.gif)

Rough solution idea: 
- change the toggle container to a flex box

**Comment by mweech** [comment]
cannot reproduce anymore.
