### ISSUE TITLE
bug(ui): rcs error toast is squashed in IE11

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#604]
This is wrong:
![](https://i.imgur.com/xKtFCHd.png)

**Comment by ChrisLatRNCan** [comment]
I added flex attributes to toast class
        flex-grow: 1;
        flex-shrink: 1;
        flex-basis: 50%;

**Comment by ChrisLatRNCan** [comment]
As suggested by @AleksueiR I put flex css attribute to auto (flex-grow: 1; flex-shrink: 1; flex-basis: auto;)
