### ISSUE TITLE
Complete Translations of French Text

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#607]
- [x] Extract and compile a spreadsheet of text that needs to be translated
- [x] Review english strings in the translation file for validity
- [x] Have text translated
- [x] Integrate translated text

**Comment by ChrisLatRNCan** [comment]
Translation of translation.csv file is done. Still doing the QA.

**Comment by ChrisLatRNCan** [comment]
Few observations: 
- Function applyFeatureCount in legend.service.js doesn't retrieve properly french translation of the data type found in the translations.csv. Probably another issue will need to be created;
- Here and there some text are not translate and don't seem to be related at all with translations.csv. Probably few reasons for that (config file, ESRI dynamic service, error messages, etc).
