### ISSUE TITLE
Style Metadata Output

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#608]
UI panel that contains metadata output should be styled similar to R1.  This should be done in both the initial metadata panel and the popout panel.

![metadata panel](https://cloud.githubusercontent.com/assets/7583387/15290020/d4380016-1b43-11e6-8270-8f1c962f9a8a.PNG)

**Comment by AleksueiR** [comment]
What's initial metadata panel?

**Comment by james-rae** [comment]
I believe "initial" is the slide-out panel, and the popout is the larger panel miles implemented

**Comment by AleksueiR** [comment]
Thanks.

Ah, the popup dialog. It uses the same directive to generate the content as the side panel, so it doesn't add much to the work.
