### ISSUE TITLE
Integrate File Based Layer Import with UI Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#611]
Depends on #112

**Comment by AleksueiR** [comment]
I keep running into errors when trying to generate file-based layers.

**Comment by AleksueiR** [comment]
Impossible to load non-local files due to #702 (unless the host is added to the proxy) right now.

**Comment by mweech** [comment]
@AleksueiR that is because we are using a whitelist based proxy.  let's continue to work on the functionality as the proxy used elsewhere would not be based on a whitelist.  we should probably consider allowing this functionality to be disabled in the settings however.
