### ISSUE TITLE
bug(geo): cannot zoom to feature (Land Pub sth Zone layer)

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#616]
It works for the JOSM feature layer.
See console output:

> service.js:115 Uncaught (in promise) Error: Source projection not recognized by proj4 library(…)

![can t_zoom_to](https://cloud.githubusercontent.com/assets/2285779/15308062/39d3fa20-1ba7-11e6-8f18-149d2b46004e.gif)

**Comment by james-rae** [comment]
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/281 

That layer has a custom string projection, which i would imagine is killing the limited support we have for client-based projections at the moment

**Comment by AleksueiR** [comment]
Thanks for explaining.

**Comment by mweech** [comment]
should provide an error message indicating something along the lines of "This functionality is not supported when geospatial data is using a custom projection."

**Comment by AleksueiR** [comment]
I apologize for not being on top of this, but showing an error toast in this situation is not the right approach. Imagine, user clicks on one item, gets an error, clicks another, gets an error, clicks a third one, gets another error. At this point user doesn't know if it applies to all the points or just some of them.

A better approach would be to detect if graphics can be reprojected at all when the table is first created by trying that on the first item, for example. If reprojection is not possible, disable all zoom controls and update their tooltips to say something like "Data in custom projection. Cannot zoom to feature".
