### ISSUE TITLE
Throttle initial layer loading

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#618]
With about ten layers added upfront, the app become unresponsive for a while when layer data is loaded (after the loading screen is removed). 

In this gif, I clicked on the legend button in the first frame and it takes a couple of seconds for the main panel to simply open:
![layer_lag](https://cloud.githubusercontent.com/assets/2285779/15327783/8df2c928-1c20-11e6-85d8-0034b35adc94.gif)

I think we can improve (visible) performance here by not allowing all the layers to load at the same time. We can add a timeout to start loading layers in a staggered fashion or impose a limit on how many layers can be loading at a time (thanks @alyec Aly).

**Comment by milesap** [comment]
Should throttling only occur for mobile devices (i.e. touch enabled devices like iPhone and Android) or for all devices?

What would be a reasonable limit for the number of concurrent layers to be loading (3, 5, or 8)?

**Comment by AleksueiR** [comment]
All devices.
Let's try 3, and see how it works out.

**Comment by milesap** [comment]
It's a good idea to have all placeholders generated immediately followed by the throttled loading of the layers. In the current PR implementation (#1554) however, layers appear as soon as they start loading. There is no best way that James or I can see to render all placeholders up front without spending a good amount of time modifying `legend.service.js` and the `legendEntryFactory`. We have a few options:

- Estimate and open a new issue (I would guess a 5-8)
- Shelve this for a future code review meeting and reestimate 
- Leave this as-is, do nothing

If anyone has a suggestion for a more straight forward implementation please let me know

**Comment by AleksueiR** [comment]
We can include this change into the structured legend refactoring as it's a large modification anyway. Just need to make sure we implement delayed loading of layer records in the new design.

**Comment by AleksueiR** [comment]
Why was this closed?

**Comment by milesap** [comment]
Part of larger v2.0 refactor release, moving milestone
