### ISSUE TITLE
chore(build): switch to latest version of JSHint (2.9.0 right now) and jscs

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#62]
Update dependency;
make sure there is no conflicts between old and new rule sets;
fix any style errors;

**Comment by spencerwahl** [comment]
As far as I can tell we only depend on gulp-jshint, which currently uses jshint version 2.7

**Comment by AleksueiR** [comment]
New jshint has better es6 support;
also, what do you think about adding the following jscs rule: [`"requireEnhancedObjectLiterals": true`?](http://jscs.info/rule/requireEnhancedObjectLiterals)

**Comment by alyec** [comment]
Investigate eslint vs jshint as well.

**Comment by AleksueiR** [comment]
JShint and JSCS will be replaced by ESlint in 2.0.
