### ISSUE TITLE
The map for index-fgp-fr does not load

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#620]
Removing `rv-langs` lets the map load but we lose loading with french translations...
As a starting point the page works in `v0.14.0` even with `rv-langs='["fr-CA"]'`

**Comment by ChrisLatRNCan** [comment]
Basically putting just "fr-CA" instead of '["fr-CA"]' will let the French basemap load. But still, it's a bit weird. I keep investigate. I'll compare with the  '["en-CA", "fr-CA"]'.

**Comment by ChrisLatRNCan** [comment]
It seems that translateLoadingSuccess is not called at all in core.run.js (angular-translate stuff).

**Comment by ChrisLatRNCan** [comment]
So basically, getting the right language from configService.data key value and passing it to $translate.use() will do the job. In core.run, the runBlock function explicitely pick 'en-CA' (see TODO below). First tests seem to work. 

core.run extract:
        // TODO: write language detection routine
        $translate.use('en-CA');

**Comment by spencerwahl** [comment]
The problem seems to revolve around the code snippet you found. On the french page the language only gets set to `'fr-CA'` once the initial config loads... however, this causes `configService.getCurrent()` to fail as there is no config object tied to any other language. The default (creating objects for both languages) and only using English worked because of that line in core.run.

Moving `$translate.use(langs[0])` outside of the promise callback (in configService) seems to fix the problem. But this might still be subject to a race condition. I agree this is heavily linked to #16 as I think the best solution would be proper language detection in core.run.

**Comment by ChrisLatRNCan** [comment]
So I'll keep working on that. The way I'm dealing with it right now in runBlock (core.run) is:
1- Looking what's inside the configService.data keys list;
2- Validating keys name;
3- If there'no recognizable key just load en-CA (maybe call setLanguage too)

**Comment by ChrisLatRNCan** [comment]
Previous post is more like a plaster than a real solution.
Still have problems with configService. Not sure how the getcurrent can be called from inside the init...promise to return the service.data(...) object.

**Comment by ChrisLatRNCan** [comment]
It's working. For now, it's better to set a value for the language right away ($translate.use(lang[0])) and not wait for the promise to be executed. Also, no more $translate.use() in runBlock (core.run). In the case where rv-lang is not avalaible we can either set a default (what is actually done) or extract the language from the json filename (filename needs to be normalized). There's also the option to put a mandatory language parameter in the json config file. Still testing.

**Comment by AleksueiR** [comment]
We need to define a proper language detection sequence (one I posted the other day is outdated) and fallbacks in case something (like a config file) is missing.

**Comment by ChrisLatRNCan** [comment]
It's part of the tasks I'm listing in #16
