### ISSUE TITLE
feat(ui): display a notification when a layer cannot be displayed in the current basemap

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#626]
As was found in #491, some (tile?) layers might not be shown in certain basemap projections. We need a way to indicate this in the legend.

**Comment by alyec** [comment]
This will apply to any layers with server side rendering: the server must know about those projections in order to generate imagery.  I believe WMS, tile, image and dynamic layers will all be affected.

**Comment by AleksueiR** [comment]
## Notes from UX review:
 - `layerRecord` needs a new state (see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/606) (and a template for `legendEntry`)
 - this template will not have a reload control
 - this template will not have seetings control
 - this template will have a remove layer control
 - _[proposed]_: this template will have a control to switch app to layer's target projection
 - `legendEntry` symbology is displayed as in a default template
 - this template should have some other visual indication that it doesn't funciton and/or flag [needs mockup]

**Comment by mweech** [comment]
will be implemented under #1186

**Comment by milesap** [comment]
Shelved until refactoring is stable on v2.0

**Comment by milesap** [comment]
@james-rae likely a check of some sort will need to be put into geoApi during the refactor which I'll use on the front-end

**Comment by AleksueiR** [comment]
This tile layer can be used for testing:
```json
{
        "id": "Oilsands basemap",
        "name": "oilsandsbasemap",
        "layerType": "esriTile",
        "url": "http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer/"
      },
```

**Comment by AleksueiR** [comment]
![](https://i.imgur.com/kCoJkPK.png)
