### ISSUE TITLE
Point Information Panel Shows Results when No Info is Available

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#643]
URL: http://fgpv.cloudapp.net/demo/develop/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,FeatureServer

If you click in an area with no results, the Railways WMS layer and the Barley raster group layer incorrectly indicates a result for the layer at this point, however the result is empty (the service is likely providing a response, however to indicate there is no data at this point).  

![pointinformation_noresult](https://cloud.githubusercontent.com/assets/7583387/15429150/88730734-1e6d-11e6-9750-b95142a4d3f2.PNG)

**Comment by jolevesq** [comment]
@mweech Should we put a message when all layers have query disable to indicate to the user why he see nothing. Do I add this in this issue?

**Comment by mweech** [comment]
The panel should indeed report "no results" as the other layers do, as it appears to be iterating over an empty set of results.
in this case the mini layer selector should not specify a count of 1 and instead appear to return no results at all.

**Comment by AleksueiR** [comment]
@jolevesq, if all layers have the `query` option disabled, I think the identify panel should not open at all as there can't possibly be any results.

**Comment by jolevesq** [comment]
@AleksueiR it is not the way it behaves now. The panel open with empty content. I can make the panel not opening when empty but do you think the user will understand it is because no layers have query enable?

**Comment by jolevesq** [comment]
@AleksueiR I made it so the details panel do not open if all layer are not visible or not queryable.

**Comment by AleksueiR** [comment]
Thanks. Are you planning to PR it this week?

**Comment by jolevesq** [comment]
Yes, I think I will push it tomorrow at the same time as #645 and #420

**Comment by ChrisLatRNCan** [comment]
The error is back...

**Comment by ChrisLatRNCan** [comment]
#1403 may have broken the fix. Investigation to come.

**Comment by ChrisLatRNCan** [comment]
See #1411
