### ISSUE TITLE
Browser Compatibility -Map does not load in Safari

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#648]
Tried loading the viewer Index.one and index-wet site.  However, it loads only options for Legend and Menu on the left handside. Map pages are blank.

Tested on build :http://fgpv.cloudapp.net/demo/v0.15.0-1/ 

Safari version :5.1.7 (7534.57.2)

![image](https://cloud.githubusercontent.com/assets/18539315/15438314/94be78f8-1e99-11e6-9653-b3355a9a6964.png)

**Comment by mweech** [comment]
Safari for PC is below the version threshold for support.
