### ISSUE TITLE
Geo Module Refactoring

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#650]
# Refactoring of geo module's core services

Our terminology at the moment is all over the place.  Part of the refactoring should involve naming things better.  `LegendItem`, `LegendEntry`, `LegendGroup`, `LegendPlaceHolder` will all be classes which fit into the legend.  `LegendItem` will be at the root of this hierarchy with the remaining classes.  `Layer`s are strictly map objects, `LayerRecord`s contain the layer map object + additional state.
## Legend Entry Service

This service is mostly a container for an object hierarchy.  This can be converted to ES6 classes along with some refactoring as we add ES6 properties and inheritance.
### LegendItem

A base class of the legend subclassed into single "entries" and "groups" (contains all the UI related state for the display of layers)
- options { opacity, visiblity, ... }
- flags { outOfScale, userAdded, layerType, ... }
- use ES6 props for options and flags
- template enum[ entry, group, placeholder ]
  - abstract, only set by child classes
  - should drive the clickAction via the associated directive
- getLayerRecord: null if no binding (e.g. structured legend)
- name
- legendId (formerly id -- want to keep it clear that it is split)
- sortingGroupType enum[feature,raster]
- getSortGroupIndex: convert the type enum to an int for CSS reference
- remove: governed by options
- sortable? add this if needed
### LegendPlaceHolder(LegendItem)

A placeholder's main purpose is to keep a reference while the layer is loading
- all state should be derived from the bound layerRecord (e.g. error, loading ...)
- should never exist in an unbound state
- constructor should take a callback to generate the appropriate legendItem once the layer has finished loading
  - callback format: () => return legendItem [entry,group]
  - layerRecord must be in a loaded state
### LegendEntry(LegendItem)

A single line legend UI element
- symbology {}
### LegendGroup(LegendItem)

A collapsible group of LegendItems (Groups or Single Entries)
- add, remove (operates on all legendItem instances)
- getItembyLegendId
- walkItems
- expanded (ES6 prop)
- items (public read, add/remove write)
### LegendEntryDynamic(LegendEntry)
- parent
- root
### LegendGroupDynamic(LegendGroup)
- parent
- root
- _subLayers
- both parent and root can be null if it is the root element
## Legend Service

Binds layerRecords and legendItems together.  Currently only `auto legend` is implemented, these could become classes or just separate function sets within the same service.  This should probably be revisited when work starts on structured legends.
- auto legend works by taking a layerRecord and generating a legendItem
  - addLayer(layerRecord, index - position in legend) => legendPlaceHolder (for binding the callback)
  - getLayerIndexAbove(mapObj): for layer positioning in index
  - moveLayer(mapObj, id, pos): sync legend state to map state
- structured legend works by magic
## Layer Registry

Layer registry tracks all layers created by the system.
### LayerRecord
- constructor should take a map reference
- state
- metadata (should be cached after first retrieval)
- isOffScale: RO prop
- maxScale, minScale: RO prop
- updateScaleState: to be consumed by zoom event listeners in registry
- removeLayer: called from legendEntry
### FeatureRecord (LayerRecord)
- featureCount: int
### DynamicRecord (LayerRecord)
- featureCount: { subLayerId => count }  subLayerId == featureIdx ???

**Comment by jolevesq** [comment]
@alyec make sense and agree with this.

I have a concern with an aspect of what I see in the legend and i don't know if it should be part of this refactoring discussion. Currently, inside the viewer itself we use object pass by the geoApi like the layers in the sample below.

```
// apply opacity to the whole layer
this._layerRef.setOpacity(this.options.opacity.value);
```

Should all those functions be manage by the geoApi? To set the opacity, we call geoApi with the layer id and the opacity value. Doing this inside the viewer may have an impact on it if we change/update the geoApi or if ESRI modify the layer object/properties. It breaks a little bit the purpose of the geoApi (ability to change the back with minimal effect on the viewer).

**Comment by alyec** [comment]
Based on the way `LayerRecord` and the rest of the hierarchy is shaping up we may be able to move all of it into geoApi.  It would be fairly easy to have the class proxy calls like setOpacity to the ESRI layer it contains.

I think this change would be too jarring for the beta release but it might make sense to look at after that.  Legend would stay as is, since it governs the UI's layer hierarchy and controls but it could call those proxy functions on it's matched `LayerRecord` which would remove the need for legend to keep `_layerRef` at all.

**Comment by mweech** [comment]
this is the kind of activity we should address post v1.0.

**Comment by mweech** [comment]
completed under milestone v2.0 scope.
