### ISSUE TITLE
Metadata does not display on the demo page when viewed on an outside network

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#652]
In the demo config, `aafc_agri_environmental_indicators` and `ecogeo` layers retrieve metadata from `http://intranet.ecdmp-stage.cmc.ec.gc.ca/geonetwork/srv/eng/csw?` which cannot be accessed from outside the firewall.
http://fgpv.cloudapp.net/demo/develop/index-one.html
![](https://i.imgur.com/1UZwmCB.png)

**Comment by mweech** [comment]
something is tying the metadata to an internal catalogue CSW.  however, i don't know if thats derived from the rcs registration or a setting in the viewer config.

**Comment by mweech** [comment]
there is not external data catalogue that is capable of serving metadata requests from our cloud server
