### ISSUE TITLE
User should be able to hide the Overview Map

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#656]
The Overview map provides helpful context to the user but takes a lot of screen real estate in particular on smaller devices.  The Overview map should be able to be hidden by the user or hidden by an option in the config.

**Comment by AleksueiR** [comment]
Partial duplicate: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/287

**Comment by jolevesq** [comment]
@mweech This has been solve by #595. I added the missing image for the open/close overview map.

**Comment by mweech** [comment]
just found it in the page! was surprised.. 

questions to determine if i should close this or leave it in the backlog as additional r3 improvements:
- can you disable the overview map in the config? 
- @AleksueiR what do u think about having a minimum resolution to hide the overview map by default?

**Comment by AleksueiR** [comment]
@mweech it's already logged: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/287

I would like to change the ugly "hide/show" icon for the overview map to something better, and it's also not keyboard accessible, so it definitely needs tweaks.
