### ISSUE TITLE
Identify might not run on valid targets in dynamic layers

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#664]
Identify will not run on dynamic layers whose `visibleAtMapScale` flag is true. This, however, does not apply to all its children which can exclude valid identify targets. Instead of checking if the layer object itself in scale, need to check if any of its children are in scale.

See discussion here: https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgpBkv0W4OZq9yygST

**Comment by AleksueiR** [comment]
> Does the visibleAtMapScale value indicate that all child layers are out of scale? If not, we are dropping valid identify targets here.
@aleksueir

> it does not. may want to utilize the stuff I added for the scale flags. see the latest commits on this branch. Easist approach would be to grab the flags.scale.visible from the legend, though might not be best architecture to reference the legend from the identify service. Alternate approach is to re-calculate the scales using function makeScaleSet in layer-registry
@james-rae

**Comment by james-rae** [comment]
Bit of clarification -- identify __would__ run on dynamic layers with `visibleAtMapScale === true` .  We were never in the situation where sublayers were being missed.  It was actually the opposite -- offscale sublayers would show up in the identify queries.
