### ISSUE TITLE
"Esc" does not close settings panel on all 3 browsers

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#665]
Tested on build :http://fgpv.cloudapp.net/demo/v0.15.0-1/index-one.html

This is reported based on tests performed for the below  issue

eat(ui): close panel on escape #572

Clicking on "Esc" did not close the "Settings" Panel. Could view this issue in all three browsers - IE11, Chrome (50.0.2661.102 m)  and Firefox (46.0). Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/15587095/a3540dae-2355-11e6-928c-c039fe14817c.png)

**Comment by milesap** [comment]
Having issues with IE 11 on my system, can't verify functionality for this issue. Will reassign if my IE issue is resolved soon.

**Comment by milesap** [comment]
PR #943 addresses this issue
