### ISSUE TITLE
Functionality for restoring a removed layer "Undo"

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#667]
Once the "remove" layer option is selected, there is a message which appears confirming the action with an "Undo" option to restore it. This option disappears too soon. Is this working as designed?

**Comment by AleksueiR** [comment]
The default delay is 3 seconds. What would you consider an adequate time for the "undo" option?

**Comment by mweech** [comment]
lets up it to 5s and see how that plays.. several ppl (myself included) have had the same experience that it disappeared to fast.

**Comment by mweech** [comment]
outdated
