### ISSUE TITLE
Add `query-off` flag to legend entries

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#668]
Follow up on #409:

There is no visible indication on legend items that the `query` option is turned off right now.
We discussed it and think a good solution would be to display a `query-off` flag on the legend entry when it's turned off. Something like this:
![2016-05-24 14_32_58-adobe photoshop cs3](https://cloud.githubusercontent.com/assets/2285779/15515473/702bf36e-21bc-11e6-9bcf-058743537ecb.png)
This way it's easy to tell which layer or sublayer will not appear in the identify results. This will be a separate task.

Notes:
- the flag should be visible __only__ when the query is turned off for this particular legend entry
- the flag needs a meaningful tooltip (suggestions are welcome) because phrases like `query is disabled` or `identify is disabled` can be meaningless to the user

**Comment by james-rae** [comment]
bad suggestions in user-speak

`layer is not selectable`
`layer will be excluded from map click results`
