### ISSUE TITLE
Settings Menu load behind the map after switching to Full Screen Mode from a WET page

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#671]
Tested on http://fgpv.cloudapp.net/demo/v0.15.0-1/index-wet.html

**Steps to Reproduce**

-

1.  Load index-wet (v0.15.0-1) build
2. Select "menu" and navigate to Full Screen
3. Select Legend
4. Navigate to a Layer to load the data table
5. Select the icon for options (on the top right corner of the datagrid)
6. Nothing loads

Options are actually loaded in the default screen (turn off the Full Screen mode).

This issue is seen in all 3 browsers

![image](https://cloud.githubusercontent.com/assets/18539315/15608773/fd115812-23e9-11e6-8c51-3b34c7d144a9.png)

![image](https://cloud.githubusercontent.com/assets/18539315/15608913/c9f4b720-23ea-11e6-9625-f70511795c14.png)

**Comment by mweech** [comment]
this bug occurs for all menus when moving to fullscreen following loading the index-fgp-en.html page.

**Comment by AleksueiR** [comment]
Simplest solution involves lowering app's z-index in the full-screen mode.

Angular Material uses z-index of 100 for the drop-menu, setting app's z-index below that will allow for the menu to show up while still blocking the host page. There might be a problem if the host page uses z-indexes larger than 50 or 100, in which case full-screen would not work. 

A more complete solution would be to override $z-index- variables defined in Angular Material with higher values and up z-index here as well. There seems to be some of the z-index- in Angular Material which are not derived from variables (in version 1.0.5); This should be revisited after upgrading Angular Material or in case additional bug reports (host page having higher z-index for example).
