### ISSUE TITLE
Bounding box is visible when the layer is hidden

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#675]
The bounding box stays visible when the layer is hidden.

![bb_visibility](https://cloud.githubusercontent.com/assets/2285779/15610882/a0b9e38e-23f5-11e6-963d-f1d8df5db847.gif)

Is this the desired behaviour or should it the bb be hidden as well?

**Comment by ChrisLatRNCan** [comment]
I don't think we should hide the BBox. It's a relevant information about extent of the data (convex/concave hull would be even better). However in a multilayers scenario we don't know to which layer the BBox is related. Maybe the BBox option could be carry one level UP (eg. aside visibility icone).

**Comment by AleksueiR** [comment]
Suggestions from UX review:
 - turning `visibility` __off__ turns `bounding box` __off__
 - turning `visibility` __on__ does not affect `bounding box`
 - turning `bounding box` __on__ does not affect `visibility`
 - turning `bounding box` __off__ does not affect `visibility`

This way a bounding box can be explicitly turned on for a hidden layer without affection layer's visibility; it also will be hidden when they layer itself is hidden.

Additional suggestion is to add a `bounding box` flag to the legend entry, similar to other flags. This one should only be display when the `bounding box` is visible - this will make it easier for the user to tell which layer the bounding box relates to.

**Comment by milesap** [comment]
FIXME: If bbox is on and settings panel is closed, hiding layer does not hide bbox
