### ISSUE TITLE
Implement Highlighting of Map Features

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#677]
Implement functionality that would allow for a map feature to be highlighted on the map.  This would function by greying out the rest of the map with a semi-translucent graphic layer.  The highlighted feature would appear as the only prominent element on the map.  

For layers that are not feature based, the highlighting would only be applied while browsing through Identify results and could be indicated by providing a circular "spotlight" around where the identify action occured.

- [x] Add highlight graphic layer to map at startup.  Ensure it does not break the layer repositioning logic.
- [x] Method to add feature to highlight layer
- [x] Method to add marker (for click location) to highlight layer
- [x] Steal RAMP logic to dim the rest of the map when highlight is active
- [x] Trigger highlight on grid detail launch
- [x] Trigger highlight on grid zoom
- [x] Add marker on identify click event
- [x] Remove highlight and marker on close cases (see below)
- [x] Utilize server geometry fetch for features in dynamic layers
- [x] Handle reprojection of dynamic geometry

**Comment by james-rae** [comment]
See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/424 for design history

**Comment by james-rae** [comment]
With grid zoom, the detail panel does not open.  This puts us in a potentially funny state where you can only get rid of the highlight by opening then closing the detail panel.

Bad ideas:

* don't highlight on zoom
* highlight triggered by zoom is on a timer, unhighlights after X seconds
* add a kill-highlight control to our app

**Comment by AleksueiR** [comment]
More ideas:
- highlight set on zoom from the grid can be removed when ...
   - ... the grid is closed
   - ... the user pans the map
   - ... the user changes zoom level
   - ... a different point is zoomed to
   - ... the user clicks on the map (should not trigger identify while the highlight is active)

**Comment by mweech** [comment]
highlighting ends on:
- different point is selected
- grid is closed
- point information panel is closed
- any interaction with the map (pan/zoom/click)

**Comment by mweech** [comment]
This functionality will be leveraged in solution to #557.

**Comment by james-rae** [comment]
Bumping estimate: the need to project dynamic layer geometry was not forseen in initial estimate.  Integration of images between legend, feature displays (grid/identify), and hilights was also more complicated than expected.

**Comment by james-rae** [comment]
Regarding the hilight trigger from the feature details pane.  We had [originally agreed](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/424#issuecomment-222209499) to put a button beside the title of each identified feature.  Clicking it would trigger a hilight.  

During the last UI Design meeting, there was [more ideas proposed](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/424#issuecomment-223569547) around how the panel would trigger hilights, which may or may not invalidate the button approach.  As well, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/689 would factor in to button-stuff as the icon would be beside the hilight button.  

So my question is, should I slop in a basic, functioning button, or submit the hilighting codebase with only the data grid triggering hilights for the time being?  In second case, the detail hilight would be added once the above design choices get flushed out (the hilight trigger should just be a single call).

**Comment by AleksueiR** [comment]
I'm for PRing without the button.
