### ISSUE TITLE
Close icon on "help summary" takes multiple clicks to close

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#678]
Please investigate  Tested on :http://fgpv.cloudapp.net/demo/v0.15.0-1/index-wet.html

**Comment by spencerwahl** [comment]
On IE:
After opening help and clicking on the close button a scroll bar will appear, shifting the close button and keeping the panel open. Clicking the shifted button will close the panel. Best guess is the ripple animation overflows the panel.

Didn't find any problems with Firefox or Chrome.

**Comment by AleksueiR** [comment]
This also applies to popup details and metadata panels.
