### ISSUE TITLE
Use symbol in details display

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#689]
We're currently hiding the 'rvSymbol' data in the details (doesn't make sense as a row in the display). However, it is possible for us to use the data to display the icon in a meaningful spot.

Symbol data generation should be moved (probably around attribute loading).

More info will be added after UI meeting

**Comment by cynngah** [comment]
Refactoring should take into account #635 dynamic layer symbology

**Comment by AleksueiR** [comment]
Position the symbology icon to the right of the feature name, so it's top edge is on the same level as the top edge of the feature name text (image below doesn't reflect that).

Approximate mockup:
![](https://i.imgur.com/2pANuGE.png)

**Comment by AleksueiR** [comment]
Partially completed: correct symbol is not shown at the moment (the first symbol from layer symbology is used instead). PRed to James' highlighting branch.

**Comment by AleksueiR** [comment]
See #793 PR.
