### ISSUE TITLE
bug(ui) details panel does not select the first item on load.

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#693]
When a user click on the map to get details, even if there is data it will show nothing found because  data is empty when the watch occur. It use to work in 0.14 something happen in the mean time.

```
$scope.$watch('self.display.data', newValue => {
            // if multiple points added to the details panel ...
            if (newValue && newValue.length > 0) {
                // pick first point to be selected initially
                selectItem(newValue[self.display.selectedIndex], self.display.selectedIndex);
            } else {
                selectItem(null);
            }
        });
```

<img width="405" alt="screen shot 2016-05-31 at 12 37 25 pm" src="https://cloud.githubusercontent.com/assets/3472990/15683159/f493d46a-272e-11e6-9254-d4ae2c10e047.png">

**Comment by jolevesq** [comment]
If I put a break point inside the return of identifyPromise it works.

**Comment by AleksueiR** [comment]
I think I found the culprit - will post later if this is confirmed.

**Comment by AleksueiR** [comment]
See this [line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/details/details-data.directive.js#L31). A `watch` is set on the `data` object passed to the directive. Initially, the object is an empty array which is later populated by identify results as they are returned. The default watch` is not triggered by shallow changes (adding, removing, etc) to the array. That is why the first item which is selected __before__ data is available, is empty.

To fix this, change `watch` to `[watchCollection](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watchCollection)`. Alternatively, it's possible to use a [`deep watch`](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch) (see `objectEquality` option), but it's less efficient.

**Comment by jolevesq** [comment]
@AleksueiR it works only the first time user click on map. The second time it won't. Even if we close the panel. i will investigate.
