### ISSUE TITLE
Overview Map does not hide consistently

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#694]
Tested on :http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html

Tested Item : User should be able to hide the Overview Map #656

Overview map does not seem to hide everytime a user wants to hide. There is another overview map displayed beneath the map which is hidden. This behaviour is usually seen when basemaps are Mercator. Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/15687951/9c542040-2745-11e6-9cd7-c299fa39d9ce.png)

**Comment by jolevesq** [comment]
Same thing happen when we switch from English to French. Seems the overview map is not destroy before recreating the map.
