### ISSUE TITLE
Data panel and basemap panels overlap

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#698]
Tested on : v0.16.0

Linked to #139 - bug(ui): basemap selector not closing properly when closed by opening filters panel
                                #638 - Bug/basemapclosebug

**Steps:**

1. Load Index/Wet Map
2. Click on Legend to load all layers
3. Select a layer to open data grid panel
4. While the panel is open, select the basemap selector to load basemaps
5. Both panels are overlapping . 

Please confirm the behaviour.

![image](https://cloud.githubusercontent.com/assets/18539315/15713565/e5386060-27e4-11e6-80ab-3954c5cde001.png)

**Comment by mweech** [comment]
opening the basemap selector should auto close the datagrid.
