### ISSUE TITLE
"Hide layer" not working after switching basemap

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#700]
Tested on build: http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html with Chrome & Firefox
Clicking on "Hide layer" button cannot hide map points in this scenario.
- Click Legend icon to display all layers
- Click Basemap button to open basemap pane
- Select World Imagery Mercater Map
- Click "Hide layer" icon for Joint Canada-Alberta layer, all map points for this layer not hiding, see below screenshot
![image](https://cloud.githubusercontent.com/assets/18723160/15724414/edf5a354-2814-11e6-81e1-9e2d7d6d7133.png)

**Comment by mweech** [comment]
After switching to Mercator projection (index-fgp-en.html or index-one.html) the show/hide layer functionality does not work. This remains non-functional after returning to the LLC projection.

**Comment by mweech** [comment]
delaying actioning of this bug until stateful change from mercator to lambert is completed.  may resolve the issue.

**Comment by mweech** [comment]
can no longer reproduce after implementation of stateful basemap change.
