### ISSUE TITLE
EsriRequest CORS Detection

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#702]
The ESRI request library seems to favour the proxy over CORS detection even with alwaysUseProxy set to false.  Needs investigation to see if there's a setting missing or if the library itself should be replaced.  See https://developers.arcgis.com/javascript/3/jshelp/inside_defaults.html for config options.

**Comment by mweech** [comment]
This is an action item for our team to address post v1.0

**Comment by AleksueiR** [comment]
__Update:__
Submitting a print job when exporting the map often fails since esri calls the print service through the proxy. If the print task is submitted the second time, usually, the call is made without the proxy.

**Comment by james-rae** [comment]
Hack workaround: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2833
