### ISSUE TITLE
All Map Points are not visible when basemaps are changed

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#703]
Tested on: http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html

For some reason, all map points are not carried over when basemaps are switched even though the visibility icon is enabled.

Steps to reproduce
Load the FGP site http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html
Make sure visibility icon is switched on for all layers
Switch the basemap to Mercator World Imagery
Only points for Joint Canada-Alberta is seen on the map
Please investigate

**Comment by mweech** [comment]
index-one.html contains a basemap layer that is obscuring other data points below it after switching projections.  this is compounded by a bug #708 where layer show/hide functionality is broken after switching map projections.
