### ISSUE TITLE
Unable to load the selected basemaps

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#704]
Tested on: http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html with Firefox & Chrome
When switching basemap, the selected basemap only flashed for less than 1 second and then the basemap was still the defaulted one
- Load http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html 
- Click Basemap icon to open Basemap pane
- Select basemap other than the defaulted map, for example, World Imagery or World Base Map - Elevation, etc.
- The selected basemap (in screenshot, it is Elevation) is unable to load, still showing the defaulted basemap
![image](https://cloud.githubusercontent.com/assets/18723160/15754100/8e07e3de-28c4-11e6-8e83-2d787b502f31.png)

**Comment by mweech** [comment]
This is not a bug.  This is related to the Basemap LLC layer (a basemap layer) rendering over top of the mercator basemap.
