### ISSUE TITLE
Bounding box for Land Pub layer not displayed

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#706]
Tested on build: http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html with Chrome & Firefox
Bounding box is not shown even it is enabled.
- Load v0.16.0/index-one and click Legend icon to display all layers
- Open Settings for Land Pub Standard Zone Details layer
- Enable the Bounding Box within the Settings panel (screenshot below)
![image](https://cloud.githubusercontent.com/assets/18723160/15757461/ae57f066-28d3-11e6-9662-27d594e362ff.png)

**Comment by alyec** [comment]
This is related to the layer using a custom projection since the bounding box code uses client side reprojection.
