### ISSUE TITLE
bug(core): current demo doesn't load in IE10

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#71]
![2015-11-05 15_22_59-title - f12](https://cloud.githubusercontent.com/assets/2285779/10980636/2d92207a-83d1-11e5-95e1-3fe792778b52.png)

**Comment by spencerwahl** [comment]
@alyec After solving the above error another one is thrown saying 'Promise is undefined'. 
@AleksueiR said it might be coming from geoApi, is this the case?

**Comment by AleksueiR** [comment]
To clarify - `Array.from` is not supported by IE10/11.

**Comment by alyec** [comment]
Yeah, no promise support in IE: http://caniuse.com/#feat=promises need to polyfill

**Comment by AleksueiR** [comment]
Can we temporary polyfill this in until Aly is back? I want to see if the viewer works in IE at all.

**Comment by spencerwahl** [comment]
Update on ie10 nonsense:

The browser complains about things in the following order:
* Array.from
* Promise
* Symbol and module (this seems to be coming from proj4?)

There may be more problems after this is fixed, but the app partially loads after fixing Array.from and Promise.

Polyfills worked fine up until the module problem; if I understood @AleksueiR properly module (non-es6) is just not a thing in IE.

Here are the polyfills I tried using:

	https://www.npmjs.com/package/array.from

	https://github.com/jakearchibald/es6-promise

	https://github.com/paulmillr/es6-shim/

**Comment by AleksueiR** [comment]
> ... here's some good news: http://www.theverge.com/2016/1/6/10722426/internet-explorer-8-9-10-dying
Given this news, I think we can safely build R2's viewer with IE11+ in mind, and blame the IT departments for their insecure practice of running unsupported browsers.  
-- Dan Bowerman [January 6, 2016 8:12 AM](https://gitter.im/RAMP-PCAR/TeamRoom?at=568d12cd84fa46770b24dd95)

**Comment by AleksueiR** [comment]
All hail the King Muffin!
