### ISSUE TITLE
Add graphic to panels when requests fail

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#710]
When requests to retrieve metadata or attributes or something else fail, in addition to showing a error toast notification, show a "sad panda" image:
![](https://i.imgur.com/lRglKLC.png)
Thank you @james-rae for this suggestion!
### Datatable failed:

![](https://i.imgur.com/TIZ2VJy.png)
### Metadata failed:

![](https://i.imgur.com/EPVOeRJ.png)

**Comment by mweech** [comment]
Graphic would need to be configurable given some sights will be international partnerships (i.e. NACEI).
