### ISSUE TITLE
"Zoom To Feature" for any map points in a hidden layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#712]
Tested on http://fgpv.cloudapp.net/demo/v0.16.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,FeatureServer,ZoomScale
Consider the scenario when certain layer is hidden, what should be the expected behavior when using "Zoom to Feature" for map points?
1. Hide one layer - all map point for this layer hidden
2. open data table for this layer
3. "Zoom to feature" for any point of the layer
The map still zoomed to somewhere, but because all feature point not shown, not sure if the map zoom to the right point or not. Below screenshot is an example when zooming to Obj ID 49
![image](https://cloud.githubusercontent.com/assets/18723160/15790949/8711d5b0-29a2-11e6-89bb-c4391f602512.png)

**Comment by AleksueiR** [comment]
The current suggestion is to disable the zoom controls when the layer is hidden. This will require to track layer's state to re-enable controls when the layer is made visible again.

**Comment by jolevesq** [comment]
Zoom to feature button must be disable in the details panel as well

**Comment by jolevesq** [comment]
@AleksueiR if the user change the visibility when the datatable is open, we want the button to enable itself? To disable it before the datatable open is quite easy, to change the state when it is open will need more work.
