### ISSUE TITLE
Metadata Panel is blank in IE11 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#714]
Metadata Panel is blank in IE11. This loads in other browsers like Firefox and Chrome

Metadata was tested for Eco Geo layers and AAFC Agri Environmental Indicators. Please investigate

**Comment by bkutty** [comment]
Please note that the pop up for metadata also has an issue with closing similar to the one reported in #678

**Comment by AleksueiR** [comment]
Duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/619.
