### ISSUE TITLE
Zoom to Layer Bounding Box

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#716]
Allow the user to zoom to the extent of the dataset (i.e. the bounding box).

**Comment by cynngah** [comment]
Feedback pls:

I think it would make sense to make it such that zooming to the layer's bounding box is only available when the bounding box is visible. Or else it's kind of like the user is zooming into a random area.

**Comment by jolevesq** [comment]
I think it can be use even if the bounding box is not visible. It will be helpful for dataset with very small extent. For those, even bounding box can be hard to see.

**Comment by mweech** [comment]
i agree with @jolevesq that this is a feature with value.  while we use the language zoom to "bounding box", we should label the functionality as "zoom to layer extent" as without the bounding box itself displayed, it would not necessarily be clear what it zoomed into.

**Comment by AleksueiR** [comment]
How would this work with wms and other image layers with huge bounding boxes ([temperature lyaer](http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/World/Temperature/ImageServer) has enormous bounding box)?

**Comment by AleksueiR** [comment]
Add this option to the extras menu (wording to be confirmed):
![](https://i.imgur.com/66bvCdH.png)

**Comment by AleksueiR** [comment]
Use "Zoom to layer boundary" label instead.
