### ISSUE TITLE
Details expand panel doesn't always show correct information

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#718]
It seems, in some cases, the details expand panel will not show hits for a currently selected layer or will show hits from a previously selected layer. See gif below:

![expand_panel_glitch](https://cloud.githubusercontent.com/assets/2285779/15858678/aad130a0-2c8f-11e6-8f05-4082e2825337.gif)

Haven't checked, but this might be happening with the metadata panel as well.

**Comment by jolevesq** [comment]
The modification to keep the selected layer in detail panel modify the way we handle details panel. Should have an effect on expand who was done in a previous PR.
