### ISSUE TITLE
Tooltip for "Menu" lingers on even after navigating away

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#733]
Tooltip for "menu" remains on the viewer even after a user has navigated away  or has already  loaded Full Screen mode. Same issue is seen when you exit the full screen.
Tested on http://fgpv.cloudapp.net/demo/v0.17.0-1/index-fgp

Browsers : Firefox and Chrome

![screenhunter_2222 jun 08 11 39](https://cloud.githubusercontent.com/assets/18539315/15900495/b67f92dc-2d6d-11e6-9230-24bcd3f69423.jpg)

![screenhunter_2224 jun 08 11 45](https://cloud.githubusercontent.com/assets/18539315/15900747/969b6bc0-2d6e-11e6-9731-22fac5124de3.jpg)

**Comment by AleksueiR** [comment]
This is likely an issue with Angular Material. Upgrading to the latest version might solve this.

**Comment by milesap** [comment]
Reviewed issue - this is expected behavior. Focus moves back to the menu icon when the menu side panel closes. Since it has focus its tooltip should be shown. Tested by mouse and tab key various ways and it seems to be working well.
