### ISSUE TITLE
Feature Information is blank for "Joint Canada-Alberta" Oil Sands Layer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#735]
Tested on : http://fgpv.cloudapp.net/demo/v0.17.0-1/index-fgp-en.html?
Browsers : Chrome and Firefox

Steps to Reproduce

Load FGP Index site
Select a map point from the Oil Sands Layer
Point Information Panel opens with information on the selected Feature
Select "Expand" icon in this panel
Pop up displaying Feature Information is blank
Could not see this issue for other layers

Placement of this pop up also needs to be on the center of the page

![screenhunter_2226 jun 08 12 06](https://cloud.githubusercontent.com/assets/18539315/15901975/a7341c8e-2d73-11e6-8af4-9bc56c65ac50.jpg)

**Comment by AleksueiR** [comment]
Duplicate #718.
