### ISSUE TITLE
"Spatial Density " Layer Point info displays "Undefined"

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#737]
Tested on http://fgpv.cloudapp.net/demo/v0.17.0-1/index-fgp-en.html?keys=Barley

_This layer seems to be breaking as it returns no results inspite of loading successfully. Please investigate_

![screenhunter_2228 jun 08 14 43](https://cloud.githubusercontent.com/assets/18539315/15906569/72eba910-2d87-11e6-92ad-e6846a3b11e7.jpg)

![screenhunter_2229 jun 08 14 48](https://cloud.githubusercontent.com/assets/18539315/15906727/200f829c-2d88-11e6-85a0-cab3c41f9ca3.jpg)

- [x] Prevent grid from opening on Raster sublayer
- [x] Change error message in feature count to instead indicate it is a Raster
- [x] Ensure the mouse doesn't change to a finger when over Raster sublayer
- [x] Handle raster layers in identify pipeline
- [x] Change geoApi attribute loader to not reject raster endpoints
- [x] Include layer type in attribute `layerData`

**Comment by mweech** [comment]
Should not be able to open the datagrid for this layer.

**Comment by james-rae** [comment]
Took slightly longer than estimated (maybe a 4); the asynchronous nature of the Raster Layer status added complexity, as well as the Angular mechanisms for building legend items and triggering / disabling clicks is rather complex for a noob
