### ISSUE TITLE
All map feature points went missing upon switching from Mercator map to Blank Map of Lambert gallery

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#738]
After jumping to Blank Map under Lambert Maps from any of Mercator Maps (World Imagery, Physical Map, Topographic Map, etc.), the map is fully blank without any map feature points shown.
![image](https://cloud.githubusercontent.com/assets/18723160/15906992/3bc938a6-2d89-11e6-8edd-f5014cbf210d.png)

**Comment by mweech** [comment]
delaying actioning of bugfix until viewer state gets maintained upon projection change.  may invalidate the bug.
