### ISSUE TITLE
Legend Info for Canadian Railway Network layer needs to be aligned in Firefox

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#745]
Tested on :http://fgpv.cloudapp.net/demo/v0.17.0-1/index-fgp-en.html

Browser - Firefox

This issue is seen only in Firefox (v 46.0)

Legend Info appearing for the Railways  layer on the Layer Panel is not  aligned properly . Please align the title of the Legend so as to not overlap the contents

![screenhunter_2236 jun 09 14 18](https://cloud.githubusercontent.com/assets/18539315/15941363/cbd542ae-2e4d-11e6-8bca-5a89dd6d775e.jpg)

**Comment by spencerwahl** [comment]
Not a WET collision, it happens on index-one as well

**Comment by mweech** [comment]
Relates to #760

**Comment by jolevesq** [comment]
@mweech do we solve this or just work on #760?
