### ISSUE TITLE
Please update "Help" to include/update text relevant to the current FGP Viewer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#746]
As seen on :http://fgpv.cloudapp.net/demo/v0.17.0-1/index-fgp-en.html

Linked to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/185
Please update "Help" section to include/update the following

- [x] Include "GeoLocation" feature explanation
- [x] Navigation Controls - Remove the text "the datagrid updates accordingly to what's viewable in the current extent." as the filter is not implemented at present
- [x] Update Legend Info to include dynamic and other layer types as seen in the build. 
- [x] Zoom Scale Dependent Layers- Please correct the description to exclude"and have an action available to zoom to the closest zoom level at which the layer will be visible"
- [x] Data Table Panel - Does not display the current map extent.
- [x] Accessibility - Please remove Zoom Slider reference

(edited for formatting)

**Comment by cynngah** [comment]
Zoom Scale Dependent Layers does have this function now, so I will be leaving this in the help section.
