### ISSUE TITLE
FeatureServer Layers break Identify

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#752]
Tested on build http://fgpv.cloudapp.net/demo/v0.17.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,FeatureServer 
with both Firefox and Chrome
Clicking on any map feature points is not responding. Sometimes after clicking many times the map just zoomed in, but still there is no map feature details displayed on the left panel as it supposed to be.
And it seems the map never finished loading - or the loading speed might be very slow.
Below is an example when zooming to a Mercury emission layer and clicking on the yellow map point.
![image](https://cloud.githubusercontent.com/assets/18723160/15966847/e289d35c-2ef2-11e6-8136-841816f5d400.png)

**Comment by james-rae** [comment]
Root cause traced to code processing the `FeatureServer`.

Original error occurs in function `assignDirectMaster`, line `this.slaves[masterId].add(item);`

For time being, error can be avoided by omitting the `FeatureServer` key from the URL

**Comment by james-rae** [comment]
Issue is with the `FeatureServer` entry in the RCS.  It is registered as a Dynamic Layer, which will not work in the viewer (Feature Servers cannot export a map image).  If the layer is added to the map as a feature layer, the identify works fine.

Added https://github.com/fgpv-vpgf/rcs/issues/51 to request an RCS error on registration in this situation
