### ISSUE TITLE
Behaviour when no config file is present

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#754]
@ChrisLatRNCan brought up a very good point that, right now, we require a config file for the viewer to load at all.

We should probably allow the viewer to start when there is no config attribute; choosing a default basemap, default starting language, only rcs and user added layers.

Questions:
- Is there a good case for not having a default state?
- What to do for default basemaps? Supply a list or just use the blank basemap
- Anything else we have to worry about a default for?

**Comment by alyec** [comment]
Having a default set of basemaps would be nice and probably more helpful than the blank basemap case.  But I don't think we need to handle this the same way we do for the default layers in JSON schema (i.e. I don't want to list out all the default basemaps in the schema).

**Comment by mweech** [comment]
yes i think we should definitely have a default state to fall back on.  imo, i think the default state should not involve the presence of an rcs.  although rcs is a prevelant tool for us now re: fgp, this is not the only intended deployment pattern for the viewer.

re: basemap i think we should default to the LCC transportaion map we use at the moment.

**Comment by ChrisLatRNCan** [comment]
I don't know if it's the configService that will handle the default state but some services rely on configService.getCurrent() to retrieve language information at initial load. With #757 language initialization has been isolated to avoid conflicts at load.

**Comment by james-rae** [comment]
Question came up to put the bare-bones default config in-code, or have it as a json file.  Some points to consider:

* Having it in a file lets us use the current file-read-parse logic
* Having it in a file means the defaults can be adjusted easier (e.g. it will likely have one basemap; can adjust the basemap)
* A file means having to add it to the ramp release bundle, and requires person to have deployed it in the correct location. In-code config is just part of the codebase.
* Longer term though: if we eventually deploy RAMP on a content provider, would putting the default there make sense? Would people not using the content provider get angry if the ramp library attempted to access it for a default config?

**Comment by james-rae** [comment]
No feedback given. Will go forward with in-memory solution. This feature is an edge case for a new user or very very fast mockups, so lets avoid complicating the deployment process.  If user needs to change map behaviors, they can always make a proper config.

**Comment by YaroRoodzit** [comment]
Tested with build v2.4.0-b2. The viewer is working correctly with the minimum loaded configuration.
