### ISSUE TITLE
The removed layers re-appeared after switching basemap between Lambert and Mercator

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#755]
Tested on http://fgpv.cloudapp.net/demo/v0.17.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley with Firefox & Chrome
When changing base map from Lambert gallery to Mercator gallery, or vice versa, the removed layers on previous base map displayed again on the new base map, even the layer is not shown under Legend any more. See below screenshot for Joint Canada-Alberta layer.
![image](https://cloud.githubusercontent.com/assets/18723160/15969317/89711b9e-2efd-11e6-890e-f6f288188e73.png)

**Comment by mweech** [comment]
state is not being captured.  when switching basemap projections it is taken as loading from scratch.  as the RCS key is still present on the browser URL, the layer will be loaded again. will leave open to reverify upon implementation of #715.

**Comment by mweech** [comment]
issue occurs due to the layer being in a "delayed remove" state where it is just hidden at first.  need to check for this state when legend is recreated under mercator.

**Comment by cynngah** [comment]
Can't reproduce anymore
