### ISSUE TITLE
User Added Layer Map points  are not visible when Projection is changed

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#756]
Tested on:http://fgpv.cloudapp.net/demo/v0.17.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley

Linked to :feat(ui): create add/import layer ui component #112 

File Used for tests: rc_cdr.csv; Canada.Json

Steps to Reproduce

Load FGP v0.17.0. Validate basemap is Lambert
Add a File based layer by selecting the +" sign near Legend Info
Upload a csv/Json file. Added layer points are displayed on the current projection
Change Projection to Mercator/World Imagery
Newly added layer points are no longer visible eventhough Layer options are visible  in the Legend Panel.

**Comment by mweech** [comment]
Changing the map from one projection to the other does not carry state forward at the moment.  Will leave open until #715 is implemented to verify the issue does not still exist.

**Comment by mweech** [comment]
layer is now missing as expected after changing projection.
