### ISSUE TITLE
Data Tables not displayed for all User Added Layers (incl. GeoJSON, CSV & Shapefile)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#758]
Tested on build http://fgpv.cloudapp.net/demo/v0.17.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley 
 with both Firefox and Chrome
All three kinds of data file (GeoJSON, CSV & Shapefile) can be added, but no data tables could be opened when clicking on the added layers. Meanwhile, there is a small square icon tool tip underneath layer name which says "ESRI Feature Layer (...counting features)".
Even map points for user added layers are displayed on the base map, clicking on any point has no response.

![image](https://cloud.githubusercontent.com/assets/18723160/15974435/60fc9292-2f16-11e6-86b1-84918225d875.png)

**Comment by AleksueiR** [comment]
It works as expected on the feature branch at the moment of the PR: http://fgpv.cloudapp.net/demo/users/AleksueiR/blurg/index-one.html

@alyec Aly, could have layer record refactoring broken it?

**Comment by alyec** [comment]
Yeah, I'm temporarily assigning myself just to have a quick look at the attribute promise trigger for File based FeatureRecords.
