### ISSUE TITLE
Print preview of data table includes "zoom to feature Details" and  is also incomplete

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#759]
Tested on :http://fgpv.cloudapp.net/demo/v0.17.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,ZoomScale,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley

Browser :Chrome and Firefox

_Please remove the "zoom to feature details" in Print Preview. Also notice that information was missing from the print preview. Only the first few columns were displayed. Please investigate_

![screenhunter_2242 jun 10 15 07](https://cloud.githubusercontent.com/assets/18539315/15975792/52babaae-2f1d-11e6-99b1-34e9ac04fdff.jpg)

**Comment by AleksueiR** [comment]
@bkutty, can you check this again. I can't reproduce this.

**Comment by bkutty** [comment]
No longer an issue
