### ISSUE TITLE
fix(ui): (English/French) language glitches inventory

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#764]
This is an inventory of related language glitches that need to be addressed. The scope of this issue is not about processes (eg. French translation doesn't load).
Here a list of what the inventory is targeting:

- Translation to be done or lack of text (eg. help, error messages,...). This could be either in English or French.

- Bad/deficient translation

- Bad wording/formulation. Could be either in English or French (eg. using a noun when we should use a verb on a button). Text clarification could enter in that category (eg. help, context info, ...).

- Terms normalization. Always use the same expression for the same concept.

Put a comment as a task list with what you have found (please put enough details).

**Comment by mweech** [comment]
text at bottom of datagrid indicating "showing X of Y" is still in english.

**Comment by ChrisLatRNCan** [comment]
No translation yet for side menu (hamburger menu). 
See app\layout\shell.directive.js

**Comment by cynngah** [comment]
Pulling these changes tomorrow from issue #746 , but still need French translations for these parts in the csv file:

Under help.legend.info:
- [] "Dynamic layers represent interactive data on the map that cannot be cached, but have to be fetched from the server each time the map is changed. They can be a collection of feature layers and can be viewed in the data table panel."
- [] "Image Service layers displays imagery and other types of raster data provided by an ArcGIS Server Image Service. They are not interactive and do not show in the data table panel."
- [] "Tile layers displays map content from an ArcGIS Server Map service that has been cached (tiled). A cached map service contains pre-generated map tiles. They are not interactive and do not show in the data table panel."


Under help.geolocation.info:
- [] "Click to zoom to the current geographical location of the user."

**Comment by ChrisLatRNCan** [comment]
DataTable initialization can be done via a plugin.
From here [https://datatables.net/plug-ins/i18n/]  :
> There are two methods by which you can include internalisation options in DataTables - loading the language file through an Ajax request (language.url), or at initialisation time using the language property.

So what should I implement ? (there's maybe a thrid way)

**Comment by alyec** [comment]
Using an inline property will be faster and is more robust.  Once it's working I can store the JSON files separately and inject them as part of the build process (this is what is happening with general translations in #804 )

**Comment by ChrisLatRNCan** [comment]
PR #816 to update translations.csv

**Comment by ChrisLatRNCan** [comment]
We'll have French toast in config.service.

**Comment by ChrisLatRNCan** [comment]
I did insomnia about PR #837 over the weekend. I missused $translate.instant by using the wrong function signature ($translate.instant(transId, lang) instead of $translate.instant(transId, interParam,interID,forcelang)). It doesn't brake anything but it doesn't improve the code either. My understanding is that angular-translate cannot pick a translationID in the translation table with a particular language without changing the overall language used status. So if the used lang is 'en' you cannot search for a 'fr' translationID without changing the used lang to 'fr' and, as a side effect, permit another module to load the wrong language profil.

**Comment by ChrisLatRNCan** [comment]
For DataTable translation we can find files to be injected (json) [here](https://github.com/DataTables/Plugins/tree/master/i18n)

**Comment by ChrisLatRNCan** [comment]
For side menu and basemap menu translation process has been put in place.
However index-wet.html through RV.getMap('rv-app-0').setLanguage won't translate them on language switch. Language switch through upper page link in index-fgp-en.html and/or index-fgp-fr.html will translate both menus.

**Comment by mweech** [comment]
@ChrisLatRNCan Not switching language through index-wet.html should be logged seperately as a bug.

**Comment by mweech** [comment]
merged: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/921
