### ISSUE TITLE
Turn datatable "details" and "zoom in/out" "buttons" into real buttons

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#766]
These buttons are right now just icons with a click listeners applied to them (they are also not keyboard accessible and their tooltips are inferior). 

![](https://i.imgur.com/GCYIgZr.png)

These buttons need to be turned into proper button directives. To avoid making hundreds of these directives for the datatable, I believe we can built one each and reuse them.

**Comment by milesap** [comment]
There is no clear way to integrate angular directives with datatables in an efficient manner (and without excessive hacks). I'll open this for discussion on possible solutions and we can revisit this at a later time.
