### ISSUE TITLE
Documentation for Viewer Release

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#767]
- [x] ~~need to test dgeni doc generation as it has not been tested in some time~~ remove dgeni as it is basically undocumented for our use case and convert to jsdoc
- fill in the API documentation with guidance, overviews and samples (can steal some from the wiki)
  - ~~take what is easy to steal from the wiki~~ (since we have slides from the workshop these can form a lot of the basis of the developer guide which would be outside the estimate for this task, see #839)
  - [x] open a discussion for which sections are missing / need improvement
  - [x] fix badly tagged docs in the repo
  - [x] pick a decent jsdoc template
- [x] publish API docs to github/azure

**Comment by alyec** [comment]
I've done some work towards fixing the build and automating doc deployment on github.  I'll hold onto this issue until I've been able to automate the deployment.

**Comment by mweech** [comment]
Original estimate should have been 13 due to need to switch away from dgeni.
