### ISSUE TITLE
Define and Build Library for Viewer Release

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#768]
- [x] figure out what we are building (as opposed to zipping up our whole repo) ideally include 1-2 minified JS files
- [x] inject XSLTs into the build
- [x] apply translations on an XSLT constant so both XSLTs do not need to be loaded
- [x] remove favicon from assetcopy
- ~~convert map-icon to SVG (find an appropriate SVG)~~ moving to a new task
- ~~apply prefix to iconsets~~
- [x] write a script to cache actively used SVG icons
- [x] load cached SVG icons using template cache
- [x] convert datatables images to data URLs
- [x] add datatables images to CSS
- [x] rename injector to bootstrap
- ~~add support in injector for arbitrarily named lib / css file to be loaded~~ moving to a new task
- [x] split build task to output separately to `build/examples` and `build/lib`
- [x] convert dist task to uglify `build/lib`
- [x] tar/zip should only use source from `build/lib`

**Comment by alyec** [comment]
## Proposal for cleaning up the build

### content/metadata
- XSL files to strings
- do lang translation on XSL strings
- put strings in constant file

### content/images
- favicon will not ship (this is a library)
- map-icon will have an SVG default but should be overriden by implementors
- overview has overview.png and will be replaced by nicer material icons
- iconsets
  - prefix all iconset usage in the form 'rvicon-alert:warning'
  - traverse our build and find all SVG graphics used
  - create small SVG files with only the icons used
  - load SVG files into template cache (gulp task)
  - svg.js library may be of use
- datatables
  - convert all pngs to base64 data URLs
  - override in CSS sheet (already exists)

### Misc build cleanup
- rename injector.js to bootstrap.js
- split build into
  - build/examples: `*.html`, `config.*.json`
  - build/lib: `bootstrap.js`, `core.js`, `main.css`

### Additional tasks if we can squeeze them in
- add gulp task to print file sizes as things get added to core.js
- check for CSS clean up in newer versions of angular material

**Comment by alyec** [comment]
Since no one has objected and informally people seem to be okay with the proposal I think that's what we're going to use.

**Comment by alyec** [comment]
Moving the following into a new task:
- convert map-icon to SVG (find an appropriate SVG)
- add support in injector for arbitrarily named lib / css file to be loaded
- add gulp task to print file sizes as things get added to core.js
- check for CSS clean up in newer versions of angular material
