### ISSUE TITLE
Define and Provide Working Examples with Release

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#769]
- [x] figure out which examples we want to include (we can use our test pages as a basis)
- [x] examples should cover functional pages as well as instructions about how the library is instantiated on the page
- [x] publish them on github or to azure

**Comment by mweech** [comment]
Minimum examples at this point would be:
- index-wet.html (working example for static config in a WET page)
- index-multiple.html (working example for multiple static configs)
- index-rcs.html (working example for RCS)
- index-fgp-en/fr.html (working example for FGP specifically)

**Comment by alyec** [comment]
Things we need to show and explain:
- set RCS URL via attribute
  - supply keys via API
  - supply keys via attribute
- set available languages via attribute
  - switching languages via API
- get bookmark via API
- restore bookmark via API
- loading with a minimal config
  - describe what a minimal config is
- loading as a single page app
- CSS guidance for the viewer prefixes / reserved sections
