### ISSUE TITLE
Improvement for User Added Layers Component

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#770]
- [x] improve error handling of component to avoid situations where layer fails or execution path is blocked without feedback to the user (at minimum indicate an error occurred even if its difficult to give the specifics of what went wrong)
  - This mostly works with one exception - if the prediction function cannot determine the service type upfront, we cannot validate user's selection later.
- [x] provide better feedback to the user when actions are occuring behind the scenes (i.e. trying to connect to a service, loading a file, etc).
- [x] add a color picker for layer symbol color
- [ ] ~~allow user to pick when a poorly named file is uploaded (i.e. json file without a .json extension)~~ see #868 
- [x] include smart defaults for file based layers (i.e. try to guess the lat/long)
- [x] include smart defaults for service based layers (i.e. mainly pick the first available field as the primary field)

**Comment by AleksueiR** [comment]
Having troubles finding a keyboard accessible colour picker library.

**Comment by AleksueiR** [comment]
There is a problem implementing "allow user to pick when a poorly named file is uploaded (i.e. json file without a .json extension)" - prediction code in geoApi needs to be refactored, separating processing files and services code. @mweech Can we move this into a separate task, maybe under geoApi repo.

**Comment by AleksueiR** [comment]
I could not find a keyboard accessible colour picker (well, to be fair, I found one that let's you tab through the sample colours, but doesn't allow selecting one), and [HTML5 browser colour picker](http://codepen.io/AleksueiR/pen/PzJwLE) conveniently doesn't work in IE (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color).

An accessible colour picker should let the user either pick from a number of pre-selected colour samples or select a colour from a colour wheel or manipulate rgb/hsl sliders. None that I found do that.

Most colour pickers let the user type hex (#ffffff) or rgb (rgb(146, 78, 146)) codes; some, colour names (orange, blue, teal, etc.). I would think these picker are deemed WCAG accessible but not very useful to a keyboard user.

[md-color-picker ](https://github.com/brianpkelley/md-color-picker) would be my top choice:
- uses angular material
- has lots of options
- knows more colour names (for keyboard users) than others: https://github.com/bgrins/TinyColor/blob/master/tinycolor.js#L805

Unfortunately, it also depends on Angular Material 1.0.5+; our AM dependency is pinned at 1.0.4. If we want to use `md-color-picker`, we need to update our dependencies first (this might be very simple or not so much - need to check if AM 1.0.5+ introduces any regression issues).

Some colour pickers examples: 
http://angularjs.jqueryrain.com/demo/color-picker/
http://www.uibox.in/tag/color-picker

**Comment by mweech** [comment]
i couldnt fully use md-color-picker from a keyboard on the demo, but maybe thats just the demo.

Minimum requirement for keyboard accessibility is to allow text input of a color code.  Not an ideal minimal and if we can do better i agree, lets go for it.  However, I can only assume we pinned at 1.0.4 for a reason, so I'm a bit concerned with the level of effort to move to 1.0.5+ especially at this point in time. 

We need to make a decision under the following context:
- solution needs to be implemented, PR'd and tested by the end of Jul 14th (there are some other issues competing for time as well)
- allow keyboard users to enter color values in an alternative fashion
- pick a solution that we would not just end up replacing soon after

**Comment by AleksueiR** [comment]
md-color-picker is not fully keyboard accessible (I couldn't find any, as I said), but you can type in colour codes and names.

I don't remember why we pinned AM at 1.0.4. Anyone?

**Comment by spencerwahl** [comment]
Can't enter colours in french using md-color-picker. We'd have to figure out a way to get the input and translate it before sending it to the colour picker.

**Comment by AleksueiR** [comment]
There is an extensive list of color names in English: https://www.wikiwand.com/en/List_of_colors:_A%E2%80%93F

Does anyone know where to find a list of color names in French?

**Comment by mweech** [comment]
color names are pretty safe to google translate IMO.

**Comment by mweech** [comment]
still about 4-5 pts of effort remaining in this task.

**Comment by james-rae** [comment]
[v0.13.0-23](https://github.com/fgpv-vpgf/geoApi/releases/tag/v0.13.0-23) adds a colour parameter to the file layer creation functions in geoApi https://github.com/fgpv-vpgf/geoApi/pull/133
