### ISSUE TITLE
Enhance "Zoom to details" in scale-dependent layers

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#777]
Right now, it will zoom the map to the level where layer is regardless of whether the current extent is inside the layer's bouding box or not. In a situation where the current extent is somewhere over BC and the layer in question is a city-level smattering of points over Toronto, "zoom to details" will take the user to the city-level in BC where there is no points, guaranteed.

##### Suggestions:
When user clicks "zoom to details" on a scale dependent layer:
- if the current extent is outside the layer's bounding box, zoom to a proper level and move extent to the center of the bounding box
- if the current extend is inside the layer's bounding box, simply zoom to a proper level

**Comment by cynngah** [comment]
Relates #625
