### ISSUE TITLE
Mercator Maps - User added layers (File & Service based) not shown up under Legend

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#788]
This issue happened when adding File based layers (GeoJSON, CSV, or Shapefile) and WMS service layers as well. The added map feature points displayed on the map, but all added layers are not shown up under Legend, thus there is no way to open data tables for added feature layers.

![image](https://cloud.githubusercontent.com/assets/18723160/16121751/77b12b88-33b2-11e6-91c3-50682f4cbd53.png)

**Comment by mweech** [comment]
cannot reproduce June 27th.
