### ISSUE TITLE
Zoom To Feature not responding for user added shapefile - rivers_north_america.zip

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#789]
After added shapefile: ne_10m_rivers_north_america.zip to the map and opened data table, Zoom To Feature button is not working. 
![image](https://cloud.githubusercontent.com/assets/18723160/16122436/188f10d6-33b5-11e6-8e9b-cd2d045cdfe8.png)

**Comment by IsabellaPan** [comment]
James has all the info for this issue, incl. the uploaded shapefile.

**Comment by james-rae** [comment]
Test file
[ne_10m_rivers_north_america.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/323502/ne_10m_rivers_north_america.zip)

**Comment by mweech** [comment]
verified.
