### ISSUE TITLE
Bounding Box for user added file based layers not working

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#791]
Bounding box is not shown even it is enabled under Settings. This happened for all user added file based layers.
![image](https://cloud.githubusercontent.com/assets/18723160/16130273/5973fc58-33d6-11e6-9a4b-e352d5e8d63f.png)

**Comment by james-rae** [comment]
Two ideas for fixing:
* Hide bounding box toggle on file based layers
* Use the [graphicsExtent](https://developers.arcgis.com/javascript/3/jsapi/esri.graphicsutils-amd.html#graphicsextent) function on the file layer's contents to derive the bounding box

**Comment by alyec** [comment]
I'm okay with either of the above.  I also remember seeing someone track the bbox manually while doing the JSON conversion since all the points have to be visited.  Might be something we can inject into `makeGeoJsonLayer`.

**Comment by mweech** [comment]
Note: Zoom to Layer Boundary still works even if there is no ability to display a bounding box.

**Comment by ChrisLatRNCan** [comment]
From now I can manually set fullExtent and make the bbox appear.
However, while playing with bbox (not only for file upload) I found some weird stuff like this:
![image](https://cloud.githubusercontent.com/assets/16193004/19453017/5f826808-9481-11e6-9fc7-887229c51d36.png)
That's huge bbox. I didn't know that we had railways under seas.

**Comment by ChrisLatRNCan** [comment]
I implemented bbox calculations at file load to avoid repetitive calls when bbox is enabled/disabled.
I tested with csv, json and zipped shapefile on both type of projection.

**Comment by mweech** [comment]
Verified.
