### ISSUE TITLE
Make API event-based

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#794]
Right now if certain api calls are made during map recreation they will break.

To handle this we can replace our promise-based api startup with an event-based system that can switch between queue and call mode.

Might be missing some steps but the main changes are:
- on map creation broadcast `rvApiReady`
- on map deletion broadcast `rvApiWaiting`
- create api service on first `rvApiReady`
- update queueing code for api proxies to halt on `rvApiWaiting` and resume on `rvApiReady`

**Comment by milesap** [comment]
completed - though new api discussion also covers api events so closing this
