### ISSUE TITLE
Add support for name field in Feature Layers

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#796]
We currently do not have a name field definition in place for Feature Layers.  This is really only noticeable on the identify results pane, where the header shows `Feature ###` instead of the feature name.

A quick solution would be to utilize the `.displayField` property of the feature layer object.  This will use the name field as defined on the Map Service (note that this is what is happening for Dynamic Layers - the identify results include the name field defined by the server).  Our file-based layer generator may also need to manually set this property to make things consistent.

A more complex, more flexible solution would involve adding a name field to the config schema, which would allow a site publisher to define a specific field. We may also need to add an optional setting on the RCS registration to allow a publisher to override the name field.  This will be done in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/836

- [x] Use server-defined name field if present

**Comment by mweech** [comment]
Is this not already done for RCS registration of Feature Layers when a "display_field" is specified?

**Comment by james-rae** [comment]
Sweet, one less thing to do.  If we implement the complex solution, the config schema should adopt the name of the field stored in RCS, `nameField`

**Comment by AleksueiR** [comment]
What about file-based layers? Is this the same as the primary field in RAMP?

**Comment by james-rae** [comment]
Yes.  Your wizard is likely already getting the field.  It just needs to be applied to the correct spot depending on what approach we take.

**Comment by AleksueiR** [comment]
Yes, I added the primary field picker initially, but it didn't do anything useful (no on-hover tooltips), so I wasn't sure it's still needed,

**Comment by mweech** [comment]
As part of this change, Point Information panel should look at this layer property to see if it is set and then use nameField to decide which attribute is used as a heading.
