### ISSUE TITLE
Mercator Maps - Magnifying glass & tooltip not appearing when Scale Dependency layer is out of scale

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#801]
For Scale Dependency layer CESI Air Ozone, when zooming in to scale 100km (60mi), this layer was out of scale and map points were not displayed. However, the magnifying glass & tool tip (Layer out of Scale) were not appearing as expected for any Mercator Maps.
Related to issues https://github.com/fgpv-vpgf/fgpv-vpgf/issues/783

![image](https://cloud.githubusercontent.com/assets/18723160/16206037/9bce8840-36f4-11e6-9d6b-0b47c986c711.png)

**Comment by mweech** [comment]
cannot reproduce under new build.
