### ISSUE TITLE
Bounding box (Manitoba) not working for initial loaded Lambert map

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#814]
Tested for version 18.0-2, URL: http://fgpv.cloudapp.net/demo/v0.18.0-2/index-fgp-en.html?
keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
This is related to an earlier issue logged which is resolved in current build -  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/736
Bounding box for this layer only appears when switching from defaulted Lambert base map to any of Mercator maps.

**Comment by james-rae** [comment]
Projection lookup was not applied to layers coming from RCS.
