### ISSUE TITLE
Opening main panel alters view of window

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#815]
Steps to reproduce:
- Open [index-wet](http://fgpv.cloudapp.net/demo/develop/samples/index-wet.html), index-fgp-en or index-fgp-fr
- scroll down
- click on button to open the legend
- window scrolls to the top at the beginning of the animation

This is probably caused due to how the panel's animation is started. I think the panel is placed at the top of the page, (possibly just the above the viewer)... with it being in focus the window tries to show the entire panel and pans upwards.

**Comment by AleksueiR** [comment]
Works as expected in [v0.18.0-1](http://fgpv.cloudapp.net/demo/v0.18.0-1/index-wet.html).

**Comment by AleksueiR** [comment]
The focus was being set to the close button on the main panel at the beginning of the transition (not waiting for child promises to resolve). The initial panel's position (shifted upwards) put the button above the app container (even above the top border of the page) and by focusing on it, the page would scroll up.
