### ISSUE TITLE
Allow Datagrid to be Filtered by Current Extent

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#822]
The viewer should allow for the user to filter the datagrid by the current viewable extent.  This would be done by providing a Filter by Extent option when viewing the datagrid.

**Comment by james-rae** [comment]
This analysis was done in November 2015.  Putting it here in hopes it has some value.

# Existing Code
 
Examining the methods of filtering available in existing applications (RAMP, GCViz, others if anyone else has info), and their pros and cons.

## RAMP

RAMP's Year-1 development only supported simple filtering – a layer was on or off, and the grid showed what was on the map. Initial work into Year-2 (prior to team merge) added in support for the RQL query language as part of the filtering pipeline. This allows feature attributes to be filtered by any SQL WHERE-ish statement.  The results would define what entered the datagrid, and what was visible on the map.

The spatial element (i.e. what is visible on the map) utilizes the Spatial Query as part of the ESRI API. Layers in, ObjectIds out.

PROS
* Can support any WHERE-ish filtering requirements
  * Nested Boolean logic
  * Aggregation support
  * Regular Expressions
  * Collection support
* De-coupled from grid control – architectural flexibility 
* Client-side performance

CONS
* Any user-facing filter controls must be built.
* De-coupled from grid control – requires grid population code
* Requires feature attributes to be in a predictable form
  * Not an issue with ESRI layers
  * Expanding support to other types of layers may require transformation code
* Requires attributes to be on client
  * We are putting stuff in grids, so have already scraped it from a service (both Feature and Dynamic Map Service apply).
  * Extra work to visually filter features in dynamic layers

 
## GCViz

GCViz utilizes the built in filtering controls of the datatables grid. This combines both the filtering and grid population into one step.

Like RAMP, the spatial element is handled by the ESRI Spatial Query object.

PROS
* Out-of-box functionality
  * Grid population
  * Filtering input boxes in grid column headers
* Client side processing. No server hits.
* Datatables filter support is extendable
  * Would require some team learning

CONS
* Forces implementer to stick with datatables.
  * Not necessarily a bad thing

## ArcGIS Online

Look at how ArcGIS Online accomplishes filtering. 
* What can we leverage?
* Can we structure things in a way that has maximum compatibility?
* Is accessibility met?
* Ensure our use doesn't hamper support for other layer types.
* ESRI JS Sample site uses definition query. If AGOL also takes this approach then we are in a good spot.
* Suggest someone with experience developing with AGOL endpoints add some content here

## Filter Support for Different Service Types

This section attempts to predict how those services will be consumed by the viewer (i.e. what Layer object type) and what kinds of filtering support is possible.

FeatureLayer types in JSAPI can support & instantiate MapService and FeatureService endpoints (feature layer enpoints only). 
* Supports [Definition Statement](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#setdefinitionexpression) Filtering

Dynamic Map Service Layer types in JSAPI can support & instantiate MapService, FeatureService, Hosted Feature Service, and MapService with Dynamic Capabilities
* Supports [Definition Statement](https://developers.arcgis.com/javascript/jsapi/arcgisdynamicmapservicelayer-amd.html#layerdefinitions) Filtering
* Could not find detailed info on MapService with Dynamic Capabilities and any additional impacts to definition statements. As I can tell, the Dynamic part allows for changes in layer order and symbology; it should not impact filters.

The following Image Based Layers will not have filtering at this time. This covers:
* Mapservice with Raster Data Source
* Image Service
* Tile Service (Cache)
* Hosted Tile Service (AGOL)

Unknown: Vector Tiles
* appears possible to access attribute data for tiles
* don't see any API call allowing to change the visibility of individual features in a tile
* no "definition query" type properties
* will not be available until JSAPI 4 is implemented
* [Preview Page](http://basemapsbeta.arcgis.com/preview/app/index.html)

# Suggested Approaches
 
Current Suggestion (still open for team debate):

Utilize the filtering engine that comes with datatables.  The product is mature and powerful, and we avoid re-inventing the wheel.  GCViz team (and possibly other groups) already have experience leveraging the filtering framework in datatables.

Utilize the Definition Query of feature-sourced map layers to restrict what is shown on the map. This approach is supported by FeatureLayer and DynamicMapServiceLayer types, allowing us to filter both with the same statements.

**Comment by mweech** [comment]
updated requirement description to focus on a Filter by Extent button instead of a default behavior which would be expensive performance wise and cause updates on small movements of the viewable area.

**Comment by milesap** [comment]
### Proposal using Query

#### 1. Get feature ID's
Using `esri.tasks.Query`, a mapserver request is made for a list of all feature ID's that are located in our current extent (more formally - all features that intersect with the extent). The following properties in the `esri.tasks.Query` object are used:
    
    query.outFields = ["THEOBJECTID"];
    query.geometry = geoService.mapObject.extent;
    query.spatialRelationship = "esriSpatialRelIntersects";

#### 2. Filter datatable

Create a filtering function that gets called for every row in datatable. Return true if the rows ID is in the list of ID's from step 1. This function is passed into datatables range filter `$.fn.dataTable.ext.search` 

### Issues
- `exceededTransferLimit` will continue to require multiple synchronous requests to be made to bypass the usual limit of 1000.

**Comment by alyec** [comment]
> will continue to require multiple synchronous requests to be made to bypass the usual limit of 1000

Why would the requests be synchronous?

**Comment by james-rae** [comment]
^ they would be asynch calls, but executed in synchronous fashion (i.e. you need to wait for one to finish before you can know if you need the next one)

**Comment by alyec** [comment]
✔️

**Comment by james-rae** [comment]
See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/485 for more info on server limits.  In particular, `exceededTransferLimit` is not provided if the server version is 10.0 or older.

@jolevesq had mentioned using a SQL plugin for Datatables (and I believe he is using this currently in GCCanViz, so we might have working samples). 

I believe a filtering function will be faster, particularly with extent search (since we have to compare against object ids). SQL is more flexible in that the query is a string instead of a function. Layer definition statements are also in SQL format, making it easy to apply them in the grid. We can probably have a good long design meeting for options on this.

**Comment by james-rae** [comment]
Some notes from Johann regarding grid filtering in GCCanViz before he left for vacation:

Everything is inside 2 files -- [DatagridVM.js](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js) and [gisDatagrid.js](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/gistasks/gisDatagrid.js).  You can look at http://atlas.gc.ca/imaema/en/index.html for a sample on how it works in real life. 

`DatagridVM` lines 331 to 1638

* We create the fields ([_self.createFields](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L775))
* We add renderer for long text (…) and set it WCAG
* Do setup if a link table is set
* Add select column
* Setup function ([_self.initCompl](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L461))
* Filters only works for dynamic and feature layer. They work only for services. Even if a file added layer is a type of feature layer, filters does not work.
* For each table it check the data type and if it is dynamic or feature layer it will add the filter map and spatial filter button to the table.
* We add clear filters and export CSV to all tables
* Add a selection column (html)
* Loop thought all field and if they are searchable, add the proper type of filter (html)
* Link search field function ([_self.addSearcFields](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L577))
* For each filter check the type and apply the proper function (text, dropdown, date, numbers and select checkbox)
* We set event for button click ([_self.setEvents](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L973))
* Set click on row = selection and double click on row = zoom to
* Apply filter ([_self.applyFilterMap](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L1407))
* Loop trough all filters and create the definition query
* Concat if definition query already exist
* Apply the definition query (different between feature layer and dynamic)
* Spatial filter ([_self.selExtent](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L1550) and [_self.setSelection](https://github.com/GeoCanViz/GeoCanViz/blob/master/src/js/widgets/viewmodels/datagridVM.js#L1619))
* Draw a box on map to get extent then set selection
* With all the object id to select, build the definition query
* We support multiple field type
	* string
	* number
	* date
	* hyperlink
	* only the value
	* value with another field to link value
	* Static value to apply to all link
	* Picture
	* show as link inside datable
	* show image inside identify

**Comment by AleksueiR** [comment]
Filter by extent be toggled on/off on a per layer basis. When turned on, a "filter" flag is added to the legend entry to it's clear which layers are filtered (clipped from mockups):
![](https://i.imgur.com/UFe1G1N.png)
