### ISSUE TITLE
Feature highlighting icon is hidden partially 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#823]
Tested : v18.0-2

_The highlighter seems to be under the Feature point at times. Is this acceptable_?

![screenhunter_2295 jun 23 09 53](https://cloud.githubusercontent.com/assets/18539315/16315466/6d732aec-3950-11e6-8a8e-2414c29e0eba.jpg)

![screenhunter_2300 jun 23 14 58](https://cloud.githubusercontent.com/assets/18539315/16316142/08cb1980-3953-11e6-9f8f-ba321ab0597b.jpg)

**Comment by mweech** [comment]
At the moment this is by design as it brings prominence to the features you are viewing.

**Comment by mweech** [comment]
this is by design.  confirmed during sprint review June 24th.
