### ISSUE TITLE
"Esc" does not always close the Panels

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#825]
Tested on v18.0-2

Relates to :https://github.com/fgpv-vpgf/fgpv-vpgf/issues/622

Panels are not always closed on "Esc". It seems to work on the initial load of the map. However, stops working after being on the viewer for sometime. Do not have the exact steps to reproduce. Please investigate.

**Comment by spencerwahl** [comment]
Was able to find a scenario:
- Open main panel
- Open datagrid for some layer
- Open settings panel for some layer
- Esc will not close the settings panel

**Comment by mweech** [comment]
After a while, map also stops responding to identify requests.

**Comment by AleksueiR** [comment]
:point_up: maybe this should be a separate issue?

**Comment by milesap** [comment]
This seems to be resolved with PR #943
