### ISSUE TITLE
Get Link - Basemap check mark always defaulted to Transportation (With Labels)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#826]
Get Link captured the selected basemap (World Street Map in below screenshot), but the check mark for basemap still pointed to Transportation (With Labels) in Lambert Gallery.
![image](https://cloud.githubusercontent.com/assets/18723160/16317307/733e9ce2-3958-11e6-8c19-e35082a6c858.png)

**Comment by spencerwahl** [comment]
Investigated this as it pointed to a possibly large problem for bookmarking. Actual fix for the problem turned out to be very tiny so it will be PRd tomorrow.
