### ISSUE TITLE
Full page app support

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#834]
Put a flag in the config that lets the viewer know its in control of the page. Control meaning either:
- the viewer is the only content on the page (as in `index-one.html`)
- or it is in full-screen mode within the host page

Update `focus.service.js` so that it uses this config value, currently we have a `rv-fullpage-app` attribute in `index-one.html` as a temporary solution.

Should turn on things like the share button.

**Comment by AleksueiR** [comment]
This flag should be true when the viewer is __the only content on the page__ and when the viewer is in __the full-screen mode within the host page__.

This will also be used by the focus manager to not show the "keyboard focus" dialog when then viewer is in the full screen.

See PR #1167
