### ISSUE TITLE
Viewer Documentation

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#839]
Now that we have a build for docs setup ( #767 ) we need to identify the missing pieces.  I'm suggesting that we split our docs into user and developer sections.  Users being anyone making use of our library and developers being anyone who working on the library (i.e. us).

Sections we need (feel free to edit directly if you think of something obvious that does not need discussion):
## User Docs
- Working Examples
- Config Schema
- FGPV specific tag attributes
- User facing API (what is exposed from `window.RV`)
  - setting map position
  - get and restore bookmarks
  - switch languages
- Accessing logs and debugging
## Developer Docs
- Dev Environment Setup
- FGPV API Docs
- geoApi API Docs (linked, this should not be built directly into the FGPV)
- Tooling / Build Process
- Architecture Overview
- Module Descriptions
- UI Breakdown / Terminology
- Function Specific Docs
  - Startup
  - Attribute Loading
  - Datagrids / Working with Datatables
  - State Preservation
  - Details Panel
  - Legend Generation (Auto and Structured)
  - Layer Classes / Layer Creation
  - User Added Layers
  - Identify
  - Highlighting
  - Symbology
  - Zoom Scale Dependency
- Adding translations and general use of `angular-translate`
- Proxies
- Test
- Exception Handling
- Logging

**Comment by ChrisLatRNCan** [comment]
For both user and developper we could add **Language managment** since it touches many aspect already mentionned on your list.

**Comment by alyec** [comment]
Thanks, I've added it to both.  Feel free to edit if you think it belongs in a different place.

**Comment by mweech** [comment]
this epic needs to be populated with child issues..

**Comment by milesap** [comment]
Shelved until all assigned documentation is merged.

**Comment by milesap** [comment]
Will be required for 2.0 release
