### ISSUE TITLE
Registered WMS with "recursive" flag set not displaying in Viewer

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#840]
Registering a WMS layers with recursive set to grab all the sublayers: 
```
{
	"fr": {
		"feature_info_format": "text/plain",
		"service_url": "http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities",
		"service_type": "ogcWms",
		"legend_format": "image/png",
		"recursive": true,
		"service_name": "WMS french"
	},
	"en": {
		"feature_info_format": "text/plain",
		"service_url": "http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities",
		"service_type": "ogcWms",
		"legend_format": "image/png",
		"recursive": true,
		"service_name": "WMS english"
	},
	"version": "2.0"
}
```

Registers in the RCS as such:

```

{
 	"layers": [{
 		"featureInfoMimeType": "text/plain",
 		"name": "WMS english",
 		"url": "http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities",
 		"layerEntries": ["railway",
 			"railway.structure.line",
 			"railway.structure.point",
 			"railway.track",
 			"railway.ferry",
 			"railway.subdivision",
 			"railway.station",
 			"railway.marker_post",
 			"railway.crossing"],
 		"legendMimeType": "image/png",
 		"layerType": "ogcWms",
 		"id": "rcs.0.en"
 	}]
 }

```

When loading in the viewer (http://fgpv.cloudapp.net/demo/develop/index-fgp-en.html?keys=wmessy), this is what I see: 
![image](https://cloud.githubusercontent.com/assets/5294596/16388877/2f7290f4-3c69-11e6-8dc0-1ea30dd10bf2.png)

Am I doing something horribly wrong?

**Comment by alyec** [comment]
`service_url` should point to the WMS endpoint directly (i.e. remove the rest of the query string)

**Comment by james-rae** [comment]
> Am I doing something horribly wrong?

You're using WMS  :dancers: :dash: 

at first glance, the URL has getcapabilities request tacked on it.  could be that is the issue?

**Comment by dan-bowerman** [comment]
That might have been an issue, but doesn't appear to be the issue. I fixed that, but this is the sort of call I see in Fiddler:

http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&STYLES=&VERSION=1.3.0&LAYERS=,,,,,,,,&WIDTH=1036&HEIGHT=698&CRS=EPSG:3978&BBOX=-1964435.2135720942,-316569.440225214,2832470.213572094,2915322.4402252138

Seems the layer names are not appearing at all in the URL, just commas. Viewer or RCS?

**Comment by alyec** [comment]
RCS, it should not return a list of strings in `layerEntries`, rather it is a full object (since the viewer can set visibility and opacity per entry): https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/schema.json#L539 and https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/schema.json#L399

Example
```js
    {
      "id":"rail_wms",
      "name": "Railways",
      "layerType":"ogcWms",
      "url":"http://maps.geogratis.gc.ca/wms/railway_en",
      "layerEntries": [ {"id": "railway.track", "name": "Lines of many colours"}, {"id": "railway.station"} ],
      "featureInfoMimeType": "text/plain"
    }
```

If it is my RCS code which did that I will pay in muffins.

**Comment by dan-bowerman** [comment]
Thanks for the clarification, it's working well now. Sorry for not consulting the schema first!
