### ISSUE TITLE
Get Link - Bounding box visibility not captured for Mercator maps

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#841]
Tested URL: http://fgpv.cloudapp.net/demo/v0.18.0-2/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale
1. Screenshot for original Mercator map
![image](https://cloud.githubusercontent.com/assets/18723160/16392154/73bead92-3c78-11e6-8b99-9b71d0ff7cc8.png)
2. Screenshot for map loaded from Get Link URL
![image](https://cloud.githubusercontent.com/assets/18723160/16392190/9daf8b80-3c78-11e6-80cc-e636aa84e68b.png)

**Comment by spencerwahl** [comment]
WOMM (And Aly's machine)

**Comment by bkutty** [comment]
Please review this issue again. I could reproduce this using Firefox and Chrome. Bounding box is not captured when basemaps are Mercator. Tests were done using the JOSM and Airport Layers

**Comment by spencerwahl** [comment]
Alright retested, it was happening due to the projection switch. (Turning on a bounding box after using a mercator bookmark kept the bounding box)

This is fixed in v0.18.4 as far as I can tell

**Comment by mweech** [comment]
Not reproducable under current build.  Can you verify?

**Comment by mweech** [comment]
works in v1.3.0
