### ISSUE TITLE
FGP not responding when uploaded file size reached 7MB

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#850]
Tested on http://fgpv.cloudapp.net/demo/v0.18.0-4/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Uploaded a CSV file 521.csv (7231KB) will cause the map not responding. Need to know the system limitation?
![image](https://cloud.githubusercontent.com/assets/18723160/16499947/771c2a96-3ed0-11e6-959a-5963cd4b66fe.png)

**Comment by AleksueiR** [comment]
Does this happen in all browsers?

**Comment by IsabellaPan** [comment]
@AleksueiR It happened in both Firefox and Chrome. The screenshot already posted was captured in Firefox. Chrome screenshot see below:
![chrome capture](https://cloud.githubusercontent.com/assets/18723160/16564149/ed0b830e-41d3-11e6-85cd-c94e49c0bad8.JPG)

**Comment by IsabellaPan** [comment]
Test file 521.csv was sent to Mike and Aleksuei on July 11.

**Comment by james-rae** [comment]
Making the geoApi calls in a simple page to read the file (from develop webserver), validate, and convert to geoJson layer took approx 4 seconds in Chrome, using my desktop tower. 

Measuring again in the app (with same params), the time was closer to 8; the extra time being used to render the large set of points as graphics on the map.

The map rendering is likely out of our control.  The geoApi part -- could this be turned into a web worker (caveat: I barely know what a web worker is)?
