### ISSUE TITLE
Update index-fgp-en/fr.html sample pages to reflect new look and feel of GcGEO

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#861]
Update sample pages to reflect the new look and feel:
http://redmine.gcgeo.gc.ca/redmine/issues/4478

**Comment by milesap** [comment]
Looking for clarification on what needs to be changed. I downloaded the files linked at http://redmine.gcgeo.gc.ca/redmine/issues/4478, and this is what is rendered:

![861](https://cloud.githubusercontent.com/assets/10187181/16811154/132528a6-48f5-11e6-9c44-bcfc11df729e.png)

Should I replace the sign in title and form shown above with our map?

**Comment by milesap** [comment]
Closing issue - not enough information given to implement this change request.

**Comment by mweech** [comment]
As per discussion with @milesap.. the "Sign in" title will be replaced with "FGP Viewer" and the viewer and getlink box will be placed below the line underneath it.
