### ISSUE TITLE
Get Link not loading any layers in IE11

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#862]
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Screenshot for original map:
![image](https://cloud.githubusercontent.com/assets/18723160/16740578/bdb5beae-476d-11e6-9249-e990fb77a564.png)
Screenshot for Get Link map: 
![image](https://cloud.githubusercontent.com/assets/18723160/16740626/f1eb274a-476d-11e6-9ced-a775421c29e1.png)

**Comment by james-rae** [comment]
Could not reproduce.  Likely fixed in a previous patch for Get Link or IE Polyfills.
