### ISSUE TITLE
Unable to upload CSV and JSON files in IE11

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#863]
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
For CSV and JSON type of file, Import File panel displayed "Incorrect file format" error in IE11. However, the same CSV and JSON files can be uploaded when using Firefox and Chrome.
![image](https://cloud.githubusercontent.com/assets/18723160/16740921/23f765a4-476f-11e6-9bba-e743f5fb0ff0.png)

**Comment by james-rae** [comment]
IE is not recognizing the `TextDecoder` library that allows us to go from binary streams to strings. The [polyfill](https://github.com/inexorabletash/text-encoding) for `TextDecoder` [was added](https://github.com/fgpv-vpgf/geoApi/pull/116/commits/2fa8b59610fa989cedf3ba565a409be62e40bb0c) but apparently is not working.  

Need to figure out why the polyfill is failing in IE

**Comment by milesap** [comment]
IE dev tools unresponsive/not working, unable to diagnose or locate cause of issue.
