### ISSUE TITLE
Symbology for file-based layers is not displayed

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#867]
Legend (a placeholder is displayed for json, csv, and shapefile)
![](https://i.imgur.com/sfrRE4l.png)

Datatable (empty gif is displayed for csv)
![](https://i.imgur.com/cWSnqK5.png)

Details panel (broken image for csv)
![](https://i.imgur.com/Om2PIHk.png)

**Comment by james-rae** [comment]
The default symbology for CSV layers had no `outline` specified. The code was expecting an outline defined and set to a "no outline" state.  Code updated to handle the missing object.

Also added in `layerId` property to render-generated legend (related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/869 )

**Comment by james-rae** [comment]
File based icons will not display in the legend until https://github.com/fgpv-vpgf/fgpv-vpgf/issues/902 is implemented.   Also, be aware of work in progress to support that https://github.com/james-rae/fgpv-vpgf/commit/0ee9c065f5b3669f65c507966a7708fd31aa266a
