### ISSUE TITLE
Feature Layers from Group Layer services can have the wrong symbology in legend

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#869]
Try to add [this layer](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NorthAmerica/energy_infrastructure_of_north_america_en/MapServer/7) to the map. The logic inside `legend.service.js` assumes `layerId` matches positions of a corresponding legend object in a legend endpoint. This is true, unless the service has group nodes with no symbology, then they are skipped.

`layerId` of the aforementioned layer is 7; the legend endpoint returns the following array:
```
0 "Natural Gas Processing Plants"
1 "Liquefied Natural Gas Terminals"
2 "Refineries"
4 "Refinery"
5 "Upgrader"
6 "Asphalt Refinery"
7 "Power Plants, 100 MW or more"
9 "Biomass"
10 "Coal"
11 "Geothermal"
12 "Hydroelectric"
13 "Natural Gas"
14 "Nuclear"
15 "Other"
16 "Petroleum"
17 "Pumped Storage"
18 "Solar"
19 "Wind"
20 "Renewable Energy Power Plants, 1 MW or more"
22 "Biomass"
23 "Geothermal"
24 "Hydroelectric"
25 "Pumped Storage"
26 "Solar"
27 "Wind"
```

If you pick seventh item from the array, it's `Biomass`, not `Power Plants, 100 MW or more`.

Instead of fixing this logic, it might be better to display geoApi-generated symbology as it works correctly already.

**Comment by mweech** [comment]
RCS registration of this layer using the following syntax results in the right legend being produced (key: EnergyNA): {"en":{"service_url":"http://geoappext.nrcan.gc.ca/arcgis/rest/services/NorthAmerica/energy_infrastructure_of_north_america_en/MapServer","scrape_only":[0,1,2,3,7,8,20,21],"service_type":"esriMapServer","service_name":"Energy Infrastructure of North America"},"fr":{"service_url":"http://geoappext.nrcan.gc.ca/arcgis/rest/services/NorthAmerica/energy_infrastructure_of_north_america_fr/MapServer","scrape_only":[0,1,2,3,7,8,20,21],"service_type":"esriMapServer","service_name":"Infrastructure énergétique d'Amérique du Nord"},"version":"2.0"}

**Comment by AleksueiR** [comment]
The logic constructing the symbology stack on the viewer is at fault here:
![](https://i.imgur.com/sD5K3oV.png)

This how legend for [this layer](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NorthAmerica/energy_infrastructure_of_north_america_en/MapServer/7) looks.
