### ISSUE TITLE
"Your Location" button zooming to scale level 6m and loading blank map for all Mercator projections

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#874]
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
with all three major browsers.
![image](https://cloud.githubusercontent.com/assets/18723160/16777500/cea36188-4837-11e6-9c57-afd2a0774e2e.png)

Related to issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/401

**Comment by milesap** [comment]
Waiting on #954 for resolution
