### ISSUE TITLE
Unable to close expanded Feature Information window using Close icon

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#877]
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley on IE11
After expanded Point Information to open a new Feature Information window, clicking on Close button on top right of the window cannot close the expanded window.
Clicking Close icon only added another scroll bar and soon disappeared, and Close icon just shifted its place between the added inner scroll bar and its original place.
![image](https://cloud.githubusercontent.com/assets/18723160/16780118/396e75ce-4843-11e6-95f6-49cad5f8a257.png)

**Comment by mweech** [comment]
Close icon is still functional, however the appearance of the scrollbar would cause the close button to shift to the left and the click would not occur over the button.  A bit of rapid clicking will get it to trigger. :wink:

**Comment by AleksueiR** [comment]
I think https://github.com/fgpv-vpgf/fgpv-vpgf/issues/678 is a duplicate or at least related.

**Comment by milesap** [comment]
IE dev tools unresponsive/not working, unable to diagnose or locate cause of issue.
