### ISSUE TITLE
No Point Information displayed when clicking map points for user added Scale Dependency layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#887]
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
with all three major browsers.
Testing using Scale Dependency layer URL: 
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer
While clicking on map points for this layer,  it always showed "Zoom Level 1", but without any feature information displayed.
![image](https://cloud.githubusercontent.com/assets/18723160/16816186/f06811aa-490a-11e6-8a3b-22768dd8eb96.png)

**Comment by james-rae** [comment]
Not reproducible in current build (though can reproduce on `v1.0.0-rc2`).  Likely a fix that has been committed since this was logged has also solved this issue.
