### ISSUE TITLE
Picture not displaying on Menu panel

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#888]
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
There should be a picture displayed on top of the panel after clicking Menu button.
![image](https://cloud.githubusercontent.com/assets/18723160/16816564/6520987c-490c-11e6-9dad-bb6c60f64252.png)

**Comment by mweech** [comment]
Image file is expected to be located at http://fgpv.cloudapp.net/demo/develop/samples/content/images/fgp.svg however the content folder is missing.
