### ISSUE TITLE
Details panel doesnt show data on every other click

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#893]
If an identify click returns one result for a layer the panel will alternate only showing a header (with no ability to get details) or showing full details.

Tested using: http://fgpv.cloudapp.net/demo/develop/samples/index-fgp-en.html?keys=map_service_test

GIF for clarity:
![some_biomass](https://cloud.githubusercontent.com/assets/2285779/16849759/0404be24-49ca-11e6-9b83-04b44be9cff6.gif)

**Comment by james-rae** [comment]
Doesn't appear to be the "every second request fails" issue, as I can make multiple rest requests ok
