### ISSUE TITLE
Legend panel gets stuck above app-bar if rapidly opened and closed

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#895]
![image](https://cloud.githubusercontent.com/assets/8732588/16847328/78ac5a5e-49be-11e6-9e6a-07aaae7f0c44.png)

To reproduce: click legend button rapidly

**Comment by jolevesq** [comment]
If we use a debounce function it will solve the problem. We can use this function anywhere a user can click multiple times and it creates a weird effect.
