### ISSUE TITLE
Map object hijacks key events when hovered over

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#901]
If you hover over the map and try to manipulate any input filed with arrow (home, end, minus, plus, etc.) keys, map object intersects and stops propagation of these events turning them into pan/zoom actions.

In here I press left/right arrow keys:
![esri_has_your_base](https://cloud.githubusercontent.com/assets/2285779/16850073/61137e7e-49cb-11e6-9ae7-4af315efb16c.gif)

**Comment by mweech** [comment]
@AleksueiR i assume expected behavior would be to disable keyboard navigation of map while a textbox has focus?

**Comment by AleksueiR** [comment]
@jolevesq mentioned during the workshop last week that GcViz implements its own custom keyboard support for map navigation. If we can reuse that and disable the built-in esri keyboard support, this will be fixed. This ties into #808.

**Comment by AleksueiR** [comment]
Related to #808.
