### ISSUE TITLE
GeoJSON with no features fails to load

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#911]
Using a geojson file with no features (see `poly-noattr.json` for a sample) fails to load.  Traced to `LayerFileBlueprint.validate` and haven't looked further.  @AleksueiR was looking into file validation a few days ago, this may be related.

**Comment by AleksueiR** [comment]
Validations of this kind should be done in geoApi's [validateGeoJson](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/layer.js#L454) function.

**Comment by AleksueiR** [comment]
Might be related to #933.

**Comment by mweech** [comment]
This case is now handled such that when attempting to add a GeoJSON file with no attributes, the process fails when trying to select is as type GeoJSON.
