### ISSUE TITLE
Blank Map not captured when using Get Link

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#926]
Tested on http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
For Firefox and Chrome
Original Blank Map:
![image](https://cloud.githubusercontent.com/assets/18723160/16964753/1e6a2646-4dcb-11e6-9222-bb16b6987556.png)
Map loaded from Get Link URL;
![image](https://cloud.githubusercontent.com/assets/18723160/16964836/68171998-4dcb-11e6-8480-008184b46d25.png)
- [x] Encode info blank state
- [x] Update bookmark version
- [x] Parse blank state, set config appropriately (correct wkid, default basemap)
- [x] Update decoder page to support new format

**Comment by spencerwahl** [comment]
Partial progress made in: https://github.com/spencerwahl/fgpv-vpgf/commit/cd430855f3f7845477646867af59ea54cc4c8c25

Main problem was IDs for current selected basemap seemed to not always update. This would cause the bookmark to be inconsistent when dealing with blank basemaps.

**Comment by mweech** [comment]
Verified
