### ISSUE TITLE
Cannot Add Group Layer using User Added Layers 

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#929]
When trying to add http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/0 it indicates the wrong service type for any Service Type selection.

http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer works..
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/1 works..

Expected Functionality:
-User adds http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/0
-Identified as a Group layer so Dynamic Layer is selected
-User is prompted to select either the Group, or the sublayers (0 or 1, 2, 3, 4).  Other group layers are hidden.

**Comment by james-rae** [comment]
The URL predictor will indicate the layer type being `serviceType.GroupLayer`.  This can be used to push the wizard into the Dynamic mode and do additional tricks.
