### ISSUE TITLE
User Added Layer Type Flag not showing for Dynamic Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#931]
When adding a Dynamic layer from an Esri REST service (http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer), the User Added Layers type flag is not added.

**Comment by AleksueiR** [comment]
Cause: the user-added flag is applied to the top level legend entry and is not propagated to its children.

**Comment by AleksueiR** [comment]
@cynngah There is a small problem: [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1107/files#diff-b23af0e22029c29a4db541250de46dbdR565) sets the `user` flag on dynamic layer children, but it doesn't take into account subgroup children. Subgroups don't have flags and assignment fails. Need to check first if `flags` exist on a child element.
