### ISSUE TITLE
User Added Layer silently fails

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#933]
When a user added layer of type csv fails to be converted to a feature layer (i.e. some rows have a blank value in the latitude column), then the viewer will fail to add the layer, close the dialog for adding layers and there is no indication something has gone wrong.  Instead, the viewer should add the very least catch all failures and add the layer with an error state.

**Comment by cynngah** [comment]
Doesn't silently fail anymore but it tells you a very bad error message

Relates #210
