### ISSUE TITLE
Unable to add ESRI Air Quality layer in IE11

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#935]
Tested in build: http://fgpv.cloudapp.net/demo/v1.0.0-rc3/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Esri Air Quality layer URL: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer
This is a similar issue as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/908 but it is only specific to IE11 browser. Adding the same layer is working with Firefox and Chrome.
![image](https://cloud.githubusercontent.com/assets/18723160/16992738/7f523004-4e6e-11e6-8b20-88ee2399564a.png)
It failed both the first attempt and second attempt as well to load this Esri layer.

**Comment by spencerwahl** [comment]
need to add https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Polyfill

**Comment by spencerwahl** [comment]
Adding this in to go along with alex's geoApi changes for #908
