### ISSUE TITLE
When solo record was collapsed there is no Chevron button to display details again

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#946]
Tested in build: http://fgpv.cloudapp.net/demo/v1.0.0-rc3/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley for all three major browsers
When there is only single point for the layer after clicking map point, no Chevron button could be found on both expanded Feature Information window and Point Information panel as well. In this case Map point details couldn't be displayed.
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/819
![image](https://cloud.githubusercontent.com/assets/18723160/17026792/5a066fce-4f2f-11e6-85df-87b68f545708.png)
![image](https://cloud.githubusercontent.com/assets/18723160/17026841/7c8a70ae-4f2f-11e6-8c9f-19b4071f9509.png)

**Comment by milesap** [comment]
This issue is resolved with PR #945
