### ISSUE TITLE
Closing service import wizard breaks if clicked immediately

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#952]
Below, the service import panel doesn't close, it collapses the first step of the import stepper. If you interact with the url field and enter something there, the panel is closed properly

![silly_service_import](https://cloud.githubusercontent.com/assets/2285779/17066939/628f9902-5017-11e6-82bb-c591571d5fa9.gif)

**Comment by AleksueiR** [comment]
Happens in all browsers.

**Comment by mweech** [comment]
Chrome WOMM.
