### ISSUE TITLE
IE 11 Scale dependent layers Visibility Toggle broken for dynamic layers

### ISSUE THREAD

**Issue by cynngah** [fgpv-vpgf/fgpv-vpgf#953]
Visibility toggle broken for dynamic layers in IE. Shows up for out of scale layers when it's not supposed to.

**Comment by james-rae** [comment]
Cannot reproduce.  Likely related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1019 , as you can see the issue occurring in the screenshot there. 
Best guess is when that `00002ee2` Timeout error happens, it causes the thread to die before it can execute the scale / visibility setup code.

**Comment by james-rae** [comment]
May also be related / solved by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1028

**Comment by james-rae** [comment]
`v1.0.2-rc1` after clearing IE cache issue is now appearing.  It is the `00002ee2` bug
