### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#959]
Library is now released.  Need to do performance testing to identify bottlenecks, max layers, etc.

**Comment by AleksueiR** [comment]
"Slow" performance can be also caused by longer than usual service response times (in cases where these calls are blocking).

**Comment by mweech** [comment]
Spring cleaning.  Performance bottlenecks typically originate from target services with programmatic issues fixed organically.
