### ISSUE TITLE
Handle cases where hosting page has Angular already

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#960]
From Pauline George (NACEI):

> We tried to embed the map viewer and it is returning some errors.  After some investigation the errors maybe due to conflicts with the core.js and bootstrap.js files.  It seems like the conflict occurs if a site or application is already using angular (we are using angular).  There seems to be an open issue in github for this particular issue

**Comment by AleksueiR** [comment]
A quick fix might involve using the same approach as the issue with jQuery libraries - check if Angular is already loaded and load it ourselves if not.

**Comment by alyec** [comment]
> check if Angular is already loaded and load it ourselves if not

To clarify this a bit further, we have other libraries that depend on Angular and may be sensitive to the version.  I think the best we can do until we sort out https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1689 is:
- load angular conditionally (like we do with jQuery)
- keep `angular-*` dependencies in the main build
- try to test out the various lines of angular and keep known issues in a compatibility list on the wiki

**Comment by AleksueiR** [comment]
Angular seem to bind to jQuery as soon as it loads. If just Angular (without jQuery) is loaded by the host page, it will not bind correctly with jQuery loaded after that. 

I can add another warning saying that jQuery must be loaded before Angular. Any other ideas?

**Comment by AleksueiR** [comment]
Alternatively, Angular binds jQuery to `angular.element`, so we can replace all `angular.element` with calls  to `$`. Something else might break though.

**Comment by AleksueiR** [comment]
> To use `jQuery`, simply ensure it is loaded before the `angular.js` file.
https://docs.angularjs.org/api/ng/function/angular.element

**Comment by bkutty** [comment]
Tested Build :http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-mobile.html

The warning message of different js libraries seems to be hidden due to bug https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1702. Re-opening this issue

**Comment by milesap** [comment]
One of two things should happen IMO:
1. Do not load viewer if angular major/minor version differs from ours (and display a warning in console). Looking ahead to v2.0 for example, angular 1.4 or 1.5 will not work with our 1.6. Given our resources and timelines, back supporting prior angular versions may not be a great idea.

2. We run and load our own angular and jquery libs if it differs from the host page. This seems like the better solution at first glance - but I'm not all that sure if it would work without some major changes. If this idea is supported further investigation would take place.

**Comment by AleksueiR** [comment]
I agree with not loading the viewer is major version of Angular is differs from ours.

**Comment by milesap** [comment]
I assume you mean both major and minor?

**Comment by milesap** [comment]
I forgot to mention, the following dependencies require angular versions match to work (they could still work on patch changes but the authors do not support mismatched version):
- angular-animate
- angular-aria 
- angular-messages
- angular-sanitize

**Comment by AleksueiR** [comment]
We can try to load corresponding minor versions of `animate`, `aria`, etc. if the minor version is different and see if that works.

**Comment by alyec** [comment]
How about an attribute which allows people to try and pin an Angular / jQuery version (`rv-ng-version` or something)?

Unless something has changed I don't think we can sandbox angular and jquery very well (webpack + es6 imports may alleviate that, not sure) and I'm not a fan of clobbering the global scope (I got to do a lot of bugfixing on old RAMP because of other libraries doing that).

**Comment by milesap** [comment]
Moving this to v2.0.0 for now - feel free to reprioritize if needed

**Comment by milesap** [comment]
complete with webpack changes
