### ISSUE TITLE
Investigate combining bounding boxes into a single “bounding box” layer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#970]
Currently there is one layer per bounding box.

Proposed change is to make one bounding box layer, and any time a bounding box is created it is placed in this layer.  The layer is always above the working map stack (same as the highlighting layer).

The box Graphic will have an extra property added, containing the id of the layer it belongs to (so we can find it in the BB layer).  Alternately we can have the main layer object maintain a pointer to the graphic, avoiding searching the layer but strongly couples the implementation to the BB concept.

**Comment by AleksueiR** [comment]
Are there any benefits to a single layer solution? This would require additional logic when toggling the visibility of the bounding boxes as they will be "features" inside an always-on bounding box layer.

**Comment by mweech** [comment]
No rationale for investment of development time.
