### ISSUE TITLE
Add GPX, TopoJSON & KML file support for User Added Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#971]
Add the capacity for the Viewer to have GPX, TopoJSON and KML files be supported by the User Added Layers feature.

http://160.106.65.239/redmine/issues/386

**Comment by yblain** [comment]
Related Redmine issue: http://redmine.gcgeo.gc.ca/redmine/issues/389

**Comment by mweech** [comment]
Need to do some R&D on what libraries are available to perform conversions to GeoJSON which is our basis for converting to Esri layer types.
