### ISSUE TITLE
Need to have a UI component breakdown with terminology

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#972]
Map authors as well as RAMP Developers would benefit from having a better breakdown of RAMP UI components including a baseline of the terminology to describe them.  With the advent of the extensibility framework, this is now particularly vital in order to ensure documentation, dev proposals and plug-in documentation are aligned.   

The UI component breakdown should use both a graphical representation of the interface with the sections tagged, as well as have textual definitions of each UI components.

**Comment by mweech** [comment]
Modified issue body to give a use case to work around.

**Comment by AleksueiR** [comment]
Working copy: https://gist.github.com/AleksueiR/03a27c47af53a51692645cef3eed171b
