### ISSUE TITLE
Plan API / Plugin architecture

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#977]
This will be done over several steps:

- [x] Review third party API's like Google Maps to see what are some common design patterns and best practices

- [ ] Solicit feedback from interested parties both in and out of ECCC for use cases we might miss

- [x] Determine if any existing map functionality can/should be branched off to a plugin
    - It's clear that for some use cases, a faster loading/highly responsive map is best (ex. PCC) with a trade-off in removing some heavy weight functionality that's not needed. Especially for public facing maps with more basic needs, just there to show some visual data on a map.
    - Let's map authors be in control of just how fast vs. feature rich they want their viewer

- [x] Document the basic structure of the API and how it is accessed by page/plugin authors

- [x] ~~List core plugins we will provide and their scope~~

See the [API Manifesto](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/API-Manifesto) for latest direction.

**Comment by AleksueiR** [comment]
Check wiki for more information: https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Plugins

**Comment by milesap** [comment]
Updated issue comments

**Comment by milesap** [comment]
:warning: wip :warning: 

Possible areas of the viewer that can be split off into into its own module/plugin (and only uses the external API):

#### data table
> Move entire table code, as is, out of viewer including all related libraries as a first step. It is unlikely we have the time to re-work this section, but some general performance enhancements would be nice since it is likely to be used a lot

#### export

#### full state preservation / share links / bookmarks

> These would be bundled as a group, we don't want too many different plugins, Instead group by related functionality.

#### geoApi

> This one will be tricky. While we always liked the idea of being able to swap out the geoApi, it is the equivalent of doing a heart transplant. The idea is that the viewer defines what geo related functionality it needs (think interfaces) and as long as those are properly defined, it doesn't matter by what. So geoApi implements the viewers geo interface (if we assumed JS has interfaces), where geoApi implements some of that itself, and passes through some work to the esri API (like it currently does). If someone wants to enable support for different services or modify existing ones, they can build on geoAPI or pull it out entirely and implement the interface themselves)

#### Focus Manager

> If accessibility is not your thing

#### Legend / Search / Import service & file

> As a group, for maps that only want to show data

**Comment by mweech** [comment]
@milesap update/estimate plz...

**Comment by milesap** [comment]
Planning is complete on my end, the tentative API is [here](http://fgpv-vpgf.github.io/fgpv-vpgf/api/modules/_index_d_.rv.html). 

That said, we still need one more meeting to finalise the API before it moves to implementation. @james-rae should have a look at [simple](http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.layer.simplelayer.html) and [config](http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.layer.configlayer.html) layer types to see if those need any major changes.
