### ISSUE TITLE
Improve Layer state handling

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#980]
If a layer is not visible or is offscale, it would never attempt to fetch data and therefore never proceed from the Loading to Loaded state

**Comment by james-rae** [comment]
Adjusted the state transition from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/606 to be

![layerstatenew](https://cloud.githubusercontent.com/assets/7585245/17226622/58a92e10-54d8-11e6-88b3-2acf98dfe879.png)

The main changes are
* a new layer begins in `LOADING` state. makes sense as we are trying to load it.
* after a `load` event, we go to the `LOADED` state. This covers any off scale or invisible layers, as they are done as they are going to get for the moment.
* if a layer has visible data at the beginning, the `update-start` event will go from `LOADED` to `REFRESH` state.
  * if there is data, the `LOADING` -> `LOADED` -> `REFRESH` flow should be very fast.  There is no reason for the API to pause on `LOADED`

May be worth looking into merging `LOADING` and `REFRESH` state -- to me they are the same thing, unless we have different animations?

**Comment by spencerwahl** [comment]
A couple things:

1. I don't think the `update-end` transition from `loading` to `loaded` will ever be triggered (and it shouldn't imo)

2. `loading` was being used for full layer reloads (pressing the reload button) while `refresh` was being used on map-based updates (panning, zooming, etc.). I _think_ `loading` is tied to the loading placeholder while `refresh` just causes the "working" animation on a loaded layer.

**Comment by james-rae** [comment]
Yeah, `update-end` from `LOADING` I assumed was on the diagram for completeness, but agree should never happen in practice. I didn't bother deleting it from the pic.

If `LOADING` is tied to extra placeholder stuff, then it makes sense to keep the `REFRESH` state.

**Comment by AleksueiR** [comment]
I always thought a layer was in the `NEW` state from when it was created and until it is added to the map/layer selector, then it is `LOADING`. It seems we have no use for that right now though. If we need to delay adding a layer to the map after a layer record is created, the `NEW` state can be useful for distinguishing layers added to the map from ones on hold.
