### ISSUE TITLE
Grouping Layers in Slider Portion of Identify Results Panel

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#984]
Currently the viewer maintains the order of the layers in the slider portion of the Details panel.  As a result, on the first Identify click, it is possible for there to appear to be "No Results" as indicated in the screenshot from JOSM below.  Also, when many layers exist in the viewer, results will be greatly spread out and it is possible they will overflow beyond the viewing area of the slider while showing a long list of layers with no results.
![](https://cloud.githubusercontent.com/assets/5294596/22252111/2a19fe5a-e21b-11e6-90d3-70c4b541e18b.png)

Once a layer is selected, subsequent Identify clicks will be sticky as per #645.  However, this does not address the poor initial feedback provided or deal with results being buried at the bottom of the slider.

In order to address these shortcomings:
- Add three "groups" of layers to the slider area, "Results", "Waiting for Response", "No results"
- All layers will initially appear in "Waiting for response"
- As results are received, the layer is moved to the appropriate group
- Identify results should still stick to previous layer selection (forward planning FTW  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/645#issuecomment-223328636)

**Comment by dan-bowerman** [comment]
An example using JOSM:
![image](https://cloud.githubusercontent.com/assets/5294596/22252111/2a19fe5a-e21b-11e6-90d3-70c4b541e18b.png)

**Comment by milesap** [comment]
No UI design changes will be made. Layers with results will be placed above loading layers, and layers with no results will be placed below loading layers. 

I will preserve layer ordering within these respective groupings.
