### ISSUE TITLE
Centering the map throws an error when using centerAt function

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#987]
Centering the map using the centerAt function throws an error, the message appears to be a promise with message `{message: "Request canceled"...}`. The map updates to the new center position despite this error. This error can be thrown thousands of times when centerAt is called often (as is the case when keyboard navigation is implemented soon).

To reproduce, try running `mapObject.centerAt(someMapPoint);` inside the `map.service.js onMapLoad` function.

**Comment by james-rae** [comment]
Could not reproduce. Note that we use `centerAt()` for all zooming and bookmark restoration.  
I tried adding a specific call in the map load handler, no error was thrown. 

Am assuming one of the many fixes since this was logged has corrected the problem.
