### ISSUE TITLE
Expand tooltip gets stuck after grid info request

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#995]
To reproduce:
* Open the grid for a feature based layer.
* Ensure the Details panel is currently closed (it should be if you just opened the grid from the legend).
* Click the Details button for a row in the grid
* Details panel opens. The tooltip for the Expand button triggers and stays open

![expand](https://cloud.githubusercontent.com/assets/7585245/17151918/87bb9918-5343-11e6-8b0d-2a8175a878c0.png)

Does not happen if the Details panel is already open when the request is made.

**Comment by AleksueiR** [comment]
This is likely caused by the focus being set to the details panel. Cannot reproduce in 1.1.0.
