### ISSUE TITLE
Mystery pipe on FGP grid record count

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#996]
A pipe appears after the grid record count on the FGP pages.

![pipe](https://cloud.githubusercontent.com/assets/7585245/17152196/d53a0bba-5344-11e6-97e5-5fe70caf2378.png)

Possibly the JOSM Parser has infected our site and is injecting pipes.

**Comment by AleksueiR** [comment]
Caused by a datatable style brought over through the wet tempalate.

**Comment by bkutty** [comment]
No longer an issue. Tested on v1.4.0-7.
